### ISSUE TITLE
 at0: ERROR while getting interface flags: No such device

### ISSUE THREAD

**Issue by Darksleep** [FluxionNetwork/fluxion#10]
### Which version of fluxion are you using?
rev 9

### What distribution of Linux (including the version) are you running it on?
ubuntu 16 64bit and Kail linux 2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
ALFA AWUS036H - (Did work)

### Which is the driver for it?
rtl8187

### Does it support injection ( output of aireplay-ng -9)
No 

### General description of your issue along with the steps to reproduce it
got it to work for one time now it dose not so i dont know what y

at0: ERROR while getting interface flags: No such device
SIOCSIFADDR: No such device
at0: ERROR while getting interface flags: No such device
SIOCSIFNETMASK: No such device
SIOCSIFMTU: No such device
SIOCADDRT: Network is unreachable

**Comment by deltaxflux** [comment]
Well I (hopefully) find the issue, give it a try now.

**Comment by Darksleep** [comment]
Tryed it and it does now work fine that error does not pop up. but now fake wifi dose not show

**Comment by Darksleep** [comment]
What seems to happen is there issue with AP terminal not opening so fake wifi is never made it sometimes work with my built in wifi card but With my ALFA AP window will not open

**Comment by deltaxflux** [comment]
Can you confirm that you are able manually to setup a hotspot using hostapd?
I noticed that you maybe used airebase-ng if use hostapd instead which is more reliable and stable in my optinion.

**Comment by Darksleep** [comment]
I will get back to you in a sec

**Comment by Darksleep** [comment]
While using Ghost Phisher and wifi phisher I can use Hostapd

**Comment by deltaxflux** [comment]
Sounds like a script kiddie

**Comment by Darksleep** [comment]
Ok i think i know what happening it skips a step images to follow

**Comment by Darksleep** [comment]
![imag0014](https://user-images.githubusercontent.com/6968595/27696796-79324d5e-5cea-11e7-9be4-0fff09749dee.jpg)
![imag0015](https://user-images.githubusercontent.com/6968595/27696797-7935f26a-5cea-11e7-91e9-63737492844a.jpg)
![imag0016](https://user-images.githubusercontent.com/6968595/27696799-7937475a-5cea-11e7-80a6-ea168a42e8f1.jpg)
![imag0017](https://user-images.githubusercontent.com/6968595/27696798-793726b2-5cea-11e7-889a-336074710823.jpg)
![imag0018](https://user-images.githubusercontent.com/6968595/27696800-79390810-5cea-11e7-8208-9aede8940f34.jpg)

**Comment by Darksleep** [comment]
The first image is skipped when using my ALFA card so i never able to pick hostapad or airbase

last one is AP window that never pops up when picking my ALFA Card

hope these help

**Comment by deltaxflux** [comment]
Ah because of your chipset. I take a look at the source code as soon as I can.

**Comment by Darksleep** [comment]
Thanks dude Cool software should be added to Kail out of the box

**Comment by Darksleep** [comment]
Calling me script kiddie ?

**Comment by Darksleep** [comment]
I only used said tools as it was quicker for me then setting up full system just to test something

**Comment by deltaxflux** [comment]
Good luck

**Comment by Darksleep** [comment]
K THANKS

**Comment by officiallor** [comment]
The problem happens only when the network essid has spaces
