### ISSUE TITLE
Working but not working ?

### ISSUE THREAD

**Issue by Dylan433447** [FluxionNetwork/fluxion#1006]
KALI LINUX 2020.4   --> LATEST FLUXION 

when i run the Captive portal it runs normally and no strange messages BUT !  no ACESS POINT IS SHOWN on my phone -

NOTICE : EVEN THOUGH NO ERRORS SHOWS UP i DON'T GET DISCONNECTED FROM MY PHONE (I WAS ATTACKING MY ROUTER) SO  The attack shows no errors and also it doesn't work functionally

**Comment by cjb900** [comment]
if your phone is not being disconnected from the real AP there are 2 may be 3 possible causes. 
1) not all AP's are vulnerable to the same deauthing method. I would try one of the other deauthing methods and see if that works
2) the chipset in your adapter may not be properly supported for wifi hacking so is not able to properly deauth and create the fake AP at the same time. 
3) the AP has protection that detects you are deauthing it and then changes the channel it is broadcasting on making deauthing hard. to fix this you would need to use a second/third adapter for target tracking so when your AP changes the channel it is on the deauthing portion of fluxion is able to switch to that new channel and then continue to properly deauth

**Comment by Dylan433447** [comment]
my adapter  Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter

**Comment by cjb900** [comment]
well that is most likely your issue then. RTL chipsets are notoriously problematic for wifi hacking and not recommended. You are going to be better off getting one that is properly supported

**Comment by Dylan433447** [comment]
like what ? give me some examples and the price if you can

**Comment by cjb900** [comment]
here is a list of known adapters/chipsets that will work. I can't give prices that easily as they very from where you live and whats available online around you. https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by Dylan433447** [comment]
is that one works fine ?  Atheros AR9271 802.11n 150Mbps Wireless USB WiFi Adapter F Linux Kali WIN10 ROS

**Comment by cjb900** [comment]
if its in the list of known compatible adapters/chipsets then yes it will work

**Comment by Dylan433447** [comment]
one more thing ,   the evil twins attack works fine on LATEST Airgeddon V10.31 so ..  i don't know why it doesn't work for fluxion but no errors and its fine with airgeddon and its stable too but the only problem is . it doesn't redirect victims to my AP automatically . i swear it was working before in 2019 now it doesn't also option disappeared  strange

**Comment by cjb900** [comment]
well no evil twin attack no mater what tool you use will be able to redirect a victim to your fake AP automatically. the reason being is the real AP is password protected and the fake one is not. so the AP's are different to where no victim will be automatically connected to the fake AP you create.

**Comment by cjb900** [comment]
for why airgeddon works and fluxion doesn't i can't fully say. I know some of the dependencies are shared between the two but not all and they are coded/developed differently. it may be the chipset in your adapter for why airgerddon works and fluxion doesn't 
¯\_(ツ)_/¯

**Comment by Dylan433447** [comment]
Okay maybe it works but i wonder why not all of them even whom close to me arent connecting to the fake ap U THINK MY AP IS TOO WEAK ? COZ OF MY ADAPTER OR WHAT ? IS IT ABOUT THE ADAPTER STRENGTH ? BUT i think signal strength arent that bad i mean the next apartment also he is in CHANNEL 1 FOR SAKE Do u think my adapter would reach that far ? On CH 1?

**Comment by cjb900** [comment]
the way the evil twin attack works is by deauthing the clients from the real AP. then they user had to realize the device was disconnected and not connected to a mobile network if its a mobile device or connected to another band(2.4ghz or 5ghz) if their AP has dual bands. once they are disconnected they then have to try and connect to the real AP and see they can't. its this process where we hope they then see the fake AP when they can't connect to the real AP. once they connect to the fake AP they get the captive portal to put in the password(assuming their device is able to properly load the captive portal).

with all that there are many factors that may cause victims to not connect to the fake AP or load the captive portal. So it is just a waiting game to see if you are able to get their password or not and no way to 100% guarantee you will.
