### ISSUE TITLE
Internet Method

### ISSUE THREAD

**Issue by Dylan433447** [FluxionNetwork/fluxion#1007]
Can you guys add  an INTERNET METHOD option to the attack ?  like THIS ONE 
![Screenshot from 2021-01-12 09-25-23](https://user-images.githubusercontent.com/34538048/104274217-054bec00-54a9-11eb-9be4-455ec24b5fd0.png)
![Screenshot from 2021-01-12 09-25-29](https://user-images.githubusercontent.com/34538048/104274220-067d1900-54a9-11eb-830a-d2274de48e47.png)
![Screenshot from 2021-01-12 09-25-32](https://user-images.githubusercontent.com/34538048/104274222-0715af80-54a9-11eb-9e22-2f3037920a1c.png)

**Comment by cjb900** [comment]
why are you posting questions related to a completely different tool in this github?

**Comment by Dylan433447** [comment]
They're both are scripts for performing an Evil Twins attack

**Comment by cjb900** [comment]
true but they are developed and coded completely separate from each other.
