### ISSUE TITLE
Fluxion not leasing ip addresses

### ISSUE THREAD

**Issue by AhmedBarayez** [FluxionNetwork/fluxion#1009]
After starting captive portal everything is going well but i cannot connect, it's stuck on obtaining ip address but it never do, and no dhcp window is appearing
I only have dns, jammer, hostpad, authenticator
And if i insert static ip it works perfectly
So the dhcp isn't working properly
I'm using laptop hp 14-n011ex

**Comment by cjb900** [comment]
if the dhcp window is not appearing make sure you are running a supported OS like kali or Parrot OS. Any other linux OS may not work out of the box and require additional setup.

**Comment by AhmedBarayez** [comment]
> if the dhcp window is not appearing make sure you are running a supported OS like kali or Parrot OS. Any other linux OS may not work out of the box and require additional setup.

I'm running Ubuntu 20.4.1 LTS
What should i do to make it running

**Comment by cjb900** [comment]
The best think I would suggest is to use a dedicated hacking distro like Kali Linux or Parrot OS. If you insist on using Ubuntu them you can try this https://github.com/FluxionNetwork/fluxion/issues/792 and see if this helps. This is an old issue so i can't say if it will work on the latest version of Ubuntu.

**Comment by AhmedBarayez** [comment]
> The best think I would suggest is to use a dedicated hacking distro like Kali Linux or Parrot OS. If you insist on using Ubuntu them you can try this #792 and see if this helps. This is an old issue so i can't say if it will work on the latest version of Ubuntu.

I downloaded kali and it's working perfectly on it now thanks
