### ISSUE TITLE
fix path on diagnostics.sh

### ISSUE THREAD

**Issue by SiNaPsEr0x** [FluxionNetwork/fluxion#101]
root@kali:~/hack/fluxion/scripts# ./diagnostics.sh  wlan0
./diagnostics.sh: riga 3: lib/InterfaceUtils.sh: File o directory non esistente
[ FLUXION Info ]
grep: fluxion.sh: File o directory non esistente
FLUXION V.

 fix path to ../fluxion/lib

**Comment by MPX4132** [comment]
It's right along with the issues template, or maybe I put it in the FAQ, I already forgot.

**Comment by MPX4132** [comment]
Yeah, it was with the issues template: "Paste the output of `./script/diagnostics.sh`"
You have to run it from fluxion's root directory.

**Comment by MPX4132** [comment]
You're welcome. We do need to come up with a solution to allow it to run from in there, though. I just quickly wrote the script last night.
