### ISSUE TITLE
cat: /tmp/fluxspace/hits.txt: No such file or directory

### ISSUE THREAD

**Issue by Skwipo** [FluxionNetwork/fluxion#1010]
Fluxion in the current master version can't find the /tmp/fluxspace/clients.txt file, but the file exists and has content. the problems occurs if i start the final attack with hostapd.

the errormsg is:

cat: /tmp/fluxspace/clients.txt: File or Directory not found!
cat: /tmp/fluxspace/hits.txt: No such file or directory

version :  FLUXION 6.9
--
wlan0  2.4Ghz // Chipset: Qualcomm Atheros AR9285

**Comment by cjb900** [comment]
not sure what OS you are using but i can run fluxion on the latest kali 2020.4 with all the updates with no issues. Its possible it may be your chipset as thats not one i'm familiar with for if it is properly supported for wifi hacking. You could try reinstalling hostapd and see if that helps at all.

**Comment by Skwipo** [comment]
sorry but its working its just some errors while user put worng password but when i put the right password the scritp saved it

**Comment by amsaqib2005** [comment]
Hi
I am getting the error on final results

  CLIENTS ONLINE:ace/clients.txt: No such file or directory

I am using Kali/Linux latest version. 

please advise the solution. thank you
