### ISSUE TITLE
Pyrit Not Installing

### ISSUE THREAD

**Issue by Shivanshu10** [FluxionNetwork/fluxion#1011]
Cannot install pyrit
Cannot install pyrit on kali linux 2020

**Comment by cjb900** [comment]
the latest version of fluxion is 6.9. if you are getting a message that pyrit is needed then you are not using the latest version because pyrit was removed sometime last year or so. I would download a new copy from github.

**Comment by Shivanshu10** [comment]
I updated the repo and it worked
Thanks
