### ISSUE TITLE
 phishing page Not show On Mobile

### ISSUE THREAD

**Issue by Dakshkanani** [FluxionNetwork/fluxion#1012]
Helppp? im having a problem with fluxion!!! Everything starts beautiful, even the Fake AP... but when you connect devices to fake AP, Captive portal doesn’t show on the device (phishing page)!

**Comment by cjb900** [comment]
How is anyone supposed to help you with out knowing your set up. 
What OS are you using?
are you running said OS in a VM?
What wifi adapter/chipset do you have?
What type of mobile device are you trying to connect to the fake AP?

In my testing everything works. I get the captive portal on my 2 samsung phones and my iPhone with no issues.

**Comment by Dakshkanani** [comment]
Iam use Linux In Viruatbox
My wifi adaptor Run Perfectly
My Phone Is Redmi Note 4

Plz Help How Solve This Problem pray And Create Fake Ap Mobile Automatically Disconnected Fake Ap

**Comment by cjb900** [comment]
well telling me your wifi adapter runs perfectly does not help. Not all wifi adapters are properly supported for evil twin wifi hacking which is what fluxion does. thats why i asked what adapter/chipset you have. Also wifi hacking in a VM is known to be unreliable so its possible using a VM could be part of your issue as well

**Comment by Dakshkanani** [comment]
My wifi Chep   MT7601U
