### ISSUE TITLE
Filter access points?

### ISSUE THREAD

**Issue by attilius743** [FluxionNetwork/fluxion#1014]
Hi,
first of all, thank you so much for your service.
When fluxion scan all access points, he found many of its, and there are many people connected.
Is not possible to scroll the list of connections, that is not completely visible.
There is a way to filter the list by connection power, or choosing a sub list of bssid?
Thank you!!

**Comment by attilius743** [comment]
have you closed my request without an answert because is not possible to do nothing for my problem?

**Comment by cjb900** [comment]
This was closed because what you are asking would be a feature request not an issue and respire re-coding how fluxion scan and displays networks. You would be better off re-coding fluxion your self to do this or look into running airodump-ng manually to get what you want.

**Comment by attilius743** [comment]
Thank you for your answer, I will try with airodump-ng.
However I inserted the question in the right section. Here an attachment to show it. I don't know why it is marked as an issue.
![image](https://user-images.githubusercontent.com/65614192/106004403-78617f00-60b3-11eb-95f9-00bc7af03db2.png)

**Comment by attilius743** [comment]
ah ok, I thinked that you would said something like: "add this parameter calling fluxion". or: "look this file.sh and try to add some command like this".
But I like also your solution about airodump-ng. It's a support answer this for me.
Thank you a lot
