### ISSUE TITLE
CaptivePortal and Handshaking are not working

### ISSUE THREAD

**Issue by MajorRaccoon** [FluxionNetwork/fluxion#1015]
So, i have usb ac-54, with driver RTL88x2BU on my vmware.
When I am trying to start captive portal, it says that it "can't launch application for interface, returning", and when i launch Handshaking one windows only says "waiting for beacon frame" IDK what to do with it, please help

**Comment by cjb900** [comment]
That chipset does not properly support the modes needed to be used in fluxion. It does not support VIF. you are going to have to either replace that adapter with one that properly supported or get a second one and use 2 adapters.

**Comment by MajorRaccoon** [comment]
Well, and what adapters can you recommend?

**Comment by cjb900** [comment]
Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by MajorRaccoon** [comment]
Okay, thanks
