### ISSUE TITLE
Jammer still don't work (Latest version)

### ISSUE THREAD

**Issue by anthonybkt** [FluxionNetwork/fluxion#1019]
Hello, I have a problem with the deauth with Fluxion. 
Whether I choose MDk4, MDk3 or aircrack-ng it doesn't want to deauth the wifi devices I chose.

Hardware : 

2 Wifi card : 

Alfa Network AWUS036NH
and
ALFA Network AWUS036NHA

Operating system: Kali linux

I tested on 2 computer :
Laptop macbook pro 2013 (dual bot)
and
Computer ryzen 5 3600x 

PLEASE HELP !

**Comment by cjb900** [comment]
Have you tried deauthing our side of fluxion to see if it works there? Also its possible that if the AP you are attacking has 802.11w enabled that makes deauthing very hard if not impossible. Also there is no way to know if an AP has 802.11w or not unless you have admin access to the AP.

**Comment by anthonybkt** [comment]
Do you mean that I have to try on another network?

**Comment by cjb900** [comment]
yes if everything you have tried to deauth it is not working and this is not an AP you have access to there is nothing anyone can do to make deauthinig work

**Comment by anthonybkt** [comment]
I try to deauth the same wifi with JAM WIFI on mac os and it's work.
So the wifi is not the problem...

**Comment by cjb900** [comment]
well like i said try deauthing out side of fluxion and see if that works or not. I've used fluxion to deauth many AP's with no issues.
If you can't get fluxion to work try airgeddon and see if that works for you.

**Comment by anthonybkt** [comment]
I will try it, does airgeddon have french page ?

**Comment by cjb900** [comment]
I can't recall off the top of my head. But it may very well have French a captive portal

**Comment by anthonybkt** [comment]
Ok, I just try on the rapsberry pi 3 and still dosen't work........ witch version you have ? Can you send me your please ?

**Comment by cjb900** [comment]
Version of what? airgeddon, fluxion Kali?

**Comment by anthonybkt** [comment]
If you can, I would like to have your kali version and the fluxion version please

**Comment by cjb900** [comment]
the latest version of Kali 2020.4 with all the updates and the latest version of fluxion 6.9

**Comment by anthonybkt** [comment]
Rah I have the same version what's wrong with me ? :ccc

**Comment by cjb900** [comment]
no idea. Have you even attempted to deauth out side of fluxion manually?

**Comment by anthonybkt** [comment]
I will try now but all my wifi card will be use by fluxion...........

**Comment by cjb900** [comment]
I did not ask you to do it while fluxion was running. Just to try deauthing nothing else out side of fluxion to see if that works or not.

**Comment by anthonybkt** [comment]
Ok, I try with aireplay and it's not work...

**Comment by cjb900** [comment]
ok so thy with mdk3/4 and see if that works. If that fails then its either something with your setup or the AP you are attacking. If you haven't you can try airgeddon and see if that works

**Comment by anthonybkt** [comment]
Oh no !!! MDK3 and MDK4 don't deauth to !! I will try tomorow for set up correctly

**Comment by anthonybkt** [comment]
Did you install aircrack-ng, mdk3, mdk4 with the fluxion tool (./fluxion.sh -i) or do you download it before ?

**Comment by cjb900** [comment]
it should not matter how they are installed. Whether you do it before or have fluxion do it. I've done it both ways in the past with no issues deauthing. One thing you can try is run airmon-ng check kill before starting fluxion and see if that helps any

**Comment by anthonybkt** [comment]
You were right ! My router use 802.11w so I can't jam it with mkd3, mkd4, aircrack-ng....

But I found a powerfull program, and it can jam with 802.11w it's JAM WIFI

**Comment by anthonybkt** [comment]
Do you have any Idea for check if a AP have 802.11w enabled ?

**Comment by cjb900** [comment]
with out having admin access to an AP there is no way i know of to see what bands an AP is running on.

**Comment by anthonybkt** [comment]
Ah........ Thanks for all you solve my problem. 
My last question is : How can have wifi password on 802.11w AP without brute force ?

**Comment by cjb900** [comment]
if deauthing via fluxion or airgeddon does not work you would have to use the other tool you found to deathuth it and then hope the victim connects to the fake AP you create.

**Comment by anthonybkt** [comment]
Understand, I appreciate thanks for are very nice !

**Comment by usuarionuevor** [comment]
I use this https://github.com/zartaz/Mdk4_deauther 
in my case for different reasons, for me fluxion deauth works, but fails to track channel changes and that tool works perfect here hope it helps you too

**Comment by cjb900** [comment]
@usuarionuevor all that bash script is is just a wrapper for the real mdk4 which is what fluxion already had in it. if an AP has 802.11w enabled(which not all AP's do) that most likely will not work. Also fluxion does have the ability to track an AP to see if the channels are changing when deauthing. Its called target tracking. You just need a second and or third adapter to use it depending on your set up.

**Comment by anthonybkt** [comment]
Are you sure that is impossible to deauth 802.11w ??

Or maby a orther solution for kick device from the protected AP ?

**Comment by cjb900** [comment]
Well i don't have any AP's near me that i can't deauth or that i know have 802.11w. So i can only go by from what i've see from others. As i mentioned before you can try using airgeddon and see if deauthing there works or not. It does use the same mdk4 and airplay but also has an additional deauthing method that may work.
