### ISSUE TITLE
FAQ Fix

### ISSUE THREAD

**Issue by SiNaPsEr0x** [FluxionNetwork/fluxion#102]
export FLUXIONWIKillProcesses=1; export FLUXIONWIReloadDriver=1 ./fluxion.sh

fix with:

export FLUXIONWIKillProcesses=1; export FLUXIONWIReloadDriver=1; ./fluxion.sh

**Comment by MPX4132** [comment]
Ah, thanks for letting me know. It's been fixed.

**Comment by SiNaPsEr0x** [comment]
this best run!

**Comment by SiNaPsEr0x** [comment]
mi script for you is:
on root homedir:
#Start
#export FLUXIONDebug=1;   #DEBUG
export FLUXIONWIKillProcesses=1; export FLUXIONWIReloadDriver=1; #KILLA SERVIZI PARALLELI
cd hack/fluxion/;
#git clone --recursive git@github.com:FluxionNetwork/fluxion.git;
git pull;
git pull --recurse-submodules;
./fluxion.sh
