### ISSUE TITLE
Fluxion doesn't work

### ISSUE THREAD

**Issue by Eladtopaz** [FluxionNetwork/fluxion#1020]
#### Summary
I am currently using Asus Windows 10 computer with a Kali Linux-2020.4 Version on Oracle VM VirtualBox.
Plus I have an external Wi-Fi adapter: ALFA AWUS036NHA.
I have installed the latest version today, using the git clone, on the virtual machine. It is written that it is Fluxion 6.9

Whenever I use the attack Handshake Snooper, it doesn't find the handshake.
I am using the same adapter for a wireless interface for target tracking.
I use aireplay-ng as the deauthentication attack
And cowpatty for the verification.
Every 30 seconds, and Synchronously.
Now here is the bug:
It is searching for a handshake in the chosen Wi-Fi (my own home network) but it just never finds it. Even if I take my iPhone/PC and turn on and off the Wi-Fi several times, it never finds the handshake!
So I am getting the handshake manually by airodump-ng, and deauth small attack, and then I am going for attack number 1 -

Captive Portal.
Here is the second bug:
I chose the Wi-Fi adapter for both the wireless interface for target tracking and the access point.
I chose mdk3 for the deauthentication attack. (Tried mdk4 too)
I chose Rogue AP - hostapd.
hash - cowpatty.
I am entering the correct path.
I chose cowpatty verification.
Create an SSL.
Disconnected (Actually this one I tried disconnected and emulated and the same result)
11 for Generic Portal (Tried 7 too)

Here is the bug:
It doesn't let me get into the "new network" and even if it is let me get into it, I open Youtube or something, and it just says "no internet connection" it doesn't ask me for a password.

##### What is the current behaviour?
The Snooper doesn't work at all.
The evil twin attack doesn't work, no web page is shown, doesn't even let people get into the "new network."

#### How to reproduce
Just follow the steps I did exactly and see it will happen to you too. 

##### If the current behaviour is a bug, please provide the steps to reproduce it.
Just follow my steps 

##### What do you think the expected behaviour should be?
In the Spooner attack, I expected it to show in yellow on the screen when I find the handshake, stop and give me to save it.
In the  Captive attack, I expected to go into the network, open the browser and a password request will be shown.

##### Specs
There is no output I stopped both of those attacks after I ran the two, 1 hour each and tried several options and settings and nothing happen in the attacks.

**Comment by cjb900** [comment]
The issue you are having is that you are using the same adapter for target tracking that you are trying to use for deauthing and creating the fake AP. That will not work. If you actually need to use target tracking(not all AP's change their channels when you deauth them) you would need a second adapter.

**Comment by Eladtopaz** [comment]
Ok, but why the Snooper didn’t work?
And, if I have only 1 adapter, how can I use Fluxion to hack a WiFi password? Is there even an option to do it? I saw someone who used an old version of Fluxion maybe even Fluxion 2 and he did a password crack with 1 adapter...

**Comment by cjb900** [comment]
the snooper does work it just requires an additional adapter to use it. I would just skip that option if you only have one adapter. If you know that the AP you are attacking changes its channel when deauthing you would need to get a second USB adapter to use it in a VM

**Comment by Eladtopaz** [comment]
I still don’t understand how in the past version someone did all that with 1 adapter... why isn’t it possible now?
And if the AP doesn’t change it channel? (Because I am pretty sure it doesn’t) how do I need to make the setting of that attack for this to work with 1 adapter?

**Comment by cjb900** [comment]
It could have been the adapter they were using, the driver of that adapter or the kernel version they had in what ever OS they were using. But everyone I've seen tying to use target tracking with one adapter has run into issues. That's why a second or third adapter is needed to properly use it.

**Comment by Eladtopaz** [comment]
Ok, last thing -
You said if the AP doesn’t change its channel, I can do this with one adapter, so, HOW?😅

**Comment by cjb900** [comment]
the target tracking has an opting to skip it(don't recall the number option at the moment).

**Comment by Eladtopaz** [comment]
Thank you so much, it is working now.
