### ISSUE TITLE
Error when stating AP using mt7601u Adapter

### ISSUE THREAD

**Issue by Choudroi00** [FluxionNetwork/fluxion#1022]
In the last step before the attack began (all requirements have been entered) the window freezes and nothing happens afterwards. I guess the problem only happens with the MT7061U Chips. if You can fix this issue in short time I will be thankful .

**Comment by cjb900** [comment]
that chipset is a known one that does not work properly. There is no way i know of to get that chipset to work(i have seen many try and fail to get that chipset to work). You will need to either replace that adapter or get a new one. here is a list of known adapters/chipset that will work

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by Choudroi00** [comment]
Thanks and Wow really this is a fast reply . Really, this problem only
occurs when using this device, but when switching it to any other device it
Works!, even some are not mentioned in your list

**Comment by cjb900** [comment]
that list is not a list of every known chipset/adapter that will work. Its just a list of adapters/chipsets that have been tested with airgeddon(similar wifi hacking tool to fluxion) and known to work fully. So it is very possible that there are others out there that have not been tested that will fully work.
