### ISSUE TITLE
Hidden Network

### ISSUE THREAD

**Issue by vet-murat** [FluxionNetwork/fluxion#1027]
### Feature Request

1. Can hidden networks be added to find SSID?
2. When the modem is reset, can the name of the fake network change?
Thank You Us :)
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

**Comment by strasharo** [comment]
1) Duplicate https://github.com/FluxionNetwork/fluxion/issues/1024
2) No
