### ISSUE TITLE
Victim stuck at obtaining ip address

### ISSUE THREAD

**Issue by enrico8055** [FluxionNetwork/fluxion#1030]
May i know how to solve it? 

I use the newest version

**Comment by cjb900** [comment]
How is anyone going to be able to help you if you don't give the information needed. 
What OS are you using?
How do you have said OS installed(on hardware or in a VM)?
What wifi adapter and chipset are you using?
Are you getting any errors in any of the fluxion windows?
What device are you trying to connect to the fake AP?

**Comment by enrico8055** [comment]
I have try in kali 2020.4 and ubuntu 20.4, and rhe problem is same
I use native OS, not in VM
I use realtek for the adapter, i think the adapter isnt the problem because before i update the fluxion to 6.9, it work properly
The victim use Redmi note 8, Redmi note 9
I try in I3 540 PC and AMD A4 Laptop

**Comment by cjb900** [comment]
what is the exact chipset you have. Can you also share a screen shot of the open windows in fluxion?

**Comment by enrico8055** [comment]
Qualcomm Atheros AR9485 Adapter
For screenshot may be tomorrow because in my country already 12 PM

**Comment by cjb900** [comment]
ok well Atheros AR9485 is completely different than realtek. when you get the screen shots can you also send one of the output of this. ```iw list | grep "Supported interface modes" -A 8```

**Comment by enrico8055** [comment]
i have realtek, jht, and d-link also
ok tq for your advice i wi try tomorrow

**Comment by enrico8055** [comment]
![16168152414077138944389429890004](https://user-images.githubusercontent.com/54464654/112708712-3c496f80-8ee6-11eb-8dc9-9cf0bbb13e39.jpg)

**Comment by enrico8055** [comment]
![16168153247851401089543220907562](https://user-images.githubusercontent.com/54464654/112708751-6bf87780-8ee6-11eb-92d1-a0360dfa913d.jpg)

**Comment by cjb900** [comment]
can you run this and post the output because that doesn't look like any current version of kali i've seen ```uname -a && lsb_release -a```

**Comment by enrico8055** [comment]
now i use ubuntu 20.04, yesterday my kali not work, i try to use another os but also not work

**Comment by cjb900** [comment]
ya Ubuntu is not going to you very well with flixion. Because Ubuntu is not a dedicated hacking OS like kali so does not have all the stuff built in to properly work with wifi hacking. You would be better off switching back to kali

**Comment by enrico8055** [comment]
ok may be i will switch again
