### ISSUE TITLE
Unable to start captive portal ,

### ISSUE THREAD

**Issue by amanhu** [FluxionNetwork/fluxion#1031]
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by cjb900** [comment]
How is anyone going to be able to help you if you don't provide any of the information we require.

**Comment by Fone91** [comment]
> How is anyone going to be able to help you if you don't provide any of the information we require.

Can you help me? I have the issue. I got the handshake. When i choose option Captive Portal, Fluxion notify that "Unable to start captive portal interface, returning". My chipset adapter : RTL8812AU.

![Untitled](https://user-images.githubusercontent.com/77982417/113724723-d5655b00-971c-11eb-9aa0-6c851c86d787.png)

**Comment by cjb900** [comment]
your issue is going to be the adapter/chipset you have. That chipset does not support VIF meaning you will not be able to deauth and create the fake AP at the same time. There is no way to fix that adapter to get it to work. You will have to either get a second adapter to use with it or get a new one that supports Monitor mode, AP mode and VIF.

**Comment by Fone91** [comment]
> your issue is going to be the adapter/chipset you have. That chipset does not support VIF meaning you will not be able to deauth and create the fake AP at the same time. There is no way to fix that adapter to get it to work. You will have to either get a second adapter to use with it or get a new one that supports Monitor mode, AP mode and VIF.

Thank you so much. Can you recommend me which chipsets support all Monitor mode, AP mode and VIF at same time on 5GHz band?

**Comment by cjb900** [comment]
any of these adapters/chipsets will work 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. This card has issues with Rpi2/3. The recommended Linux kernel version is 5.3 or greater)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)
