### ISSUE TITLE
Fluxion updates my kali 

### ISSUE THREAD

**Issue by Devilzeyez** [FluxionNetwork/fluxion#1033]
Hi there been using fluxion for a while now, and iwas working perfectly.
i installed the new version "6" and it messes up my kali os. i uses a custom version 2020 and after the update it updates kali to the new version.... 
also the new version 6 do not get the handshakes !!

plz advise

Regards

**Comment by cjb900** [comment]
If you are using a version of kali that is not the original one from kali.org there is no way to tell what updating fluxion could have done. I can say if you were using a standard version of kali updating fluxion should not have had any affect on kali other then possibly making changes to the dependencies it used. If you can't get fluxion to work you may be better off trying the latest version of kali 2021.1 and see if that helps. the latest versions of both kali and fluxion work on my end with no issues.

**Comment by Devilzeyez** [comment]
Will try, is there a way to get the older version 5?

**Comment by cjb900** [comment]
its not on the official github page for it so you would have to see if you can find it online somewhere
