### ISSUE TITLE
Please help to make a captive portal run with fluxion

### ISSUE THREAD

**Issue by federson1** [FluxionNetwork/fluxion#1034]
Please can someone help me with making a captive portal run with fluxion? I don't know how to make  jss query and the css. https://mega.nz/folder/ax0xiKJB#nQcWeiDUzWUqS-dpIvpKog (It contains the httml, styles, images and fonts)

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/wiki/Preparing-portals-for-fluxion
