### ISSUE TITLE
Language: It's not the same Spanish (of Spain) than Latinamerican Spanish

### ISSUE THREAD

**Issue by Noobsaibot73** [FluxionNetwork/fluxion#1035]
Fluxion will not work properly in Spain because the spanish used in Fluxion, it's not the spanish of Spain but Latinoamerican spanish
![house](https://user-images.githubusercontent.com/83715020/117170623-7736a100-adca-11eb-9370-1979f51d5a3b.png)
![house1](https://user-images.githubusercontent.com/83715020/117170646-7c93eb80-adca-11eb-8ec1-9555e9ce0f84.png)
![Errorhtml](https://user-images.githubusercontent.com/83715020/117170845-a5b47c00-adca-11eb-82ce-4a4bad3dd938.PNG)
![Finalhtml](https://user-images.githubusercontent.com/83715020/117171397-1e1b3d00-adcb-11eb-9200-06ba914a9423.PNG)

Take care of that, this won't be credible here in Spain

**Comment by strasharo** [comment]
Just create a pull request with your proposed changes, we have no native Spanish speakers available.
