### ISSUE TITLE
"[FLUXION AP Authenticator]" Xterm window does not close automatically.

### ISSUE THREAD

**Issue by averov90** [FluxionNetwork/fluxion#1040]
#### Summary
The **Xterm** window "**[FLUXION AP Authenticator]**" never closes automatically.

##### What is the current behaviour?
Currently, the Xterm window titled "[FLUXION AP Authenticator]" never automatically closes. Neither with manual closing, nor with reopening with a sufficiently long attack.
Even when I close this window manually, it doesn't close the first time, but the second. Obviously something is wrong.

#### How to reproduce
It is enough to select after the full launch of the attack, the evil twin, select the menu item to complete the attack. All windows will close except for the "[FLUXION AP Authenticator]" window.

##### What do you think the expected behaviour should be?
I guess the correct behavior would be to automatically close the persistent [FLUXION AP Authenticator] window. This is especially true for long-term attacks when several dozen xterm windows can accumulate in the system.

**Comment by xpz3** [comment]
https://github.com/xpz3/fluxion/commit/5bc414b3fa9aa6f678d394b4e5b76aae9ae579d2.patch
Try this patch

**Comment by strasharo** [comment]
@xpz3 Could you, please, create a pull request? Thank you!

**Comment by xpz3** [comment]
Done

**Comment by xpz3** [comment]
Force pushed new commit. Earlier, I accidently ran kill inside a for loop.

**Comment by strasharo** [comment]
Thanks!
