### ISSUE TITLE
Minimized xterm during handshake snooping to utilize workplace

### ISSUE THREAD

**Issue by oliverbob** [FluxionNetwork/fluxion#1044]
How do I add this line in fluxion.sh or attack.sh?

`for id in $(xdotool search --sync --class xterm | head -10); do xdotool windowminimize $id; done`

Reference: https://www.guru99.com/introduction-to-shell-scripting.html

I'm using version 6.9

The goal is to start xterm minimized so that I can multitask on the same screen/workplace (in kali). I'm asking this because I tried to bring fluxion to another workplace, but it keeps popping up to the active workplace when snooping for handshake.

Any ideas?

Thanks

**Comment by strasharo** [comment]
Just use a virtual desktop instead.

**Comment by oliverbob** [comment]
@strasharo I appreciate your input but there is a huge downside performance to that solution. I want something native to the application. Please let's keep this open for others to show their solution.

Thanks.
