### ISSUE TITLE
REQUEST GOOGLE DENMARK CHANGE TO ENGLISH LANGUAGE.

### ISSUE THREAD

**Issue by hackerz2929** [FluxionNetwork/fluxion#1045]
I just want u change google denmark captive portal gateway to english language. Because.my client wifi will confious when that fake website captive portal in denmark. Need to change google demark(46) to english. Only google denmark stable with my interfaces.. please update only google denmark portal to english language

**Comment by cjb900** [comment]
No one here is going to change this for you. If you want it changed you will need to do it your self. If you want to make your own portal you can find information here https://github.com/FluxionNetwork/fluxion/wiki/Preparing-portals-for-fluxion

**Comment by hackerz2929** [comment]
I do not have good html coding script..just teach me for change to
english..can you give tutorial?

**Comment by cjb900** [comment]
https://lmgtfy.app/?q=fluxion+custom+captive+portal

**Comment by hackerz2929** [comment]
Can i change manually to your folder sites google denmark to english or not? Or i need to built again?

**Comment by cjb900** [comment]
you can just modify what is there to fit what you want.

**Comment by hackerz2929** [comment]
Can i change manually to your folder sites google denmark to english or
not? Or i need to built again?

**Comment by cjb900** [comment]
just modify one of the portals already in fluxion to fit what you are trying to do

**Comment by hackerz2929** [comment]
I just want to change Anmelden to sign in(english).
And also title above password box.
Please Enter Your Wifi Password.

**Comment by cjb900** [comment]
so like i said. take that captive portal or any of the other ones in fluxion and modify it to your liking. There is no need to create a completely new captive portal

**Comment by hackerz2929** [comment]
Anmelden i can change to sign in.
But title above password box. I not found where is to change. I want to
change that title to "Please Enter Your Wifi Password". Help me only
this..please buddy

**Comment by cjb900** [comment]
the link i shared above has links in it with instruction on how to modify the captive portals in fluxion. like i said no one here is going to do this for you.

**Comment by hackerz2929** [comment]
Please refer fluxion latest version. Number 46 captive portal. The title
above password box in denmark. I not found where is to change the title to
english. I just found Anmelden. So i can change Anmelden only to english
language.. please take screenshot for me how to change the title above chat
box password.
Refer google denmark captive portal number 46

**Comment by hackerz2929** [comment]
Please look attached file. Seem you give wrong link.

**Comment by cjb900** [comment]
Oh i didn't give the wrong links. One is for if you want to create your own custom captive portal. The other one is for how to search online for what you are trying to do.
