### ISSUE TITLE
fluxion handshake snooper not working

### ISSUE THREAD

**Issue by Nexuss05** [FluxionNetwork/fluxion#1047]
I use an acer aspire one with above installed as zorin os operating system (ubuntu 18.04)

as soon as I run fluxion I run the handshake snooper, select the victim wifi, select "qualcomm atheros AR9485 Wireless Network Adapter (rev 01), select aireplay-ng deauthentication together with cowpatty verification every 30 seconds synchronously. as soon as the attack starts no longer terminates. it seems it fails to capture hash. the deauthentication seems to work. what can I do?

**Comment by cjb900** [comment]
if you are actually getting the handshake but fluxion is not detecting it you can just point fluxion to where the handshake is saved to and move on from there. If you are not getting the handshake than it could be that there are no clients on the AP you are attacking or your deauthing may not be working. Either do to your adapter/chipset or the type of deauthing you chose.
