### ISSUE TITLE
Experiment to Fluxion fake AP. Client can connect after 15minute running fake AP

### ISSUE THREAD

**Issue by hackerz2929** [FluxionNetwork/fluxion#1048]
I had do experiment😊😊.please fix that client can connect after 1second running fake Ap

**Comment by cjb900** [comment]
not sure i understand what you are asking. If the client can connect to the fake AP what are you expecting to have fixed?

**Comment by strasharo** [comment]
Enough with this bs, 5 out of 5 issues opened are nonsense, user banned.
