### ISSUE TITLE
Fluxion Alfa awus036acs

### ISSUE THREAD

**Issue by Klavyeli** [FluxionNetwork/fluxion#1050]
Fluxion 2.0 Since my old network card does not support 5.0 GHz frequency, I purchased an Alfa awus036acs card, it supports monitor mode but flux does not work.
![Ekran görüntüsü 2021-05-27 191621](https://user-images.githubusercontent.com/38491552/119862617-5c66d080-bf21-11eb-9c6f-af2837bb9503.jpg)

**Comment by cjb900** [comment]
The RTL8811AU chipset in the awus036acs by its self will not work with fluxion. RTL chipsets are notoriously problematic for wifi hacking. You would have to use your old network card along with the awus036acs to get fluxion to work.
