### ISSUE TITLE
Error when executing the last operation of choice

### ISSUE THREAD

**Issue by luscafter** [FluxionNetwork/fluxion#1052]
bash: /tmp/fluxspace/captive_portal_authenticator.sh: No such file or directory

**Comment by cjb900** [comment]
If a file is missing that would probably mean that fluxion was not download properly. I would try re-download it

**Comment by luscafter** [comment]
> If a file is missing that would probably mean that fluxion was not download properly. I would try re-download it

Really, bro! I will download and try again :D
