### ISSUE TITLE
clients.txt: No such file or directory

### ISSUE THREAD

**Issue by usuarionuevor** [FluxionNetwork/fluxion#1055]
FREEZES at starting captive portal... `clients.txt: No such file or directory`

![20210615_121218](https://user-images.githubusercontent.com/35457371/122036484-eb099780-cdd3-11eb-9224-286b1b8f7da6.jpg)

- Kali 2021.2 full upgraded 2021-06-15
- Latest fluxion, checked for updated 2021-06-15
- using `airmon-ng check kill`

Specs:

not used (wlan0):
![Screenshot_2021-06-15_12_33_03](https://user-images.githubusercontent.com/35457371/122039811-57d26100-cdd7-11eb-8794-1acd57e1785e.png)

target tracking: AWUS036ACM - MT7612U
![Screenshot_2021-06-15_12_38_24](https://user-images.githubusercontent.com/35457371/122039867-691b6d80-cdd7-11eb-9792-a4d86591f1d7.png)

jamming: AWUS036NH - RT3070
ap: AWUS036NH - RT3070
![Screenshot_2021-06-15_12_36_43](https://user-images.githubusercontent.com/35457371/122039906-79334d00-cdd7-11eb-9d8a-79f8beda7eec.png)
![Screenshot_2021-06-15_12_37_55](https://user-images.githubusercontent.com/35457371/122039913-7b95a700-cdd7-11eb-8457-2c5ed5670492.png)

**Comment by usuarionuevor** [comment]
also tried with one card for each interface, and switched AP-target tracking-deauth to see if there's any specific problem with any of them or with any of the cards but same result, fluxion auto deauth is not working, the only way to make it work is by skip target tracking and use static channel.

Using fluxion for AP with static channel and the app "wifi-deauther" does the job but it would be nice if fluxion worked all-in-one. I'll check airgeddon since it seems to be maintained and more polished.

**Comment by usuarionuevor** [comment]
@strasharo can you say at least why you closed this?

**Comment by cjb900** [comment]
this was probably closed because no one here is able to reproduce your issue and you stated at the end of you last post that you were going to try another tool airgeddon. 

Regarding your issue though, one think you can try and see if it helps is to use one adapter AWUS036NH - RT3070 and start fluxion with ```./fluxion.sh -k``` and see if that helps with your issue.

**Comment by usuarionuevor** [comment]
you mean AWUS036NH for target tracking and AWUS036ACM for jamming&AP ?

**Comment by cjb900** [comment]
Are you even sue the AP you are attacking changes its channel its on when you deauth. If it doesn't that is most likely why you are having issues trying to use it.

**Comment by usuarionuevor** [comment]
> Are you even sue the AP you are attacking changes its channel its on when you deauth. If it doesn't that is most likely why you are having issues trying to use it.

Yes it does, all modern routers I see changes the channel "often" even if not attacking, but even if it had fixed channel like ancient routers shouldn't it work anyway? I mean I have the AWUS036NH just to check what channel is in...

tried `./fluxion.sh -k` but same result, handshake snooper works fine btw (with normal `./fluxion.sh` I mean),

PS: I'm currently using auto-deauther tool by this author https://github.com/zartaz/ but he deleted the git... I did some tweaks I'm not sure if I can share his code?
