### ISSUE TITLE
I Need Help.

### ISSUE THREAD

**Issue by ja3ferr** [FluxionNetwork/fluxion#1059]
|    Q        |   A
|------------ | -----
| Version     | 6.9

#### Support Question
Hello im new here and i have this problem when i try to select a wireless interface for target searching i nothing happen when i choose option 1/2 it just give me two more options 1 repeat / 2 back and its completely usless.

https://user-images.githubusercontent.com/88549315/128534941-be22b8fc-d981-4f71-b34b-2865f2c7eaa9.mp4

**Comment by cjb900** [comment]
Well for one if the version in your description is right you are using a very old version of fluxion. the latets is 6.9 not 4.10. Second i see that you are using a VM. If you do not have a USB wifi adapter connected to the VM it will not work. VM's are not able to use the built in wifi adapter in a computer which would be why you are probably not seeing any interface options. You need a USB wifi adapter that supports monitor mode, AP mode, and VIF. Alternatively if the computer you have has a built in wifi adapter that supports all these modes you can run kali from a live USB.

**Comment by ja3ferr** [comment]
@cjb900 thx for ur time, im using 6.9 u can see it on the video sry about the description part im not using 4.10, yes i have USB wifi adapter and my monitor does not support it im new with kali im just checking youtube and trying new stuff idk what's the soloution should i juste download kali without VM virtualbox or what should i do :c

**Comment by cjb900** [comment]
well if the USB wifi adapter you have is not supported by your computer/OS (which i find hard to believe) the only thing you can try is to either dual boot kali along side Windows or run it from a live USB and see if you can get the USB wifi adapter to work there. For it to properly work with fluxion though it has to support monitor mode, AP mode, and VIF as not all wifi adapters support all these modes.

**Comment by ja3ferr** [comment]
![image](https://user-images.githubusercontent.com/88549315/128548677-194d4274-1fdc-4b47-99fe-91425bcdeacf.png)

**Comment by ja3ferr** [comment]
bro the USB wifi adapter working 
![image](https://user-images.githubusercontent.com/88549315/128548928-f709edfd-2f56-4c75-97c0-db2c0284fc20.png)

**Comment by cjb900** [comment]
ok well you mentioned in your last post "yes i have USB wifi adapter and my monitor does not support" I took this as it not being supported by your computer/OS. Sorry for any confusion. You do have to actually tell the VM to connect and use that USB wifi adapter. Just plugging it into the computer does not automatically connect it to the VM to where it can be used by kali.

**Comment by ja3ferr** [comment]
Okey thx for the help i will check the youtube about this part 'tell the VM to connect and use that USB wifi adapter' cause like i said im new but thx i got the idea <3.

**Comment by ja3ferr** [comment]
Thank you soo much for the help, All gucci now @cjb900 @

**Comment by ja3ferr** [comment]
Yoo do you have any idea about this problem too :( it gets stuck always

https://user-images.githubusercontent.com/88549315/128556736-17ee03db-9cd8-4721-8861-e12f93e717d9.mp4

**Comment by cjb900** [comment]
As i mentioned before your USB Wifi adapter has to support monitor mode, AP mode and VIF. that is most likely being caused by your adapter not supporting AP mode or VIF. VIF is the ability of a wifi adapter to be able to deauth and create a fake AP ad the same time. This is not something that all wifi adapters/chipset support. If you run this in a new terminal can you post a screen shot of the output ```sudo airmon-ng && iw list | grep "Supported interface modes" -A 8```

**Comment by ja3ferr** [comment]
![image](https://user-images.githubusercontent.com/88549315/128557569-3ec3512b-8dc7-4275-a80c-838c55a462a4.png)

**Comment by cjb900** [comment]
ya the chipset in that adapter is complete crap. it doesn't support both AP mode or VIF. there is no way to get that adapter to work unfortunately. you will need to get a new adapter that supports monitor mode, AP mode, and VIF

**Comment by ja3ferr** [comment]
Okey thx is this problem only with the USB adapter or i can get this problem with another pc (with wifi card)

**Comment by cjb900** [comment]
this problem is not necessarily specific to this card just any wifi card that does not support all the proper modes will have this or similar issues.

**Comment by ja3ferr** [comment]
![image](https://user-images.githubusercontent.com/88549315/128868435-d12efb18-a258-4944-97ef-b97ace15fc9d.png)
Hello again i got this USB adapter and ithink it supports AP like u see but i got problem in the scanner i cant see any target
![image](https://user-images.githubusercontent.com/88549315/128868581-2ce5babe-949e-4911-8d86-bbdfc7927341.png)

**Comment by ja3ferr** [comment]
I tried with airodump.ng too still 0 detect and it works on the windows btw 
![image](https://user-images.githubusercontent.com/88549315/128870514-6a58e877-1551-4eb9-94ca-c776c21320b0.png)
![image](https://user-images.githubusercontent.com/88549315/128870640-1c1341bc-eed8-4f54-ac8f-249ddef8e800.png)

**Comment by cjb900** [comment]
Well posting screen shots of Windows showing available wifi networks around you is needed or helpful since you already posted that before. What i would do is reboot the VM. unplug and re-plug in the wifi adapter. Make sure it is connected to the VM and then in kali use this command to start fluxion from the directory where you cloned it to and see if this helps. ```./fluxion.sh -k```.

**Comment by ja3ferr** [comment]
i tried all of that and still didnt work :(

**Comment by cjb900** [comment]
Than the issue is either something with your card or your OS. The only thing i can suggest would be to try updating/upgrading everything in kali and see if that helps. If that doesn't make any difference you can try running kali from a live USB and see if it works where or not. If that doesn't work either then you may need to get a different card if you can't get it to work as something with it may be faulty.

**Comment by ja3ferr** [comment]
Now everything working perfect but im Unable to capture wpa handshakes  :(((

**Comment by ja3ferr** [comment]
problems everywhere Sadge

**Comment by cjb900** [comment]
well if the AP you are attacking has no clients connected to it you won't be able to capture any handshakes

**Comment by ja3ferr** [comment]
I tried even on my own wifi still not even getting disconnected and i never got a handshake so I dont think there's no clients, idk bro I did all parts monitor mod  and all the things and tried even different things not only fluxion still didnt got one x( but im trying to find my fault so I can fix it atleast

**Comment by cjb900** [comment]
well if you can't even disconnect clients on your own AP than something somewhere isn't working either with the card or in the OS. Have you tried running kali from a live USB or dual booting it and not running it from a VM? Also when you run fluxion are you running it with ```./fluxion.sh -k``` or are you just running it with ```./fluxion.sh```? Because the ```-k``` kills processes connected to the network manager that can cause issues with wifi hacking tools running properly.

**Comment by ja3ferr** [comment]
nope i didnt try it from life usb, i run fluxion after i do airmon-ng check/kill/start  then i just do ./fluxion.sh. btw i want to delete this kali and the vm do you know from where i can download only kali and will that make any diff?

**Comment by cjb900** [comment]
If you are using the VM image of kail i've not used it personally but the way it is set up should not make any difference for how fluxion runs. I always just use the standard image of kali which has been changed to bare metal and can be downloaded from https://www.kali.org/get-kali/#kali-bare-metal

**Comment by ja3ferr** [comment]
okey i'll try it, btw u said that i should try updating/upgrading kali only by this commands  sudo apt update. sudo apt full-upgrade -y. or there's another thing to update with.

**Comment by cjb900** [comment]
that command should update/upgrade everything in kali except for anything installed that does not use the kali repo. But that will update anything used in fluxion if there is any updates that is.
