### ISSUE TITLE
2021/8/24/23:30,no internet connection found!Run the fluxion.sh script，It prompts no internet connection found

### ISSUE THREAD

**Issue by jackblackjjx** [FluxionNetwork/fluxion#1062]
When i use it ,it is yesterday,the script still can use it,but today i use it,it not works!After run the "./fluxion.sh -i ",it prompts no internet connection found,but i can use google,and my internet enviroment is connection.
I try to delete the old one,and git clone it newer,Also don't work!
I reboot my kali ,apt-get update,apt-get upgrade ,Also don't work!
I change the Time zone ,Also.
What happened it? I searched nothing about it , can you help to solve it?Thanks,bro.

**Comment by cjb900** [comment]
This is not an issue with fluxion but an issue with something in Kali.

**Comment by jackblackjjx** [comment]
Thanks,I found the problem,It's my network's fault,I use usb to let PC get network,changed my network to wifi ,I can connect the internet,It runs now.Thanks again.


| |
Jack Black
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/24/2021 ***@***.***> wrote：

This is not an issue with fluxion but an issue with something in Kali.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
