### ISSUE TITLE
Error CaptivePortalLogin in Android 11

### ISSUE THREAD

**Issue by usuarionuevor** [FluxionNetwork/fluxion#1063]
![Screenshot_20210825-194125_CaptivePortalLogin](https://user-images.githubusercontent.com/35457371/130843379-4fa3a32f-aa9a-402e-b143-a05127314da0.jpg)
Android 11
Kernel: 4.19.127

on desktop PC with windows 10 works OK, only seems to happens on Android

fluxion: latest, kali: latest.

**Comment by strasharo** [comment]
Your android device is not using the DNS provided by fluxion, so it doesn't resolve the captive portal.
