### ISSUE TITLE
Issue: E: Package 'dhcp' has no installation candidate

### ISSUE THREAD

**Issue by dislorth** [FluxionNetwork/fluxion#1064]
I just installed Fluxion on Kali Linux 2019:

                 Site: https://github.com/FluxionNetwork/fluxion                
                      FLUXION 6 (rev. 9) by FluxionNetwork                      
                             Online Version [6.9]

            [*] aircrack-ng...................................... OK.           
            [*] bc............................................... OK.           
            [*] awk.............................................. OK.           
            [*] curl............................................. OK.           
            [*] cowpatty......................................... OK.           
            [*] dhcpd....................................... Missing!           
            [*] 7zr.............................................. OK.           
            [*] hostapd..................................... Missing!           
            [*] lighttpd.................................... Missing!           
            [*] iwconfig......................................... OK.           
            [*] macchanger....................................... OK.           
            [*] mdk4........................................ Missing!           
            [*] dsniff........................................... OK.           
            [*] mdk3............................................. OK.           
            [*] nmap............................................. OK.           
            [*] openssl.......................................... OK.           
            [*] php-cgi..................................... Missing!           
            [*] xterm............................................ OK.           
            [*] rfkill........................................... OK.           
            [*] unzip............................................ OK.           
            [*] route............................................ OK.           
            [*] fuser............................................ OK.           
            [*] killall.......................................... OK.           

         [ Missing dependencies: try to install using ./fluxion.sh -i ] 

But there are some missing dependencies so I'm trying to install them running the command:
**sudo ./fluxion.sh -i** but I'm getting the next error:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package dhcp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'dhcp' has no installation candidate

Dependency installation failed!
Press enter to retry, ctrl+c to exit...
```

I have try already the next commands trying to fix it:
apt-get install isc-dhcp-server
apt-get update
apt-get dist-upgrade
apt-get update --fix-missing

but still the same when I try **sudo ./fluxion.sh -i** command:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package dhcp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'dhcp' has no installation candidate

Dependency installation failed!
Press enter to retry, ctrl+c to exit...
```

What can I do for fixing this issue an get Fluxion ready?

**Comment by yhxiong** [comment]
apt update
sudo apt install isc-dhcp-server
is ok！！！
