### ISSUE TITLE
captive server error

### ISSUE THREAD

**Issue by incred-ishaan** [FluxionNetwork/fluxion#1065]
![Screenshot (30)](https://user-images.githubusercontent.com/70360369/131809671-d8090263-9c72-4f04-9541-3185f057a67f.png)
can anyone please help to resolve this

**Comment by cjb900** [comment]
The reason you can not start the captive portal is the wifi adapter/chipset you have does not support AP mode or VIF. This is not an issue with fluxion but an issue with the chipset and there is no way to fix it other then getting a new card that actually supports all the modes needed (monitor mode, AP mode, and VIF).

**Comment by incred-ishaan** [comment]
thanks a lot for assistance.

**Comment by cjb900** [comment]
Well another thing to note is that RTL chipsets are notoriously problematic for wifi hacking. I've seen many with with RTL chipsets that support all the proper modes have nothing but issues with using them for wifi hacking. getting another adapter would be the only solution here and then just use the 2 adapters in fluxion.

**Comment by incred-ishaan** [comment]
ooh! so thats a tragedy for me only. i have a friend with same adapter and everything works well for him. anyways thanks alot, please see if you can suggest some thing to resolve it.

**Comment by cjb900** [comment]
if it works for your friend the only thing i can suggest would be to make sure everything in kali is up to date. then reboot kali then unplug and replug in your adapter. Make sure its is connected to the VM and run kali with ```./fluxion.sh -k```

**Comment by incred-ishaan** [comment]
i have tried everything. nothing works. he also did the same thing. but he has 2 separate adapters. he never tried on a single rtl adapter. i guess my adapter is unable to support both the modes at one time. because separately all the modes are working fine, its only in this attack, captive server is unable to start.

**Comment by cjb900** [comment]
Yes RTL chipsets even if they support all the proper modes always seem to have issues if used on their own. You will have to get a second adapter either the same one or one that is properly supported for an evil twin attack and able to properly support VIF

**Comment by incred-ishaan** [comment]
can you please suggest one! that is the cheapest and works perfectly well. i am just a beginner and learning things for educational purposes. thank you.

**Comment by cjb900** [comment]
I can't say which one is the cheapest. That's all going to depend on where you live and whats available around you or online. But here is a list of known good adapter and chipsets that will work with little to no issues. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH (2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)

**Comment by xpz3** [comment]
> can you please suggest one! that is the cheapest and works perfectly well. i am just a beginner and learning things for educational purposes. thank you.

Just buy another v2/v3 card and use both with fluxion. One for ap another for deauth. Your card doesn't support vif. So just one won't work. If you use one card, only ap or deauth will work at a time

**Comment by incred-ishaan** [comment]
what is this vif? i searched a lot but find nothing, what is its fullform

**Comment by xpz3** [comment]
> what is this vif? i searched a lot but find nothing, what is its fullform

vif standa for virtual interface. in simple words, its the ability of a chipset to perform more than one mode at a time. for evil twin attack you need two modes- monitor mode for deauth and master mode for hosting fake AP. some cards support vif so that we can create these two interfaces virtually on a single hardware. if vif isnt supported, you'd need two separate cards that support the required individual interface modes.
