### ISSUE TITLE
FLUXION EVIL TWIN AP NOT CONNECTING 

### ISSUE THREAD

**Issue by HUBBLEGMR** [FluxionNetwork/fluxion#1072]
I AM USEING KALI LINUX LATEST 2021 VERSION MY PROBLEM IS WHEN I USE FLUXION FOR EVIL TWIN AP MY AP IS CREATED BUT NOT CONNECT TO AP DHCP SERVER ALSO STARTED BUT NOTHING HAPPEN.
 IN TEMP FILE  SOME FILES CREATE WHEN I LAUCH PLEASE SOLVE THIS ISSUE OR BUG 
![Uploading IMG_20211107_144446.jpg…]()
FLUXION SCREEN SHOT ADDED

**Comment by cjb900** [comment]
@HUBBLEGMR I don't know what type of screenshot you added but it's just redirecting back to this github issue and not showing any picture. Also if fluxion is not creating the DHCP properly you may want to try reinstalling dhcpd and see if that helps.
