### ISSUE TITLE
Aborted, xterm test session failed.

### ISSUE THREAD

**Issue by fraggout23** [FluxionNetwork/fluxion#1073]
#### Summary
Everytime I attempt to run the ./fluxion script i get the same message Aborted, xterm session failed. no matter what i do i tried running it through sudo and straight up su doesnt work, tried it on another pc running debian 10 and still nothing had it work on debian 8 successfully but 10 is not working at all.

##### What is the current behaviour?
fluxion wont run

##### If the current behaviour is a bug, please provide the steps to reproduce it.
not sure if it is a bug but the script just wont run.

##### What do you think the expected behaviour should be?
the script should just run like normal as it did on debian 8

Dell XPS 15 9560, 8gb ram, i5-7300hq 2.50ghz x4, 64 bit, 250gb nvme
Debian 10 kernel: 4.19.0-18-amd64

**Comment by strasharo** [comment]
Did you actually try to run xterm manually?

**Comment by fraggout23** [comment]
I ran the command "xterm" an external console popped up, im not sure if there are arguments im missing or xterm is supposed to be ran automatically in conjunction with fluxion.

**Comment by Lunaring** [comment]
Hi @fraggout23  i found youre problem.
it's an xterm problem.
Here as a test if it is an xterm problem: 
open the console and write 
> xterm

now xterm pops up as its own console. ( ok so far)

but as soon as you write
> root xterm
it can not resolve xterm.

Solution for this :

> sudo su
> xauth add $(xauth -f ~john/.Xauthority list|tail -1)

Please swap ~john for your ~user.
as an example:

> xauth add $(xauth -f ~kali/.Xauthority list|tail -1)

**Comment by fraggout23** [comment]
unfortunately that didn't work I got these error code.

xauth: timeout in locking authority file /root/.Xauthority
xauth: file /home/USERNAME/.Xauthority does not exist

**Comment by Lunaring** [comment]
I guess you have executed the wrong code.
when i log into linux it is "Kali" because i use the kali version.
you must have thought that you need to authorize the root user.

but you are (in my example) authorizing the kali user under root.

if your user is called "fraggout" here is the example of what you need to do under root

> **xauth add $(xauth -f ~fraggout/.Xauthority list|tail -1)**

not :
<del>xauth add $(xauth -f ~root/.Xauthority list|tail -1)<del>

Please let me know if it worked, what you entered or what error came out.
