### ISSUE TITLE
Fluxion Service AP send failed

### ISSUE THREAD

**Issue by izqx** [FluxionNetwork/fluxion#1075]
fluxion version : 6.9
VMware: Kali-Linux-2021.2-vmware-amd64
Driver : rt2800usb
Chipset : Ralink Technology, Corp. RT2870/RT3070
An error will be reported about 6-7 minutes after the AP is created
Everything was fine until the error was reported
The analog AP signal can be searched, but cannot be connected
![SJ)UJRBT7A6DBFOHP(6Z1XW](https://user-images.githubusercontent.com/33259989/148670277-c1c28566-0c59-4d36-b473-983a37ae7904.png)

**Comment by cjb900** [comment]
Something with the state of the interface changed. This would usually be the cause of some other program/process that may have been running in the background. I would try rebooting your computer then unplug and re-plug in your wifi adapter. then start fluxion with this command ``sudo ./fluxon.sh -k`` and see if that helps any

**Comment by ClairJobs** [comment]
> 

I also met this problem.
