### ISSUE TITLE
Fluxion error

### ISSUE THREAD

**Issue by Adil1146** [FluxionNetwork/fluxion#1077]
Hello Github,
When I use command ./fluxion it shows "mission aborted please execute as a root" when i start with root it says "aborted xterm test session failed"
please give me the solution as soon as possible.
Thank you.

**Comment by Luncer** [comment]
I want to close all type of this xterm problems. 
user#: ./fluxion.sh
Fluxion Need root than you use
user#: sudo ./fluxion.sh

If they say "Aborted, xterm test session failed."

Here you make sure that xterm and xdpyinfo is installed and works with the normal user.
user#: xterm
user#: xdpyinfo

If there is no error. take the fluxion.sh and write the following command at the top of the file

Short undynamic code:
`cp /home/username/.Xauthority /root/`

Now fluxion works over remote with root.

Here is a dynamic script that you can insert as an alternative above without specifying exactly your username.

Dynamic Code:
```
xauth_file="${HOME}/.Xauthority"

if [ -f "$xauth_file" ]; then
  echo "the .Xauthority-data was found: $xauth_file"
  
  # Copy the .Xauthority-data to /root/
  cp "$xauth_file" /root/
  
  echo "success"
else
  echo "No .Xauthority-data found"
fi
```
