### ISSUE TITLE
Aireplay-ng sets the wrong channel when changed by the router

### ISSUE THREAD

**Issue by X4n4ks4** [FluxionNetwork/fluxion#1078]
Aireplay-ng sets the wrong channel when changed by the router.

When I use fluxion for the first time and want to disconnect clients via aireplay it works fine, but when the router changes wifi channel then aireplay stays with the first one and stops disconnecting clients.

**Comment by cjb900** [comment]
Ya that can happen with some routers. You will need a second wifi adapter to use target tracking so fluxion can change the channel its deauthing on to match the channel the router is changing to.

**Comment by X4n4ks4** [comment]
I used 3x WN722n v1 with atheros chipset. RT3020 the same problem.

**Comment by Krawzir** [comment]
Shade naser ba cootome street for anime com in her in gift hem

In locashin for her(7H96QF3C+99)

في الاثنين، ٧ فبراير، ٢٠٢٢ ٨:٢١ ص X4n4ks4 ***@***.***> كتب:
