### ISSUE TITLE
Aireplay-ng sets the wrong channel when changed by the router.

### ISSUE THREAD

**Issue by X4n4ks4** [FluxionNetwork/fluxion#1079]
Aireplay-ng sets the wrong channel when changed by the router.

When I use fluxion for the first time and want to disconnect clients via aireplay it works fine, but when the router changes wifi channel then aireplay stays with the first one and stops disconnecting clients.

My thread was closed. I used 3x WN722n v1 with atheros chipset. RT3020 the same problem.

**Comment by usuarionuevor** [comment]
Maybe this is why auto channel tracking doesn't work... I had similar issue and my thread was closed too, I have to use static channel and this tool for deauth https://github.com/zartaz/Mdk4_deauther/
