### ISSUE TITLE
Unable to run install.sh

### ISSUE THREAD

**Issue by Yanziji** [FluxionNetwork/fluxion#108]
I use Chmod 755 install.sh

Then run, but there is no need to automatically install dependencies. I manually install dependencies, and finally dhcpd this dependency package installed, but it still prompts me when I was not installed!

Could you tell me how to solve this problem? Thank you!

I'm from China. Is it related to the blockade of my network here?

**Comment by deltaxflux** [comment]
You don't fill out the issue template automatically close.
