### ISSUE TITLE
Fluxion 6.9 having show stopper issue while selecting interface

### ISSUE THREAD

**Issue by AdonisPro** [FluxionNetwork/fluxion#1080]
Hello Team,

Thanks for this awesome tool but unfortunately i am unable to use this. I have downloaded the latest version i.e. V6.9 from your git repo and installed it in Kali 2021.

Now while i try to run the fluxion i face a peculiar issue. Once i choose option 1, Captive portal and the interface gets allocated, the interface name in my kali linux machine changes from **wlan0** to **fluxwl0**. Now when i proceed in the next steps, i never get option to choose interface as fluxwl0 but wlan0 option is given to me. Hence if i choose wlan0 it says, Unable to start captive portal interface.

Initial ifconfig o/p:
![image](https://user-images.githubusercontent.com/91906895/155576383-72274166-22e2-430c-a70c-6ece07e8fe64.png)

After we select option 1: Captive Portal
![image](https://user-images.githubusercontent.com/91906895/155576730-aaf727c2-d264-412d-94a5-9267fbbcaa4f.png)

Now if i proceed with fluxion and select respective options:
![image](https://user-images.githubusercontent.com/91906895/155576896-a7936fd4-af0b-4572-b3c0-4a423b5d95ed.png)

I am using TPLink TL WN-725N, with rtl8188eu driver, Please note: **it very well supports packet injection and monitor mode and manually all the operation that fluxion does, i can execute them.** 

I have run the diagnosis also via your script:
![image](https://user-images.githubusercontent.com/91906895/155577329-04ecf27c-aa7c-4da3-9036-50f2b23ee561.png)

![image](https://user-images.githubusercontent.com/91906895/155577386-7e8b6a6e-74c2-4d53-af89-2f7398a3da3f.png)

I don't know why it is giving chipset not in the list.

I would earnestly request the learned fraternity to please help me solve the issue as i really want to use this great tool. 

@deltaxflux @MPX4132 

Earnest request . Please help as i can't proceed a bit.

**Comment by cjb900** [comment]
The chipset in your adapter is not going to work properly with fluxion even if it does support the modes needed. RTL chipsets are notoriously problematic for wifi hacking and there is no real fix for them other then getting a better supported adapter/chipset. You can find a list here 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)

**Comment by AdonisPro** [comment]
@cjb900 Thanks for responding. But would appreciate if at least one comment from the creator of the issue is allowed before closing the issue. 

The manual operation of everything that fluxion does is working fine with this chipset. I am just trying to figure out the root cause. Any help?

**Comment by cjb900** [comment]
The root cause is most likely that the drivers for RTL chipsets in linux are complete crap and buggy when it comes to anything wifi hacking related even if they support all the modes needed. More people have issues with RTL chipsets for wifi hackong then those that do not use an RTL chipset. can't say exactly why fluxion changes the wifi interface name just that is does and works fine if you have a known good adapter/chipset. But if you want a response from one if the devs of fluxion good luck. they rarely reply to anything here anymore

**Comment by AdonisPro** [comment]
Hello @cjb900 

Requesting one help. The list of wireless adapters that you have given me yesterday, i had a deep look. But unfortunately no **D-Link** and/or **TP-Link** adapters are available. Those models are **end of life**

Alfa AWUS051NH -- Not available in Market online/offline.

AWUS 036ACHM -- Not available in Market online/offline.

Alfa AWUS036NHA -- Too costly

Alfa AWUS052NHS -- Not available in Market online/offline.

Panda PAU07 -- Not available in Market online/offline.

Panda PAU09 -- Too costly

I'd request you to please suggest some more models please.

Also, Can i use **Generic AR9271 802.11n 150 Mbps Wireless USB WiFi Adapter with WiFi Antenna WLAN Network Card**

All the TP-Link routers these days are not supporting monitor mode, packet injection and AP mode and moreover all of them are using Realtek chipset. 

So i am badly confused and in trouble. Actually want to use this great fluxion tool and for that struggling. Need your help Please.

Regards

**Comment by AdonisPro** [comment]
@cjb900/ et-al,

please help.

**Comment by cjb900** [comment]
That list of adapters and chipsets is just of ones that have been tested and known to work and support monitor mode, AP mode and VIF. There may be other cards/chipsets out there that may work but you would need proof they support the modes needed to work properly. you can get a way with buying 2 cards as long as they both support monitor mode and AP mode. Fluxion does allow 2 different cards to be used. You may also be able to use this link to find a supported card/chipset https://github.com/morrownr/USB-WiFi. but in the end if you are unable find a card/chipset where you live there is nothing anyone here can do about that.

**Comment by AdonisPro** [comment]
@cjb900 

Thanks for your response and help. But i am keen to find the root cause why the interface name is getting changed as soon as the interface is getting allocated by fluxion for Captive Portal option.

Please can you help me? This is really alarming to me. Not sure if this is an issue with the new version. Please have a look at the steps and screenshot i pasted above.

**Comment by cjb900** [comment]
The wifi interface name getting changed is supposed to happen. Its how fluxion was coded/developed. my guess is that they used the fluxwl0 to help with consistent coding or something. But as long as you have a wifi adapter that properly supports monitor mode AP mode and VIF that interface name change should not interfere with the function of fluxion

**Comment by AdonisPro** [comment]
Hi @cjb900 ,

### Thanks for your response. At the very beginning, i'd request you to please consider my comments and statement as a discussion rather than a stubborn argument. 

I agree with you that the wifi interface name getting changed is as per coding--> It might be and also i've see somewhere a comment by @deltaxflux that he has added some code regarding interface handling in this 6.9. 

_I just want to convey to you that my wireless adapter functions in a proper way and supports, monitor mode, packet injection and AP mode. Also i have tested with another D-Link adapter which supports all the monitor mode, packet injection and AP mode. But the same problem i faced. To debug more, i have tested this time with a fresh distribution of Kali 2021.3. But no luck._

Just i want to state my view here:

**whatever may be the code implemented for interface handling, that should be consistent. For the sake of this code change, I consider that after the interface allocation is done, the wi-fi interface name is getting changed to _fluxwl0_. But then in the next step, fluxion should give me the option to select that interface fluxwl0 rather than keeping the name as _wlan0_ _which does not exist at that time as the name got changed._ 

Then if an interface wlan0 which does not exist and got renamed by fluxion to fluxwl0 is selected then obviously it will not be able to allocate.** 

I am not sure if i am able to explain it fully and have been trying my best to put my point as an observation which could definitely be a bug. All the step by step o/p is put in the screenshot that i pasted in my very first comment. 

i'd earnestly request you to please have a look at this and please help me and if you think you might also contact the developers, (being a collaborator you have the access to contact the developers in some other way) so that they can have a look. The reason why i am telling this is i really want to use this great tool. 

Again explicitly marking @deltaxflux @afonso @dandrews @MPX4132 @Hritik14 if they at all take a look at my comment.

Please help.

Regards

**Comment by AdonisPro** [comment]
Hello @cjb900 

Please help by guiding me to solve or re-open this as an issue.

**Comment by cjb900** [comment]
The reason that fluxion changes the interface name but does not display that in the list is that fluxion tries to split the card into 2 virtual interfaces(VIF). From what you have described your cards do not seem to support this. Which, if they are using RTL chipset would be as expected. As mentioned before RTL chipsets are notoriously problematic for wifi hacking. Even if they support each mode individually when it comes to wifi attacks like fluxion they almost always run into one issue or another. This is why they are not recommended for wifi hacking. The quickest way to get fluxion to work is to use or get one of the supported wifi adapters/chipsets from the list and or link I provided before. Otherwise, you can try and use the latest version of kali 2022.1 which was released a few weeks ago and see if that helps. You also seem to have more than one card so you can try using different combinations of those cards one for the AP and one to deauth and see if any combination of that works for you. Another thing you can try while using 2 cards is to run ``sudo airmon-ng check kill`` before starting fluxion and see if that also helps any as well. If any of these suggestions do not help you will have to look into getting a supported wifi card/chipset. Also as mentioned before getting any of the devs to comment on this is not likely to happen as they are rarely active here anymore and I do not have any direct contact with them. I was just sent an email to be a contributor here several months ago.
