### ISSUE TITLE
How can I change the background color of Generic Captive Portal?

### ISSUE THREAD

**Issue by jinglei207** [FluxionNetwork/fluxion#1081]
I want to change the background gray color to a more bright color like orange or yellow. Thanks.

![Screenshot_2022-03-05-21-22-20-342_org adblockplus browser](https://user-images.githubusercontent.com/31416095/157309192-d139c224-3f9e-4ce6-abb0-65a1f0fec1e9.jpg)

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/blob/master/attacks/Captive%20Portal/attack.sh#L1043
