### ISSUE TITLE
Hello. I've got a problem . When creating the rogue AP after being done with the handshake snooper attack, it won't show other windows like what I see in YouTube tutorials..what could be the problem?

### ISSUE THREAD

**Issue by Ghostretri** [FluxionNetwork/fluxion#1083]
.
Hello. I've got a problem . When creating the rogue AP after being done with the handshake snooper attack, it won't show other windows like what I see in YouTube tutorials..what could be the problem?

**Comment by strasharo** [comment]
Let me grab the crystal ball
![image](https://user-images.githubusercontent.com/3337997/162175972-3b365c91-8836-4143-abbd-ed523b786cad.png)
