### ISSUE TITLE
Can't execute the program, command not found.

### ISSUE THREAD

**Issue by yonasuriv** [FluxionNetwork/fluxion#1085]
##### What is the current behaviour?
```
./fluxion.sh: line 255: format_center_literals: command not found
./fluxion.sh: line 262: format_center_literals: command not found
./fluxion.sh: line 270: installer_utils_check_update: command not found
./fluxion.sh: line 289: installer_utils_check_dependencies: command not found
./fluxion.sh: line 290: installer_utils_run_dependencies: command not found


Dependency installation failed!
Press enter to retry, ctrl+c to exit...
```

#### How to reproduce

- If I run `./fluxion.sh` I get  `Aborted, please execute the script as root.`

- If I run `sudo ./fluxion.sh ` I get _what I wrote in current behaviour._

- If I run `sudo ./fluxion.sh -i ` to install the missing dependencies I _still get the same._

**I'm running Parrot 5.0**

I've tried to search over the internet about this issue but all the topics having the same problem got closed with no answer.

**Comment by cjb900** [comment]
Have you tried installing the missing dependence manually with ``sudo apt install <package name>`` with out the <> obviously

**Comment by yonasuriv** [comment]
> Have you tried installing the missing dependence manually with `sudo apt install <package name>` with out the <> obviously

What package are you talking about?

```
sudo apt install fluxion
sudo apt install format_center_literals
```

Those won't work

**Comment by yonasuriv** [comment]
I think I'm getting the error because cloning the repository outside of my user home since I want it clean.

Can that be the problem?

**Comment by yonasuriv** [comment]
Fixed the issue by adding it into a hidden folder.

```
git clone https://www.github.com/FluxionNetwork/fluxion.git ~/.fluxion
cd ~/.fluxion
sudo ./fluxion.sh -i
```

**Comment by yonasuriv** [comment]
Fixed the issue by adding it into a hidden folder.

```
git clone https://www.github.com/FluxionNetwork/fluxion.git ~/.fluxion
cd ~/.fluxion
sudo ./fluxion.sh -i
```
