### ISSUE TITLE
How to attack double WiFi at the same time? 2.4G and 5G has same name!!

### ISSUE THREAD

**Issue by ch-boogeyman** [FluxionNetwork/fluxion#1088]
When attack 5G wifi,The user's phone will auto connect 2.4G wifi with the same name.
So,how to acttack double WiFi at the same time?

**Comment by cjb900** [comment]
To attack a dual band AP you need at least 2 wifi adapters. One to attack one of the bands with deauthing and creating the fake A with fluxion. Than you need another wifi adapter to just deauth the other band you are not attacking outside of fluxion with wither mdk4/3 or aireplay-ng. There is way to attack a dual band AP in fluxion by itself with just one wifi adapter.
