### ISSUE TITLE
deauthorizing in evil twin attack

### ISSUE THREAD

**Issue by F250SC** [FluxionNetwork/fluxion#1089]
Hey,

I may have an issue, but I’m not Shute if it is one or not.

when I run evil twin with captive portal, the deauther is sending round about 20 packages and then nothing anymore.
Should it not constantly sending packages? (Like airgeddon)

same problem with all 3 deauthers.

thanks for the tips.

**Comment by cjb900** [comment]
how is anyone supposed to be able to help you if you don't give any information on your setup. We are not physic here
