### ISSUE TITLE
Native Chinese translation.

### ISSUE THREAD

**Issue by Yanziji** [FluxionNetwork/fluxion#109]
Thank the author for giving us such a good tool! I'm from china! Read the phishing page in chinese! I think the page language is not localized! Therefore, it has been adapted to the reading habits of Chinese people!
Amend as follows:

DIALOG_WEB_INFO="您的网络出现了严重问题,请输入密码来自动修复"
DIALOG_WEB_INPUT="请输入您的无线网络密码:"
DIALOG_WEB_SUBMIT="提交并修复"
DIALOG_WEB_ERROR="出错了:您输入的密码错误!"
DIALOG_WEB_OK="正在自动修复错误,网络会在短时间内恢复"
DIALOG_WEB_BACK_ZH="返回"
DIALOG_WEB_ERROR_MSG="此处不能为空"
DIALOG_WEB_LENGTH_MIN="密码最少要有{0}个字符!"
DIALOG_WEB_LENGTH_MAX="密码必须少于{0}个字符!"
DIALOG_WEB_DIR="ltr"

**Comment by MPX4132** [comment]
@Yanziji Oh, thank you very much for helping out!
Please check out the latest version, it's available here on the repository. We've been working on it a lot lately, and it has changed quite a bit. If you ever have some free time, please take a look at the file 
```
fluxion/language/中文.lang
```
If you'd like, you can help us translate it into mandarin. Just specify weather it's simplified, or traditional. You can post the translation here and I'll add it to the repository.

**Comment by Yanziji** [comment]
@MPX4132 Thank you for your trust in me, and I love your tools too! I'd be happy to provide Chinese service for your tool!

**Comment by MPX4132** [comment]
@Yanziji Awesome, please take a look at the file and helps us translate it. It doesn't have to be perfect, just make sure people understand the instructions and dialog.

**Comment by Yanziji** [comment]
@MPX4132 

中文.lang:

#!/bin/bash
# Chinese

FLUXIONInterfaceQuery="请选择你要调用的网卡设备"
FLUXIONUnblockingWINotice="解除所有占用无线接口设备的进程..."
FLUXIONFindingExtraWINotice="查询USB外部网卡接口设备..."
FLUXIONRemovingExtraWINotice="正在移除USB外部网卡接口设备..."
FLUXIONFindingWINotice="寻找可用的USB外部网卡接口设备..."
FLUXIONSelectedBusyWIError="选择的USB外部网卡接口设备正在被调用!"
FLUXIONSelectedBusyWITip="Run \"export FLUXIONDropNet=1\" before FLUXION to use it."
FLUXIONGatheringWIInfoNotice="采集接口信息..."
FLUXIONFindingConflictingProcessesNotice="自动查询干扰Fluxion运行的进程..."
FLUXIONKillingConflictingProcessesNotice="结束干扰Fluxion运行的进程..."
FLUXIONStartingWIMonitorNotice="启动监听模式..."
FLUXIONStartingWIAccessPointNotice="启动访问点接口..."
FLUXIONCannotStartWIAccessPointError="${CRed}无法创建虚拟钓鱼热点$CClr, 请返回重试!"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONStartingScannerNotice="启动扫描, 请稍等..."
FLUXIONPreparingScannerResultsNotice="综合扫描的结果获取中,请稍等..."
FLUXIONScannerFailedNotice="你的无线网卡好像不支持 (没有发现APs)"
FLUXIONScannerDetectedNothingNotice="没有发现访问点, 请返回重试..."
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONHashFileDoesNotExistError="Hash文件不存在!"
FLUXIONHashInvalidError="${CRed}错误$CClr, 无效的Hash文件!"
FLUXIONHashValidNotice="${CGrn}成功$CClr, Hash效验完成!"
FLUXIONPathToHandshakeFileQuery="指定捕获到的握手包存放的路径 $CClr(例如: /.../dump-01.cap)"
FLUXIONAbsolutePathInfo="捕获到握手包后存放的绝对路径"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CaptivePortalStaringAPServiceNotice="开始建立钓鱼热点AP..."
CaptivePortalStaringAPRoutesNotice="启动钓鱼热点AP路由服务..."
CaptivePortalStartingDHCPServiceNotice="启动接入点DHCP服务作为守护进程..."
CaptivePortalStartingDNSServiceNotice="启动接入点DNS服务作为守护进程..."
CaptivePortalStartingWebServiceNotice="启动钓鱼热点作为守护进程..."
CaptivePortalStartingJammerServiceNotice="启动接入点干扰器作为守护进程..."
CaptivePortalStartingAuthenticatorServiceNotice="启动验证器脚本..."
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerChannelQuery="选择要扫描的信道"
FLUXIONScannerChannelOptionAll="扫描所有信道 "
FLUXIONScannerChannelOptionSpecific="扫描指定信道"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerChannelSingleTip="单一信道"
FLUXIONScannerChannelMiltipleTip="多个信道"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerHeader="FLUXION 扫描仪"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONAPServiceQuery="选择攻击方式"
FLUXIONAPServiceHostapdOption="钓鱼热点破解 (${CRed}推荐用这个)"
FLUXIONAPServiceAirbaseOption="Rogue AP - airbase-ng (缓慢)"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CaptivePortalVerificationMethodQuery="请选择验证密码方式"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
DialogQueryHashSource="选择一种方式来检查握手包获取状态"
FLUXIONHashSourceQuery="选择一种方式来检查握手包获取状态"
FLUXIONHashSourcePathOption="检测文件的路径"
FLUXIONHashSourceRescanOption="握手包目录(重新扫描)"
FLUXIONFoundHashNotice="发现目标热点的Hash文件."
FLUXIONUseFoundHashQuery="你想要使用这个文件吗?"
FLUXIONHashVerificationMethodQuery="选择Hash的验证方法"
FLUXIONHashVerificationMethodPyritOption="验证码 (${CGrn}推荐用这个$CClr)"
FLUXIONHashVerificationMethodAircrackOption="aircrack-ng 验证 (不推荐)"
CaptivePortalCertificateSourceQuery="选择钓鱼认证门户的SSL证书来源"
CaptivePortalCertificateSourceGenerateOption="创建SSL证书"
CaptivePortalCertificateSourceRescanOption="检测SSL证书 (${CClr}再次搜索$CGry)"
CaptivePortalInterfaceQuery="选择钓鱼热点的认证网页界面"
CaptivePortalGenericInterfaceOption="通用认证网页"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
HandshakeSnooperMethodQuery="选择一种方式来检查握手包获取状态"
HandshakeSnooperMonitorMethodOption="监听模式 (${CYel}被动$CClr)"
HandshakeSnooperAireplayMethodOption="aireplay-ng 解除认证方式 (${CRed}侵略性$CClr)"
HandshakeSnooperMdk3MethodOption="mdk3 解除认证方式 (${CRed}侵略性,不推荐用这个$CClr)"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONAttackQuery="请选择一个攻击方式"
FLUXIONAttackInProgressNotice="${CCyn}\$FLUXIONAttack$CClr attack in progress..."
FLUXIONSelectAnotherAttackOption="选择启动攻击方式"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONGeneralBackOption="${CRed}返回"
FLUXIONGeneralExitOption="${CRed}退出"
FLUXIONGeneralRepeatOption="${CRed}重复操作"
FLUXIONGeneralNotFoundError="未找到"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONCleanupAndClosingNotice="清理进程并退出"
FLUXIONKillingProcessNotice="Killing ${CGry}\$targetID$CClr"
FLUXIONDisablingMonitorNotice="关闭监听模式界面"
FLUXIONDisablingExtraInterfacesNotice="关闭USB外部网卡接口"
FLUXIONDisablingPacketForwardingNotice="关闭 ${CGry}转发数据包"
FLUXIONDisablingCleaningIPTablesNotice="清理 ${CGry}iptables"
FLUXIONRestoringTputNotice="恢复 ${CGry}tput"
FLUXIONDeletingFilesNotice="删除 ${CGry}文件"
FLUXIONRestartingNetworkManagerNotice="重启 ${CGry}网络管理"
FLUXIONCleanupSuccessNotice="所有进程清理完成!"
FLUXIONThanksSupportersNotice="再次感谢使用Fluxion!"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# FLUXSCRIPT END

**Comment by Yanziji** [comment]
@MPX4132 Part of the translation may not be accurate, because my English is not good, I'm still learning! I hope I can help you later! And slowly optimize the Chinese Translation

**Comment by Yanziji** [comment]
Because I am in China, the network has blocked, the file can not upload! Can only paste to you!
#!/bin/bash
# Chinese

FLUXIONInterfaceQuery="请选择你要调用的网卡设备"
FLUXIONUnblockingWINotice="解除所有占用无线接口设备的进程..."
FLUXIONFindingExtraWINotice="查询USB外部网卡接口设备..."
FLUXIONRemovingExtraWINotice="正在移除USB外部网卡接口设备..."
FLUXIONFindingWINotice="寻找可用的USB外部网卡接口设备..."
FLUXIONSelectedBusyWIError="选择的USB外部网卡接口设备正在被调用!"
FLUXIONSelectedBusyWITip="Run \"export FLUXIONDropNet=1\" before FLUXION to use it."
FLUXIONGatheringWIInfoNotice="采集接口信息..."
FLUXIONFindingConflictingProcessesNotice="自动查询干扰Fluxion运行的进程..."
FLUXIONKillingConflictingProcessesNotice="结束干扰Fluxion运行的进程..."
FLUXIONStartingWIMonitorNotice="启动监听模式..."
FLUXIONStartingWIAccessPointNotice="启动访问点接口..."
FLUXIONCannotStartWIAccessPointError="${CRed}无法创建虚拟钓鱼热点$CClr, 请返回重试!"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONStartingScannerNotice="启动扫描, 请稍等..."
FLUXIONPreparingScannerResultsNotice="综合扫描的结果获取中,请稍等..."
FLUXIONScannerFailedNotice="你的无线网卡好像不支持 (没有发现APs)"
FLUXIONScannerDetectedNothingNotice="没有发现访问点, 请返回重试..."
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONHashFileDoesNotExistError="Hash文件不存在!"
FLUXIONHashInvalidError="${CRed}错误$CClr, 无效的Hash文件!"
FLUXIONHashValidNotice="${CGrn}成功$CClr, Hash效验完成!"
FLUXIONPathToHandshakeFileQuery="指定捕获到的握手包存放的路径 $CClr(例如: /.../dump-01.cap)"
FLUXIONAbsolutePathInfo="捕获到握手包后存放的绝对路径"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CaptivePortalStaringAPServiceNotice="开始建立钓鱼热点AP..."
CaptivePortalStaringAPRoutesNotice="启动钓鱼热点AP路由服务..."
CaptivePortalStartingDHCPServiceNotice="启动接入点DHCP服务作为守护进程..."
CaptivePortalStartingDNSServiceNotice="启动接入点DNS服务作为守护进程..."
CaptivePortalStartingWebServiceNotice="启动钓鱼热点作为守护进程..."
CaptivePortalStartingJammerServiceNotice="启动接入点干扰器作为守护进程..."
CaptivePortalStartingAuthenticatorServiceNotice="启动验证器脚本..."
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerChannelQuery="选择要扫描的信道"
FLUXIONScannerChannelOptionAll="扫描所有信道 "
FLUXIONScannerChannelOptionSpecific="扫描指定信道"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerChannelSingleTip="单一信道"
FLUXIONScannerChannelMiltipleTip="多个信道"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerHeader="FLUXION 扫描仪"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONAPServiceQuery="选择攻击方式"
FLUXIONAPServiceHostapdOption="钓鱼热点破解 (${CRed}推荐用这个)"
FLUXIONAPServiceAirbaseOption="Rogue AP - airbase-ng (缓慢)"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CaptivePortalVerificationMethodQuery="请选择验证密码方式"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
DialogQueryHashSource="选择一种方式来检查握手包获取状态"
FLUXIONHashSourceQuery="选择一种方式来检查握手包获取状态"
FLUXIONHashSourcePathOption="检测文件的路径"
FLUXIONHashSourceRescanOption="握手包目录(重新扫描)"
FLUXIONFoundHashNotice="发现目标热点的Hash文件."
FLUXIONUseFoundHashQuery="你想要使用这个文件吗?"
FLUXIONHashVerificationMethodQuery="选择Hash的验证方法"
FLUXIONHashVerificationMethodPyritOption="验证码 (${CGrn}推荐用这个$CClr)"
FLUXIONHashVerificationMethodAircrackOption="aircrack-ng 验证 (不推荐)"
CaptivePortalCertificateSourceQuery="选择钓鱼认证门户的SSL证书来源"
CaptivePortalCertificateSourceGenerateOption="创建SSL证书"
CaptivePortalCertificateSourceRescanOption="检测SSL证书 (${CClr}再次搜索$CGry)"
CaptivePortalInterfaceQuery="选择钓鱼热点的认证网页界面"
CaptivePortalGenericInterfaceOption="通用认证网页"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
HandshakeSnooperMethodQuery="选择一种方式来检查握手包获取状态"
HandshakeSnooperMonitorMethodOption="监听模式 (${CYel}被动$CClr)"
HandshakeSnooperAireplayMethodOption="aireplay-ng 解除认证方式 (${CRed}侵略性$CClr)"
HandshakeSnooperMdk3MethodOption="mdk3 解除认证方式 (${CRed}侵略性,不推荐用这个$CClr)"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONAttackQuery="请选择一个攻击方式"
FLUXIONAttackInProgressNotice="${CCyn}\$FLUXIONAttack$CClr attack in progress..."
FLUXIONSelectAnotherAttackOption="选择启动攻击方式"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONGeneralBackOption="${CRed}返回"
FLUXIONGeneralExitOption="${CRed}退出"
FLUXIONGeneralRepeatOption="${CRed}重复操作"
FLUXIONGeneralNotFoundError="未找到"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONCleanupAndClosingNotice="清理进程并退出"
FLUXIONKillingProcessNotice="Killing ${CGry}\$targetID$CClr"
FLUXIONDisablingMonitorNotice="关闭监听模式界面"
FLUXIONDisablingExtraInterfacesNotice="关闭USB外部网卡接口"
FLUXIONDisablingPacketForwardingNotice="关闭 ${CGry}转发数据包"
FLUXIONDisablingCleaningIPTablesNotice="清理 ${CGry}iptables"
FLUXIONRestoringTputNotice="恢复 ${CGry}tput"
FLUXIONDeletingFilesNotice="删除 ${CGry}文件"
FLUXIONRestartingNetworkManagerNotice="重启 ${CGry}网络管理"
FLUXIONCleanupSuccessNotice="所有进程清理完成!"
FLUXIONThanksSupportersNotice="再次感谢使用Fluxion!"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# FLUXSCRIPT END

**Comment by MPX4132** [comment]
@Yanziji Thank you very much, I've made the changes and [posted them to the repository](https://github.com/FluxionNetwork/fluxion/commit/1609169670e5ca6aff8e8b3fa80c2e42c6d80971).

**Comment by Yanziji** [comment]
@MPX4132 Hope your tools are getting better and better! Please contact me if there is anything I can do for you!

**Comment by MPX4132** [comment]
@Yanziji Thank you for your help. The tool is getting better because people like you help out. There's about four more sentences in the program that we haven't added into the language files because those parts were recently developed. I'll need to translate those too. I'll put them here, and you can translate them if you'd like.

**Comment by MPX4132** [comment]
@Yanziji Here are the sentences that have just been added:
```
FLUXIONUnknownWIDriverError="Unable to determine interface driver!"
FLUXIONUnloadingWIDriverNotice="Waiting for interface \"\$wiSelected\" to unload..."
FLUXIONLoadingWIDriverNotice="Waiting for interface \"\$wiSelected\" to load..."
FLUXIONPhysicalWIDeviceUnknownError="${CRed}Unable to determine interface's physical device!"
FLUXIONMonitorModeWIEnabledNotice="${CGrn}Interface monitor mode enabled."
FLUXIONMonitorModeWIFailedError="${CRed}Interface monitor mode failed!"

FLUXIONStartingScannerTip="Once the target AP appears, close the FLUXION Scanner to continue."
```
Notice how some of those sentences have markers in them, like `\"\$wiSelected\"` in this one:
```
FLUXIONUnloadingWIDriverNotice="Waiting for interface \"\$wiSelected\" to unload..."
```
That part with the marker will be substituted with a variable. In this case, the marker will be substituted with an interface name. Once substituted, it'll say something like the following:
```
FLUXIONUnloadingWIDriverNotice="Waiting for interface wlan1 to unload..."
```
Hopefully that'll help you translate those lines, thank you for your help.

**Comment by MPX4132** [comment]
@Yanziji I’m sorry, I misread your report. I’ll add your translation changes to the portal page in a couple of hours, I’ve got to get some sleep now. It’s extremly late where I am.

**Comment by Yanziji** [comment]
@MPX4132 OK      see you!

**Comment by Yanziji** [comment]
@MPX4132 Well！ Contact me if you need anything!
I have no translation variables  :)

**Comment by deltaxflux** [comment]
Thanks for your contribution. Added

**Comment by MPX4132** [comment]
You portal translation [has been added](https://github.com/FluxionNetwork/fluxion/commit/d508e20b694a5231290c9949889a4294967316a5), thanks for your help.

**Comment by MPX4132** [comment]
@Yanziji Sorry, I didn't realize the generic portals were missing (including the Chinese one). That was a bug and it has been fixed, you should download [the latest version](https://github.com/FluxionNetwork/fluxion/commit/8cb32c92d374f00dd0a1959ebfcbfb919f12598f) and check it out.

**Comment by Yanziji** [comment]
1

**Comment by ww18877317962** [comment]
When the input captures the absolute path stored after the handshake package, display the Hash file does not exist!
