### ISSUE TITLE
A problem of fluxwl0v:INTERFACE-DISABLED

### ISSUE THREAD

**Issue by achdu0000** [FluxionNetwork/fluxion#1090]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Specs

I've got a total new and good network adapt. But when I started using pfishing attack, it does well   at the begining. However, every time about lasting work 6min45sec, there is some trouble like:
```
fluxwl0v: INTERFACE-DISABLED
fluxwl0v: INTERFACE-ENABLED
andle_probe_req: send failed
andle_probe_req: send failed
andle_probe_req: send failed
andle_probe_req: send failed
andle_probe_req: send failed
andle_probe_req: send failed
......
```
Could anyone tell me what's wrong with it? Thanks a lot!

**Comment by achdu0000** [comment]
Here is the screen-cut:
![image](https://user-images.githubusercontent.com/75735826/172569099-7ec13086-046b-4ed3-ba03-a61b680e480b.png)

**Comment by cjb900** [comment]
How is any one supposed to help if you don't say what wifi adapter and chipset you have. You Say it's a total new and good network adapt but you are obviously running into issues with it.
