### ISSUE TITLE
请问fluxion如何自定义热点名称？因为目标SSID显示乱码。

### ISSUE THREAD

**Issue by lszhwxa** [FluxionNetwork/fluxion#1094]
|    Q        |   A
|------------ | -----
| Version     | 5.9

#### Support Question
由于airodump-ng问题，部分中文SSID出现乱码，目标SSID真实名称为“蓝蓝”，却只能显示为“����”。导致我验证hash时以致无法通过，而且，即使通过了，SSID名称只显示为“����”，这不是想要的结果。

所以，我想知道如何自定义SSID名称呢，将“����”改成正确的“蓝蓝”？
![2022-06-21_124403](https://user-images.githubusercontent.com/57699051/174720365-d6643102-d4b8-43da-a782-d8e478e59317.jpg)

**Comment by strasharo** [comment]
![image](https://user-images.githubusercontent.com/3337997/175006465-5146b5f4-bbc0-4a30-a299-6ee4f47deef3.png)
tl;dr you're at 5.9, current version is 6.9

**Comment by lszhwxa** [comment]
> ![image](https://user-images.githubusercontent.com/3337997/175006465-5146b5f4-bbc0-4a30-a299-6ee4f47deef3.png) tl;dr you're at 5.9, current version is 6.9

我很好奇，你发的图片是想表达什么意思？

现在6.9版本同样存在这个问题，我的问题是如何自定义热点名称？
