### ISSUE TITLE
How does fluxion modify the user's request and response packets (e.g. by inserting JavaScript scripts into the web page, with the purpose of working with BEeF)?

### ISSUE THREAD

**Issue by RiotGamesU** [FluxionNetwork/fluxion#1096]
|    Q        |   A
|------------ | -----
| Version     | FLUXION V6.9

#### Support Question

How does fluxion modify the user's request and response packets (e.g. by inserting JavaScript scripts into the web page, with the purpose of working with BEeF)?

#### Specs

None

**Comment by cjb900** [comment]
Fluxion does not use beef. If it did it would be one of the required dependencies which it's not. The captive portal is an unencrypted http:// page and as such is able to just capture the password provided in plan text. I don't know the back end coding of how this is exactly does if that's what you want.
