### ISSUE TITLE
i can't solve that problem start captive portal interface!

### ISSUE THREAD

**Issue by ChinaClay** [FluxionNetwork/fluxion#1097]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select an interface for the access point.

[1] ens33    [-] Intel Corporation 82545EM Gigabit Ethernet Controller (Copper) (rev 01)                                                                                                      
[2] wlx002e2dcd6451 [*] Realtek Semiconductor Corp. 802.11ac NIC                                                                                                                                     
[3] Repeat                                                                                                                                                                                  
[4] Back                                                                                                                                                                                  

[fluxion@elliot-vmwarevirtualplatform]-[~] 2

[*] Unable to start captive portal interface, returning!

#!MY Wireless Adapter is RTL8812CU

┌─[elliot@elliot-vmwarevirtualplatform]─[~]
└──╼ $lsusb
Bus 001 Device 002: ID 0bda:c811 Realtek Semiconductor Corp. 802.11ac NIC
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 003: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 002 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
┌─[elliot@elliot-vmwarevirtualplatform]─[~]
└──╼ $

> 

> 

>

**Comment by ChinaClay** [comment]
it accesses scan the network near me.i mean successes,

**Comment by ChinaClay** [comment]
Waing

**Comment by cjb900** [comment]
The chipset you have RTL8812CU is not going to work in fluxion. RTL chipsets are notoriously problematic for wifi hacking and always have issues. There is no fix for it other than getting a better more supported adapter/chipset. Q

**Comment by ChinaClay** [comment]
> The chipset you have RTL8812CU is not going to work in fluxion. RTL chipsets are notoriously problematic for wifi hacking and always have issues. There is no fix for it other than getting a better more supported adapter/chipset.

Thanks for co,mment.And But it absolutely works before the this that step.

**Comment by cjb900** [comment]
Most RTL chipsets do not support either AP mode or VIF(ability to split the chipset into 2 virtual interface. One for deauthing and one for creating the fake AP). Even if the chipset you have does support these modes RTL chipsets are crap and always have issues. This is why they are not recommended for wifi hacking. Why it may have worked before but is not now is another reason RTL chipsets are not recommended as they are just not reliable for any wifi hacking. You will be better off getting a better more supported adapter/chipset rather then trying to get the one you have to work. Below you can find a list of supported adapters and chipset that will work with fluxion.

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)

**Comment by ChinaClay** [comment]
Thanks for reply.iyt's really helpful.
and is it nedds driver？my kali mybe newest.what should i download new driver

________________________________
发件人: cjb900 ***@***.***>
发送时间: 2022年6月26日 5:24
收件人: FluxionNetwork/fluxion ***@***.***>
抄送: ChinaClay ***@***.***>; Author ***@***.***>
主题: Re: [FluxionNetwork/fluxion] i can't solve that problem start captive portal interface! (Issue #1097)


Most RTL chipsets do not support either AP mode or VIF(ability to split the chipset into 2 virtual interface. One for deauthing and one for creating the fake AP). Even if the chipset you have does support these modes RTL chipsets are crap and always have issues. This is why they are not recommended for wifi hacking. Why it may have worked before but is not now is another reason RTL chipsets are not recommended as they are just not reliable for any wifi hacking. You will be better off getting a better more supported adapter/chipset rather then trying to get the one you have to work. Below you can find a list of supported adapters and chipset that will work with fluxion.

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)

―

**Comment by cjb900** [comment]
there are no drivers you can install that will the RTL chipset you have work. If you get any of the adapters/chipsets from the list I provided above all should work with no drivers needed in kali.
