### ISSUE TITLE
Not detecting rtl8192-fixes ?

### ISSUE THREAD

**Issue by Blaxou** [FluxionNetwork/fluxion#11]
### Which version of fluxion are you using?
Latest

### What distribution of Linux (including the version) are you running it on?
`$ uname -a`
`Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-1kali1 (2017-06-06) x86_64 GNU/Linux`
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Belkin Components F7D2102 802.11n N300 Micro Wireless Adapter v3000 [Realtek RTL8192CU]

### Which is the driver for it?
[pvaret's rtl8192cu fix](https://github.com/pvaret/rtl8192cu-fixes)

### Does it support injection ( output of aireplay-ng -9)
It supported, but not with this driver anymore : 
`ioctl(SIOCSIWMODE) failed: Invalid argument
ioctl(SIOCSIWMODE) failed: Invalid argument
Error setting monitor mode on wlan0
`
### General description of your issue along with the steps to reproduce it
Just enter Fluxion and choose a choose a language, then it says : `There are no wireless cards, quit...`

**Comment by deltaxflux** [comment]
Well I'm not responsable for other drivers but anyway this seems outdated: 
> Realtek 8192 chipset driver, ported to kernel 


Anyway I recommend that you remove this driver and use the offical driver instead. Here is the link to the driver wiki:
https://wireless.wiki.kernel.org/en/users/Drivers/rtl819x

**Comment by Blaxou** [comment]
Okay, thanks, ;)

What does this mean ? That RTL8192 is supported ?
Because when I was using it, it was soooo slow, and when I install the fix it went well

PS : Sorry for the newbish questions ;)

**Comment by deltaxflux** [comment]
Well if you install the drivers propertly you should able to enable monitor mode again so yes. I use the RT2870/RT3070 chipset

**Comment by Blaxou** [comment]
Yeah but I can't find the drivers, the Realtek is bs and I can't find them anywhere else ;(

**Comment by deltaxflux** [comment]
First search: https://askubuntu.com/questions/246236/compile-and-install-rtl8192cu-driver
