### ISSUE TITLE
log in page doesn't load

### ISSUE THREAD

**Issue by ahmed01240** [FluxionNetwork/fluxion#1100]
#### Summary
the login page does not load
i'm using ar9271 for the ap 
rtl8188eus for jamming
and sometimes i use the intel for tracking

##### What is the current behaviour?
every thing works except login page for the victim

##### If the current behaviour is a bug, please provide the steps to reproduce it.
i tried every method and always the same problem
![Screenshot_2022-07-20_00-14-12](https://user-images.githubusercontent.com/88556803/179899005-1bd0ef2a-6868-41bd-93a8-721b7129e38b.png)
![Screenshot_2022-07-20_00-20-55](https://user-images.githubusercontent.com/88556803/179899051-514c0b77-bf0e-4c94-8689-bd1d8c64f172.png)
![Screenshot_2022-07-20_00-18-19](https://user-images.githubusercontent.com/88556803/179899080-2fde4978-52a1-43f3-b4c1-4bfee8a9ed6f.png)
![Screenshot_2022-07-20_00-21-37](https://user-images.githubusercontent.com/88556803/179899105-16977ea5-30ef-4f17-b474-725962dc1a25.png)
![Screenshot_2022-07-20_00-16-07](https://user-images.githubusercontent.com/88556803/179899119-03b1936a-755f-4476-96bd-e1e05f7fa617.png)

##### What do you think the expected behaviour should be?
when the victim is connected to the fake ap and open any browser  , the ap will redirect to a fake log in page

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by ahmed01240** [comment]
update 
it works when i enter the ip 192.169.254.1 manually on the victim's phone browser

![Screenshot_2022-07-20_02-59-48](https://user-images.githubusercontent.com/88556803/179921368-4b3b0f7e-1f37-4693-9d04-6a634850ee10.png)

**Comment by ahmed01240** [comment]
Sorry guys I just figured out the problem, I was using a private dns on the phone.... I look like an idiot now 😔

**Comment by 1732337191** [comment]
using a private dns on the phone是啥意思
