### ISSUE TITLE
Fluxion jammer service Windows close randomly

### ISSUE THREAD

**Issue by Hastaluego123** [FluxionNetwork/fluxion#1101]
Hello everyone, i have an issue with the jammer Windows service she closed randomly…

im on live usb persistence kali 2022.2

my jammer is a realtek RTL8187 and the AP is Qualcomm Atheros AR9271

do you know why she closed ?

**Comment by cjb900** [comment]
RTL chipsets can be problematic for wifi hacking. I would try just using the AR9271 for both the AP and jamming and see if that works.

**Comment by Hastaluego123** [comment]
Thank for your answer, really it can do the both jamming and AP a the same Time without issue, i thought its one for AP and one for jamming

**Comment by cjb900** [comment]
Yes the AR9271 is capable of both jamming and creating the fake AP at the same time. You just have to select it for both when fluxion askes witch adapter to use for jamming and the AP

**Comment by Hastaluego123** [comment]
Ok thank i’ill try ;)

**Comment by Hastaluego123** [comment]
With AR9271 my victim device is able to connect on the true wifi AP and internet work perfectly, i see the fake AP too, but jamming seem not working because i see the two AP …

**Comment by cjb900** [comment]
I know others have used that chipset with no issues. what wifi band are you trying to attack. Is this a 2.4 or 5 ghz one?

**Comment by Hastaluego123** [comment]
I have the problem on the 2.4 and 5Ghz

**Comment by cjb900** [comment]
so 2.4 is the only band you will be able to jam/deauth. both wifi adapter you have are only 2.4 capable. So its possible if you are jamming the 2.4 band your device may be jumping to the 5 ghz band and not getting removed from the real AP. the only way to fix that would be to get another wifi adapter that jams the 5ghz band

**Comment by Hastaluego123** [comment]
Yes maybe ! What wifi adapter 5ghz can do this job ? (Jamming and deauth), i have a tplink archer t1u

**Comment by cjb900** [comment]
well i personally have a Panda Pau09 with the RT5572 chipset that supports 2.4 and 5ghz. but below is a list of adapters/chipsets that support 5ghz

MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)

**Comment by Hastaluego123** [comment]
Your panda is ok with the virtual machine ? And un your list they support jamming and deauth a the same Time ? 

Can i keep my AR9271 to make the fake AP ?

**Comment by cjb900** [comment]
I would not have suggested the adapter i have or any of the other ones if it doesn't work in VM's(excluding the AWUS036ACM)  and can't jam or deauth

**Comment by Hastaluego123** [comment]
Ok thank you i wanted to say « can they jamming and make AP a the same Time ? »

**Comment by cjb900** [comment]
yes but they can only do one wifi band at a time. they can not jam both the 2.4 and 5ghz and create the fake AP all at the same time

**Comment by Hastaluego123** [comment]
Ok ;) i have a TP-Link Archer T2U Plus USB Wifi AC600 can it do the job ?

**Comment by cjb900** [comment]
does it have one of the chipsets i mentioned above?

**Comment by Hastaluego123** [comment]
Realtek RTL8821AU Chipset

Show this: https://github.com/nlkguy/archer-t2u-plus-linux

**Comment by cjb900** [comment]
so that could possibly work for just jamming. but its an RTL chipset which are notoriously problematic for wifi hacking and may not work properly. Which is why the there are no RTL chipsets in the list i gave

**Comment by Hastaluego123** [comment]
Ok i think i’ill buy the AWUS052NHS panda are expensive

**Comment by Hastaluego123** [comment]
Lol its impossible to buy them, im french and none website sell them, Amazon too :( it seem there are too old…

**Comment by cjb900** [comment]
Ya unfortunately depending on where you live the selection of available wifi adapters may be limited. But you don't have to get one of these adapters specifically. you just need a wifi adapter with one of the supported chipsets in it.

**Comment by Hastaluego123** [comment]
Ok thank for your help cjb900 ;)

i have a question, if the victim rooter support 2,4ghz and 5ghz at the same Time, i need to start 2 jamming with 2 adapter if i want to deauth all devices ? If i just jamming one band the device will switch on the second band ?

**Comment by cjb900** [comment]
Yes

**Comment by Hastaluego123** [comment]
Ok How to do this ? I start 2 fluxion terminal ?

**Comment by cjb900** [comment]
Fluxion does not have a just deauthing option so you would have to do deauth either manually in another terminal or start a second instance of fluxion and then when all 6 windows open close all of them except the one deauthing.

**Comment by Hastaluego123** [comment]
Ok ;) i juste find this adapter rt5572

https://a.aliexpress.com/_ufG4En

**Comment by cjb900** [comment]
as long as that adapter actually comes with that chipset it should work fine
