### ISSUE TITLE
I don't know what's error

### ISSUE THREAD

**Issue by OldDream666** [FluxionNetwork/fluxion#1102]
When i connect the fluxion ap 
This shows 
ERR_NAME_NOT_RESOLVED
![Screenshot_2022-08-06-23-22-18-196_com android captiveportallogin](https://user-images.githubusercontent.com/89271654/183255560-fc51ea19-b005-4284-934b-5bc11f3e15d5.png)

**Comment by cjb900** [comment]
How is anyone supposed to help if you don't give any information on your setup or how you got this error.
