### ISSUE TITLE
How fluxion uses two network cards to work at the same time

### ISSUE THREAD

**Issue by 1732337191** [FluxionNetwork/fluxion#1103]
Hello Fluxion developers, I have two network cards, RT5370 and RTL8812AU. Fluxion can be used normally with RT5370. When I use RTL8812AU, I report the error "Unable to start captive portal interface, returning". I read issues#1097 and #1070 and understand that RTL8812AU does not support VIF. I want to use RT5370 to deauthing and use RTL8812AU to create AP, I don't know how to use

**Comment by cjb900** [comment]
RTL chipsets like the RTL8812AU are crap for wifi hacking you can try running `sudo airmon-ng check kill` before starting fluxion and see if that helps. Thare also seems to be some patched drivers for that chipset but not owning one I can't say it they will work. Personally if the above command and patched driver help you will probably be better off getting rid of the RTL8812AU and getting a better supported wifi adapter/chipset. If you need a list of supported ones you can find them below.

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
