### ISSUE TITLE
Unable to start captive portal

### ISSUE THREAD

**Issue by throwawaya609** [FluxionNetwork/fluxion#1104]
#### Summary

I am trying to do an evil twin attack using my realtek8812bu network adapter and it gives me this error:
![image](https://user-images.githubusercontent.com/109557965/184509151-8c0365ea-3d3c-403f-85b6-ad6510708752.png)
##### What is the current behaviour?
Unable to create captive portal
#### How to reproduce
grab a network and their bssid. select captive portal, sometimes I press skip on first option but even if I select my wlan0 to track target no matter what I select on 2nd screen (select an interface for access point) It says unable to create portal. Or if I select fluxet0, the device which i've never heard of (perhaps wlan0 renamed?) it says: 
![image](https://user-images.githubusercontent.com/109557965/184509130-3fbfdbc6-7917-4c68-8b8c-89f08b902c29.png)

##### What do you think the expected behaviour should be?

Creating captive portal and deauthing
##### If this is a feature request, what is the motivation or use case for the added feature?
Not a feature req
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
Interface (wlan0) Info 
**Device**: phy1
**Driver:** rtl88x2bu
**Chipset:** Realtek Semiconductor Corp. RTL88x2bu [AC1200 Techkey]
**Master Modes** Yes
**Injection Test:** read failed: Network is down
wi_read(): Network is down
Injection is working!

#### Expected behavior

Creating a captive portal

**Comment by cjb900** [comment]
That chipset is crap and will not work as it does not support VIF which is needed to be able to both deauthing and creating the fake AP at the same time. There is no known fix for this other than to get a better supported wifi adapter/chipset or to get a second adapter that supports monitor and AP mode to use 2 adapters in fluxion. If you need a list of supported adapters/chipsets you can find them below.

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
