### ISSUE TITLE
Arch MAKEPKG ERROR: Failure while downloading fluxion git repo

### ISSUE THREAD

**Issue by rushic24** [FluxionNetwork/fluxion#1109]
### Bug Report
![image](https://user-images.githubusercontent.com/6279035/188477001-c92f8d02-1d7b-469c-bf69-ee3700ee111d.png)

#### How to reproduce
```cd bin/arch && makepkg```

##### What do you think the expected behaviour should be?
install fluxion

My internet is working fine.

**Comment by cjb900** [comment]
Are you able to download another github repo just to test? Because I can download fluxion in kali with no issues.

**Comment by rushic24** [comment]
manually the github repo works. Something is wrong in the makepkg

**Comment by strasharo** [comment]
Troubleshooting your build environment is out of our scope.
