### ISSUE TITLE
./install/install.sh crashes at line 237

### ISSUE THREAD

**Issue by 2009h** [FluxionNetwork/fluxion#111]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion crashes* Wifislax64-1.1 installation problem 

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*
Crashes with:
```
./install/install.sh: line 237: [: ==: unary operator expected
```

#### What do you think the expected behaviour should be?
*What do you think should happen?*

### Specs
*Paste the output of `./script/diagnostics.sh`*

**Comment by MPX4132** [comment]
Try cloning/downloading the latest version. It no longer uses that script as installer.

**Comment by 2009h** [comment]
file:///root/Wifislax64-1.1 installation problem.png

**Comment by 2009h** [comment]
![wifislax64-1 1 installation problem](https://user-images.githubusercontent.com/20770325/29555700-bcfd878e-8723-11e7-9fbc-fa57b4e8c42e.png)

**Comment by 2009h** [comment]
![wifislax64-1 1 installation problem](https://user-images.githubusercontent.com/20770325/29555822-1dd4699c-8724-11e7-8450-abe58e9bef5a.png)

**Comment by MPX4132** [comment]
Download the latest version from here: https://github.com/FluxionNetwork/fluxion/archive/master.zip
Then run it: ./fluxion.sh

**Comment by 2009h** [comment]
Thank you very much
![wifislax64-1 1](https://user-images.githubusercontent.com/20770325/29556311-bf6e77e2-8725-11e7-837b-79f7cf249d77.png)

**Comment by MPX4132** [comment]
Oh, awesome! You’re the first to test that new system, good thing it worked.

**Comment by Lookkin** [comment]
So. I was having the same problem and after updating the master now I get a denied access error. Any idea how to fix it? thanks.

**Comment by MPX4132** [comment]
@Lookkin Are you on a Rapsberry Pi or something low power like that?

**Comment by Lookkin** [comment]
It's an old HP laptop (bought it in 2011) with an AMD A8 processor and 6GB of ram. @MPX4132

**Comment by MPX4132** [comment]
The problem you described sounds like something wrong with your system. Fluxion doesn't deal with permission, plus, it runs as root, so it should not give permission errors.

**Comment by Lookkin** [comment]
I have been messing a lot with it and I managed to download the latest version but I still get the loop with and error that says: 
Reading Package list... done
Building dependecy tree
Reading state information.... done
E: unable to locate package php-cgi
lib/installer/InstallerUtils.sh : line 275: unprep_package_manager: command not found
and stays on a loop.
Any idea on could the problem be? @MPX4132

**Comment by MPX4132** [comment]
@Lookkin Fluxion is trying to install `php-cgi` and it's not available in your distro's repository. You need to figure out how to install it on your system.

**Comment by MPX4132** [comment]
@Lookkin Does your system use `pacaur`, `yaourt` or `pacman`?
You can check by doing:
```
which pacaur; which yaourt; which pacman
```
If a path is returned, you're using one of those.

**Comment by Lookkin** [comment]
It did nothing when I typed it. @MPX4132

**Comment by MPX4132** [comment]
Run the diagnostics script.
