### ISSUE TITLE
 "handle_ probe_ Req: Send failed"  error prompt

### ISSUE THREAD

**Issue by QianSong1** [FluxionNetwork/fluxion#1113]
#### Summary

The new version (6.9) will show the "handle_ probe_ Req: Send failed"  prompt in about 10 minutes, unable to connect the fake wifi with my phone.

##### What is the current behaviour?

[https://img-mid.csdnimg.cn/release/static/image/mid/ask/132776030956166.jpg?x-oss-process=image/auto-orient,1](url)

#### How to reproduce
Create fishing hotspots normally, and they will appear in about 10 minutes

#### Possible causes of this problem

In the script [fluxion. sh], when using [airmon-ng] to check for interference with the wireless network card process, the process check and killing is not complete. The error message [handle_probe_Req: Send failed] will appear, so the fake WiFi hotspot stops working.

**Comment by cjb900** [comment]
You again are not giving any information on your setup or following the issue template properly. No one is psychic or has a crystal ball here.
