### ISSUE TITLE
【handle_ probe_ Req: Send failed】error prompt

### ISSUE THREAD

**Issue by QianSong1** [FluxionNetwork/fluxion#1114]
#### Summary

The new version (6.9) will show the "handle_ probe_ Req: Send failed" prompt in about 10 minutes, unable to connect the fake wifi with my phone.

#### What is the current behaviour?

[https://img-mid.csdnimg.cn/release/static/image/mid/ask/132776030956166.jpg?x-oss-process=image/auto-orient,1](url)
![image](https://user-images.githubusercontent.com/101644710/192077776-85d706f0-238a-4fd1-a7e8-0ae288e1f4c1.png)

#### How to reproduce
Create fishing hotspots normally, and they will appear in about 10 minutes

#### If the current behaviour is a bug, please provide the steps to reproduce it.

Create fishing hotspots normally
10 minutes latter
![image](https://user-images.githubusercontent.com/101644710/192077776-85d706f0-238a-4fd1-a7e8-0ae288e1f4c1.png)

#### What do you think the expected behaviour should be?

The error message 【handle_ probe_ Req: Send failed】 will not appear, and fake WiFi should not stop working

#### If this is a feature request, what is the motivation or use case for the added feature?
Fix the error and prevent the fake WiFi from stopping working

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
Personally, I believe that the possible cause of this problem is true after verification

In the script [fluxion. sh], when [airmon-ng] is used to check the interference to the wireless network card process, the process check and termination are not completed. The error message [handle_probe_Req: Send failed] is displayed, so the pseudo WiFi hotspot stops working.

After I added the command [airmon-ng check kill] at the beginning of the script [fluxion. sh], this error disappeared, and the fake WiFi has been working for a long time without any problems. I hope the R&D brother can optimize it. Thank you

#### Expected behavior

The error message 【handle_ probe_ Req: Send failed】 will not appear, and fake WiFi should not stop working

**Comment by cjb900** [comment]
If running ``airmon-ng check kill`` fixes your issue this is not a problem with fluxion but an issue with either your Linux distro or the wifi adapter/chipset you are using. ``airmon-ng check kill`` terminates process in your distro that can cause issues with wifi hacking. This is already a known which is why fluxion has a `-k` flag you can use when starting fluxion wich runs the `airmon-ng check kill` while starting fluxion.

**Comment by QianSong1** [comment]
Wow, I see. Thank you very much
