### ISSUE TITLE
Captive portal site folder is empty

### ISSUE THREAD

**Issue by ragsmax** [FluxionNetwork/fluxion#112]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion crashes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*

#### What do you think the expected behaviour should be?
*What do you think should happen?*

### Specs
*Paste the output of `./script/diagnostics.sh`*

**Comment by MPX4132** [comment]
https://github.com/FluxionNetwork/fluxion/issues/100

**Comment by usama7628674** [comment]
You just need to download the portals/sites. They're not included by default anymore, since it was getting pretty large (file size).
If you're using git to download the project, download it with submodules (sites):

git clone --recursive git@github.com:FluxionNetwork/fluxion.git

**Comment by ragsmax** [comment]
Thank you
