### ISSUE TITLE
Stuck in starting captive portal access point 

### ISSUE THREAD

**Issue by Jaypanchal1401** [FluxionNetwork/fluxion#1122]
Cannot get Fluxion starts the Captive Portal AP, it always gets stuck at that step of the attack. I know this issue has been treated many times, but I've been unable to solve and that's why I'm asking for your help.

![16691306760312854393544309574698](https://user-images.githubusercontent.com/83592890/203353045-af780e29-0520-42bd-ba0e-4417b6a1aa69.jpg)

Version:- latest

**Comment by cjb900** [comment]
you did not fill out the full issue template properly. So this is getting closed.

**Comment by Jaypanchal1401** [comment]
Why

**Comment by Jaypanchal1401** [comment]
Which template

**Comment by cjb900** [comment]
![image](https://user-images.githubusercontent.com/47070308/203353947-83dd8bb0-24cb-4e38-8b16-71aa2f01432a.png)
