### ISSUE TITLE
"Select SSL certificate source for captive portal" step in captive portal attack not existing/showing

### ISSUE THREAD

**Issue by ialexandridis** [FluxionNetwork/fluxion#1123]
### Bug Report
yes
#### Summary
When i run captive portal attack after i get the handshake, i run the steps normally but the one step with ssl certificate never shows up, like its not existing, and moves to the next one. Using Atheros ar9271 on parrotOS (no VM).
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### Expected behavior
the correct behavior must be showing the step, like it should.

**Comment by cjb900** [comment]
Yes that is normal and ad far as i know the ssl cert is still created.
