### ISSUE TITLE
help with this error while installing 

### ISSUE THREAD

**Issue by Kudamass** [FluxionNetwork/fluxion#1125]
└─# git clone https://github.com/FluxionNetwork/fluxion.git
Cloning into 'fluxion'...
remote: Enumerating objects: 7959, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (42/42), done.
error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
error: 3707 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by cjb900** [comment]
This is an internet connection of some kind. Not any issues with fluxion. As you can see i can git clone fluxion with no issues. I would try either re-cloning it and if that fails try downloading it from your browser. If that still fails you have an internet connection issue somewhere that we can't help from here.
 
![image](https://user-images.githubusercontent.com/47070308/207462385-9bb0bbbe-c8d2-4ea6-93c7-340409907964.png)

**Comment by Kudamass** [comment]
okay .i will try changing my internet connection and see what happens.

**Comment by cjb900** [comment]
its also possible this is an issue with something in your linux distro like git isn't installed and or working properly. If another internet connection doesn't help you can try reinstallig git and see if that helps.

**Comment by Kudamass** [comment]
you have been a great help .it was the network . i used vpn and the connection was stable long enough for the download to complete. many thanks 

─# git clone https://github.com/FluxionNetwork/fluxion.git
Cloning into 'fluxion'...
remote: Enumerating objects: 7959, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 7959 (delta 17), reused 48 (delta 15), pack-reused 7901
Receiving objects: 100% (7959/7959), 32.74 MiB | 364.00 KiB/s, done. 
Resolving deltas: 100% (3936/3936), done.
