### ISSUE TITLE
Hello, I am having some trouble with fluxion/linset: When I give the command to scan all channels in order to find wireless networks, the list remains blank even after several minutes...  the scanner doesn

### ISSUE THREAD

**Issue by Saurabh414-hub** [FluxionNetwork/fluxion#1138]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by ElongatedTusk** [comment]
Can you say what wireless adapter you're using and the driver, please? 

Output of  `lsusb' will display your wireless adapter if it is a USB adapter. 

Also the output of `iw phy phyX info` where X = the number assigned to your wireless adapter would be helpful.

**Comment by Saurabh414-hub** [comment]
> Can you say what wireless adapter you're using and the driver, please?
> 
> Output of `lsusb` will display your wireless adapter if it is a USB adapter.
> 
> Also the output of `iw phy phyX info` where X = the number assigned to your wireless adapter would be helpful.

**Comment by Saurabh414-hub** [comment]
I am not using an external wireless adaptor, I am using inbuild in laptop 
![Screenshot (25)](https://user-images.githubusercontent.com/125311223/219569372-30174a5a-f8c8-4ed7-8cb2-478c3433add9.png)
![Screenshot_2023-02-17_12-09-14](https://user-images.githubusercontent.com/125311223/219569448-ea9283c3-0bca-4f83-9f34-dfd6861fc2bc.png)

**Comment by cjb900** [comment]
If you are using a VM (VirtualBox or VMware) you can't use the built in wifi adapter in your computer. You will have to get a supported USB one and pass it through to the VM or run kali either live from a USB or dual boot. Let the st of supported wifi adapter/chipset can be found below.

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by ElongatedTusk** [comment]
I don't suspect you'll have much luck with Fluxion in a virtual machine. Fluxion needs access to your wireless adapter in order to change it to monitor mode to scan. Assuming your wireless adapter even does support monitor mode, it probably won't in the virtual machine.

**Comment by cjb900** [comment]
@ElongatedTusk many have used VM's with fluxion successfully. Its just that VM's like VMware and VirtualBox are not able to use the built in wifi adapter in computer. thats why i said a USB wifi adapter would be needed if they were using a VM. If they don't want to use a VM they can try running kali from a live USB or dual boot. But i can't say if their built in wifi adapter will work properly for wifi hacking and a USB wifi adapter may be needed either way.

**Comment by chacha121** [comment]
> If you are using a VM (VirtualBox or VMware) you can't use the built in wifi adapter in your computer. You will have to get a supported USB one and pass it through to the VM or run kali either live from a USB or dual boot. Let the st of supported wifi adapter/chipset can be found below.
> 
> Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB) MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB) MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB) Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB) Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB) Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB) Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB) Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB) Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver) Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

i am using parrot os (dual boot); still getting the same error, not able to scan any network
i have pcie card (TP-LINK Archer T5E AC1200)
heres the ss of lsusb
![image](https://github.com/FluxionNetwork/fluxion/assets/113207752/b48fffa5-62b0-44bb-b509-8e31d4782541)

**Comment by cjb900** [comment]
Intel wifi adapters can be hit or miss if they will work well for wifi hacking. I would recommend getting a supported USB wifi adapter from the list i posted above and go from there if you still have issues.

**Comment by chacha121** [comment]
> Intel wifi adapters can be hit or miss if they will work well for wifi hacking. I would recommend getting a supported USB wifi adapter from the list i posted above and go from there if you still have issues.

![image](https://github.com/FluxionNetwork/fluxion/assets/113207752/2ca4c518-8863-44af-9011-1b51492ad056)
but it meets all the requirement as stated (supported interface modes)
i.e. AP and MONITOR

**Comment by cjb900** [comment]
A wifi adapter can support all the modes but still does not mean it will work well for wifi hacking stuff. If you can't get it to work then getting a better supported USB wifi adapter is all we can suggest.
