### ISSUE TITLE
cannot auto-istall missing dependancies

### ISSUE THREAD

**Issue by maxxigan** [FluxionNetwork/fluxion#1142]
[ Missing dependencies: try to install using ./fluxion.sh -i ]     
even when i run ./fluxion.sh - i it says the same error.
am using kali linux debian.
any suggestions?

**Comment by cjb900** [comment]
If you are still having this issues it would help to have a screenshot what you are seeing. What i can say though is that i have a fresh live USB of kali with all the updates installed and running `./fluxion.sh -i` installed all the missing dependencies with no errors and running `./fluxion.sh` afterwards gives no errors.

**Comment by vbunny503** [comment]
Hi Guys,
I too ran into same issue while i was setting up Fluxion on my new Kali installation. You are right,  running command "./fluxion.sh -i" would do nothing. here is what i have tried.
1. I updated Inventory and then upgraded my Kali (sudo apt update followed by supo apt upgrade -y)
2. i launched fluxion and i see couple of dependencies are missing like , bc, DKMS, MDK4, pyrit etc.
3. i individually installed the missing dependencies using ("sudo apt-get install bc" , i followed the same for all and in 5-10 minutes i had my fluxion running fine. 
The script to install missing dependencies isnt working in latest version of Fluxion(6.11). It used to work in previous version though.

**Comment by yamix007** [comment]
you'll have to 

- sudo update
- sudo dist-upgrade
- install linux headers first
- sudo apt install airgeddon ( the dependencies will be installed from this tool after you open it )
- then use fluxion later & the dependencies will be installed, there will be only one missing at the end & you'll have to manually install it
