### ISSUE TITLE
I've been getting this error a lot lately. Please I need help :)

### ISSUE THREAD

**Issue by R3DB4T** [FluxionNetwork/fluxion#1143]
dpkg: error: duplicate file trigger interest for filename '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders' and package 'libgdk-pixbuf-2.0-0:amd64'
E: Sub-process /usr/bin/dpkg returned an error code (2)

Im running the command sudo ./fluxion.sh -i     to launch the .sh file on my Kali Linux machine.

**Comment by cjb900** [comment]
I have a fresh live boot of Kali with all the updated installed and running `./fluxion.sh -i` works as expected with no errors and all the missing dependencies installed. So i'm guessing your issue is something in your kali setup or an issue with dpkg and not an issue with fluxion
