### ISSUE TITLE
Common issue

### ISSUE THREAD

**Issue by hugofpsilva** [FluxionNetwork/fluxion#1145]
I was getting the same issue as many users before with a fresh install of Kali.
```
./fluxion.sh: line 255: format_center_literals: command not found
./fluxion.sh: line 262: format_center_literals: command not found
./fluxion.sh: line 270: installer_utils_check_update: command not found
./fluxion.sh: line 289: installer_utils_check_dependencies: command not found
./fluxion.sh: line 290: installer_utils_run_dependencies: command not found

Dependency installation failed!
Press enter to retry, ctrl+c to exit...
```

I think I figured out the cause.

What caused this for me was having a space on the working directory leading up to fluxion.

For example, running

`sudo '/home/kali/a b/fluxion/fluxion.sh'`

triggers the error, while

`sudo '/home/kali/a/fluxion/fluxion.sh'`

doesn't, without any other change and on the same machine.

Please do check if you can replicate this "solution" and get back to me.

Thanks 😄

**Comment by cjb900** [comment]
I can confirm that having a space in any part of the directory path that fluxion is run from does indeed cause these errors and removing any spaces does not cause any errors. this is good to know for anyone else that comes here having similar issues. Thanks for finding this out.
