### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by akbar091202** [FluxionNetwork/fluxion#1146]
I'm confused with fluxion now, when using kali linux it's also like this 
![Screenshot_20230331-045950](https://user-images.githubusercontent.com/110935872/228974203-656bccca-afde-489f-b7e9-750837b843c8.png)

**Comment by cjb900** [comment]
Well its pretty obvious. You need to run fluxion as root which would require a rooted android phone. But for wifi hacking on a phone with a tool like fluxion you will also need a phone that supports OTG and a USB wifi adapter that supports monitor mode, AP mode and VIF. But one thing to note is that fluxion is not coded to work from a phone even if you were able to meet all the requirements fluxion wont work.
