### ISSUE TITLE
Telegram notification with password used on the Captive Portal

### ISSUE THREAD

**Issue by datrix88** [FluxionNetwork/fluxion#1148]
I integrated Telegram notifications on Fluxion to receive notifications when a password is entered in the captive portal.
Incorrect and correct passwords are notified.

Obviously it is necessary to have internet on the machine where the attack is being performed.

I create a Fork with this feature:

https://github.com/datrix88/fluxion

I hope it can be useful to someone :)

**Comment by elhaddajiOtmane** [comment]
Nice

**Comment by IvanCR-ADIDAS** [comment]
How to use the bot with internet, if my network card is in monitor mode?

**Comment by cjb900** [comment]
@IvanCR-ADIDAS please open an issue on the github for this fork version of fluxion. We don't want to clog this up with questions related to a forked version fo fluxion
