### ISSUE TITLE
airodump-ng not working within fluxion.sh

### ISSUE THREAD

**Issue by K0K0SHA** [FluxionNetwork/fluxion#1149]
#### Summary
Fluxion unable to control network interfaces properly, even when run as sudo. 

##### What is the current behaviour?
Aircrack-ng suite is installed and 100% tested working including airodump-ng. Fluxion seems to successfully bring down the network interface which the user selects, but the "Fluxion Scanner" which is like a frontend for airodump-ng shows no access points. It shows no other information. Thus, Fluxion is unable to proceed with any attack, due to the "Fluxion Scanner" not capturing any AP's. This issue may be worked around by manually enabling monitor mode on a certain NIC using sudo airmon-ng start prior to launching Fluxion. In this case, Fluxion is shown to proceed properly, and airodump-ng works as normall.

#### How to reproduce
This issue might be hard to reproduce because it might be hardware specific. Fluxion works on a certain laptop, on one version of Fluxion, but not on another laptop with a different version. 

##### If the current behaviour is a bug, please provide the steps to reproduce it.
This is a bug, but it seems to have the workaround of manually enabling monitor mode on your scanner interface. 

##### What do you think the expected behaviour should be?
It should launch airodump-ng on the NIC. Airodump is shown working on the machine.

**Comment by cjb900** [comment]
Because you did not fill out the issue template properly we have no way to properly help
