### ISSUE TITLE
Fluxion freezes on step 'Starting Captive Portal access point service...'

### ISSUE THREAD

**Issue by HashTagOS** [FluxionNetwork/fluxion#115]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behaviour?
Fluxion freezes on the follow step: "Starting Captive Portal access point service..."

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Regular usage

#### What do you think the expected behaviour should be?
Portal Capture Details Screen appears.

### Specs
[ Interface (wlan1) Info ]
Device: phy0
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n

ioctl(SIOCSIWMODE) failed: Device or resource busy
22:03:30  Trying broadcast probe requests...
22:03:30  Injection is working!
22:03:32  Found 9 APs

...

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd
[ Aircrack-ng Info ]
  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org
[ System Info ]
Linux version 4.6.0-kali1-amd64 (devel@kali.org) (gcc version 5.4.0 20160609 (Debian 5.4.0-6) ) #1 SMP Debian 4.6.4-1kali1 (2016-07-21)

**Comment by MPX4132** [comment]
You edited the output, run it again and paste the raw output.

**Comment by HashTagOS** [comment]
Added top part and excluding private portion, sincerely.

**Comment by MPX4132** [comment]
Whoops, I forgot it shows neighboring APs when it runs the test. That's fine, I just wanted to make sure you're not using a device that needs drivers patched (Ralink Tech.).

**Comment by MPX4132** [comment]
Well, the device I use to test the program has the same chipset as yours, and you're using the same driver as mine, meaning that device is perfectly fine. I think there may be a process interfering with the interface. Run fluxion in killer mode:
```
export FLUXIONWIKillProcesses=1; ./fluxion.sh
```

**Comment by MPX4132** [comment]
@HashTagOS Let us know weather you got it working or not.

**Comment by Eweleval** [comment]
*] Starting Captive Portal access point service...
Warning: locale not supported by Xlib, locale set to C
      

this is my problem and i have tried the fixed and it still ain't working

**Comment by Eweleval** [comment]
lenovo g510s touchscreen
using kali linux rolling

**Comment by deltaxflux** [comment]
Which wireless card are you using?

**Comment by Eweleval** [comment]
Qualcomm Atheros AR956x Wireless Network adapter"
