### ISSUE TITLE
Problem with hidden Wifi

### ISSUE THREAD

**Issue by CenteredRay** [FluxionNetwork/fluxion#1150]
#### Summary

The attack is not possible on WiFi configured as hidden/hide SSID
##### What is the current behaviour?
When you try to launch the attack (after you grab the hash using fluxion) you will get into infinity of "Starting Captive Portal access point service..." forever, until you forcibly kill the process using Ctrl+Z and sometimes u can shut fluxion down using Ctrl+C.
#### How to reproduce
Find/Create a Wifi configured as hidden, which shows up as `<length: THELENGTH>` on airmon commands, and shown as blank text (nothing at all) in list when choosing network, and then it shows NaN or smth like that on top of the terminal during the next steps.

##### What do you think the expected behaviour should be?

It should ask me for the SSID to use, instead of bugging out like that.

**Comment by cjb900** [comment]
Fluxion has never been able to attack hidden AP's. Create a pull request with the changes to add this and the devs and consider if this should be added or not.
