### ISSUE TITLE
Can't connect to Fake AP

### ISSUE THREAD

**Issue by tekgamerpt** [FluxionNetwork/fluxion#1152]
#### Summary
Can't connect to fake AP

##### What is the current behaviour?
I can retrieve hanshake  but when creating captive Portal it seems that web service is not running. When trying to connect, devices can't get a IP adress and also Fluxion does not detect connection atempt.
#### Expected behavior

<img width="790" alt="VirtualBoxVM_u9dSv0epva" src="https://github.com/FluxionNetwork/fluxion/assets/34514180/3df0f189-0b5e-4ab4-970c-7a4e0ce8f235">

**Comment by cjb900** [comment]
You didn't fill out the issue template properly. So per the note in the temple, this is getting closed,
