### ISSUE TITLE
the handshake checker dont appear

### ISSUE THREAD

**Issue by iyeeeed** [FluxionNetwork/fluxion#1155]
when i start the deauthing to get the handshake a handshake captor window should be appear to see if the handshake is captured or not as you can see in the screenshot using kali linux
![kali-linux-2023 2-vmware-amd64 - VMware Workstation 17 Player (Non-commercial use only) 23_06_2023 13_01_54](https://github.com/FluxionNetwork/fluxion/assets/137417162/6fc8ea07-ee2b-434e-8fdf-fc725d72eb3f)
any solutions? pls help

**Comment by cjb900** [comment]
Again you are still not filling out the issue template properly. So for a third time this is getting closed.
