### ISSUE TITLE
Chinese translation update

### ISSUE THREAD

**Issue by Wubeizi** [FluxionNetwork/fluxion#116]
I wanted to find yesterday's post, but it was closed and I had to start a new post!

This time I updated some translation errors and some suitable for not ordinary technical instructions for the user

I did not find the following two words in Chinese .lang! please help me!
![snipaste_20170823_094700](https://user-images.githubusercontent.com/29472751/29595135-32716f20-87e8-11e7-8420-fc6a22e7f745.png)
 
I have a network blockade, had to paste to you!

中文.lang : 

#!/bin/bash
# Chinese

FLUXIONInterfaceQuery="请选择你要调用的网卡设备"
FLUXIONUnblockingWINotice="解除所有占用无线接口设备的进程..."
FLUXIONFindingExtraWINotice="查询USB外部网卡接口设备..."
FLUXIONRemovingExtraWINotice="正在移除USB外部网卡接口设备..."
FLUXIONFindingWINotice="寻找可用的USB外部网卡接口设备..."
FLUXIONSelectedBusyWIError="选择的USB外部网卡接口设备正在被调用!"
FLUXIONSelectedBusyWITip="Run \"export FLUXIONWIKillProcesses=1\" before FLUXION to use it."
FLUXIONGatheringWIInfoNotice="采集接口信息..."
FLUXIONUnknownWIDriverError="无法确定接口驱动程序!"
FLUXIONUnloadingWIDriverNotice="等待接口 \"\$wiSelected\" 卸载..."
FLUXIONLoadingWIDriverNotice="等待接口 \"\$wiSelected\" 加载..."
FLUXIONFindingConflictingProcessesNotice="自动查询干扰Fluxion运行的进程..."
FLUXIONKillingConflictingProcessesNotice="结束干扰Fluxion运行的进程..."
FLUXIONPhysicalWIDeviceUnknownError="${CRed}无法确定接口的物理设备!"
FLUXIONStartingWIMonitorNotice="启动监听模式..."
FLUXIONMonitorModeWIEnabledNotice="${CGrn}接口监听模式开启."
FLUXIONMonitorModeWIFailedError="${CRed}接口监听模式失败!"
FLUXIONStartingWIAccessPointNotice="启动访问点接口..."
FLUXIONCannotStartWIAccessPointError="${CRed}无法创建虚拟钓鱼热点$CClr, 请返回重试!"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONStartingScannerNotice="启动扫描, 请稍等..."
FLUXIONStartingScannerTip="如果出现目标AP, 关闭FLUXION Scanner以继续下一步."
FLUXIONPreparingScannerResultsNotice="综合扫描的结果获取中,请稍等..."
FLUXIONScannerFailedNotice="你的无线网卡好像不支持 (没有发现APs)"
FLUXIONScannerDetectedNothingNotice="没有发现访问点, 请返回重试..."
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONHashFileDoesNotExistError="Hash文件不存在!"
FLUXIONHashInvalidError="${CRed}错误$CClr, 无效的Hash文件!"
FLUXIONHashValidNotice="${CGrn}成功$CClr, Hash效验完成!"
FLUXIONPathToHandshakeFileQuery="输入捕获到握手包存放的路径 $CClr(例如: /.../dump-01.cap)"
FLUXIONAbsolutePathInfo="输入握手包存放的绝对路径"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CaptivePortalStaringAPServiceNotice="开始建立钓鱼热点AP..."
CaptivePortalStaringAPRoutesNotice="启动钓鱼热点AP路由服务..."
CaptivePortalStartingDHCPServiceNotice="启动接入点DHCP服务作为守护进程..."
CaptivePortalStartingDNSServiceNotice="启动接入点DNS服务作为守护进程..."
CaptivePortalStartingWebServiceNotice="启动钓鱼热点作为守护进程..."
CaptivePortalStartingJammerServiceNotice="启动接入点干扰器作为守护进程..."
CaptivePortalStartingAuthenticatorServiceNotice="启动验证器脚本..."
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerChannelQuery="选择要扫描的信道,开启后会新打开一个页面,按CTRL+C关闭停止扫描.扫描结果标记为绿色的AP为有客户端连接的！"
FLUXIONScannerChannelOptionAll="扫描所有信道(推荐用这个) "
FLUXIONScannerChannelOptionSpecific="扫描指定信道"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerChannelSingleTip="单一信道"
FLUXIONScannerChannelMiltipleTip="多个信道"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONScannerHeader="FLUXION 扫描仪"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONAPServiceQuery="选择攻击方式"
FLUXIONAPServiceHostapdOption="钓鱼热点破解 (${CRed}推荐用这个)"
FLUXIONAPServiceAirbaseOption="Rogue AP - airbase-ng (缓慢)"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CaptivePortalVerificationMethodQuery="请选择验证密码方式"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
DialogQueryHashSource="选择一种方式来检查握手包获取状态"
FLUXIONHashSourceQuery="选择一种方式来检查握手包获取状态"
FLUXIONHashSourcePathOption="检测文件的路径"
FLUXIONHashSourceRescanOption="握手包目录(重新扫描)"
FLUXIONFoundHashNotice="发现目标热点的Hash文件."
FLUXIONUseFoundHashQuery="你想要使用这个文件吗?"
FLUXIONHashVerificationMethodQuery="选择Hash的验证方法"
FLUXIONHashVerificationMethodPyritOption="验证码 (${CGrn}推荐用这个$CClr)"
FLUXIONHashVerificationMethodAircrackOption="aircrack-ng 验证 (不推荐)"
CaptivePortalCertificateSourceQuery="选择钓鱼认证门户的SSL证书来源"
CaptivePortalCertificateSourceGenerateOption="创建SSL证书"
CaptivePortalCertificateSourceRescanOption="检测SSL证书 (${CClr}再次搜索$CGry)"
CaptivePortalInterfaceQuery="选择钓鱼热点的认证网页界面"
CaptivePortalGenericInterfaceOption="通用认证网页"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
HandshakeSnooperMethodQuery="选择一种方式来检查握手包获取状态"
HandshakeSnooperMonitorMethodOption="监听模式 (${CYel}被动$CClr)"
HandshakeSnooperAireplayMethodOption="aireplay-ng 解除认证方式 (${CRed}侵略性$CClr)"
HandshakeSnooperMdk3MethodOption="mdk3 解除认证方式 (${CRed}侵略性,不推荐用这个$CClr)"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONAttackQuery="请选择一个功能模块"
FLUXIONAttackInProgressNotice="${CCyn}\$FLUXIONAttack$CClr attack in progress..."
FLUXIONSelectAnotherAttackOption="选择启动攻击方式"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONGeneralBackOption="${CRed}返回"
FLUXIONGeneralExitOption="${CRed}退出"
FLUXIONGeneralRepeatOption="${CRed}如未找到可用的USB外接网卡,请重新插入网卡后选择此项扫描网卡设备！"
FLUXIONGeneralNotFoundError="未找到"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FLUXIONCleanupAndClosingNotice="清理进程并退出"
FLUXIONKillingProcessNotice="Killing ${CGry}\$targetID$CClr"
FLUXIONDisablingMonitorNotice="关闭监听模式界面"
FLUXIONDisablingExtraInterfacesNotice="关闭USB外部网卡接口"
FLUXIONDisablingPacketForwardingNotice="关闭 ${CGry}转发数据包"
FLUXIONDisablingCleaningIPTablesNotice="清理 ${CGry}iptables"
FLUXIONRestoringTputNotice="恢复 ${CGry}tput"
FLUXIONDeletingFilesNotice="删除 ${CGry}文件"
FLUXIONRestartingNetworkManagerNotice="重启 ${CGry}网络管理"
FLUXIONCleanupSuccessNotice="所有进程清理完成!"
FLUXIONThanksSupportersNotice="再次感谢使用Fluxion!"
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# FLUXSCRIPT END

**Comment by MPX4132** [comment]
Unfortunately, that's not possible. The attacks are named after the directory that contains them, meaning, if you changed the directory names under `fluxion/attacks/` then those will change.

**Comment by MPX4132** [comment]
Give me a few minutes, I'll add support for that.

**Comment by Wubeizi** [comment]
OK! The two words are not translated :)

**Comment by MPX4132** [comment]
I'm gonna need more time. Bash has trouble with Chinese symbols being used in data structures.

**Comment by Wubeizi** [comment]
I personally recommend no translation, because if you replace it in Chinese, the coding problem may be unable to run

**Comment by MPX4132** [comment]
Sorry, I took a break and forgot about it. I'll see if I can come up with something tomorrow (it's night time here). Maybe I should add descriptions next to the attacks.

**Comment by Wubeizi** [comment]
I use the tools you developed for a long time, I think that if you do not understand the technology used by ordinary people, no operating instructions will be very difficult! Or even give up this very good tool!

I suggest adding a few recommended options or a guide to each option in each option! So that can not let those who can not use the technical users!

Hope my advice can help you!

PS: my English is not good, I still study! Our conversations are translated by google! If there is anything wrong please forgive me!

**Comment by Wubeizi** [comment]
I use your tool for a long time! Feel very easy to use, the operation is also simple!

But for those who do not technology, the use will be very difficult to use, or even give up the use of direct!

So, I suggest you add a guide to the tool and some instructions!

So that many people can use this good tool! More and more people like the tools you developed

PS: I am short English, still learning! Our conversations are google translation! If there is anything wrong please forgive me!

**Comment by ww18877317962** [comment]
When the input captures the absolute path stored after the handshake package, display the Hash file does not exist!
