### ISSUE TITLE
fluxion required two network card or only one will serve the prepose? 

### ISSUE THREAD

**Issue by Mash772** [FluxionNetwork/fluxion#1162]
I am running kali on windows 11 vm ware while selecting attack with fluxion it is giving error like "unable to start captive portal interface returning fluxion" or interface reservation failed fluxion"

please help. 
i am using one network capture card.

**Comment by cjb900** [comment]
This is usually a sign that you are using a wifi adapter that does not properly support one or more of the following monitor mode, AP mode and VIF. You can try rebooting your whole computer unplug and re-plug in your wifi adapter and then before starting fluxion run `sudo airmon-ng check kill` and see if that helps. If not you can try using this forked version of fluxion https://github.com/usama7628674/fluxion-1 and see if that works. If both fail you probably have an unsupported wifi adapter and would have to get a better supported one from our list below.

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)
MT7921AUN <- present in Alfa awus036axm or awus036axml  or comfast-CF-953AX or comfast-CF-951AX

**Comment by Mash772** [comment]
TP-Link Archer T2U PLUS [RTL8821AU] card i am using. is it compatible . i am able to monitor capture handshake but facing issue in fluxion. is there any other tool i can use except fluxion?

**Comment by cjb900** [comment]
🤦‍♂️ you obviously didn't look at our list of known supported adapters/chipsets if you are asking a question like that. No that is a crap chipset and would be why you are having issues. You would be better off ditching that adapter and getting on from the list I provided

**Comment by Mash772** [comment]
![Screenshot 2023-09-16 094019](https://github.com/FluxionNetwork/fluxion/assets/145143036/dc4a6d5c-9e76-4a56-8541-1c2288a8d852)
please refer screen shot. also wanted to know to make access point for evil twin attack. do i required two network card.

**Comment by Mash772** [comment]
> 🤦‍♂️ you obviously didn't look at our list of known supported adapters/chipsets if you are asking a question like that. No that is a crap chipset and would be why you are having issues. You would be better off ditching that adapter and getting on from the list I provided

i have checked that. your given list. and just wanted to confirm weather it will work or not. ill try get one from above list.

**Comment by cjb900** [comment]
No fluxion can work with one wifi adapter if it is from our list. Anything not on that list we can not guarantee if it will work. Also, fluxion only works with wifi adapters not Ethernet cards like the one you pointed to.

**Comment by Mash772** [comment]
when i choose 2nd option it says "unable to start captive portal interface returning fluxion"

**Comment by cjb900** [comment]
If you are referring to the second option as your TP-Link Archer T2U Plus [RTL8821AU]. Again that is a crap wifi adapter for wifi hacking and why you are having issues. So again you need to get a better supported one from the list I provided.

**Comment by Mash772** [comment]
Alfa AWUS036ACH is available to buy. . please confirm will it working perfectly in fluxion .
