### ISSUE TITLE
Need to use "airmon-ng check kill" prior to launching in Blackarch

### ISSUE THREAD

**Issue by Troodon7** [FluxionNetwork/fluxion#1167]
#### Summary

When launching Fluxion, everything seems to launch and work as expected, however I find that I am forced to run "airmon-ng check kill" prior to running in Blackarch otherwise it does not show any AP's. I feel like this could be an easy add to the script and I was going to modify the launcher in sbin but I figured if it can be resolved here I will just update after. 

##### What is the current behaviour?

fluxion does not find access points 

#### How to reproduce
launch fluxion on a freshly installed and updated Blackarch system. 
##### If the current behaviour is a bug, please provide the steps to reproduce it.

This is not a bug in my opinion but some may see it that way. 
##### What do you think the expected behaviour should be?

When fluxion is launched, during startup it should run the check kill in order to work as expected.
##### If this is a feature request, what is the motivation or use case for the added feature?
This could be considered a feature request. The idea would be specifically for blackarch though (with xfce)
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
This did not seem to work (ran as sudo just in case) "Error lib folder not found"

#### Expected behavior

I expected to launch fluxion (as sudo) and have the following happen before:
airmon-ng check kill
fluxion.sh 
***ADD ON CLEANUP***
systemctl restart systemd-networkd.service
systemctl restart NetworkManager

**Comment by cjb900** [comment]
This is already an option by running fluxion with `-k` as references here https://github.com/FluxionNetwork/fluxion/wiki/Flags-&-Preferences

**Comment by Troodon7** [comment]
Much appreciated!
