### ISSUE TITLE
Feature Request: Support for Custom Terminal Emulators

### ISSUE THREAD

**Issue by rxtsel** [FluxionNetwork/fluxion#1168]
# Feature Request: Support for Custom Terminal Emulators

## Description
I would like to propose the addition of a feature that allows users to easily switch the default terminal emulator used by Fluxion to a custom one, such as Alacritty. Currently, Fluxion relies on xterm, and I believe it would be beneficial to offer flexibility in choosing the terminal emulator based on user preferences.

## Proposed Implementation
I suggest introducing a configuration option or environment variable that users can set to specify their preferred terminal emulator. This way, changing the terminal emulator would only require modifying this variable, making it more convenient for users who prefer alternatives to xterm.

## Example Use Case
As a user, I would like to use Alacritty instead of xterm as my terminal emulator. I envision being able to set an environment variable, such as `FLUXION_TERMINAL`, to "alacritty," and have Fluxion scripts automatically use Alacritty for all terminal interactions.

## Additional Context
This feature would enhance the user experience for those who have a preference for different terminal emulators, and it aligns with the trend of users exploring alternatives to traditional terminal emulators like xterm.

**Comment by cjb900** [comment]
In the entire history of this tool you are the first I've ever seen asking to use something other then xterm. If there was a large influx of people coming here asking to use something else may be support could be added. But that's not the case and with xterm being so widely used and supported in almost every Linux distro (not saying alacritty isn't widely supported) i don't see support for other terminal emulators like alacritty being added. If you wanted to submit a poll request adding support for alacritty may it can get added then. Also you could just fork Fluxion and then add support for those that want to use it.
