### ISSUE TITLE
Unable to run Fluxion on Mac OS

### ISSUE THREAD

**Issue by elgplayer** [FluxionNetwork/fluxion#117]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion crashes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*
![fluxion problem](https://user-images.githubusercontent.com/6267293/29614994-8b4483ac-880c-11e7-8f2b-ce27ed5c987f.jpeg)
So I have a problem, when trying to install fluxion on Mac OS. I know its designed to only work on Linux but I think it also should work on Mac because its based on UNIX. Before I ran the install, sudo ./fluxion.sh I ran `export DISPLAY=:0`. Not running gave me issues because it was not in a graphical shell.

#### What do you think the expected behaviour should be?
*What do you think should happen?*
It should install

### Specs
*Paste the output of `./script/diagnostics.sh`*

**Comment by Geczy** [comment]
It's  not meant to be run on mac. It is only compatible with Unix systems

**Comment by elgplayer** [comment]
But Mac is a UNIX os. So therefore I would not see why its not working.

**Comment by deltaxflux** [comment]
Because it is a kind of fork. Stop using the dark side and switch to arch. Different OS means software compatibility issues. If you really want to get into you should use an OS which fits your preferences.

**Comment by MPX4132** [comment]
It’s probabaly because I didn’t use POSIX compatible calls, which is what MacOS supports. I’ve been using MacOS for almost a decade, and I easily prefer it over Linux for its stability. It has only crashed on me twice, and both were development-induced kernel panics. Unfortunately I haven’t been able to use it recently because I packed my things away for a home renovation, and I’ve been doing development on a borrowed laptop.

**Comment by elgplayer** [comment]
But is there a chance that support for Mac OS will come?

**Comment by MPX4132** [comment]
Well, the tool is specifically designed for Linux, so I have to focus on Linux. If it’s feasable to add MacOS support I’ll do it. I just need to get my things unpacked.

**Comment by SiNaPsEr0x** [comment]
use parallels (I used it) and work correctly!

**Comment by elgplayer** [comment]
eh... k

**Comment by SiNaPsEr0x** [comment]
@elgplayer do you know parallels? search ... for macos is the best virtual.. low use GB and more efficient

**Comment by MPX4132** [comment]
I usually test with virtualbox, works completely fine. Seamless mode makes it even better if you're looking for full screen. I've noticed it runs smoother on MacOS than it does on windows. I haven't ran it on linux, though. If you're waiting on support, I suggest you use a VM for now. I don't think I'll be unpacking soon. There's a hurricane coming and it's getting pretty serious, and it just freaking went up a category about an hour ago. It's pretty distracting.

**Comment by SiNaPsEr0x** [comment]
on parallels connect alfa wifi usb directly to VM ... the kernel modules is more integrated in linux OS with other partner wich virtualbox, vmware etc... parallels is top for macos!

**Comment by elgplayer** [comment]
Maybe flag this issue as an enchantment

**Comment by Geczy** [comment]
Yeah I agree

I have a macbook too and this would be a nice feature, what do you think @MPX4132

**Comment by MPX4132** [comment]
Well, it seems like MacOS is similar enough to linux; it could be supported. I haven't had a chance to unpack my stuff, so I haven't used the iMac in a while. I'll take a look at the changes required and make an educated guess then. I'm thinking it's probably going to be all POSIX bs that I'll have to deal with.

**Comment by Geczy** [comment]
Do our libraries even compile on mac? Like linux kernels / drivers needed

**Comment by SiNaPsEr0x** [comment]
@Geczy is more complicated... with Parallels is more simple 🍡

**Comment by MPX4132** [comment]
Well, if you're talking about the utility libraries, they should. MacOS uses bash by default as far as I'm concerned. The only major issue I image I'll encounter is that MacOS uses an airport utility to mess with networking interfaces, everything else (ifconfig, iwconfig, ip link) are all wrappers of the airport utility (if I recall correctly).
