### ISSUE TITLE
Error: RPC Failed

### ISSUE THREAD

**Issue by inayatiphone619** [FluxionNetwork/fluxion#1170]
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 7715 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by cjb900** [comment]
You didn't fill out the issue template and gave no helpful information. So this is being closed.
