### ISSUE TITLE
Cant download php-cgi

### ISSUE THREAD

**Issue by lepex1** [FluxionNetwork/fluxion#1173]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Specs

After I executed the command `sudo ./fluxion.sh 
` I got the line `[*] php-cgi..................................... Missing!`.  Fluxion can't download this dependency automatically. Can you tell me how I can download it manually?

**Comment by cjb900** [comment]
Because you did not fill out the issue template this is getting closed.
