### ISSUE TITLE
No internet at all. Please help 

### ISSUE THREAD

**Issue by mahadidot** [FluxionNetwork/fluxion#1174]
I installed fluxion on my parrot machine.
And im trying to perform captive portal on fluxion.
But suddenly my entire machine network down.
Ethernet cable pluged in bht no internet connection.
Same. I faced same problem with Linux mint also. 

How i can fix this?

**Comment by cjb900** [comment]
Because you obviously don't know how to read and didn't properly fill out the issue temple this is getting closed.
