### ISSUE TITLE
/home/kali/fluxion/lib/ap/airbase-ng.sh: line 36: [: -eq: unary operator expected

### ISSUE THREAD

**Issue by JustGuardian** [FluxionNetwork/fluxion#1175]
##### What is the current behaviour?

[*] Starting Captive Portal access point service...
/home/kali/fluxion/lib/ap/airbase-ng.sh: line 36: [: -eq: unary operator expected
Error: any valid prefix is expected rather than "at0".

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V6.12

#### BASH Info 
GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy2
**Driver:** rtl8xxxu
**Chipset:** Realtek Semiconductor Corp. RTL8188FTV 802.11b/g/n 1T1R 2.4G WLAN Adapter
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(389)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.10
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2022, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.7  - (C) 2006-2022 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
./scripts/diagnostics.sh: line 89: pyrit: command not found
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 6.6.9-amd64 (devel@kali.org) (gcc-13 (Debian 13.2.0-9) 13.2.0, GNU ld (GNU Binutils for Debian) 2.41.50.20231227) #1 SMP PREEMPT_DYNAMIC Kali 6.6.9-1kali1 (2024-01-08)

#### Chipset
Chipset: rtl8xxxu
Chipset is not in list

AND

**Comment by cjb900** [comment]
RTL wifi chipsets are completely crap for wifi hacking and most likely the cause of your issue. You will need to get a better supported wifi adapter/chipset from this list below and then if you still have issues we can try to help from there.  

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)
MT7921AUN <- present in Alfa awus036axm or awus036axml  or comfast-CF-953AX or comfast-CF-951AX

**Comment by JustGuardian** [comment]
> RTL wifi chipsets are completely crap for wifi hacking and most likely the cause of your issue. You will need to get a better supported wifi adapter/chipset from this list below and then if you still have issues we can try to help from there.
> 
> Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB) MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB) MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB) Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB) Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB) Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB) Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB) Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB) Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver) Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe) MT7921AUN <- present in Alfa awus036axm or awus036axml or comfast-CF-953AX or comfast-CF-951AX

I forgot to stop NetworkManager with airmon-ng, now it works, sorry for the useless issue.
