### ISSUE TITLE
Stucked "Starting Captive Portal" 5Ghz only

### ISSUE THREAD

**Issue by tekgamerpt** [FluxionNetwork/fluxion#1176]
Hello
Im testing my new USB Card, the AWUS036ACM, and i'm having problem starting Captive Portal but only in 5Ghz frequency. 2.4 Ghz works fine.

<img width="493" alt="vncviewer_JZ3FjZESDQ" src="https://github.com/FluxionNetwork/fluxion/assets/34514180/46bcbceb-8d10-4d44-9d98-40d43b533528">

Its stucked here...

Am im missing something

Thank you in advance and great work

**Comment by cjb900** [comment]
You probably need to set your reg domain in your Linux system. Also before starting fluxion run `sudo airmon-ng check kill`

**Comment by tekgamerpt** [comment]
already did that. I think is a hostapd problem because with airbase-ng, AP works

**Comment by cjb900** [comment]
I know others here use that adapter with no issues. So since you did not properly fill out the issue temple we will no longer be helping here

**Comment by tekgamerpt** [comment]
Sure... Thank you anyway

**Comment by karimHI** [comment]
SAME ISSUE
