### ISSUE TITLE
Redirect to local captive portal only http requests, pass to the wan https requests

### ISSUE THREAD

**Issue by sweft54** [FluxionNetwork/fluxion#118]
### Do you want to request a *feature* or report a *bug*?
*feature*

### What is the current behaviour?
DNS redirects to local webserver all the requests

#### If the current behaviour is a bug, please provide the steps to reproduce it.
In the current behaviour this is expected

#### What do you think the expected behaviour should be?
Due to https and hsts restrictions, maybe only http requests should be redirected to local web server; https requests should pass to the wan

### If this is a feature request, what is the motivation or use case for the added feature?
The users could choose if redirect all the traffic to the local captive portal or only http requests and pass to the wan https; if https/hsts traffic is redirected to the local captive portal there will be an error without the option to go on, so the attack will be useless.

What do you think about it?
Thank you

**Comment by MPX4132** [comment]
I'm not sure I understand what you're trying to explain, let me break it down. You're suggesting we allow the forwarding of encrypted traffic to the Internet in the rogue network, correct? You're saying it would help getting sites using HSTS working, correct? If that's correct, I don't understand why you'd want that if you're trying to force the target's clients to experience a disconnection. Moreover, as far as I'm concerned, HSTS is configured on the server side and to access the server you need a working Internet connection. If you've ever experienced a captive portal re-authentication prompt, it causes all types of "Security warnings" on browsers, so I don't really understand the point of having an option to allow encrypted-traffic-only forwarding.

**I'm not rejecting your idea, I'm just not understanding the reasoning.** If you could maybe explain it a bit better for me, and everyone else that might see it the way I just did, that would be great.

**Comment by sweft54** [comment]
Hello, sorry if I wan not clear.
I'm trying to explain what's happening now: setup the evil twin with the captive portal, dhcp and everything else, deauth all clients connected to the real ap.
Let's say that the clients get disconnected from the real ap and connected to the evil ap: I tried with different browsers (firefox, internet Explorer, chrome) and different os/machines, impersonating the clients, a mac osx, a Windows 7 machine and a quite old Samsung s3 mobile.
I have all browsers configured to have the home page at Google.
When I'm connected to the evil ap and I open the browser, since Google has https/hsts the returned page is an error page, with no option to go on (bypass the error).
If I intentionally go to an http website, instead, the captive portal pops up.
Most of the users, I think, looking at the returned error page, will think that their ap is not working good, so they will try to reconnect to the real ap, reboot it, etc.: I think most of the attacks will not be successful.
But if I have a second interface, connected to the internet, when a client connects to the evil ap, I could forward the https requests to the internet, real websites, so they will not have the error; so, they will stay connected to the evil ap, thinking all it's ok.
When the clients go to an http site, maybe from a search in Google, then they can be redirected to the evil captive portal asking for the password.
I know it's a mix of working/asking for password, but I think it will be more successfully then having a error page in the browser with no option to proceed (this is based on my experience).

Again sorry for my english, I hope I have clarified what I have in mind.

**Comment by MPX4132** [comment]
Okay, I understand what you're saying now. The problem with the idea is that if you allow the forwarding of encrypted traffic to the Internet, then every encrypted site will work fine. I don't think what you're asking for is possible. An encrypted site using SSL (https) prevents injection of external information, which is why it's so safe and used globally. That makes it impossible to redirect to the captive portal, since it would break SSL by redirecting to a foreign domain (the rogue captive portal server). I think the reason you're experiencing issues with HSTS is because of caching and cookies, but I'm not 100% sure. Unless someone can correct me and elaborate on the issue, I don't think this is possible.

**Comment by sweft54** [comment]
Thank you very much for your replies, just to comment your last sentences:

_The problem with the idea is that if you allow the forwarding of encrypted traffic to the Internet, then every encrypted site will work fine._

Yes, this is what I want to achieve.

_An encrypted site using SSL (https) prevents injection of external information, which is why it's so safe and used globally. That makes it impossible to redirect to the captive portal, since it would break SSL by redirecting to a foreign domain (the rogue captive portal server)._ 

Ok, but I don't want to inject and redirect SSL to the evil captive portal. Again, I'd want to pass without redirection/injection to real websites when SSL is requested, so there will be no errors.
Only http requests to be redirected to the captive portal.

Thank you again

**Comment by MPX4132** [comment]
What's the point of redirecting non-encrypted sites only? That would mean you can defeat the captive portal by using secure sites.

**Comment by sweft54** [comment]
Yes, I agree, but till now there are a lot of not encrypted sites, so the attack can be successful as soon as the client goes to a http website.
So the question is: better to have errors in the browser due to hsts/https, with no option to bypass it (for hsts) or better to let the client believe that all is ok redirecting https to real websites and asking for password in the captive portal only for http requests? In my opinion it's better the second option, but I may be wrong :)
I had a lot of clients connected to the evil ap which weren't able to get the captive portal page because of hsts websites requests (mainly google), that's the reason of my thread.

**Comment by MPX4132** [comment]
This tool is meant to be used for security auditing and research, and should not be used illegally in any way. It is your responsibility to make sure you're following the law. Make sure you read the disclaimer section in `README.md` and you understand the license agreement. I don't think I can help you with this feature request so you'll have to wait for someone else to answer the thread.

**Comment by deltaxflux** [comment]
Doesn't make any kind of sense.
