### ISSUE TITLE
The jammer on the evil twin isn't working

### ISSUE THREAD

**Issue by JondaMC** [FluxionNetwork/fluxion#1180]
#### Summary

The jammer is on a different channel than the AP, for example in aireplay-ng, so the deauth attack is on channel -1 while the AP is on channel 6.
After a moment, the jammer window closes

##### What is the current behaviour?

No errors or crashes are shown, only that i said

![20240331_171735](https://github.com/FluxionNetwork/fluxion/assets/165569415/74e18d3e-11eb-469e-bff4-c6e9bc21f435)

![20240331_171749](https://github.com/FluxionNetwork/fluxion/assets/165569415/89eb6a4f-9022-4b46-93aa-38771664eb15)

#### Expected behavior

If the deauth attack was launched on the correct channel and not on channel -1

**Comment by cjb900** [comment]
you did not properly fill out the issue template. So this is getting closed.
