### ISSUE TITLE
plz add dual deauthentication on both band at same time 

### ISSUE THREAD

**Issue by Niansahh** [FluxionNetwork/fluxion#1182]
add features to deauthenticat band abg at same time mean when we perform 5ghz only 5ghz deauthenticated 2.4 ghz still open so there are no benefit to perform hack and also add hostapd for dual wifi 5ghz and 2.4 ghz at same time.i think it could be huge update for fluxion after few years

**Comment by cjb900** [comment]
This can not be done with one wifi adapter. You would need a second wifi adapter to deauth the other 2.4ghz band
