### ISSUE TITLE
not installing in parrot os

### ISSUE THREAD

**Issue by Adarshthakut** [FluxionNetwork/fluxion#1185]
./fluxion.sh: line 255: format_center_literals: command not found

./fluxion.sh: line 262: format_center_literals: command not found

./fluxion.sh: line 270: installer_utils_check_update: command not found

./fluxion.sh: line 289: installer_utils_check_dependencies: command not found
./fluxion.sh: line 290: installer_utils_run_dependencies: command not found

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

**Comment by cjb900** [comment]
Fluxion runs just fine here. Has to be something on your end. 
![image](https://github.com/FluxionNetwork/fluxion/assets/47070308/2dec0dfa-b464-4d81-a394-f108e852aac3)

**Comment by Adarshthakut** [comment]
![Uploading issue.png…]()

**Comment by Adarshthakut** [comment]
![Uploading issue.png…]()

**Comment by Adarshthakut** [comment]
![Uploading issue.png…]()

**Comment by Adarshthakut** [comment]
@cjb900 
![issue](https://github.com/FluxionNetwork/fluxion/assets/154810071/9d050ba9-2064-4830-aef7-a306214c910d)

**Comment by cjb900** [comment]
Posting a screenshot of the exact information you already shared initially is not going to help. Also, you never filled out the issue template. So this is not getting reopened. Fluxion works just fine on the latest Parrot OS on my end with no issues. So this has to be something on your end you will need to fix.

**Comment by Adarshthakut** [comment]
how to fix it please help me

**Comment by cjb900** [comment]
Don't use a version of Parrot OS that looks to be from HTB. Use the official one from their site. Using anything other than the official version there is no telling what modifications were made so there is no guarantee fluxion will work. Its only been tested on the official version of Parrot OS.

**Comment by Adarshthakut** [comment]
i am using offical version
cat /etc/os-release
PRETTY_NAME="Parrot Security 6.0 (lorikeet)"
NAME="Parrot Security"
VERSION_ID="6.0"
VERSION="6.0 (lorikeet)"
VERSION_CODENAME=lory
ID=debian
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://www.parrotsec.org/community/"
BUG_REPORT_URL="https://gitlab.com/parrotsec/"

**Comment by Adarshthakut** [comment]
please reply
