### ISSUE TITLE
无法创建钓鱼热点ap没有出现6个窗口

### ISSUE THREAD

**Issue by Lucas888666** [FluxionNetwork/fluxion#1189]
<img width="667" alt="屏幕截图 2024-05-24 224001" src="https://github.com/FluxionNetwork/fluxion/assets/169078153/d463de35-adbf-4355-9423-56f3217599f9">

|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by cjb900** [comment]
Didn't follow the issue template so this is getting closed
