### ISSUE TITLE
Not Loading .CAP Files

### ISSUE THREAD

**Issue by reubadoob** [FluxionNetwork/fluxion#119]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behavior?
*Fluxion will not load a .cap file. I am receive the error "Hash file does not exist"*

#### If the current behavior is a bug, please provide the steps to reproduce it.
*After selecting an access point, I choose [1] Captive Portal, [1] Rogue AP - hostapd (Recommended), [1] Path to capture file. I then enter the path to the .cap file and get the attached screenshot error*

#### What do you think the expected behaviour should be?
*Fluxion should load the .cap file I have saved and directing it to open?*

### Specs
*Paste the output of `./scripts/diagnostics.sh <interface>`*
root@kali:~/fluxion/scripts# ./diagnostics.sh wlan1
./diagnostics.sh: line 3: lib/InterfaceUtils.sh: No such file or directory
[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
./diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown

ioctl(SIOCSIWMODE) failed: Device or resource busy
13:50:58  Trying broadcast probe requests...
13:51:00  No Answer...
13:51:00  Found 1 AP 

13:51:00  Trying directed probe requests...
13:51:00  02:1D:D2:81:7B:C0 - channel: 1 - ''
13:51:06   0/30:   0%

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.12.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170805 (Debian 6.4.0-3) ) #1 SMP Debian 4.12.6-1kali1 (2017-08-18)

![gnome-shell-screenshot-1j044y](https://user-images.githubusercontent.com/31323201/29685461-d01e9cee-88d2-11e7-92ba-d5231f6f008c.png)

**Comment by MPX4132** [comment]
It's clearly stated, "**Absolute** path:" not "Relative path:" The bug report says run `./scripts/diagnostics.sh` not `./diagnostics.sh`

Just input the absolute path, man. Absolute path means from the file system's root directory...
`/home/myusername/mycapfiles/thecapfile`

**Comment by cjb900** [comment]
Well you are using a crap RTL chipset which are notoriously problematic for Wi-Fi hacking and not recommended. You will need to ditch that and get a better supported card. Then if you still have issues please open a new tissue and don't comment on issues that have been closed for ~8 years or join our discord. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
MT7921AUN <- present in Alfa awus036axm or awus036axml  or comfast-CF-953AX or comfast-CF-951AX
