### ISSUE TITLE
/fluxion.sh: 42: [[: not found

### ISSUE THREAD

**Issue by humblelad** [FluxionNetwork/fluxion#1193]
#### Summary
I am running .sh file and getting error. Pls see screenshot. 

##### If the current behaviour is a bug, please provide the steps to reproduce it.

![Screenshot 2024-06-19 at 12 26 31 PM](https://github.com/FluxionNetwork/fluxion/assets/30574278/99bd6229-1150-4b0d-a56f-501e2bfdb7be)

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by cjb900** [comment]
for not following the issue template this is getting closed

**Comment by humblelad** [comment]
I solved it myself. it was related to sudo permissions.
