### ISSUE TITLE
Realtek RTW8821CE stop working or halt the system in twin attack mode

### ISSUE THREAD

**Issue by zonalimitatore** [FluxionNetwork/fluxion#1196]

**Comment by cjb900** [comment]
Realtek wifi chipset are notoriously problematic for wifi hacking and not recommended. You also didn't properly fill out the issue template. So this is getting closed.

**Comment by zonalimitatore** [comment]
I've corrected the syntax...was in <<   >>

**Comment by cjb900** [comment]
Well correcting your post will not help here when you are still using a crap Realtek wifi chipset. you are going to be better off ditching that adapter and getting a better one from the list below 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)
MT7921AUN <- present in Alfa awus036axm or awus036axml  or comfast-CF-953AX or comfast-CF-951AX

**Comment by zonalimitatore** [comment]
I've also Alfa AWUS036H usb. But I don't think is AP capable

**Comment by cjb900** [comment]
ya thats another card with a known crap Realtek chipset. While you can try using a combination of those 2 adapters in fluxion there is no guarantee it will work and you will probably be better off ditching both and getting a better card/chipset from the list above.

**Comment by zonalimitatore** [comment]
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)

**Comment by cjb900** [comment]
yes that patched driver stopped working years ago. I don't have an adapter with that chipset to know if it could get working again or not. So its not even worth it IMHO because even with the patched driver it was still not very reliable.

**Comment by zonalimitatore** [comment]
Copy that, thank you. So it should be removed from list!
