### ISSUE TITLE
Not connecting to the AP?

### ISSUE THREAD

**Issue by TheProtocoler** [FluxionNetwork/fluxion#12]
### Which version of fluxion are you using?
Version 2 revision 1

### What distribution of Linux (including the version) are you running it on?
Parrot Security 2.0.5 - Helium

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
ALFA AWUS036H. Driver: rtl8187 

### Which is the driver for it?
rtl8187
### Does it support injection ( output of aireplay-ng -9)
Yes, injection is working just fine.

`18:22:32  5E:35:3B:0E:2F:39 - channel: 6 - 'HOMESPOT'`
`18:22:32   Ping (min/avg/max): 1.554ms/8.243ms/17.450ms Power: -67.35`
`18:22:32   23/30: 76%`
(didn't copy all of the APs my AWUS picked up)
### General description of your issue along with the steps to reproduce it
1. starting fluxion
2. going through the menu (choosing language, choosing my adapter, picking aps, choosing an ap)
3. choosing "deauth target"
4. getting handshake and then checking it.
5. then creating a SSL cert
6. Selecting web interface
7.  using number 20 (dutch)
 Everything is created just fine and i can see the ap on my network list but when i try to connect to it, it doesn't connect.. i read the F.A.Q, but when i mean no internet, i mean that it doesn't even want to connect to the AP.
Could it be with the DHCP configuration file or something? It literally doesn't connect. Any suggestions and any help? I'm at my wits' end, thanks!

**Comment by deltaxflux** [comment]
I will check it, thanks for your detailed issue.

**Comment by TheProtocoler** [comment]
@deltaxflux thank you so much, please do keep me updated.

**Comment by TheProtocoler** [comment]
@deltaxflux I might have found the problem. I tried using Linset, I got through the spanish menu, and I think the probleem being is that when creating the evil twin, you have a new terminal opening up called "DHCP" in green, On linset, the Multiple interfaces which match the same subnet is eth0 and at0. While in fluxion, it's eth0 and wlan0. On Linset I can't really get redirected to the log in page everytime (although i got to the login page a few times and upon entering the pass, nothing happens and i just get redirected back). I think the problem is that maybe you have to change the multiple interfaces that match the same subnet and shared network from wlan0 TO at0? Thanks!
The picture below show the linset DHCP terminal, this is what I mean about it being at0
![546](https://user-images.githubusercontent.com/21243470/27774414-2b3926e0-5f92-11e7-8e81-8a46b8e1e2c3.PNG)

Thanks again!

**Comment by deltaxflux** [comment]
I don't think so I thought it is a hostapd bug. Now it woks again flawless for me. Please share results.

**Comment by TheProtocoler** [comment]
@deltaxflux okay, now I can get connected to the internet although it has that yellow triangle on windows and i don't get redirected whatsoever (and nothing is showing on my FAKEDNS XTerm). This might be a problem from my wireless adapter.

May I know which wireless adapter you are using? Thank you again.

**Comment by vvbv** [comment]
I have the same problem.   :(
![screenshot_2017-07-03_21-15-35](https://user-images.githubusercontent.com/22215311/27812492-f4a72dd6-6034-11e7-85f8-3e43ccf283ca.png)

**Comment by deltaxflux** [comment]
@TheProtocoler 

Well yes this is a **driver issue**. I missed to look at your wireless card. The _ALFA AWUS036H is unsupported_ for access points. So use another card.  

I personally use the alfa AWUS036NH which support

Supported interface modes:
* IBSS
* managed
* AP
* AP/VLAN
* monitor
* mesh point

If you want a cheaper card I can recommend the _TP-LINK TL-WN722N_ . Please not that only the _TP-LINK TL-WN722N  **V1**_ Support monitor mode. The newer version **V2** use another chipset and is **not supported** . If you have any trouble please let me know.

@vvbv 
Do you use the same wireless card ? 

**EDIT:**
First I thought that the variable $CHANNEL is negative but in this case its **only a driver issue.**

Cheers

**Comment by TheProtocoler** [comment]
@deltaxflux 

I thought so. Thanks again! And yes, I thought that too at some point. I thought that the $Channel was negative, so I tried to change my wireless adapter's interface to my victim's channel. Still didn't work, so I thought this is a problem from my wireless adapter. Since AWUS036H is pretty outdated nowadays haha, thank you for the help again! 

Cheers!

**Comment by vvbv** [comment]
This is my hardware information, sorry for the delay in responding. I have always used this card with fluxion.

root@router:~# lshw -C network
  *-network               
       description: Ethernet interface
       product: RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:08:00.0
       logical name: enp8s0
       version: 01
       serial: 00:a0:d1:8c:77:d0
       size: 10Mbit/s
       capacity: 100Mbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm vpd msi pciexpress bus_master cap_list rom ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=2.3LK-NAPI duplex=half latency=0 link=no multicast=yes port=MII speed=10Mbit/s
       resources: irq:27 ioport:a000(size=256) memory:f8200000-f8200fff memory:f8220000-f823ffff
  *-network
       description: Wireless interface
       physical id: 1
       bus info: usb@1:6
       logical name: wlx00164478ba7d
       serial: 00:16:44:78:ba:7d
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=rtl8187 driverversion=4.8.0-58-generic firmware=N/A ip=192.168.1.2 link=yes multicast=yes wireless=IEEE 802.11

**Comment by deltaxflux** [comment]
@vvbv 
Please do `iw list`

**Comment by vvbv** [comment]
@deltaxflux , I tried a previous version, and I no longer have channel -1 error, but the dns server does not start. What version of isc-dhcp-server do you use?.

router@router:~$ iw list
Wiphy phy6
	max # scan SSIDs: 4
	max scan IEs length: 2285 bytes
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Device supports RSN-IBSS.
	Supported Ciphers:
		* WEP40 (00-0f-ac:1)
		* WEP104 (00-0f-ac:5)
		* TKIP (00-0f-ac:2)
		* CCMP (00-0f-ac:4)
		* 00-0f-ac:10
		* GCMP (00-0f-ac:8)
		* 00-0f-ac:9
	Available Antennas: TX 0 RX 0
	Supported interface modes:
		 * IBSS
		 * managed
		 * monitor
	Band 1:
		Bitrates (non-HT):
			* 1.0 Mbps
			* 2.0 Mbps
			* 5.5 Mbps
			* 11.0 Mbps
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm)
			* 2472 MHz [13] (20.0 dBm)
			* 2484 MHz [14] (disabled)
	Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * new_station
		 * new_mpath
		 * set_mesh_config
		 * set_bss
		 * authenticate
		 * associate
		 * deauthenticate
		 * disassociate
		 * join_ibss
		 * join_mesh
		 * set_tx_bitrate_mask
		 * frame
		 * frame_wait_cancel
		 * set_wiphy_netns
		 * set_channel
		 * set_wds_peer
		 * probe_client
		 * set_noack_map
		 * register_beacons
		 * start_p2p_device
		 * set_mcast_rate
		 * Unknown command (104)
		 * connect
		 * disconnect
	Supported TX frame types:
		 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
	Supported RX frame types:
		 * IBSS: 0x40 0xb0 0xc0 0xd0
		 * managed: 0x40 0xd0
		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * mesh point: 0xb0 0xc0 0xd0
		 * P2P-client: 0x40 0xd0
		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-device: 0x40 0xd0
	software interface modes (can always be added):
		 * monitor
	interface combinations are not supported
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	Device supports TX status socket option.
	Device supports HT-IBSS.
	Device supports SAE with AUTHENTICATE command
	Device supports low priority scan.
	Device supports scan flush.
	Device supports AP scan.
	Device supports per-vif TX power setting
	Driver supports full state transitions for AP/GO clients
	Driver supports a userspace MPM

**Comment by deltaxflux** [comment]
Your interface is not supported.

This is your output:
Supported interface modes:
* IBSS
* managed
* monitor

**This is what it looks like**

Supported interface modes:
* IBSS
* managed
* AP
* AP/VLAN
* monitor
* mesh point

**Comment by navyarm** [comment]
Hi, deltaflux. I have a problem like this, fluxion creates the fake AP with all Wi-Fi network except one. How can I solve this problem?. (It seems odd to me that it worked with this network before, but now do not work). I have this problem since my pc has turned off while the fake AP was on. Also from that time i see a Wi-Fi network without name and with a negative channel (see the picture)
![img_3388](https://user-images.githubusercontent.com/29991023/27987301-c8b6e588-640b-11e7-90e8-c57d5fab7b56.JPG)
. Sorry for my english bro

**Comment by behzad1k** [comment]
hi @deltaxflux 
Im afraid I have the same problem as the others here 
please check out my iw list : 

z0b@z0b:~$  iw list
Wiphy phy1
        max # scan SSIDs: 4
        max scan IEs length: 2257 bytes
        max # sched scan SSIDs: 0
        max # match sets: 0
        max # scan plans: 1
        max scan plan interval: -1
        max scan plan iterations: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Device supports RSN-IBSS.
        Device supports AP-side u-APSD.
        Device supports T-DLS.
        Supported Ciphers:
                * WEP40 (00-0f-ac:1)
                * WEP104 (00-0f-ac:5)
                * TKIP (00-0f-ac:2)
                * CCMP-128 (00-0f-ac:4)
                * CCMP-256 (00-0f-ac:10)
                * GCMP-128 (00-0f-ac:8)
                * GCMP-256 (00-0f-ac:9)
                * CMAC (00-0f-ac:6)
                * CMAC-256 (00-0f-ac:13)
                * GMAC-128 (00-0f-ac:11)
                * GMAC-256 (00-0f-ac:12)
        Available Antennas: TX 0x1 RX 0x3
        Configured Antennas: TX 0x1 RX 0x3
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
                 * outside context of a BSS
        Band 1:
                Capabilities: 0x116e
                        HT20/HT40
                        SM Power Save disabled
                        RX HT20 SGI
                        RX HT40 SGI
                        RX STBC 1-stream
                        Max AMSDU length: 3839 bytes
                        DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 8 usec (0x06)
                HT TX/RX MCS rate indexes supported: 0-7
                Bitrates (non-HT):
                        * 1.0 Mbps
                        * 2.0 Mbps (short preamble supported)
                        * 5.5 Mbps (short preamble supported)
                        * 11.0 Mbps (short preamble supported)
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 2412 MHz [1] (16.0 dBm)
                        * 2417 MHz [2] (16.0 dBm)
                        * 2422 MHz [3] (16.0 dBm)
                        * 2427 MHz [4] (16.0 dBm)
                        * 2432 MHz [5] (16.0 dBm)
                        * 2437 MHz [6] (16.0 dBm)
                        * 2442 MHz [7] (16.0 dBm)
                        * 2447 MHz [8] (16.0 dBm)
                        * 2452 MHz [9] (16.0 dBm)
                        * 2457 MHz [10] (16.0 dBm)
                        * 2462 MHz [11] (16.0 dBm)
                        * 2467 MHz [12] (16.0 dBm) (no IR)
                        * 2472 MHz [13] (16.0 dBm) (no IR)
                        * 2484 MHz [14] (disabled)
        Supported commands:
                 * new_interface
                 * set_interface
                 * new_key
                 * start_ap
                 * new_station
                 * new_mpath
                 * set_mesh_config
                 * set_bss
                 * authenticate
                 * associate
                 * deauthenticate
                 * disassociate
                 * join_ibss
                 * join_mesh
                 * remain_on_channel
                 * set_tx_bitrate_mask
                 * frame
                 * frame_wait_cancel
                 * set_wiphy_netns
                 * set_channel
                 * set_wds_peer
                 * tdls_mgmt
                 * tdls_oper
                 * probe_client
                 * set_noack_map
                 * register_beacons
                 * start_p2p_device
                 * set_mcast_rate
                 * connect
                 * disconnect
                 * channel_switch
                 * set_qos_map
                 * Unknown command (121)
        Supported TX frame types:
                 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
        Supported RX frame types:
                 * IBSS: 0x40 0xb0 0xc0 0xd0
                 * managed: 0x40 0xd0
                 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * mesh point: 0xb0 0xc0 0xd0
                 * P2P-client: 0x40 0xd0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * P2P-device: 0x40 0xd0
        software interface modes (can always be added):
                 * AP/VLAN
                 * monitor
        valid interface combinations:
                 * #{ managed } <= 2048, #{ AP, mesh point } <= 8, #{ P2P-client, P2P-GO } <= 1,
                   total <= 2048, #channels <= 1, STA/AP BI must match
        HT Capability overrides:
                 * MCS: ff ff ff ff ff ff ff ff ff ff
                 * maximum A-MSDU length
                 * supported channel width
                 * short GI for 40 MHz
                 * max A-MPDU length exponent
                 * min MPDU start spacing
        Device supports TX status socket option.
        Device supports HT-IBSS.
        Device supports SAE with AUTHENTICATE command
        Device supports low priority scan.
        Device supports scan flush.
        Device supports AP scan.
        Device supports per-vif TX power setting
        P2P GO supports CT window setting
        Driver supports full state transitions for AP/GO clients
        Driver supports a userspace MPM
        Device supports active monitor (which will ACK incoming frames)
        Driver/device bandwidth changes during BSS lifetime (AP/GO mode)
        Device supports configuring vdev MAC-addr on create.

**Comment by deltaxflux** [comment]
@navanchauhan 

Well, it is clear why it doesn't work. How should hostapd use a negative channel? This "bug" appears mostly because airodump-ng can't capture enough packages or they are invalid because you capture not the entire package.  Airodump-ng signify this with -1. You could solve this if you capture longer, reduce the range or use a more powerfull wireless card.

@be-we 
Looks like your wireless card is supported but I need more information about your environment. Can you please open a new issue with all details present including the diagnostic script.

**Comment by aqeel5user** [comment]
awus036h working smoothly in wifphisher. try it. i am using it.

**Comment by matic914** [comment]
@deltaxflux  I use ALFA AWUS036NH. I follow all the steps and my problem is that at the moment of entering the language of the web interface (Spanish), everything is fine but the window of the twin web does not open and neither redirects me using the cell phone or another PC. Sorry for my english!!

![screenshot from 2018-04-03 16-32-28](https://user-images.githubusercontent.com/38051069/38274425-24f52512-3765-11e8-99b9-829f3c4630cd.png)

**Comment by deltaxflux** [comment]
#### Summery

Well, debug this is pretty hard. It would be a pleasure if you could help me and share information. 

#### Debugging lighttpd
First we make sure that you submodules are installed. While beeing in the fluxion directory do:
`git submodule init && git submodule update`

This clones all required submodules. To make sure that you have all required files but the main issue here is the lighttpd or the fakedns script.We try to figure out this.

1. We check if the lighttpd is working propertly. 
2. Close the lighttpd window if any and try to run lighttpd manually
3. Use following command `lighttpd -f <conf>` 

*Note* The lighttpd config is located inside the fluxion temp directory normally in `/tmp/fluxspace`

If some strange errors appear let me know

#### Debugging fakesna
1. Run the fakedns script `python2 <script>` Located inside the fluxion temp directory.

####  Final words
Please create a new issue with all required information and I will check it out as soon as possible. 

**Edit:** I remove your screenshot because you could get doxed.
