### ISSUE TITLE
Opening xterm windows too small and locate at the corner

### ISSUE THREAD

**Issue by imofelrj** [FluxionNetwork/fluxion#1200]
When I begin sniffing, these opening xterm windows are too small and they are at the corner of my screen.
What can I do to put them in the center of my screen of proper size ?

**Comment by imofelrj** [comment]
Background info: I'm running kali on a RasPi 4b, and access by vnc.
When I use ssh, the popping up xquartz windows are small either.

**Comment by cjb900** [comment]
Sounds like a resolution issue that you need to fix. Other have run fluxion in similar setups and never mentioned issues like this.
