### ISSUE TITLE
Network is down in evil twin after 10 minutes about

### ISSUE THREAD

**Issue by attilius743** [FluxionNetwork/fluxion#1202]
#### Summary
I tried to launch evil twin from kali linux 2024.02 amd64. I choose with no SSL and with emulation (because otherwise it doesn't start).
After some minutes, about 10, the 

##### What is the current behaviour?
fluxion's windows are still visible, but the evil twin doesn't work: the network isn't visible anymore

#### How to reproduce
I choose the evil twin attack, then I choose all recommended choise, but with NO SSL and with EMULATED, finally I choose the number 14 in the last question.

##### If the current behaviour is a bug, please provide the steps to reproduce it.
described in the previous step

##### What do you think the expected behaviour should be?
that it will wait until someone connects to my network

##### If this is a feature request, what is the motivation or use case for the added feature?
it's not a feature request

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
![5004](https://github.com/user-attachments/assets/c5668547-c911-45ea-be2e-f618900aeaab)

#### Expected behavior
that it will wait until someone connects to my network

**Comment by cjb900** [comment]
If running `diagnostics.sh` can't properly determine the wifi adapter/chipset you have that's a pretty good sign that probably crap for wifi hacking and most likely why you are having issues. You would be better off ditching that adapter/chipset and getting one from the list below

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH or AWUS 036ACHM(2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
MT7921AUN <- present in Alfa awus036axm or awus036axml  or comfast-CF-953AX or comfast-CF-951AX

**Comment by attilius743** [comment]
this adapter works on kali linux 2019.02 and fluxion 6.9.
I will attach the diagnostics.sh output:
1) before use fluxion
2) after the monitor mode
3) when the evil twin attack is just started
4) when the issue starts
[1. wlan0 before fluxion starts.txt](https://github.com/user-attachments/files/16979563/1.wlan0.before.fluxion.starts.txt)
[2. wlan0 in monitor mode fluxwl0.txt](https://github.com/user-attachments/files/16979564/2.wlan0.in.monitor.mode.fluxwl0.txt)
[3. evil twin just started.txt](https://github.com/user-attachments/files/16979565/3.evil.twin.just.started.txt)
[4. evil twin issue.txt](https://github.com/user-attachments/files/16979566/4.evil.twin.issue.txt)
