### ISSUE TITLE
Fluxion stuck on "Select a wireless attack for the access point"

### ISSUE THREAD

**Issue by kalilinux-arch** [FluxionNetwork/fluxion#1205]
tried selecting both options but stuck at same point

[*] Select a wireless attack for the access point

                                                                     ESSID: "[N/A]" / [N/A]                                                                                    
                                                                   Channel:  [N/A]                                                                                             
                                                                     BSSID:  [N/A] ([N/A])                                                                          

        [1] Captive Portal Creates an "evil twin" access point.
        [2] Handshake Snooper Acquires WPA/WPA2 encryption hashes.
        [3] Back 

Wifi Adapter i am using -
  wlan0     IEEE 802.11  ESSID:"Xiaomi 11T Pro"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 7E:6B:9C:26:06:27   
          Bit Rate=52 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=70/70  Signal level=-32 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:30   Missed beacon:0

**Comment by cjb900** [comment]
🤦
