### ISSUE TITLE
Windows minimized

### ISSUE THREAD

**Issue by warsoldier200500** [FluxionNetwork/fluxion#1206]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

![window-issue-v0-34zeta4krxyd1](https://github.com/user-attachments/assets/3f8d6a86-669d-447d-b7bf-e719e4e82fd3)
The window its collapsed instead of being normal expanded.

The previous kali version everything was working fine.

**Comment by cjb900** [comment]
This is an issue with bash and not an issue with fluxion https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078556. Nothing we can do other than waiting for an update to bash and or Kali to fix this.

**Comment by warsoldier200500** [comment]
Thank you for the prompt reply :)
