### ISSUE TITLE
Manual enlargement of Xterm on fluxion instead of automatic enlargement with six windows

### ISSUE THREAD

**Issue by KreativeNerd** [FluxionNetwork/fluxion#1207]
I am using VMware workstation 17.6.1. This problem appeared with me after updating Kali Linux to 2024.3. It became small and I had to enlarge it manually. When I search for networks or attack the evil twin, the windows that appear automatically are very small. They used to appear normally before the update. Also this seems to affect both fluxion and Airgeddon that uses Xterm terminal. Please what is the solution to the problem? 

![image](https://github.com/user-attachments/assets/5829731f-4d15-459f-abd0-1f11172138a0)

**Comment by cjb900** [comment]
this is a known bug in bash.

**Comment by NormTurtle** [comment]
@cjb900 please provide a workaround for this. instead of just closing

**Comment by cjb900** [comment]
There is no known work around because it's an issue with bash not fluxion. So you will have to either just manually enlarge the window or wait for an update that fixes it. That's why it was closed. If there was a workaround I would have provided it instead of just closing it
