### ISSUE TITLE
AWUS036H (RTL8187) support.

### ISSUE THREAD

**Issue by poonwizard** [FluxionNetwork/fluxion#121]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behaviour?
Detecting APs - wireless card may not be supported

#### If the current behaviour is a bug, please provide the steps to reproduce it.
sudo fluxion.sh
4 - english
select wireless interface alfa RTL8187
select all channels 

Wireless card may not be supported. 
alfa awus036h?

#### What do you think the expected behaviour should be?
never used fluxion before

### Specs
this is from another PC but running it says there is 1 AP found 
could provide more details if needed

**Comment by MPX4132** [comment]
Run the diagnostics script.

**Comment by poonwizard** [comment]
`user@kali:~/fluxion$ sudo ./scripts/diagnostics.sh FXan1AP
[ FLUXION Info ]
FLUXION V.


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (FXan1AP) Info ]
Device: phy1
Driver: rtl8187
Chipset: Realtek Semiconductor Corp. RTL8187

15:24:40  Trying broadcast probe requests...
15:24:40  Injection is working!
15:24:42  Found 1 AP 

15:24:42  Trying directed probe requests...
15:24:42  D8:B6:B7:99:06:D9 - channel: 1 - 'Comtrend06D8'
15:24:43  Ping (min/avg/max): 1.631ms/19.240ms/77.015ms Power: -27.10
15:24:43  29/30:  96%



[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.11.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170704 (Debian 6.4.0-1) ) #1 SMP Debian 4.11.6-1kali1 (2017-06-21)
`

**Comment by MPX4132** [comment]
Sorry for taking long, I got busy. It seems you encountered an issue with interface initialization, or the interface crashed somehow. That extra `FXan1AP` interface shouldn't be there. If you ran and terminated the program properly (ctrl+c), the interface should've been removed automatically. Run fluxion again and press ctrl+c at the interface selection screen to get rid of it, or reboot your computer.

Try running fluxion with the airmon-ng active flag and the killer flag:
```
export FLUXIONWIKillProcesses=1; export FLUXIONAirmonNG=1; ./fluxion.sh
```

**Comment by poonwizard** [comment]
No need for apologies, people are always busy.

https://gfycat.com/maturegivingibadanmalimbe

Above is a screen recording of what I did. 

diag ran on wlan1

root@kali:/home/user/fluxion# ./scripts/diagnostics.sh wlan1
[ FLUXION Info ]
FLUXION V.


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy3
Driver: rtl8187
Chipset: Realtek Semiconductor Corp. RTL8187

ioctl(SIOCSIWMODE) failed: Device or resource busy
08:59:16  Trying broadcast probe requests...
08:59:17  Injection is working!
08:59:18  Found 1 AP 

08:59:18  Trying directed probe requests...
08:59:18  D8:B6:B7:99:06:D9 - channel: 1 - 'Comtrend06D8'
08:59:19  Ping (min/avg/max): 2.420ms/20.763ms/36.344ms Power: -26.54
08:59:19  28/30:  93%



[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.11.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170704 (Debian 6.4.0-1) ) #1 SMP Debian 4.11.6-1kali1 (2017-06-21)

**Comment by MPX4132** [comment]
Alright, you've got a couple of problems from what I can see in the gif you linked.

I noticed both of your wireless interfaces, wlan0 and wlan1, are connected to your wireless network. That's a problem, because it means they're both busy and bringing them down will NOT solve the problem, just temporarily suppress it. I'm positive this is what's causing the "interface crash" I told you about earlier. The network-manager service is likely snatching the interfaces and setting them to managed mode, rather than monitor mode. This problem is resolved by running fluxion with the `FLUXIONWIKillProcesses` flag, so just do:
```
export FLUXIONWIKillProcesses=1; ./fluxion.sh
```
Do **not** drop the interfaces yourself. Also, forget the `FLUXIONAirmonNG` flag, that's not the problem you're having.

The second problem is visible when you actually launched fluxion... the X server has some type of issue which you need to resolve on your own:
```
No protocol specified
xdpyinfo:  Unable to open display ":0"
```

**That's the main problem in your case.** The X server is failing and doesn't allow the "FLUXION Scanner" window to start, leading to your problem.

**Comment by MPX4132** [comment]
Please run the latest version of the diagnostics script and paste the results here.

**Comment by poonwizard** [comment]
So if you run the diag script as a non-root user it will fail most the test but pass xterm testing but if ran as sudo/root it will fail so I started looking for solutions for that and found the following page: https://www.linuxquestions.org/questions/linux-software-2/cannot-open-display-as-root-352200/

with the solution: 
xhosts +
Which allow all users to run applications as themselves in an X environment logged in as another user.

**Comment by poonwizard** [comment]
user@user:~$ cd fluxion/
user@user:~/fluxion$ sudo ./scripts/diagnostics.sh wlan1
[sudo] password for user: 
[ FLUXION Info ]
FLUXION V3.2


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy1
Driver: rtl8187
Chipset: Realtek Semiconductor Corp. RTL8187
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
**Test: XServer/XTerm failure!**


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.12.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170805 (Debian 6.4.0-3) ) #1 SMP Debian 4.12.6-1kali5 (2017-08-25)

**user@user:~/fluxion$ xhost +
access control disabled, clients can connect from any host**

user@user:~/fluxion$ sudo ./scripts/diagnostics.sh wlan1
[ FLUXION Info ]
FLUXION V3.2


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy1
Driver: rtl8187
Chipset: Realtek Semiconductor Corp. RTL8187
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
**Test: XServer/XTerm success!**


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.12.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170805 (Debian 6.4.0-3) ) #1 SMP Debian 4.12.6-1kali5 (2017-08-25)
user@user:~/fluxion$

**Comment by MPX4132** [comment]
That seems like a workaround, not really a temporary solution, but it's up to you. Fluxion requires running as root, so running it as another use will likely not work. Did you resolve the issue?

**Comment by poonwizard** [comment]
I'm not well versed in Linux operations but I feel like I am in the right track in solving the problem. 

I have made it to Starting Captive Portal AP service and it the script hasn't moved passed there in 15 minute so I'm thinking something else is off now.

**Comment by MPX4132** [comment]
I think your driver may not be supported, check out [this bug report](https://github.com/FluxionNetwork/fluxion/issues/73) I participated in from earlier this month.

**Comment by MPX4132** [comment]
Checkout [this wiki article](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!) I wrote a while ago.

**Comment by poonwizard** [comment]
Okay I believe you're correct. My alfa adpater/chipset isn't able to do this. Whats funny? The onboard in the laptop is able to. WHAT?

**Comment by MPX4132** [comment]
Lol, that's interesting huh. Yeah, I didn't suggest that one because the driver didn't even show a description in that gif you linked. It's probably that stupid RTL driver. @SiNaPsEr0x was having issues with it too, I'm not sure whether or not he got it working. If you didn't checkout the wiki article, I suggest you try it out to see if you get anywhere. The alfa probably has better antennas than the internal radio.

**Comment by poonwizard** [comment]
I checked it out. Hostapd wouldn't start with it. 
I ran hostapd with the internal adapter and it started. 
So I ran fluxion with it and completed the attack using the internal adapter. 
I checked a couple places online and AP isn't a supported mode and when running iw list AP isn't listed for the interface mode for my Alfa adapter with the rtl driver.

**Comment by MPX4132** [comment]
That's pretty ridiculous. If you look at the issue history it's usually something with a process snatching the interface, or a freaking RTL driver.

Actually, the reason I didn't add checking if the interface supports AP mode is because iw list sometimes doesn't show it for cards that support it, or some issue along the lines of that.

**Comment by poonwizard** [comment]
Here is a screen record of me performing Fluxion attack against myself using the laptops internal wireless adapter: https://gfycat.com/GlitteringAlienatedFlyingsquirrel

Sorry for sluggish recording. This laptop doesn't do well.

**Comment by MPX4132** [comment]
Password logs and network logs are stored at `fluxion/attacks/Captive Portal/pwdlog` and at `fluxion/attacks/Captive Portal/netlog` if you ever need to check those out. The password log will log all attempted passwords, while the netlog will log all the target networks and their WPA/WPA2 keys.

**Comment by usama7628674** [comment]
What about airbase maybe it'll work for your adapter but it's too slow

**Comment by poonwizard** [comment]
Ya know whats stranger? Back on windows with the wireless utility, you can set the RTL8187 as an AP. 

https://i.imgur.com/j37FxpE.png

**Comment by MPX4132** [comment]
Yeah, so it's just a bad driver. Now we know, the rtl8187 is garbage.

**Comment by usama7628674** [comment]
So far Atheros chipsets are best.Alfa awus036nha (AR9271) is excellent when capturing handshakes and it
works very well with any script and also TP-Link WN722.

**Comment by MPX4132** [comment]
Yeah, the alfa you mentioned uses the ath9k_htc driver. It's pretty awesome, works perfectly. It's the one I use to test the script with.

**Comment by usama7628674** [comment]
What about ralink chipsets?Are they any good?

**Comment by poonwizard** [comment]
Either of you know how I'd go about usin a ubiquity airgrid m2 hp with fluxion or other tools?

**Comment by MPX4132** [comment]
@usama7628674 I haven't tried any of them, I woudn't know, sorry. Somehow all I got are atheros chipsets, even the internal one of a laptop I'm using is atheros. Actually, I've got an a Realtek adapter with the rtl8192cu driver. It sucks, can't even enable monitor mode.

@poonwizard as far as I'm concerned, the Ubiquiti M2 lineup only offers ethernet and a web UI for routing configuration. As far as I'm concerned, it doesn't allow direct access to the radio, so it would be impossible to use it with fluxion.

**Comment by usama7628674** [comment]
plus antenna you mentioned works properly when you have have higherTX (transmitting power).These days most of the adapters comes with 20dbi hardlocked unless you do ROM hacks to boost it up but I think it makes some difference

**Comment by poonwizard** [comment]
No wonder I couldn't get my adapter to increase its tx power output..

**Comment by aqeel5user** [comment]
awus036h working smoothly in wifphisher. try it. i am using it.

**Comment by aqeel5user** [comment]
awus036h working smoothly in wifphisher. try it. i am also using it.
