### ISSUE TITLE
Target AP immune to deauthentication.

### ISSUE THREAD

**Issue by victorhab1** [FluxionNetwork/fluxion#126]
I'm facing this AP, it seems like it is intelligent, it keep changing the channel every time I try to attack this (With the fake AP attack).
When a client connect after that, fluxion "looses the connection" with the target AP and don't even try the inserted password.

When it does that, the mdk3 window shows:
read failed: Network is down
wi_read(): Network is down
Thus, fluxion is innefective.

**Comment by freeroute** [comment]
I confirm that. I have the same situation. AP changes the channel under attack.

**Comment by Megaeloelo** [comment]
I have the same error output, but my target is still on the same channel. Is mdk3 broken or something?

**Comment by MPX4132** [comment]
@Megaeloelo It could be a driver crash. It has happened to me once; the driver crashed and mdk3 threw out those messages.

**Comment by victorhab1** [comment]
@MPX4132 I was watching the channel hopping of the AP with my onboard wireless card (outside the VM), although these mdk3 messages doesn't seem to appear when the target ap changes the channel.

Anyway, it never happened to me before, I use mdk3 for a long time now.

**Comment by MPX4132** [comment]
It might just be some random bug, I was getting them today too but the deauthenticator was still working, or at least it seemed to keep working. We need to check it a solution is possible, so I'll leave this open. I just haven't had time to check it out.

**Comment by Megaeloelo** [comment]
Ok in my issue I needed to use command: airmon-ng check kill.

**Comment by MPX4132** [comment]
@Megaeloelo run the script with the killer flag:
```
FLUXIONWIKillProcesses=1; ./fluxion.sh
```

**Comment by deltaxflux** [comment]
_**FIXED**_

**Comment by victorhab1** [comment]
Even running with this flag 
`FLUXIONWIKillProcesses=1; ./fluxion.sh`
Still having the same thing:
> read failed: Network is down
> wi_read(): Network is down
And the AP still changing the channel.

**Comment by deltaxflux** [comment]
This is not the issue you described before. Known issue with low priority.
