### ISSUE TITLE
Android not getting the AP page due to connectivity test failed.

### ISSUE THREAD

**Issue by victorhab1** [FluxionNetwork/fluxion#127]
Android is checking the address: http://connectivitycheck.android.com/generate_204
to decide if there is internet access or not before even opening the fake AP page on the browser.

I found this, might be useful:
http://www.ateijelo.com/blog/2016/09/11/make-android-believe-it-has-internet-access

**Comment by deltaxflux** [comment]
Thanks for reporting I will add it but before I make some tests.

**Comment by deltaxflux** [comment]
looks like it is deprecated.

**Comment by MPX4132** [comment]
It sounds more like a bug with Android, than a bug with Fluxion. There's captive portals everywhere here, and none offer Internet without prior authentication. That would mean your Android device is incapable of connecting to those or has trouble connecting to those, which is a bit ridiculous on Android's side.

**Comment by deltaxflux** [comment]
That is what the article is about.

**Comment by MPX4132** [comment]
Well, I read the article but I still don't see why that matters. I've never seen captive portals that allow any type of traffic without authenticating. The url "http://connectivitycheck.android.com/generate_204" would likely be blocked too. I understand the author of the article states they resolved the issue with replying to requests with a 204 code, but I don't think captive portal restricted networks do that by default.

**Comment by deltaxflux** [comment]
Yep, we use the same URL as you might notice.  We should don't keep attention at it because it is deprecated.

**Comment by MPX4132** [comment]
Yeah, I see what you mean. I just read his comment:
```
Hi, Igor. Thruth be told, this worked for some time, but then I had a friend with Android 7 for whom this trick wasn't enough. I haven't had the time to research what changed. If you find a way to do it, let me know. Likewise, if I find anything, I'll tell you here in a comment.
```
