### ISSUE TITLE
captive portal attack in progress - no actions

### ISSUE THREAD

**Issue by eitanhindi** [FluxionNetwork/fluxion#128]
![screenshotfull](https://user-images.githubusercontent.com/30051406/29866376-3853ab8e-8d46-11e7-9f5a-721524393b9d.png)

### What is the current behaviour?
final step: 4 screens shows up, and hangs.
no reconfirm password. (from the connected devices)
real AP disconnect all connected devices, but no redirect to login page or asking reconfirm password.

looks like mdk3 disconnect the real AP every 3 seconds, what causing for the AP  to appear and disappear any few sec, and cant perform reconfirm password from connected devices.

**note**: all steps working fine with no errors, till the 4 screens

### Specs
real AP -> netgear.
running fluxion by -> export FLUXIONWIKillProcesses=1; ./fluxion.sh 
testing with connected devices -> 3 android phones

*Paste the output of `./script/diagnostics.sh`*:

root@kali:~/fluxion# ./scripts/diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.2

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy2
Driver: 8812au
Chipset: Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.9.0-kali4-amd64 (devel@kali.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.9.30-2kali1 (2017-06-22)

**Comment by eitanhindi** [comment]
## **update**
when runing with debug:
Captive Portal certificate is already set, skipping!
Captive Portal site (interface) is already set, skipping!
hostapd: no process found
lib/ap/hostapd.sh: line 23: kill: (32096) - No such process
Current MAC:   00:00:00:00:00:00 (XEROX CORPORATION)
Permanent MAC: 00:00:00:00:00:00 (XEROX CORPORATION)
New MAC:       c4:04:15:11:87:69 (NETGEAR INC.,)
Network driver didn't actually change to the new MAC!!
mdk3: no process found
attacks/Captive Portal/attack.sh: line 790: kill: (32127) - No such process
rm: cannot remove '/tmp/fluxspace/mdk3_blacklist.lst': No such file or directory
attacks/Captive Portal/attack.sh: line 803: kill: (32132) - No such process
attacks/Captive Portal/attack.sh: line 809: kill: (32136) - No such process
rm: cannot remove '/tmp/fluxspace/clients.txt': No such file or directory
hostapd: no process found
lib/ap/hostapd.sh: line 23: kill: (32146) - No such process
[*] Starting Captive Portal access point service...

**Comment by SiNaPsEr0x** [comment]
but before you write you understand at least what are you doing? it's all working at that time (I'm trying to explain just because of the low literacy level) you have to wait for the user of that network to connect so that he inserts the real password .. the system will control the handshake and if it matches the password true you will discover it

**Comment by MPX4132** [comment]
The clients will only be redirected to the rogue network’s Captive Portal if you’re connected to the rogue network l. When you launch the attack, make sure you check if the clients got disconnected. If they did, they’ll need to reconnect but only the rogue AP will work.
After connecting to the rogue network clients will be redirected.

**Comment by eitanhindi** [comment]
@SiNaPsEr0x but before you write you understand at least what are you doing?
yes i m, but i do missing something at the last attack, thank u.

@MPX4132  
im sorry for forgeting to say that:
1) my android device is disconnected from the real AP, while the attack.
2) in my android i do need to reconfirm the password.
3) nothing is progressed from there, im stuck in loop of reconfirm the password.

"The clients will only be redirected to the rogue network’s Captive Portal if you’re connected to the rogue network l":
sorry for my poor understanding, but can u please guide me gow to make sure that im (as the attacker) connected to the rogue network? any more info about that point will complete my performence i guess.

thank u very much!
