### ISSUE TITLE
Network lock, handshake selection loop and a suggestion 

### ISSUE THREAD

**Issue by adars47** [FluxionNetwork/fluxion#130]
### Do you want to request a *feature* or report a 
Bug?

Network lock, is it really necessary to lock eth as well? 

While picking the handshake, if I pick up a incorrect file it gets stuck in loop, I can't grab another handshake 

### What is the current behaviour?
*fluxion crashes*

#### What do you think the expected behaviour should be?
*What do you think should happen?*

### If this is a feature request, what is the motivation or use case for the added feature?

 The ability to use a router or an ap instead of a wireless network card.. 
To clarify
Deauth can be done through the wireless card 
The captive port can be hosted like the way it is being hosted now..(using hostpad) it can be easily accesed through lan. 
The attaker will rename and create a open network for the victims to join ( manually) from the router ( only flaw )
The site can then be accessed by there victim through the ethx port router or ap..
The router will use the fake dns from the app,
 

To conclude, in order for this happen, you need to lock only the wireless networks not lan ( idk if that's possible ) 

And add a few menu to select which eth port to listen to.. 

And make the dhcp server listen to the selected lan port, 

To clarify I am a total noob, just yesterday I googled which language are sh files written in.. but still after looking at the sh files, I guess it's doable .. feel free to correct me if I am wrong..or interested in this idea..

### Specs
*Paste the output of `./script/diagnostics.sh`*

**Comment by MPX4132** [comment]
Whoops, I accidentally reopened this.

It is possible, but it would be a pretty bing issue if the users don’t have a router that supports AP mode.
