### ISSUE TITLE
[Request] Rogue network on ethernet AP device.

### ISSUE THREAD

**Issue by adars47** [FluxionNetwork/fluxion#131]
### If this is a feature request, what is the motivation or use case for the added feature?

The ability to use a router or an ap instead of a wireless network card..
To clarify
Deauth can be done through the wireless card
The captive port can be hosted like the way it is being hosted now..(using hostpad) it can be easily accesed through lan.
The attaker will rename and create a open network for the victims to join ( manually) from the router ( only flaw )
The site can then be accessed by there victim through the ethx port router or ap..
The router will use the fake dns from the app,

To conclude, in order for this happen, you need to lock only the wireless networks not lan ( idk if that's possible )

And add a few menu to select which eth port to listen to..

And make the dhcp server listen to the selected lan port,

To clarify I am a total noob, just yesterday I googled which language are sh files written in.. but still after looking at the sh files, I guess it's doable .. feel free to correct me if I am wrong..or interested in this idea..

**Comment by MPX4132** [comment]
@adars47 Technically, that's already possible. All you have to do is configure your router to access point mode, and have it forward all DHCP and DNS requests to the host computer, as well as take care of other things like proper subnet and what not...

**Comment by adars47** [comment]
I did that, actually stripped all hostpad, dchp, fakedns and a lot more functions,  but the network lock was creating problems as I needed eth x to be functional and using exitfunction  wasn't helpful as lighttpd would crash as well, and if it did, I would have to start the dhcp, dns, and apace plus, I tried to figure out it out by looking up what I didn't understand from the codes but being someone who hasnt had much experience with shell it was difficult..so anyway if you have a well documented sh file it would be really helpful..

**Comment by MPX4132** [comment]
Hmm, are you by any chance running fluxion with the `FLUXIONWIKillProcesses` flag?

**Comment by adars47** [comment]
And the main problem I faced whIle working with the app ("without tearing it apart") was that the dchp was not pushing the site, fake dns was working fine (" as i could see my phone's activity" ) but dchp was stuck at interface down, tried modifying the dchp.interface on my machine but that doesn't seem to help the dchp server..

**Comment by MPX4132** [comment]
If you are, that flag kills `network-manager`, which might lead to your problem.

**Comment by MPX4132** [comment]
The DHCP service isn’t responsible for pushing the site, the DNS is.

**Comment by MPX4132** [comment]
The DHCP server is a python script that isn’t connected to the OS’s built in networking, so tweaking anything will not work. It seems like your wireless interface is giving you issues.

**Comment by MPX4132** [comment]
Yeah, I think you just missed a couple of steps, like giving your ethX interface a static IP.

**Comment by MPX4132** [comment]
Hmm, I think the DHCP is hooking to the wireless interface only, I think... I forgot.

**Comment by adars47** [comment]
The file I am using to unlock the interface is exitmode.sh, I have tried matarado function but that didn't unlock the interface..

And correct me if i am wrong but, dns gives you  the ip, in our case redirects the client to index.html and it's the dchp's work to maintain the client ip thus naming the packets with the correct ip.. but here the dhcp server is looking for the clients in the wlan1 interface, which is completely wrong..

And my kali machine has a static ip, it's just that the dhcp server is looking for packets in the wrong interface..

**Comment by MPX4132** [comment]
You need to update to the latest version if you still have an exitmode.sh file.

Actually, this could be a pretty awesome feature... It bypasses potential issues with the card and master mode, and the data rates are natively high.

**Comment by MPX4132** [comment]
I've started [a new branch](https://github.com/FluxionNetwork/fluxion/tree/universal-interface) targeting this type of behavior. I think it's a pretty valid idea, considering the fact APs are designed specifically for such operation. This feature would be much more manual than the current automatic one due to the fact the AP would need to be configured manually, meaning it'll have to be added as an option, while the automatic choice (the current behavior) stays as the recommended and default method.

**Comment by adars47** [comment]
I got the solution to dhcp server not listening, turns our you can force the dhcp server to be run on multiple interfaces using ...

subnet 10.0.0.0 subnet 255.255.255.0 {

interface eth2;
....
....
....}

In the dhcp conf file..
( will be useful if later on this function is to be automated )

the fake dns as usual is working perfectly fine but lighttpd seems to be having issues, it loads up perfectly fine in the fake ap but no luck trying to acess it through a different network, i don't think lighttpd is supposed to be linked to any interfaces but still for some reason I can't acess the files on the ap setup using ethx ...

**Comment by MPX4132** [comment]
Yo, try out the universal-interface branch on the latest commit. Try using the ethernet AP device you've got and let me know what happens.

**Comment by MPX4132** [comment]
It's not even close to perfect, but I need to verify the functionality works. I've been kinda busy lately and haven't had much time to work on it.

**Comment by adars47** [comment]
@MPX4132 the virtual Inrerface is not functioning properly, and the newer update isn't working at all, the previous version could do an okay job with few minor tweaks.. but the latest one is totally non functional..

Here is an idea to move forward with this concept, for the time being, I am using a repeater to increase the range which gave me an idea of what to do.. i don't know if it's possible , but let me put it anyway.. 

1) start dhcp server on the selected interface not on virtual.. ( virtual interface is creating a lot of problems) 
2) fake dns should have an ip which is assigned by the dhcp server, we need our ap to be able to acess it
3) the dhcp server shold assign itself an specific ip, which is used to host the hosttpd file..

Right now I am getting interface not available error...

In previous versions this is what I did to make it functional

1) in the attack.sh
   Dhcp config part..  I specified my eth port using interrace ethx; which made it listen to eth instead of wireless..

2) fake dns responded to it.. 

In the router's setting I gave the dns ip to where it was hosting.. 

3) used arp poisioning to redirect the gateway traffic to the kali's ip
The kali machine  was connected as a client with the ap in dhcp setting

**Comment by MPX4132** [comment]
Yeah, I’m not surprised it didn’t work, I didn’t test it at all. All I did was refactor functionality and make sure the previous system still works. I’ll check it out tomorrow.

I can’t make the original network interface be the AP interface. I did that originally and found a problem with it, i can’t remember what it was anymore. I think it had to do with an issue with `mdk3`.

**Comment by MPX4132** [comment]
@adars47 Alright, I think I've fixed the bug on the latest commit of the [universal-interface branch](https://github.com/FluxionNetwork/fluxion/tree/universal-interface). It was caused by bad design from my part. I need to rewrite the AP services utility, it's kinda ugly right now.

**Comment by adars47** [comment]
It's working perfectly fine now... you can even add this to the master branch now... there is still a flaw but it's natural with this form of attack, if someday someone manages to pass through ssl validation, this program would be unstoppable.. most people just use google.com which translates to https making life hell for portals like these.. so I guess until that day it's the best anyone could do.. :)

**Comment by MPX4132** [comment]
Awesome, thanks for being the beta tester man. I’m gonna make some minor tweaks to the script, and I’ll do a merge after. If you’ve got anything else related to this, don’t hesitate to bring it up here.

**Comment by Cris90sb** [comment]
But it is useless to try again and try again only works in the network in which you are connected so if your friend does not give you his password and you are connected to his router you can not do anything fluxion works so

**Comment by MPX4132** [comment]
@Cris90sb, what do you mean?

**Comment by Cris90sb** [comment]
that it's useless that you want to crakkare the networks if you are not connected in their modem if you are connected to your modem fluxion it works but if you try to do it to another where however you are not connected you can also say goodbye to fluxion will never work

**Comment by MPX4132** [comment]
@Cris90sb you clearly **do not** understand the concept of fluxion’s `Captive Portal` attack. It’s also clear you didn’t read, or didn’t understand, the README file, which happens to be **the first thing you seen when you access the repository.** Don’t go around spreading misinformation. I suggest you check out the README file, or check the wiki because you’re terribly misinformed.

**Comment by Cris90sb** [comment]
I do not care about these stupid things, I just told you the truth of how fluxion works if it's so you're very misinformed about this tool

**Comment by MPX4132** [comment]
@Cris90sb I wrote the latest version of the tool, it’s extremly unlikely I’m misinformed because I know exactly how it works. Again, **you don’t know what you’re talking about**. I’m not going to argue with you any further because you’re literally wasting my time. I’m going to ignore you because you chose to ignore what I said. You choose to be ignorant even after being told you’re misinformed. I apologize if I’m offending you, but you need to understand you’re misinformed. If you have an issue related to fluxion, open a new issue.

**Comment by Cris90sb** [comment]
still with this legislation fluxion works only for example if you are already connected nowadays it is difficult for people to give you the password of WI FI to enter and then use this tool wake up we are in 2017 I ignore you that you can not explain well how it works this tool that works only if you are connected in the network I hope I was clear bye

**Comment by MPX4132** [comment]
@Cris90sb Fluxion does not require a connection to the target network, in fact, the `Captive Portal` attack assumes you’re **not** connected to the target network.

Fluxion generates its own wireless network by making a twin of the original access point. To force people to connect to it, fluxion starts jamming every client on the original network. That causes them to disconnect from the original network, and makes them unable to connect to it again until fluxion is terminated.

Once connected to the “rogue” network, the twin fluxion generated, you’re prompted with the captive portal to access the internet.

Fluxion stops jamming the original network, and shuts down if one of the clients in the “rogue” network (in the evil twin) inputs the correct password.


Fluxion doesn’t doesn’t require you knowing the password in advanced. Fluxion can also determine if users are entering an incorrect password by checking against a handshake hash.

**Comment by fluxhlp** [comment]
@adars47 if you were able to use router as an AP and run fluxion. Could you help me with 
https://github.com/FluxionNetwork/fluxion/issues/963#issue-696103558
Thanks!

**Comment by adars47** [comment]
@fluxhlp yeah, I was able to use the ap as the evil twin. What part are you having trouble with ?

**Comment by fluxhlp** [comment]
actually i am a beginner. i tried using router as a repeater and ap. I don't know how to go further since router is connected via ethernet and fluxion uses wireless interface. So, how do i host fake ap and captive portal on my router ?

**Comment by adars47** [comment]
You setup a fake ap by manually changing the ssid and channel..(Mac as well if possible ) .. set your routers DNS to your fake DNS server run by fluxion( your Kali machine ) ... everything else should run perfectly.. also you might have to set your router to use a static IP that way the fluxion network should be under the same subnet.

**Comment by fluxhlp** [comment]
I am sorry, I am new to networking and having a little trouble. ssid and channel name can be setup. but I am having issues understanding a few things:
1) for router, do i use the dns server of fluxion in attack.sh or in dhcp conf file?
2) should I change interface to eth x in dhcp conf file. also how do I provide static ip to my router?
3) could you please mention all the files which require changes as per your experience?

**Comment by giteshkumar13** [comment]
> [@adars47](https://github.com/adars47) thanks for the response, I was able to do it.

Hey could tell me steps please?
Or refer to any resource where I can get help?
