### ISSUE TITLE
[Request] 5GHz Support

### ISSUE THREAD

**Issue by gjames2467** [FluxionNetwork/fluxion#135]
*feature*
Anyone working on 5 GHz support.  I have not taken a deep dive into the code yet but just wanted to throw it out there.

**Comment by MPX4132** [comment]
The script relies on airodump-ng, which doesn't seem to like 5GHz very much. You can probably work around it by adding the `--band a` flag, but idk, I haven't messed with it.

**Comment by SiNaPsEr0x** [comment]
And automatic procedure when scanning fhe Wi-Fi and select them?

**Comment by gjames2467** [comment]
I will add band A to the scan and see how it works and report back.

**Comment by MPX4132** [comment]
@SiNaPsEr0x Yeah, we probably need to add automatic detection to trigger the flag somehow.

**Comment by ozitrance** [comment]
5G works fine for me. Didn't need to add the "--band a" switch to the code - just specify the channels to scan. For the 5G channels you can specify something like: 20-200. Try that!

Also, if airelpay-ng (de-authentication) complains about no beacons found - try to add the -D switch to the code - to disable AP detection. I think it's only necessary if the channel shows as -1, but I found that if I wait a little more with the scan - the real channel will show up.

**Comment by freeroute** [comment]
Could you please post a sample command to specify channel between 20-200? I would like to try with my card.
Is this the correct command?:  "./fluxion --channel 20-200"

**Comment by ozitrance** [comment]
You don't need to use any special commands. Before it starts scanning the networks, Fluxion asks you if you want to scan all channels or specific ones... Choose the second option and you'll be able to specify the channels (20-200 will work there)

**Comment by freeroute** [comment]
Ahh, it's so simple. Thanks. I tried, it works.

**Comment by deltaxflux** [comment]
It is pointless. There aren't good chipset out there which support 5ghz and *Master Mode*. In addition, there are also bugs with airodump at 5ghz. Don't think that it is possible in the next months because of the mentioned issues above.
