### ISSUE TITLE
No handshake file

### ISSUE THREAD

**Issue by m0lmk** [FluxionNetwork/fluxion#136]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behaviour?
Handshake file not created

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Select a wireless attack for the access point
[2] Handshake Snopper
[2] aireplay-ng deauth
[1] pyrit verification

Capture process starts, opens 2 windows (Captor and Deauth) and soon captures a handshake (as shown at top of window).

No file is created in attacks/Handshake Snooper/handshakes and all windows stay open.

In the main Fluxion window, select [2] to exit.

#### What do you think the expected behaviour should be?
Should a file be created in attacks/Handshake Snooper/handshakes and the windows close?

### Specs
root@kali:~/fluxion# ./scripts/diagnostics.sh *
[ FLUXION Info ]
FLUXION V3.2

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (LICENSE) Info ]
Device: Unknown
basename: missing operand
Try 'basename --help' for more information.
Driver: Unsupported
Chipset: 
Injection Test: ioctl(SIOCGIFINDEX) failed: No such device
failed

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.4.50-v7 (root@builder) (gcc version 4.8.3 20140401 (prerelease) (crosstool-NG linaro-1.13.1-4.8-2014.04 - Linaro GCC 4.8-2014.04) ) #1 SMP Fri Apr 21 01:18:29 CDT 2017
root@kali:~/fluxion#

**Comment by m0lmk** [comment]
![screen shot 2017-09-02 at 17 21 06](https://user-images.githubusercontent.com/9196880/29997132-6124216e-9003-11e7-911a-da9514601eb1.png)

**Comment by MPX4132** [comment]
A valid handshake hadn't been received yet. You'll know a valid handshake has been received once the "Handshake Captor" window stops updating (the "Elapsed" field stops moving). The deauthenticator will also automatically shutdown and the window will close.

If you've got another question feel free to reply here.

P.S I suggest you do **not** use `mdk3` for deauthentication, it's **super freaking aggressive** to the point it doesn't let the handshake captor get a valid handshake. Try using the `aireplay-ng` deauthenticator.

**Comment by m0lmk** [comment]
So, in the image above where it says WPA Handshake at the top of the window does not mean that a handshake has been captures?

**Comment by deltaxflux** [comment]
Miss the line:  
>Ignore the "WPA handshake: ..." message at the top right. The airodump-ng handshake validator sucks or something.

**Comment by lemonade3** [comment]
Hi @deltaxflux,

I have the same problem with the image. And ""Elapsed" field stopped moving. But nothing happens, it just waiting

**Comment by MPX4132** [comment]
@lemonade3 That's normal, once it freezes like that just go to the main Fluxion window and choose the option that lets you select another attack, and choose the `Captive Portal` attack.

**Comment by jeretc** [comment]
..with the older fluxion you can basically move on to next step once you get the handshake.

**Comment by MBHacks** [comment]
guys its been 16 mins and nothing happened it still sending deauth 
could someone help me to solve this problem

**Comment by MPX4132** [comment]
If you’re too far away from your target, it might not work. Another cause could be that there’s no targets available, for example, at night. When people go to sleep, their devices won’t try to reconnect if they’re not turned on and using the internet. When things like phones are in sleep mode, they usually disconnect from the WiFi. You just have to keep trying man. This is very likely not a problem with fluxion

**Comment by MBHacks** [comment]
Thank you man that worked for me thank you for your help

**Comment by MPX4132** [comment]
@MBHacks awesome news, glad you got it working man.
