### ISSUE TITLE
hostapd won't start using the virtual interface

### ISSUE THREAD

**Issue by ozitrance** [FluxionNetwork/fluxion#137]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
hostapd won't start using the virtual interface that fluxion creates (FXan1AP) but works fine if I use the same config file and just change the interface name to the physical one (wlan1).

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Using Fluxion, trying to create a Captive Portal attack, getting to the last stage, Fluxion will hang on "Starting Captive Portal access point service...." and will not continue. 

If I navigate to /tmp/fluxionspace/ and running "hostapd MA:CA:DD:RE:SS-hostapd.conf" (configuration file created by Fluxion) I get the following errors:

FXan1AP: Could not connect to kernel driver
Using interface FXan1AP with hwaddr 00:00:00:00:00:00 and ssid "WHATEVER"
Failed to set beacon parameters
FXan1AP: Could not connect to kernel driver
Interface initialization failed
FXan1AP: interface state UNINITIALIZED->DISABLED
FXan1AP: AP-DISABLED
FXan1AP: Unable to setup interface.
FXan1AP: interface state DISABLED->DISABLED
FXan1AP: AP-DISABLED
hostapd_free_hapd_data: Interface FXan1AP wasn't started
nl80211: deinit ifname=FXan1AP disabled_11b_rates=0

However, if I edit the config file and change the interface to the physical one, hostapd starts right away and Fluxion continues executing the rest of the attack. The problem now (I think) is that Fluxion is looking for traffic from the virtual interface but hostapd is operating on a different interface...

### Specs
My configuration is bellow:
Raspberry Pi 3 - running Kali Linux 2017.1
My wireless card is: ALFA Network AWUS1900 which uses the RTL8814AU chip.
I'm using version v4.3.21 of the driver which can be found here: https://github.com/astsam/rtl8812au/tree/v4.3.21
(I tried the newer ones too v5.1.5, but had a lot more problems with airodump-ng and aireplay-ng)

The device works beautifully. I'm focusing on 5G networks at the moment and can easily find all 5G networks by specifying channels to scan in Fluxion. I had a problem with de-authentication but adding the "-D" switch to your aireplay-ng code fixed that and I could easily disconnect clients and capture WPA handshakes.

Another little change I made is to the hostapd.sh code - just adding "hw_mode=a" to the configuration file creation section - to work on the 5G frequencies.  It works great with the physical interface - I'm easily able to create 5G networks.

Any thoughts...?

**Comment by MPX4132** [comment]
Please run the diagnostics script first:
```
cd fluxion
./scripts/diagnostics.sh
```
I'm guessing it's a problem with the driver. The script creates a secondary interface to deal with the fact we need to force-deauthenticate and host an access point at the same time.

You should take a look at [the page I wrote about this](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!).

**Comment by ozitrance** [comment]
Thanks for responding! 
My results are bellow.  Seems fine I think. The injection test on this test worked but it sometimes doesn't for some reason. Seems random. If I take down the interface before running the test (ifconfig wlan1 down) it will work right away...
Also, I noticed there's a delay sometimes until the device starts scanning/finding anything. Not sure why either but I don't mind waiting those 10-15 seconds. It seems to work fine after (and it doesn't always happen). 

I can easily make hostapd work with the settings from your article. Everything starts up right away, no delays. Only when it's trying to use the virtual interface it fails (no delays here too, just the error messages). 

Do you think it's all related?  The Injection not working sometimes and hostapd not working on the virtual interface? Or you're just trying to point out that there's clearly some issues with the driver..?


[ FLUXION Info ]
FLUXION V3.2


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy1
Driver: 8814au
Chipset: Realtek Semiconductor Corp. 
Injection Test: Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.9.41-Re4son-v7+ (root@kali-pi-dev) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #21 SMP Mon Aug 28 21:02:50 AEST 2017

**Comment by deltaxflux** [comment]
Seems like it is a driver issue. Do you read and try already the driver patch [here](https://github.com/FluxionNetwork/fluxion/wiki/Patch-driver-(rtl8812au))?

**Comment by ozitrance** [comment]
@deltaxflux yes I did tried the 5.1.5 version first actually - nothing really works for me with that driver. Airodump barely works. 

I tried it again today, using the driver from here: https://github.com/aircrack-ng/rtl8812au/ which seems to be the most updated project for this driver, but I just get the same bad results. 

In regards to hostapd - I get exactly the same errors when trying to use the virtual interface.

Funny thing, I remember it worked for me few days ago. Unfortunately I don't remember which driver I used and if I used my VM or the RPi3... I tried so many things... I read somewhere that version 5.1.5 works better for the 8812au but for 8814au (what I use) the 4.3.21 is still more recommended. I guess I will have to wait for more updates.

Any chance it was something in the last updates for Fluxion? I remember using lower version too, maybe that's when it worked...? I'm only asking this because I saw a few people complains about the same thing just in the last few days here: https://github.com/FluxionNetwork/fluxion/issues/87

**Comment by MPX4132** [comment]
@ozitrance Have you tried running earlier versions of Fluxion V3? Check if you can find a version that works and we can take a look at it, and compare the differences.

**Comment by ozitrance** [comment]
@MPX4132 I just tried another card with the new version and it works fine. This card only supports 2.4g so I tried my problematic one with 2.4g and I still get the errors. I guess it is a driver problem...

I'm still gonna try older versions. I'm almost certain it worked with my own 5g wifi before... I'll try my VM too.

Thank you!

**Comment by MPX4132** [comment]
Alright, cool. Try them out and report back if you've got anything.

**Comment by ozitrance** [comment]
I was able to confirm those drivers don't support virtual interfaces yet. Hopefully in the future. I guess we can close this issue now. Thanks for all the help

**Comment by MPX4132** [comment]
Alight, thanks for your research man. Hope it works out later on.

**Comment by nicshaca** [comment]
try this:  https://github.com/nicshaca/Fluxion-awus1900

**Comment by msdhoni77** [comment]
Hi team,

I am facing some issue while running airgeddon in my raspberry pi 4(Installed Kali) with wifi adaptor  LEOXSYS hg150n which supports packet injection and monitor mode.

It is throwing an error as "failed to set beacon parameters "

Can anyone help me 

> #please__

**Comment by cjb900** [comment]
@msdhoni77 why are you posting issues with airgeddon when this is the github for fluxion. You would be better off asking in the [github](https://github.com/v1s1t0r1sh3r3/airgeddon) or [discord](https://discord.gg/sQ9dgt9) for airgeddon. Also this post has already been closed and is 3 years old. Another thing you don't give enough information like.
What OS are you using. What steps/part of airgeddon you are using when you got this error. What chipset your adapter has.
