### ISSUE TITLE
Error, invalid hash file!

### ISSUE THREAD

**Issue by kfreelancea** [FluxionNetwork/fluxion#138]
Hi!
Can anyone tell me what I suppose to do when the script ask for the path to handshake file?

Thank you.

**Comment by usama7628674** [comment]
Make sure you give absolute path.You can find captured handshake file in the following
directory.
`fluxion/attacks/Handshake Snooper/handshakes`

**Comment by MPX4132** [comment]
You can get capture files by running the `Handshake Snooper` attack. Once you've got a cap file with `Handshake Snooper` you can run `Captive Portal` and it will not ask for the cap file.

**Comment by MPX4132** [comment]
@kfreelancea Check out the [Captive Portal attack guide](https://github.com/FluxionNetwork/fluxion/wiki/Captive-Portal-Attack). If you continue to have issues with the problem you stated above, come reply here. Otherwise, open a new issue and state your new problem.
