### ISSUE TITLE
After entering the password in the log in page it doesn't show up on fluxion

### ISSUE THREAD

**Issue by mido2018** [FluxionNetwork/fluxion#139]
After I enter the password in the log in page on my device nothing happens and the password never shows up on fluxion.

**Comment by MPX4132** [comment]
Well, you can check the web server is working by running the attack again (with the "Generic English" interface). Once the attack is running, open a navigator on the host machine and got to the address `192.168.254.1`. You should see the fluxion interface at this point. Enter the password and check what fluxion does. If fluxion does anything, chances are your interface is crashing or something (bad driver).

**Comment by mido2018** [comment]
Fluxion starts showing data on the DNS Service but when I enter the password nothing happens at all on both the log in page and Fluxion. Also, I tried to host this on 2 laptops and the same thing happens everytime.

**Comment by mido2018** [comment]
After I entered 192.168.254.1 in the navigator the log in page appeared and I enetered the password but nothing happened.

**Comment by MPX4132** [comment]
Run the diagnostics script:
```
cd fluxion
# Replace "wlanX" with your interface identifier:
./scripts/diagnostics.sh wlanX
```

**Comment by click2aliheart** [comment]
Fluxion tools not working fine with Google sits its not show options to enter WiFi password web interface

**Comment by MPX4132** [comment]
@click2aliheart I can't understand what you're saying, sorry. If you're using a translator, type your sentence then translate it to English, then translate it back to your language and check if it makes sense.

**Comment by nghili96** [comment]
let try
 `apt-get remove php-cgi`
it worked to me

**Comment by click2aliheart** [comment]
thanks bro but some time new Android mobile alert risk not show up googel
and other side show passworld option
