### ISSUE TITLE
Enter Path to Handshake File Path [Issue]

### ISSUE THREAD

**Issue by syedhamza786** [FluxionNetwork/fluxion#142]
Which handshake file path enter in Fluxion? I capture cap file of a wireless network and enter that file location but it giving an error that "Error: Invalid Hash File". Please tell which path should I enter for the smooth working of Fluxion. Help!!!

**Comment by MPX4132** [comment]
@syedhamza786 It means the capture file you have is corrupted, you can check whether it's valid or not by using pyrit:
```
pyrit -r path/to/file.cap analyze
```
You just need to capture a valid handshake.

**Comment by msfu101** [comment]
I have the same Issue, pyrit says 

Parsed 3 packets (3 802.11-packets), got 1 AP(s)

#1: AccessPoint xx:xx:xx:xx:xx:xx ('xxxxxxxx'):
  #1: Station xx:xx:xx:xx:xx:xx, 1 handshake(s):
    #1: HMAC_SHA1_AES, bad, spread 1

when i write the path to the .cap file to fluxion it says File not present.
What can i do pls?
