### ISSUE TITLE
Can't connect to fake AP

### ISSUE THREAD

**Issue by mattoide** [FluxionNetwork/fluxion#143]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
Can't receive ip address /can't connect  fake AP

#### What do you think the expected behaviour should be?
connect to fake ap.
never had this problem with old release of fluxion (don't remeber what version, but i have same problem, "stuck on obtaining ip", in Fluxion 2 REV 9)
sorry for bad english

### Specs
/diagnostics.sh: riga 3: lib/InterfaceUtils.sh: File o directory non esistente
[ FLUXION Info ]
grep: fluxion.sh: File o directory non esistente
FLUXION V.

[ BASH Info ]
GNU bash, versione 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
Licenza GPLv3+: GNU GPL versione 3 o successiva <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlp4s0b1) Info ]
./diagnostics.sh: riga 20: interface_physical: comando non trovato
Device: Unknown
./diagnostics.sh: riga 25: interface_driver: comando non trovato
Driver: Unsupported
./diagnostics.sh: riga 30: interface_chipset: comando non trovato
Chipset: Unknown
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy

ARP linktype is set to 1 (Ethernet) - expected ARPHRD_IEEE80211,
ARPHRD_IEEE80211_FULL or ARPHRD_IEEE80211_PRISM instead.  Make
sure RFMON is enabled: run 'airmon-ng start wlp4s0b1 <#>'
Sysfs injection support was not found either.

failed

[ XTerm Info ]
Version: XTerm(322)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 beta3 - (C) 2006-2013 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.4.0-93-generic (buildd@lgw01-03) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017

**Comment by deltaxflux** [comment]
Well, you do it wrong.
`sudo bash script/diagnostics.sh`

**Comment by MPX4132** [comment]
Your English is good, don't worry about it. Please update to the latest version of fluxion (V3.2):
```
git clone --recursive https://github.com/FluxionNetwork/fluxion.git # Download the latest revision
cd fluxion # Switch to tool's directory
./fluxion.sh # Run fluxion (missing dependencies will be auto-installed)
```
If you don't have git installed or if you would prefer to use an alternative method, just go to the repository and click the green download/clone button. **I highly suggest you use the git method, since it includes the extra site interfaces.**

**Comment by MPX4132** [comment]
@deltaxflux He's on an outdated version, that's why the diagnostics script isn't working. He's on 2.9 from what I read.

**Comment by deltaxflux** [comment]
@MPX4132 I missed that, thanks :)

**Comment by mattoide** [comment]
I had a problem with driver. Now i can connect to fake ap, but it doesn't appear the captive portal.
I tried on android and win 10. 
It's only appena if i go manually to 192.168.254.1

**Comment by MPX4132** [comment]
@mattoide Run the diagnostics script
```
cd fluxion
./scripts/diagonistics.sh wlanX # Replace wlanX with your wireless interface
```

**Comment by mattoide** [comment]
./diagnostics.sh: riga 3: lib/InterfaceUtils.sh: File o directory non esistente
[ FLUXION Info ]
grep: fluxion.sh: File o directory non esistente
FLUXION V.


[ BASH Info ]
GNU bash, versione 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
Licenza GPLv3+: GNU GPL versione 3 o successiva <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlp4s0b1) Info ]
./diagnostics.sh: riga 20: interface_physical: comando non trovato
Device: Unknown
./diagnostics.sh: riga 25: interface_driver: comando non trovato
Driver: Unsupported
./diagnostics.sh: riga 30: interface_chipset: comando non trovato
Chipset: Unknown
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy

ARP linktype is set to 1 (Ethernet) - expected ARPHRD_IEEE80211,
ARPHRD_IEEE80211_FULL or ARPHRD_IEEE80211_PRISM instead.  Make
sure RFMON is enabled: run 'airmon-ng start wlp4s0b1 <#>'
Sysfs injection support was not found either.

failed


[ XTerm Info ]
Version: XTerm(322)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 beta3 - (C) 2006-2013 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.4.0-93-generic (buildd@lgw01-03) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017

**Comment by MPX4132** [comment]
Do **not** give fluxion a monitor interface. You have to give it a regular (managed mode) interface.
Also, you gotta run the diagnostics script from fluxion's root directory:
```
cd fluxion
./scripts/diagnostics.sh wlanX
```
