### ISSUE TITLE
Nothing after handshake ..

### ISSUE THREAD

**Issue by lemonade3** [FluxionNetwork/fluxion#144]
Hi!

Fluxion is working untill handshake..

I got handshake but it is not asking to check handshake.. Just waiting.. 

What should i do?

Thanks in advance..

**Comment by MPX4132** [comment]
It's normal for fluxion to freeze like that. Fluxion stops the `Handshake Snooper` attack only once a valid handshake has been captured and verified. That means the handshake has already been verified and is ready to be used. Select the main fluxion window and enter the "select another attack" option, and choose the `Captive Portal` attack.

**Comment by lemonade3** [comment]
@MPX4132,i did what you said before, but this time it freezes at;

Starting Captive Portal access point service..

Thank you..

**Comment by deltaxflux** [comment]
Do you miss to read your wiki ?
If yes [here](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!) is the link.

**Comment by MPX4132** [comment]
Try running it with the killer flag:
```
export FLUXIONWIKillProcesses=1; ./fluxion.sh
```
I had to post it here in case you missed it from the wiki, since I just updated the wiki to reflect that.

**Comment by lemonade3** [comment]
@MPX4132 , @deltaxflux i did what you said. I read wiki. And create TestAP and it worked well. Then i tried run it with killer flag, but it didnt worked again. Everything fine i got handshake, then fluxion freeze so i choose select another attack, i choose captive portal attack, and coming to create ssl certifacation. But thats all. After that it freezes again just waiting with;

"Starting Captive Portal access point service.."

**Comment by MPX4132** [comment]
You only need to run the `Handshake Snooper` attack once per network. If you've already captured a handshake for the network sometime before, you don't have to run it again. Run the diagnostics script
```
cd fluxion # change directory into fluxion's directory
./scripts/diagnostics.sh wlanX # Make sure to change wlanX to the interface you're using.
```

**Comment by lemonade3** [comment]
Here is the output;

./diagnostics.sh: line 3: lib/InterfaceUtils.sh: No such file or directory
[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
./diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown
Injection Test: No Answer...


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.11.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170704 (Debian 6.4.0-1) ) #1 SMP Debian 4.11.6-1kali1 (2017-06-21)


It says device unknown, and driver unsupported but aircrack-ng is working well also i can create TestAP too..

**Comment by MPX4132** [comment]
Please run the script **exactly as I said.** Run it from fluxion's root:
```
./scripts/diagnostics.sh wlanX
```

**Comment by lemonade3** [comment]
Sorry.. thats my bad, here is the new output;

`[FLUXION Info ]
FLUXION V3.2`


`[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`

`This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash`


`[ Interface (wlan0) Info ]
Device: phy0
Driver: rtl8192eu
Chipset:  
Injection Test: No Answer...`


`[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!`


`[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd`


`[ Aircrack-ng Info ]`

  `Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe`
  `http://www.aircrack-ng.org`



`[ System Info ]
Linux version 4.11.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170704 (Debian 6.4.0-1) ) #1 SMP Debian 4.11.6-1kali1 (2017-06-21)`

**Comment by MPX4132** [comment]
It's all good, we need to fix that stupid script. It's my fault it's like that, I rushed it.

**Comment by MPX4132** [comment]
It seems like a driver issue. If you look at the other closed issues you'll see info about the RTL drivers, like your `rtl8192eu`. There's even [a guide](https://github.com/FluxionNetwork/fluxion/wiki/Patch-driver-(rtl8812au)) but it's for a different driver, you can look into it.

**Comment by lemonade3** [comment]
Actually i am not an expert but if that would be a driver issue, how can i use my card as an AP. Also how can i capture handshake..

**Comment by MPX4132** [comment]
The problem is that fluxion requires multiple virtual interfaces. One interface is used to jam the target access point, while the secondary interface is set to master mode (access point mode). Some drivers, like some RTL drivers, have an issue with that.

**Comment by lemonade3** [comment]
Oh got it, Thank you very much @MPX4132. Okey than i will ask one more question. I am using Kali under Vmware. And using a usb wireless card. How can i do the same thing with fluxion if i jam the target access with my Windows. And using my wireless card as an AP. Is there a way for that..?

**Comment by MPX4132** [comment]
Unfortunately, that functionality does not exist right now, sorry. You can try modifying the script yourself, if you're capable. You can also use an external access point if you have a router capable of access point mode and fluxion will jam the target, while the external access point device creates the rogue AP. But you need that external device. If you know what I'm talking about, check out the second fluxion branch called, "universal-interface" that one gives you that extra option but it's still under development, I haven't completely finished it.

**Comment by lemonade3** [comment]
Thanks for reply.. How can i check the second fluxion branch called "universal-interface"

**Comment by MPX4132** [comment]
Just download it [from here](https://github.com/FluxionNetwork/fluxion/archive/universal-interface.zip).

**Comment by lemonade3** [comment]
Thank you..

**Comment by rjshakil1145** [comment]
i'm using kali linux 2018.1,while i'm using fluxion everything working well but all going shit when its starting captive portal ap service,its not starting.its just hanging on and on.i'm using tp link tl-wn727n external usb wifi card.if i try with my internal wifi card then the captive portal ap service is starting its all window,but my internal wifi card doesn't support injection.if anyone have any suggestion then please help me
![screenshot from 2018-03-19 18-16-02](https://user-images.githubusercontent.com/37431509/37825211-36d6bb92-2eb9-11e8-9c13-4e744b5ef604.png)
