### ISSUE TITLE
Captive Portal access point service not working

### ISSUE THREAD

**Issue by m0lmk** [FluxionNetwork/fluxion#145]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behaviour?
Fluxion launches the captive portal access point service but the window immediately closes and fluxion hangs.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Start a normal captive portal attack using hostapd and pyrit verification. Create an SSL cert, select a portal.

Fluxion displays
`[*] Starting Captive Portal access point service`

Then a new terminal window flashed up and closes.

I have also trier running:
`export FLUXIONWIKillProcesses=1; ./fluxion.sh`

#### What do you think the expected behaviour should be?
The Captive Portal access point service should start or there should be feedback displaying why it did not start.

### Specs
root@kali:~/fluxion# ./scripts/diagnostics.sh wlan1
[ FLUXION Info ]
FLUXION V3.2

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
Device: phy0
Driver: rtl8187
Chipset: Realtek Semiconductor Corp. RTL8187
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.4.50-v7 (root@builder) (gcc version 4.8.3 20140401 (prerelease) (crosstool-NG linaro-1.13.1-4.8-2014.04 - Linaro GCC 4.8-2014.04) ) #1 SMP Fri Apr 21 01:18:29 CDT 2017
root@kali:~/fluxion#

**Comment by MPX4132** [comment]
Check out [this article](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!), I just updated it. Chances are you're experiencing issues due to the horrible RTL driver. It's always an issue with them.

**Comment by m0lmk** [comment]
Thanks @MPX4132 

I've tested it with another adaptor and it's working fine. I've also got a new Alfa AWUS036ACH arriving on Monday so I'll see if it works with that after installing the Kali drivers.

**Comment by MPX4132** [comment]
You might have issues with that one too. If I remember correctly, people have had issues with the AC variant of the Alfa radios because it also requires an RTL driver. You can check out the closed issues.

**Comment by m0lmk** [comment]
Yes, I'm expecting some although packet injection is allegedly working now... We'll see!

I've also got a AWUS036NHA on the way which should work well.

**Comment by MPX4132** [comment]
That last one will work for you 100%. I've been testing the script with another device that uses the same driver. It's pretty good.
