### ISSUE TITLE
HandShake Capture Problem

### ISSUE THREAD

**Issue by Darkv2s** [FluxionNetwork/fluxion#149]
Hello, 
there's a problem with handshake capture,  when i try to capture hand shakes nothing happen no dir created or any changed , also when trying to scan it i found nothing ..
but when i capture it manually , and enter the path it worked great..
OS: Manjaro 17.0.2

**Comment by deltaxflux** [comment]
I would like to see some logs. **Use:**
`export FLUXIONDebug=1 ; ./fluxion`

**Comment by Darkv2s** [comment]
Scapy 2.x is required to use Pyrit's analyze/attack functions but seems to be unavailable.
Verifier aircrack-ng, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID My_Router, MAC 80:1F:02:55:E1:15
Handshake for My_Router (80:1F:02:55:E1:15) is missing!
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
-- Then when i installed scapy i
New pcap-file '/tmp/fluxspace/capture/dump-01-clean.cap' written (4 out of 6 packets)
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID My_Router, MAC 80:1F:02:55:E1:15
Handshake for My_Router (80:1F:02:55:E1:15) is missing!
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 80:1f:02:55:E1:15 ('My_Router')
1/2: New Station 00:08:22:0e:28:fc (AP 80:1f:02:55:E1:15)
1/3: New Station 00:08:22:8a:f1:01 (AP 80:1f:02:55:E1:15)
2/3: Challenge AP 80:1f:02:55:E1:15 <-> STA 00:08:22:8a:f1:01
3/4: Response AP 80:1f:02:55:E1:15 <-> STA 00:08:22:8a:f1:01
3/4: New Handshake AP 80:1f:02:55:E1:15: HMAC_MD5_RC4, bad, spread 1
4/5: Confirmation AP 80:1f:02:55:E1:15 <-> STA 00:08:22:8a:f1:01
4/5: New Handshake AP 80:1f:02:55:E1:15: HMAC_MD5_RC4, good, spread 1
Capture-source was closed...

still no dir created , and the handshake missing message in 2 cases and GUI windows stucked

**Comment by deltaxflux** [comment]
` sudo pip2 install scapy`
