### ISSUE TITLE
Not seeing installed dependencies 

### ISSUE THREAD

**Issue by NeonAnon** [FluxionNetwork/fluxion#150]
rfkill is already the newest version (0.5-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
           [*] aircrack-ng...................................... OK.           
           [*] awk.............................................. OK.           
           [*] curl............................................. OK.           
           [*] dhcpd....................................... Missing!           
           [*] 7zr.............................................. OK.           
           [*] hostapd..................................... Missing!           
           [*] lighttpd.................................... Missing!           
           [*] iwconfig......................................... OK.           
           [*] macchanger....................................... OK.           
           [*] mdk3........................................ Missing!           
           [*] nmap............................................. OK.           
           [*] openssl.......................................... OK.           
           [*] php-cgi.......................................... OK.           
           [*] pyrit............................................ OK.           
           [*] xterm............................................ OK.           
           [*] rfkill...................................... Missing!           
           [*] unzip............................................ OK.           
           [*] route............................................ OK.           
           [*] fuser............................................ OK.           
           [*] killall.......................................... OK.  
All "Missing!" 's are installed
#### If the current behavior is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*
Honestly i have no clue how to recreate, Im using a Raspberry Pi 3 with the debian repo added to the arm version of the latest kali image for the Arm processor  

## Specs
*Paste the output of `./script/diagnostics.sh`*

root@kali:~/fluxion/scripts# ./diagnostics.sh
./diagnostics.sh: line 3: lib/InterfaceUtils.sh: No such file or directory
Usage ./scripts/diagnostics <wireless_interface>

**Comment by deltaxflux** [comment]
The diagnostic script requires a valid input. Like:
`./script/diagnostics.sh [interface]`

Can you provide:
`whereis rfkill` and `which rfkill`
