### ISSUE TITLE
Upload concept to Dev

### ISSUE THREAD

**Issue by Gotlander54** [FluxionNetwork/fluxion#151]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion crashes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*

#### What do you think the expected behaviour should be?
*What do you think should happen?*

### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by Gotlander54** [comment]
I have used your program, and while it is somewhat complex, it does what it is supposed to do. There is one "fatal" flaw, the "generic" sites won't convince anyone to enter private info unless they are pretty dumb these days. I know that "hacking" is illegal, but they don't hire "Security" guys who can't show results and fire guys who "get hacked" and it is very competetive field to say the least. I warned years ago that "hacking" the satellites rendered all other stuff useless, but no one listened and you might inquire why the old "MTV" computer-generated character, "Max Headroom," suddenly disappeared and has not been seen since "Regan-era" television. "Satellite" Transmission is far beyond the capability of those except governments folks who own satellite broadcast stuff. Anyway, I began last year "playing" with Fluxion and created my own "sites" because the original "router" pages will never work and are almost as bad as "wifiphisher" crap. I "modified" one of your own pages from "tplink" English that seemed appropriate to use and used "graphics" skills instead of "coding" skills since that is my forte. Instead of "router" page, it incorporates "company" page, since here in U.S., many modern and ancient individual routers are allowed by the ISP providers using "patched" firmware that has been vulnerable for many years. I will glady send this and let you "play with it," but My "graphics" are just modified versions of what you already have used before. I am not entirely sure how to upload simple mods to you, even github itself has been "hacked" in last couple years and who knows?
![background](https://user-images.githubusercontent.com/31826435/30251501-36b175b8-962e-11e7-8510-3d685770cc95.png)

![house1](https://user-images.githubusercontent.com/31826435/30251507-7287024c-962e-11e7-8b98-0e5af981065e.png)

**Comment by MPX4132** [comment]
I agree, some of the Captive Portal interfaces kinda suck. I made two of them, the Technicolor (EN) and the Arris (EN) one, I think those two are decent. The generic sites also need work. I’ve been working on the functionality aspect of the script, so I haven’t had time to deal with those. On a good quantity of them, the English is complete unorthodox. “You device has deficiencies” that sounds super weird. 

Anyway, this repo is for the actual script. The sites are in the [other repo](github.com/FluxionNetwork/sites). If you want to contribute, you’ll have to use git to commit your changes. It’s not hard or too complicated at all, [this article explains it fairly well](https://mattstauffer.co/blog/how-to-contribute-to-an-open-source-github-project-using-your-own-fork/).

If you’ve got anymore questions or issues related to this, reply here.

**Comment by Gotlander54** [comment]
I have not been able to get these specific pages to be sent by Fluxion, and previous versions before latest version 3 just "failed" after an hour or two and injection stopped working and "stuck in loop." I hope you understand both the obvious, and of course, I want a job in "security" for one of the many companies like "Linksys/Cisco," who just introduced a totally vulnerable new router series and, not to do anything illegal, yet, how can it work if not "tested" in reality??? The test guys are my neighbors with latest stuff, they have already consented, they are friends who are fascinated with this themselves and have laughed at me for amateur router pages like "wifiphisher" that "would not even fool my grandma" into giving out a password. I actually told a neighbor old woman I know that "Abcd1234" is NOT the best idea for an otherwise "impenatriable" new router. Your code works, it just has the one thing that is perhaps not something you want to test yourself in real world. I will risk the testing and give results. I have "open" WiFi guys for monitor, but only way to "know" is actual test. Just because you own "burglar" tools does not make you "a burglar" unless you actually become "blackhat," and I must admit, without them, we would not have learned much of how things are in cybersecurity fields. Nothing is illegal about .png pictures I came up with. The "sites" function, just the 'generic," won't send them on "attack" mode in version 3, and even though it did send in previous version 2, it still "looped back" anyway because the links must all function together. (excess code always creates a "loop" failure). I hope I am making some sense, I am certainly not an expert by any means, just I know that Linux is logic, and I "see it" in sleep.

**Comment by Gotlander54** [comment]
Thanks, the Technicolor is the most recent edition to the "line," but individual routers no longer send info, it goes to ISP with "multirouter" and they let you keep any old junk and "patch it" later. I completely understand, but so do they too that "no faith" except in ISP, not old router fools. I know this is really a problem, I am running a risk here just saying, but if it works it works. It falls on me and not you to do anything, you are "out-of-loop" as developer, not tester of technology. Setup with every other in this test is understood, but risk is only way to test it against "real" scenario and results will be given with no risk to the developer. I could probably get friends to develop, but world of internet getting more dangerous by hours, not days. I remember days of "FM" radio and this same argument when "recording" a music tape from "radio" went to courts as "copyright infringement" issues. Wow, I can laugh at that now as well as same issues with VCR tapes on old movies. So far, freedom of "airwaves" has prevailed. May not be so simple with iNTERNET in future. Freedom of course relies on those in horrible places in world to have access. I am not sure what to tell you, it could be illegal to breathe tomorrow without an "Air Tax." Fact is: Children who are born in U.S. today already owe nearly $4000 in Social security taxes before they are old enough to even have a social security number yet. The "Future" has no guarantees. You can ignore all contained in this post, I will gladly step back, it is not anything but some anonymous idea from a "crazy" graphics designer who says stupid things about a revolutionary ideaa, which failed with old "Linset" because of "outdated" design flaws that were abandoned years ago by code revisions of their day.

**Comment by Gotlander54** [comment]
I guess if you laugh at me, it is okay, what idiot who has had both bank and credit accounts stolen on "yahoo.com" still uses the same stupid account??? Well, I have had this same stupid account for over 20 years, and if someone else wants to be Me, they will be ones who talk to credit folks about my ungodly bills. I am on Food Stamps, my last job at Amazon.com Warehouse just folded when I got sick and landed in hospital, at their request.. They do not tolerate anyone who gets sick, period. I was "TERMINATED" just like all other "robots" that fail. Trying to create something new and this may be dangerous. Suppose internet is "banned" for public use at some future date??? Get the picture??? Be careful, this is not "funny" if it gets rough later. I will send everything I can, just so far, stuck in "loop" until page return, which needs something from other than router companies who sub-contract through ISPs. Obvious!!!!

**Comment by MPX4132** [comment]
It's a bit hard trying to follow what you're saying. I believe you're trying to add your contribution to the repository, which as I understand is a graphical improvement to a portal, but again, you'll have to use git and github. I also understand you're saying there exist routers that redirect straight to their ISP for authentication, that's pretty odd and I've never heard of it. However, that's completely fine. It's fine because routers have independent configuration interfaces. Just like you, I live in the US and I don't see what the big problem is. All routers I've seen around here are just like every other router. 

I test the script with a separate isolated virtual access point. I'm not in danger of doing anything illegal. Everything I test on, and test with, is my own property. Thanks for your offer, by the way, but I prefer doing things personally.

**Comment by Gotlander54** [comment]
I don't wish to "scare you" away from present devlopment, the "Fluxion" program already works just fine for those who understand it. It is not "your job" to do what I am doing, but all results will be forwarded to you in any event because it is just right and proper that you can "see" if it works. I will keep results between My own developer team and you. No reasons to publish any results are clearly understood and should remain that way regardless of what we discover using the program. It does work, and "hats off" for what it is worth. Most of the much more advanced so-called "code experts" are asking questions that don't matter, it seems rather silly now, but this could be "The Future" for ordinary "dwellers" who just want to "get online" to speak for a moment in time and "silence" is the goal of oppression, no matter what is said or who says it.
