### ISSUE TITLE
Trouble with Captive Portal

### ISSUE THREAD

**Issue by calee4nyaboy** [FluxionNetwork/fluxion#153]
I am running the latest version of Kali Linux and have used Fluxion 3.2 and 3.3 with similar results described below.  USB Wifi card is ALFA AWUS036H (RTL8187).  Card has been tested to properly: go into monitoring, capture handshake and perform injection.  I wanted to post a log file as I thought I would be asked for one so I ran "export_ FLUXIONDebug=1 ; ./fluxion.sh".  I am sort of new to Linux so if it outputted a log file, I have no idea where it is or if that is how to gather a log file.  If not, please provide very specific guidelines and I will perform them verbatim.  Remember, I'm not new to IT but Linux is not one of my strengths.

I will describe in as much detail as to whats going on.  After choosing to start a captive portal, Fluxion asks:

[*] Select an interface for the captive portal.

My options are:

[1] eth0     [+] Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/G
[2] wlan0    [+] Qualcomm Atheros AR242x / AR542x Wireless Network Adapter (PCI-
[3] wlan1    [+] Realtek Semiconductor Corp. RTL8187

I am not sure which one to use.  When it ran the scan on all channels a moment before this, I chose wlan1 (the ALFA unit).  If I choose wlan1 for the captive portal, Fluxion says:

Starting Captive Portal access point service...

The window just sits there saying that.  It never starts the other four windows and never goes any further.  However, if I go back and choose eth0 instead, it does move beyond that point and opens the four windows.  Once the four windows are open, my cell phone gets kicked off the test AP I'm using.  I can not log back onto the test AP point.  When I enter the password (that I know is correct) in the Android WiFi interface (not a browser), it says "incorrect password".  Secondly, I was under the impression a second AP  (the evil twin with no encryption) was supposed to show up in my phone.  The SSID for my test AP is "TRENDnet".  However, I never see two AP's called TRENDnet on my phone.  What also might be important is that after a few minutes, in the lower right "FLUXION AP Jammer [mdk3]" window, it says:

Periodically re-reading blacklist/whitelist every 3 seconds

read failed: Network is down
wi_read(): Network is down

So my questions are:

-  Which interface do I use for the captive portal?  Must I use the same USB ALFA that I used for scanning the Wifi?  Or must I specifically use a different one (like you need two cards to do this)  Or is eth0 best to use?  I can't even get it to work on the ALFA (wlan1)

-  What behavior should I expect after my phone gets kicked off the AP?  Does any of the behavior above sound like I'm experiencing a bug?  I have never seen this actually work so I don't know exactly what behavior to expect.

-  When it says "Network is down" in the Jammer window, is that a problem?

This is a neat program and am looking forward to testing it.  Any help you can provide is appreciated.

**Comment by calee4nyaboy** [comment]
Update: I just downloaded an older version.  (0.25 r136) and NONE of these problems happened.  I got it to work!  These newer versions are buggy!

**Comment by usama7628674** [comment]
@calee4nyaboy  I've older version (0.24) and it is the stable as far I can tell.

**Comment by FrZ-BR** [comment]
@calee4nyaboy im getting this same problem in the "Fluxion AP Jammer"

When it says "Network is down" in the Jammer window, is that a problem?

**Comment by usama7628674** [comment]
@FrZ-BR I've old version.I can send it to you and you can check it and see if that works for you.

**Comment by FrZ-BR** [comment]
@usama7628674 Thanks i would be very thankful 🥇

**Comment by usama7628674** [comment]
Ok sending it via sendspace.just wait a bit

**Comment by usama7628674** [comment]
Here's the link       https://www.sendspace.com/file/ilhdzx
First run setup and then fluxion script

**Comment by usama7628674** [comment]
@FrZ-BR Let me know it that works for you or not.

**Comment by FrZ-BR** [comment]
@usama7628674 Thanks mate i will try it in about +- 3hours... i back with results !

**Comment by usama7628674** [comment]
@FrZ-BR I will see your reply tomorrow.I would've slept by that time.

**Comment by MPX4132** [comment]
That option says where to make the rogue network available. If you have an ethernet AP device, use eth0. Otherwise use a wireless interface wlanX. I'm almost 100% positive it's a bug with your driver. Check out previous (closed) issues.

**Comment by FrZ-BR** [comment]
@usama7628674 Work great. no more "Network is down" but im getting alot of Handshakes corrupted.. that never happen before with the newest version... any ideas?

**Comment by calee4nyaboy** [comment]
@MPX4132  Yes, I have seen some people talk about the RTL8187 driver possibly having issues. But the fact that everything works fine in an older version with my exact same hardware tells me it's not the driver, it's buggy software.

**Comment by calee4nyaboy** [comment]
@FrZ-BR  Yes, the older version did report corrupted handshakes, I saw that too. I just ignored it and I was still able to get the password off my test AP

**Comment by FrZ-BR** [comment]
@calee4nyaboy so you mean i should ignore the handshake part and continue whiteout it? im novice sorry.

**Comment by usama7628674** [comment]
@FrZ-BR The version that I sent you yesterday was 0.24 @calee4nyaboy  is using 0.25 r136 so if you want to try that version then here's the link for that version.
https://github.com/disquette38/fluxion

**Comment by calee4nyaboy** [comment]
Update Number Two:  I just downloaded Ver 2, Rev 3 and THAT is by far the best version I have found.  It was flawless.  No errors, no corrupt handshake stuff, nothing.  I believe this is the version that most people on the YouTube videos were using where they said it was working with no issues.

The client (my cell phone) even auto-connected to the evil twin after it was kicked off the target test AP.  In ver 0.25, I never saw that behavior as I have to connect to the evil twin manually.  I find this to be a very important feature because the target user will not get confused about seeing two identical SSIDs when browsing local WiFi because the program will usually connect them *for* them.  So they never have to see the local WiFi list in the first place (it connects behind their back)

I only used this version for a short time because I have to go take care of some other things but thats what I can report so far.

**Comment by FrZ-BR** [comment]
@calee4nyaboy what about https sites? that version can create an valid ssl cert?

**Comment by usama7628674** [comment]
@calee4nyaboy Will you please send me this Ver 2 Rev 3.I would be very thankful.

**Comment by usama7628674** [comment]
@FrZ-BR If you've got a personal certificate, you must save it at fluxion/attacks/Captive Portal/certificate/server.pem and the attack will automatically detect it. If you don't have a personal certificate, select the option to automatically generate one.

**Comment by FrZ-BR** [comment]
@usama7628674 Yes, i tried both and all https sites back with SSL-Warning. how did you manage to override this?

**Comment by usama7628674** [comment]
I didn't.Maybe any personal certificate will do it.

**Comment by FrZ-BR** [comment]
im lost about this. tried everything.. anyone got lucky with https?

**Comment by calee4nyaboy** [comment]
@usama7628674  I am new to this site and don't know if you can "PM" (private message) through here. So I don't know how to send you the file.

As for the https sites, I'm not really sure what that's about or what it has to do with getting the password. I know the program says it makes an SSL thing but I don't know why we need it. If someone can explain that would be great.

**Comment by FrZ-BR** [comment]
@calee4nyaboy it's because if you try for example to HTTPS://Facebook.com will give an warning because of the ssl...

This will make lose credibility

**Comment by calee4nyaboy** [comment]
Okay, that makes sense. Honestly, I doubt most people will attribute that error message to being logged into a rogue AP.  If they are not aware enough not to log into the evil twin then they won't know much about the SSL error, at least I think.

**Comment by FrZ-BR** [comment]
Yeah I think that too. But with the version 0.25 the client auto-connect to the rogue AP after start the attack (friend above confirme too). And that https bypass would be the dream.... 

I still don't know why the version 0.25 do the auto connect and the latest version not.

Which version are you using with success?

**Comment by usama7628674** [comment]
@calee4nyaboy You can upload to https://www.sendspace.com/ and after that send the link to my mail
usamasattar098@gmail.com

**Comment by usama7628674** [comment]
@FrZ-BR @calee4nyaboy This certificate doesn't have a valid signed signature. That's why you see a warning.

**Comment by FrZ-BR** [comment]
@calee4nyaboy please share the link here too just past it

**Comment by FrZ-BR** [comment]
@usama7628674 no way to "fix" this? I'm novice sorry

**Comment by usama7628674** [comment]
@FrZ-BR I will share the link once I get link first.

**Comment by strasharo** [comment]
@MPX4132 Just as a tip, previously we were enforcing folks with 8187 to use airbase-ng, because it's incompatible with hostapd. Haven't checked the current source, but that might be the difference.

**Comment by MPX4132** [comment]
@strasharo Oh, I see. Yeah, that's more than likely it. Thanks for pointing that out man.

**Comment by deltaxflux** [comment]
@MPX4132 I don't check my code after fluxion v3 in detail. Did you remove the check?

**Comment by MPX4132** [comment]
@deltaxflux Yeah, I did, I just checked. I did that because I don't think any card/driver should get special treatment. Instead of special cases, I just added more options to the script. I think we shouldn't include special cases because if we include it for one, others will want to have their special cases included as well and the script will likely get extremely messy over time.

@calee4nyaboy You're going to have to use `airbase-ng` as the access point service, `hostapd` isn't supported by your card. If your driver doesn't support virtual interfaces, you'll have to figure something out yourself, man. The script relies on virtual interfaces. I'm not saying to give up and though it out, I'm saying you should look for an alternative, like a different driver that might support your device. Unfortunately, I'll have to close the issue. If you need any more help, or you want to share an idea that might pose as a solution to this, post your thoughts here, open a new issue otherwise.

**Comment by tomford007** [comment]
Running Fluxion 3.8 and I'm having this exact problem. I'm using a Hawking USB WiFi device. Very disappointing.

**Comment by tomford007** [comment]
Anyone?

**Comment by hasanalizxc** [comment]
> @FrZ-BR I've old version.I can send it to you and you can check it and see if that works for you.

Can you send me old version?

**Comment by hasanalizxc** [comment]
> Update Number Two: I just downloaded Ver 2, Rev 3 and THAT is by far the best version I have found. It was flawless. No errors, no corrupt handshake stuff, nothing. I believe this is the version that most people on the YouTube videos were using where they said it was working with no issues.
> 
> The client (my cell phone) even auto-connected to the evil twin after it was kicked off the target test AP. In ver 0.25, I never saw that behavior as I have to connect to the evil twin manually. I find this to be a very important feature because the target user will not get confused about seeing two identical SSIDs when browsing local WiFi because the program will usually connect them _for_ them. So they never have to see the local WiFi list in the first place (it connects behind their back)
> 
> Also, I dont think this version ever asks which interface to run the evil twin on. Why would the latest version ask but this version doesn't?
> 
> I only used this version for a short time because I have to go take care of some other things but thats what I can report so far.

can you send v2 link?

**Comment by calee4nyaboy** [comment]
The website that hosted version 2.3 is no longer active.  I would have to send it to you another way as I have it saved on my laptop.

**Comment by rohanagrawal8053** [comment]
I am using alfa AWUS036ACS .it supports monitor mode and packet injection but when I use fulxion CAPATIVE PORTAL it says"unable to start CAPATIVE PORTAL INTERFACE, returning.
Please help what to do

**Comment by cjb900** [comment]
Because your adapter does not support VIF. VIF is the ability for the wifi adapter to be able to create a fake AP and deauth at the same time. Not all wifi adapter/chipset support VIF. There is no way that i know of to give the chipset in that adapter VIF support. You will either need to replace that adapter or get a second one to use 2 adapters in fluxion.
