### ISSUE TITLE
Clients Online not working?

### ISSUE THREAD

**Issue by FrZ-BR** [FluxionNetwork/fluxion#155]
Hello,

Just a quick question....

"Clients Online" is not showing users online?

Thanks.

**Comment by deltaxflux** [comment]
Should work and it works for me. Sure that you have any connected clients?

**Comment by MPX4132** [comment]
Works for me as well.

**Comment by FrZ-BR** [comment]
@deltaxflux im positive. i can see the DNS requests and the counter go up. any ideas where i can look for? Kali 2017 OS

**Comment by usama7628674** [comment]
Clients online is working fine in latest version.

**Comment by deltaxflux** [comment]
Can't confirm this issue.

**Comment by tomford007** [comment]
Same issue with 3.8 and Kali 2017.3
