### ISSUE TITLE
SSL cert how-to?

### ISSUE THREAD

**Issue by FrZ-BR** [FluxionNetwork/fluxion#159]
Question.

How to add the ssl cert to https sites? i cant find any information or instructions for this. 
if the person try www.google.com will show up an waning about the SSL.. how you guys handle with https sites?

https://image.prntscr.com/image/xT3eAUNaScW5LRDi9aGoFg.png

if anyone can show me the right way i would be thankful !

**Comment by deltaxflux** [comment]
We already create an SSL certificate. This certificate doesn't have a valid signed signature. That's why you see a warning.

**Comment by Fix3dll** [comment]
How can i do it without SSL cert? @deltaxflux

**Comment by rad4day** [comment]
At this point in time you cant unless you get hold of a CA certificate.
Google, Facebook etc use HSTS with certificate preloading. So most browsers WONT allow the user to access the site via http.

**Comment by Fix3dll** [comment]
When i am trying to enter google, page not loading. Normally i need to see verification page. What should i do? Am beginner and dont know english well but i want to learn this.

**Comment by MPX4132** [comment]
@Fix3dll You’ll have to somehow get the user to use an http (unencrypted page). Some devices auto-detect the captive portal and prompt the user to sign in.

**Comment by takroli3** [comment]
I need a solituon for problem same
