### ISSUE TITLE
Add index.php to lighttpd.conf

### ISSUE THREAD

**Issue by sweft54** [FluxionNetwork/fluxion#160]
### Do you want to request a *feature* or report a *bug*?
Feature

### What is the current behaviour?
Not possible to have index.php in the current captive portal

#### If the current behaviour is a bug, please provide the steps to reproduce it.
NA

#### What do you think the expected behaviour should be?
Add index.php to lighttpd.conf

### If this is a feature request, what is the motivation or use case for the added feature?
Ability to let a user to have its own captive portal which has a landing page to index.php

### Specs
NA

I'm proposing to edit the file:
fluxion/attacks/Captive Portal/attack.sh

To add to lighttpd.conf index.php

to be:
`index-file.names = (
        \"index.php\",
	\"index.htm\",
	\"index.html\"
)`

instead of:
`index-file.names = (
	\"index.htm\",
	\"index.html\"
)`

I don't know if this is related to index.php, but this may introduce some problems with lighttpd (I'm using kali 2017.2 with up to date updates): my lighttpd server stops working randomly (the process is still active, but it is not serving the captive portal, it serves again only after a manual restart) and I need to use apache2 (kill lighttpd and start apache manually), which is working perfectly.
If the feature is accepted, it should be tested to not have lighttpd to stop if this is related.

**Comment by deltaxflux** [comment]
Done, thanks for requesting.

**Comment by Geczy** [comment]
nice find
