### ISSUE TITLE
 Installing fluxion on debian break a lot of things

### ISSUE THREAD

**Issue by medBouzid** [FluxionNetwork/fluxion#162]
I installed fluxion on debian and it removed a lot of things automatically, after the installation finished the fonts of my system changed, and a lot of other things as well, also I was not able to run my 3G usb connexion until I installed this : `apt-get install netbase ifupdown ppp` , my system becomes terrible, Now I tried to open an external drive, when I connect it to my laptop it appears in the folders explorer, but when I click on it, the folders explorer disappear, I thought maybe it's unmounted so I tried this : 

`sudo mount /dev/sdc1 /mnt`

I got this

```
Mount is denied because the NTFS volume is already exclusively opened.
The volume may be already mounted, or another software may use it which
could be identified for example by the help of the 'fuser' command 
```
But I am not able to open it, every time I try the whole file explorer disappear :(

**Comment by medBouzid** [comment]
@deltaxflux wow you're a hero :)

**Comment by deltaxflux** [comment]
Thanks, I know.
