### ISSUE TITLE
[Disregard my goofup..iptables]Captive portal not redirecting connected clients.

### ISSUE THREAD

**Issue by PoSHMagiC0de** [FluxionNetwork/fluxion#163]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
Clients are not directed to captive portal when browsing. (Currently testing against a Google Pixel).

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Followed instructions.  Can get handshake, can spin up captive portal.  Other wifi is being jammed successfully.  Can connect to rouge ap.  Go to browse and get "no internet access", no captive portal shows up.

#### What do you think the expected behaviour should be?
A long time ago when I first tried this clients would be directed to captive portal when they tried to browse anywhere in browser.  I even had my tablet tell me I had to sign in before getting internet access.

Just to make sure captive portals work I tried wifiphisher (both wifiphisher and fluxion started having crashing startup issues when I switched to ParrotOS) and it is working as intended.  Now I just need wifiphisher captive portal redirect ability in fluxion.  :-) 

### Specs
[ FLUXION Info ]
FLUXION V3.3

[ BASH Info ]

GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
Device: phy1
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: No Answer...

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.12.0-parrot6-amd64 (parrot-devel@lists.parrotsec.org) (gcc version 6.4.0 20170805 (Debian 6.4.0-3) ) #1 SMP Parrot 4.12.6-1parrot6 (2017-08-24)

edit:
Disregard.  I forgot I had set some extreme rules for my default firewall.

**Comment by MPX4132** [comment]
It’s probably something with the operating system, maybe routing is an issue... I would need to get a virtual machine running and test it, but I can’t at the moment, and not for at least for two weeks.

**Comment by usama7628674** [comment]
Yes sometimes it creates such type of problems but I tried several times and it worked at least for me.

**Comment by MPX4132** [comment]
@PoSHMagiC0de From what I understood, it seems you figured something out. I'm closing the issue. Comment here if you have anymore feedback.
