### ISSUE TITLE
Real issue this time...have to reboot after running Fluxion, no network.

### ISSUE THREAD

**Issue by PoSHMagiC0de** [FluxionNetwork/fluxion#164]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
network on wired and wireless does ping ips or resolve names after using fluxion.
Also notice several processes still running when done light lightdm.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Just run through fluxion once and then exit.  Enable our networkmanager and try to browse via wifi or ethernet.

#### What do you think the expected behaviour should be?
I expect all network services to return as they were or capable to be returned by just enabling the networkmanager.

### Specs
[ FLUXION Info ]
FLUXION V3.3

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
Device: phy1
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: No Answer...

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.12.0-parrot6-amd64 (parrot-devel@lists.parrotsec.org) (gcc version 6.4.0 20170805 (Debian 6.4.0-3) ) #1 SMP Parrot 4.12.6-1parrot6 (2017-08-24)

**Comment by usama7628674** [comment]
use these commands 
`nmcli n on`
`service networking restart`
`service network-manager restart`
`service wpa_supplicant restart`

**Comment by MPX4132** [comment]
Hmm, those shouldn't be required. Fluxion should reset everything automatically, unless you're running it with the killer flag... Then that's on you.

**Comment by deltaxflux** [comment]
@usama7628674 
I don't would use service is obsolete. Instead, I recommend systemctl:
`systemctl restart wpa_supplicant`
`systemctl restart NetworkManager`

**Comment by usama7628674** [comment]
@deltaxflux Yes you are right but I thought that would also work.

**Comment by deltaxflux** [comment]
Not on modern OS. Arch completely use systemctl and replace services

**Comment by usama7628674** [comment]
@deltaxflux But I use kali and I think you can tame any linux the way you want.

**Comment by deltaxflux** [comment]
That is wrong e.g I sad earlier but if you don't think of arch is also a linux

**Comment by usama7628674** [comment]
I was reading about black arch linux and it comes preinstalled with more than 1500 tools which is way more than kali.I respect the power of any linux whether it is kali,arch,ubuntu,debian etc.

**Comment by deltaxflux** [comment]
No response closing.

**Comment by kidemanny** [comment]
after checking the handshake it tells me to choose english but then it creates a fake wifi but does not disconnect the one i am connected to what should i do
