### ISSUE TITLE
people would connect but not get the Capture Portal page in fluxion

### ISSUE THREAD

**Issue by lvyflok** [FluxionNetwork/fluxion#166]
people would connect but not get the Capture Portal page

**Comment by deltaxflux** [comment]
Run the diagnostic script.

**Comment by lvyflok** [comment]
But how ?

**Comment by MPX4132** [comment]
Go to fluxion's root directory and execute the script from there:
```
cd fluxion
./scripts/diagnostics.sh wlanX # Replace wlanX with your interface name
```

**Comment by lvyflok** [comment]
Thank you
can I ask you another question here. or i need to create another topic?

**Comment by deltaxflux** [comment]
Create another issue.

**Comment by deltaxflux** [comment]
What is the output?
