### ISSUE TITLE
Captive portal is not working (Connection refused)

### ISSUE THREAD

**Issue by usherfiles** [FluxionNetwork/fluxion#167]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behaviour?
Before you read this, I'll attach the Logs, screenshots and the "FluxSpace" folder on a ZIP here:
[Fluxion Captive portal Test.zip](https://github.com/FluxionNetwork/fluxion/files/1305056/Fluxion.Captive.portal.Test.zip)

Fluxion works fine until starts the AP and the captive portal... First of all , android says "No internet connection, please connect to another network" instead of "you need to login on the network" or something like that.
Second, Even if I manually go to the applications on android and select chrome, even if I type 192.168.1.1 MANUALLY to test the captive portal, it gives me a "Connection Refused" error, same happens with whatever I put on the URL address bar.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Just launch the fakeAP on your network and try haha

#### What do you think the expected behaviour should be?
I think it would be convenient to people with smarthphones to not be noticed that there's not internet and get a "Sign into WifiNetwork *SSID*" instead of "No internet connection" notification.
I don't know if it already works like that, but it's not working for me 

### Specs

[ FLUXION Info ]
FLUXION V3.3

[ BASH Info ]
GNU bash, versión 4.3.46(1)-release (i586-slackware-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
Licencia GPLv3+: GPL de GNU versión 3 o posterior <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /usr/bin/bash

[ Interface (wlan0) Info ]
Device: phy1
Driver: rtl8192se
Chipset: Realtek Semiconductor Co., Ltd. RTL8191SEvB (rev 10)
Injection Test: Injection is working!

[ XTerm Info ]
Version: X.Org 7.7.0(325)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.5
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 r2858 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.4.16-smp-wifislax (root@wifislax) (gcc version 5.3.0 (GCC) ) #1 SMP PREEMPT Sat Jul 30 02:34:00 CEST 2016

**Comment by deltaxflux** [comment]
You created 2 issues for the same specific problem I already answered you.
