### ISSUE TITLE
handshake problem

### ISSUE THREAD

**Issue by coco5843** [FluxionNetwork/fluxion#168]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*This impossible to get the handshake, and even if you have a custom handshake you can't use it "invalid hash file*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*2 computers, 2 fluxions, I was able to get the handshake with the rev 2 there is 1 week ago, and now I can't, if I take this handshake file and put it in another computer where fluxion is installed this handshake is detected but when I start the ap, an error is displayed: "invalid hash file" *

**Comment by deltaxflux** [comment]
It is **not** an issue with fluxion. To capture a handshake depends on the user and many other facts.
