### ISSUE TITLE
Evil Clone Standalone Functionality

### ISSUE THREAD

**Issue by xmpp-23179** [FluxionNetwork/fluxion#169]
### Do you want to request a *feature* or report a *bug*?
*Feature*

### What is the current behaviour?
*Evil Clone Standalone Functionality*

### If this is a feature request, what is the motivation or use case for the added feature?
It would be nice to be able to utilize Fluxions "Evil Clone" functionality with simulated inputs (BSSID, SSID, client capture page, etc.) It would make it easier to demonstrate honeypot AP risks to clients.

**Comment by deltaxflux** [comment]
I don't get the purpose for that.
