### ISSUE TITLE
Not create the fake AP (only with a one wifi network)

### ISSUE THREAD

**Issue by navyarm** [FluxionNetwork/fluxion#17]
### Which version of fluxion are you using?
Fluxion 2, REV 9

### What distribution of Linux (including the version) are you running it on?
Kali linux 3.22.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

Qualcomm atheros AR9485 wireless network adapter

### Which is the driver for it?
nl80211

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it

Hello, and thanks for this great program. Has worked perfectly so far, today i found a problem. The program works well all the steps except when he has to create the fake AP. When i select the number of the interface i want, the terminal (like the one in picture) does not appear. Later, however, the 4 terminals appear, but the fake AP is not visible (not create i think). This only happens with a wifi network in particular, Before, however, he created the fake AP Even with this wifi network.
![27696800-79390810-5cea-11e7-8208-9aede8940f34](https://user-images.githubusercontent.com/29991023/27981558-a2ec45d8-635b-11e7-8820-aff58c476a17.jpg)

**Comment by deltaxflux** [comment]
#12

**Comment by sarimnaveed2** [comment]
I have the same issue and #12 isn't related to it I guess. The fake AP isn't created or it isn't visible ....

**Comment by tanimtanu** [comment]
I have the same problem ap is not cteated what to do help me pls

**Comment by MPX4132** [comment]
@tanimtanu Make a new issue, this one's too old.

**Comment by tanimtanu** [comment]
Pls give me its solution first

**Comment by deltaxflux** [comment]
If you want a solution you need to make a new issue. We can't deal with your problem if you don't give us detailed information about or system. This issue seems to be old use another one like @MPX4132 said.

**Comment by tanimtanu** [comment]
Hmm give the sloution of that man issue.Again dhcp server started failed
some error shows in here also

**Comment by deltaxflux** [comment]
Good luck.

**Comment by rohit0x5** [comment]
same error is tart and wait 45 min the fake ap was not created fuck men my neigbour is shouting

**Comment by cjb900** [comment]
@rohit0x5 why are you commenting on something that was closed 5 years ago. If you are having current issues with fluxion open a new issue and provide as much information on your issue including your setup then we can try to help. You can also join the [discord ](https://discordapp.com/invite/G43gptk)for faster responses
