### ISSUE TITLE
Karma Attack Implementation

### ISSUE THREAD

**Issue by Nimda-suriV** [FluxionNetwork/fluxion#170]
### Do you want to request a *feature* or report a *bug*?
*Feature*

### If this is a feature request, what is the motivation or use case for the added feature?

Hi, can we implement the KARMA Attack in Fluxion? It would be more effective if say we can DoS the realAP and then push the evil twin AP via the KARMA Attack and the target would be none the wiser.

Basically if the victim has Open Networks set automatically, these will get picked automatically if the realAP was DoS'd (especially if the evil twin's tx-power was stronger than the realAP). Mobile devices are susceptible to this attack from my tests

Wifiphisher uses roguehostapd for this, a modified version of hostapd that wraps a KARMA Attack inside it via python. The problem with Wifiphisher though is that it takes completely over a Wifi Adapter, you can't run anything else using your one lonesome adapter. So me thinks that Fluxion is more flexible in this respect since it doesn't need a Dual Mode Wifi Adapter (can run Station and Monitor simultaneously) or 2 Wifi Adapters.

PS: There is also this Lure10 Attack that you may want to check out also, Wifiphisher has it as well.

So is it possible to implement the KARMA Attack using 1 Wifi Adapter? 

Thanks

**Comment by usama7628674** [comment]
@Nimda-suriV You can now use wifiphisher to do jamming and create an AP with single wifi adapter.

**Comment by deltaxflux** [comment]
Pointless, Wifiphisher stops at the first entered the password without even checking. If you want this feature I recommend to use your own tools but I don't see any positive advantages to implement that.

**Comment by usama7628674** [comment]
@deltaxflux Wifiphisher now supports WPA key check whether it's correct or wrong just like fluxion.

**Comment by deltaxflux** [comment]
But the karma attack doesn't do that.

**Comment by Nimda-suriV** [comment]
@deltaxflux 

I'm not sure if you think I'm trying to sell Wifiphisher... but I'm talking about the KARMA Attack, not necessarily Wifiphisher.

The KARMA Attack isn't unique to wifiphisher, Wifi Pineapple does it, right?

I'm talking about the attack's capability to have the victim connect automatically to the evil twin you're generating without them knowing it.

As you disable their AP, they just basically connect to your fakeAP. Androids and iOS devices are susceptible to this attack is all I'm saying and it would be nice if this project implemented such attacks to its existing versatility.

Think about it, most people these days use their phones and tablets anyway. So it is a really useful feature pentest wise. Instead of just hoping for them to manually pick their spoofed AP, they just connect automatically and if you tailor a convincing enough phishing page they'd buy it. Tried and tested.

It's not that hard to harvest popular open wifis and business' and clients mostly use them.

I'm not sure if I'm sensing some anger there, but I guess if you think the KARMA Attack is "pointless" or just don't like Wifiphisher (I promise I'm not trying to sell it here, I just think that those 2 attacks are pretty useful and I don't think there's a license against implementing them), I guess I'll just have to modify Fluxion myself then.

It would have been nice if it was official to Fluxion though since many stuff that Fluxion can do they're still trying to figure out how to make it python-native to Wifiphisher.

Thanks for replying!

@usama7628674 

Yes you can run Wifiphisher with 1 Adapter now but just as a Wifi Honeypot. Unless you have a Dual Mode Adapter, you're just a fakeAP waiting for someone to connect.

You still need an external adapter to do the DoS or at least 1 other Laptop (which I have to use unfortunately). Unlike Fluxion that can leverage both DoS and fakeAP with just a non-Dual Mode Adapter.

And Wifiphisher at the moment doesn't support dynamic languages, although that's not so hard to mod actually.

Anyway, thanks for the feedback.
