### ISSUE TITLE
Where is the default handshake file

### ISSUE THREAD

**Issue by EOS123** [FluxionNetwork/fluxion#171]
Enter path to handshake file (Example: /.../dump-01.cap) 
Absolute path: 
How do I enter a path to a handshake file?
![default](https://user-images.githubusercontent.com/31821291/30568192-6c12e80c-9d06-11e7-9376-ae52b6768d07.PNG)

**Comment by calee4nyaboy** [comment]
For me, if I put the handshake file on the desktop,  then I have to type in:

/root/Desktop/handshake.cap

It IS caps sensitive. Notice the capitalized "D".
Obviously you need to insert your correct handshake.cap file name in the example above.

**Comment by EOS123** [comment]
![8 enter path to handshake file](https://user-images.githubusercontent.com/31821291/30575184-96bf16a4-9d31-11e7-98b4-12c08da53957.PNG)

![7 select a method to retrieve the handshake](https://user-images.githubusercontent.com/31821291/30575180-90d5231e-9d31-11e7-8e0f-63280b25fe89.PNG)

![6 select an access point service](https://user-images.githubusercontent.com/31821291/30575173-85783308-9d31-11e7-80af-b913419cd026.PNG)

![5 select an interface for the captive portal](https://user-images.githubusercontent.com/31821291/30575165-7b142f20-9d31-11e7-90a3-fe8e042556ec.PNG)

![4](https://user-images.githubusercontent.com/31821291/30575161-756653aa-9d31-11e7-980f-90701ffcf3ed.PNG)

![3](https://user-images.githubusercontent.com/31821291/30575146-676908f6-9d31-11e7-978e-e63bca394bf1.PNG)

![2 select a channel to monitor](https://user-images.githubusercontent.com/31821291/30575143-61980a12-9d31-11e7-9ab8-eb2d3ed3debe.PNG)
Please guide the problems encountered during the FLUXION 3 operation
![1 select a wireless interface](https://user-images.githubusercontent.com/31821291/30575137-5b7170f6-9d31-11e7-8062-5333ffb7eee5.PNG)
Enter the path of the handshake file. How to proceed?

**Comment by deltaxflux** [comment]
Center the full path to the cap. E.g.
**/root/Desktop/Cap1.cap**
