### ISSUE TITLE
Hanshakes captured but not saved/detected

### ISSUE THREAD

**Issue by DjangoSec** [FluxionNetwork/fluxion#173]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion Doesn't recognize handshakes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*
![screenshot from 2017-09-19 19-04-42](https://user-images.githubusercontent.com/29945254/30605846-f7f89b00-9d6f-11e7-9315-ceee9e918a72.jpg)
*
### Note
Network goes down after capturing the handshake. it doesn't get saved in the handshakes folder and the script wont detect it.

### Specs
*[ FLUXION Info ]
FLUXION V3.3

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /usr/bin/bash

[ Interface (wlp0s29f7u6) Info ]
Device: phy0
Driver: ath9k_htc
Chipset: Qualcomm Atheros Communications TP-Link TL-WN322G v3 / TL-WN422G v2 802.11g [Atheros AR9271]
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
read failed: Network is down
wi_read(): Network is down
Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/bin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.9.48-1-MANJARO (builduser@manjaro) (gcc version 7.1.1 20170630 (GCC) ) #1 SMP PREEMPT Thu Sep 7 10:44:53 UTC 2017
*

**Comment by deltaxflux** [comment]
The handshake is not valid. Go in debug mode and show the logs.

**Comment by deltaxflux** [comment]
Check #165 out.
