### ISSUE TITLE
Fluxion 3 into the handshake file path is invalid how to solve

### ISSUE THREAD

**Issue by EOS123** [FluxionNetwork/fluxion#177]
![how does fluxion 3 go to the handshake file](https://user-images.githubusercontent.com/31821291/30700317-d7c84514-9f19-11e7-9409-fda90cb5fb3d.PNG)

**Comment by MPX4132** [comment]
Oh, nice, you got both the output and the issue in one screen shot. You're telling fluxion to use a directory as the capture file, which is invalid. What you need to do is capture a handshake file for the target access point by running the `Handshake Snooper` attack, then go into the attack you tried on the image and input the path to the handshake you caught earlier. If you use the `Handshake Snooper` attack, fluxion will auto-detect the file and won't ask you for it anymore.

**Comment by talal2** [comment]
i opened a terminal into handshake snooper, and i ran -> ./attack.sh .
But nothing 
Can you please help me ?

**Comment by MPX4132** [comment]
@talal2 You shouldn’t execute fluxion’s internal scripts. Those should only be used by fluxion. You may only execute `fluxion.sh` and `./scripts/diagnostics.sh`.

**Comment by talal2** [comment]
./scripts/diagnostics.sh -> I Don't have any prob in it .
fluxion.sh -> 30 min, No Handshake -> http://prntscr.com/gp92ub :(

**Comment by MPX4132** [comment]
Sorry, I’m having trouble understanding what you’re asking. Only run `fluxion.sh`, **do not** run any other script. **That means you shouldn’t try running `attack.sh`.** `fluxion.sh` will run the attack itself.
