### ISSUE TITLE
FLUXION won't MDK Deauth during the Captive Portal process

### ISSUE THREAD

**Issue by lisztomania** [FluxionNetwork/fluxion#178]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*During the Captive Portal process, the window running the mdk deauth script remains blank. It's as if the script is not running. To confirm, I tried connecting to the network I was attacking and I was able to connect.*

#### What do you think the expected behaviour should be?
*It should prevent anyone from being able to connect to the original Access Point*

**Comment by deltaxflux** [comment]
Well, this is a problem which relates to mdk3. We plan to switch to aireplay-ng later.
