### ISSUE TITLE
Wifi Card selection

### ISSUE THREAD

**Issue by BLX-S** [FluxionNetwork/fluxion#18]
### Which version of fluxion are you using?
V2 Rev9

### What distribution of Linux (including the version) are you running it on?
Linux parrot 4.9.0-parrot25-amd64

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Broadcom Limited BCM4360 802.11ac Wireless Network Adapter (rev 03) (MBP retina Built-in card)

### Which is the driver for it?
driver | = | wl0
driverversion | = | 6.30.223.271 (r587334)

### Does it support injection ( output of aireplay-ng -9)
Yes it does:
└──╼ #aireplay-ng -9 prism0
18:46:38  Trying broadcast probe requests...
18:46:40  No Answer...
18:46:40  Found 2 APs

18:46:40  Trying directed probe requests...
18:46:40  54:FA:3E:34:C4:4A - channel: 56 - '*I masked out the AP name for security purposes*'
18:46:46   0/30:   0%

18:46:46  90:5C:44:F7:B0:74 - channel: 64 - ' '*I masked out the AP name for security purposes*'
18:46:52   0/30:   0%

### General description of your issue along with the steps to reproduce it
After the fluxion install I verified that all the dependencies were installed and I managed to successfully start the tool. I selected all channels but it said the wifi card wasn't supported. I had to create a new pseudo wireless interface but then I was able to use all the wifi tools independently. I think the tool would need an option to select your wifi card because I currently use prism0 instead of wlan0

**Comment by vvbv** [comment]
Try 
```
ifconfig prism0 down  
ip link set prism0 name wlan0  
ifconfig wlan0 up  
```

**Comment by BLX-S** [comment]
I had to jump through some more hoops to rename the network interfaces but it still didn't work.. same error:
`[2] Error: your wireless card  isn't supported  
Do you want exit? [Yes / No]:N
./fluxion.sh: line 777: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
 [1]	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	 	  100%	 
`
