### ISSUE TITLE
Does FLUXION 3 need one or two adapters?

### ISSUE THREAD

**Issue by EOS123** [FluxionNetwork/fluxion#182]
Does FLUXION 3 need one or two adapters?

**Comment by MPX4132** [comment]
Only one, but it supports two if you need that. It even supports external ethernet AP devices, but the attack becomes a bit more manual, so I only suggest you try that if you know what you're doing.

**Comment by coco5843** [comment]
I have a different question linked to this question, is there an option to add 2 adapters ? how ?

**Comment by MPX4132** [comment]
@coco5843 just select the first adapter when performing the scan. The first one is used for deauthetication. You can then select a second adapter when you go into the actual `Captive Portal` attack. The second adapter is used to host the access point.
