### ISSUE TITLE
Developer! Hello. Urgent problem! Cannot double hide the name of the SSID WiFi signal

### ISSUE THREAD

**Issue by zq16777** [FluxionNetwork/fluxion#184]
Hello, developer and for WIFI signal SSID hidden no way to create a SSID hidden twin brother AP signal names, only display x0x0x0x0x0x with WiFi signal is not the same name hiding, need to develop a new Fluxion tool!!!!

**Comment by MPX4132** [comment]
@zq16777 Please fill the template with your information. Run the diagnostics script:
```
cd fluxion
./scripts/diagnostics.sh interfaceHere
```
Change interfaceHere to your interface's identifier.

I think you're experiencing an issue related to bash and Chinese characters. I say this from past experience. From earlier experiments I ran, bash doesn't seem to like Chinese, it throws out errors. From what I remember, non-ASCII characters are illegal in ESSID names, so your target access point shouldn't even be using those types of characters in the name.
