### ISSUE TITLE
Fluxion  Super big problem ！！！！！！

### ISSUE THREAD

**Issue by zq16777** [FluxionNetwork/fluxion#187]
The specified path [*] captured shook Bao Cunfang's (for example: /dump-01.cap /...)
The absolute path that is stored after the handshake bag is captured:'/root/Desktop/cap'pip-01.cap
[*] Hash file does not exist!

[*] 指定捕获到的握手包存放的路径 (例如: /.../dump-01.cap)

捕获到握手包后存放的绝对路径: '/root/Desktop/cap' pip-01.cap
[*] Hash文件不存在!

**Comment by MPX4132** [comment]
@zq16777 I’ll try to clarify the steps a bit:

1. Run `Handshake Snooper` on the target. That will generate the hash file.

2. Run `Captive Portal` to try to get WPA key.

**Comment by fengchen-github** [comment]
要输入已经抓到的握手包
the captured handshake packet
