### ISSUE TITLE
Don't use environment variables

### ISSUE THREAD

**Issue by Geczy** [FluxionNetwork/fluxion#189]
## Feature

Instead, use arguments

Replace `EXPORT FLUXION_DEBUG=1` with `./fluxion.sh --debug` for example

**Comment by MPX4132** [comment]
Already working on that, just that I’m gonna have to refactor behavior and I haven’t had time.

**Comment by Geczy** [comment]
That's fine, that's why I made an issue

**Comment by deltaxflux** [comment]
I don't see any issues with environment variables.
