### ISSUE TITLE
Can't connect to fake ap

### ISSUE THREAD

**Issue by christiantokevin** [FluxionNetwork/fluxion#191]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
I can't connect my android phone to fake ap for testing purpose. But in the fluxion ap service xterm windows, there is showing that my phone's mac address are connected to the ap, but not in my phone, and in fluxion ap authenticator windows (clients still 0).

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*

#### What do you think the expected behaviour should be?
*What do you think should happen?*

### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by deltaxflux** [comment]
Do more information provided, closing.
