### ISSUE TITLE
Captive Portal attack hangs on AP start

### ISSUE THREAD

**Issue by G30ATHGR** [FluxionNetwork/fluxion#192]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behaviour?
*fluxion crashes*

####Debug  (export FLUXIONDebug=1;./fluxion.sh output)

rm: cannot remove '/tmp/fluxspace/mdk3_blacklist.lst': No such file or directory
attacks/Captive Portal/attack.sh: line 942: kill: (4240) - No such process
attacks/Captive Portal/attack.sh: line 948: kill: (4244) - No such process
rm: cannot remove '/tmp/fluxspace/clients.txt': No such file or directory
hostapd: no process found
lib/ap/hostapd.sh: line 23: kill: (4264) - No such process
[*] Starting Captive Portal access point service...

### Specs
wlan0 alphacard : AWUS036ACH
chipset			: RTL8812AU
OS 				: Kali 2017.2

[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
./diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.12.0-kali2-amd64 (devel@kali.org) (gcc version 6.4.0 20170906 (Debian 6.4.0-5) ) #1 SMP Debian 4.12.12-2kali1 (2017-09-13)

**Comment by MPX4132** [comment]
I’m almost 100% sure this is a driver issue, there’s a wiki article I wrote about this, and there’s a ton of other issues just like this one, checkout the closed issues. What are you looking for? You’re looking to see if you have the same driver those other people have, if you do, it’s a driver problem.
