### ISSUE TITLE
[Question] Do I need two wireless interafeces?

### ISSUE THREAD

**Issue by DarkSkull91** [FluxionNetwork/fluxion#193]
Hi guys! I've just successfully completed an Evil Twin attack with Fluxion after many attempts. I can do this attack using two wireless interfaces: one to select the victim network and the other to select "host" the accesspoint. Is it correct to use two wireless interfaces? If I use only one the captive portal hangs on. I use a AWUS036ACH alfa card.

Thanks in advance.

**Comment by MPX4132** [comment]
You do not, just select the same interface when prompted the second time. However, I think your Alfa adapter has an issue with drivers, from what I recall. You might want to check out the closed issues, you’ll probabaly find more answers there.

The only thing I’ll say is that fluxion utilizes virtual interfaces, which some drivers don’t handle properly.

**Comment by MPX4132** [comment]
If you have any more questions regarding this issue, please reply here. We could potentially reopen the issue if we find a reproducible bug afflicting all hardware.

**Comment by DarkSkull91** [comment]
Yes, only another question that can help other users that bought this wireless card. Could you suggest me the best wireless card to work with fluxion?

Thanks.

**Comment by MPX4132** [comment]
I test fluxion with the Alfa AWUS036NH, which uses the `ath9k_htc` driver. The one you have peobabaly has a driver issue, meaning it could work if you find a replacement driver. You should browse the closed issues, there’s a couple of people that have had your problem and have asked for other good wireless adapters. Check it out if you have a chance.
