### ISSUE TITLE
Channel Changes

### ISSUE THREAD

**Issue by wvthoog** [FluxionNetwork/fluxion#194]
Been using Fluxion alot the last couple of months, but i've noticed that on on a few (maybe newer) AP's the target AP changes channel. After it changes channel the deauth process on the original channel doesn't apply any more. (so the target AP user isn't interfered to communicate with the target AP)

First i thought it's because i use 30/33dBm USB adapters, and they maybe would be 'overpowering' the target AP so it changes channel (auto channel selection on target AP). But even when i lower the output to 20dBm the problem persists. 

So my question is, is this a common problem ? does Fluxion plan to integrate a periodic scan for channel changes ? (of the target AP)

**Comment by DarkSkull91** [comment]
@wvthoog could you tell me which wireless adapter you have?

**Comment by wvthoog** [comment]
Two Ralink RT3070 (directional and omni) and a Atheros AR9271L

**Comment by deltaxflux** [comment]
There is already a simular issue opened.
