### ISSUE TITLE
Unable to start captive portal

### ISSUE THREAD

**Issue by christiantokevin** [FluxionNetwork/fluxion#195]
### Do you want to request a *feature* or report a *bug*?
*bug*

### What is the current behaviour?
*fluxion crashes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
![screenshot from 2017-10-04 17-26-28](https://user-images.githubusercontent.com/27953008/31171321-6e0601a6-a929-11e7-803c-d8411f6f3bc7.png)

#### What do you think the expected behaviour should be?
*Unable to start captive portal when use my external wifi adapter, my adapter is tp-link tl-wn722n v1 (AR9271), and yes it supported monitor mode, mdk3 aireplay-ng and any other modules are working, but why when i'm trying to start captive portal, the application says that it's unable to start. But when i use my built in wifi adapter (actually it should be written as wlp3s0, but in this time it didn't showing up, need to restart), it works, captive portal started.*

### Specs
*./diagnostics.sh: line 3: lib/InterfaceUtils.sh: No such file or directory
[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.

[ BASH Info ]
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlxf8d1110d2aa3) Info ]
./diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown
Injection Test: DUMA 2.5.15 (shared library, NO_LEAKDETECTION)
Copyright (C) 2006 Michael Eddington <meddington@gmail.com>
Copyright (C) 2002-2008 Hayati Ayguen <h_ayguen@web.de>, Procitec GmbH
Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>

Injection is working!

[ XTerm Info ]
Version: XTerm(322)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  https://www.aircrack-ng.org

[ System Info ]
Linux version 4.4.0-96-generic (buildd@lgw01-10) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
*

**Comment by usama7628674** [comment]
Well if internal adapter is working then I guess external adapter has some driver problem.

**Comment by MPX4132** [comment]
I agree with @usama7628674, it’s likely a driver issue with your wireless hardware.

**Comment by haloohooloo** [comment]
I have the same problem and my external adapter is Alfa AWUS036ACH / 88XXau Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter.

**Comment by salah2bebop** [comment]
@haloohooloo did you find a solution? i have the same adapter.

**Comment by cjb900** [comment]
@salah2bebop you do realize this was closed and is from like 3 years ago. If you did any type of research on the AWUS036ACH you would see that the chipset it has does not support VIF. Meaning that it will not work with fluxion by its self. You would have to have a second adapter to use along with this one to properly use fluxion.

**Comment by salah2bebop** [comment]
@cjb900  thanks for your reply, can you tell me what kind of adapter should
I have?

**Comment by cjb900** [comment]
Well if you want to only use one adapter then you have to have one that supports packet injection, monitor mode, and AP mode. it also has to support VIF(virtual Interfaces) if you don't mind having 2 adapters then you can probably keep that one and just get another one so one adapter is deauthing and the other one is creating the fake AP. Here is a list of known good adapters and chipsets. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by salah2bebop** [comment]
Thank you very much for tout reply.

**Comment by Aoki07** [comment]
Hello , i have a problem in the second step in fluxion for to create a "captive portal " this message appears when I select my wifi card :
] Select an interface for the access point.

[1] eth0 [+] Intel Corporation 8254EM Gigabite Ethernet Controller(rev
[2] wlan0 [+] TP-Link TL-WN722N v2
[3] Repeat
[4] Back

[fluxion2@kali]-[~] 2

[*] Unable to start captive portal interface, returning!

can someone Help please?

**Comment by DHANIFPIBZ** [comment]
Hello , i have a problem in the second step in fluxion for to create a "captive portal " this message appears when I select my wifi card :
] Select an interface for the access point.

[1] eth0 [+] Intel Corporation 8254EM Gigabite Ethernet Controller(rev
[2] wlan0 [+] TP-Link TL-WN722N v2
[3] Repeat
[4] Back

[fluxion2@kali]-[~] 2

[*] Unable to start captive portal interface, returning!

can someone Help please?

**Comment by cjb900** [comment]
you do realize that you are posting a comments on an issue that has been closed for almost 3 years. Also may be if you did any research you would know that your issue is the card you have is not supported for wifi having which is why you are having issues. there is no one that can help you other than tell you to get a new card

**Comment by oussamajad** [comment]
download the driver
then open up include/autoconf.h
look for #define CONFIG_CONCURRENT_MODE and uncomment it by removing the double forward slash
or add it
#define CONFIG_CONCURRENT_MODE
after that, build the driver then install it
make && make install

**Comment by zebdev786** [comment]
> Hello , i have a problem in the second step in fluxion for to create a "captive portal " this message appears when I select my wifi card :
> ] Select an interface for the access point.
> 
> [1] eth0 [+] Intel Corporation 8254EM Gigabite Ethernet Controller(rev
> [2] wlan0 [+] TP-Link TL-WN722N v2
> [3] Repeat
> [4] Back
> 
> [fluxion2@kali]-[~] 2
> 
> [*] Unable to start captive portal interface, returning!
> 
> can someone Help please?


Anyone with the solution is most welcomed...please help me out(I'm using TP link v2/v3 adapter)

**Comment by cjb900** [comment]
@zebdev786 if your adapter is the TP-Link TL-WN722N v2/3 there is no solution. The chipset in that adapter does not support the proper modes to work in fluxion by its self. You would need to either get an adapter that supports monitor mode, AP mode and VIF or a second one to us with that adapter in fluxion

**Comment by zebdev786** [comment]
@cjb900  It supports monitor mode, packet injection and I can also create fake AP using it, then why it won't work?

**Comment by cjb900** [comment]
Because that adapter does not support VIF which is needed to be able to both deauth and create the fake AP at the same time. To my knowledge there is no way to give that adapter support for VIF. There have been many that i've seen try and fail to get that adapter to work by its self. You are just going to have to either replace that adapter with a know supported one or get a second one to use with it in fluxion.

**Comment by yassmiss** [comment]
Svp…  j'ai acheté cet adaptateur d'amazon 
https://www.amazon.fr/dp/B07YDHTHH3/ref=cm_sw_r_apan_glt_i_NRS5WB3CCX9G97NNA94E?_encoding=UTF8&psc=1
Mais malheureusement il a le meme probleme..!

Svp..  Qqn pouvait me donner un lien d'amazon d'un autre fonctionnant à 100% par essai…pour que je l'achete… !
Meme si affilié ..!

**Comment by yassmiss** [comment]
Sorry… !
Someone can give me a like of un good wireless low price in amazon witch work 100% with injections ..!
Thanks,

**Comment by cjb900** [comment]
being from the United States I can't say what would be cheap and available to you online. But here is a list of known adapters and chipsets that will work with fluxion with little to no issues. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH (2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by yassmiss** [comment]
All those you have mentioned are expensive. !!

Please .. Can you confirm to me that this one will work without any problem :
[Atheros AR9271 802.11n 150Mbps Wireless USB WiFi Adapter Fast For Linux F8H2](https://www.ebay.fr/itm/234171744338?_trkparms=ispr%3D1&hash=item3685b94052:g:I6MAAOSwGPZhMwy1&amdata=enc%3AAQAGAAACoPYe5NmHp%252B2JMhMi7yxGiTJkPrKr5t53CooMSQt2orsSRAQR8FABHjfpFoyRlXhWmSUxpBfCOvPGFFlJwzo1AGfYnPWn5qy45CN%252BKMXgSUtGjAC4N9UbAMuUFd2rmmBzTDSkMlTcWLnYAN60zVMfw%252Ffhj%252FiWiw4R4QznWuRuBlK0ntvS8cbR4PpqrhGKZO%252B%252FrlzWj%252FdiJ5T2jYT12I%252BTk7haD5lVesWiwItENx2f5R16lU0cykhRVhhlNLuvgf3SDbMq5AwfT81%252FFhuCb806O%252BluHg% 252BebjD8Up4smBrpbPsOa44fqEnvRG8nro4VKqwq5OsQs6oZXLrAUuegCqNmVhsoodHicvsbz68A2K5jwOYCaucTTS% 252BDlZbQr0JqtgTW5VGMmon6799qDF5eQJrc2UW 252B1ziLA6BMfidA0hiTF3AcMOFPAE6dH0KtqAPcy2AV5AsQLo1yEtOtZTSJkSPkrSsGv1ySRAdiM4PMV7Q8SoO9zBN%%% 252B3LDFeLLzqo2QT5mTC6ByPJBhZV 252F0UWAEFvsWXHnX% 252FoNTExNmXceYAVNHW33HB4Tat5PsBV3f 252FJVSyGIQbUsOHw8CxaxFikjYNBzhJySnh%%% 252BeXyU11b6zNFXiNMJaxJ7yrSaaJ0xrD9dw0rlSiQbNDeVYfDr3oCkUsOhl7Rlqypf 252FG7F6i85AVa79N77ZIIdlxGuPMlmBRVBoR8MU 252FwmN9p1GdOsQFn2iCIp%%% 252FmF3dhVlXtpLIn7tarUbx 252FYUbhQiC 252FokOKsO%%% 252FdTm 252BGWZxsgAV5Hzl1xSYeoSIT 5o3j% 252FJMYZTSoF7wZnk6mC7RnXE9rRD9d0dqU% 252BUQ4suZsyMBTMECr83cTcOif6bvg0ScGK% 252BR1kr4EiXuCnhDhDnY0Nq3Q2CNHDhDhDnY0Nq3Q2DjoT7Z3HDnY0Nq3% 3LizTj7Z3% 25Kcl3X45% 7W3Z533 %Kcl3X45% 7W3C3Z3H5Xcl3X45% 3W3Z3H533 %Kcl3X453% 7W3Z533% 3Wcl3ZsyMBTMECr83)

Please !

**Comment by cjb900** [comment]
Do you not know how to read🤨The link you shared has the Atheros AR9271 chipset in the description which is one of the chipsets in the list i shared. So as long as that adapter actually comes with that chipset it will work.

**Comment by yassmiss** [comment]
Yes.... I read ... I just wanted to be sure .. !!

thanks,

**Comment by Medullitus** [comment]
> Well if you want to only use one adapter then you have to have one that supports packet injection, monitor mode, and AP mode. it also has to support VIF(virtual Interfaces) if you don't mind having 2 adapters then you can probably keep that one and just get another one so one adapter is deauthing and the other one is creating the fake AP. Here is a list of known good adapters and chipsets.
> 
> Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB) Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB) Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB) Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB) Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB) Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB) Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

BUT WHY IT'S SAID IT SUPPORTS MONITOR MODE FUCK VIF FUCKKKKKKKKKKKKKKKKKKKKKKKK

**Comment by afastars** [comment]
Hi all,

For those having problem please check you Wireless adapter as follow:

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Thanks

**Comment by hasnain295** [comment]
Hello , i have a problem in the second step in fluxion for to create a "captive portal " this message appears when I select my wifi card :
] Select an interface for the access point.

[1] eth0 [+] Intel Corporation 8254EM Gigabite Ethernet Controller(rev
[2] wlan0 [+] TP-Link TL-WN722N v2
[3] Repeat
[4] Back

[fluxion2@kali]-[~] 2

[*] Unable to start captive portal interface, returning!

can someone Help please?

**Comment by HackerX001** [comment]
unable to start captive portal interface returning fluxion

**Comment by cjb900** [comment]
@HackerX001 why are you posting a comment on something that is like ~6 years old and closed? If you are having issues please join our discord or open a new issue and fill out the issue template.
