### ISSUE TITLE
how install?

### ISSUE THREAD

**Issue by hanbing88** [FluxionNetwork/fluxion#196]
how install in kalilinux?

**Comment by usama7628674** [comment]
`git clone --recursive https://github.com/FluxionNetwork/fluxion.git # Download the latest revision`
`cd fluxion # Switch to tool's directory`
`./fluxion.sh # Run fluxion (missing dependencies will be auto-installed)`

**Comment by saintofinternet** [comment]
somehow the ./fluxion is not auto installing the dependcies in Kali running on RPI... it does show the list of dependencies but does not install them.

**Comment by rad4day** [comment]
Thank you for digging up this ancient issue @saintofinternet

**Comment by deltaxflux** [comment]
On arch it is working. I will try kali and see if the problem exists there.
