### ISSUE TITLE
Unable to connect to fake AP and fluxion dns window didn't showing up

### ISSUE THREAD

**Issue by christiantokevin** [FluxionNetwork/fluxion#197]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion crashes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
![screenshot from 2017-10-05 11-32-33](https://user-images.githubusercontent.com/27953008/31211294-18b464ba-a9c2-11e7-9cfe-4ab8d6e676e9.png)

#### What do you think the expected behaviour should be?
*No matter what interface used (built in or usb), clients can't connect to fake ap, even on fluxion ap service window says that a client is connected, but in my phone says nothing, it can't connect to fluxion fake ap. And also, sometimes the fluxion dns service window didn't showing up. How can i fix this? Need help please, sorry for my bad english.*

### Specs
*
[ FLUXION Info ]
FLUXION V3.4

[ BASH Info ]
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
Device: phy1
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: DUMA 2.5.15 (shared library, NO_LEAKDETECTION)
Copyright (C) 2006 Michael Eddington <meddington@gmail.com>
Copyright (C) 2002-2008 Hayati Ayguen <h_ayguen@web.de>, Procitec GmbH
Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>

Injection is working!

[ XTerm Info ]
Version: XTerm(322)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  https://www.aircrack-ng.org

[ System Info ]
Linux version 4.4.0-96-generic (buildd@lgw01-10) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
*

**Comment by usama7628674** [comment]
Would you able to connect if dns window shows up?

**Comment by MPX4132** [comment]
Yeah, the python DNS failed to start. This could be caused by a lot of things. Make sure your python interpreter is working fine. Run the following and post the output:
```
which python
```

Do you know if fluxion installed anything on your system? I’ve never seen an issue with the DNS script, so this is a first.

**Comment by bytecod3r** [comment]
I have the same issue, could you tell me how did you solve it?

**Comment by strasharo** [comment]
Maybe something is listening on 53? try "netstat -npl | grep :53"

**Comment by bytecod3r** [comment]
I fixed it by changing the python2 in the source that executes the fakedns from dummy path.

**Comment by Firsty46** [comment]
> I fixed it by removing the condition in the source before executing the fakedns from dummy path.
Please help me how to fix it?
