### ISSUE TITLE
Fluxion Fails To verify WPA Hash during handshake snooper attack session

### ISSUE THREAD

**Issue by 5p3c7r3** [FluxionNetwork/fluxion#198]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion Fails To verify WPA Hash (Specifically Not WPA2 There's nothing Wrong with that)

#### If the current behaviour is a bug, please provide the steps to reproduce it.
1. Create An AP with WPA-PSK Security (Make sure to use WPA not WPA2 or WPA + Wpa2) and set WPA Encryption to TKIP
2. run fluxion
3. Select the Hanshake Snopper Attack
4. Select the aireplay-ng attack
5.use Pyrit verification
6. even though It seems to run without a problem when the WPA Hanshake is captured 
fluxion doesn't recognizes it
and continues instead of stopping

![capture](https://user-images.githubusercontent.com/20989997/31279851-409fea96-aaf6-11e7-980a-386e10adcd7a.PNG)

#### What do you think the expected behaviour should be?
All 3 spawned terminals should save the capture file then terminate

### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

```
root@HackNetOS:~/fluxion# airmon-ng check kill


root@HackNetOS:~/fluxion# airmon-ng start wlan0


PHY	Interface	Driver		Chipset

phy1	wlan0		rt2800usb	Ralink Technology, Corp. RT2870/RT3070

		(mac80211 monitor mode already enabled for [phy1]wlan0 on [phy1]10)
root@HackNetOS:~/fluxion# ./diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.4


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy1
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Injection Test: Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.12.0-kali2-amd64 (devel@kali.org) (gcc version 6.4.0 20170906 (Debian 6.4.0-5) ) #1 SMP Debian 4.12.12-2kali1 (2017-09-13)



```

**Comment by deltaxflux** [comment]
Check #165 out.

**Comment by 5p3c7r3** [comment]
```
root@HackNetOS:~# pip2 freeze | grep scapy
Warning: cannot find svn location for chirp===daily-20170714
scapy==2.3.3
root@HackNetOS:~# 
```

**Comment by 5p3c7r3** [comment]
Here is the Debug Output

`
[fluxion@HackNetOS]-[~] Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 16 header bytes, only got 12
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 10 captured bytes, only got 0
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
1/44: New Station 6c:88:14:bd:71:98 (AP 88:ce:fa:89:e2:5e)
2/44: Challenge AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: Response AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, bad, spread 1
4/46: Confirmation AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
4/46: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, good, spread 1
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 16 header bytes, only got 13
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
1/44: New Station 6c:88:14:bd:71:98 (AP 88:ce:fa:89:e2:5e)
2/44: Challenge AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: Response AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, bad, spread 1
4/46: Confirmation AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
4/46: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, good, spread 1
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 94 captured bytes, only got 71
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
1/44: New Station 6c:88:14:bd:71:98 (AP 88:ce:fa:89:e2:5e)
2/44: Challenge AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: Response AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, bad, spread 1
4/46: Confirmation AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
4/46: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, good, spread 1
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 420 captured bytes, only got 0
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
1/44: New Station 6c:88:14:bd:71:98 (AP 88:ce:fa:89:e2:5e)
2/44: Challenge AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: Response AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, bad, spread 1
4/46: Confirmation AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
4/46: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, good, spread 1
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 16 header bytes, only got 5
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
1/44: New Station 6c:88:14:bd:71:98 (AP 88:ce:fa:89:e2:5e)
2/44: Challenge AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: Response AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, bad, spread 1
4/46: Confirmation AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
4/46: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, good, spread 1

Capture-source was closed...

#1: AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
  #0: Station 6c:88:14:bd:71:98, 1 handshake(s)
    #1: HMAC_MD5_RC4, good, spread 1

New pcap-file '/tmp/fluxspace/capture/dump-01-clean.cap' written (4 out of 744 packets)
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
1/44: New Station 6c:88:14:bd:71:98 (AP 88:ce:fa:89:e2:5e)
2/44: Challenge AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: Response AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, bad, spread 1
4/46: Confirmation AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
4/46: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, good, spread 1
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 136 captured bytes, only got 57
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
1/44: New Station 6c:88:14:bd:71:98 (AP 88:ce:fa:89:e2:5e)
2/44: Challenge AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: Response AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, bad, spread 1
4/46: Confirmation AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
4/46: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, good, spread 1
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 16 header bytes, only got 12
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing packets from '/tmp/fluxspace/capture/dump-01.cap'...
1/1: New AccessPoint 88:ce:fa:89:e2:5e ('TestWPA')
1/44: New Station 6c:88:14:bd:71:98 (AP 88:ce:fa:89:e2:5e)
2/44: Challenge AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: Response AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
3/45: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, bad, spread 1
4/46: Confirmation AP 88:ce:fa:89:e2:5e <-> STA 6c:88:14:bd:71:98
4/46: New Handshake AP 88:ce:fa:89:e2:5e: HMAC_MD5_RC4, good, spread 1
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 600, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 10 captured bytes, only got 6
Verifier pyrit, path /tmp/fluxspace/capture/dump-01-clean.cap, SSID TestWPA, MAC 88:CE:FA:89:E2:5E
Handshake for TestWPA (88:CE:FA:89:E2:5E) is missing!
^Cattacks/Handshake Snooper/attack.sh: line 75: kill: (6319) - No such process
attacks/Handshake Snooper/attack.sh: line 58: kill: (6320) - No such process
xterm: no process found
root@HackNetOS:~/fluxion# ^C
root@HackNetOS:~/fluxion# 
`

**Comment by deltaxflux** [comment]
Looks like your pyrit is broken use aircrack instead

**Comment by douirc** [comment]
I have the same problem:
# pip2 freeze | grep scrapy
Warning: cannot find svn location for chirp===daily-20170714
scapy===unknown.version

tried:
# pip2 install scapy
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages

when running handshake snooper the cap files are created:
root@kali:/tmp/fluxspace/capture# ls
dump-01.cap        dump-01.csv         dump-01.kismet.netxml
dump-01-clean.cap  dump-01.kismet.csv

but when I close to continue with attack the files are deleted.

**Comment by deltaxflux** [comment]
Same response, don't mess up your system. This bug was already solved by kali devs and it is not related to fluxion. Use aircrack to verify the handshake, hope it will work.

**Comment by MPX4132** [comment]
I've experienced this issue on a slower system (Raspberry Pi B+). Might be a race condition between updating the file and reading it.

**Comment by M1z23R** [comment]
Ok, so i used airodump-ng separate from fluxion, got two handshakes (both marked as *good*) and both striped and non-striped .cap files work with fluxion, I am guessing it has to do with parsing of pyrit's output. I tried looking at the scripts (fluxion.sh and HashUtils.sh) but i can't figure out the answer. Please help :)

**Comment by MPX4132** [comment]
@M1z23R Have you tried the latest version? It’s should work for all systems now. If you haven’t already tried the latest version, clone it and try running the `Handshake Snooper` attack with pyrit as the verifier, choose synchronous when you’re asked about the synchronicity, and use the mdk3 deauthenticator.

**Comment by flxkalu** [comment]
@delatflux do u mean to use aircrack-ng asin the normal terminal window?

If thats the case how do i continue with fluxion after obtaining the handshake through aircrack-ng

**Comment by MPX4132** [comment]
The problem here might’ve been related to not taking TKIP hashes, that’s been resolved with Fluxion 4.
