### ISSUE TITLE
Fake AP not creating

### ISSUE THREAD

**Issue by JokerizVirgin** [FluxionNetwork/fluxion#199]
So I was trying to creat a fake ap by Fluxion by tutorial from YT but the fake ap window is not showing up... So anybody know what to do?

......TIA......

**Comment by deltaxflux** [comment]
First fill out the issue template

**Comment by MPX4132** [comment]
Huh, I hadn't thought of YouTube. I just saw some videos, and just about every single one is outdated, so it's a bad source for instructions.
