### ISSUE TITLE
Adding new french sites

### ISSUE THREAD

**Issue by JuanReagan** [FluxionNetwork/fluxion#200]
### Do you want to request a *feature* or report a *bug*?
*Feature*

### What is the current behaviour?
*There aren't any french sites*

### If this is a feature request, what is the motivation or use case for the added feature?
I found 4 hostapd french webpages, but I don't have enough javascript/html knowledge to make them compatible with fluxion. Please help, Fluxion is so well designed otherwise!

[RouterPages.zip](https://github.com/FluxionNetwork/fluxion/files/1363558/RouterPages.zip)

**Comment by deltaxflux** [comment]
Done
