### ISSUE TITLE
handshake corrputed

### ISSUE THREAD

**Issue by RRibbon** [FluxionNetwork/fluxion#201]
help me please..

when i check the handshake after i got one,im always get "handshake corrupted" massage..

i want to give screenshoots,but i cant send it now,its always error,
i will sent the screenshoots or anything help anyway after i got a reply..

thanyou..

**Comment by 5p3c7r3** [comment]
Did you capture then handshake or did fluxion do it ?

**Comment by RRibbon** [comment]
![screenshot from 2017-10-07 21-40-41](https://user-images.githubusercontent.com/32472786/31313257-e24c0b60-ac07-11e7-82c6-f5c2f4cb738f.png)

I think the fluxion did it,cause im using fluxion.. 
Just see the ss

**Comment by usama7628674** [comment]
From the image above I can see clearly you're using fluxion 2 which is very old.Clone this repo and try again.

**Comment by deltaxflux** [comment]
Please update fluxion

**Comment by itz-8infinite** [comment]
I have been having the same issue too but in my case i started capturing handshake using 'wifite' and then when it asks if i already have captured the handshake, so i just give the directory of my .cap file. Hope that works coz i even tried updating the fluxion but it didnt helped

**Comment by deltaxflux** [comment]
Yeah fluxion accept only "good" handshakes. You can prove this with aircrack-ng or pyrit. The main problem is that aircrack-ng detect sometimes bad handshakes as good and pyrit good handshakes as bad.
