### ISSUE TITLE
Stuck at Starting Captive Portal access point service

### ISSUE THREAD

**Issue by A7mardRS** [FluxionNetwork/fluxion#202]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
* stuck at " Starting Captive Portal access point service*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*cd fluxion*
*sudo ./fluxion.sh*
*4 for english*
*2 for my external alfa AWUS036H rtl8187*
*1 for all channels *
*after chosen the target and got the handshack i press on select another attack and tried to captive portal and choose hostapd and after choosing the ssl page and try to run the fake AP it stuck at 
Starting Captive Portal access point service*

#### What do you think the expected behaviour should be?
*it should start the fake because it worked perfect with my internal chipset "AR928X" but it disnt work on rtl8187*

### Specs
*internal chipset: AR982x working fine*
*external chipset: alfa awus036h rtl8187 not working*
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by usama7628674** [comment]
Your adapter is old and is not compatible with hostapd.You need to upgrade your adapter.

**Comment by A7mardRS** [comment]
Ok .
Can you suggest a great long rang adapter compatible with all kali and can live more than as much as longer life

**Comment by 5p3c7r3** [comment]
Maybe a AWUS036N

**Comment by 5p3c7r3** [comment]
AWUS036NHA ?

**Comment by usama7628674** [comment]
I personally use awus036nha and it's compatible with all scripts.I recommend you to get one.
