### ISSUE TITLE
Connection Refused 

### ISSUE THREAD

**Issue by usherfiles** [FluxionNetwork/fluxion#203]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behaviour?
Every time I launch the FakeAP, First, my smarthphone says "no internet" instead of "you need to login" , second, when I go to google.com, any browser says CONNECTION REFUSED, like This:  [https://i.stack.imgur.com/x0dQr.png](url)  even if I try different pages, every time I get the same error...

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Just start the Captive Portal with any network and go to google.com with your cellphone.

#### What do you think the expected behaviour should be?
Show me the captive portal. ALSO don't tell me that "there's no internet, please connect to another network", instead of that say "You need to login".

Is there any commands I can follow to update every thing that fluxion needs to work properly? because I'm using wifislax 4.12 (the latest version) and maybe it has some things missing or outdated... Can you provide a list of commands to update the necessary programs to run fluxion without problems? .

### Specs
NOTE: the languaje is spanish:
No existe el fichero o directorio : that file or directory doesn't exist.
no se encontrÃ³ la orden: order don't found 

wifislax scripts # ./diagnostics.sh wlan0
./diagnostics.sh: lÃ­nea 3: lib/InterfaceUtils.sh: No existe el fichero o el directorio
[ FLUXION Info ]
grep: fluxion.sh: No existe el fichero o el directorio
FLUXION V.

[ BASH Info ]
GNU bash, versiÃ³n 4.3.46(1)-release (i586-slackware-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
Licencia GPLv3+: GPL de GNU versiÃ³n 3 o posterior <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /usr/bin/bash

[ Interface (wlan0) Info ]
./diagnostics.sh: lÃ­nea 20: interface_physical: no se encontrÃ³ la orden
Device: Unknown
./diagnostics.sh: lÃ­nea 25: interface_driver: no se encontrÃ³ la orden
Driver: Unsupported
./diagnostics.sh: lÃ­nea 30: interface_chipset: no se encontrÃ³ la orden
Chipset: Unknown
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: X.Org 7.7.0(325)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.5
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 r2858 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.4.16-smp-wifislax (root@wifislax) (gcc version 5.3.0 (GCC) ) #1 PREEMPT Sat Jul 30 07:45:32 CEST 2016

**Comment by usama7628674** [comment]
Try to browse non-https sites and see if it works or not.

**Comment by usama7628674** [comment]
The certificate that fluxion creates is not a valid signed CA certificate that's why you're getting this error.

**Comment by usherfiles** [comment]
@usama7628674 even If I type the default gateway, it does the same thing...

**Comment by usama7628674** [comment]
First clean your android history and start captive portal attack.browse and http site and captive portal will pop up.

**Comment by usama7628674** [comment]
also tell me the adapter you're using to create rogue ap.

**Comment by usherfiles** [comment]
@usama7628674  I've tried to delete the saved network on my android, then connect again, clear my history / cookies / etc, and even tried with samsung browser... and it does the same.
The adapter I'm using is Nisuta CPE310

**Comment by usama7628674** [comment]
Did you browse any http site. 
try this site 
http://www.czone.com.pk

**Comment by usherfiles** [comment]
@usama7628674  Tried everything you said... no luck :( https://i.imgur.com/mH822XA.png

**Comment by usama7628674** [comment]
@usherfiles If you're using laptop then try with internal adapter.

**Comment by usherfiles** [comment]
@usama7628674 I'm using a desktop computer and wifislax from the USB (booteable from the USB)

**Comment by usama7628674** [comment]
make sure you're using DHCP and not static ip.

**Comment by usama7628674** [comment]
Did you get DHCP lease on DHCP fluxion window?

**Comment by usherfiles** [comment]
I leave all how it comes to use, didn't change any ip for my cellphone neither the PC... 
Just turned on wifislax, installed fluxion how the readme.md says and execute it... 
if you're saying that if fluxion gives me an IP to my cellphone, yes, it does... the default gateway is 192.168.254.1 and the first device that connects to the fakeap get the  192.168.254.100

**Comment by usama7628674** [comment]
I'll check on my pc and update here.

**Comment by usama7628674** [comment]
Here's the screenshot from my android
![screenshot_2017-10-10-11-40-59](https://user-images.githubusercontent.com/29252277/31372979-ad0218cc-adb1-11e7-804f-5ce2fc98ce59.png)


and the fluxion windows
![screenshot from 2017-10-10 11-41-45](https://user-images.githubusercontent.com/29252277/31372990-ba5da374-adb1-11e7-8abc-7c8bfc8826bc.png)


I'm using kali linux 2017.2 and awus036nha adapter.

**Comment by usherfiles** [comment]
Maybe my linux has something needed for fluxion that is outdated... or I don't know, I have no clue why this only happens to me... does your android say "No internet, connect to another network" on the notification bar or "log in into network"?

**Comment by usama7628674** [comment]
It says "Cannot auto-connect.connect manually".

**Comment by usherfiles** [comment]
Maybe I should try a Live USB version of Kali Linux 2017?

**Comment by usama7628674** [comment]
Are you using latest version of fluxion?If not,then try to clone this repo and give it a shot.

**Comment by usama7628674** [comment]
Yes,try with kali

**Comment by usherfiles** [comment]
@usama7628674 Yes, I always download the latest version of fluxion, because Live USBs don't save changes made after you turn off the PC.

**Comment by azamet90** [comment]
@usama7628674 pls release another update for this man :-/ the developpers  made the tool garbage again

**Comment by cjb900** [comment]
@azamet90 you do realize that your 2 comments one the OP is not even using a dedicated hacking OS which is probably why they are having issues. And this thread is over 3 years old. Also I just tested the latest updated pushed to fluxion and had no issues connection to the fake AP it created. So your issues could be related to something else
