### ISSUE TITLE
Hash file not exist!

### ISSUE THREAD

**Issue by ww18877317962** [FluxionNetwork/fluxion#208]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion crashes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*

#### What do you think the expected behaviour should be?
*What do you think should happen?*

### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by deltaxflux** [comment]
Run the handshake snooper first.
