### ISSUE TITLE
 When you enter the absolute path stored after grabbing the handshake package, the hash file does not exist!

### ISSUE THREAD

**Issue by ww18877317962** [FluxionNetwork/fluxion#209]
When you enter the absolute path stored after grabbing the handshake package, the hash file does not exist!
What should I do, run "Handshake Snooper" in the "attack.sh", no response
For the first time, I was a novice，Thank you！！！！

**Comment by MPX4132** [comment]
**Do no run `attack.sh`**
That script should only executed by `fluxion.sh`.

All you need to execute is `fluxion.sh`.
Once fluxion gives you the option to select an attack, choose the `Handshake Snooper` attack.

The `Handshake Snooper` attack will attempt to obtain the hash file. Once the hash file has been caught, fluxion will not ask you for the path anymore. It will automatically load it for you.

After the attack succeeds, you need to select the other attack, the `Captive Portal` attack.

It’s important to understand you should only execute `fluxion.sh`, not any other script!

**Comment by ww18877317962** [comment]
Thank you very much,I just got it wrong，now it is Ok!

**Comment by MPX4132** [comment]
Alright, awesome. Come back here if you have any more issues.
