### ISSUE TITLE
Getting 'Handshake Corrupted'

### ISSUE THREAD

**Issue by renancompuece** [FluxionNetwork/fluxion#211]
When i get this i try press 1 to reload handshake to check  many times, but doesn work ...

**Comment by 5p3c7r3** [comment]
Did you capture the handshake yourself or did fluxion did it

**Comment by renancompuece** [comment]
fluxion did it

**Comment by deltaxflux** [comment]
There a ton of ways why the handshake is currupted, please make sure it is not an issue causing by fluxion.

**Comment by renancompuece** [comment]
it occours in some networks. in others, not. but when i try this network in wifiphisher, for example, all work well and clients are deauthenticaded

**Comment by deltaxflux** [comment]
Ask the mdk3 or aireplay devs
