### ISSUE TITLE
Stucks on - Starting captive portal access ..........

### ISSUE THREAD

**Issue by akki9711** [FluxionNetwork/fluxion#213]
I want to report a bug.
gets stuck and does not respond on  "Starting captive portal access .........."
using RALINK usb adapter, works fine with earlier versions of fluxion.
![screenshot from 2017-10-19 16-02-10](https://user-images.githubusercontent.com/29523549/31766952-f80d0ef8-b4e6-11e7-9aa2-b20ce05d0c70.png)

**Comment by deltaxflux** [comment]
Yeah read the response there.

**Comment by akki9711** [comment]
That solution wasn't able to fix the issue. Earlier my Ralink adapter worked with fluxion but not with this fluxion release.

**Comment by deltaxflux** [comment]
Which wireless card do you use ?

**Comment by strasharo** [comment]
Learn to fill in the template.
