### ISSUE TITLE
Original (attacked) AP needs re-authentication after successful attack

### ISSUE THREAD

**Issue by ssrmpc** [FluxionNetwork/fluxion#215]
### Do you want to request a *feature* or report a *bug*?
*feature*

### What is the current behaviour?
*attacked AP requires re-authentication from the client device after captive portal goes down*

#### If the current behavior is a bug, please provide the steps to reproduce it.
*After successfully received the wifi password and we close fluxion,  the client device that was originally connected to the attacked AP requires re-authentication from the user*
Since the user just entered the password in the captive portal, this behavior indicates a network attack, or at least that there is something strange.

#### What do you think the expected behaviour should be?
*The client device should get back to his WPA2 encrypted AP without triggering a user action*

### If this is a feature request, what is the motivation or use case for the added feature?
The motivation is to hide the attack and to trigger the least amount of user actions.

### Specs
The issue occurs on the user side.... e.g. the iPhone that was connected to the attacked AP

### Speculation

The captive portal created is using the same Name and Channel... but a different MAC-Address. I could imagine that this is causing the re-authentication behavior on the client side.

What happens if the captive Portal uses the same Name and MAC-Address but another Channel?
This is how my FritzBox is doing it. On the Client device I just see one SSID... but one network is 2.4GHz and the other one is using 5GHz.

**Comment by strasharo** [comment]
If both APs have the same MAC the jamming would be pointless, since it will deauth from both.

**Comment by ssrmpc** [comment]
Well just as last word to this....

if you use another channel and the same SSID of the AP.... the devices will automatically change to the stronger AP. In other words there is no jamming needed.

think about it

**Comment by strasharo** [comment]
And you expect to have a single adapter on two channels simultaneously?
