### ISSUE TITLE
Win10 Ubuntu

### ISSUE THREAD

**Issue by aurora0129** [FluxionNetwork/fluxion#216]
*Bug*
After I had chosen the language, the program only showed me two options:[*}select a wireless interface; [1]repeat. But there was no interfaces I could select. So I chose the "repeat", and I could see some error massage flash, which said "InterfaceUtils.sh: Line 190, too many arguments"

*Paste the output of `./script/diagnostics.sh [interface]`*
#!/bin/bash

source lib/InterfaceUtils.sh

if [ ! "$1" ]
then echo "Usage ./scripts/diagnostics <wireless_interface>"; exit 1
fi

echo "[ FLUXION Info ]"
declare -r FLUXIONInfo=($(grep -oE "FLUXION(Version|Revision)=[0-9]+" fluxion.sh))
echo "FLUXION V${FLUXIONInfo[0]/*=/}.${FLUXIONInfo[1]/*=/}"
echo -ne "\n\n"

echo "[ BASH Info ]"
bash --version
echo "Path: `ls -L $(which bash)`"
echo -ne "\n\n"

echo "[ Interface ($1) Info ]"
if interface_physical "$1"
then echo "Device: $InterfacePhysical"
else echo "Device: Unknown"
fi

if interface_driver "$1"
then echo "Driver: $InterfaceDriver"
else echo "Driver: Unsupported"
fi

if interface_chipset "$1"
then echo "Chipset: $InterfaceChipset"
else echo "Chipset: Unknown"
fi

echo -n "Injection Test: "
aireplay-ng --test "$1" | grep -oE "Injection is working!|No Answer..." || echo "failed"
echo -ne "\n\n"

echo "[ XTerm Info ]"
echo "Version: `xterm -version`"
echo "Path: `ls -L $(which xterm)`"
echo -n "Test: "
if xterm -hold -fg "#FFFFFF" -bg "#000000" -title "XServer/XTerm Test" -e "echo \"XServer/XT
erm test: close window to continue...\"" &> /dev/null
        then echo "XServer/XTerm success!"
        else echo "XServer/XTerm failure!"
fi
echo -ne "\n\n"

echo "[ HostAPD Info ]"
hostapd -v
echo "Path: `ls -L $(which hostapd)`"
echo -ne "\n\n"

echo "[ Aircrack-ng Info ]"
aircrack-ng -H | head -n 4
echo -ne "\n\n"

echo "[ System Info ]"
if [ -r "/proc/version" ]
then cat /proc/version
else uname -r
fi

**Comment by deltaxflux** [comment]
Use a prober os

**Comment by aurora0129** [comment]
I'm using Microsoft's version of Ubuntu. That is a linux subsystem on win10 anniversary version. All other linux applications work well and I've also installed the VcXsrv for GUI. Ifconfig works well; The only problem is it seems it cannot find the interfaces...
![capture](https://user-images.githubusercontent.com/32964811/31847226-0a3761fe-b64b-11e7-902f-16ea738d28c5.PNG)
