### ISSUE TITLE
About adding new french sites...

### ISSUE THREAD

**Issue by JuanReagan** [FluxionNetwork/fluxion#218]
### Do you want to request a *feature* or report a *bug*?
*feature*

### What is the current behaviour?
*French sites added are not working*

#### What do you think the expected behaviour should be?
*French sites working*

### If this is a feature request, what is the motivation or use case for the added feature?
Do you read what I asked in my last request ? The sites I shared were not compatible with fluxion...
Anyway, I took a deeper look into it, and made them compatible.

Please replace Free, Sfr, and all non-generic french sites (except Djaweb's one !) I submitted with these :

[SFR_French.zip](https://github.com/FluxionNetwork/fluxion/files/1405090/SFR_French.zip)
[Freebox_French.zip](https://github.com/FluxionNetwork/fluxion/files/1405092/Freebox_French.zip)
[Bbox_French.zip](https://github.com/FluxionNetwork/fluxion/files/1405094/Bbox_French.zip)
[Livebox_French.zip](https://github.com/FluxionNetwork/fluxion/files/1405095/Livebox_French.zip)

**Comment by deltaxflux** [comment]
But they worked for me ? I will take a look

**Comment by JuanReagan** [comment]
That's weird, the pages did load for me too but the passwords entered were not taken into account..
Thanks anyway for all your work

**Comment by deltaxflux** [comment]
It would be a pleasure if you make a pull request here: 
https://github.com/FluxionNetwork/sites

**Comment by deltaxflux** [comment]
Thanks for your constribution.
