### ISSUE TITLE
DHCP service is not running

### ISSUE THREAD

**Issue by afiuq** [FluxionNetwork/fluxion#219]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
cannot connect to fake AP. stuck with obtaining IP adress

#### If the current behaviour is a bug, please provide the steps to reproduce it.
![screenshot from 2017-10-25 21-38-56](https://user-images.githubusercontent.com/21167599/32001808-7827f61c-b9cd-11e7-82f9-c6bf90f61f2e.png)

#### What do you think the expected behaviour should be?
there should be a Fluxion DHCP windows there

### Specs
[ FLUXION Info ]
FLUXION V3.4

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlp4s0) Info ]
Device: phy0
Driver: ath9k
Chipset: Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: XTerm(324)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-16-generic (buildd@lcy01-02) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu2)) #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017

**Comment by deltaxflux** [comment]
I don't think your driver support monitor mode but not master mode. However you use ubuntu. Ubunutu is not supported by fluxion.
