### ISSUE TITLE
handshake problem after new update of fluxion tool

### ISSUE THREAD

**Issue by KaliLinuxB2A** [FluxionNetwork/fluxion#220]
In airodump-ng terminal ,it shows the handshake file was captured but the  De-authenticate and  UI for handshake terminal were not close automatically. then after I check for the handshake file in /root/fluxion/attacks/Handshake Snooper but there wasn't  any handshakes folder and  file. Please Fix It.
![screenshot from screencast_10-26-17_13 58 40 webm - 4](https://user-images.githubusercontent.com/32506305/32042204-4b1b79ba-ba26-11e7-9cae-243fc0a88ff1.png)

**Comment by deltaxflux** [comment]
Read the other issues.
