### ISSUE TITLE
The script failed to initialize an xterm test session

### ISSUE THREAD

**Issue by hunar1997** [FluxionNetwork/fluxion#221]
Hi .. fluxion worked perfectly but yesterday i upgraded from Ubuntu 17.04 to 17.10 and now it wont start and shows me this message:
`The script failed to initialize an xterm test session.`
I'm just a *user* i dont know what else to say :/

**Comment by deltaxflux** [comment]
`sudo apt-get install xdpyinfo`

**Comment by hunar1997** [comment]
when i type that it says `Unable to locate package xdpyinfo`   
when i run `xdpyinfo` it shows alot of outputs about the display   
what is wrong? :/

**Comment by Axairlem** [comment]
Same thing here, using Ubuntu 17. Can't install xdpyinfo although I tried to google the package, found 1 link providing a tar.gz file which doesn't seem to work at all when I install it. @hunar1997 : To answer your question, Kali Linux fixed everything in my case and it is the recommended distro for Fluxion. Hope this helped.
Kali Download: https://www.kali.org/downloads/
xdpyinfo file:  https://www.archlinux.org/packages/extra/x86_64/xorg-xdpyinfo/ (Didn't work in my case)

**Comment by deltaxflux** [comment]
Well, Use a prober OS and take a look how to install these packages. I recommend:
* Wifilax
* Kali
* Parrot
* Arch

**Comment by alvarosamudio** [comment]
tested in deepin 15.5 and works wonders :+1: :ok_hand:

**Comment by hunar1997** [comment]
I forgot about this question XD, i solved it by logging out and using (Ubuntu on Xorg) instead and now everything works :D

**Comment by Halpmewithdis** [comment]
i have the same problem

**Comment by joelstitch** [comment]
I am having the same issue running Fluzion on Kali. I am running Kali Nethunter on a Oneplus 7 Pro and accesing the display trough VNC using Kalis KeX Manager.

**Comment by mamilux** [comment]
> I am having the same issue running Fluzion on Kali. I am running Kali Nethunter on a Oneplus 7 Pro and accesing the display trough VNC using Kalis KeX Manager.

Just run service as root not kali. But anyway fluxion wont launch

**Comment by mamilux** [comment]
![IMG_20200331_005110](https://user-images.githubusercontent.com/6977384/78068883-2ccb3f80-73d4-11ea-8122-f7db3609ec68.jpg)
Stuck in launch screen. When i tap ctrl+c i can see closing screen

**Comment by joelstitch** [comment]
> > I am having the same issue running Fluzion on Kali. I am running Kali Nethunter on a Oneplus 7 Pro and accesing the display trough VNC using Kalis KeX Manager.
> 
> Just run service as root not kali. But anyway fluxion wont launch

I actually got it running with root. Thank for the help! I just had to close the session on Kex Manager and start a new one with the user root

**Comment by xpz3** [comment]
![Screenshot_20200401-063431](https://user-images.githubusercontent.com/46419195/78089193-3d83b180-73e4-11ea-9fae-206451a92841.jpg)
No such issue for me. Latest nethunter on oneplus 3 phone

**Comment by mamilux** [comment]
> ![Screenshot_20200401-063431](https://user-images.githubusercontent.com/46419195/78089193-3d83b180-73e4-11ea-9fae-206451a92841.jpg)
> No such issue for me. Latest nethunter on oneplus 3 phone
> I just installed the dependencies

Weird. What I'm missing i don't know. Still same. Maybe because of the Marshmallow Nexus5?

**Comment by xpz3** [comment]
Something's wrong with your nethunter installation. You might not be installing the correct version for your os or the installation method could be wrong. Are you xdamama on discord?

**Comment by mamilux** [comment]
> Something's wrong with your nethunter installation. You might not be installing the correct version for your os or the installation method could be wrong. Are you xdamama on discord?

Yeah xdamami. But how? My device officially supports Nethunter. Downloaded latest (20.1) from official website installed over cm13.

**Comment by oled19** [comment]
Connect user root on kex manager,startvnc lest try

**Comment by oled19** [comment]
![15883760845725115984712501478217](https://user-images.githubusercontent.com/40560412/80848881-0f8dc900-8c3f-11ea-9661-56a84194c147.jpg)

**Comment by oled19** [comment]
![15883764011893304962525810988035](https://user-images.githubusercontent.com/40560412/80849080-d73aba80-8c3f-11ea-833e-49e8206e332e.jpg)

**Comment by xpz3** [comment]
> Connect user root on kex manager,startvnc let try

The issue has been resolved already via discord

**Comment by oled19** [comment]
> > Something's wrong with your nethunter installation. You might not be installing the correct version for your os or the installation method could be wrong. Are you xdamama on discord?
> 
> Yeah xdamami. But how? My device officially supports Nethunter. Downloaded latest (20.1) from official website installed over cm13.

0970429166

**Comment by nikhilsharma41** [comment]
How can is resolve this?


![Capture](https://user-images.githubusercontent.com/39900961/122291476-7be68d00-cf12-11eb-8f61-e7a07fe446c6.PNG)

**Comment by cjb900** [comment]
@nikhilsharma41 Have you checked to make sure kali is up to date and that xterm is working? Because fluxion works on my end in the latest kali with all the updates.

**Comment by K0K0SHA** [comment]
> `sudo apt-get install xdpyinfo`

not a valid package name

**Comment by cjb900** [comment]
@K0K0SHA Because that's not how you install it in Kali or any Debian-based Linux distro. Info on how to install it can be found here: https://command-not-found.com/xdpyinfo

**Comment by K0K0SHA** [comment]
> @K0K0SHA Because that's not how you install it in Kali or any Debian-based Linux distro. Info on how to install it can be found here: https://command-not-found.com/xdpyinfo

I have both xdpyinfo and x11-utils installed, but the issue was still appearing. I made it stop by deleting the following code section in fluxion.sh:
`if ! xdpyinfo &>/dev/null; then # Assure display info available.
  echo -e "\\033[31mAborted, xterm test session failed.\\033[0m"; exit 4
fi
`
I have no idea what the point of that line of code is. What does xdpyinfo &> /dev/null do, and why does the script stop if it produces no output?

**Comment by cjb900** [comment]
I'm not one of the developers of fluxion. I only try to help others here with it. So I can't say why that is in the code. I do know this is not an error I've personally gotten when running fluxion. My only guess is that you are using a none dedicated hacking distro like Ubuntu or some other Debian-based Linux distro and not using Kali Linux or Parrot OS which fluxion is more designed for.

**Comment by xpz3** [comment]
> > @K0K0SHA Because that's not how you install it in Kali or any Debian-based Linux distro. Info on how to install it can be found here: https://command-not-found.com/xdpyinfo
> 
> I have both xdpyinfo and x11-utils installed, but the issue was still appearing. I made it stop by deleting the following code section in fluxion.sh: `if ! xdpyinfo &>/dev/null; then # Assure display info available. echo -e "\\033[31mAborted, xterm test session failed.\\033[0m"; exit 4 fi ` I have no idea what the point of that line of code is. What does xdpyinfo &> /dev/null do, and why does the script stop if it produces no output?

It's there to check if xterm is available or not and that it works fine as well. If the check fails, most likely the fluxion windows would fail to open even though xterm is installed and works outside of fluxion..

**Comment by K0K0SHA** [comment]
Hello everyone, I resolved the issue in this thread for myself. Everything seemed to be installed, including x11, xdpyinfo, and xterm. I got output from xdpyinfo, but when I noticed that when I typed xterm in my terminal, nothing would happen. It didn't give me an XTerm. Instead, it complained that it could not find my hostname. I had happened to change it after I installed XTerm and Fluxion. 

I changed hostname back using hostnamectl and fluxion is working fine. Be sure to check if your XTerm works.

**Comment by xpz3** [comment]
Or you could simply open a terminal and type xhost + and close it. Then
fluxion would work fine too

**Comment by fraggout23** [comment]
SOLUTION: 

Ensure xdpy-info is installed: **sudo apt-get install x11-utils**
Allow root to execute gui programs: **sudo xhost +SI:localuser:<user name>**

Now run: **sudo fluxion.sh**

**Comment by kkl90** [comment]
Doesnt work.

`Authorization required, but no authorization protocol specified

xhost:  unable to open display ":1.0"`

Worked one time with this: `xhost + local`,
and tried to launch fluxion but it still says that xterm pass failed. So the above error still appears.

**Comment by dhgclt** [comment]
https://github.com/dhgclt/xterm-fix-for-kali-nethunter/blob/main/README.md
