### ISSUE TITLE
not working site

### ISSUE THREAD

**Issue by starlonedz** [FluxionNetwork/fluxion#222]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion crashes*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
nothing happen after captring the provided site

#### What do you think the expected behaviour should be?
*What do you think should happen?*
launch the provided site:

https://github.com/starlonedz/sites/pulls

### Specs
fluxion 3.4

**Comment by deltaxflux** [comment]
You could make a pull request.

**Comment by starlonedz** [comment]
Didnt know how to join the files

**Comment by deltaxflux** [comment]
First merge your pull request after that I do the rest.
