### ISSUE TITLE
problem running fluxion on wifislax .

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#223]
when i run it on wifislax and choose my intel corporation wireless 3160   wireless interface then i scan the wifi(s) but it show nothing although it supports monitor mode and worked with linset. the second wifi adapter works well and it's TP-link Tl-WN722n .

![snapshot1](https://user-images.githubusercontent.com/20546638/32111382-345dfea4-baef-11e7-83a6-a5963785ee6c.png)
![snapshot2](https://user-images.githubusercontent.com/20546638/32111383-34807e48-baef-11e7-88e6-235a254623ec.png)

**Comment by deltaxflux** [comment]
_Hint hint_ it is your wireless card which is not supported. Secound fill out the issue template.

**Comment by minanagehsalalma** [comment]
bro how is it not supported but works with linset ???

**Comment by deltaxflux** [comment]
Bro I don't care. Just to be friendly
