### ISSUE TITLE
can you add the missing packages  from Kail Linux offline ?

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#224]
please add the missing packages  from Kail Linux offline . because the most of the times i use it live from a usb-cd .. so when i want to use fluxion it shows me these missing packages  
![image](https://user-images.githubusercontent.com/20546638/32111803-6db813d2-baf0-11e7-8e0d-8dc26ad2a2be.png)

and ever time i use it i download them again  and again please fix it

**Comment by deltaxflux** [comment]
Do I look like a kali support forum? Write kali devs.

**Comment by minanagehsalalma** [comment]
@deltaxflux no but you can add them to the fluxion .zip file like these 
![image](https://user-images.githubusercontent.com/20546638/32112782-0e68c914-baf3-11e7-8a0b-068ac9d5982d.png)

**Comment by deltaxflux** [comment]
I mean with included dependency version that these are program versions which work propertly with fluxion. I don't include them in fluxion. Download the source a compile it by our own.

**Comment by minanagehsalalma** [comment]
Okay my mistake
