### ISSUE TITLE
problem running fluxion on wifislax .

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#225]
### Do you want to request a *feature* or report a *bug*?
Bug

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*
bash fluxion.sh 
![image](https://user-images.githubusercontent.com/20546638/32112173-64588bcc-baf1-11e7-8005-de4a4314cb7a.png)
![image](https://user-images.githubusercontent.com/20546638/32112177-6706b2d6-baf1-11e7-8530-9e7990faef62.png)

#### What do you think the expected behaviour should be?
*What do you think should happen?*
the airmon-ng 
........................................
when i run it on wifislax and choose my intel corporation wireless 3160 wireless interface then i scan the wifi(s) but it show nothing although it supports monitor mode and worked with linset. the second wifi adapter works well and it's TP-link Tl-WN722n .
i use fluxion lastest version and i don't Faces this problem in kail linux .

**Comment by deltaxflux** [comment]
Use kali if it works there and don't create more than one issue for the same problem.

**Comment by Justincase210** [comment]
I didn't need these bugs or assholes.help!!

**Comment by minanagehsalalma** [comment]
@deltax
But I prefer wifislax on kail.

On Oct 27, 2017 5:47 PM, "Justincase210" <notifications@github.com> wrote:

I didn't need these bugs or assholes.help!!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FluxionNetwork/fluxion/issues/225#issuecomment-340009304>,
or mute the thread

**Comment by deltaxflux** [comment]
Maybe it is a driver issue. Install the driver propertly.

**Comment by minanagehsalalma** [comment]
How is that i use it live form a usb

**Comment by deltaxflux** [comment]
Why if you you really want to get into use a vm or install it at your hdd.

**Comment by minanagehsalalma** [comment]
Vm will not show the built in wifi drive.  And its boring to show from two
operating system every time i turn on my laptop

**Comment by deltaxflux** [comment]
Ok good luck
