### ISSUE TITLE
can you add a text file in the temp folder fluxspace that Contain the wrong passwords  ?

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#226]
please make it keep the wrong passwords in candidate.txt to see what did the clients type and if it's a word from the password or near from it . and i am not talking about the latest typed one but all of them

**Comment by deltaxflux** [comment]
Wrong passwords are saved in root/attemps/pwlog

**Comment by minanagehsalalma** [comment]
@deltaxflux  there no any locationlike this i am using kail linux

**Comment by deltaxflux** [comment]
there is.

**Comment by minanagehsalalma** [comment]
Where bro where .

**Comment by minanagehsalalma** [comment]
@deltaxflux what os do you use ?
