### ISSUE TITLE
problem with Microsoft's versions of Ubuntu. 

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#228]
after running the next command ./fluxion.sh 
it says

xdpyinfo not installed, please install the relevant package for your distribution.

**Comment by strasharo** [comment]
Use a supported OS.

**Comment by minanagehsalalma** [comment]
What if i can't use a supported os

**Comment by deltaxflux** [comment]
You have created 6 issues, please think about before posting senseless or invalid issues.

**Comment by minanagehsalalma** [comment]
Sorry i thought it was fluxion fault.  I just want your project to be
perfect 😢😢
