### ISSUE TITLE
can you add jamming interface  option like wifiphisher ?

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#229]
hello bro
can you add jamming interface  option in case of  having two wireless adapters . so one start the AP INTERFACE and the other start jamming with mdk3 but -c option channel hopping 😊😊😊
please 
i am sorry if i bothered you .

**Comment by minanagehsalalma** [comment]
@deltaxflux why did you closed it without answering me bro

**Comment by sk-y2k** [comment]
Because you can easily do it manually...

**Comment by minanagehsalalma** [comment]
ok.I thought it will be awesome if this option was in fluxion like wifiphisher
