### ISSUE TITLE
[Feature Request] Attack webpage library.

### ISSUE THREAD

**Issue by PrinceShaji** [FluxionNetwork/fluxion#23]
Right now, we have to create our own custom webpage for using with a particular make of router. It's be nice to have a library with community created custom attack webpages. That way, instead of creating a custom page, we could import it if it's already been made by the community or upload our own designs for others to use. 

Don't know how feasible it is, but the easiest way would be creating a fluxion website on GitHub and individuals uploading files to it.

**Comment by vvbv** [comment]
I think it's easier, make fluxion detect the sites in the folder and generate a menu.

**Comment by PrinceShaji** [comment]
Yeah. That works too.

**Comment by deltaxflux** [comment]
I will do it.

**Comment by deltaxflux** [comment]
Switch to https://github.com/FluxionNetwork/sites
