### ISSUE TITLE
fluxion was unable to activate the monitor mode of TL-WN722N

### ISSUE THREAD

**Issue by merlinnusr** [FluxionNetwork/fluxion#231]
only works when I put the commands manually 

$ sudo ifconfig <device-name> down
$ sudo iwconfig <device-name> mode Monitor
$ sudo ifconfig <device-name> up

**Comment by navanchauhan** [comment]
Platform ?

**Comment by merlinnusr** [comment]
Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux

**Comment by deltaxflux** [comment]
Please fill out the issue template and create a new issue.
