### ISSUE TITLE
The fake network doesn't start

### ISSUE THREAD

**Issue by satsriakal** [FluxionNetwork/fluxion#233]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
Kali Linux + ALFA RTL8187.
 Using the latest version, the fake network doesn't start.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
I follow the normal steps. I choose "Rogue AP - Hostapd", but when I start the web interface, the script get stuck on "Avvio del servizio del Portale di Cattura..." and nothing happens.
If I choose "Rogue AP - airbase-ng"  the behaviour is the same.

#### What do you think the expected behaviour should be?
*What do you think should happen?*
I expect that the fake network starts.

### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

./diagnostics.sh: line 3: lib/InterfaceUtils.sh: No such file or directory
[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
./diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown
Injection Test: No Answer...
Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.12.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170820 (Debian 6.4.0-4) ) #1 SMP Debian 4.12.6-1kali6 (2017-08-30)

**Comment by deltaxflux** [comment]
Take a  look here: https://ubuntuforums.org/showthread.php?t=1395012
