### ISSUE TITLE
captive portal not coming up

### ISSUE THREAD

**Issue by Parshuram2** [FluxionNetwork/fluxion#234]
### Do you want to request a *feature* or report a *bug*?
feature

### What is the current behaviour?
no captive portal

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*

#### What do you think the expected behaviour should be?
*What do you think should happen?* Does this need 2 wifi adapters? All it does it say captive portal starting and then does nothing

### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

[ Interface (wlan0) Info ]
./diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown
Injection Test: ioctl(SIOCGIFINDEX) failed: No such device
failed

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.12.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170820 (Debian 6.4.0-4) ) #1 SMP Debian 4.12.6-1kali6 (2017-08-30)

**Comment by deltaxflux** [comment]
Injection Test: ioctl(SIOCGIFINDEX) failed: No such device
failed
