### ISSUE TITLE
Http Server process is not terminated at Fluxion exit

### ISSUE THREAD

**Issue by ssrmpc** [FluxionNetwork/fluxion#235]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
The http server process keeps running.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Just use fluxion as normal. Exit fluxion.

#### What do you think the expected behaviour should be?
pgrep http | kill -9 xargs

### If this is a feature request, what is the motivation or use case for the added feature?
Proper cleanup at exit

**Comment by deltaxflux** [comment]
Fixed thanks for reporting

**Comment by MPX4132** [comment]
This might’ve been an issue with calling stop_attack, since it’s responsible for killing processes spawned by start_attack

```
function stop_attack() {
	...
	# Kill captive portal web server.
	if [ $CaptivePortalServerPID ]; then
		kill $CaptivePortalServerPID &> $FLUXIONOutputDevice
		CaptivePortalServerPID=""
	fi

	...
}

function start_attack() {
	...
	echo -e "$FLUXIONVLine $CaptivePortalStartingWebServiceNotice"
    lighttpd -f "$FLUXIONWorkspacePath/lighttpd.conf" &> $FLUXIONOutputDevice
	CaptivePortalServerPID=$!
	...
}
```
