### ISSUE TITLE
fluxion was unable to activate the monitor mode of TL-WN722N

### ISSUE THREAD

**Issue by merlinnusr** [FluxionNetwork/fluxion#236]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
fluxion was unable to activate the monitor mode of TL-WN722N V2
When it tries to activate it the program stays in a cycle and deactivates my wireless adapter

#### If the current behaviour is a bug, please provide the steps to reproduce it.

I have a VMware® Workstation 12 Pro  12.5.7 build-5813279 

Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux

1.-I active my wireless adaptor 

2.-  [My Wireless adapter is active ](https://imgur.com/a/ai9vU)

3.- [Now I run ./fluxion script without parameters ](https://imgur.com/a/dYuJi)

4.- [My adapter is inactive ](https://imgur.com/a/VcZNx)

5.- [I can't enable it with the script without parameters](https://imgur.com/a/E4brx)

6.- [Now I am using the script with parameters ](https://imgur.com/a/mOX2z)

7.- [I can't enable it ](https://imgur.com/a/Zpkpn)

#### What do you think the expected behaviour should be?
I don't know :/

### Specs
export FLUXIONWIKillProcesses=1; ./fluxion.sh

**Comment by deltaxflux** [comment]
Only the  TL-WN722N V1 does work properly.  TL-WN722N V2 is not supported.

**Comment by merlinnusr** [comment]
lol

**Comment by amitgiri723** [comment]
Please help! 
Please help! 

I have kali Linux on dual boot,   I installed Fluxion on it,  then after installation of Fluxion,  I tried to run but there is not showing of any SSID, BSSID of any wifi-network in Fluxion scanner. 

Till 2018/10/23, it worked  by typing command, 

 #export FLUIXIONAirmonNG=1
#. /Fluxion.sh

and it really  worked ,  but now after two days  it not work even with that command. 
Please give me solution. 

Thank you!
