### ISSUE TITLE
Update Wiki Section: Patch driver (rtl8812au)

### ISSUE THREAD

**Issue by ssrmpc** [FluxionNetwork/fluxion#237]
_### Do you want to request a *feature* or report a *bug*?_
*Dokumentaion-Bug*

_### What is the current situation?_
The documentation is outdated and misleading, The patch driver from Alfa is not necessary anymore since it was used for the packet **realtek-rtl88xxau-dkms.**

_#### What do you think the expected behaviour should be?_
The installation instructions are: 
- **apt-get install realtek-rtl88xxau-dkms**

**IMPORTANT:**
The current driver **realtek-rtl88xxau-dkms** **does not support virtual interfaces** )except mode monitor). Therefore if you just use 1 external WiFi-Adapter the **_hostapt_** will fail! 

Please also consult the [aircrack-ng blog](https://aircrack-ng.blogspot.ch/2017/08/on-drivers-rtl8812au-wn722n-monitor.html) to get more detailed information regarding this realtek-driver.

The only possible workaround is to use 2 physical Wifi-adapters so that no virtual interface must be crated and used.

**Comment by ssrmpc** [comment]
May I change the Wiki? Do I have to do a pull request for that?

**Comment by deltaxflux** [comment]
Good point yeah you have to 
1. clone https://github.com/FluxionNetwork/fluxion.wiki.git 
2. makes changes
3. submit pull request

**Comment by strasharo** [comment]
@ssrmpc , you can paste your proposed content here and we'll add it to the wiki.

**Comment by ssrmpc** [comment]
I apologize for being late.....

Unfortunately I am suffering from a Chemo Therapy that isn't very amusing.

As a matter of fact I already sent you all the Info within a private email,
but I'll try to do my best so that you'll have your info within the next
24h.

Cheers
-Marc

2017-11-12 21:42 GMT+01:00 strasharo <notifications@github.com>:

**Comment by deltaxflux** [comment]
Yeah good luck with that.

**Comment by strasharo** [comment]
Good luck, get well soon.
