### ISSUE TITLE
run install error

### ISSUE THREAD

**Issue by Yanziji** [FluxionNetwork/fluxion#24]
at the last of command sudo ./intaller,sh show that dailog which is give below

fatal: destination path 'revolver' already exists and is not an empty directory.
chmod: cannot access 'revolver/revolver': No such file or directory
mv: cannot stat 'revolver/revolver': No such file or directory

**Comment by rad4day** [comment]
quick fix: check that you have "git" installed
and then go into fluxion/install
`rm -rf revolver`
then rerun the installer

**Comment by Yanziji** [comment]
Thank you very much. It has been processed  @rad4day
