### ISSUE TITLE
problem with fluxion scanner

### ISSUE THREAD

**Issue by al3abwar1** [FluxionNetwork/fluxion#243]
Hi
i have problem with fluxion scanner , i have 2 wifi card , i choose one then choose all channel
when he start scan i didn't get any victem . but when i scan on my normal computer i find more than 10 wifi ready to hack 
this problem also with fern wifi crack
can i get any solution for that

**Comment by deltaxflux** [comment]
Your wireless card is the limit not the software.

**Comment by al3abwar1** [comment]
what do you mean my card is the limit ? i have two card .

**Comment by MPX4132** [comment]
I also think your cards might be the issue, try running the diagnostics script. Go into the fluxion directory and run:

```
./scripts/diagnostics.sh <INTERFACE_HERE>
```
 Paste the output here, otherwise we can’t help you.
