### ISSUE TITLE
correct password doesnt work in fluxion

### ISSUE THREAD

**Issue by renancompuece** [FluxionNetwork/fluxion#244]
I choose network and even i put correct password, fluxion counter attempts increment but not show the password. I try this one month before and works fine. Why it happens ? is there any way to see attempt ?

**Comment by MPX4132** [comment]
Attempts are stored at:
```
cat \"$FLUXIONWorkspacePath/pwdattempt.txt\" >> \"$CaptivePortalPassLog/$APTargetSSID-$APTargetMAC.log\"
```
Which is at:
```
$FLUXIONPath/attacks/Captive Portal/pwdlog/$APTargetSSID-$APTargetMAC.log
```
