### ISSUE TITLE
No deauthentication with Deauth all [mdk3]

### ISSUE THREAD

**Issue by xmagickx** [FluxionNetwork/fluxion#246]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
At the last window when the fakeAP is set up the Deauth all [mdk3] window opens and shows deauthentication but does not work i.e. client remains connected to original Ap.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
As mentioned above.

#### What do you think the expected behaviour should be?
Clients should be disconnected from the original AP

### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by MPX4132** [comment]
Are you sure the target AP isn't just hoping to a new channel?

**Comment by deltaxflux** [comment]
We are not mdk3 devs so please contact them if you have problems with mdk3.

**Comment by xmagickx** [comment]
@deltaxflux my standalone mdk3 works fine but with fluxion the clients PWR in aireplay-ng does not reduce to zero when monitoring with another wifi card with airodump-ng instead it becomes -22 -20dBm. But deauth clients with aireplay-ng reduces their PWR to 0dBm and deauthticates them. 

@MPX4132 no AP is fixed

**Comment by xmagickx** [comment]
I was thinking if fluxion could use aireplay-ng to disassociate clients with another wifi card just like wifiphisher does instead of mdk3 in the scenario when FakeAP is starting

**Comment by deltaxflux** [comment]
Well you can choose between mdk3 and aireplay-ng

**Comment by xmagickx** [comment]
@deltaxflux Yes that I can only during capturing the handshake but not during the last part when all the windows open i.e fakeAP FAKEDNS DHCP server etc etc. In there only mdk3 is used for deauth...

**Comment by MPX4132** [comment]
With the modification I made a while ago, you can choose another wireless interface if you need it, otherwise you can just choose the same as the scanning interface. It'll show as if it's already in use (purple [-]), but because it's allocated to fluxion, it's possible to reuse it. Moreover, like @deltaxflux said, you've got two options, `mdk3` and `aireplay-ng`.

**Comment by xmagickx** [comment]
@MPX4132 u didn't get me. I said in the last part where all the automatic 5 windows of XTerm opens up there only mdk3 is used for deauthing no option for using aireplay...

**Comment by MPX4132** [comment]
@xmagickx Yeah, you're right, there is no option for that... I'm sorry, I thought I had written an option to allow that.

**Comment by xmagickx** [comment]
Well if that could be implemented it would be great... I used aireplay-ng in the last part by editing the program a bit... Anyways thanks....

**Comment by xmagickx** [comment]
Just one query... Does the attack continue to be effective even if the AP changes channel while attack is in progress in the last part when multiple xTerms open up???

**Comment by MPX4132** [comment]
No, the attack will not work if the target access point changes channel, since clients of the target AP will not be disconnected from an access point on a different channel.

**Comment by xmagickx** [comment]
@MPX4132 I was thinking of this when AP changes channel during the attack how to counter that scenario... I'm working on it a bit...

**Comment by MPX4132** [comment]
Well, someone's already made an issue with that in mind. It's just a matter of someone implementing it. I just haven't had time to experiment. I've been busy with other things lately.

**Comment by mutahhir786** [comment]
in last mdk3 deauth is not working send me program to use aireplay-ng instead of mdk3

**Comment by MPX4132** [comment]
There's already an option to select between mdk3 and aireplay-ng for deauthentication within the script.

**Comment by mutahhir786** [comment]
In last step when all windows shows there is no option of aireplay-ng and
mdk3 is not working...

**Comment by ichobod** [comment]
@xmagickx Do you mind sharing how you edited it? I'm have the same issue.

**Comment by suzzanadh** [comment]
@xmagickx please share how you edited to choose airplay instead of mdk 3 in 2nd part

**Comment by xmagickx** [comment]
Just see aireplay-ng commands... You will find it... Edit the fluxion.sh
accordingly...
