### ISSUE TITLE
Password verification error

### ISSUE THREAD

**Issue by atseniuk** [FluxionNetwork/fluxion#25]
### Which version of fluxion are you using?
Newest

### What distribution of Linux (including the version) are you running it on?
Kali 2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Alfa awus036nh 

### Which is the driver for it?
Alfa awus036nh  Etwork driver

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Created fake AP and captured a handshake that Fluxion verified however when I connect to fake AP and enter the correct key it says incorrect password.

**Comment by strasharo** [comment]
Was the handshake verified with pyrit or aircrack?

**Comment by atseniuk** [comment]
pyrite however have attempted with aircrack

On Jul 16, 2017, at 2:59 AM, strasharo <notifications@github.com<mailto:notifications@github.com>> wrote:


Was the handshake verified with pyrit or aircrack?

**Comment by deltaxflux** [comment]
Is something in the pwlog folder?

**Comment by borlandconnect** [comment]
Can you run pyrit -r <path to handshake pcap file" analyze and post the output here.

**Comment by strasharo** [comment]
Can you execute:
pyrit -r <full path to handshake pcap file> analyze 
and post the output here.

**Comment by deltaxflux** [comment]
Closed until needed
