### ISSUE TITLE
fake AP to fake page

### ISSUE THREAD

**Issue by Shadowingz** [FluxionNetwork/fluxion#250]
nowaday, allmost website is https so it dont rediect to fake page to enter password. 
can you make a notice after connect to fake AP say that: "Internet access request". When click to that, it redirect to fake page to enter password. This is the old feature of the older version of Fluxion that you forget it

**Comment by rad4day** [comment]
Improve your English, please. Thanks.

**Comment by MPX4132** [comment]
@Shadowingz Maybe you're using the wrong portal interface.
