### ISSUE TITLE
Fluxion on Kali Nethunter not displaying text

### ISSUE THREAD

**Issue by wvthoog** [FluxionNetwork/fluxion#253]
### Do you want to request a *feature* or report a *bug*?
*don't know*

### What is the current behaviour?
*fluxion doesn't display some text (lists, menu's)*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*using Kali Nethunter on Moto G4 Plus. Setup Kernel 3.10.107 with xcfe4 / xcfe4-terminal running in chroot*

#### What do you think the expected behaviour should be?
*display lists. (eg languages, wireless interfaces, wireless networks, attacks etc*

### If this is a feature request, what is the motivation or use case for the added feature?
not a feature request. Just wondering why this is not displayed

### Specs
[ FLUXION Info ]
FLUXION V3.4

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
Device: phy1
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT5370
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm failure!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 3.10.107-lineageOS (wvthoog@wvthoog-virtual-machine) (gcc version 4.6.2 20111004 (prerelease) (Linaro GCC 4.6-2011.10) ) #10 SMP PREEMPT Tue Nov 14 14:31:33 CET 2017

**See attached photos. /usr/bin/xterm does exist**

![iwconfig1](https://user-images.githubusercontent.com/24963008/32786501-6b447db2-c954-11e7-82a5-223c8f6ea9b4.jpg)
![fluxionstartup1](https://user-images.githubusercontent.com/24963008/32786513-73fc8300-c954-11e7-8141-e522c4c95ccb.jpg)
![fluxionselectlanguage1](https://user-images.githubusercontent.com/24963008/32786526-7f0df09e-c954-11e7-874a-fc898d5d39d2.jpg)
![fluxionselectinterface1](https://user-images.githubusercontent.com/24963008/32786545-8d3cb056-c954-11e7-8994-95f1ed66bf45.jpg)
![fluxioninterfaceselected1](https://user-images.githubusercontent.com/24963008/32786556-927d32fc-c954-11e7-8e7e-9303fde74d1f.jpg)
![fluxionscanallchannels1](https://user-images.githubusercontent.com/24963008/32786567-9b48d666-c954-11e7-98d8-220965b16818.jpg)
![fluxionlistwirelessnetworks1](https://user-images.githubusercontent.com/24963008/32786576-a01ff05c-c954-11e7-8eee-1455ea63c2da.jpg)
![fluxionhandshake1](https://user-images.githubusercontent.com/24963008/32786590-a9b4cc00-c954-11e7-9124-83a2c5e4578a.jpg)

**Comment by MPX4132** [comment]
**Thank you very much** for being the single one person I've seen lately to follow the damn template. You even added lots of images, thanks.

So your problem is fairly straight forward... you're missing xterm:
```
[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm failure!
```
Just install it and things should start working fine.

**Comment by deltaxflux** [comment]
The one window (main window in the middle ) doesn't look like a xterm window. Try to run fluxion in a xterm window and see if it is working.

**Comment by wvthoog** [comment]
R
![fluxionxterm1](https://user-images.githubusercontent.com/24963008/32824514-8fd475aa-c9e1-11e7-9ff0-c3cb2b2860b4.jpg)
an the diagnotiscs test through ssh, that's why XTerm failed. Ran the same test again in X. Results below. Same issue

**Comment by deltaxflux** [comment]
Maybe reconfigure your xterm. I see the it display a text in the xterm terminal means it works?
For me it works one my op5 and I don't have had any issue like this.

**Comment by wvthoog** [comment]
@deltaxflux 
could you post your Xresources file

**Comment by jitu3232** [comment]
Can we run fluxion on android without gnu and in nethunter terminal
