### ISSUE TITLE
No promt for selecting target network

### ISSUE THREAD

**Issue by gregthanas** [FluxionNetwork/fluxion#254]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*Can't select target network.*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*Fluxion scans for networks and prompts the user to close the window of the scanner. I closed the windows either with Ctrl + C, or by pressing the X button on the bar. After that, the list of detected networks appears on my terminal, but without any other prompt. Selecting a network is impossible, can't proceed further.*

#### What do you think the expected behaviour should be?
*The terminal should give a prompt for selecting the network and waiting for the input.*

### Specs
*#!/bin/bash

source lib/InterfaceUtils.sh

if [ ! "$1" ]
then echo "Usage ./scripts/diagnostics <wireless_interface>"; exit 1
fi

echo "[ FLUXION Info ]"
declare -r FLUXIONInfo=($(grep -oE "FLUXION(Version|Revision)=[0-9]+" fluxion.sh))
echo "FLUXION V${FLUXIONInfo[0]/*=/}.${FLUXIONInfo[1]/*=/}"
echo -ne "\n\n"

echo "[ BASH Info ]"
bash --version
echo "Path: `ls -L $(which bash)`"
echo -ne "\n\n"

echo "[ Interface ($1) Info ]"
if interface_physical "$1"
then echo "Device: $InterfacePhysical"
else echo "Device: Unknown"
fi

if interface_driver "$1"
then echo "Driver: $InterfaceDriver"
else echo "Driver: Unsupported"
fi

if interface_chipset "$1"
then echo "Chipset: $InterfaceChipset"
else echo "Chipset: Unknown"
fi

echo -n "Injection Test: "
aireplay-ng --test "$1" | grep -oE "Injection is working!|No Answer..." || echo "failed"
echo -ne "\n\n"

echo "[ XTerm Info ]"
echo "Version: `xterm -version`"
echo "Path: `ls -L $(which xterm)`"
echo -n "Test: "
if xterm -hold -fg "#FFFFFF" -bg "#000000" -title "XServer/XTerm Test" -e "echo \"XServer/XTerm test: close window to continue...\"" &> /dev/null
	then echo "XServer/XTerm success!"
	else echo "XServer/XTerm failure!"
fi
echo -ne "\n\n"

echo "[ HostAPD Info ]"
hostapd -v
echo "Path: `ls -L $(which hostapd)`"
echo -ne "\n\n"

echo "[ Aircrack-ng Info ]"
aircrack-ng -H | head -n 4
echo -ne "\n\n"

echo "[ System Info ]"
if [ -r "/proc/version" ]
then cat /proc/version
else uname -r
fi*
![image](https://user-images.githubusercontent.com/8137385/32888655-a5738758-cad0-11e7-96c2-b1790519b461.png)

**Comment by MPX4132** [comment]
Try entering the number of the target AP without leading zeroes. Also, I'm not sure what happened there but you shouldn't have 10 prompts before you can enter something.

**Comment by gregthanas** [comment]
Well, sorry for the misleading screenshot. There are many prompts because I pressed the ENTER button many times, but it is not the problem. I tried it the way you suggested and still it did not work.

**Comment by MPX4132** [comment]
That's weird. Ok, so let's clarify this a big. You ran the scan and the scanner get some candidate targets. Then you closed the window with X, which populated your main fluxion window, then you could **not** enter a number like this:
```
[fluxion@kali]-[~] 1
```
If that's what happened, that's strange and might have something to do with character encoding on your machine. You can look for the numbers online, copy them and try pasting them to the terminal. If that works, it's probably some type of character encoding problem on your system, which is super weird.

**Comment by deltaxflux** [comment]
Yeah weird, I don't have had any of this problem yet. Which is your operating system? And can you execute the diagnostic script rather than open it.

**Comment by usama7628674** [comment]
@deltaxflux He's using kali linux

**Comment by deltaxflux** [comment]
@MPX4132 I agree with that. Sorry buddy but I would recommend that your fix your system on your own.
