### ISSUE TITLE
Handshakes of a network ESSID containing double quotes and spaces are never verified.

### ISSUE THREAD

**Issue by underscrew** [FluxionNetwork/fluxion#256]
The handshakes of a network ESSID containing double quotes and spaces, such as `"test123 "`, is captured, but it never get verified through neither method.

Also, these double quotes and spaces are shown only on fluxion, not on windows, linux or android.

Is the normalization using the `sed` command necessary for the `"`? Will it solve the never verified handshake issue?

**Comment by deltaxflux** [comment]
we should add td noticed. Fixed tommorrow

**Comment by MPX4132** [comment]
Was this fixed?
