### ISSUE TITLE
Fluxion Gets Stuck on Server Starting Service ; Won't Detect Clients

### ISSUE THREAD

**Issue by Schneiderism** [FluxionNetwork/fluxion#257]
### Do you want to request a *feature* or report a *bug*?
Report a bug

### What is the current behaviour?
Once going through all of the steps to set up the rogue AP, it gets hung up on "Server Starting Server" and won't detect clients or show and activity.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Select the wireless device, scan for networks, select a network, capture the handshake if necessary, select the default english fake login page, and launch the program

#### What do you think the expected behaviour should be?
The server should start the service, clients should show up in the list, and the DNS server should show activity

### If this is a feature request, what is the motivation or use case for the added feature?
N/A

### Specs
```[ FLUXION Info ]
FLUXION V3.4


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy2
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Injection Test: Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)
```

**Edit** Attached screenshot of what the screen looks like when it hangs

![screenshot from 2017-11-18 10-44-57](https://user-images.githubusercontent.com/11036216/33090704-c573a60a-cea9-11e7-874b-081e3e8b62af.png)

**Comment by ProsAnon** [comment]
Same problem here, and also I got a message about SSL certificates, when i try to create one,it gets me right here(in the same stage your photo is). Sorry for bad english, not exactly my primary :dango:

**Comment by seventhplug** [comment]
Im having this problem tOo... i cant connect to the evil twin ap.

**Comment by MPX4132** [comment]
If you look though the past issues, this is probably one of the most common ones... it's a driver problem. We can't do much about it. It's usually caused by a driver that does not support virtual interfaces.

**Comment by MPX4132** [comment]
Yeah, driver problem `rt2800usb`...

**Comment by Schneiderism** [comment]
Is it possible to bypass the need for  virtual interfaces by using two different antennae?

**Comment by MPX4132** [comment]
If you're talking about two different wireless cards/radios, yes, you can use two and that would work perfectly fine. Just make sure to select the second radio when you enter the `Captive Portal` attack. So, when fluxion asks you to select a radio for scanning, choose radio A. When you're ready for the `Captive Portal` attack, select the `Captive Portal` option and choose radio B when prompted.

**Comment by Schneiderism** [comment]
Last clarifying question: Do both cards need injection capabilities, or just the Captive Portal?

**Comment by MPX4132** [comment]
@Schneiderism That's a good question. No, only the monitor card/radio needs injection. The monitor interface is used to deauthenticate the target access point, which requires injecting deauthentication packets. The `Captive Portal` interface requires a master-mode capable wireless card/radio (having the capability of turning into an access point).

**Comment by Schneiderism** [comment]
Perfect, this is the information I've been searching so desperately for! Hopefully it's relevant to other cases.

**Comment by lo0oper** [comment]
Is there any other way out to the problem

**Comment by lo0oper** [comment]
I am using the inbuilt WiFi card for this as it could be switched to monitor mode and here in India we don't have the easy access to the external WiFi cards they even cost much for an engineering first year student ?
