### ISSUE TITLE
Text not visible on Nethunter

### ISSUE THREAD

**Issue by Parshuram2** [FluxionNetwork/fluxion#258]
### Do you want to request a *feature* or report a *bug*?
*Bug* Not Sure

### What is the current behaviour?
*fluxion crashes* Options text not visible in Nethunter

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*A great way to do this is to provide screenshots and commands.*

#### What do you think the expected behaviour should be?
*What do you think should happen?* Text should be visible
### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
Injection is working
Xterm is good. Although I don't see any text when I run Fluxion. No language options and not my wlan0 and wlan1. Hostapd is good. Aircrack doesn't show any output. I can run airmon on it for sure. 
System Info :-  LINUX 3.4.113-LINEAGEOS-GLCDLDE5F
![2017_11_23_01 11 41](https://user-images.githubusercontent.com/23211166/33146962-29144cee-cfec-11e7-8159-35f37edae37e.png)
![2017_11_23_01 13 23](https://user-images.githubusercontent.com/23211166/33146971-2c89700c-cfec-11e7-82f3-7e176d3d9769.png)
![2017_11_23_01 09 55](https://user-images.githubusercontent.com/23211166/33146976-2fce31a8-cfec-11e7-89d3-30303fee9c6c.png)
![2017_11_23_01 13 35](https://user-images.githubusercontent.com/23211166/33146979-312afc48-cfec-11e7-959c-ad7230410d21.png)

**Comment by seventhplug** [comment]
Works perfectly on my Nethunter (0neplus X with TL-WN722N) no issues

**Comment by Parshuram2** [comment]
Yea Tried that..But then fluxion asks me to type FLUXIONWIKillProcesses=1 before using it, so no option there as well. Also, if xterm is good,why can't I see any options?..strange

**Comment by seventhplug** [comment]
got some issues on my nethunter issue #259 sorry didn't test it thoroughly before i commented here. i just tested til i get the AP up but not tried connecting other clients to the evil AP.. but mine is not wifi dongle related

**Comment by Hritik14** [comment]
@deltaxflux  I suppose #266 might be a reason. Not sure though.
@Parshuram2 Can you post the output of `sudo bash -x fluxion.sh`

**Comment by Parshuram2** [comment]
Well, I tried changing resolution in VNC, running it in Xterm..No joy!. I mean it runs I can put the card in monitor mode..but then since no options are visible ,I cannot select a target or move ahead anymore. :(
Seems to be a solvable issue. I think it HAS to do with screen resolution/orientation or some shit like that.

**Comment by Hritik14** [comment]
Try piping all STDOUT/STDERR to a file repeat the steps (Provide stdin anyway) and check the file to confirm it is a resolution issue.

**Comment by MPX4132** [comment]
@Parshuram2 Wifite, reaver, and airmon-ng all use a single interface. Fluxion requires two interfaces. To circumvent that, we use two _virtual interfaces_. Older drivers do not support virtual interfaces.

The diagnostics script should only be executed from fluxion's root directory:
```
cd fluxion
./scripts/diagnostics.sh wlanX
```

You shouldn't have to use the killer flag either, something's interfering with the interface.

**Comment by MPX4132** [comment]
@seventhplug Don't put the interface in monitor mode for fluxion. From what I remember, I explicitly unset all monitor mode interfaces before offering them to the user. Switching the interface to monitor mode before running fluxion is a waste of time, and might cause issues when fluxion creates a virtual interface since it's not the original.

**Comment by Hritik14** [comment]
@MPX4132 From your reply it seems you wrote the monitor switches. Can you have a look at  #266  ?

**Comment by MPX4132** [comment]
@Hritik14 Sure thing.

**Comment by Parshuram2** [comment]
We are talking about the TEXT not being visible. I have no issues with fluxion working or my card.

**Comment by MPX4132** [comment]
@Parshuram2 If you have no issues with your radio, why do you even mention it and state that’s what proves it’s a problem with fluxion?

“Also, how can it not be a fluxion issue. The card works perfect with wifite,reaver,airmon etc etc..”

I really don’t understand how you derived that.

Anyway, what’s bash’s version? It might have to do with the fact I used functionality only available in bash 4.4 and higher, or something like that. Then again, that might not be the issue, considering @seventhplug ‘s report.

Make sure the language scripts exist under `fluxion/language`.

**Comment by MPX4132** [comment]
Please download the latest version of fluxion and run the diagnostics script **exactly** as below:

```
cd fluxion
./scripts/diagnostics.sh wlanX # replace with your wireless interface’s identifier
```
Post the results in your reply.

**Comment by MPX4132** [comment]
Please also reply with the output of
```
cd fluxion
readarray -t languageCodes < <(ls -1 language | sed -E 's/\.sh//')
for lang in "${languageCodes[@]}"
do echo $lang
done
```

**Comment by Parshuram2** [comment]
Am I not making myself clear? The only issue is ..wherever there is a list of options to choose from ...it is not displaying. THAT IS IT. Language scripts are present because if I choose any AP randomly guessing say 6 or 7 or 20..the program works as it should. I have to choose options remembering their numbers i.e what each choice no. stands for. REST OF THE THINGS ARE FINE. 

You cannot select a particular AP though..because you cannot see it's number after scan.

**Comment by MPX4132** [comment]
@Parshuram2 Post the output of what I asked for, along with the output of the following:
```
env
```
I'll have to close the issue otherwise, I need more info to narrow down the problem. I don't know what you know or what you've tried. Also, ease up on the capitals. Everyone can read here.

**Comment by deltaxflux** [comment]
#268
