### ISSUE TITLE
aireplay-ng deauth timeout

### ISSUE THREAD

**Issue by sadboyzvone** [FluxionNetwork/fluxion#260]
### Do you want to request a *feature* or report a *bug*?
*Both?*

### What is the current behaviour?
*fluxion aireplay-ng deauth doesn't give me a handshake*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*Use Handhsake Snooper, aireplay-ng deauth instead of Monitor*

#### What do you think the expected behaviour should be?
*If there is a way it would be good if aireplay would do the deauth every 2 seconds, because it will allow the device to connect,while the monitor captures the handshake*

### If this is a feature request, what is the motivation or use case for the added feature?
*Tested fluxion with my phone,it didn't even try to connect to the AP since deauth was so fast*
### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by sadboyzvone** [comment]
I've made a small snippet of how it could work but I don't know enough bash to do a PR :))
`while true; do aireplay-ng --deauth=1 -a $APTargetMAC --ignore-negative-one $WIMonitor; sleep 5; done`

**Comment by sadboyzvone** [comment]
Actually fixed it myself :pp I'll open a PR

**Comment by sadboyzvone** [comment]
fixed in #261

**Comment by deltaxflux** [comment]
Not usefull
