### ISSUE TITLE
Cannot access Fake AP created with AWUS036NH

### ISSUE THREAD

**Issue by wifidemon** [FluxionNetwork/fluxion#263]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
Laptop and phone sees evil twin fake AP but cannot connect to fake AP.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
cd fluxion
sudo ./fluxion.sh
4 for `English`
1 for `wlan0` `Ralink Technology, Corp. RT2870/RT3070` (Alfa AWUS036NH)
1 for `All channels`
After the target AP appears, I stopped the FLUXION Scanner
15 for the target AP
1 for `Captive Portal`
2 for `wlan0` `Ralink Technology, Corp. RT2870/RT3070` (Alfa AWUS036NH)
1 for `Rouge AP - hostapd`
Y for using a previously captured WPA handshake
1 for `pyrit verification`
1 for `Create an SSL certificate`
45 for `Login-Xfinity (English)`

Using a wireless device (laptop and phone), I tried connecting to the fake AP (open AP) it rarely connects. 

Sometimes it connects, and I can see some URLs in the FLUXION AP DNS Service when it works and the fake login page can be viewed. But If I reconnect to the fake AP minutes later, it stop connecting to the fake AP.

`Appears that connecting to fake AP once will prevent further connections to the fake AP!`

#### What do you think the expected behaviour should be?
Wireless devices should connect to fake AP and see the webpage. Reconnecting to fake AP should work for an extended time.

### Specs
Running Kali 2017.2 in a Virtualbox VM

![image](https://user-images.githubusercontent.com/34006866/33242891-93f47a88-d2a9-11e7-95ff-4638600c208d.png)

**Comment by MPX4132** [comment]
It’s a driver problem. Your driver does not support virtual interfaces.

**Comment by MrKali** [comment]
I am currently experiencing the same problem. Is it possible to solve the problem or do I have to buy a new adapter?

**Comment by MPX4132** [comment]
@MrKali you’ll probably have to purchase another wireless adapter.

**Comment by azamet90** [comment]
> I am currently experiencing the same problem. Is it possible to solve the problem or do I have to buy a new adapter?
 my internal wifi and external wifi is doing the same thing there is some different problem... fluxion should work with internal wifi too
