### ISSUE TITLE
[Missing Documentation] Use of FLUXIONAirmonNG ?  

### ISSUE THREAD

**Issue by Hritik14** [FluxionNetwork/fluxion#266]
Grepping FLUXIONAirmonNG doesn't give any initialization of it ? I think it is used to check if Arimon-ng is available or something ?    
 On my system no monitor mode interface is turned on before starting airodump-ng which causes no Wireless AP  to show up.     
I checked it out and a line in fluxion.sh checks if `FLUXIONAirmonNG` set then only proceeds to use airmon-ng. Why so ? Isn't airmon a required dependency ? 

PS: Though the default wireless interface got a little messed up instead. 
Before: 
` wlp2s0: <BROADCAST,ALLMULTI,PROMISC,NOTRAILERS,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether MAC_ADDRESS_HERE brd ff:ff:ff:ff:ff:ff
`
After:
`wlp2s0: <NO-CARRIER,BROADCAST,ALLMULTI,PROMISC,NOTRAILERS,UP,LOWER_UP> mtu 1500 qdisc mq state DORMANT mode DORMANT group default qlen 1000
    link/ieee802.11/radiotap 56:01:94:65:40:04 brd ff:ff:ff:ff:ff:ff
`

**Comment by deltaxflux** [comment]
Is your wireless card compartible?

>  I think it is used to check if Arimon-ng is available or something ?

Yes it check if aircrack-ng is installed. Airmon is in the package of aircrack-ng

**Comment by Hritik14** [comment]
I can enable monitor mode manually by aimon-ng. Actually editing the script to skip the `FLUXIONAirmonNG` variable is set does everything OK. 
The problem is I cannot find any initialization of `FLUXIONAirmonNG`.     
Now if aircrack-ng is a required dependency (which gets installed when fluxion.sh is run) then do we really need to check if it is there ? It must be there.

**Comment by deltaxflux** [comment]
Can u redirect me to the line?

**Comment by c0mrade69** [comment]
sorry guys for spam. I'm new here and can't find way to contact whoever. I just wanted upload Slovak translation to Captive Portal. Please guide me how to / where to put it if interested. If not please ignore me and delete this post..
Sorry again for spamming here but really don't know how / where to put it and just wanted support your great work!

**Comment by Hritik14** [comment]
@deltaxflux https://github.com/FluxionNetwork/fluxion/blob/a88ebb2e381f4161b6ba371af0c09b58d5bd661c/fluxion.sh#L495 
In fact every occurrence of `FLUXIONAirmonNG` is only a conditional statement. It is never initialized. I don't know how fluxion was even working. 

@c0mrade69 Follow [this article](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/#summary) to know how to work with git. Add a language file to `fluxion/language`.

**Comment by c0mrade69** [comment]
@Hritik14 thank you sir, will try to follow.

**Comment by deltaxflux** [comment]
@Hritik14 Do you want to update Slovak translation ? If please share it below.

**Comment by deltaxflux** [comment]
@MPX4132 you designed this can you help me out?

**Comment by c0mrade69** [comment]
@deltaxflux there must be misunderstanding. I want to add NEW language - **Slovak** for attacks/Captive Portal/generic/languages. 
I don't have complete translation for UI stored in fluxion/language. 
Btw Slov**akia** and Slov**enia** are 2 different countries so are their languages **SK** and **SL**.

**Comment by deltaxflux** [comment]
Oh I see, can you share your translated Slovakia version here?

**Comment by c0mrade69** [comment]
Here it goes. Can you please give me step by step guide how to support you in future with other files?
[Slovak.zip](https://github.com/FluxionNetwork/fluxion/files/1507681/Slovak.zip)

**Comment by deltaxflux** [comment]
Can you translate: https://github.com/FluxionNetwork/fluxion/blob/master/language/en.sh to Slovakia?

**Comment by c0mrade69** [comment]
I can try sir :) Can you please give me some contact or way how to do it "right way"?

**Comment by c0mrade69** [comment]
@deltaxflux and cs.sh should be **CZ**.sh as Czech language has short tag CZ.

**Comment by c0mrade69** [comment]
@deltaxflux submitted slovak translation. hope it finds its way to you .. :)

**Comment by deltaxflux** [comment]
@c0mrade69 I see but you delete the english translation please fix this before I merge it.

**Comment by deltaxflux** [comment]
> @deltaxflux and cs.sh should be CZ.sh as Czech language has short tag CZ.


your right

**Comment by c0mrade69** [comment]
> @c0mrade69 I see but you delete the english translation please fix this before I merge it.

@deltaxflux 
I would like to but have no idea how :[ I'm really new into this

**Comment by deltaxflux** [comment]
ok I do it manually

**Comment by c0mrade69** [comment]
@deltaxflux sorry about that sir

**Comment by deltaxflux** [comment]
I added it thanks for your work

**Comment by c0mrade69** [comment]
@deltaxflux You are welcome sir. I admire your work!
I found error while trying to use Slovak language:
![image](https://user-images.githubusercontent.com/34037644/33332608-fb771a14-d464-11e7-8f3e-41d82306a60f.png)


I'm working on the missing files already. Would really appreciate the correct way how to connect it to your project :) anyone could give me contact where I can talk to someone and get few quick answers :)

**Comment by Hritik14** [comment]
@c0mrade69  Nice suggestion but I don't think that would be possible with current structure. 
Before adding language make sure you upload files to **all** these locations:
```
./attacks/Handshake Snooper/language
./attacks/Captive Portal/language
./language

```

**Comment by c0mrade69** [comment]
@Hritik14 roger that :) but what you mean by upload them..? where / how?  can you give me contact buddy? email, Line ID, fb whatever.. would like to really improve

**Comment by Hritik14** [comment]
I've already given you the link on [How to contribute on github](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/). Follow that.

**Comment by c0mrade69** [comment]
@Hritik14 thanks my friend I checked it, but there are not answers on all my questions :/

**Comment by MPX4132** [comment]
@Hritik14 @deltaxflux Sorry about the confusion, the `FLUXIONAirmonNG` flag should only be set to true (`export FLUXIONAirmonNG=1`) if you absolutely need fluxion to use `airmon-ng` to switch the radios to monitor mode. Fluxion **does not use airmon-ng by default anymore**, due to compatibility issues with some newer cards. Here's the [merged branch](https://github.com/FluxionNetwork/fluxion/pull/91) and a bit of explanation after I finished implementation.

**Comment by MPX4132** [comment]
Alright, I updated the section dealing with [flags and preferences](https://github.com/FluxionNetwork/fluxion/wiki/Flags-&-Preferences).

**Comment by MPX4132** [comment]
@Hritik14 Sorry I closed your merge request earlier, I just realized why you were working on that by reading this thread.

“
Before adding language make sure you upload files to all these locations:
```
./attacks/Handshake Snooper/language
./attacks/Captive Portal/language
./language
```
“

Again, sorry, I wasn’t understanding why it was required.

**Comment by Hritik14** [comment]
@MPX4132 Well.. On my system not using airmon-ng causes not to populate the FLUXION Scanner (the airodump window).

**Comment by MPX4132** [comment]
@Hritik14 If your system prefers fluxion, uncomment it from the preferences file. Take a look at the [Flags and Preferences](https://github.com/FluxionNetwork/fluxion/wiki/Flags-&-Preferences) wiki.

**Comment by Hritik14** [comment]
@MPX4132 I think my system prefers `airmon-ng`. The problem is running fluxion with default settings shows unpopulated airodump window (i.e. no AP is detected) . Shouldn't it give some sort of suggestion that the user should try `export FLUXIONAirmonNG=1` ?

**Comment by MPX4132** [comment]
Considering the fact it’s been months since I released that change, and no one had reported it, I don’t think it makes much of a difference. You can add it, if you want.

I just noticed I said fluxion instead of airmon-ng, whoops.
