### ISSUE TITLE
Fluxion problem in Displaying text (nethunter)

### ISSUE THREAD

**Issue by lightakun** [FluxionNetwork/fluxion#268]
Cloned and installed fluxion in my leeco le2 having nethunter installed (arm64) 
See the pics below
The text are not showing
PICS

https://ibb.co/mwbBf6
https://ibb.co/cQZKYR
https://ibb.co/irBNnm
https://ibb.co/nswoSm
https://ibb.co/kZkXnm
https://ibb.co/gDCj06
https://ibb.co/bC2pYR
https://ibb.co/nHcHL6
https://ibb.co/fMFXnm

**Comment by MPX4132** [comment]
Run the diagnostics script:
```
cd fluxion
./scripts/diagnostics.sh wlanX
```
**Make sure you replace "wlanX" with your interface's identifier.**

**Comment by lightakun** [comment]
@MPX4132

Thank you for the response :)
I did the diagnostic.sh but still the problem persist :(

Things ive tried
1) update the F out of my system(apt update, apt upgrade, apt dist-upgrade, apt-get update, apt-get upgradr, apt-get dist-upgrade)

2)Reinstalled and installed fluxion again

3)tried with xterm too but still text overlapping and no text after  "select languages screen"

Some info:
I have tp-link wn722n wireless adapter which has some atheros chipset(drivers installed)

My manged mode is [wlan1] and monitored mode is [wlan1mon]

Wlan0 is my inbuild wlan that my phone has(no monitor mode support)

All the dependencies are installed properly
,(is it because of lacale?)

HERES THE OUTPUT OF ./diagnostics.sh
http://freetexthost.com/6xk1rdhkfi

Hope the problem gets solved soon :)

**Comment by MPX4132** [comment]
**You must execute it exactly as I did:**
Go to the fluxion **ROOT**, and run it from there:
```
cd fluxion # this is the root, not scripts
```
Then run the diagnostics script with your interface:
```
./scripts/diagnostics.sh wlanX
```

**Comment by lightakun** [comment]
@MPX4132
heres the result on wlan1mon(monitor mode)


 http://freetexthost.com/i3ocu0mx4q

But still the problem persist :(

**Comment by MPX4132** [comment]
Yeah, the problem will persist. I just needed the diagnostics information to dismiss some potential causes. The good news is that your WiFi card/radio uses a good driver, the `ath9k_htc` which fully supports fluxion.

Run this command and paste the output in your reply:

```
cd fluxion
la -lA language
```

**Comment by lightakun** [comment]
@MPX4132

Heres the output

root@kali:~# cd fluxion
root@kali:~/fluxion# ls -lA language
total 112
**-rwx--x--x. 1 root root 5164 Nov 29 02:21 cs.sh
-rwx------. 1 root root 5451 Nov 29 02:21 de.sh
-rwx--x--x. 1 root root 5606 Nov 29 02:21 el.sh
-rwx------. 1 root root 5156 Nov 29 02:21 en.sh
-rwx--x--x. 1 root root 5216 Nov 29 02:21 es.sh
-rwx------. 1 root root 5519 Nov 29 02:21 fr.sh
-rwx--x--x. 1 root root 5232 Nov 29 02:21 it.sh
-rwx--x--x. 1 root root 5330 Nov 29 02:21 pl.sh
-rwx------. 1 root root 5266 Nov 29 02:21 pt-br.sh
-rwx------. 1 root root 5163 Nov 29 02:21 ro.sh
-rwx--x--x. 1 root root 5324 Nov 29 02:21 sk.sh
-rwx------. 1 root root 5126 Nov 29 02:21 sl.sh
-rwx------. 1 root root 5122 Nov 29 02:21 tk.sh
-rwx------. 1 root root 5102 Nov 29 02:21 zh.sh
root@kali:~/fluxion#

**Comment by MPX4132** [comment]
Thank you for your quick reply, it looks good. Run the following and post the output here:

```
cd fluxion
readarray -t languageCodes < <(ls -1 language | sed -E 's/\.sh//')
for lang in "${languageCodes[@]}"
do echo $lang
done
```

**Comment by lightakun** [comment]
@MPX4132
heres the output

root@kali:~/fluxion# for lang in "${languageCodes[@]}"
> do echo $lang
> done
cs
de
el
en
es
fr
it
pl
pt-br
ro
sk
sl
tk
zh

**Comment by Hritik14** [comment]
@lightakun 
Please run 
` bash -x ./fluxion.sh &> /tmp/fluxion_debug <(echo 1);` as root and
wait 5 seconds then press `Ctrl+C`
and upload the contents of `/tmp/fluxion_debug` ?

**Comment by lightakun** [comment]
@Hritik14

@Hritik14

Heres the fluxion_debug file

https://drive.google.com/file/d/1dnHYvTdt5EDh9uOWnqex5JYFiySiWvv0/view?usp=drivesdk

(The output was very big so couldnt upload to any text hosting sites due to their text limits)

I used my wireless interface as wlan1(managed mode)

I ran the following code in root of the fluxion directory 
  Thanks for replying! :)

**Comment by Hritik14** [comment]
@lightakun I suppose something's wrong with the `printf` you are having. 
Please post the output of 
`printf '\t\e[1;31m[\e[1;33m%d\e[1;31m]\e[0m %s / %s\n' 1 cs $'\304\215e\305\241tina'`
(I suppose you'd get a blank line, which you shouldn't)
Also the output of
`man printf | tail -n1`

**Comment by lightakun** [comment]
@Hritik14

Heres the output :)

https://drive.google.com/file/d/1gpH4gBXlfrQp1eJfv5mlS1RD0pW3P5as/view?usp=drivesdk

(Screenshot :p)

**Comment by Hritik14** [comment]
@lightakun Weird. Please run these commands
```
script /tmp/fluxion_debug
bash -x ./fluxion.sh
```
press `Ctrl+C` when you get a prompt, wait for fluxion to quit then `exit` 
And upload the new `/tmp/fluxion_debug` file

**Comment by lightakun** [comment]
@Hritik14

Hes the output

root@kali:~/fluxion# script /tmp/fluxion_debug
Script started, file is /tmp/fluxion_debug
bash -x ./fluxion.shscript: failed to execute /su/bin/sush: No such file or directory
Script done, file is /tmp/fluxion_debug
root@kali:~/fluxion# 

Heres the fluxion_debug


Script started on 2017-11-29 19:15:09+0000
bash -x ./fluxion.shscript: failed to execute /su/bin/sush: No such file or directory

Script done on 2017-11-29 19:15:09+0000

**Comment by Hritik14** [comment]
@lightakun  Please run the commands exactly as they are. 
Make sure `fluxion.sh` is present in your directory.

**Comment by lightakun** [comment]
@Hritik14

Heres the output of
script /tmp/fluxion_debug
bash -x ./fluxion.sh

https://drive.google.com/file/d/1zqrhJmWFxgaG9vuyqiWH0H29gTiSJisG/view?usp=drivesdk

:)

**Comment by MPX4132** [comment]
@lightakun I can't seem to open that file you posted. Why is it so massive? It should only be a few hundred bytes. By the way, you can use https://pastebin.com to post text, and you can use imgur.com to post images. Those are the more standard way of doing it, and if you need to upload a file, just drag it into you message here and I'll allow you to upload it.

**Comment by MPX4132** [comment]
@lightakun Please run the following and post the output:
```
cd fluxion
readarray -t languageCodes < <(ls -1 language | sed -E 's/\.sh//')
__io_query_format_fields__record_count=${#languageCodes[@]}
__io_query_format_fields__indexes=($(seq $__io_query_format_fields__record_count))
for n in "${__io_query_format_fields__indexes[@]}"; do
echo $n
done
```
You should get a list of numbers, 1 - 14.

**Comment by lightakun** [comment]
@MPX4132
heres the output :)

https://pastebin.com/DbGkKhz6

**Comment by MPX4132** [comment]
Try running it again all in one line like this, just copy, paste it, and run it:
```
cd fluxion; readarray -t languageCodes < <(ls -1 language | sed -E 's/\.sh//'); __io_query_format_fields__record_count=${#languageCodes[@]}; __io_query_format_fields__indexes=($(seq $__io_query_format_fields__record_count)); for n in "${__io_query_format_fields__indexes[@]}"; do echo $n; done
```

**Comment by lightakun** [comment]
@MPX4132

Heres the output :)

https://pastebin.com/q2GvBbXe

Now i can see numbers :)

**Comment by MPX4132** [comment]
Damn, then the problem is with something else. Give me some time to figure something else out, I'm working on fixing something that was requested over three months ago.

**Comment by lightakun** [comment]
@MPX4132
okay no problemo :)

**Comment by deltaxflux** [comment]
@MPX4132 solved now?

**Comment by lightakun** [comment]
@deltaxflux
No ! Nt yet!
Waiting fr u to bring a fix to this :)

**Comment by lightakun** [comment]
@deltaxflux
Heres the output of
env and tput cols if needed

https://pastebin.com/7n7UG6UU

**Comment by MPX4132** [comment]
@deltaxflux Na, we're still trying to work it out. It's probably something stupid, like that one problem we had a while ago where `awk` was linking to either `gawk` or `mawk`, which didn't support all the flags we were using.

**Comment by deltaxflux** [comment]
Yep this could be the case. I removed all SS because they share sensitive data. However it would be great if you can check also the SS. His wifi was already captured and inside the wigle database so he was pwned. However I will add a disclaimer inside the issue template.

**Comment by lightakun** [comment]
@MPX4132
@deltaxflux 
Any solution? :relieved:

**Comment by MPX4132** [comment]
@deltaxflux , I must've missed it. I've been removing info that could lead to doxxing when people post it here, whoops.

**Comment by MPX4132** [comment]
@lightakun I'll take a look at it tomorrow, I really need to sleep now. It's already morning and I haven't slept, it's a bad habit.

**Comment by lightakun** [comment]
@MPX4132
go to.bed right now. Yes bad habit .
Sleep well :)

**Comment by deltaxflux** [comment]
I think it is clearly a missconfiguration of you OS. I does work for me on my nethunter device and on my other OS. I can't reproduce the bug even if I run it on my nethunter device.
