### ISSUE TITLE
Captative Portal not working with Alfa AWUS036ACH (new supported in Kali). 

### ISSUE THREAD

**Issue by darkarp** [FluxionNetwork/fluxion#272]
### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
*fluxion stucks at creating AP*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Captative Portal with pre-collected handshake. Stuck at starting the AP. Nothing else shows after (waited 1 hour every try)

#### What do you think the expected behaviour should be?
To create the AP

### OUTPUT

root@kali:~/fluxion# ./scripts/diagnostics.sh wlan0

./scripts/diagnostics.sh: line 3: ../lib/InterfaceUtils.sh: No such file or directory
[ FLUXION Info ]
FLUXION V3.4

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
./scripts/diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./scripts/diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./scripts/diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.13-1kali1 (2017-11-17)

### Possible Solution

I saw that airmon-ng is used by the program but airmon-ng doesn't work with this chipset. The only way to put it in monitor mode is "ifconfig wlan0 down; iwconfig wlan0 mode monitor; ifconfig wlan0 up"

**Comment by MPX4132** [comment]
Download the latest version and try running it again. Someone broke the diagnostics script and you ran the broken version.
