### ISSUE TITLE
Fluxion won't catch any handshake.

### ISSUE THREAD

**Issue by ProsAnon** [FluxionNetwork/fluxion#279]
I am stuck here, it's my own wi-fi and i tried to crack it via fluxion, i got till the handshake screen, and no handshake caught. I used the first option, not the mdk3.
I also try to connect with my phone but it's not connecting,and i get no handshake. 
Am i doing something wrong? 
Sorry for bad english, not my main language.
I attach a SS.

**Comment by SecureThisShit** [comment]
Could be a driver Problem there. I had problems with the Alfa Cantennas (Ralink). You have no Clients shown, that was my problem as well.

With a TP-Link Cantenna i get to see Clients again, can also capture a Handshake. But Pyrit and also Aircrack cannot verify this handshake. In the deltaflux Version this worked for me.

![grafik](https://user-images.githubusercontent.com/27858067/33446666-10fb5fb0-d601-11e7-9713-6b1e5a1965f4.png)

**Comment by MPX4132** [comment]
Update date to the latest version and try again. Also, you’re using a passive method of attack. You can only get a handshake if you, or someone else in your network, connects to the access point while he attack is occurring.

**Comment by ProsAnon** [comment]
Sorry I know I'm gonna be a headache. I am kinda new in those things. Don't want to waste your time, but I think this is the latest version.
And I should get a handshake when I try to connect(For testing this) right? but I cannot connect my phone because of the deauth's, right?

Thank you very much for replying.

**Comment by MPX4132** [comment]
Don’t worry about bothering me, I’m good.

Yeah, you need to get a handshake file. You need to run the `Handshake Snooper` attack first, but I need to fix a bug I introduced earlier. Give me about 30 minutes to fix it and verify the fix, then download the latest version directly from the repository. Don’t download the release, just click the clone button on the repo and download the zip, if you don’t want to use the clone command.

After you have the handshake captured, you do the `Captive Portal` attack.

**Comment by ProsAnon** [comment]
Ok I'll wait. You know I just switched the computers because on my other one it worked, untill the FakeAP. I mean that part when it starts to make the clients to connect to the fake page. It looks like the other computer's network adapter does not support this thing.

**Comment by MPX4132** [comment]
@ProsAnon Hey, you're running a REALLY outdated version of the script. It's version 2, and we're already at version 3.5. Download it directly from the repo with this:
```
git clone --recursive https://github.com/FluxionNetwork/fluxion.git
```
Then try running the attack.

**Comment by ProsAnon** [comment]
Hey, yeah I was very outdated :D. I tried the atack with wlan0 but it's the same..I get no handshake even my phone reconnects several times.

Am I doing something wrong?

**Comment by MPX4132** [comment]
I need more information to figure it out. What options did you choose in fluxion? Also, run the diagnostics script:
```
cd fluxion # Go to fluxion's root directory (top most directory)
./scripts/diagnostics.sh wlan0
```

**Comment by MPX4132** [comment]
@ProsAnon There was another bug with the script, redownload the latest version and try again.

**Comment by ProsAnon** [comment]
@MPX4132  I downloaded from the command you wrote. It's the same thing, my phone connects and disconnects several times but I don't get the handshake.

I'll post the diagnostics :
root@kali:~/Desktop/fluxion# ./scripts/diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.5


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy0
Driver: b43
Chipset: 
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)
root@kali:~/Desktop/fluxion# 

Thank you.

**Comment by MPX4132** [comment]
@ProsAnon You need to tell me exactly what you tried, I don't know what you did and haven't done yet. What options did you pick after executing fluxion.

**Comment by ProsAnon** [comment]
Photos here.
![screenshot from screencast_12-01-2017_02 58 20 am webm](https://user-images.githubusercontent.com/33962128/33473410-5e7656c6-d644-11e7-898d-a73e63148e56.png)
![screenshot from screencast_12-01-2017_02 58 20 am webm - 1](https://user-images.githubusercontent.com/33962128/33473411-5e9e78ea-d644-11e7-86b0-c4a28ef9a499.png)
![screenshot from screencast_12-01-2017_02 58 20 am webm - 2](https://user-images.githubusercontent.com/33962128/33473412-5ebede00-d644-11e7-8fb5-6fa0ec625514.png)
![screenshot from screencast_12-01-2017_02 58 20 am webm - 3](https://user-images.githubusercontent.com/33962128/33473413-5edcbd30-d644-11e7-91c7-ca860abb26ee.png)
![screenshot from screencast_12-01-2017_02 58 20 am webm - 4](https://user-images.githubusercontent.com/33962128/33473414-5efb5ab0-d644-11e7-8b11-9b97cc16a4b2.png)
![screenshot from screencast_12-01-2017_02 58 20 am webm - 5](https://user-images.githubusercontent.com/33962128/33473415-5f1bb8be-d644-11e7-8bc7-1a0ec6a55025.png)
![screenshot from screencast_12-01-2017_02 58 20 am webm - 6](https://user-images.githubusercontent.com/33962128/33473416-5f3afd8c-d644-11e7-9572-49a0922703b3.png)
![screenshot from screencast_12-01-2017_02 58 20 am webm - 7](https://user-images.githubusercontent.com/33962128/33473417-5f72a386-d644-11e7-8f49-cf0659abc127.png)

**Comment by MPX4132** [comment]
Try running it exactly like you have it but choose "Every 30 seconds..." and "Synchronous."  I think I need to change the values of the deauthenicator, since I think it's attacking before the device has a chance to reconnect properly, but try what I said anyway.

**Comment by ProsAnon** [comment]
I did what you said. I downloaded from "git clone https://github.com/FluxionNetwork/fluxion.git"
Same thing. My phone disconnects and reconnects several times, what was different this time is that the Handshake Captor windows dissapeared for few seconds but it got no handshake. It happened once "wlan0 network is down" or something like that.

**Comment by MPX4132** [comment]
I don't think the problem is with fluxion, I found [this article](https://null-byte.wonderhowto.com/how-to/fix-network-is-down-airodump-ng-0166996/), I suggest you take a look.

**Comment by ProsAnon** [comment]
I don't get that kind of message. You know there in the box of Handshake monitor windows where the handshake should appear I get sometimes not everytime [wlan0 is down] then it's closing and opens again and works but no handshake.
I forgot to tell you that I used this way on another computer and it worked untill the evil twin page(it does not support AP because it's an old laptop) so I switched to a better one.

**Comment by MPX4132** [comment]
@ProsAnon If I remember correctly, "wlan0 is down" message means that either something snatched the interface, like another processes (network-manager maybe?), or that the target access point changed channels and you're no longer capturing anything because the target AP moved to another channel. 

You can PM me via email, which you can find in fluxion's log:
```
cd fluxion
git log
```

What do you mean by "dumped the network," what exactly did you do/run?

**Comment by ProsAnon** [comment]
Sorry I said english is not my main language, by "dumping" i meant monitoring, i used airodump-ng but I don't see any clients connected(I and my friend were connected at that time).

I'll PM you about something,thank you !

**Comment by ProsAnon** [comment]
I have not solved this issue...can you help me please?

2017-12-02 10:39 GMT+02:00 deltax <notifications@github.com>:

**Comment by ProsAnon** [comment]
OK I understood that my driver may be the problem, or the network adapter.

One more thing, can anyone recommand me a goot USB Wireless adapter compatible with this things? Thank you.

**Comment by MPX4132** [comment]
I've been using the `AWUS036NHA` to develop fluxion. You don't necessarily need that one. I suggest you get any device that uses the `ath9k_htc` driver. It's the driver the `AWUS036NHA` uses, and that's what's important. I've also had success with the `ath9k` driver. Those two work flawlessly.

**Comment by MPX4132** [comment]
@ProsAnon Check the latest commit, it might work.

**Comment by ProsAnon** [comment]
I cloned the latest version, and at the stage where it sends deauths and the snooper window, should be the handshake captor window too, but it does not appear. It works fine, disconnects my device(phone) then it reconnects itself but still no handshake.

I was asking if my laptop's wireless adapter and driver are compatible with this kind of operation, just to know if it's not then we must not lose our time, if you can recommand me a good USB Wireless adapter(in case my adapter is not good).

**Comment by MPX4132** [comment]
@ProsAnon The captor window will no longer appear, I removed it to fix a bug. It now runs in the background. Try running the attack synchronously with an interval of 60 seconds. About the adapter, the one I mentioned above is the one I use.

**Comment by ProsAnon** [comment]
Nothing happens.
I use aireplay options, is it ok?

![screenshot from 2017-12-02 13-56-43](https://user-images.githubusercontent.com/33962128/33515267-8c101416-d769-11e7-91c4-5f9014caba23.png)

**Comment by MPX4132** [comment]
Yeah, it looks fine... that’s weird, it looks perfectly fine, but it doesn’t pick anything up. I’ll check it out later on today, I gotta sleep.

**Comment by ProsAnon** [comment]
Thank you. I'll be online the next 12 hours

**Comment by MPX4132** [comment]
On the plus side, I think I found a bug with your help related to using two different cards, but I think it only affects the `Captive Portal` attack. It has to do with not setting the channels properly on the deauthenticator.

**Comment by ProsAnon** [comment]
I'm glad if you can fix that one, but I'll be grateful if the problem with handshake will be solved too :D

**Comment by SecureThisShit** [comment]
@ProsAnon for Raspberry Pi i recommend TP-Link-TL-WN722N.

I could not see Clients with the Alfa cantennas because of Driver problems.

**Comment by deltaxflux** [comment]
My alfa cards work fine and I can't confirm any driver issues.

**Comment by seventhplug** [comment]
I have wn722n and awus036nh i like wn722 (atheros) because it can detect more AP than my  awus036nh (ralink)

**Comment by MPX4132** [comment]
@seventhplug The `AWUS036NH` is incompatible with fluxion due to its bad driver. It doesn’t support virtual interfaces and you mentioned it has trouble with injection. The `AWUS036NHA` works completely fine, I use it for testing, but it uses the `ath9k_htc` driver.

**Comment by SecureThisShit** [comment]
If its really a driver problem try apt-get install firmware-atheros && apt-get install firmware-misc-nonfree. Helped for me today i can see the clients again with AWSUS051NH v2 (rtl3,5k chipset driver is added there).

**Comment by ProsAnon** [comment]
Hello. @SecureThisShit I tried  " apt-get install firmware-atheros && apt-get install firmware-misc-nonfree" but nothing happened. Still can't catch any handshake.
I just recieved my Raspberry Pi 3 model B today but I cannot configure it only tonight.

**Comment by MPX4132** [comment]
@ProsAnon What's the model of the wireless device you have? You posted some info above, which shows it's using the `b43` driver. If I remember correctly, that driver is not good.

**Comment by ProsAnon** [comment]
This is the diagnostics: 
" 
[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy0
Driver: b43
Chipset: 
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.13-1kali1 (2017-11-17)

"

So I need to get another network adapter?

**Comment by deltaxflux** [comment]
I agree with @MPX4132 optinion. The b43 broadcom driver is bad. The driver is obsolete and even if it support monitor mode like it is the case you maybe have problems with the master mode for the fake acess point. I strongly recommend that you use an external wireless card. If you want a cheap one I can recommend the TP-LINK TL-WN722N **V1**.

**Comment by deltaxflux** [comment]
Also here is a quick code to print out your supported modes:
`export n=$(iw list | grep "Supported interface modes:" -n | sed -e s'/:/ /'g | awk '{print $1}'); export s=$(iw list | grep "Band 1:" -n | sed -e s'/:/ /'g | awk '{print $1}'); iw list | head -n $(echo $(($n+$(echo $(($s-$n-1)))))) | tail -n $(echo $(($s-$n-1)))`

**Comment by ProsAnon** [comment]
Great, thank you very much for your help. I will post an update when I get the external wireless card.
Thank you again for your time. Respect

**Comment by josephmathewtony046** [comment]
in capture handshake it shows corrupter what would i do??????

**Comment by frog972** [comment]
Any better option than fluxion bcoz fluxion doesnot show login page

**Comment by darkhacknet** [comment]
Guys, Im faciing the same issue, but ....... there are a lot of devices connected to the vic wireless network ! So Im deauth all of them every 30 seconds. Adn no handshake is captured. that`s weird right ? 

By other side, I have captured a HS using wifite, and I tried to copy the HS to the HS folder located in fluxion. But fluxion cant detect it when I tried to launch the fake access point attack ! :/ so im totally stuck! any help will be really appreciate it ! 
Thanks in advance guys.

**Comment by cjb900** [comment]
@darkhacknet Posting to a closed issue from 5 years ago is not going to get anyone to help. Also not giving any information on your setup isn't helpful either. Please open a new issue use the issue template and then we can help or join our discord [here ](https://discordapp.com/invite/G43gptk) for more direct/faster help

**Comment by darkhacknet** [comment]
> @darkhacknet Posting to a closed issue from 5 years ago is not going to get anyone to help. Also not giving any information on your setup isn't helpful either. Please open a new issue use the issue template and then we can help or join our discord [here ](https://discordapp.com/invite/G43gptk) for more direct/faster help

OK thanks a lot..
