### ISSUE TITLE
Application Hung Up On "Starting Captive Portal access point service..."

### ISSUE THREAD

**Issue by Schneiderism** [FluxionNetwork/fluxion#285]
#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
Bible

#### What is the current behaviour?
In an attempt to use two different wireless devices in the attack, I went in and selected the AWUS036NH which supports injection as the initial scanning device (used to get a list of signals and get the handshake), and then chose the device that acts as a hotspot to use as the `Captive Portal` interface. Is this the correct process? When I ran with this procedure, it got hung up on `Starting Captive Portal access point service...`. However, I'm wondering if it's because the `Captive Portal` is being hosted on an internal wireless card. This card can act as a wireless hotspot though, so I know it's capable of acting as an access point

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Select the English language, scan for signals using the AWUS036NH device, select one, use the program to obtain that signals handshake, and then use the internal wireless card to act as the `Captive Portal`. 

#### What do you think the expected behaviour should be?
Application should start up, using the AWUS036NH for deauth packets, and the internal wireless card as the `Captive Portal`. Allegedly you can use two different devices instead of one that supports virtual interfaces. See [Issue #33](https://github.com/wi-fi-analyzer/fluxion/issues/33 "Issue #33 Page")

#### If this is a feature request, what is the motivation or use case for the added feature?
N/A

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
**AWUS036NH**
```
[ FLUXION Info ]
FLUXION V3.5


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy1
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Injection Test: Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)
```

**Internal WiFi Card**
```
[ FLUXION Info ]
FLUXION V3.5


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy0
Driver: iwlwifi
Chipset: Intel Corporation Wireless 7265 (rev 59)
Injection Test: ioctl(SIOCSIFFLAGS) failed: Operation not possible due to RF-kill
failed


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)
```

**Comment by MPX4132** [comment]
Yeah, it should work, however, it seems something went wrong with the internal card, some process might've snatched it:
> ```
> [ Interface (wlan0) Info ]
> Device: phy0
> Driver: iwlwifi
> Chipset: Intel Corporation Wireless 7265 (rev 59)
> Injection Test: ioctl(SIOCSIFFLAGS) failed: Operation not possible due to RF-kill failed
> ```

I understand you're using that card to host the rogue AP, but it seems it's soft blocked or something.
Make sure nothing's trying to snatch the card away. If you're on Kali or Debian derivatives, like it seems, take down `network-manager` or `wpa_supplicant` for a bit:
```
# This one's for network-manager
systemctl stop network-manager.service
``` 
Then try out fluxion again. You can bring `network-manager` back up with:
```
systemctl start network-manager.service
```

**Comment by Schneiderism** [comment]
Thank you for the quick reply. I'll give it a shot and report back what happens tomorrow.

**Comment by MPX4132** [comment]
Well, I don't think that's normal behavior, but I certainly don't have experience with the issue, so I'm not sure. It seems like a soft block, meaning you might have the internal wifi off with a physical switch on the computer. It also seems like a process is interfering with fluxion and stealing the interface, but I can't help you with that. I've never even seen this (`iwlwifi`) driver, so it could also be a driver issue, but it's probably more unlikely since you're using two devices so it's not a problem with virtual interfaces.

**Comment by Schneiderism** [comment]
Alright thank you. It's just an internal wireless card on an ASUS laptop. I'll see what happens with the network-manager being killed. Thank you again for your help.

**Comment by MPX4132** [comment]
Hey, I read your driver is in fact supported, the `rt2800usb`, meaning something else is the problem. You might wanna look into it.
