### ISSUE TITLE
Problems "Starting Captive Portal access point service..."

### ISSUE THREAD

**Issue by troha2** [FluxionNetwork/fluxion#287]
#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
after inject the data and capture the handshake, hung up on Starting Captive Portal access point service.... 

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Select the English language, scan for signals using the USB with chipset rtl8812au device, use the program to obtain that signals handshake, and then I use the same card to start the captive portal, I mean, my wlan0 used during the capture of the handshake.

#### What do you think the expected behaviour should be?
N/A

#### If this is a feature request, what is the motivation or use case for the added feature?
N/A 

#### Specs
Windows 10 x64, vmware 14.0.0, USB with chipset rtl8812au, kali linux 2017.3
Might be I'm doing something wrong, but I need to ask anyway.:/

<code>root@kali:~/fluxion/scripts# ./diagnostics.sh wlan0

./diagnostics.sh: line 3: lib/InterfaceUtils.sh: No such file or directory
[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
./diagnostics.sh: line 20: interface_physical: command not found
Device: Unknown
./diagnostics.sh: line 25: interface_driver: command not found
Driver: Unsupported
./diagnostics.sh: line 30: interface_chipset: command not found
Chipset: Unknown
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]
  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.13-1kali1 (2017-11-17)</code>

**Comment by MPX4132** [comment]
Run the diagnostics script from root:
```
cd fluxion
./scripts/diagnostics.sh wlan0
```

I think your problem is with your driver, the `rtl8812au` probably doesn’t support virtual interfaces.

**Comment by MPX4132** [comment]
This is definitely a driver problem, check [these out](https://github.com/FluxionNetwork/fluxion/issues?utf8=✓&q=rtl8812au+in%3Abody).
