### ISSUE TITLE
error on dhcpd.leases

### ISSUE THREAD

**Issue by drjohannspector** [FluxionNetwork/fluxion#290]
Here is what I see every time when running captive portal. I currently am using
Bus 001 Device 003: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter

Here is the output on xterm as well as executing dhcpd. Could this be why my AP sits at starting service?

FLUXION AP DHCP Service
Internet Systems Consortium DHCP Service 4.3.5
Copyright 2004-2016 Internet Systems Consortium
All rights reserved.
For info, please visit https://isc.org/software/dhcp
Config file:   /tmp/fluxspace/dhcpd.conf
Database file: /temp/fluxspace/dhcpd.leases
PID file: /var/run/dhcpd.pid
Wrote 0 leases to leases file.
Listening on LPF/FXan0AP/10:0d:7f:e5:ce:3a/192.168.254.0/24
Sending on   LPF/FXan0AP/10:0d:7f:e5:ce:3a/192.168.254.0/24
Sending on   Socket/fallback/fallback-net
Server starting service.

FLUXION AP Service [hostapd]
Configuration file: /tmp/fluxspace/10:0d:7f:e5:ce:3a-hostapd.conf
Using interface FXan0AP with hwaddr 10:0d:7f:e5:ce:3a and ssid "XXXXX"
FXan0AP: interface state UNINITIALIZED->ENABLED
FXan0AP: AP-ENABLED

root@kali:~# dhcpd
Internet Systems Consortium DHCP Server 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /etc/dhcp/dhcpd.conf
Database file: /var/lib/dhcp/dhcpd.leases
PID file: /var/run/dhcpd.pid
Can't open lease database /var/lib/dhcp/dhcpd.leases: No such file or directory --
  check for failed database rewrite attempt!
Please read the dhcpd.leases manual page if you
don't know what to do about this.

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.

**Comment by drjohannspector** [comment]
I just installed DHCP 4.3.6. See what happens. Downloaded from isc.org
ran ./configure && make

**Comment by MPX4132** [comment]
Looks like the process was already running and that’s why it failed to start. Try rebooting the machine, run it again like you did with those logs, and see if you get the same error.
