### ISSUE TITLE
Stuck on "Starting Captive Portal"

### ISSUE THREAD

**Issue by underscrew** [FluxionNetwork/fluxion#291]
#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
I am getting stuck on `[*] Starting Captive Portal access point service...`.
It only happened with this last version.
I don't have a clue on what it may be.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Start Captive Portal attack.

#### What do you think the expected behaviour should be?
Open normally.

#### Specs

which pgrep
/usr/bin/pgrep

./scripts/diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.6

[ BASH Info ]
GNU bash, version 4.4.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy0
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2070
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.9.0-kali3-amd64 (devel@kali.org) (gcc version 6.3.0 20170321 (Debian 6.3.0-11) ) #1 SMP Debian 4.9.18-1kali1 (2017-04-04)

-----

**Comment by MPX4132** [comment]
You need to post what the issue template requests.

**Comment by underscrew** [comment]
@MPX4132 updated.

**Comment by MPX4132** [comment]
@underscrew Thanks man, but can you please re-run it like this:
```
cd fluxion # It MUST be executed from root.
./scripts/diagnostics.sh wlan0
```

**Comment by MPX4132** [comment]
Also, please post the output of the following:
```
which pgrep
``

**Comment by MPX4132** [comment]
I updated fluxion just now, you no longer need to run it from root if you don't want to. Too many people keep ignoring that, so I had to rewrite it.

**Comment by underscrew** [comment]
Updated what you asked. @MPX4132

**Comment by MPX4132** [comment]
@deltaxflux you created [this issue](https://github.com/FluxionNetwork/fluxion/issues/93) a while back, and stated you have a device that uses the `rt2800usb` driver, do you mind checking if it still works with the latest version? It seems @underscrew is having issues I'd like to make sure we haven't broken something, or that we've created a compatibility issue. Nothing should have broken, I don't think I messed with the interface creation, but I did update the AP services lib script.

**Comment by MPX4132** [comment]
@underscrew Thanks for updating the information. You mentioned you've used the script before, have been using `hostapd`, or `airbase-ng`?

**Comment by deltaxflux** [comment]
It does work me now and I can't reproduce it. Looks like he has serios driver or enviroment problems. The issue was only a reminder for me that I don't foget it. However this problem is in my opinion solved.

**Comment by drjohannspector** [comment]
This is the same driver I am having issues with. I have a AWS051NH on order, not sure if that's going to work. Currently I am having using the AWS036NEH (not NE) . I have never got past "server starting service" on the DHCP xterm window. Not 100% sure new wifi adapter supports master mode, or what drivers. I should have done more research. Anyone have any input? I ran the fakeap and checked iwconfig:

wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          
FXan1AP   IEEE 802.11  Mode:Master  Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off
          
lo        no wireless extensions.

wlan1     IEEE 802.11  Mode:Monitor  Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off



http://www.alfa.com.tw/products_show.php?pc=34&ps=22

**Comment by MPX4132** [comment]
@deltaxflux Yeah, I think so too. I think the problem isn't the hardware, or the driver, it might just be something interfering with the interface... Maybe fluxion should rename the interface so that it stops being snatched. Now that I think of it, that might be why `airmon-ng` does that.

**Comment by underscrew** [comment]
I used `hostapd`.

**Comment by MPX4132** [comment]
Try running fluxion with the `airmon-ng` flag:
```
export FLUXIONAirmonNG=1
./fluxion.sh
```
Check if the issue continues.

**Comment by deltaxflux** [comment]
Or maybe try to disable the NetworkManager and bring your network card in mointor mode manually at the beginning .

**Comment by MPX4132** [comment]
The bit of code I wrote for interfaces disables all monitor mode interfaces it detects before even showing the user the list. That's done to start "clean" for fluxion's interface selector.

But I definitely agree they should try to disable network manager.

The reason I'm asking people to try using the `airmon-ng` flag is to verify whether or not it's a problem with the interface identifier.

 I think it's a problem because network-manger could attempt to take control of the interface if the interface identifier stays the same. If we have them check with `airmon-ng` (which renames the interfaces) and they get it working, it means the identifier could be the reason they're having issues. It would signify network-manager might be trying to control the interface at the same time fluxion is. From recent experience, it seems network-manager ignores interfaces which haven't been used to connect to a network. I think airmon-ng might be getting around those issues by renaming the interface.

**Comment by deltaxflux** [comment]
> it seems network-manager ignores interfaces which haven't been used to  connect to a network. I think airmon-ng might be getting around those  issues by renaming the interface.

Yeah this is true but I have never had problems with the network manager. For me it works flaweless lets see what @underscrew report.

**Comment by underscrew** [comment]
I ran` export FLUXIONAirmonNG=1` with no luck.
Disabled the network manager as well.

But I got something weird. 
It is working with other AP, but not with this one I tried before.
Handshake is ok with both verifiaction methods.

**Comment by MPX4132** [comment]
Can you explain what you meant above? What do you mean it’s working with other APs, but not the one you tried before?

Also, try to disable both, network-manager and wpa_supplicant if it’s running, then launch fluxion:
```
systemctl stop network-manager.service
systemctl stop wpa_supplicant.service
cd fluxion # go to fluxion root
./fluxion.sh
```

**Comment by deltaxflux** [comment]
Well please post the output from:

```
Ind1="$(iw list | grep "Band" -n | awk '{print $1}' | tr -d :)"
Ind2="$(iw list | grep "Supported interface modes" -n | awk '{print $1}' | tr -d :)"
iw list | head -n $(echo $(($Ind1-1))) | tail -n $(echo $(($Ind1-$Ind2-1)))
```
It will print the supported interface modes.

**Comment by MPX4132** [comment]
Closed due to failure to respond.

**Comment by zenos** [comment]
![screenshot 14h 55m 35s](https://user-images.githubusercontent.com/761973/35442902-32a50056-02a9-11e8-8257-60d4f59ef552.jpg)
how to resolve the issue with captive portal please

**Comment by MPX4132** [comment]
@zenos That’s usually caused by a problem with your wireless driver.

**Comment by zenos** [comment]
so do updating wirless driver can fix this? ,i have Realtek RTL8187 Wireless 802.11b/g 54Mbps USB 2.0 Network Adapte

**Comment by rad4day** [comment]
Well https://wikidevi.com/wiki/Rtl8187#Limitations_.2F_unimplemented_functionality_NOS says that the RTL8187 does NOT support master mode, and therefore can't host an Access Point. But I'm unsure if this information is outdated.

**Comment by underscrew** [comment]
@deltaxflux 
Sorry for the late response.

> Ind1="$(iw list | grep "Band" -n | awk '{print $1}' | tr -d :)"
empty output 
>Ind2="$(iw list | grep "Supported interface modes" -n | awk '{print $1}' | tr -d :)"
>iw list | head -n $(echo $(($Ind1-1))) | tail -n $(echo $(($Ind1-$Ind2-1)))
```
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * WDS
		 * monitor
		 * mesh point
```

I am still getting it on newer versions. It just happens to an specific AP. Very strange...

**Comment by Pinkhax** [comment]
Can you hell me with

[*] success, hash verification completed!
[*] Starting Captive Portal access point service....

It stuck right there.

**Comment by usama7628674** [comment]
@Pinkhax Please post the output of diagnostic script.

**Comment by deltaxflux** [comment]
Yeah and please open a new issue.
