### ISSUE TITLE
Add client MAC information to netlog

### ISSUE THREAD

**Issue by doyler** [FluxionNetwork/fluxion#297]
-----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Feature*

#### What is the current behaviour?
Fluxion logs SSID, BSSID, Channel, Security, Time, and Password to the netlog upon success.

#### What do you think the expected behaviour should be?
Fluxion should also include the client MAC for the device that provided the correct password.

#### If this is a feature request, what is the motivation or use case for the added feature?
For actual penetration tests/similar work, the tester or client could provide more direct training or information to the phishing victims. Additionally, it would allow network administrators to see who is/isn't providing credentials.

-----

**Comment by deltaxflux** [comment]
I agree with you. We should include this is a later version. It is not an essential bug therefore the priority is low. I hope you could understand that. In addition all pull requests are welcome.

```
<?PHP

// -----------------------
// Maintainer: Deltax
// Date: 08.12
// -----------------------

function getUserIP()
{
    $CLIENT  = @$_SERVER['HTTP_CLIENT_IP'];
    $FORWARD = @$_SERVER['HTTP_X_FORWARDED_FOR'];
    $REMOTE  = $_SERVER['REMOTE_ADDR'];

    if(filter_var($client, FILTER_VALIDATE_IP))
    {
        $IP = $CLIENT;
    }
    elseif(filter_var($FORWARD, FILTER_VALIDATE_IP))
    {
        $IP = $FORWARD;
    }
    else
    {
        $IP = $REMOTE;
    }

    return $IP;
}


$USER_IP = getUserIP();

echo $USER_IP;

?>
```

So what the script does is to get the ip  from the request. We could now search in the dhcp logs which ip does match and get the mac + some other information.

**Comment by MPX4132** [comment]
@deltaxflux I was about to complain that might not be possible, but that's a pretty good idea you have.

**Comment by deltaxflux** [comment]
I revert the commits because it broke the handshake check. I will work on the developer branch and I hope that it work till tommorrow evening.

**Comment by usagijim** [comment]
Hello Doyler, I was checking out your pyDHCPDiscover script and wanted to leave you a message on your doyler.net page but I'm getting a 'ERROR: si-captcha.php plugin: GD image support not detected in PHP!' message and so I can't submit any comments.
I'm fairly new to python but wanted to learn more through your script but when I run it I get an error message:
    transactionID += struct.pack('!B', t)
TypeError: must be str, not bytes

I was wondering if you could give a newb some pointers on how to get around the error.  Thanks
