### ISSUE TITLE
Raspberry Pi 3 model B 

### ISSUE THREAD

**Issue by ProsAnon** [FluxionNetwork/fluxion#298]
I started fluxion on my Raspberry Pi 3 Model B and I got this message when I choose wich channels to scan.

EDIT: 
I just tried with airmon-ng and airodump-ng and I got the handshake, but I cannot use it with Fluxion because I cannot scan the networks.

EDIT2:
Sorry..
The message was: Your wireless card may not be supported(No APs found) or something like this.

**Comment by MPX4132** [comment]
You didn't post the message you mentioned fluxion showed you.

**Comment by ProsAnon** [comment]
Updated. Sorry again.

**Comment by MPX4132** [comment]
You're saying it works with airmon-ng and airodump-ng, but not with fluxion, correct?

**Comment by ProsAnon** [comment]
Yes. So I successfully scanned the networks with airodump-ng, successfully captured a handshake(*.cap file right?) but I cannot use it with fluxion(I cannot go further than network scanning).

**Comment by MPX4132** [comment]
When the scanner starts, can you see any networks?

**Comment by ProsAnon** [comment]
No, I choose to scan All channels(2.4GHz & 5GHz) thena windows pops up but closes imediatly, then I get the message: "Wireless card may not be supported (no APs found).
The choices are [1]Back and [2] Exit

**Comment by MPX4132** [comment]
Please run the diagnostics script and post the results.
```
cd fluxion
./scripts/diagnostics.sh wlanX  # replace wlanX with your wireless interface identifier

**Comment by ProsAnon** [comment]
Yes.

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy0
Driver: brcmfmac
Chipset: Unknown chipset for SDIO device.
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
ioctl(SIOCSIWMODE) failed: Device or resource busy
failed


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.9.59-v7_Re4son-Kali-Pi+ (root@builder) (gcc version 4.9.4 (Linaro GCC 4.9-2017.01) ) #1 SMP Tue Nov 21 00:36:47 CST 2017
root@kali:~/Desktop/fluxion#

**Comment by MPX4132** [comment]
Try running fluxion with the `airmon-ng` flag, and check if it works:
```
export FLUXIONAirmonNG=1
./fluxion.sh
```

**Comment by ProsAnon** [comment]
I typed that command, should something appear or it continues normaly?
Nothing happened,same message.

**Comment by MPX4132** [comment]
Well, it should continue normally as if you ran fluxion. You can run it all in one line if you add a command delimiter (a semicolon), like this:
```
export FLUXIONAirmonNG=1; ./fluxion.sh
```
It should execute regularly, you shouldn't notice any difference, except that this time it should work properly.

You found a bug with the language you were using before?

**Comment by ProsAnon** [comment]
I used english, then I used Romanian, it has worked with Romanian.
I updated my last comment, can you check that out?

**Comment by MPX4132** [comment]
I’ll look into the issue in a couple of hours, I need to sleep right now, I’m really sleepy, sorry to make you wait.

Post some images of the error you got if you can, otherwise, post the output text of where you got that error. I’ll check it out later on today.

**Comment by ProsAnon** [comment]
So here are some photos:

![1img_20171209_144629](https://user-images.githubusercontent.com/33962128/33796103-dd889808-dcf6-11e7-837b-234a9d1b2ef6.jpg)
![img_20171209_144429](https://user-images.githubusercontent.com/33962128/33796104-dda87b0a-dcf6-11e7-9028-f49c978767ee.jpg)
![img_20171209_144536](https://user-images.githubusercontent.com/33962128/33796105-ddc6a0bc-dcf6-11e7-9b6d-58da02718076.jpg)
![img_20171209_144603](https://user-images.githubusercontent.com/33962128/33796106-dde7913c-dcf6-11e7-9e37-b81e37c2e0b8.jpg)


Then I get stuck here(happens nothing 34 minutes passed)
![3](https://user-images.githubusercontent.com/33962128/33796110-f5a5dd1a-dcf6-11e7-95f1-6802deeae484.jpg)

**Comment by MPX4132** [comment]
You should not use the external access point option if you don’t know how to set it up.

**The external access point option requires you to have a dedicated access point device**, which you must manually configure according to what fluxion specifies. **It is not a USB device**, it’s a device that connects to the Ethernet port of your machine.

When you use that option, **fluxion isn’t responsible for generating the access point**, you’re the one responsible for generating the access point by configuring the dedicated access point device.

**Comment by MPX4132** [comment]
There’s definitely a problem when you select the wireless interface, though. We need to look into that. I noticed your wireless device is SDIO, that means it probabaly won’t be supported by fluxion because SDIO devices are always super limited in capabilities.

**Comment by MPX4132** [comment]
Yeah, [found the problem](https://raspberrypi.stackexchange.com/questions/44711/pi-3-wifi-with-airmon-ng). It doesn’t support master mode, or monitor mode, or both.

**Comment by drjohannspector** [comment]
I have also had some luck with the nexmon kernel for the onboard wifi. Just a quick heads up, saw the rpi post and those are my jam. Still doesn't support master mode though. Search for re4son if you want them.

**Comment by MPX4132** [comment]
@ProsAnon I’m gonna have to close the issue because it’s not a problem with fluxion, is a driver problem. I suggest looking into what @drjohannspector mentioned.

**Comment by M1z23R** [comment]
I've made fluxion based fluxion alternative :)
I hope it will help you.
https://github.com/M1z23R/FluxPi

**Comment by ProsAnon** [comment]
Thank you very much, I will try it tonight when I get home.

OFF-Topic:

Do you have some free time to help me with few answers? I am kinda new into
these things and my questions may seem stupid but I am really trying to
learn these things.

2017-12-14 7:52 GMT+02:00 M1z23R <notifications@github.com>:

**Comment by M1z23R** [comment]
Sure, to be honest i am new to bash scripting also, i guess it's a good thing know some other programming languages :D
Contact me here: dr.pentesting@gmail.com
