### ISSUE TITLE
pyrit breaks when checking saved handshake

### ISSUE THREAD

**Issue by tomasvanagas** [FluxionNetwork/fluxion#30]
### Which version of fluxion are you using?
This one.

### What distribution of Linux (including the version) are you running it on?
kali linux live 2017.1
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
ALFA AWUS036NHA

### Which is the driver for it?
No additional drivers installed

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Issues when trying to reuse saved handshake, fluxion says "Corrupted handshake".
I looked into deeper and it looks like pyrit is crashing when analyzing handshake.

+=================================================================+
When typed : apt install pyrit
pyrit is already the newest version (0.5.1+git20160815-0kali1).
+=================================================================+
When asked to analyze the handshake: 
root@kali:~/handshakes# pyrit -r FoxFi66-84\:8E\:DF\:A0\:5B\:52.cap analyze
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing file 'FoxFi66-84:8E:DF:A0:5B:52.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 467, in analyze
    parser = self._getParser(capturefile)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 183, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 699, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 588, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 26 captured bytes, only got 6
root@kali:~/handshakes# 
+=================================================================+
959. if [ "$handshakeloc" = "" ]; then
960.                         deauthforce
961.                 else
962.                        if [ -f "$handshakeloc" ]; then
963.                                pyrit -r "$handshakeloc" analyze &>$flux_output_device
964.                                pyrit_broken=$?
				       echo "$pyrit_broken"  <------------------------------------------+
965.                                                                                                                           
966.                                if [ $pyrit_broken = 0 ]; then                                               
967.                                Host_SSID_loc=$(pyrit -r "$hand                                       
                                                                                                                                  
Added this line to get "pyrit_broken" variable value,    ------------------------------------+
and result is "1".
+=================================================================+

Anybody has this issue as well?
Thank you very much.

**Comment by tomasvanagas** [comment]
Everythings working on normaly installed kali, probably pyrit's dependences weren't up to date and needed dist-upgrade.

**Comment by deltaxflux** [comment]
Simular bug exist. Kali team already fixed it.
https://bugs.kali.org/view.php?id=3785
