### ISSUE TITLE
AP changes channel

### ISSUE THREAD

**Issue by vv7v7** [FluxionNetwork/fluxion#300]
Dear Developer,

Is it possible to add feature to automatically restart fake ap on new channel when original ap changed it's channel ? It might be that there're a lot of new firmwares/routers which changes channel of an ap if same essid exists.

Best regards,
V7

**Comment by deltaxflux** [comment]
Duplicate issue

**Comment by MPX4132** [comment]
@vv7v7 The issue's logged in the Known Issues, in the Issues section.
