### ISSUE TITLE
Issue w/ mdk3 handshake snooper

### ISSUE THREAD

**Issue by drjohannspector** [FluxionNetwork/fluxion#302]
Something I noticed recently, while using the handshake snooper, I will typically see the xterm window that displays the bssid, mac addresses, etc of the client used in the handshake snooper, it seems to close for a brief moment, reopens itself and has to scan for connected clients for that AP once again, I see it running the deauth commands, that window closes with it and restarts about a second later. I noticed this only happens with mkd3 and I will often see "Operation failed, no valid hash was found" it appears in the window after snooping for 30 seconds, although it seems to continue on after the error, so I'm not sure it make a difference. 

The concerning thing for me is the automatic closing of 2 of the xterm windows while running handshake snooper on all the recommended settings.  

systemctl stop NetworkManager.service
systemctl stop wpa_supplicant.service
./fluxion.sh

That is all I use to run Fluxion. Again, I am not sure this is a bug, or just normal operation. I seem to be having difficulty with collecting a handshake the past couple days so perhaps this is related. I did however grab one on aireplay, I believe but when I went to use it in the captive portal, it told me there was an error with the hash and it would not proceed after selecting my .cap file.

**Comment by M1z23R** [comment]
That's normal, when you choose sync method the airodump and mdk3/aircrack-ng windows close so handshake snooper can check the file for valid handshakes, if no handshakes are found it removes temp .cap file and starts a new airodump-ng capture.
Simple words, it's normal, if you want you can try async method.

**Comment by deltaxflux** [comment]
You don't fill out our issue template please do this before posting.

**Comment by MPX4132** [comment]
@M1z23R Lol, it's refreshing as hell when someone gets it 100% spot on. Thank you for explaining it in detail to demystify it for other people.

@drjohannspector Like @M1z23R said, it's exactly what's supposed to happen (it's normal).

**Comment by deltaxflux** [comment]
Yeah this was my bot. The bot greps for the issue template template and if it is not found he does automatically post this.

**Comment by MPX4132** [comment]
@deltaxflux Oh sorry, I wasn’t trying to say you didn’t find the issue. I’m sure you would’ve found it if you had looked at it, but it’s like our rules say, no template, no service, so it’s understandable your bot closed the issue. I was just letting @M1z23R know he did a good job with the explanation he gave. It shows he understands exactly what fluxion is doing, and the majority of the people just don’t care about that.

**Comment by MPX4132** [comment]
Oh whoops, I accidentally reopened it. I’m closing it.

**Comment by deltaxflux** [comment]
@MPX4132 I maybe check for special words and redirect the user to our wiki. I'm not trying to be rule at all but I find it very difficult for me to answer most of these issues without a issue template.
