### ISSUE TITLE
Some ASCII characters in ESSID aren't supported.

### ISSUE THREAD

**Issue by M1z23R** [FluxionNetwork/fluxion#306]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?

Can’t receive a valid handshake.
#### If the current behaviour is a bug, please provide the steps to reproduce it.

Create an access point with name “‘-.-‘“ (no quotes)
#### What do you think the expected behaviour should be?

verifier blablabla  | grep used in the HashUtils fails to retrive it as valid because special chars are included in ssid name.

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
Not needed, but i use atheros ath9k.

-----

**Comment by mandelake** [comment]
Same here, for "**freebox_H&R**" (no quotes)

**Comment by deltaxflux** [comment]
I don't see any point why you should support special characters

**Comment by M1z23R** [comment]
Well it's not really our choice what name will someone have for AP. In my case it's my AP's ssid that's causing problems. I guess it's not that much work to add some export settings for such occasions.

**Comment by deltaxflux** [comment]
I know but it is for legal purposes only.

**Comment by MPX4132** [comment]
I think this is a significant issue, I’ll  try to fix it today.

**Comment by MPX4132** [comment]
I’ve added support for all the damn characters you can think of, knock yourself out. It was painstakingly teidious to debug, so I’m a bit irritated.

**Comment by M1z23R** [comment]
I believe it was pain in the a**, but thank a lot :)

**Comment by MPX4132** [comment]
@M1z23R sure thing man. It was definitely a pain there too, lol.
