### ISSUE TITLE
cat: /tmp/fluxspace/ip_hits: No such file or directory (issue persists)

### ISSUE THREAD

**Issue by drjohannspector** [FluxionNetwork/fluxion#307]
#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes

#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behaviour?
/tmp/fluxspace/ip_tables missing?

#### If the current behaviour is a bug, please provide the steps to reproduce it.
start captive portal, does not start. windows appear for a half second or so, then it hangs after giving me the error I posted below

#### What do you think the expected behaviour should be?
portal should start

(already posted ./diagnostics.sh in past issue that was closed. Noticed it is still giving me this error today. 

I am still seeing this when starting captive portal:

[fluxion@kali]-[~] 50
cat: /tmp/fluxspace/ip_hits: No such file or directory
[*] Starting Captive Portal access point service...

It hangs there and never opens any xterm windows.

**Comment by drjohannspector** [comment]
Fresh install of Kali, same issue. Captured handshake, start portal. Receive this message, started yesterday afternoon before the most recent update. apt-get update, apt-get upgrade and apt-get dist-upgrade all performed before installing fluxion.

**Comment by deltaxflux** [comment]
Hope it is resolved I pushed an older version thats we the problem was solved and exist later

**Comment by eliddell1** [comment]
is there a work around for this?  same issue

**Comment by deltaxflux** [comment]
Still there?

Update your fluxion to the latest version
`git pull -f`

**Comment by a578740694** [comment]
same question

**Comment by deltaxflux** [comment]
question?

**Comment by tom1t** [comment]
hi, i have the same problem. 
_cat: /tmp/fluxspace/ip_hits: No such file or directory_

fluxion has the latest version. 
Even a new installation does not solve the problem.

**Comment by perseo001** [comment]
i have the same 

cat: /tmp/fluxspace/ip_hits: No such file or directory 

kali linux 2017.3 i ve been following the issues also with the xterm terminal,

**Comment by MiniuBoo** [comment]
I have the same error.....

**Comment by eliddell1** [comment]
fluxion is already up to date..
This is just not working.. please prioritize

**Comment by x-x-x-x-x-x** [comment]
Made a Github acc just for this reason. Please, fix this issue soon or I will bombard small children with nuclear devices. Totally not a legitimate threat... unless you're a small child.

**Comment by signatroniker** [comment]
Kali and Fluxion are up-to-date here (git pull -f) and I got the same issue. Any workarounds? Anything to help solve this?

**Comment by drjohannspector** [comment]
Same issue, persists. I'm glad I'm not crazy....I figured this was a weird error to get all of a sudden, completely out of the blue. Zero system changes.

**Comment by eliddell1** [comment]
So i got it kind of working all of a sudden.. i think the only difference is i set it to "create ssl certificate" as before i was choosing "no ssl cert" and i had just tried using the non hostpad once first.. then went back to trying hostpad..  anyway, curious as to the debug window, just logging "file not found" over and over again..  wish i knew what file it was talking about..  see attached screenshot..

![screenshot from 2017-12-16 21-45-45](https://user-images.githubusercontent.com/3533916/34076156-c3217af2-e2aa-11e7-8671-72bf2dbc224e.png)

**Comment by eliddell1** [comment]
curious.. what wifi card are people using.. i have it working with TPLink TL-WN7221 thats on 2.4GHz on one kali machine, but still cant get it to work on my other machine  running same version of kali where im trying it on a 5GHz AP

**Comment by drjohannspector** [comment]
I see the same thing, "file not found", it literally crashes my machine. This is not a wifi card issue, I have multiple cards that all work with Fluxion that do not work any longer. 

5ghz and 2.4ghz all produce the same results. Whatever has happened, it rendered Fluxion useless until it is fixed.

**Comment by eliddell1** [comment]
hmm this is weird because it is working on one of my kali machines but not the other..  both running the latest version of kali and fluxion..  but even the working one complains about some file not being found..

**Comment by troha2** [comment]
I'd like to see some extra features, like in this script.;)
https://github.com/Vodker/wifimosys

**Comment by drjohannspector** [comment]
Same

**Comment by drjohannspector** [comment]
I see this now when I start captive portal, a few seconds after the AP starts, then another xterm window appears with scrolling "File not found" it is impossible to close and eats all my resources, have to reboot.


[*] Captive Portal attack in progress...

	[1] Select another attack
	[2] Exit

[fluxion@brickroad]-[~] _IceTrans_IceTransSocketUNIXConnect: Cannot connect to non-local host kali
SocketUNIXConnect: Cannot connect to non-local host kali
_IceTransSocketUNIXConnect: Cannot connect to non-local host kali
_IceTransSocketUNIXConnect: Cannot connect to non-local host kali
_IceTrans_IceTransSocketUNIXConnect: Cannot connect to non-local host kali
_IceTransSocketUNIXConnect: Cannot connect to non-local host kali
SocketUNIXConnect: Cannot connect to non-local host kali
Warning: Warning: Tried to connect to session manager, Could not open network socketTried to connect to session manager, Could not open network socketWarning: 

Tried to connect to session manager, Could not open network socket
_IceTransSocketUNIXConnect: Cannot connect to non-local host kali
Warning: Tried to connect to session manager, Could not open network socket

**Comment by a578740694** [comment]
When starting fluxion
./fluxion.sh: Line 281: bc: command not found
./fluxion.sh: Line 282: bc: command not found
./fluxion.sh: Line 283: bc: command not found
./fluxion.sh: Line 285: bc: command not found
./fluxion.sh: line 286: bc: command not found
./fluxion.sh: Line 288: 211+ (211-2 *) / 2: Syntax error: operand required (error symbol is ") / 2")
./fluxion.sh: Line 289: 158+ (158-2 *) / 2: Syntax error: operand required (error symbol is ") / 2")

**Comment by tom1t** [comment]
@a578740694 **Line 277 - 309** is only for the Resolution (Screen-Size)

**Comment by zartaz** [comment]
Same problem here also the debug terminal window remains open after exit the script

**Comment by itroy187** [comment]
same

**Comment by drjohannspector** [comment]
same issue, no change here.

**Comment by deltaxflux** [comment]
@a578740694

Install bc

**Comment by drjohannspector** [comment]
Just installed BC as well. Let's see what happens.

**Comment by drjohannspector** [comment]
This scrolls right before it says starting captive portal interface, all the xterm windows appear, I have an extra one that just is filled with "File not found" it scrolls so fast it crashes my system, can't even close it. Fresh install, updated....

cat: /tmp/fluxspace/ip_hits: No such file or directory

**Comment by zartaz** [comment]
Same issue after installing bc, nothing changes ... 😒😯

**Comment by MPX4132** [comment]
Sorry guys, I’ll check this out in a couple of hours. I’ve been busy lately. The problem started after adding the MAC logging. [This commit](https://github.com/FluxionNetwork/fluxion/commit/00dfab2842f44580f5f456a41ea295d484b64226) is before that was added, so it should work fine.

**Comment by deltaxflux** [comment]
Well I have a lack of time. I redesign the feature so it should work. I also add bc in the dependency list. We also switch to awk like I did because it is more reliable.

**Comment by eliddell1** [comment]
just did a pull -f still not working... the error goes away, but still hangs when creating the captive portal using hostapd

**Comment by deltaxflux** [comment]
Then it is not causes by this issue. Create a new issue with all your details

**Comment by drjohannspector** [comment]
I'm at work for the rest of the morning, when I get home I will try the earlier commit and report back.

**Comment by tomford007** [comment]
I was having this issue too. I deleted my fluxion folder and reinstalled from scratch to 3.9 andthis error went away. Im on Kali 2017.3.  Dev, I have a different issue but I'm new and not sure how to post, help me out please?

**Comment by tomford007** [comment]
Scratch that.. It's pretty clear how to do it..

**Comment by MPX4132** [comment]
Looks like @deltaxflux fixed the issue, are you guys still having problems with?

**Comment by tom1t** [comment]
The error message is now gone. 

Unfortunately, the AP service does not start. 
Fluxion has been completely reinstalled

**Comment by MPX4132** [comment]
@tom1t have you ever had fluxion succesfully run the `Captive Portal` attack?

**Comment by a578740694** [comment]
And @ tom1t the same problem

**Comment by MPX4132** [comment]
The verifier’s broken, I verified it about an hour ago.

**Comment by a578740694** [comment]
The problem still exists

Linux kali 4.14.0-kali1-amd64 #1 SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux

**Comment by MPX4132** [comment]
Check again.

**Comment by a578740694** [comment]
![0](https://user-images.githubusercontent.com/34572317/34291159-e9d7932c-e735-11e7-8a66-bf6f9fcda1b0.gif)

**Comment by MPX4132** [comment]
@a578740694 I don't understand what you're trying to show with you post, can you be a bit more specific as to what I should be looking at? By the way, is that the very latest version in the repository?

**Comment by zartaz** [comment]
for me its fixed

**Comment by a578740694** [comment]
This is the latest version and I would like to ask if my operation is correct and the Captive Portal flashes after finally selecting the AP page.

**Comment by deltaxflux** [comment]
@a578740694 
Create a new issue with your personal information. Problem is solved and I'm sure that this is not the problem.

**Comment by zartaz** [comment]
Delta i think the post is closed cause the described error is not longer exists ,the only issue is trully with pop up windows captive portal redirection which is in another post

**Comment by MPX4132** [comment]
@a578740694 Oh I see, yeah it seems that's an issue. Make a new issue with it. We need to check if it's an issue with fluxion or an issue with your wireless device. Try running fluxion again, but run it with the debug flag:
```
export FLUXIONDebug=1
./fluxion.sh
```
Post what you find in the new issue.
