### ISSUE TITLE
Hash Verification Issue

### ISSUE THREAD

**Issue by Obi-JuanKenobi** [FluxionNetwork/fluxion#308]
#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behaviour?
Attempting to attack an ap with a "/" in it's name produces:
"cp: cannot create regular file '/tmp/fluxspace/Access/Point-XX:XX:XX:XX:XX:XX.cap': No such file or directory

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Do a "Captive Portal" attack on an access point with a "/" in its name. Example: Access/Point
at "Select method to retrieve the handshake" I fed it a .cap I had gotten using aircrack-ng, separately.

#### What do you think the expected behaviour should be?
Should successfully verify the .cap file provided by the user.
Maybe by replacing illegal characters in the store location?

#### Specs
[ FLUXION Info ]
FLUXION V3.8

[ BASH Info ]
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy0
Driver: ath9k
Chipset: Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(322)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc3 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.3.0-kali1-amd64 (debian-kernel@lists.debian.org) (gcc version 5.3.1 20160101 (Debian 5.3.1-5) ) #1 SMP Debian 4.3.3-5kali4 (2016-01-13)

-----

**Comment by deltaxflux** [comment]
Yo have to escape them with \
like Acess\/Point

Or you simply rename the file
