### ISSUE TITLE
Can't connect to fake ap

### ISSUE THREAD

**Issue by yotaishu** [FluxionNetwork/fluxion#309]
#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
I can make fake access point. But I can't connect the AP.
Before I used older version(Rev2). But then I didn't have this problem.

#### What do you think the expected behaviour should be?
connect to fake ap.

#### Specs
[ FLUXION Info ]
FLUXION V3.8

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface ([interface]) Info ]
Device: Unknown
basename: missing operand
Try 'basename --help' for more information.
Driver: Unsupported
Chipset: 
Injection Test: ./scripts/diagnostics.sh: line 43: aireplay-ng: command not found
failed

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
./scripts/diagnostics.sh: line 57: hostapd: command not found
Path: attacks
CODE_OF_CONDUCT.md
_config.yml
CONTRIBUTING.md
fluxion.sh
language
lib
LICENSE
logos
README.md
scripts

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.14.0-kali1-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-16)) #1 SMP Debian 4.14.2-1kali1 (2017-12-04)

**Comment by a578740694** [comment]
The old version also can not connect to the virtual AP

**Comment by M1z23R** [comment]
apt-get install hostapd
You are missing it.
