### ISSUE TITLE
Capturing Password

### ISSUE THREAD

**Issue by tomford007** [FluxionNetwork/fluxion#312]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What do you think the expected behaviour should be?
 Capture password

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

Wow, hope I do this correctly. So I tried running this on my own network.. It's strange.. I don't get a pop up window to enter password and if I try to log in to network while fluxion is running it wont accept the password. Nothing happens, it just wont connect.

-----

**Comment by zartaz** [comment]
same here except the pop up window tells me that this network has connectivity issues try another one

**Comment by MPX4132** [comment]
You guys need to post more info. We have no idea what you're running. Is it Kali? Ubuntu? Raspbian? Arch? That's why you're supposed to do what the template says:
```
cd fluxion # Go to fluxion's root directory
./script/diagnostics.sh [interface] # Execute the diagnostics script, but substitute [interface]
```

**Comment by zartaz** [comment]
Sorry mate , i am running kali 2017,3 full updated and fluxion 3,9,when i go home i ll run the diagnostic script

**Comment by zartaz** [comment]
./diagnostics.sh wlan0
[ FLUXION Info ]
grep: fluxion.sh: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος(folder doesn't exists)
FLUXION V.


[ BASH Info ]
GNU bash, έκδοση 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL έκδοση 3 ή νεώτερη <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy0
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Injection Test: Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.13-1kali1 (2017-11-17)

**Comment by MPX4132** [comment]
We’re you running the attack with internet connectivity emulated, or was it with internet connectivity disconnected?

**Comment by zartaz** [comment]
Disconnected

**Comment by zartaz** [comment]
everything works fine till the popup window(no internet access try another network),also when i try to connect from my laptop it just don't connect.from my android when i try browse in http the dns spoof work it redirects me to the fake security message,in the earlier versions the popup window was redirecting me automatically in the captive portal without errors asking me the password

**Comment by MPX4132** [comment]
Are you using SSL? If you aren’t, try using it and see if it changes anything.

**Comment by zartaz** [comment]
Yes ssl also i test 3,10 and the result was the same it also gives me an error about captive portal folder missing resulting no correct pop up window when i go home i'll give you details

**Comment by zartaz** [comment]
./diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.10


[ BASH Info ]
GNU bash, έκδοση 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL έκδοση 3 ή νεώτερη <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy0
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.14.0-kali1-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-16)) #1 SMP Debian 4.14.2-1kali1 (2017-12-04)

1)sometimes after exiting script wlan0 remains in monitor mode
2)it leaves fluxion AP Authenticator window open every time after exit
3)it gives me the error "touch: cannot touch '/root/Desktop/fluxion-master/attacks/Captive Portal/pwdlog/MPAMIAS-XXXXXX-XX:XX:XX:XX:XX:XX-IP.log': Δεν υπάρχει τέτοιο αρχείο ή κατάλογος(the file doesn't exists)" i change mac on purpose
4) the captive portal is not working

**Comment by MPX4132** [comment]
Have you updated the device you're testing with recently? Maybe something changed with it. Check which version of fluxion was working properly for you and let me know to see if I can find any significant changes related to your issue.

**Comment by zartaz** [comment]
My first move everytime before i run your script is update upgrade and dist upgrade,i think the last working version was 3,6, the same exactly error i have in my laptop with the  internal wifi adapter aka different machine diferent card same os same script version

**Comment by MPX4132** [comment]
Updates to the host machine are fine. You mentioned a pop up window on some system that would take you to type login portal. I’m talking about that system. Did you update it or change anything from the time it was working to now? Chances are that’s what changed. Fluxion hasn’t changed much from 3.6. The only difference now is that we added options to allow emulating a connectivity and to enable or disable SSL.

**Comment by zartaz** [comment]
Yes my android sm-a520f was updated in that period but when i try to login to an ap that needs some kind of info or code in order to connect me the pop up windows works,i didn't think to connect with anorher device cause i tried to connect with my laptop and i failed andbibthoughtit was general error of dhcp

**Comment by zartaz** [comment]
I will try another device and i will respond asap,do you think samsung or manufacter general would take countermeasures about that attack???

**Comment by zartaz** [comment]
![screenshot_20171223-011347](https://user-images.githubusercontent.com/34681862/34314667-a3dc42c0-e77e-11e7-8fae-0dd56b8bdbd8.png)

**Comment by zartaz** [comment]
![screenshot_20171223-011544](https://user-images.githubusercontent.com/34681862/34314679-f6e75e3c-e77e-11e7-9782-63b848a0cd22.png)
![screenshot_20171223-011552](https://user-images.githubusercontent.com/34681862/34314680-fc70e076-e77e-11e7-8d21-3e8eb3efd4b3.png)

**Comment by zartaz** [comment]
![screenshot_20171223-012030](https://user-images.githubusercontent.com/34681862/34314756-d326d88c-e77f-11e7-9728-6604088d00c7.png)

**Comment by zartaz** [comment]
When i try to connect in that legimate network its redirects me at once in that page giving insrtructions in order to connect the pop up saying tap here to connect to network

**Comment by zartaz** [comment]
With fluxion that pop up is writing that network is not connected tobthe internet try another one

**Comment by MPX4132** [comment]
It can't be Samsung, they can't really detect this type of thing, plus, it's Google that develops Android. It's probably just a misconfiguration with fluxion's lighttpd's server. I don't have an android device to test things with, but last time I did test it, we had success and the device would show popup asking to advance to the network login. I can't understand Greek (I think), man, so I'm having a bit of a hard time understand the images you're posting. I don't have much experience with android either, so I'm not familiar with the interface.

You need to check which exact version of the script was working fine for you, so I can take a look at it. Verify it still works fine and it's not just an update by Samsung/Google that broke it.

**Comment by zartaz** [comment]
Thanks for your response i will try another devices in order to figure whats going on

**Comment by zartaz** [comment]
ok with lg smartphone everything works fine also the errors are gone after your last fix except the authenticator window which needed to be manually closed ,samsung still prompts to change network and last its my turn to contribute in el.sh :D

**Comment by MPX4132** [comment]
The authenticator window remains open by design. It’s supposed to be like that so users can see the key immediately, and dismiss it when they want.

**Comment by zartaz** [comment]
ok now i understand about the window,its good tha remains open so if someony accidentally close the script without writing tha wpa would keep it,so anyone who has a newer version of android would not be able to see the prompt to give us the wpa?

**Comment by MPX4132** [comment]
Well, the prompt should still come up, even on newer versions. If it doesn’t, it’s a problem. I can’t test it because I have not Android devices.

**Comment by MPX4132** [comment]
@zartaz Can you help me out a bit? Can you tell me what sites your Android 8 device tries to connect to immediately after connecting to the rogue AP? You’ll see what it tries to connect to in the DNS window. We might’ve missed a domain, or maybe your device has a new domain. The following is a list of the (Android) domains fluxion is actively redirecting right now:

```
www.google.com
clients[0-9].google.com
connectivitycheck.gstatic.com
connectivitycheck.android.com
android.clients.google.com
```

**Comment by aki2419** [comment]
everything seems to work until the last phase. Where it is waiting for clients, when i checked on my iPhone 6S it would not connect to fake AP automatically and would give error "no internet connection"... tried with SSL option still same issue..

**Comment by zartaz** [comment]
![2017-12-23 13-15-36](https://user-images.githubusercontent.com/34681862/34319161-ae61b508-e7e3-11e7-97e8-c2390e3b6f95.png)

**Comment by MPX4132** [comment]
@aki2419 That’s interesting, can you give us more details? I’m particularly curious about what password you use, but I don’t want to know your password. I’d like to know if the correct password has any special characters, for example, any characters not in the English alphabet (any non-ASCII characters).

**Comment by aki2419** [comment]
@MPX4132 my via wifi password is pure numerical... 9130009268 is the password... the same worked in older version without any issues.. i tried using both SSL and without SSL.. and both in emulated and disconnected setup...

**Comment by MPX4132** [comment]
@zartaz Thanks for the info. We might have to add that *`mtalk.google.com` domain...

**Comment by zartaz** [comment]
You are welcome ,whenever u need info tell me

**Comment by MPX4132** [comment]
@aki2419 What's the encryption method for your wireless network? Are you by any chance using WEP encryption, rather than WPA or WPA2? **If you're using WEP, I highly suggest you change to WPA2.** WEP encryption can be broken in less than five minutes with the aircrack-ng suite.

**Comment by MPX4132** [comment]
@zartaz I added the domain, but I don't think that was the problem. Can you check if anything changed with that device that doesn't prompt you for network login?

**Comment by zartaz** [comment]
yes i'll try it now

**Comment by MPX4132** [comment]
@zartaz I'm having trouble translating this screenshot:
![screenshot_20171223-012030](https://user-images.githubusercontent.com/34681862/34314756-d326d88c-e77f-11e7-9728-6604088d00c7.png)

Can you switch your phone's language temporarily to english, then try to screenshot that same screen?

I tried translating it with Google but I don't understand what the translation means:

**Comment by zartaz** [comment]
![screenshot_20171224-125933](https://user-images.githubusercontent.com/34681862/34325974-c5b781c0-e8aa-11e7-8d98-42631b6e8906.png)

**Comment by zartaz** [comment]
soory for not responding asap my bro

**Comment by zartaz** [comment]
![ezgif-4-8b31b9f825](https://user-images.githubusercontent.com/34681862/34326066-65c5d82c-e8ad-11e7-8ed5-c0bb24f472b2.gif)

**Comment by zartaz** [comment]
i have tested on ios latest version windows 10 and android of other manufacters also updated and the prompt was the same as mine i think is the most minor problem

**Comment by zartaz** [comment]
In my upper example I show you a router that redirects my device after connecting without need to press the prompt button,can we replicate that settings ???

**Comment by MPX4132** [comment]
That’s what I was trying to fix by adding `mtalk.google.com`. Your Android device is checking for something, but I don’t know what.

About the bug you said you found. Try waiting a bit to see if the windows don’t auto-close. If I remember correctly, there’s a delay because the authenticator waits a bit.

**Comment by zartaz** [comment]
I tried that I just don't wait so long for the file size of the uploaded gif

**Comment by zartaz** [comment]
u r right i am sorry it stops after 13-14 secs

**Comment by MPX4132** [comment]
@zartaz It’s all good, don’t worry about it. I know what’s causing that. Essentially, it has to do with the script waiting to recheck for a handshake. It sleeps for the amount of time you selected when you were configuring the attack (where it says 30 seconds recommended). So, if you stop the attack at around 15 seconds, it’ll sleep for another 15 and once it wakes up it’ll realize it needs to stop, and it proceeds to kill all other windows.

I’ll try to see if I can fix that somehow in a bit. I think it might be possible by using `wait` along with the `sleep` command.

**Comment by zartaz** [comment]
ok mate,i don't understand how a routers firmware that has 1+ year to be updated redirects me correctly even after my device update.can't we replicate that routers redirection settings(these routers have a captive portal waiting also for right password or other type of credentials in order to connect you)?maybe is the way the script redirects traffic to our ip? i remember when i was mitming with ettercap the configuration file had an *.* option which was redirecting everything to me except ssl which was after redirected with the sslstrip,u think it propably conflicts with the rest of the script?. i don't know how accurate are my questions in the scripts situation,but i try to give some thoughts with appreciation feelings :P

**Comment by zartaz** [comment]
my friend also why you remove the handshake folder by default?

**Comment by MPX4132** [comment]
The handshake directory should be created dynamically, by the arbiter in the `Handshake Snooper` attack. There’s no need to create it manually and add it to the repository.

Do you mind testing something for me? We can try to redirect all traffic to see if that helps your phone recognize the fact it’s behind a captive portal.

If you don’t mind, edit `fluxion/attacks/Captive Portal/attack.sh` and replace the lines below (lines 484 to 487):
```
# Redirect www.domain.com to domain.com
#\$HTTP[\"host\"] =~ \"^www\.(.*)$\" {
#	url.redirect = ( \"^/(.*)\" => \"http://%1/\$1\" )
#}
```
With these lines:
```
\$HTTP[\"host\"] =~ \".*" {
	url.redirect  = (
		\"^/(.*)\" => \"http://captive.gateway.lan/\",
	)
}
```

**Comment by zartaz** [comment]
ok i'll do ti now

**Comment by zartaz** [comment]
it gives me syntax error

**Comment by MPX4132** [comment]
Please post a screenshot of what it looks like after you replaced the text. You might’ve replaced something wrong, I’m not sure.

**Comment by zartaz** [comment]
![2017-12-24 18-51-10](https://user-images.githubusercontent.com/34681862/34327984-9452459e-e8db-11e7-9d5e-f4bcd106cc6b.png)

**Comment by zartaz** [comment]
syntax error close to non acceptable symbol ( { )
and command not found is the ending of the other lines

**Comment by zartaz** [comment]
static-file.exclude-extensions = (
	\".fcgi\",
	\".php\",
	\".rb\",
	\"~\",
	\".inc\"
)

index-file.names = (
	\"index.htm\",
	\"index.html\",
    \"index.php\"
)

\$HTTP[\"host\"] =~ \".*" {
	url.redirect  = (
		\"^/(.*)\" => \"http://captive.gateway.lan/\",
	)
}
" > "$FLUXIONWorkspacePath/lighttpd.conf"

	# Configure lighttpd's SSL only if we've got a certificate and its key.
	if [ -f "$FLUXIONWorkspacePath/server.pem" -a -s "$FLUXIONWorkspacePath/server.pem" ]; then
		echo "\
\$SERVER[\"socket\"] == \":443\" {
	ssl.engine = \"enable\"
	ssl.pemfile = \"$FLUXIONWorkspacePath/server.pem\"
}

**Comment by deltaxflux** [comment]
I will try to replicate this.

**Comment by zartaz** [comment]
If you want modify the script so I can test it and send you back the results guys

**Comment by deltaxflux** [comment]
I thought that you modify the script.

**Comment by zartaz** [comment]
Matias did I just test it :P

**Comment by MPX4132** [comment]
@zartaz download [this experimental branch](https://github.com/FluxionNetwork/fluxion/tree/captive-redirection) and test it on your device. If it works, we can merge it with the master branch.

**Comment by zartaz** [comment]
perfect i'll try it now

**Comment by zartaz** [comment]
no pop up window appears,everything else is the same except the message on my fake ap name informing that there is no internet

**Comment by zartaz** [comment]
can u sent me the 3.4 version just to test it?

**Comment by MPX4132** [comment]
[This is Fluxion 3.4's repository](https://github.com/FluxionNetwork/fluxion/tree/265606c68eb559bf29bb39d30a8d5f9231c98f34).

The versions are all in the commit history. To find a particular version in the repository, click "fluxion.sh" and click the "history" button. Then open the changes until you see that the revision changes.

**Comment by zartaz** [comment]
thanks mate

**Comment by zartaz** [comment]
its definitely my android update causing the error

**Comment by MPX4132** [comment]
Yeah, I suspected it was something like that. You mentioned all other devices seem to work fine, huh?

**Comment by zartaz** [comment]
my lg only with modified firmware cyanogenmod version 2014

**Comment by MPX4132** [comment]
What’s the model of the Samsung phone?

**Comment by zartaz** [comment]
![screenshot_20171224-233722](https://user-images.githubusercontent.com/34681862/34329291-88210b16-e903-11e7-9fd2-2369f8759396.png)

**Comment by zartaz** [comment]
![screenshot_20171224-233645](https://user-images.githubusercontent.com/34681862/34329293-98258974-e903-11e7-9198-a563f4b1d032.png)

**Comment by zartaz** [comment]
![screenshot_20171224-225634](https://user-images.githubusercontent.com/34681862/34329298-b0a2e924-e903-11e7-8914-9077e0f6a388.png)

**Comment by zartaz** [comment]
![screenshot_20171224-233634](https://user-images.githubusercontent.com/34681862/34329304-d7ea7db2-e903-11e7-9131-fda10c67d3bf.png)

**Comment by MPX4132** [comment]
@zartaz try the latest version on the repo. I added the standard redirect code for captive portals with [this commit](https://github.com/FluxionNetwork/fluxion/commit/98ebe0a26607a81e1bab7e5b41927932fd098e73). I assumed it was sending the proper code, but I was wrong. The server was sending redirect code 301 (permanent), rather than 302 (found a redirect). Just get the latest version on the repo and see if it fixes anything man.

**Comment by MPX4132** [comment]
If that doesn't fix it I don't think I can do much more. I don't have a device like that one to test things with.

**Comment by zartaz** [comment]
Ok mate I'll try it when I go home btw merry Xmas

**Comment by MPX4132** [comment]
Thanks man, Merry Christmas.

**Comment by zartaz** [comment]
my friend i've just tested ,the script is unstable with random behavior,1st time it gave me the first pop up that saying there is no internet connection,after 5 sec it gives another pop up with messenger redirecting me to the captive portal,2 time in captive portal it crashes and stops,3 time it doesn't open dns window and 4th everything runs smoothly except the pop up that said no internet connection try another windows i've been w8 for 20 sec but nothing else happens,very strange and unstable behavior,if you stable it and at least gives the prompt in messenger it can do the job Keep up the good work mate!!!

**Comment by MPX4132** [comment]
That’s odd man, the latest change I made couldn’t have caused those issues. Try restarting the fluxion host machine, and the Samsung phone.

The latest change couldn’t have caused those issues because all I changed was the lighttpd server configuration VERY little. I literally added a line with a return code, so that affects nothing in fluxion. The only thing that’s affected is the client device, in your case, the Samsung phone.

So, again, try restarting your devices and try fluxion again, along with the Samsung phone.

**Comment by aki2419** [comment]
@MPX4132 i am using WPA2 with AES encryption... i will try again to test it, in case if it works and post the same here..

**Comment by aki2419** [comment]
@MPX4132 hey... I tried, but still i am getting the same error, "password incorrect"...
![image](https://user-images.githubusercontent.com/34571464/34338207-455e749c-e98c-11e7-80eb-4f0f6b7894f9.png)

**Comment by MPX4132** [comment]
Yeah, the emulated option makes the phone think it has a connection to the internet (it emulates connectivity), so no prompt comes up.

Have you tried a different interface? Like 54? I can’t think of any issues with fluxion that would cause the issue you’re having.

**Comment by M1z23R** [comment]
@aki2419 I know it's idiotic question, but are you 100% sure you are entering valid password ?
Try running aircrack-ng against your handshake with wordlist containing only your password.

**Comment by M1z23R** [comment]
echo "YOURPASSWORD" >> password.lst
aircrack-ng -w password.lst -b AA:BB:CC:DD:EE YOURHANDSHAKEFILE.cap

**Comment by zartaz** [comment]
Matias when I go home I'll try it again ,so I have a question,when we use 1 adapter we are forced to use only one channel? Can I use mdk3 with channel hoping  to deauth the ap? Sometimes mdk3 crashes without ap changing channel.in that situation the best solution is two usb 3,0 Alfa adapters one for mdk3 and the other for the captive? Do I need to place the antennas of the different cards away from each other to avoid jamming between them? Also can I use my first adapter with channel hoping for the case that ap changes channel and the second for the captive?

**Comment by aki2419** [comment]
@MPX4132 yes, i am entering the correct password.. i did crack my WPA handshake via aircrack-ng and hashcat with the my WPA2 passcode...

**Comment by MPX4132** [comment]
@zartaz that’s not possible right now man. We haven’t implemented dynamic deauthentication. I’ll see if I can work on something later on. I’m a bit busy right now.

**Comment by zartaz** [comment]
Bro don't worry, I'll choose my first adapter for scan and mdk3 thru your script removing -c option from mdk3 command that will do the work and the second for captive portal,also I added a function with your variables to increase the txpower ,my question was if you know if that is hardware possible for the adapters

**Comment by MPX4132** [comment]
@aki2419 I really don’t know what could be causing that man. I can take a look, but you have to share your cap file and password, which might not be comfortable for you.

If you do decide you want me to check it, send it directly to me via email. My email is in the git repository, just do:
```
git log
```
And use the arrow to find my email next to my name.

Before you decide, know that I can’t really do anything if the cap file works fine in my machine. It could be your has a problem that’s preventing aircrack-ng from working properly.

**Comment by MPX4132** [comment]
@zartaz Yeah, it should be possible to deauthenticate two different channels with two different adapters.

**Comment by aki2419** [comment]
@MPX4132 I have emailed you the data.. Can you share the older version of fluxion so i can test them out ??

thanks in advance...

**Comment by MPX4132** [comment]
@aki2419 I’ll check it out in a bit. Every version is in the repo. You just have to go to the repo and click on fluxion.sh, then click the “history” button at the top right to see all changes. I labeled revision changes with “Upgraded revision...”

You’ll have to click the link to the commit and check the version change:
![d912f972-7c98-4ecc-925a-394eaa0ec0f2](https://user-images.githubusercontent.com/5618628/34342725-9d745d58-e97e-11e7-844b-3eee94a27485.jpeg)


For example, this one is from fluxion 3.4 to fluxion 3.5:
![82503a5a-8bcf-433b-86b4-713c8c63b77a](https://user-images.githubusercontent.com/5618628/34342726-ac83647e-e97e-11e7-9520-baa3e9516b4b.jpeg)

Once you find the version you need, click browse files and you’ll be taken to the repository for that version:
![a443ee6f-7ba9-432c-9872-7d414875f1b7](https://user-images.githubusercontent.com/5618628/34342735-0c7446dc-e97f-11e7-98dc-db281f5958ea.jpeg)


At that point, you can click the download button and you’ll download that version of fluxion.

**Comment by zartaz** [comment]
ok fully tested,the pop up window still prompt me that i don't have internet connection and to choose another network,it still does't undertand that is behind captive portal

**Comment by MPX4132** [comment]
Considering the fact you said it worked one time, even though it was unstable, says the problem probably lies with the phone. Fluxion isn’t actively doing or changing anything. I don’t really know what else to do, sorry.

**Comment by zartaz** [comment]
Yes the problem is the update,don't worry man you gave your best

**Comment by MPX4132** [comment]
Yeah, sorry. I’ll check it out If I ever get access to a device like that, but chances are it’s something with the software itself.

**Comment by MPX4132** [comment]
Closed for no-reply after a week.

**Comment by rad4day** [comment]
@yoriatet please open an issue and follow the instructions.
