### ISSUE TITLE
Problem entering WPA Key in Fake AP

### ISSUE THREAD

**Issue by portsky** [FluxionNetwork/fluxion#313]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
WPA key is not accepted when the Submit key is pressed on the Fake AP screen 

#### If the current behaviour is a bug, please provide the steps to reproduce it.
When I go through the Fluxion 2.9 attack I get right to the stage where the Fake screen is presented to enter the WPA key. But when I enter the key and click the Submit button nothing happens. However if I press the enter key on the popup keyboard the attack completes properly.
Unfortunately Wifislax version 3 does not work with my card which is the TL-WN722N.

#### What do you think the expected behaviour should be?
I would expect when I press the Submit key that the attack would proceed and the WPA key would be checked for validity.

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**I had to use diagnostics.sh from Fluxion 3.8 because I could not find a diagnostics.sh on Fluxion 2.9**

Output from diagnostics.sh
[ FLUXION Info ]
FLUXION V3.8

[ BASH Info ]
GNU bash, version 4.3.46(1)-release (x86_64-slackware-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /usr/bin/bash

[ Interface (wlan1) Info ]
Device: phy1
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: Injection is working!

[ XTerm Info ]
Version: X.Org 7.7.0(325)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 r2913 - (C) 2006-2015 Thomas d'Otreppe
  https://www.aircrack-ng.org

[ System Info ]
Linux version 4.9.40-wifislax64 (root@wifislax64) (gcc version 5.3.0 (GCC) ) #1 SMP PREEMPT Fri Jul 28 15:14:39 CEST 2017

-----

**Comment by rad4day** [comment]
Just for clarification: You're using Fluxion 2.9?

**Comment by deltaxflux** [comment]
@rad4day 
Yes he uses Fluxion 2.9 but he is techically a professional. He only want to draw attention to the bug. 
I will fix this Bug in Fluxion 3.0.

**Comment by portsky** [comment]
Thank you for your attention.
Do you think it would be possible to incorporate the fix into 2.9.? This works great for me but I am having problems with version 3.
Please let me know.
Thanks again, I appreciate your support.

**Comment by MPX4132** [comment]
@portsky what problems are you having with v3?

**Comment by portsky** [comment]
I was having problems in V 3.8 and 3.9 with the system hanging at the 'Starting Portal service' stage. However yesterday I updated to V 3.10 and this now seems to be fixed.
I have also been testing with an ALFA AWUS052NH 5ghz WiFi card and although I get right through to the Fake AP stage, it does not display or connect to the Fake AP. I'm not sure where the problem is as all the windows for DHCP etc load successfully but the client never seems to connect. ( All the counts stay at zero for Clients, Attempts etc).
Thanks for the great work on the latest updates.
Happy Christmas

**Comment by MPX4132** [comment]
Can you post what the AP service window outputs? It’s the top center one.

**Comment by MPX4132** [comment]
By the way, your driver must’ve been having problems because between 3.8 and 3.10, nothing really changed with the access point service, if I remember correctly. It’s common for driver to do some weird bs sometimes. I know it has happened to me with the AWUS036NHA, which is why I’m mentioning it.

**Comment by portsky** [comment]
I have figured out why I got further than the Starting Captive Portal service on 3.9 Vs 3.10. I used pyrit on 3.9 but used airbase and aircrack options on V3.10.
I tried using pyrit on v3.10 and it also hung at the Starting Captive Portal stage. So both working the same in 5Ghz.
For clarification I can use pyrit on both 3.9 and. 3.10 with 2.4ghz and everything completed successfully with the Asus052nh card. (I still have the original problem I raised with the Submit button not registering though.)

One other thing I noticed in the 5Ghz attack, there was no DHCP window.
Sorry I couldn't paste the AP Service screen. However here is a link to a pic of the AP Service window:
https://1drv.ms/i/s!AsdKdDWUMRPHg1gjqTZBiTXesxwt

**Comment by portsky** [comment]
Sorry here is the correct link:
https://1drv.ms/i/s!AsdKdDWUMRPHg1iBOdymwR0zGUrV

**Comment by MPX4132** [comment]
I can’t see that image without logging into OneDrive. Do you mind uploading it directly to GitHub?

What web UI are you choosing at the very end before launching the attack? You mentioned you’re having an issue with the submit button not working. The web UI you choose might be the problem.

I didn’t understood what you said very well. Did you have success with 2.4GHz, but not with 5GHz?

Also, if you can’t get through with pyrit, chances are you don’t have a valid handshake.

**Comment by portsky** [comment]
Yes I had full success with 2.4ghz, except for the Submit button issue (I tried option 7 for English and 52 for Movistar Spanish and neither worked).
Sorry Im having problems posting screen info directly but here are the contents of the screen when using 5ghz, the AP Service screen displays the following:
≠========================
Created Tap interface at0
Trying to set MTU on at0 to 1500
Trying to set MTU on FXan1AP to 1800
Access Point with BSSID C0:56:27:03:3F:16 started

This message is then repeated many times:
Client 00:0A:EC:7A:43:6C associated (unencrypted) to ESSID: "belkin.home"
=============================

The other visible difference between the 2.4ghz and 5ghz process is that no Fluxion AP DHCP Service window appears with 5ghz.

**Comment by MPX4132** [comment]
You’re using airbase-ng? If your device uses the `ath9k_htc` you shouldn’t need to use airbase-ng.

**Comment by portsky** [comment]
Hi, I hope I have not confused things. Below is a full status of my situation. I'm hoping I can get a fix for the Submit button problem as this is a key issue in getting the victim to enter the WPA key. It would be a bonus if I can get the 5ghz problems fixed.
Many thanks for you assistance.

I am actually testing with two different wifi cards.
==========================================================================
Card 1 = TL-WN722N. This card work well in the 2.4ghz range. I can capture handshake, use hostapd and pyrit, deauthenticate and can capture the WPA key. The only problem I have with this is the Submit button problem on the Fake AP screen, which I originally raised.
The output from the diagnostics.sh above was done with this card.

Card 2 = Afla AWUS052NH. 
a) This card works similar to the TL-WN722N above in the 2.4ghz range, I can capture handshake, use hostapd and pyrit, deauthenticate, and can capture the WPA key. However I also have the same problem with the Submit button on the Fake AP screen.
b) In the 5ghz range is where I have the main problems. It captures the handshake ok but I cannot use hostapd or pyrit because it hangs when Starting Captive Portal service. However if I use the Airbase and Aircrack options instead it proceeds to produce the multiple windows FLUXION AP Service, FLUXION AP Jammer, FLUXION AP Authenticator, FLUXION Web Service and FLUXION DNS Service. However it does not load the FLUXION DHCP Service window and it does not proceed any further. Even if I deauthenticate manually. I previously posted the message I get on the AP Service screen.

Here is the output from diagnostics.sh with the AWUS052NH card:
[ FLUXION Info ]
FLUXION V3.10


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1mon) Info ]
Device: phy1
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT3572
Injection Test: No Answer...


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)

**Comment by MPX4132** [comment]
@portsky what captive portal UI are you using? Have you tried using another? The UI you’re using could be the culprit.

The 5GHz problem is probabaly related to a misconfiguration in hostapd, which causes a failure in dhcpd and the DNS. That one should be easy to fix but I don’t have a 5GHz device to test it with, sorry.

**Comment by portsky** [comment]
Hi, I did some testing and the Submit buttons on thefollowing UI menu options work:
23, 29, 32, 40, 45, 46, 50.

The Submit button does not work on the following options:
7, 28, 52, 66.

I only tested English and Spanish options.

I would appreciate if you get any update on the 5ghz issues please let me know.
Thanks again for all your help

**Comment by MPX4132** [comment]
@portsky I’ve tried the generic English portal, 7, and it works fine man.

The others might not work properly. I never tried them all, so there’s a chance some don’t work. I’ll see if I can fix some of the ones you mentioned sometime. I might not have a chance to fix them till the weekend, though.

As for the 5GHz problem, I’ll make an experimental branch so we can test some things out, but I’m gonna need your help. You’ll have to be the tester.

**Comment by portsky** [comment]
Sure no problem I would be happy to be a tester. Although I'm not an expert I can figure most things out.
