### ISSUE TITLE
Fake AP's logging page is showing wrong password.

### ISSUE THREAD

**Issue by AgnivaDutta** [FluxionNetwork/fluxion#314]
When I I created the logging page which requires the clients to enter the password, As a client I entered the correct password(As I am testing with my own AP) but still the page shows wrong password. And there is no visual of the password on the aircrack screen. Why is this happening?

**Comment by deltaxflux** [comment]
Well, it is not reproducable and I think you should provide more information about this issue. Make a new issue if it exists otherwise use it normal.

**Comment by MPX4132** [comment]
If you built a portal for fluxion (a web interface), you better read [this guide](https://github.com/FluxionNetwork/fluxion/wiki/Prepping-protals-for-fluxion) to understand what needs to exist to have it work properly with fluxion.
