### ISSUE TITLE
Captive portal interface not removed after scripts exit

### ISSUE THREAD

**Issue by zartaz** [FluxionNetwork/fluxion#315]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?

when i exit the script FXan0AP is not removed from ifconfig list causing error with the captive portal when i run the script for a second time
#### If the current behaviour is a bug, please provide the steps to reproduce it.

run script then exit run ifconfig to see FXan0AP exists run again the script till the captive portal to receive captive portal error 
[*] Select a wireless interface

[1] FXan0AP  [+] Ralink Technology, Corp. RT2870/RT3070                         
[2] wlan0    [+] Ralink Technology, Corp. RT2870/RT3070                         
[3] Repeat                                               

Starting captive portal interface...
[*] Unable to start captive portal interface, returning!

#### What do you think the expected behaviour should be?

after script exit remove FXan0AP also sometimes random terminal windows needs to be manually closed

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
./diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.9

[ BASH Info ]
GNU bash, έκδοση 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL έκδοση 3 ή νεώτερη <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy0
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.13-1kali1 (2017-11-17)

-----

**Comment by MPX4132** [comment]
How do you exit the script?

**Comment by zartaz** [comment]
i've tested both with exit choise and control + C same attitude

**Comment by MPX4132** [comment]
I’m sorry, I accidentally forgot to check that before removing an obsolete line of code. The abort handler wasn’t calling unprep_attack to undo changes. It’s been fixed in the latest version.

**Comment by zartaz** [comment]
No need to feel sorry man & thanks for the solution 😁

**Comment by Aoki07** [comment]
Hello , i have a problem in the second step in fluxion for to create a "captive portal " this message appears when I select my wifi card :
] Select an interface for the access point.

[1] eth0 [+] Intel Corporation 8254EM Gigabite Ethernet Controller(rev
[2] wlan0 [+] TP-Link TL-WN722N v2
[3] Repeat
[4] Back

[fluxion2@kali]-[~] 2

[*] Unable to start captive portal interface, returning!

can someone Help please?

**Comment by cjb900** [comment]
Your issue is due to using a wifi adapter that is know to now work for wifi hacking. Only the V1 of that adapter works for with hacking. Also posting your issue to multiple times is not going to get your issue fixed any faster. especially when the adapter you use is your issue.

**Comment by Aoki07** [comment]
ok thanks for your answer, so which adapter i can use?

**Comment by cjb900** [comment]
Any of these adapters or chipsets are known to work.

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by Aoki07** [comment]
ok thanks for this
