### ISSUE TITLE
Error: your wireless card isn't supported

### ISSUE THREAD

**Issue by don1406** [FluxionNetwork/fluxion#316]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes, multiple times

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
*fluxion doesn't recognize my wifi card (tp-link tl-wn722n v2)*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
*After the step choose language, it goes right over to "[2] Select channel", and after that i get "[2] Error: your wireless card  isn't supported  
Do you want exit? [Yes / No]". But when i manually run monitor mode with "airodump-ng wlan0" it works*
<img width="1440" alt="schermafbeelding 2017-12-22 om 18 31 54 1" src="https://user-images.githubusercontent.com/34776452/34307307-bdc330c2-e747-11e7-8160-ccfa2f4b0080.png">
<img width="1440" alt="schermafbeelding 2017-12-22 om 18 32 12" src="https://user-images.githubusercontent.com/34776452/34307320-d744a8a0-e747-11e7-9ad4-2133cae7a275.png">
<img width="1440" alt="schermafbeelding 2017-12-22 om 18 32 16" src="https://user-images.githubusercontent.com/34776452/34307325-e17e5eb0-e747-11e7-8d0e-231051d7176c.png">
<img width="1440" alt="schermafbeelding 2017-12-22 om 18 36 57" src="https://user-images.githubusercontent.com/34776452/34307329-e9594e7e-e747-11e7-99ab-75e1d457e996.png">

#### What do you think the expected behaviour should be?
*Scanning al the networks in my environment*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by zartaz** [comment]
Use fluxion 1,7 better 🐸

**Comment by MPX4132** [comment]
You’re using an extremely outdated version of fluxion (v2). Download the latest version (v3.9) from the repo.

**Comment by MPX4132** [comment]
If you continue to have the same issue with the newer version, you can reopen this issue.

**Comment by SteveVinay** [comment]
where can i get older version
