### ISSUE TITLE
Scripting issue when Captive Portal attack starts.

### ISSUE THREAD

**Issue by tom1t** [FluxionNetwork/fluxion#317]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behaviour?
Starting Captive Portal access point service...

#### Specs
[ FLUXION Info ]
FLUXION V3.10

[ BASH Info ]
GNU bash, Version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Lizenz GPLv3+: GNU GPL Version 3 oder jünger <http://gnu.org/licenses/gpl.html>

Dies ist freie Software.  Sie darf verändert und verteilt werden.
Es wird keine Garantie gewährt, soweit das Gesetz es zulässt.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy1
Driver: rtl8187
Chipset: Realtek Semiconductor Corp. RTL8187
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.14.0-kali1-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-16)) #1 SMP Debian 4.14.2-1kali1 (2017-12-04)

-----
Use: RTL8187

Starting Captive Portal access point service...
It hangs there

**Comment by MPX4132** [comment]
Confirmed.

**Comment by MPX4132** [comment]
I’ve corrected the issue with [this commit](https://github.com/FluxionNetwork/fluxion/commit/3ef08c80e751280468f2b3a40d00a874ac0301c1), thanks for the report.

**Comment by zartaz** [comment]
el.sh fully translated in greek

2017-12-23 0:43 GMT+02:00 Matias Barcenas <notifications@github.com>:
