### ISSUE TITLE
Stuck on "Starting Captive Portal"

### ISSUE THREAD

**Issue by a578740694** [FluxionNetwork/fluxion#327]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behaviour?
hostapd
When doing this step [*] Starting Captive Portal access point service...
The attack window only lasted half a second to disappear
#### If the current behaviour is a bug, please provide the steps to reproduce it.
Start Captive Portal attack.

#### What do you think the expected behaviour should be?
Open normally.

#### Specs

[FLUXION Info]
FLUXION V3.10

[BASH Info]
GNU bash, version 4.4.12 (1) -release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3 +: GNU GPL License 3rd Edition or later <http://gnu.org/licenses/gpl.html>

This software is free software, you are free to change and republish.
To the extent expressly provided by law, this software does not provide any guarantee.
Path: / bin / bash

[Interface (wlan0) Info]
Device: phy0
Driver: mt7601u
Chipset: Ralink Technology, Corp. MT7601U
Injection Test: Injection is working!

[XTerm Info]
Version: XTerm (330)
Path: / usr / bin / xterm
Test: XServer / XTerm success!

[HostAPD Info]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X / WPA / WPA2 / EAP / RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: / usr / sbin / hostapd

[Aircrack-ng Info]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[System Info]
Linux version 4.14.0-kali1-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-16)) # 1 SMP Debian 4.14.2-1 kali1 (2017-12-04)
-----

**Comment by zartaz** [comment]
how many times have you try to run the script? everytime gives you the same response?

**Comment by a578740694** [comment]
many times, always been like this

**Comment by MPX4132** [comment]
Oh, I’m sorry, I forgot to respond after dismissing the notification. You need to check if the driver your device is using is compatible with fluxion. To be compatible with fluxion, your driver must be capable of injection, which it is, it must be capable of master mode, which we don’t know, and it needs to be capable of virtual interfaces.

You’re going to have to check for those requirements yourself. Check out [this guide](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!) I wrote about this issue. I think your driver might not support virtual interfaces. 

Sorry for not being too helpful man. This issue is extremly common and the most leading cause for it is no support for virtual interfaces.

If it turns out your device doesn’t have virtual interface support, you can try to look for alternative drivers for your chipset. If you don’t want to do that, you can use a second wireless adapter and use two different adapters to run the `Captive Portal` attack. Your last option is to just buy an adapter that supports everything natively. I suggest the AWUS036NHA, which uses the `ath9k_htc` driver. It’s the device I use to test fluxion with.

**Comment by a578740694** [comment]
Should be the problem! Thank you

**Comment by a578740694** [comment]
I tried to use two adapters to attack, but there is still such a problem.

**Comment by a578740694** [comment]
If it is two adapters, how to operate fluxion it

**Comment by MPX4132** [comment]
First, make sure to select an adapter that supports injection when you’re asked to select an interface to scan for networks. That interface will be used later for jamming with mdk3. The second interface **must support master mode,** and you’ll need to select it once you choose to configure the `Captive Portal` attack. It’s the first thing you do after choosing that attack, I believe.

It’s pretty late and I’m sleepy, merry Christmas by the way. I’ll check back later on today.

**Comment by tuthieu** [comment]
It's not involved to this thread.But Chrome has just updated.I don't know if you MPX4132 and Deltaxflux have known?
In the new version,if you use SSL cert,when you go a HSTS enabled site like Google.com ,the browser shows that "Wifi need login".

**Comment by a578740694** [comment]
Airbase-ng can be used to start, but unable to obtain ip address

**Comment by MPX4132** [comment]
@tuthieu I didn’t know that, thanks for letting us know.

@a578740694 Airbase-ng is extremly slow, and you’ll have more issues with it in the end. It’s because airbase-ng uses tricks to try to act as a master mode interface. That causes issues, and one of them is that it becomes ridiculously slow sometimes.

**Comment by a578740694** [comment]
I successfully ran hostapd under Ubuntu but did not generate any AP
So I try Verify Virtual Interface Functionality

When I test
iw dev wlanX interface add wlanY type monitor

command failed: Too many open files in system (-23)

**Comment by MPX4132** [comment]
Good job verifying that, @a578740694. Yeah, I believe that means your driver does not support virtual interfaces. You'll have to find a replacement driver, use two different wireless adapters simultaneously, or buy another device that natively supports virtual interfaces.

I have no experience with using different drivers, so I can't really help you there, sorry man.

**Comment by a578740694** [comment]
ok ! 
I seems can only buy one supported wireless card

**Comment by deltaxflux** [comment]
Well before you buy a new card use proper drivers. I have never experiences with this card or driver but I took a quick look and [here](https://github.com/tanaka1892/mt7601u-ap) is a driver on github which support ap mode which the default driver don't have. Take a closer look and if you have still problems you can ask us. In addition there are many nics which support ap master mode. Check which driver the card use and if it support
* master mode
* ap mode

Regards,
deltax

**Comment by a578740694** [comment]
Thank you, I tried the AP driver inside github, but all **make** fails

**Comment by deltaxflux** [comment]
Add
```
EXTRA_CFLAGS+=-Wno-implicit-function-declaration
EXTRA_CFLAGS+=-Wno-incompatible-pointer-types
```

Inside the config.mk

**Comment by tuthieu** [comment]
Hello deltaxflux and MPX4132,
Have you had any experience with these 3 wireless adapter:TL-WN722N,TL-WN822N,Archer T2UH?
Do they work well with fluxion?
Between WN822N and T2UH,which one has more range?

**Comment by rad4day** [comment]
TL-WN722N Rev 1 works. The newer revisions don't(V2/V3)

Don't know about the other two.

**Comment by MPX4132** [comment]
Sorry, I haven’t tried any of those.

**Comment by tuthieu** [comment]
@rad4day ,@MPX4132
Thank you.

**Comment by MPX4132** [comment]
I’m closing the issue because we narrowed it down to driver problems, which isn’t an issue with fluxion.

**Comment by gittyroma** [comment]
> Oh, I’m sorry, I forgot to respond after dismissing the notification. You need to check if the driver your device is using is compatible with fluxion. To be compatible with fluxion, your driver must be capable of injection, which it is, it must be capable of master mode, which we don’t know, and it needs to be capable of virtual interfaces.
> 
> You’re going to have to check for those requirements yourself. Check out [this guide](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!) I wrote about this issue. I think your driver might not support virtual interfaces.
> 
> Sorry for not being too helpful man. This issue is extremly common and the most leading cause for it is no support for virtual interfaces.
> 
> If it turns out your device doesn’t have virtual interface support, you can try to look for alternative drivers for your chipset. If you don’t want to do that, you can use a second wireless adapter and use two different adapters to run the `Captive Portal` attack. Your last option is to just buy an adapter that supports everything natively. I suggest the AWUS036NHA, which uses the `ath9k_htc` driver. It’s the device I use to test fluxion with.

Does this mean it doesnt support have virtual interface support?
root@kali:~# iw list | grep "Supported interface modes" -A 8
	Supported interface modes:
		 * managed
		 * monitor
	Band 1:
		Capabilities: 0x17e
			HT20/HT40
			SM Power Save disabled
			RX Greenfield
			RX HT20 SGI
