### ISSUE TITLE
Display wrong password entered.

### ISSUE THREAD

**Issue by jorgers1987** [FluxionNetwork/fluxion#328]
First of all, I thank you for this application and its constant updates.

It would be nice to enter in the program that the wrong password entered next to the number of attempts is displayed on the screen.

Also, in the web portals you can see the SSID and BBSID so that the connected client can see what your network is.

Thank you

**Comment by M1z23R** [comment]
Agreed, log of all incorrect passwords would be easy to add i guess so people can have preview of what the password could be, for example someone tries 12345679 (misstype) instead of 12345678, or wrong capital error.

**Comment by MPX4132** [comment]
That info is already being logged in the password log. All won’t passwords are being logged and saved, they’re not being displayed though.

**Comment by M1z23R** [comment]
I've read the script, i thought it removes password file after each unsuccessful try or right before the try i don't remember. Anyway, i think everything in /tmp/fluxspace is deleted after CTRL+C. I am probably wrong, it's just the way i remember it.

**Comment by MPX4132** [comment]
You’re right that the temporary directory is cleared when fluxion is interrupted (ctrl+c) or when it finishes an attack, however, the password log and the network log are stored in the attack directory.

All you have to do is go to “fluxion/attacks/Captive Portal/“ and you’ll find two directories with logs there **after you’ve successfully ran an attack.** One of the directories contains the password logs (pwdlog) which store all password attempts for each network that has been attacked, while the other contains the network logs (netlog) which stores the information for a network like its ESSID, BSSID, channel, and password.

**Comment by deltaxflux** [comment]
Yeah pwlog is stored and this feature is already added.

Regards,

deltax
