### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by imset** [FluxionNetwork/fluxion#33]
### Which version of fluxion are you using?
Latest, 5522c85

### What distribution of Linux (including the version) are you running it on?
Kali 2017.1 VM

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-LINK TL-WN722N V1 Atheros

### Which is the driver for it?
ath9k_htc v.4.9.0-kali3-amd64 

### Does it support injection ( output of aireplay-ng -9)
Properly working

### General description of your issue along with the steps to reproduce it
After capturing a handshake with aircrack-ng (pyrite doesn't properly function), I will 95% of the time get a message telling me that the SSL Certificate is invalid and I need to either create a new one, search for one, or exit.
If I press search, nothing at all happens. If I opt to create one, it immediately moves on, but no clients will connect to the fake site no matter how long I wait.
The other 5% of the time, it just tells me that the handshake is corrupted.
I'm using Kali in a VM, however all other operations I've tried in all other programs have worked fine thus far.

**Comment by nzhtrtlc** [comment]
I think there is something wrong about SSL Certificate and Fake site redirecting on the script.
I don't have any issues on SSL certificate but i have issue about fake site redirecting.

**Comment by strasharo** [comment]
What do you expect from the script, to force the clients to connect to  you?!

**Comment by nzhtrtlc** [comment]
@strasharo What about redirect problem ? My clients connects to my fake access point its okay. But when they try to connect any page such as google they should redirect to fake page i selected before right ?
But its not working.. I tried lighttp version you tested on experimental version, still nothing.

**Comment by deltaxflux** [comment]
Better you don't use the script. You miss used it.
