### ISSUE TITLE
Handshake is invalid

### ISSUE THREAD

**Issue by nevermoer** [FluxionNetwork/fluxion#330]
I have a .cap file containing 'handshakes' which i captured previously.
After i enter the absolute path to the file and select pyrit verification, it says, "Error, invalid hash file"
I can't figure it out. Is a bug or i did something incorrectly?
Can someone help me out? thanks.

**Comment by xXM3Do0Xx** [comment]
Maybe The AP Have Automatic Change the Channel  Like
Previously Captured Hanshakes Was on Channel 1
and AP Change 1 to 11 use it u must Captch a New

**Comment by MPX4132** [comment]
@nevermoer you’re not doing anything wrong. However, if you caught them yourself there’s a high chance you didn’t catch a good handshake. You can test it out yourself. Verify each handshake you’ve tried manually with pyrit:
```
pyrit -r path/to/file.cap analyze
```
If you **do not** see a “good” anywhere in the output, you have a bad handshake.

**Comment by nevermoer** [comment]
@MPX4132  I see. thank you.

**Comment by nevermoer** [comment]
@MPX4132 I see. thank you

**Comment by nevermoer** [comment]
@xXM3Do0Xx oh, i have checked it, they are on the same channel

**Comment by nevermoer** [comment]
@MPX4132  i captured a new handshake. pyrit says good, but it still has the problem

**Comment by MPX4132** [comment]
Run the manual pyrit test like I mentioned above and post a **picture** of the test please.

**Comment by nevermoer** [comment]
<img width="589" alt="2017-12-29 2 45 34" src="https://user-images.githubusercontent.com/31362986/34431133-5053ff20-eca7-11e7-910f-3c10df6df612.png">

**Comment by MPX4132** [comment]
@nevermoer Oh, that's interesting! Yeah, seems like something strange's going on here. Do you mind sharing your capture file with me? I need to run some tests with it to see what's breaking fluxion. If you don't mind, send it directly to me via email. My email can be found in my profile or by going to fluxion and running
```
git log
```
If you do mind, can you give me more information about the handshake file? For example, does the ESSID have any special characters?

**Comment by nevermoer** [comment]
okay, i will send it to you

**Comment by MPX4132** [comment]
@nevermoer thanks man, I’ll check it out and get back to you in a bit.

**Comment by felangga** [comment]
Btw, so in order to get it work, we must do handshake snooper and then open captive portal ?
Is it possible to start rogue ap / captive portal without entering path of handshake file ? just like the older version of fluxion

**Comment by MPX4132** [comment]
The older version of fluxion required a handshake as well. You need to retrieve the handshake file to verify the password entered by a target client.

**Comment by felangga** [comment]
I always get -1 responds when deauthentication process. 
Is this because my wifi adapter not supported?
I'm using broadcom 8260

**Comment by MPX4132** [comment]
@felangga Can you post a picture of what you mean?

**Comment by felangga** [comment]
@MPX4132 here you go http://oi63.tinypic.com/ngc9aa.jpg

**Comment by MPX4132** [comment]
@felangga That means the target access point changed channels, so you have to restart fluxion and run the attack again. If you keep getting it you need to do deauthentication with something else, instead of using fluxion for deauthentication.

**Comment by felangga** [comment]
No, the target ap still using channel 1. The problem solved after using external wifi adapter. 
But it won't redirected to captive portal page, always connection refused

**Comment by MPX4132** [comment]
The connection will be refused if you try connecting to the encrypted access point. The open access point should redirect to the captive portal.

**Comment by felangga** [comment]
No, connected to the fake Access point. 
Yes, I disabled SSL
Yes, I tried to open http site, and still connection refused.

**Comment by MPX4132** [comment]
State all the facts man, I'm getting tired of having to guess.

**Comment by MPX4132** [comment]
What captive portal UI are you using, and what's the OS of the device you're using to test the access point with? Is it Android by any chance? It's notorious for being all over the place when it comes to redirection.

**Comment by MPX4132** [comment]
@nevermoer Like I said in my response email, it seems there's a problem with airodump-ng and special characters. I'm going to close this issue because it's beyond our control.
