### ISSUE TITLE
NEW ISSUE FACING :( please someone help me :( ANY SOLUTION ??

### ISSUE THREAD

**Issue by AffiAfriDi** [FluxionNetwork/fluxion#331]
it is not connecting to the fake ap. 
![image](https://user-images.githubusercontent.com/34939181/34437787-1f56f6a8-ec56-11e7-80ac-ab3ba3dd9b4f.png)

**Comment by usama7628674** [comment]
@AffiAfriDi You need to fill issue template first,so run diagnostic script and post here.Chances are you're using driver that doesn't support virtual interface.

**Comment by AffiAfriDi** [comment]
@usama7628674 bro please contact me on facebook/instagram. i am waiting for your msg.
facebook.com/affiafridi | instagram @affiafridi
