### ISSUE TITLE
Html Error 403 Forbidden on Verizon captive portal UI

### ISSUE THREAD

**Issue by okiwoki** [FluxionNetwork/fluxion#332]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
When using a capture portal besides the general/neutral like the Verizon template, the portal gives a 403 Forbidden error instead of displaying the page.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Choose the Verizon capture portal or any other besides the general ones.

#### What do you think the expected behaviour should be?
The capture portal should be displayed instead of a 403 page.

#### If this is a feature request, what is the motivation or use case for the added feature?

-----

**Comment by MPX4132** [comment]
I don't think you tried all the others. I know for a fact at least five others that aren't the generic and work perfectly fine.

**Comment by MPX4132** [comment]
I do agree there's probably broken portals. I haven't tried them all. They're broken because people don't bother fixing them for fluxion before they upload them to the sites' repository.

**Comment by okiwoki** [comment]
You're right, I haven't tried all of them. I'll check out the sources and see if I can see why the general ones work and some others give 403. Probably a permissions problem somewhere.

**Comment by MPX4132** [comment]
Oh, rather than trying to reverse engineer it, [here's the guide](https://github.com/FluxionNetwork/fluxion/wiki/Prepping-protals-for-fluxion) I wrote about that.

**Comment by okiwoki** [comment]
Welp, that was quick. Whomever uploaded the Verizon one didn't rename it to index.html or have final.html, error.html, etc. There also isn't anything that submits to check.php.

**Comment by MPX4132** [comment]
Yeah, they're usually minor issues. All that's needed now is to wrap the submit button with a form so that once it's clicked it send it to check.php or authenticator.php. Do you want to make the changes on the repo and make a pull request or do you want me to do it?

**Comment by okiwoki** [comment]
I'm gonna say you. I'm a github noob honestly.

**Comment by MPX4132** [comment]
Alright, don't worry about it. I'll make the changes. I encourage you to try and learning it, though. Github and git aren't as complicated as they initially seem.

**Comment by okiwoki** [comment]
Yeah, I need to. I've been meaning to put some projects on here eventually as well. Thanks for taking care of it!

**Comment by deltaxflux** [comment]
Well this is a minor bug I will fix it tomorrow 
Regards
Deltax

**Comment by MPX4132** [comment]
@deltaxflux Sorry, I just saw your message. I fixed it and committed the changes already. I hate fixing those damn things though, the code is all over the damn place and they use old hacks to make their UI layouts work.

**Comment by MPX4132** [comment]
@okiwoki Try the Verizon interface again. I tried fixing it, but I didn't actually test it. My Raspberry Pi's memory card died, so I can't test it with that, and I deleted my VM because it was running an older version of Kali. You're going to have to test it yourself man.

**Comment by okiwoki** [comment]
@MPX4132 looks good! Not getting the 403 anymore and only requires some modification so that it doesn't ask for a username/pw and only for the WPA key.

**Comment by deltaxflux** [comment]
Sounds good,sorry I have less time. I've been at the c34c3 congress.
