### ISSUE TITLE
Git Clone Error in cloning sites: Permission Denied

### ISSUE THREAD

**Issue by seventhplug** [FluxionNetwork/fluxion#333]
root@kali:~/Downloads# ./clone_fluxion.sh
Cloning into 'fluxion'...
remote: Counting objects: 5232, done.
remote: Compressing objects: 100% (65/65), done.
Receiving objects:  20% (1047/5232), 208.01 KiB | 406.00 KiBReceiving objects:  21% (1099/5232), 208.01 KiB | 406.00 KiBReceiving objects:  22% (1152/5232), 208.01 KiB | 406.00 KiBReceiving objects:  23% (1204/5232), 208.01 KiB | 406.00 KiBReceiving objects:  24% (1256/5232), 208.01 KiB | 406.00 KiBReceiving objects:  25% (1308/5232), 208.01 KiB | 406.00 KiBReceiving objects:  26% (1361/5232), 208.01 KiB | 406.00 KiBReceiving objects:  27% (1413/5232), 208.01 KiB | 406.00 KiBReceiving objects:  28% (1465/5232), 208.01 KiB | 406.00 KiBReceiving objects:  29% (1518/5232), 208.01 KiB | 406.00 KiBReceiving objects:  30% (1570/5232), 208.01 KiB | 406.00 KiBReceiving objects:  31% (1622/5232), 208.01 KiB | 406.00 KiBReceiving objects:  32% (1675/5232), 208.01 KiB | 406.00 KiBReceiving objects:  33% (1727/5232), 208.01 KiB | 406.00 KiBReceiving objects:  34% (1779/5232), 208.01 KiB | 406.00 KiBReceiving objects:  35% (1832/5232), 208.01 KiB | 406.00 KiBReceiving objects:  35% (1857/5232), 804.01 KiB | 796.00 KiBReceiving objects:  36% (1884/5232), 1.50 MiB | 1015.00 KiB/Receiving objects:  36% (1887/5232), 1.95 MiB | 971.00 KiB/sReceiving objects:  37% (1936/5232), 2.55 MiB | 901.00 KiB/sReceiving objects:  38% (1989/5232), 2.55 MiB | 901.00 KiB/sReceiving objects:  38% (2005/5232), 2.55 MiB | 901.00 KiB/sReceiving objects:  39% (2041/5232), 3.18 MiB | 959.00 KiB/sReceiving objects:  39% (2065/5232), 3.79 MiB | 995.00 KiB/sReceiving objects:  40% (2093/5232), 3.79 MiB | 995.00 KiB/sReceiving objects:  40% (2125/5232), 5.06 MiB | 1.03 MiB/s  Receiving objects:  41% (2146/5232), 5.06 MiB | 1.03 MiB/s  Receiving objects:  42% (2198/5232), 5.70 MiB | 1.11 MiB/s  Receiving objects:  43% (2250/5232), 5.70 MiB | 1.11 MiB/s  Receiving objects:  44% (2303/5232), 5.70 MiB | 1.11 MiB/s  Receiving objects:  45% (2355/5232), 5.70 MiB | 1.11 MiB/s  Receiving objects:  46% (2407/5232), 5.70 MiB | 1.11 MiB/s  Receiving objects:  47% (2460/5232), 6.16 MiB | 1.08 MiB/s  Receiving objects:  48% (2512/5232), 6.16 MiB | 1.08 MiB/s  Receiving objects:  49% (2564/5232), 6.16 MiB | 1.08 MiB/s  Receiving objects:  49% (2589/5232), 6.16 MiB | 1.08 MiB/s  Receiving objects:  50% (2616/5232), 6.53 MiB | 1001.00 KiB/Receiving objects:  51% (2669/5232), 6.53 MiB | 1001.00 KiB/Receiving objects:  52% (2721/5232), 6.53 MiB | 1001.00 KiB/Receiving objects:  53% (2773/5232), 6.53 MiB | 1001.00 KiB/Receiving objects:  53% (2777/5232), 6.53 MiB | 1001.00 KiB/Receiving objects:  54% (2826/5232), 7.09 MiB | 1.01 MiB/s  Receiving objects:  55% (2878/5232), 7.09 MiB | 1.01 MiB/s  Receiving objects:  56% (2930/5232), 7.09 MiB | 1.01 MiB/s  Receiving objects:  57% (2983/5232), 7.09 MiB | 1.01 MiB/s  Receiving objects:  58% (3035/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  59% (3087/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  60% (3140/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  61% (3192/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  62% (3244/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  63% (3297/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  64% (3349/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  65% (3401/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  66% (3454/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  67% (3506/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  68% (3558/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  69% (3611/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  70% (3663/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  70% (3710/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  71% (3715/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  72% (3768/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  73% (3820/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  74% (3872/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  75% (3924/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  76% (3977/5232), 7.45 MiB | 1.03 MiB/s  Receiving objects:  77% (4029/5232), 8.26 MiB | 958.00 KiB/sReceiving objects:  77% (4074/5232), 8.68 MiB | 915.00 KiB/sReceiving objects:  77% (4074/5232), 9.55 MiB | 835.00 KiB/sReceiving objects:  77% (4074/5232), 10.17 MiB | 555.00 KiB/Receiving objects:  77% (4074/5232), 11.02 MiB | 544.00 KiB/Receiving objects:  77% (4074/5232), 11.69 MiB | 523.00 KiB/Receiving objects:  77% (4074/5232), 12.43 MiB | 506.00 KiB/Receiving objects:  77% (4074/5232), 13.27 MiB | 501.00 KiB/Receiving objects:  77% (4074/5232), 14.19 MiB | 762.00 KiB/Receiving objects:  77% (4075/5232), 14.19 MiB | 762.00 KiB/Receiving objects:  78% (4081/5232), 14.78 MiB | 818.00 KiB/Receiving objects:  79% (4134/5232), 14.78 MiB | 818.00 KiB/Receiving objects:  79% (4176/5232), 15.86 MiB | 903.00 KiB/Receiving objects:  79% (4176/5232), 17.04 MiB | 990.00 KiB/Receiving objects:  79% (4176/5232), 18.24 MiB | 1.01 MiB/s Receiving objects:  79% (4176/5232), 18.83 MiB | 1000.00 KiBReceiving objects:  79% (4176/5232), 19.77 MiB | 1005.00 KiBReceiving objects:  79% (4176/5232), 20.54 MiB | 943.00 KiB/Receiving objects:  79% (4176/5232), 21.42 MiB | 890.00 KiB/Receiving objects:  79% (4176/5232), 22.27 MiB | 849.00 KiB/Receiving objects:  79% (4176/5232), 23.06 MiB | 827.00 KiB/Receiving objects:  79% (4176/5232), 23.93 MiB | 818.00 KiB/Receiving objects:  79% (4176/5232), 24.80 MiB | 831.00 KiB/Receiving objects:  79% (4176/5232), 25.73 MiB | 847.00 KiB/Receiving objects:  79% (4176/5232), 26.71 MiB | 897.00 KiB/Receiving objects:  79% (4176/5232), 27.79 MiB | 917.00 KiB/Receiving objects:  79% (4177/5232), 27.79 MiB | 917.00 KiB/Receiving objects:  80% (4186/5232), 27.79 MiB | 917.00 KiB/Receiving objects:  81% (4238/5232), 27.79 MiB | 917.00 KiB/Receiving objects:  82% (4291/5232), 28.65 MiB | 1007.00 KiBReceiving objects:  83% (4343/5232), 28.65 MiB | 1007.00 KiBReceiving objects:  84% (4395/5232), 28.65 MiB | 1007.00 KiBReceiving objects:  85% (4448/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  86% (4500/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  87% (4552/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  88% (4605/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  89% (4657/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  90% (4709/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  91% (4762/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  92% (4814/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  93% (4866/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  94% (4919/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  95% (4971/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  96% (5023/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  97% (5076/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  98% (5128/5232), 29.30 MiB | 1.03 MiB/s Receiving objects:  99% (5180/5232), 29.30 MiB | 1.03 MiB/s remote: Total 5232 (delta 24), reused 29 (delta 8), pack-reused 5159
Receiving objects: 100% (5232/5232), 29.30 MiB | 1.03 MiB/s Receiving objects: 100% (5232/5232), 29.62 MiB | 866.00 KiB/s, done.
Resolving deltas: 100% (2640/2640), done.
Submodule 'attacks/Captive Portal/sites' (git@github.com:FluxionNetwork/sites.git) registered for path 'attacks/Captive Portal/sites'
Cloning into '/root/Downloads/fluxion/attacks/Captive Portal/sites'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:FluxionNetwork/sites.git' into submodule path '/root/Downloads/fluxion/attacks/Captive Portal/sites' failed
Failed to clone 'attacks/Captive Portal/sites'. Retry scheduled
Cloning into '/root/Downloads/fluxion/attacks/Captive Portal/sites'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:FluxionNetwork/sites.git' into submodule path '/root/Downloads/fluxion/attacks/Captive Portal/sites' failed
Failed to clone 'attacks/Captive Portal/sites' a second time, aborting
root@kali:~/Downloads#

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
Yeah, you got that because you didn't use ssh to clone. Considering the fact you think this is an issue, other people are going to start complaining they can't clone it because they won't know what the hell to do. I'll never it to https.

**Comment by seventhplug** [comment]
Lol! Sorry i didnt see the new installation instruction

**Comment by MPX4132** [comment]
@seventhplug it’s all good man, SSH for git is a bit of a hassle to setup because you have to add keys manually and other extra steps. I think we’ll have to retain https, but we’ll see.
