### ISSUE TITLE
Hangs when interface is selected 

### ISSUE THREAD

**Issue by applehacker321** [FluxionNetwork/fluxion#336]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
Fluxion hangs when interface is selected, have tried multiple supported WiFi cards including TLWN722n (AR9271) and RT 5370N....., still no sign of success. I am using the latest fluxion 2 and running Ubuntu Mate 16.04.02

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
You’re using an extremely outdated version of fluxion, use the latest version.

**Comment by MPX4132** [comment]
Once you update to the latest version, please run the diagnostics script.
