### ISSUE TITLE
Fluxion Authenticatior BUG

### ISSUE THREAD

**Issue by Darkcast** [FluxionNetwork/fluxion#337]
#bug 
running on kali 2017.3
When you running a captive portal and manually exit the application the authentication never closed if you test on another network it reopens the authenticator on top of the previous one.

# suggestion ¯\_(ツ)_/¯
also can you make a config so that I dont have to choose my operation language every time ?

**Comment by MPX4132** [comment]
How do you “manually exit” the application?

**Comment by Darkcast** [comment]
I use the exit option, 2 I think

**Comment by MPX4132** [comment]
Run the diagnostics script and post the output.

**Comment by Darkcast** [comment]
[ FLUXION Info ]
grep: fluxion.sh: No such file or directory
FLUXION V.


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy0
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.14.0-kali1-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-16)) #1 SMP Debian 4.14.2-1kali1 (2017-12-04)
![capture](https://user-images.githubusercontent.com/1676655/34464787-bf661eae-ee5d-11e7-9759-8e7d435e9424.JPG)

**Comment by MPX4132** [comment]
You're running an outdated version of the script, update the the latest version.

**Comment by Darkcast** [comment]
I did a git pull that same day. but ill try again.
