### ISSUE TITLE
locale not supported

### ISSUE THREAD

**Issue by nubbix** [FluxionNetwork/fluxion#341]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
*fake AP will not start*

#### If the current behaviour is a bug, please provide the steps to reproduce it.

> Starting Captive Portal access point service...
> Warning: locale not supported by Xlib, locale set to C

#### What do you think the expected behaviour should be?
Fake ap is started and windows pop up showing connected clients when they get deauthed.

#### Specs
Acer 5742Z
Intel(R) Pentium(R) CPU        P6200  @ 2.13GHz
SSD 850 Samsung

-----

**Comment by nubbix** [comment]
So I fixed the locals, but now I get this message

Starting Captive Portal access point service...

And nothing happens after that.

**Comment by MPX4132** [comment]
It's very likely you're experiencing a driver issue. You'll have to check the issue yourself using [this guide](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!).

**Comment by deltaxflux** [comment]
I also recommend to read the wiki before posting issues.

**Comment by nubbix** [comment]
Checked all via the guide provided, everything works perfectly. Never had any issue with my Alpha AWUS036H or any other RTL drivers. Using Kali Linux as OS!

**Comment by MPX4132** [comment]
Run airmon-ng and note your card’s driver. Come back here and do a search of the driver in the issues section. I’m positive that driver has issues that have been reported before.

**Comment by nubbix** [comment]
MPX4132 - You be wrong. 

First card
![2018-01-06_232143](https://user-images.githubusercontent.com/6438354/34644527-805374c0-f338-11e7-8e1a-cbff5f2e0562.jpg)

Second card
![2018-01-06_232211](https://user-images.githubusercontent.com/6438354/34644528-86ec71ba-f338-11e7-810b-d96805a85326.jpg)

All in all, two cards that cannot run Fluxion, so somewhere down the line, there must be an issue with something. I for one do not know hence why I ask here.

**Comment by MPX4132** [comment]
I said driver, not model ID, try again.

**Comment by MPX4132** [comment]
Issue with the driver confirmed.
![screen shot 2018-01-06 at 4 33 58 pm](https://user-images.githubusercontent.com/5618628/34644631-a385dca0-f2ff-11e7-8a1a-be841d3b6d43.png)
![screen shot 2018-01-06 at 4 34 57 pm](https://user-images.githubusercontent.com/5618628/34644633-a5876a50-f2ff-11e7-8ae0-1cea9c7d7a01.png)
Sorry, looks like your device has issues with its driver. I suggest you try looking for an alternative driver or try using an wireless device.

**Comment by nubbix** [comment]
I did try both Atheros and Alpha, any idea what might work?

**Comment by MPX4132** [comment]
Well, it depends on their chipset. The devices get a driver depending on chipset. Generally, atheros works fine so that one should work, but again, it depends on drivers.

I’ve had success with the `ath9k` and `ath9k_htc` drivers. I use the AWUS036NHA for testing. I’ve also had success with the WNA3100. I believe that’s the correct model number, but I can’t remember exactly and I can’t seem to find it to verify the model.

**Comment by bradcool22** [comment]
I'm pretty new to all this and i'm just wondering if fluxion works with ethernet so if not Im going to buy a those USB wifi things.

**Comment by nubbix** [comment]
@MPX4132  Thanks, will try some different drivers.

**Comment by MPX4132** [comment]
@bradcool22 You would still need a wireless adapter to jam the target. Fluxion can use ethernet access point devices, but again, you need another interface to jam the original.

@nubbix Definitely, try that before looking into buying anything.

**Comment by jackz33** [comment]
Please help, I’m getting same error message on ver 6.1 . Is this a directory error? Here it is below

Warning:  locale not supported by Xlib,  locale set to C
[*] Starting Captive Portal access point service...
Warning:  locale not supported by Xlib,  locals set to C

**Comment by space-sea** [comment]
I DONT PWND THIS
HELP ME PLS..

Warning: locale not supported by Xlib, locale set to C
[*] Starting Captive Portal access point service...
Warning: locale not supported by Xlib, locals set to C
