### ISSUE TITLE
Fluxion problem - What can I do?

### ISSUE THREAD

**Issue by James020** [FluxionNetwork/fluxion#343]
![26195428_1254238258042772_8561578885636913343_n](https://user-images.githubusercontent.com/35237061/34690460-d2a83832-f4eb-11e7-9dfd-31ea54db20f8.jpg)
A problem. Somebody help me, please!
After choosing language, the notification is "Run  export FLUXIONWIKillProcesses=1 before Fluxion to use it". What can I do?

**Comment by rad4day** [comment]
Following the instructions would be a great start :D

**Comment by MPX4132** [comment]
You selected a busy interface. It's probably been utilized by the network manager. You need to figure out how to stop it while you're using fluxion. If you're using Kali, which you might be, you can stop the network manager while you use fluxion, and start it back up when it's done:

```
systemctl stop network-manager.service
```

Try not to use the killer flag. I'm probably a bit biased, but I think it's a horrible idea to randomly kill processes. Especially when those processes are network managers which could become corrupted, so please, avoid using it.

**Comment by Darkcast** [comment]
run the command its says on the screen if all else fail reboot.

**Comment by deltaxflux** [comment]
No response closing.
