### ISSUE TITLE
bug after CTRL + C to close Wifi Monitor window, and target channel is 6

### ISSUE THREAD

**Issue by jasondenom** [FluxionNetwork/fluxion#345]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
 [1]	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	 	  100%	 

 (*) Active clients

        Select target. For rescan type r
[deltaxflux@fluxion]-[~]

#### If the current behaviour is a bug, please provide the steps to reproduce it.
Once airodump-ng scans for target, and picks up a target on channel 6, i press CTRL + C to close the Wifi Monitor window. I am returned the above errors. Other targets, on channels 1 and 11 for example, don't seem to affect anything adversely.

#### What do you think the expected behaviour should be?
I should be returned with the BSSIDs and their channels, they should be organized and numbered, and then i should be able to enter the corresponding number to begin an attack.

#### Specs
I dont know what this is. I am pasting the info in dump-01.csv. I don't now if it will help, but looking through the code myself, I wondered if it could be of any help.

BSSID, First time seen, Last time seen, channel, Speed, Privacy, Cipher, Authentication, Power, # beacons, # IV, LAN IP, ID-length, ESSID, Key
**:**:**:**:**:**, 2018-01-09 20:56:11, 2018-01-09 20:56:32,  6,  54, WPA2, CCMP,PSK, -70,      180,       76,   0.  0.  0.  0,  14, BaseStation360, 

Station MAC, First time seen, Last time seen, Power, # packets, BSSID, Probed ESSIDs
**:**:**:**:**:**, 2018-01-09 20:56:14, 2018-01-09 20:56:29, -61,        9, (not associated) ,Printer

-----

**Comment by MPX4132** [comment]
You need to update your version of fluxion.
