### ISSUE TITLE
AP Jammer not working?

### ISSUE THREAD

**Issue by spraragen88** [FluxionNetwork/fluxion#346]
My AP Jammer window just sits at "Periodically re-reading blacklist/whitelist every 3 seconds".

Even when there is a client, all windows output info except for the Jammer window. 

Is this normal?

**Comment by MPX4132** [comment]
Nope, it should say “Disconnecting between x and y”
Maybe the target access point changed channels. Have you checked that?

**Comment by egaldoch** [comment]
For me exactly the same issue. AP is not changing the channel.

**Comment by spraragen88** [comment]
Ok I fixed it. It is a problem with MDK3 itself. I stayed up all night trying to figure out what was going on. I basically had to reinstall MDK3 along with some packages.

apt update && apt install pkg-config (not sure if this helped, but its a step I took anyways)
apt-get install libnl-genl-3-200 libnl-genl-3-dev libnl-idiag-3-dev libpcap-dev (required to install MDK3)
svn co https://svn.mdk3.aircrack-ng.org/mdk3/

Then go into mdk3 folder, run make/make install

After that I could run mdk3 and it worked. It also worked in Fluxion.

**Comment by egaldoch** [comment]
Wow, thanks for the solution! I'll check it out and report back later

**Comment by rootuser9006** [comment]
hi,after this action(svn co https://svn.mdk3.aircrack-ng.org/mdk3/)
i cant find make/make install in mdk3 folder

i having the same issue
the fluxion ap jammer just sit periodically re_reading...every3second

**Comment by logan001** [comment]
and 1 year laters i have same problem.
the link for svn is not working anymore.
any suggestions?

**Comment by strasharo** [comment]
Just install mdk4 from here:
https://github.com/aircrack-ng/mdk4
If fluxion finds mdk4 in the path it will use it instead of mdk3.

**Comment by Barty89** [comment]
I have both that’s why I’m unsure why it’s not deauthing the real AP can I make another thread to post what it says on the screen or post here ?
