### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jitu3232** [FluxionNetwork/fluxion#347]
Fluxion not showing option to select in GUI in nethunter
It is showing choose language but don't show the options.
It shows to select wireless device but do not show option to select.
Please help

**Comment by jitu3232** [comment]
Photos sent by mail

**Comment by MPX4132** [comment]
Like I mentioned in the other thread, some people were having issues like this one before and I don’t think we discovered the cause for the issue.

It might be a problem with getting the screen resolution, but I’m not sure. I might have to make a VM to test it out. What version of nethunter are you running?

**Comment by jitu3232** [comment]
Here are the details

**Comment by jitu3232** [comment]
Kali version 3.16
Please help or should I try the unstable built

**Comment by MPX4132** [comment]
You shouldn't have to use an unstable build to run fluxion.

**Comment by jitu3232** [comment]
I visited your site from there it shows two builds unstable and stable
fluxion. I was talking about that.

**Comment by MPX4132** [comment]
I'm not sure what site you're talking about, but you shouldn't be downloading fluxion from anywhere other than here in GitHub.

**Comment by jitu3232** [comment]
Can this also happen if instead of 'got clone' i use zip file to extract the file.

**Comment by ufo008** [comment]
Does not support Chinese name wireless network

**Comment by ufo008** [comment]
Some wireless networks have Chinese characters and can not get handshake packets

**Comment by deltaxflux** [comment]
I think it is related in issue #349 [](https://github.com/FluxionNetwork/fluxion/issues/349)
Check out the installation guide and follow the steps.

Good luck

Regards, 
deltax

**Comment by deltaxflux** [comment]
@ufo008 Which verify method do you choose?

**Comment by ufo008** [comment]
@deltaxflux All methods have tried, that is, can not grasp the Chinese name of the wireless network handshake package, because when scanning the wireless network is also displayed garbled wireless signal name, but I do not know how to help you solve this problem.Thank you for your reply.

**Comment by rad4day** [comment]
Well you could probably use wireshark to make a capture which includes the actual wifi name. The devs could use it to fix this :D 
also you could check if the wifi name is shown correctly in airodump-ng, if not it's either a problem with your system or airodump-ng

**Comment by rad4day** [comment]
Also you shouldn't post a list of all the wifi networks in your area... I could probably determine where you live pretty accurate by now.

**Comment by ufo008** [comment]
@deltaxflux Thank you for reminding me, I will pay attention to the network security information next time

**Comment by Asux3** [comment]
Chinese Fluxion
https://github.com/GeekeyesTool/Chinese-Fluxion

**Comment by MPX4132** [comment]
The problem is with `airodump-ng` having compatibility issues with some non-ASCII characters. It doesn't matter what you select, the targeting mechanism is broken because `airodump-ng` doesn't output the proper ESSID. I've tested it. I've implemented manual targeting in Fluxion V4, but it's still under development.

**Comment by jitu3232** [comment]
I was running fluxion in GUI. But after upgrading Kali whenever I run GUI session it on shows grey screen with cursor as x. Kindly help

**Comment by MPX4132** [comment]
@jitu3232 You need to have a desktop/window manager running, otherwise fluxion will not work. It sounds like you're not using one, since you're describing what a single x session looks like. You probably did something like xstart or xinit. That will **not be enough.** You need a desktop/window manager.
