### ISSUE TITLE
Error Loading Page

### ISSUE THREAD

**Issue by tuthieu** [FluxionNetwork/fluxion#349]
Hello Fluxion team and everybody,I got problems
Is there anyone got same problems like me?
When I press connect,the site'll shows  "Error Loading Page". 
After choosing interface,the interface won't be changed to monitor mode,and I still can use internet.

**Comment by rad4day** [comment]
got tasked to comment:
try ` git submodule init`

**Comment by deltaxflux** [comment]
It likely that you miss the installation guide. I think that you just clone the repository but the sub-modules are missing. So here is the guide:

### Installation
Read [here](https://github.com/FluxionNetwork/fluxion/wiki/Generate-ssh-keys) before you do the following steps.

**Download the latest revision**
```
git clone --recursive git@github.com:FluxionNetwork/fluxion.git 
```
**Switch to tool's directory**
```
cd fluxion 
```
**Run fluxion (missing dependencies will be auto-installed)**
```
./fluxion.sh
```
And thanks for the quick response @rad4day.

Regards deltax
