### ISSUE TITLE
Fluxion 3.11 Only Generic Portals??? 

### ISSUE THREAD

**Issue by jasondenom** [FluxionNetwork/fluxion#351]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behaviour?
Just updated to 3.11 and I'm only seeing Generic Portals as options for the evil twin access point, (both disconnect and emulated). I found the sites directory, but noticed it is empty. I'm sure I'm missing something here, but I can't find anything about this issue online. How can I select other access points for targets to connect to, and be able edit the HTML code (such as in the error, final, and index files in the sites directory), the same as fluxion 2 and 3, and NOT have to use the Generic Portal, as they do not seem authentic. I added the site directories from the old version on fluxion into the new, empty, directory /attacks/Captive Portal/sites/ but I'm assuming I have to make some changes in some .sh file or something.

#### What do you think the expected behaviour should be?
Before there were many options. Ziggo, Belkin, Netgear were some .

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by jasondenom** [comment]
I figured it out. If anyone is dumb enough to have this same issue, go to the wiki and in the Captive Portal Attack section, click on the sites repository, download the master,and extract the sites-master folder. Move all the folders inside the sites-master directory into the /attacks/Captive Portals/sites directory. Fluxion is smart enough the figure out what you put in there by itself, so I didn't even have to change the shell code.

**Comment by rad4day** [comment]
Or just follow the install instructions to the letter.
(the `--recursive` in `git clone --recursive ....` matters!
