### ISSUE TITLE
Need to create a Custome ESSID 

### ISSUE THREAD

**Issue by itsStar** [FluxionNetwork/fluxion#352]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Feature request*

#### What is the current behaviour?

Current behavior is that it only use the ESSIDs scanned from the air
#### If the current behaviour is a bug, please provide the steps to reproduce it.

Not is is not a bug.
#### What do you think the expected behaviour should be?

There should be a feature to make a Custom ESSID like "Free Facebook"
#### If this is a feature request, what is the motivation or use case for the added feature?
I want to make an ESSID like "Free Facebook" So that user out there could connect to it and login to facebook and i can grab their passwords :)
 
#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
I can't understand this 
-----

**Comment by deltaxflux** [comment]
This is only for WiFi passwords and software should be made for one purpose.  I disagree with this feature request.  Take a look at ares if you need that. Hope you get pwned.

Cheers,

deltax

**Comment by itsStar** [comment]
Thanks :)
