### ISSUE TITLE
Captive portal does start

### ISSUE THREAD

**Issue by chimera234** [FluxionNetwork/fluxion#353]
Hello,

I am using a Edimax 7811UTC for 2.4&5 Ghz, drivers are correctly installed.

Handshake snooping works without any issues but when starting the Captive Portal I just see the message " Starting captive portal..." but afterwards nothing happens anymore.
Anybody has suggestions if this is a bug or how I can fix this issue on my side.

Thanks 
Chimera

**Comment by huxibei** [comment]
no word

**Comment by rad4day** [comment]
Well could you please provide more information?
-> diagnostics.sh ?

**Comment by chimera234** [comment]
Hello,

Below my output from diagnostics.sh

Thanks
Chimera

root@kali:~/fluxion/scripts# ./diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.11


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan0) Info ]
Device: phy0
Driver: 8812au
Chipset: Edimax Technology Co., Ltd 
Injection Test: Injection is working!


[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.9.59-v7_Re4son-Kali-Pi+ (root@builder) (gcc version 4.9.4 (Linaro GCC 4.9-2017.01) ) #1 SMP Tue Nov 21 00:36:47 CST 2017
root@kali:~/fluxion/scripts# ls
debug.sh  diagnostics.sh  preferences.sh  router.sh
root@kali:~/fluxion/scripts#

**Comment by deltaxflux** [comment]
Take a look at: https://github.com/FluxionNetwork/fluxion/wiki/Patch-driver-(rtl8812au)
