### ISSUE TITLE
Loop on installation

### ISSUE THREAD

**Issue by DustyReaper** [FluxionNetwork/fluxion#355]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
*Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
fluxion loops on installation, it doesn't install the missing packages

#### If the current behaviour is a bug, please provide the steps to reproduce it.
 I cloned the fluxion repository and ran ./fluxion.sh but the package installer loops permanently until i hit CTRL+C or close the window 

#### What do you think the expected behaviour should be?
The installer should install the missing packages and fluxion should start normally

#### Specs
[ FLUXION Info ]
FLUXION V3.11

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
Device: phy1
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
./diagnostics.sh: line 55: hostapd: command not found
Path: debug.sh
diagnostics.sh
preferences.sh
router.sh

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)

-----

**Comment by MPX4132** [comment]
You're missing a dependency which apparently isn't being caught. What dependency is it, do you see it in red as "missing"?

**Comment by DustyReaper** [comment]
dhcpd, hostapd, lighttpd, php-cgi and bc are missing. I also get the message "E: unable to locate php-cgi"

**Comment by MPX4132** [comment]
You're using Debian?

**Comment by DustyReaper** [comment]
Is use the latest Kali 2017.3 version

**Comment by DustyReaper** [comment]
Ugh, I feel kinda stupid right now. When I installed Kali on my laptop I didn't use a network mirror because I had no Internet connection. I added a mirror to sources.list and now it works fine. Anyway, thanks for your help!
