### ISSUE TITLE
unable to locate packages on install 

### ISSUE THREAD

**Issue by velikoffbooze** [FluxionNetwork/fluxion#360]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yep

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
fluxion refuses to install dependencies php-cgi, bc, dchpd,7zr,hostapd, and lightpd

### If the current behaviour is a bug, please provide the steps to reproduce it.

![screenshot from 2018-01-18 21-55-37](https://user-images.githubusercontent.com/35587288/35134394-9dfced8c-fc9b-11e7-9179-39563e588edd.png)

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by deltaxflux** [comment]
Maybe read here #355
