### ISSUE TITLE
Fluxion 4 release notes & Changelog 

### ISSUE THREAD

**Issue by deltaxflux** [FluxionNetwork/fluxion#361]
Hi guys,

Fluxion 4 is in progress here are some known bugs. **Fluxion 4 is unstable so please use the master branch.** 

### Unable to run interface after giving parameters
**Description:** The bug causes if you run fluxion with custom parameters.  Fluxion is unable to run 

**Effected are following parameters:** 
* --bssid 
* --essid 
* -c

**Solvable:** Yes I will take a look at the weekend.

### Language files could be obsoleted 
@MPX4132 improve the quality of the language files but it could happen that certain language strings are not used anymore.

### Interface don't get closed correctly

Already fixed: 9fce798

### Parameter -m useless
Since we don't have any tmux implementation yet the parameter **-m** has no function. Please keep in mind that it will work until the final release. So please be patient.

## Features
At the moment these features arn't added but we keep going on this.

* Dynamic Deauthentication [#152] - Make fluxion auto-adjust channels when a change is detected
* Resume Button [#70] - Add the "resume attack" feature to the `Captive Portal` attack.
* Attack Automation [#311] - Add more automation to attacks, advanced settings optimal.

**Comment by MPX4132** [comment]
@deltaxflux Oh sorry, I think I had already fixed the interface initialization issue with [this commit](https://github.com/FluxionNetwork/fluxion/commit/915fddccd420b484ca8e18a0072962da774ad31e) but I forgot to push it.

The problem I'm trying to figure out right now is how to pass the arguments to the sourced attack scripts, because they're not being passed down.

**Comment by deltaxflux** [comment]
> @deltaxflux Oh sorry, I think I had already fixed the interface initialization issue with this commit but I forgot to push it.

Well, I see at the end I will take a look at the argument parser, maybe I improve it but on another branch. 

> edit: What I mean is this, doing something like this:
./fluxion -a "Captive Portal" -e "WiFi" -b "AA:BB:CC:DD:EE:FF" -c 1 -- -a wlanX -j wlanY

Using the variables twice is in my opinion bad but I understand the purpose. I would use the ap interface -i so you don't have even to use -- 

I make a quick parse example lets see if you happy with it.

**Comment by MPX4132** [comment]
@deltaxflux Sure thing man, I think I just figured out what was wrong with the parameter issue, by the way. It was caused by the function scope. Parameters aren't inherited into functions, I had forgotten that.
