### ISSUE TITLE
macchanger after interface selection

### ISSUE THREAD

**Issue by cypherpeon** [FluxionNetwork/fluxion#363]
Wouldnt it be more comfortable to change mac right after the first interface selection?

**Comment by MPX4132** [comment]
What do you mean by “more comfortable”?

I assume you’re talking about Fluxion v3, right?

**Comment by cypherpeon** [comment]
Was talking about v3 yes. I'm just more at ease when mac is changed prior to anything else!

**Comment by deltaxflux** [comment]
I don't get the point.
