### ISSUE TITLE
Will Fluxion v4 implement iptables-save // iptables-restore

### ISSUE THREAD

**Issue by rad4day** [FluxionNetwork/fluxion#364]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
kinda*

#### Do you want to request a *feature* or report a *bug*?
*feature*

#### What is the current behaviour?
Fluxion v3 clears the IP-Tables and doesn't restore them on exit

#### What do you think the expected behaviour should be?
Saving the iptables via `iptables-save /tmp/fluxspace/iptables.rules` 
 and reload on exit via `iptables-restore /tmp/fluxspace/iptables.rules`

#### If this is a feature request, what is the motivation or use case for the added feature?

It's just a minor tweak but would probably be a great quality of life improvement.

-----

**Comment by MPX4132** [comment]
That's odd, Fluxion V3 should already do that. It's probably a bug. Thanks for letting us know, I'll look into it.

**Comment by deltaxflux** [comment]
"Bug" was already known since fluxion 0.18

**Comment by monday88** [comment]
fluxion 3.11 have problem TP-Link modem TKIP PSK handshake cannot capture. Can you solve it?
I try fluxion 2 v9 handshake can capture.

**Comment by rad4day** [comment]
@monday88 could you please open your own issue, and not take other issues off topic? Thank you.
Also when you open an new issue please fill out the template and attach logs so we might get a clue whats wrong.

**Comment by jitu3232** [comment]
can you please email me fluxion 2 version 9

**Comment by deltaxflux** [comment]
**No**
