### ISSUE TITLE
AP Jammer Issue

### ISSUE THREAD

**Issue by leavmealonepy** [FluxionNetwork/fluxion#365]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?

AP Jammer doesn't work.
"Periodically re-reading blacklist/white list every 3 seconds" but not packets being sent.

#### If the current behaviour is a bug, please provide the steps to reproduce it.

Fake AP attack

#### What do you think the expected behaviour should be?

AP Jammer should send something?

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
[ Interface (wlan0mon) Info ]
Device: phy0
Driver: iwlwifi
Chipset: Intel Corporation Wireless 7260 (rev 73)
Injection Test: ioctl(SI0CSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: XTerm(331)
Path: /ust/bin/XTerm
Test: XSevrer/XTerm success!

[ HostAPD Info ]
hostapd v2.6
User space deamon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/ETAP/RADIUS Authentic autor
Copyright (c) 2002-2016, Jouni Makiem <j@wl.fi> and controbutors
Path: /ust/sbin/hostapd

[ Aircrack-ng Info ]

Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
http://www.aircrack-ng.org

[ System Info ]
Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-18)) #1 SMP Debian 4.14.12-2kali2 (2018-01-11)
-----

**Comment by spraragen88** [comment]
I had the same problem, here was my fix:

apt update && apt install pkg-config (not sure if this helped, but its a step I took anyways)
apt-get install libnl-genl-3-200 libnl-genl-3-dev libnl-idiag-3-dev libpcap-dev (required to install MDK3)
svn co https://svn.mdk3.aircrack-ng.org/mdk3/

Then go into mdk3 folder, run make/make install

**Comment by leavmealonepy** [comment]
Nothing :/

**Comment by deltaxflux** [comment]
First things first, read the wiki before posting issues. I also strongly recommend looking for other mdk3 issues before posting here.
There are some open. 

#178
#245
#246
#302
#318
#329

However dynamic deauth is an enchantment with is actual not developt yet. So please be patient.

**Comment by leavmealonepy** [comment]
I made this post on phone, and i doesn't saw question about wiki.
I am looking hole day for an solution.

**Comment by deltaxflux** [comment]
I think it is a chipset issue. By a prober wireless card and you are good to go.

**Comment by rootuser9006** [comment]
@spraragen88  how to make the last step ?because therw is no make/make install in my mdk3 folder after i follow your step
![15205815764801702499454](https://user-images.githubusercontent.com/37206722/37196244-1092b4da-23b1-11e8-8dc6-df391f1cfcea.jpg)

**Comment by deltaxflux** [comment]
Really you fail while installing mdk3. Maybe you should try something else besides fluxion.

**Comment by rootuser9006** [comment]
ita ok now
i type : 
sudo make install 
in the last step,now my ap jammer is fixed.
thanks

**Comment by rootuser9006** [comment]
so my solution is(all below is what i write in the terminal )
1.apt update(click enter)
2.apt install pkg-config (click enter)
3.apt-get install libnl-genl-3-200 libnl-genl-3-dev libnl-idiag-3-dev libpcap-dev (click enter)
4.svn co https://svn.mdk3.aircrack-ng.org/mdk3/(click enter)
5.cd mdk3 (click enter)
6..sudo make installer(click enter)
then my ap jammer will send deauth now
but sadly the fluxion ap jammer service suddenly disappear after 4 min
is it nornal?will update again if anything happen

**Comment by rootuser9006** [comment]
mdk3 keep closing...while in the fluxion captive portal 
after sending some attack the fluxion ap jammer service keep closing...
any fix or what i did wrong?
version of fluxion v3r11

**Comment by rootuser9006** [comment]
ap jammer keep forced close while in captive portal
it happen after i update mdk3
any suggestion yo solve this？

**Comment by rootuser9006** [comment]
ap jammer keep forced close while in captive portal
it happen after i update mdk3
any suggestion to solve this？

**Comment by rootuser9006** [comment]
sorry i just see your email.
my wifi card is dlink dwa 548,ralink 5392 chipset.

i tried injection and it is work,
but when i send deaut(mdk3)to my android phone...nothing happen,
it doesnt disconnect at all.

capture handshake only when i manually reconnect to my router .

and now after i sucessfully install latest mdk3,fluxion ap jammer service
crash within few minutes
(auto close)(with success sending deauth)(but no effect on my phone)

i tried older version of fluxion which is 0.24 v128
the ap jammer dint crash(but still doesnt affect my phone either)my phone
just standstill(no disconnect)

any suggestion?or is it something wrong with my wifi chip?

**Comment by apocalipsys** [comment]
Hola, SOLUCIONADO.
En mi caso me funciono. 
	apt-get install pkg-config libnl-3-dev libnl-genl-3-dev 
	cd /mdk4-master
	make
	sudo make install
despues, edité el archivo attack.sh que está en la carpeta /attacks/captive portal/
linea 1505:
"mdk3 $CaptivePortalJammerInteface d -c $FluxionTargetChannel blablabla...."
cambié mdk3 por mdk4 y quedaria asi:
"mdk4 $CaptivePortalJammerInteface d -c $FluxionTargetChannel blablabla...."
Espero les sirva, saludos!

Tambien queria comentar otra cosa: despues de lograr el handshake snooper con éxito y tenemos que elegir la opcion "seleccionar otro ataque", cuando se elige el ataque " portal cautivo" y nos dá la lista de interfaces wifi, hay que abrir otra terminal y ejecutar el comando ifconfig para ver las interfaces con nombre "fluxwlX".  Una vez que tengamos estos datos escribir el siguiente comando
iw fluxwlX del
Por ejemplo, si tiene fluxwl0, fluxwl1 y fluxwl2, el comando seria:
iw fluxwl0 del
iw fluxwl1 del
iw fluxwl2 del
Una vez hecho esto, ejecutar el comando airmon-ng
y presionar Y en las 3 oportunidades (o las que sea dependiendo de cuantas interfaces hemos utilizado en la etapa de handshake snooper)
esto hace que nuestras interfaces se liberen
Entonces volvemos a la terminal donde nos quedamos en un principio (cautive portal attack) , donde fluxion nos dá la lista de las interfaces wifi y  elegimos la opcion "repeat" y asi con eso fluxion nos va a dar denuevo la lista de interfaces, pero esta vez "LIBERADAS" y podemos continuar con el ataque sin problemas.

**Comment by hyekalhitech** [comment]
hello @apocalipsys

im trying to use your method. but im stuck at 

"sudo make install"

here is what i do. 

i download mdk4 from github using command

"git clone https://github.com/aircrack-ng/mdk4.git- ."

download was success. and next i run 

"sudo make"

and ended up with this error

"dumpfile.c:2:10 fatal error: pcap.h: no such file or directory 
#include <pcap.h>

compilation terminated.
make[1]: *** [<builtin>: dumpfile.o] Error 1
make [1] Leaving directory '/root/mdk4-master/src'
make *** [makefile:9: all] Error 2"

how to solve this? im unable to install mdk4 on my kali. anybody has mdk4 download link that working with fluxion?

**Comment by hyekalhitech** [comment]
@apocalipsys hai pls answer me. asap

**Comment by rootuser9006** [comment]
i tried all solution i can find in the internet
but i cant diagnose the issue so i uninstall linux already
no longer use the software
thanks

**Comment by hyekalhitech** [comment]
@rootuser9006 use different version of mdk3

**Comment by apocalipsys** [comment]
@hyekalhitech
apt-get install pkg-config libnl-3-dev libnl-genl-3-dev
cd /mdk4-master
make
sudo make install

**Comment by apocalipsys** [comment]
> @apocalipsys hai pls answer me. asap
first instal mdk4 from github...
like: git clone  https://github.com/aircrack-ng/mdk4.git
and then
apt-get install pkg-config libnl-3-dev libnl-genl-3-dev
cd /mdk4-master
make
sudo make install

**Comment by genericc** [comment]
yes on new kali and ubuntu 16.4 same error
root@uptimelinux:~/mdk4-master# apt-get install pkg-config libnl-3-dev libnl-genl-3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu1).
libnl-3-dev is already the newest version (3.2.27-1ubuntu0.16.04.1).
libnl-genl-3-dev is already the newest version (3.2.27-1ubuntu0.16.04.1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-109 linux-headers-4.4.0-109-generic linux-headers-4.4.0-112 linux-headers-4.4.0-112-generic
  linux-image-4.4.0-109-generic linux-image-4.4.0-112-generic linux-image-extra-4.4.0-109-generic
  linux-image-extra-4.4.0-112-generic
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
root@uptimelinux:~/mdk4-master#
================================================================
ttacks/ieee80211s.o attacks/probing.o attacks/wids.o -o mdk4 -lnl-genl-3 -lnl-3 -lm -Losdep -losdep -lpthread -lpcap
mdk4.c: In function ‘main’:
mdk4.c:168:3: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   setuid(getuid());
   ^
make -C attacks
make[2]: Entering directory '/root/mdk4-master/src/attacks'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/mdk4-master/src/attacks'
make[1]: Leaving directory '/root/mdk4-master/src'
PREFIX:=/usr/local make -C src install
/bin/sh: 1: PREFIX:=/usr/local: not found
Makefile:13: recipe for target 'install' failed
make: *** [install] Error 127
================================================================
any idea how fix this?

**Comment by strasharo** [comment]
We're not developing mdk4, contact the developers of the tool.
