### ISSUE TITLE
Capture a handshake... How long is it going to take?It took me too long, and it didn't respond.

### ISSUE THREAD

**Issue by renmengkai** [FluxionNetwork/fluxion#369]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by rad4day** [comment]
Could you please elaborate?

**Comment by renmengkai** [comment]
Capture handshake 这个步骤大概需要多长时间？我这里一直在窃听但是一直无法获取握手包…



发自我的小米手机在 rad4day <notifications@github.com>，2018年1月27日 下午4:04写道：Could you please elaborate?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FluxionNetwork/fluxion","title":"FluxionNetwork/fluxion","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FluxionNetwork/fluxion"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rad4day in #369: Could you please elaborate?"}],"action":{"name":"View Issue","url":"https://github.com/FluxionNetwork/fluxion/issues/369#issuecomment-360968454"}}}
