### ISSUE TITLE
Auto Channel WI-FI router . Vunerable or not ? 

### ISSUE THREAD

**Issue by hyzo90** [FluxionNetwork/fluxion#37]
### Which version of fluxion are you using?
Newest one

### What distribution of Linux (including the version) are you running it on?
Kali Linux 2017

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-LINK TTL-WN722N 

### Which is the driver for it?
Atheros AR9271-AL1E

### Does it support injection ( output of aireplay-ng -9)
YES

### General description of your issue along with the steps to reproduce it
I've seen some auto channel WI-FI routers and it's kind of difficult to deauth them, because they constantly changing channels, when I tried to deauth clients of the WI-FI router.

**Comment by strasharo** [comment]
So what exactly do you expect, to chase them with a single adapter?

**Comment by hyzo90** [comment]
woww .. chilax .
