### ISSUE TITLE
Bug TKIP PSK

### ISSUE THREAD

**Issue by monday88** [FluxionNetwork/fluxion#370]
Dear Mr/Miss,
I use fluxion 3.11 have problem TP-Link modem WPA2 TKIP PSK handshake cannot capture. Can you solve it?
I try fluxion 2 v9 handshake can capture.
CCMP PSK no problem capture very fast and good.

**Comment by jitu3232** [comment]
please send me fluxion2 version 9 to this email id

**Comment by deltaxflux** [comment]
I think there is an issue with your setup.
