### ISSUE TITLE
Feature request: number of clients on station

### ISSUE THREAD

**Issue by lxknvlk** [FluxionNetwork/fluxion#371]
Like in wifiphisher, when making scan of networks, show how much clients on each station there are.

**Comment by xXM3Do0Xx** [comment]
Mark only who was in the original access point Like green color
Mark Color Raster who just connect on ap isnt from the Original
Then I know that there is no one and ended the attack

**Comment by lxknvlk** [comment]
Closing this ticket as there already is a number of station in the list

**Comment by deltaxflux** [comment]
yeah and already solved in fluxion 4.
