### ISSUE TITLE
fluxion 3.11

### ISSUE THREAD

**Issue by flxkalu** [FluxionNetwork/fluxion#372]
hi please i have fluxion 3.11 installed and after picking all the correction options and deauth-ng option, it disconnects and reconnects the device but still doesn't capture the handshake. i run kali on virtual box on a windows 10 pc.

i have tried everything to get it to capture the handshake but none has worked. Please i need your help

**Comment by makmak05** [comment]
deauthentication attack is fully work if the router is near by your wireless card and if many connected and using the victim router.. here my own tips to find if good sig nal ..in selecting wifi victim see  the power if this range 70-60 below this good in my own experience then see the data if this 0 it is not using or no device connected ..btw the more devices connected in the router victim the more you get the hash or capture the handshake... in my own experience in using.. goodluck

**Comment by flxkalu** [comment]
i tried all that. the wifi is my own network in my house and has at least 5 devices connected to it at once.

**Comment by deltaxflux** [comment]
Please provide more information.

**Comment by makmak05** [comment]
im using vmware 12 and i have no problem with that.. check it manually using airodump-ng and aireplay-ng..

**Comment by deltaxflux** [comment]
No, I mean @flxkalu

**Comment by MPX4132** [comment]
This might be related to the TKIP issue that’s been corrected in Fluxion 4, try checking out or downloading the Fluxion 4.0 branch (v4-development) and check if it works.

**Comment by MPX4132** [comment]
I’ll be busy till February 3rd, so I won’t have time to work on Fluxion 4 till then.

**Comment by deltaxflux** [comment]
Don't worry I have also less time.

**Comment by zartaz** [comment]
check if the target AP is in the same channel after the deauth attack

**Comment by flxkalu** [comment]
I finally got it to work; i just restarted my system and it started working but i ran into another problem. Thank you very much but..

After sending deauth and getting the hand shake, when i go to start a new attack where i am supposed to start captive portal, when i select my network card it says “ unable to start captive portal” why is this i have been trying to ressolve this and searched over the internet for two days. Please i really need help here. 

I use Awus036ach on kali linux rolling. Any ideas would really appreciated. Thanks

**Comment by usama7628674** [comment]
@flxkalu awus036ach doesn't support virtual interface.Take a look at here
https://github.com/wifiphisher/wifiphisher/issues/736

**Comment by thecipher420** [comment]
Same here man Im running windows 10 Kali Linux on vmmware using a TP-LINK WN822N and I Still cant

**Comment by usama7628674** [comment]
@thecipher420 I think you're using either V3 or V4 of that adapter.

**Comment by thecipher420** [comment]
V4

**Comment by usama7628674** [comment]
@thecipher420 Yeah,V4 comes with realtek chipset which is not suitable for fluxion.Purchase adapter that has atheros chipset in it like awus036nha.

**Comment by flxkalu** [comment]
Are you saying that there is no other option for using the one i already have (awus036ach)  because it's not even up to two weeks i bought it.

**Comment by rad4day** [comment]
No. The chipset or all drivers released for it don't support something crucial for fluxion. So no there is no way.

**Comment by flxkalu** [comment]
@rad4day thank you very much for your response but just to be sure, Does the awus036ach model have any advantages over awus036nha in other areas of hacking or would purchasing the awus036nha render it entirely useless? I'm very new in this field and want to learn and understand it very well. so sorry if i'm asking too many questions
