### ISSUE TITLE
AWUS036ACH monitor mode

### ISSUE THREAD

**Issue by decompwastaken** [FluxionNetwork/fluxion#373]
I am running KALI with Orical-VM and have been trying to test my WIFI security.
I managed to get my AWUS036ACH drivers working.
With ny old adapter i was able to type airmon–ng start wlan0 and it would make a virtual adapter called wlan0mon witch worked with all applications that came with KALIlike FERN ect.
With the AWUS036ACH i have to get it in to monitor mode by typing 
ifconfig wlan0 down
iwconfig wlan0 mode monitor
ifconfig wlan0 up
now my adapter says its in monitor mode and it is however some applications are looking for that virtual adaptor and wont work properly without it
i installed the RLT88xxAU chipset drivers using apt-get install realtek-rtl88xxau-dkms

**Comment by MPX4132** [comment]
Check if the problem has been resolved by downloading fluxion 4 from the development branch (v4-development). I made some changes to prevent interface snatching by reidentifying the interface. It's a development version, so expect some bugs.

**Comment by deltaxflux** [comment]
Some processes are interacting with your network card. Run `airmon check kill `to see whats interacting and kill them with `kill -9`

**Comment by MPX4132** [comment]
@decompwastaken Fluxion 4 already does that on it's own, **Fluxion 3 does not**. If you want to use `airmon-ng`, use its flag:

Fluxion 3:
```
FLUXIONAirmonNG=1
./fluxion.sh
```

Fluxion 4:
```
./fluxion -n
```

**Comment by decompwastaken** [comment]
http://kmac.us/wlan0new.jpg is what i get now. the tool that i am trying to run is Fern wifi cracker

**Comment by deltaxflux** [comment]
We are not fern wifi cracker developers. Contact them if you need help there.

**Comment by keralo** [comment]
those damn RLT88xxAU drivers... the old alfa usb wifi cards were way better (Alfa AWUS036H) . Plug and play monitor/managed mode etc out of the box.
