### ISSUE TITLE
[enhancement] add the ability to make a custom AP

### ISSUE THREAD

**Issue by Giova84** [FluxionNetwork/fluxion#375]
Since Fluxion is a tool which relies on various utilities to easily make AP with captive portals/html pages, would be nice and useful to add the ability to also make a custom AP, something like this:
choose AP name, channel, choose if to enable wep/wpa or make it open without password, choose the full path of the captive portal/html page, if to generate the ssl cert or to choose a custom ssl cert, and if to enable internet access. In this way, if we make an open AP, we could be able also to gethering other infos from connected clients.

**Comment by deltaxflux** [comment]
https://github.com/FluxionNetwork/fluxion/issues/352

**Comment by MPX4132** [comment]
I don’t understand why this would be useful. Do you have any examples you can tell us about so we understand why you want something like that?

Fluxion 4 allows the input of a custom ESSID and BSSID but eventually a corresponding capture file must be given as well.

**Comment by deltaxflux** [comment]
Take a look at the linked issue. I think you will find the answer there.  Most of them wants to perform easy mitm attacks e.g. steal facebooks accounts.

I don't see any purpose for that. So I don't implement it.

**Comment by MPX4132** [comment]
Oh, I see what you mean. Yeah, that’s beyond fluxion’s intended purpose.

**Comment by M1z23R** [comment]
People place fluxion and wifiphisher in same box but generally prefer fluxion over wifiphisher and that's why they want some of wifipshisher's functions in fluxion also.
