### ISSUE TITLE
AP changes channel due aggresive deauth for handshake

### ISSUE THREAD

**Issue by zartaz** [FluxionNetwork/fluxion#376]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes

#### Do you want to request a *feature* or report a *bug*?
feature

#### If this is a feature request, what is the motivation or use case for the added feature?
if new router firmwares detects mdk3 type deauth attacks we must use more aggresive attack type i think the best solution is after the time eg 30 secs for the handshake check the script must check if AP changed channel and run again deauth
#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V4.4

#### BASH Info 
GNU bash, έκδοση 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL έκδοση 3 ή νεώτερη <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan0) Info 
**Device:** Unknown
basename: missing operand
Try 'basename --help' for more information.
**Driver:** Unsupported
**Chipset:** 
**Master Modes** Yes
**Injection Test:** ioctl(SIOCGIFINDEX) failed: No such device
Failed (i am connected through that device right now)

#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### System Info
**Chipset:** Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-19)) #1 SMP Debian 4.14.13-1kali1 (2018-01-25)

-----

**Comment by zartaz** [comment]
in the beta version when i start the script it gives me that error ./fluxion: line 76: lib/Help.sh: no such file or folder
also it does't restore wlan0 properly it keeps alive fluxap interfaces

**Comment by deltaxflux** [comment]
Yeah I will take a look on it.

**Comment by deltaxflux** [comment]
Yep solved in the latest commit.
