### ISSUE TITLE
All the text are not showing

### ISSUE THREAD

**Issue by jitu3232** [FluxionNetwork/fluxion#377]
#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yee

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
After starting fluxion not version 3.11 & 4 only upper line is visible options are not visible. For example it shows select language and the options are not shown and same thing happens in other places where we have to select something. Please solve this issue in fluxion 4. 
I am using Kali nethunter 3.16 in one plus one device with cynogen mod android 7.1
I have already done apt-get update and apt-get upgrade

#### What do you think the expected behaviour should be?
It should show the languages other options

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by deltaxflux** [comment]
Please read here: https://github.com/FluxionNetwork/fluxion/issues/268

**Comment by deltaxflux** [comment]
Yeah I could replicate this issue but it is not related to fluxion. It is a problem with nethunter. 

I used:
Nethunter arm64 / full

I don't have any fix but I will make an issue at the nethunter github page. Lets see if we can solve this.
