### ISSUE TITLE
Fluxion AP Jammer window will randomly close during Evil Twin AP Attack

### ISSUE THREAD

**Issue by userix** [FluxionNetwork/fluxion#380]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?

The Fluxion AP Jammer will randomly close during an Evil Twin AP attack.

#### If the current behaviour is a bug, please provide the steps to reproduce it.

Just start a Evil Twin Session
#### What do you think the expected behaviour should be?

The AP Jammer service should just keep running until stopped by the user.
#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by rad4day** [comment]
It's pretty hard to debug something "random" without the tiniest clue why this is happening on your setup and not mine 🤔 
Could you please provide some diagnostic output so we can check if it's (for example) a version specific problem?

**Comment by userix** [comment]
Sorry, not very well versed in the Unix world.  I am running the Fluxion 3.11 version I got directly from the fluxion github here, using the git clone command.  

Sorry, forgot to paste the diagnostic output:
```
 FLUXION Info ]
FLUXION V3.11


[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash


[ Interface (wlan1) Info ]
Device: phy2
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Injection Test: Injection is working!


[ XTerm Info ]
Version: XTerm(331)
Path: /usr/bin/xterm
Test: XServer/XTerm success!


[ HostAPD Info ]
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org



[ System Info ]
Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-19)) #1 SMP Debian 4.14.13-1kali1 (2018-01-25)
```

**Comment by deltaxflux** [comment]
Try to update your operating system. I think it is a environment / driver problem because I used the same chip-set without any issues.

**Comment by jorgers1987** [comment]
Same problem and I'm using Kali Linux v2018.1 The attack works and creates the fake AP but the Jammer window is standing, indicates "Network down" or that screen disappears with which I believe that it does not disconnect the clients. I have a compatible wireless card to create APs and it is Atheros and it works with other applications like Linset and Wifimosys. Thanks.
