### ISSUE TITLE
Fluxion

### ISSUE THREAD

**Issue by Ynalo** [FluxionNetwork/fluxion#382]
Hey developer 

I'm using kali linux 2017.3 amd64, with alfa (awus036h) wlan1 , and have a problem with this script
I use two versions (9,11) with issues in eatch one . . 
In version 9 , when using alfa realtek, in the last step when script is ready to create fake access point , i got a mesage says 
Error: Got channel -1, expected a value > 0 .
This message comes with all networks and channels !
Now Fake AP created , but the clinets stay connected in orginal network ! 
They must dicsonnected from there nerwork , to connect my fake Ap to git pass key
 but this doesn't happen
So i tried with version (11 last update ) with same alfa card, after evertyhing is don
 in the last step either the script stops in this step
[*] Starting Captive Porta Point Service . . 
And still trying for mnts , sometimes takes an hour ! 
Then fake AP not created
 
So i disconnected my alfa , then trying with wlan0, But same problem happen, the Clinets stay connected in the orginal network 
Actually other networks attack with same alfa card, and seems my alfa is fine
And tried fluxion with Parrot os and got same issue ! 
How can fix these problem please

**Comment by deltaxflux** [comment]
Well, I don't think you have any extra ordinary features but I guess you have an old version we are currently at 
3.11 and 4.11 Dev. However read first the wiki and other issue before posting in addition the output of the diagnostic script is missing.
