### ISSUE TITLE
Failed to obtain ip address from fake AP.

### ISSUE THREAD

**Issue by NavjotSinghMinhas** [FluxionNetwork/fluxion#383]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behaviour?
When i connect to the fake AP from my device it just doesn't connects and says failed to obtain ip address

#### If the current behaviour is a bug, please provide the steps to reproduce it.
When connecting to the AP from a mobile device for the AP name "Singh\&Kaur", it doesn't lets the device to connect to the AP

#### What do you think the expected behaviour should be?
It should connect and open the browser to ask credentials

#### Specs
[ FLUXION Info ]
FLUXION V3.11

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlp3s0) Info ]
Device: phy0
Driver: ath9k
Chipset: Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: XTerm(324)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-32-generic (buildd@lgw01-amd64-016) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018

Below is the screenshot of the terminal when device was trying to connect.

![screenshot from 2018-02-11 18-00-11](https://user-images.githubusercontent.com/8942810/36073451-c2ff67c2-0f56-11e8-8261-4918991d50d2.png)

-----

**Comment by deltaxflux** [comment]
Hello @NavjotSinghMinhas,

thanks for your detailed report and welcome to fluxion. To your bug:

Does the captive portal appear if you type manually 192.168.254.1 in your browser? For me it sounds like the dhcp crashed.


However you can connect to the access point because it should work even if you don't get a valid ip adress. For testing please close the AP Jammming service window and see if it connect to your fake AP.

**Comment by NavjotSinghMinhas** [comment]
Tried with another AP, same bug, i thought it was because of the AP name having & in it.

![screenshot from 2018-02-12 13-28-11](https://user-images.githubusercontent.com/8942810/36087804-3e4cbdd2-0ffa-11e8-869d-0417503ca0e2.png)

My android device fails to connect to the network as no IP was assigned, and automatically connects to my default one.

![screenshot_20180212-132800](https://user-images.githubusercontent.com/8942810/36087842-6c2883c6-0ffa-11e8-8e83-d14244c14c82.png)

Tried opening 192.168.254.1 in browser:

![screenshot from 2018-02-12 13-31-19](https://user-images.githubusercontent.com/8942810/36087858-7eee8f28-0ffa-11e8-83b5-6483263e1f5e.png)

Also tried after closing the AP Jamming service window, same result.

![screenshot from 2018-02-12 13-33-13](https://user-images.githubusercontent.com/8942810/36087872-978f75ec-0ffa-11e8-8ddb-55e58ba9ad9b.png)

**Comment by deltaxflux** [comment]
Mhm can you please share your results with kali linux live?

**Comment by NavjotSinghMinhas** [comment]
Yes, sure.

Can you share your os version details, so that we can be on the same page.

I will have to download and install it, so expect a day delay :)

**Comment by deltaxflux** [comment]
Sorry for the late response I'm at the moment busy.

Well, I don't use kali or parrot anymore but I'm sure that the latest versions are working fine. I use at the moment arch linux (4.15.2-1 kernel) but I think for testing it is to complicated to install so don't use it if you don't want to install it as main system.

**Comment by deltaxflux** [comment]
No response so far, closing.
