### ISSUE TITLE
5ghz support

### ISSUE THREAD

**Issue by usuarionuevor** [FluxionNetwork/fluxion#385]
Since someone else already made auto-channel check: https://github.com/CVino/fluxion_v2ChannelHop
the only thing missing to make it fully functional and updated is support for 5ghz AP, when you can't connect to your 2,4ghz AP, devices will automatically switch to its respective 5ghz AP making all work done in 2,4ghz useless, the solution is to use a second chipset to create and deauth both AP.

The good news is this feature has already been done in latest **airgeddon**: https://github.com/v1s1t0r1sh3r3/airgeddon/tree/dev
I tested with AWUS036ACH (**rtl8812au**) and 5ghz AP works perfect.

Since the bigger work has been already done for both to inplement channel hopping and to create 5ghz AP I hope you can do the same on fluxion (linset).

**Comment by deltaxflux** [comment]
Well there is a kind of 5ghz support but currently it does not support the captive portal.

**Comment by MPX4132** [comment]
@voltaire1694 I'll try getting a 5Ghz interface soon so I can implement that feature, sorry for the delay.

**Comment by aquilabianca8** [comment]
This improvement is very important in these times, because the actual routers have two band (2,4ghz and 5 ghz) that works simultaneously, with different or same ssid; but i noticed they have TWO DIFFERENT MAC ADDRESS.
How to solve this problem?

Best Regards

Il giorno 15 lug 2018, alle ore 06:48, Matias Barcenas <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@voltaire1694<https://github.com/voltaire1694> I'll try getting a 5Ghz interface soon so I can implement that feature, sorry for the delay.

**Comment by MPX4132** [comment]
@aquilabianca8 You'd just have the secondary 5Ghz interface targetting the 5Ghz MAC address. On dual-band cards (a single card combining 2.4 and 5Ghz), I don't really know.

**Comment by voltaire1694** [comment]
Again, I don't think it's necessary to enable rogue AP functionality on the 5GHz band.  Every client that has 5GHz capability will also have 2.4GHz as well.  Adding a separate function for jamming 5GHz while simultaneously jamming a target in the 2.4GHz hand + Rogue 2.4GHz AP should be enough (for now) for Pen Testing dual band networks.

**Comment by MPX4132** [comment]
That’s not necessarily true, I have a pair of 5Ghz dedicated access points.

**Comment by tanderkiel** [comment]
Hello.. Can anyone recommend a compatible card with Fluxion that supports 5 ghz?

I have the 036nha that works perfect on 2.4 but I can not perform efficient audits because it does not support 5ghz.

I can also get the Awus036ach but I read that it does not work well with Fluxion.

thanks

**Comment by voltaire1694** [comment]
I have an Alfa AWUS036ACH 2.4 & 5 Ghz on order, and it appears to be highly recommended by Kali.  My intention is to run fluxion on two PCs simultaneously.  One will jam and run captive AP on 2.4GHz band and the other will jam only on the 5GHz band.  I haven't figured out if Fluxion will let me do the 5GHz jam-only function.  If not, then I'll be submitting it as a feature request.

**Comment by voltaire1694** [comment]
Now that I think about it, if the 5GHz AP being targeted for jamming does channel hopping in the 5GHz band, does this mean I will need 2x 5GHz adapters: one to monitor the hops and one to jam?  Grateful if someone could please confirm.  Voltaire1694

**Comment by voltaire1694** [comment]
One additional note: It looks like if one does not need to "host" a captive AP on the 5GHz band, but merely wants to jam clients and force them to the 2.4GHz band, one might be able to use wifijammer-ng for the 5GHz band jamming and (on a 2nd PC) run fluxion for the 2.4GHz AP + jam attack.  Has anyone tried wifijammer-ng for this type of dual-band approach?

**Comment by deltaxflux** [comment]
5ghz support is now supported. Deauth and ap works. I submit this patch as soon as I can confirm that this is stable.

**Comment by andybiss** [comment]
Hello,

Just confirming on the functionality of this improvement, does fluxion follow the channel on the 5g band if it is channel hopping? or does one need to keep track of that with a separate interface?

**Comment by Casper-88** [comment]
> 
> 
> 5ghz support is now supported. Deauth and ap works. I submit this patch as soon as I can confirm that this is stable.

can you let me know what wifi chip or model your use?

**Comment by shizzlepizzle** [comment]
any news concerning this? which 5ghz adapter would work with this? Got a asus usb-ac56 with rtl8812au but can't manage to deauth on 5ghz networks..

**Comment by dommod666** [comment]
i can deauth 5g it just doesnt want to let me host ap under 5g, 2 g works fine
