### ISSUE TITLE
wireless card does'nt supported 

### ISSUE THREAD

**Issue by SteveVinay** [FluxionNetwork/fluxion#387]
**----**
[i] Error: your wireless card  isn't supported  
Do you want exit? [Yes / No]:yes
./fluxion: line 1747: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
 [1]	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	 	  100%	 

 (*) Active clients

        Select target. For rescan type r

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by deltaxflux** [comment]
troll someone else.

**Comment by SteveVinay** [comment]
what that mean.....?????
