### ISSUE TITLE
Stuck on Starting Captive Portal access point service only with a network

### ISSUE THREAD

**Issue by navyarm** [FluxionNetwork/fluxion#389]
## Read the wiki?
Yes

## Do you want to request a feature or report a bug?

Bug

## What is the current behaviour?

I am getting stuck on [*] Starting Captive Portal access point service....
It only happened with a network
**before it worked perfectly with this network.**

## If the current behaviour is a bug, please provide the steps to reproduce it.

1. Run ./fluxion.sh to launch Fluxion 3
2. Select English
3. Select my wlan to place it into monitor mode
4.  Monitor all channels
5.  Wait a few seconds and close the monitor panel
6.  Select the target network
7.  Select Captive Portal (I already have a handshake file from Wifite)
8.  Select the wlan again for the Captive Portal interface
9.  Select Rogue AP - hostapd
10.  Point Fluxion to the captured handshake with direct pathing
11.  Select Pyrit Verification
12.  Select "Create an SSL certificate
13.  Select the generic portal for English (7)

## What do you think the expected behaviour should be?
Open normally.

## Specs

[ FLUXION Info ]
FLUXION V3.11

[ BASH Info ]
GNU bash, versione 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licenza GPLv3+: GNU GPL versione 3 o successiva <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy0
Driver: ath9k
Chipset: Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)

**Comment by deltaxflux** [comment]
Thanks for your report. Please execute this small script because I want to see which modes your nic support.

```
#!/bin/bash

function GetPosition() {
    echo $(iw list | grep -n "$1" | cut -d ":" -f1)
}

FIRST=$(echo $(($(GetPosition "Band 1:")-1)))
LAST=$(echo $(($FIRST-$(GetPosition "Supported interface modes:"))))

iw list | head -n $FIRST | tail -n $LAST
```

Thank you

**Comment by strasharo** [comment]
What wireless adapter are you using?

**Comment by deltaxflux** [comment]
Well this small script print all supported modes. I have to include it in fluxion and make some checks too.

**Comment by navyarm** [comment]
fluxion works perfectly with other WI-FI networks, Now it no longer works only with a wifi network (before it also worked with this network)

**Comment by deltaxflux** [comment]
Can you please provide the output?

**Comment by navyarm** [comment]
I do not think it's a problem of wireless adapter because it works with other wifi networks, And before that it also worked with the wifi network which is no longer working

**Comment by deltaxflux** [comment]
Oh sorry I missed that. Which names causes this problem?

**Comment by navyarm** [comment]
Ok, I provide you the output

**Comment by navyarm** [comment]
the name of the wifi network that does not work is this: InfostradaWiFi-b441fa It's a very unusual thing, first fluxion worked perfectly with this network

**Comment by navyarm** [comment]
it may be that the infostrada network has a firewall that blocks captive portal

**Comment by deltaxflux** [comment]
This is not the case, the attacker host the captive portal which means that it doesn't have any todo with the victims firewall. These are different things. This is really uncommon and I don't have any solutions for this now. I thought that the name include some special characters like whitespaces, backspaces and so one but this is not the case.
