### ISSUE TITLE
The best chipcard to work with fluxion

### ISSUE THREAD

**Issue by SwiftPredator** [FluxionNetwork/fluxion#391]
Hey,

as I mentioned some months ago, fluxion doesn't work with the rtl8812Au chipset(don't know if it works now. Please correct me if im wrong).
So which chipset do you recommend for using fluxion?

Greetings,
Paul

**Comment by strasharo** [comment]
Ас @usama7628674 said Awus036nha and  tl-w722n ( only V1, v2 and v3 are not compatible) work fine with Fluxion.

**Comment by deltaxflux** [comment]
You could also look here: https://docs.parrotsec.org/doku.php/supported-wifi-devices.
The wireless card should support monitor mode and ap mode.
