### ISSUE TITLE
few questions i have and need a little help

### ISSUE THREAD

**Issue by ronak9099** [FluxionNetwork/fluxion#392]
1)well to test it..i tried on my own wifi..and handshake snooper works and file is found! however when i try on victims wifi it doesnt work..it keeps searching? any idea why? or am dng something wrong..?

2)when dng the handshake process..i noticed my phones wifi get disconnected due to deauth..however while running the captive attk, it agains disconnect..and makes a clone? anyway to stop the clone and just let victim enter password and it saves?

2)

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*i dnt know what is this..just had a question*

#### What is the current behaviour?
*it does not handshake and keeps searching on victims wifi*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
not a bug

#### What do you think the expected behaviour should be?
it should search and find the handshake file?

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by usama7628674** [comment]
@ronak9099 Check victim's wifi if there is someone connected to it before running handshake snooper attack.You need to read wiki.Clearly you didn't understand the concept behind this tool.

**Comment by ronak9099** [comment]
ok thanks i will definitely read it again then
