### ISSUE TITLE
Online Clients Not Showing in Authenticator

### ISSUE THREAD

**Issue by curaksha** [FluxionNetwork/fluxion#393]
#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
Connected Clients do not show in the Authenticator Window

#### If the current behaviour is a bug, please provide the steps to reproduce it.
1. Run ./fluxion.sh to launch Fluxion 
2. Select English
3. Select my wlan to place it into monitor mode
4. Monitor all channels
5. Wait a few seconds and close the monitor panel
6. Select the target network
7. Select Captive Portal (I already have a handshake file from using Handshake Snooper)
8. Select the wlan again for the Captive Portal interface
9. Select Rogue AP - hostapd
10. Point Fluxion to the captured handshake with direct path
11. Select Pyrit Verification
12. Select "Create an SSL certificate
13. Select the generic portal for English (7)
14. Everything in the portal fires up perfectly (Including the Authenticator Window)
However, even when Clients join the Rogue AP, it does not reflect in the Clients Online() section. 
In previous fluxion versions, the same used to successfully happen. 

 ACCESS POINT:
    SSID ...........: @BSCIT#
    MAC ............: 54:B8:0A:07:95:EE
    Channel ........: 11
    Vendor .........: UNKNOWN
    Runtime ........: 00:07:20
    Attempts .......: 0
    Clients ........: 1

  CLIENTS ONLINE:
<no clients show here>

This is reproducible & happens every time. 

#### What do you think the expected behaviour should be?
When clients connect, their details should be visible in the Clients Online () Section

#### Specs
./diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.11

[ BASH Info ]
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy0
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

[ XTerm Info ]
Version: XTerm(330)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.13.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20171026 (Debian 6.4.0-9)) #1 SMP Debian 4.13.10-1kali2 (2017-11-08)

-----

**Comment by deltaxflux** [comment]
Active clients are printed using nmap so maybe nmap can't figure out the vendors. For me, it is not reproducible because it doesn't happen if I use fluxion. I keep it in mind but I definitly don't deal with it in deep because it is working.

**Comment by curaksha** [comment]
Thank you for your attention. Keep a look out for it if the same repeats for other users. Will try to figure how to solve the problem I have at hand, meanwhile.

**Comment by deltaxflux** [comment]
You can check if it working if you connect your own devices and take a look if they keep connected or if they gets disconnected from the network. Hope it helps good luck

**Comment by djmeero** [comment]
I confirm this bug in Fluxion 4.4 running on Kali 2018.2. I tested with my own phone everything is working fine, clients gets updated..but nothing comes up on "Clients online" i have nmap version 7.70+dfsg1-0kali2

**Comment by djmeero** [comment]
Ok I've done it. Changing line 872 in attack.sh and using readarray will fix this issue.

**Comment by curaksha** [comment]
Thank You
