### ISSUE TITLE
No Login/Authentication Page After Connecting To Fake AP

### ISSUE THREAD

**Issue by iamtelo** [FluxionNetwork/fluxion#397]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?

Handshake Capture works perfectly, thank you, but I get to the Capture Portal and it's a shit show.
Everything works up until it's time to feed the clients the Authentication page in which to re input password for internet access.
I get no errors, everything is all brightly coloured, but when I get my phone and laptop and try to browse, all it shows is, "No internet connection" as opposed to the wonderful login page to be used to obtain their password

#### If the current behaviour is a bug, please provide the steps to reproduce it.

1. Run ./fluxion.sh
2. Select English
3. Select my wlan0 to place it into monitor mode
4. Monitor all channels
5. Wait a few seconds and close the monitor panel
6. Select the target network
7. Select Captive Portal (I already have a handshake file from running the Fluxion handshake attack)
8. Select the wlan again for the Captive Portal interface
9.Select Rogue AP - hostapd
10. Point Fluxion to the captured handshake with direct pathing
11. Select Pyrit Verification
12. Select "Create an SSL certificate
13. Select the generic portal for English (7)

#### What do you think the expected behaviour should be?
Login/Authentication portal should open in the browser of the clients on the network.

#### Specs
*[ FLUXION Info ]
FLUXION V3.11

[ BASH Info ]
GNU bash, version 4.4.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy0
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(331)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-19)) #1 SMP Debian 4.14.13-1kali1 (2018-01-25)*

-----

**Comment by fbownz** [comment]
Ave had the same issue, but the login screen only appears on Mobile devices.

**Comment by deltaxflux** [comment]
Does the page appear if you type it manually in your browser?

**Comment by Techsmobile** [comment]
I hv a same problem

**Comment by FluxionPassion** [comment]
@deltaxflux same problem for me.And you need some information maybe topic owner friend dont say but I will say yes I type it manually browser and NO CONNECT NO PAGE anything...

**Comment by FluxionPassion** [comment]
I crack a lof wifi password with linset and still continue,but I have not an achivement with FLUXION ALL VERSIONS.First version and last version same for me when I connect fake ap I cant see anything about wpa login password page.

**Comment by zartaz** [comment]
I have the same issue, the only way to get pop up window in my android device is the captive portal to be connected not emulated either dnsspoofed

**Comment by deltaxflux** [comment]
Removed because it violate fluxion terms.

**Comment by Techsmobile** [comment]
Fix that issue doesnot appear login page....

**Comment by deltaxflux** [comment]
I recommend that you don't use fluxion. I guess you try these thinks at the first time. You should start manually.

**Comment by hearthacker1** [comment]
i have same problem like my friends .that the fluxion 4 not showing at last the login page and now run forward from the 
Select the generic portal for English (7)
please help us

**Comment by fbownz** [comment]
Update.  Update to fluxion 4.4 it helped

**Comment by hearthacker1** [comment]
thinks for give me a such a kind of information , but i update the fluxion
to 4.0 and the can't make a fake wifi
the fluxion tool are going to stuck in last step when i making the fake
wifi
please help me to resolve this issue again

**Comment by hearthacker1** [comment]
i am still waiting for your response . Help me to resolve this problem

**Comment by usama7628674** [comment]
@hearthacker1 Plug your wireless adapter and post the output of the following
`airmon-ng`

**Comment by hearthacker1** [comment]
can't understand what your want to tell me . please tell clear step by step
to resolve problem

**Comment by hearthacker1** [comment]
( airmon-ng ) what to ( start or stop) or what command i give with
airmon-ng .
thanks for giving me your presious time

**Comment by usama7628674** [comment]
@hearthacker1 Just put the command in terminal after plugging your wireless adapter.

**Comment by hearthacker1** [comment]
Ok i did this step but still can't working . Bro tell me this is working
online or offline

**Comment by hearthacker1** [comment]
i do the this step but can't working

**Comment by deltaxflux** [comment]
I don't think that you should use fluxion.

**Comment by hearthacker1** [comment]
why not bro see in this screen shot . this is a screen shot when i crack my
wifi and they struck on this  page . i give 30 minutes but can't working
​
​

**Comment by hearthacker1** [comment]
please help me to learn this software and thanks for all comments

**Comment by deltaxflux** [comment]
Bullshit, stop beeing annoying or I ban you.

**Comment by hearthacker1** [comment]
No. no , cool  my friend . i am just trying to solve  my issues .  i don't
want to give anger /
and if i give a you some disheart please forgive me.ok

**Comment by hearthacker1** [comment]
and these are my last issues .i am trying to solve these error . i can't
give up now

**Comment by denieshermawan** [comment]
i have same problem..

**Comment by joentpn** [comment]
#### FLUXION Info
FLUXION V5.2


#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan1) Info 
**Device**: phy1
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT5370
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.17.0-kali1-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-25)) #1 SMP Debian 4.17.8-1kali1 (2018-07-24)

#### Chipset
Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by joentpn** [comment]
when connecting to the fake AP without a password, it is not possible to establish a connection, when it connects, the password request page does not appear for verification. Can someone help me?

**Comment by doombot19400** [comment]
I have the same issue with fluxion v5.7

I'll try describing as much as i can.
ISSUE: I had previously used fluxion 0.24 and everything worked fine on my kali linux (2017.1) on a lenovo g580 laptop.
But now **everything works fine until I launch the fake AP,my samsung j7 doesn't show the"SIGN IN TO WIFI"  pop-up** bu i can visit the login page by manually entering the ip address in the browser.

I'm using fluxion v5.7 now with kali rolling 2019.1 but still the issues remains i.e. android device doesn't show a pop up showing 'SIGN IN TO THIS NETWORK' but works if i enter IP address manually.
now evil twin attack is not working just because the victim is not redirected to the login page.

I hope you guys  would do a bit more research on this.
I assume that android updates are the reason for this, and they just overcame the vulnerability.
 
regards!

**Comment by Tarek-Adra** [comment]
any updates ?
