### ISSUE TITLE
Cannot obtain IP Address

### ISSUE THREAD

**Issue by Anunayj** [FluxionNetwork/fluxion#401]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
The AP is created and Visible but devices cannot connect as they cannot obtain IP address. Manually Entering 192.168.254.1 in Browser on the Host Machine Works
#### If the current behaviour is a bug, please provide the steps to reproduce it.
Handshake Snooper Works Fine but when i use the Captive Portal in the start everything works fine and the AP is launched, but the mobile is not able to connect as it cannot obtain IP address

[Must have been some problem with DHCP] because when I manually enter a IP Address instad of DHCP (like 192.168.254.6) and gateway as 192.168.254.1. It connects, though no login prompt or redirection from any website to it. Though Manually Entering 192.168.254.1 Works 

#### What do you think the expected behaviour should be?

The Phone should be able to connect to the AP and a login page should be showed to Login.

#### Specs

[ FLUXION Info ]
FLUXION V3.11

[ BASH Info ]
GNU bash, version 4.4.18(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlp3s0) Info ]
Device: phy0
Driver: iwlwifi
Chipset: Intel Corporation Wireless 3160 (rev 93)
Injection Test: Injection is working!

[ XTerm Info ]
Version: XTerm(331)
Path: /bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /bin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.15.1-2-zen (builduser@heftig-16669) (gcc version 7.3.0 (GCC)) #1 ZEN SMP Sun Feb 4 22:27:39 UTC 2018

**_Packet Injection only works when i have manually Enabled Monitor mode using airmon-ng_** 

-----

**Comment by Anunayj** [comment]
Iwlwifi Driver supports these
    STA (Station) mode: supported
    IBSS (Ad-Hoc) mode: supported
    AP (Master) mode: supported, for a limited selection of hardware + firmware
    Mesh (802.11s) mode: unsupported
    P2P mode: supported, for Wilkins Peak (7260 + 3160) and later HW only
    Monitor mode: supported
    Packet injection: supported
Master Mod is Working (Checked by following wiki tutorial)

[source: [https://wikidevi.com/wiki/Iwlwifi](https://wikidevi.com/wiki/Iwlwifi)]

**Comment by deltaxflux** [comment]
Well, yes this sounds like it is a problem with the dhcp. Does the dhcp window even appear?

**Comment by Anunayj** [comment]
So mas it Appears I had a corrupted Installation of dhcpd (dhcp package on arch) and when Fluxion checked for it the files were already there.

**Comment by haxor-dot** [comment]
So how did you fixed the issue?

**Comment by cjb900** [comment]
@haxor-dot why are you posting to an issue that was closed and solved over 3 years ago. Also just posting "So how did you fixed the the issue?" clearly shows you didn't fully read this thread. They stated they had a corrupt instalation of dhcpd. So they probably reinstalled it and that fixed their issue. If that doesn't fix what ever issue you are having you are going to want to either open a new issue with as much detail on the exact issues you are having or join our discord for help.

**Comment by haxor-dot** [comment]
> @haxor-dot why are you posting to an issue that was closed and solved over 3 years ago. Also just posting "So how did you fixed the the issue?" clearly shows you didn't fully read this thread. They stated they had a corrupt instalation of dhcpd. So they probably reinstalled it and that fixed their issue. If that doesn't fix what ever issue you are having you are going to want to either open a new issue with as much detail on the exact issues you are having or join our discord for help.

My bad. I was just asking how he corrected the corrupt installation. btw, thanks.

**Comment by zararashigal** [comment]
> > [@haxor-dot](https://github.com/haxor-dot) why are you posting to an issue that was closed and solved over 3 years ago. Also just posting "So how did you fixed the the issue?" clearly shows you didn't fully read this thread. They stated they had a corrupt instalation of dhcpd. So they probably reinstalled it and that fixed their issue. If that doesn't fix what ever issue you are having you are going to want to either open a new issue with as much detail on the exact issues you are having or join our discord for help.
> 
> My bad. I was just asking how he corrected the corrupt installation. btw, thanks.

I have the same problem. Reinstalling did not fix it. Did you also fix your issue? If you did, mind sharing your way of achieving a fix?
