### ISSUE TITLE
No login page or authentication page 

### ISSUE THREAD

**Issue by Techsmobile** [FluxionNetwork/fluxion#403]
i didnt get login or authecation page whn i open it from chrome it doesnot loaded and 1 browser that i got to be loaded but very slow after 4 minute login page appear 
i have Alpha wireless card and with updated driver help

**Comment by FluxionPassion** [comment]
Same problem evereything ok when I connect the fake ap no login page

Wifislax Fluxion 3.1x

**Comment by deltaxflux** [comment]
Duplicate
