### ISSUE TITLE
Fluxion with pc?

### ISSUE THREAD

**Issue by ronak9099** [FluxionNetwork/fluxion#404]
Hi there, 

I have a question..on the fluxion ap dns service screen i can see that the target is connecting through web browser Firefox and other websites..but i dnt think the target is disconnected right? Which means this works only on someone who is connected to wifi on mobile? If someone is connected through pc.. what to do?

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by deltaxflux** [comment]
Please provide more information

**Comment by ronak9099** [comment]
I already gave you the all details..i am trying to hack my wifi i am connected to pc and not mobile..when i use fluxion its deauthenticating on the screen but me on pc using firefox..i see a msg request: www.firefox.com and ip address ap dns screen but i am still connected? I can use google..i can see request.www.google.com and ip address on the ap dns screen..but where do i log in so it ask me to login on the fake open wifi?

**Comment by deltaxflux** [comment]
If use https fluxion will not work flawlessly. However, you should see the captive portal if you type 192.168.254.1 does it appear?  Maybe there is something wrong with the lighttpd.

**Comment by MPX4132** [comment]
@ronak9099 Fluxion works for devices connected to the internet using WiFi. If your PC is connected to a WiFi access point, you should be affected by fluxion and should also be redirected like on mobile devices.
