### ISSUE TITLE
AWUS036ACH rtl8812au handshake snooper always searching hashes.

### ISSUE THREAD

**Issue by mailinneberg** [FluxionNetwork/fluxion#406]
Hello

Please help with rtl8812au, when I am using linux 2017.2 I can't install linux-headers-4.12.0 and no make&make install commands to finish installing v5.1.5
If I upgrade to 2018.1 and installing linux-headers-4.14 I had success with rtl8812au, but when I am starting to scan with fluxion my awus036ach is shutting down!

What happened please help.

**Comment by mailinneberg** [comment]
its OK
I found solution

**Comment by keralo** [comment]
really how?

**Comment by mailinneberg** [comment]
I had success with kali 2018.1 only https://forums.kali.org/showthread.php?36814-How-to-install-AWUS036ACH-Drivers-and-getting-it-running/page2

but handshake snooper always searching hashes((

how that fix?
