### ISSUE TITLE
Trouble cloning V4 Dev Branch

### ISSUE THREAD

**Issue by calee4nyaboy** [FluxionNetwork/fluxion#408]
I'm looking to test out the 5ghz capabilities of the Dev Branch but I am not able to clone it.  YES, I made an SSH key and followed the directions here:

https://github.com/FluxionNetwork/fluxion/wiki/Generate-ssh-keys

To be sure, I went through the procedure on that page twice but when I type:

git clone --recursive git@github.com:FluxionNetwork/fluxion.git

The results are:

root@nee:~# git clone --recursive git@github.com:FluxionNetwork/fluxion.git
Cloning into 'fluxion'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Not sure where I'm going wrong?!

**Comment by calee4nyaboy** [comment]
If there is a way I can download a .zip or a .rar of the dev branch and expand it on my laptop, can someone please provide instructions on where i can find that file?

**Comment by calee4nyaboy** [comment]
I found the zip file!  (I'm so used to cloning v3 that I wasn't sure if there was a zip file)

Are there any specific instructions I need to follow in order to install it on the laptop or is it as simple as expanding it in the directory of my choice?

**Comment by deltaxflux** [comment]
This is only for developers.
