### ISSUE TITLE
Issue template?

### ISSUE THREAD

**Issue by Geczy** [FluxionNetwork/fluxion#41]
Why? The template doesn't work anymore

`<!-- xxxxx -->` allows making Github comments that are shown to the user making an issue, but not shown in the post. It's perfect for asking for descriptions that we don't have to then read again when they submitted

Why was it removed? 

https://github.com/FluxionNetwork/fluxion/commit/17183fc25fe8fded13fa9d95fc1d0a6d747ede41

See below for what it looks like. Personally, reading issues with all this junk in there will take a LOT longer to decipher, read, and understand for the admins and other contributors

---

<p align="center"><img src="https://github.com/FluxionNetwork/fluxion/blob/master/logos/logo1.jpg?raw=true" /></p>

### Do you want to request a *feature* or report a *bug*?
-> *Bug*

----

### What is the current behavior?
-> *Quit accidentally*

---

#### If the current behavior is a bug, please provide the steps to reproduce.
-> *A great way to do this is to provide screenshots and commands.*

--- 

#### What is the expected behavior?
-> *Be creative*

---

### If this is a feature request, what is motivation or use case for changing the behavior?

---

#### Wireless adapter:
*Exact model, chipset, and driver versions.*

#### Does it support injection?
*Paste the output of `aireplay-ng -9`*

#### Fluxion version:
*Paste the output of* `cat fluxion.sh | grep revision`

#### Linux version:
*Paste the output of* `cat /proc/version` or `uname -r`

**Comment by Geczy** [comment]
Looked a lot better like this template below...

No useless junk that we have to read through. But the user making the issue will read it 


---

**Do you want to request a *feature* or report a *bug*?**


**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**


**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Wireless adapter:**


**Does it support injection?**


**Fluxion version:**

**Linux version:**

**Comment by Geczy** [comment]
The banner for example is completely unnecessary, and makes reading the issue even longer

**Comment by Geczy** [comment]
What does "be creative" even mean??

**Comment by deltaxflux** [comment]
I like this one more. It is well structured and this depends at personal behaviour.

**Comment by Geczy** [comment]
Lol I disagree, it has bad grammar and makes no sense. Good luck

**Comment by deltaxflux** [comment]
good luck
