### ISSUE TITLE
Where is the fluxion database to see the pass

### ISSUE THREAD

**Issue by elifish4** [FluxionNetwork/fluxion#411]
After successful capturing i got message: 
"success: A valid hash was detected and saved to fluxion's database"
But i don't see any pass on the terminal and not in the handshake_snooper.log file.

**Comment by strasharo** [comment]
It's not the password by the handshake that was saved to $FLUXIONPath/attacks/Handshake Snooper/handshakes/$APTargetSSIDClean-$APTargetMAC.cap". This is just the first stage of the attack.

**Comment by elifish4** [comment]
o ok... understood.
How can the password be shown after that with the fluxion tool?

**Comment by kbewolf** [comment]
hi,
look this [tutorial](https://k4linux.com/2018/03/how-to-fluxion-kali-linux-2018-1-hack-wifi.html)

**Comment by deltaxflux** [comment]
@kbewolf Mabye it helps but I don't think so.

**Comment by mrn1992** [comment]
did u find anything?

**Comment by TobiCooki** [comment]
> hi, look this [tutorial](https://k4linux.com/2018/03/how-to-fluxion-kali-linux-2018-1-hack-wifi.html)

link broken
