### ISSUE TITLE
Handshake not appearing

### ISSUE THREAD

**Issue by fastisbac** [FluxionNetwork/fluxion#412]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### What is the current behaviour?
Good.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
It's not a Bug. I do not know whether it is or not. I let the attack run for Hours it does not get the WPA HANDSHAKE. I think it's me only, Because I can't even get the Handshake with Airmon-ng.

#### What do you think the expected behaviour should be?
It should get the WPA Handshake.

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
What is this Location?^
-----

**Comment by strasharo** [comment]
In order to get a handshake you need to have active clients and be able to observe traffic from both the clients and the AP.
