### ISSUE TITLE
problem with stat .portal folder in attack folder

### ISSUE THREAD

**Issue by SiNaPsEr0x** [FluxionNetwork/fluxion#414]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
YES

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
I need create manually folder .portal in fluxion/attacks/Captive Portal/sites/
for stat command

-----

**Comment by deltaxflux** [comment]
You forgot to clone the sites
