### ISSUE TITLE
Fluxion 4 Error in file /root/fluxion/lib/Help.sh

### ISSUE THREAD

**Issue by disquette38** [FluxionNetwork/fluxion#415]
Hello,
In the version of fluxion4, there is an error at launch that concerns the /root/fluxion/lib/Help.sh file.
thank you for your work

**Comment by MPX4132** [comment]
I got it with [this commit](https://github.com/FluxionNetwork/fluxion/commit/2cd07dd57b5a8a423b5192c536de4a98cf2e762b), thanks man.
