### ISSUE TITLE
cp: cannot stat '/root/fluxion/attacks/Captive Portal/sites/.portal': No such file or directory

### ISSUE THREAD

**Issue by ighrdm** [FluxionNetwork/fluxion#421]
Hi,

I have this issue (see pic below) in Captive Portal.

Any idea?

I'll be grateful for any help. Thanks in advance

PS: I'm using Kali 2008.1

![screenshot from 2018-03-13 10-42-32](https://user-images.githubusercontent.com/30585188/37337994-fa024924-26ad-11e8-8239-882c5c2a2bfa.png)

**Comment by aquilabianca8** [comment]
Did you forget to clone portal routers..

Il giorno 13 mar 2018, alle ore 12:42, ighrdm <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hi,

I have this issue (see pic below) in Captive Portal.

Any idea?

I'll be grateful for any help. Thanks in advance

PS: I'm using Kali 2008.1

[screenshot from 2018-03-13 10-42-32]<https://user-images.githubusercontent.com/30585188/37337994-fa024924-26ad-11e8-8239-882c5c2a2bfa.png>

**Comment by ighrdm** [comment]
Thanks @aquilabianca8,

but aren't they cloned systematically with the command:

> git clone **--recursive** https://github.com/FluxionNetwork/fluxion.git

or maybe there's a manual way to clone portal routers? **Please Help!!!**

**NB:**

**1- All fluxion dependencies are auto-installed**
**2- I did download the submodules in fluxion's root directory with the following command:**
_git submodule update --init --recursive_
**I also download manually the sites from the [sites' repository](https://github.com/FluxionNetwork/sites) and extract them into:** _fluxion/attacks/Captive Portal/sites/_

**And the problem persist.**

Thanks for your time.
