### ISSUE TITLE
Downgrade

### ISSUE THREAD

**Issue by mrpopo12** [FluxionNetwork/fluxion#426]
is there any way to go back to a previous fluxion version as i am having alot of troubles with the 4.4 version.

**Comment by MPX4132** [comment]
You can download the stable versions from the [releases section](https://github.com/FluxionNetwork/fluxion/releases).

**Comment by mrpopo12** [comment]
yes the jamming does not seem to work as i am able to continue to browse my internet on a phone and tablet. But when i connect to the internet on a laptop jamming service seems to be working and wont let me connect to wiifi. i have to turn off then on again the wifi on the phone so i can see a change and then the jamming service starts working. i am using the alfa awus036nha adapter.

**Comment by MPX4132** [comment]
I use the same adapter for testing fluxion and it works perfectly fine, are you sure you're using the latest version? Are you using an up-to-date Kali linux machine?

**Comment by mrpopo12** [comment]
Discard my issue. i seem to have figured it out, it was the devices i was using to connect to the wifi.
