### ISSUE TITLE
QURIOSITY: DUAL BAND ATTACK

### ISSUE THREAD

**Issue by aquilabianca8** [FluxionNetwork/fluxion#427]
Just a quriosity:

Some router dual band have two different mac address: one work on 2,4ghz band, and the other work on 5ghz.
If we try to attack with Fluxion 2,4ghz band, we get only hansheke of that. Therefore the clients will reconnect to 5ghz band and our attack does not work..?

Thank you for your great work.

Thanks in advance.

**Comment by deltaxflux** [comment]
You got it.

**Comment by MPX4132** [comment]
Yeah, that’s a problem. We need to implement support for 5GHz first, though, but I agree that’s a problem.
