### ISSUE TITLE
Handshake Capture Issue

### ISSUE THREAD

**Issue by KaliLinuxB2A** [FluxionNetwork/fluxion#428]
In the terminal of capturing handshake ,there shows handshake.But there is not any handshake file in handshake directory and thus checking for handshake process continue in loop.

But some times the same version work when I reinstall the Kali OS.What was the exact solution for it ?

If the target AP changing the channel the jamming process doesn't work ,so put auto process to check channel on the target AP and attack on that channel immediately after the change found.

**Comment by deltaxflux** [comment]
Weird try to clean the handshake directory and restart fluxion. To make sure that you use the right / latest version do git pull -f 
Note: handshakes are **not** anymore in /root/handshakes/
