### ISSUE TITLE
Error: Your wireless card isnt supported AWUS036ACH

### ISSUE THREAD

**Issue by StratoMusic** [FluxionNetwork/fluxion#43]
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

BUG
----

### What is the current behavior?
-> *It is not letting me use my awus036ach..

---

#### Wireless adapter:
*Exact model, chipset, and driver versions.*

AWUS036ACH
Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
Driver 8812au

#### Does it support injection?
root@Valhalla:~# aireplay-ng -9 wlan0
05:37:41  Trying broadcast probe requests...
05:37:42  Injection is working!
05:37:43  Found 4 APs

#### Fluxion version:
*Paste the output of* `cat fluxion.sh | grep revision`
root@Valhalla:~/fluxion# cat fluxion.sh | grep revision
revision=10
        revision_online="$(timeout -s SIGTERM 20 curl "https://raw.githubusercontent.com/FluxionNetwork/fluxion/master/fluxion" 2>/dev/null| grep "^revision" | cut -d "=" -f2)"
        if [ -z "$revision_online" ]; then
                echo "$revision_online">$DUMP_PATH/Irev
        echo -e $red"                     FLUXION "$white""$version" (rev. "$green "$revision"$white") "$yellow"by "$white" ghost"
        revision_online=$(cat $DUMP_PATH/Irev)
        echo -e ""$white" [${purple}${revision_online}$white"$transparent"]"
                if [ "$revision_online" != "?" ]; then
                        if [ "$revision" -lt "$revision_online" ]; then
                                echo -ne $red"            New revision found! "$yellow
                                cp $0 $HOME/flux_rev-$revision.backup

#### Linux version:
4.9.0-kali4-amd64

**Comment by deltaxflux** [comment]
Please, note that nearly the same bug. Please use this #43 issue post. This would be not maintained
