### ISSUE TITLE
Handshake check appears invalid

### ISSUE THREAD

**Issue by KaliLinuxB2A** [FluxionNetwork/fluxion#432]
As you recommend the solution to clear the handshake directory and use the latest repository , yes i did all, but  I still face the problem. I wouldn't get the next step.

**Comment by KaliLinuxB2A** [comment]
I wouldn't get the next step, please fix it.

**Comment by deltaxflux** [comment]
Please do following:
`pip2 freeze | grep scapy`

**Comment by KaliLinuxB2A** [comment]
Still hanging on same step. I have tried tried with six usb wifi adapter it works in beginning of installing Kali Linux in my PC  but after some days
![screenshot from 2018-03-29 09-30-10](https://user-images.githubusercontent.com/32506305/38069230-c773b070-3304-11e8-96e1-db36fbc8b51b.png)

 it won't able to capture handshake now.

**Comment by deltaxflux** [comment]
Good luck, I don't help anybody who pwn himself twice.

**Comment by KaliLinuxB2A** [comment]
Still hanging on same step. I have tried tried with six usb wifi adapter it works in beginning of installing Kali Linux in my PC  but after some days
![Uploading Screenshot from 2018-03-29 09-30-10.png…]()

 it won't able to capture handshake now.

**Comment by KaliLinuxB2A** [comment]
I apologize for this.
