### ISSUE TITLE
No pop-up asking for WPA password after connecting to AP

### ISSUE THREAD

**Issue by gudangboys** [FluxionNetwork/fluxion#433]
Hi, in the latest version, I found that there is no pop-up (requesting for WPA password) immediately upon connecting to the rogue AP. 
Kindly advise.
Thanks lots

----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by energy1984** [comment]
Hi, I have the same problem, if I open the FAKE AP with SSL certificate does not open any page, if instead I remove the SSL certificate sometimes open the fake ap other times does not open it.

**Comment by khalidshaukat** [comment]
Same happening to me from last 2 days. here is output 
#### BASH Info 
GNU bash, version 4.4.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan0) Info 
**Device**: phy2
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### System Info
**Chipset:** Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-3)) #1 SMP Debian 4.14.17-1kali1 (2018-02-16)

**Comment by deltaxflux** [comment]
Please use this issue instead: https://github.com/FluxionNetwork/fluxion/issues/436
