### ISSUE TITLE
Error indicating .cap file path

### ISSUE THREAD

**Issue by f1r3walled** [FluxionNetwork/fluxion#435]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
It is not possible to advance with "Captive Portal" attack. After setting the interfaces it keeps recursively asking for the path to handshake file and doesn't matter what you indicate, nothing is accepted. I read the FAQ and I tried to manually indicate the path fluxion/attacks/Handshake Snooper/handshakes, but the folder handshakes doesn't exist inside fluxion/attacks/Handshake Snooper. In another attempt, I tried to execute only a "Handshake Snooper" attack supposing that it would create the .cap file mentioned in "Captive Portal" attack, but it doesn't create this file. I'm using Debian 9 Stretch and Fluxion version is 4.4

#### If the current behaviour is a bug, please provide the steps to reproduce it.
cd /opt
sudo git clone https://github.com/FluxionNetwork/fluxion.git
mv fluxion/
sudo ./fluxion
1. Captive Portal
1. wlp2s0 (My interface)
1. All channels
7. Target SSID
1. wlp2s0 (My interface)
1. wlp2s0 (My interface)
1. Rogue AP - hostapd (recommended)
Absolute path:

#### What do you think the expected behaviour should be?
It should advance with the attack once identified the right path.

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
_#### FLUXION Info
grep: ../fluxion: Is a directory
FLUXION V.

#### BASH Info 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlxc4e9840da01d) Info 
**Device**: phy6
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(327)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### System Info
Chipset: Linux version 4.14.0-0.bpo.3-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18)) #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14)_
-----

**Comment by deltaxflux** [comment]
Duplicate #436

**Comment by ylot0** [comment]
Why is the problem closed? How to solve it?
