### ISSUE TITLE
AP Jamming

### ISSUE THREAD

**Issue by zu3s** [FluxionNetwork/fluxion#437]
![screenshot from 2018-03-31 15-59-38](https://user-images.githubusercontent.com/34065997/38169105-8a414ac4-34fc-11e8-93cb-778db02f4968.png)
everything works fine till i get to the step of making the fake AP, and Jamming the "Real" AP. the web services window does not pop up , aswell as the AP jamming window statys at Periodically re-reading blacklist/whitelist every 3 seconds

help plz
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by deltaxflux** [comment]
Please check out the other issues to this topic. I answered this so many times and read the wiki.
