### ISSUE TITLE
Captive Portal (fake Login page) not showing.

### ISSUE THREAD

**Issue by faisal1391** [FluxionNetwork/fluxion#438]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
Fake login page does not show up and sites folder is empty.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
I ran the command `./script/diagnostics.sh [interface]`
Output:
#### FLUXION Info
grep: ../fluxion: No such file or directory
FLUXION V.

#### BASH Info 
GNU bash, version 4.4.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan0) Info 
**Device**: phy2
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### System Info
**Chipset:** Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-3)) #1 SMP Debian 4.14.17-1kali1 (2018-02-16)

#### What do you think the expected behaviour should be?
To show Dns window in Fluxion and to show the fake login page on the other device

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by deltaxflux** [comment]
Please read here #439

**Comment by TighTshiT** [comment]
i got same issue 
![screenshot from 2018-04-03 21-48-00](https://user-images.githubusercontent.com/31175602/38319423-50262fec-3864-11e8-9d37-c999a998cd8f.png)

**Comment by bobjones3333** [comment]
same here

**Comment by bobjones3333** [comment]
since new kali 2 update its done it only last few days was fine b4

**Comment by deltaxflux** [comment]
I removed any screenshots

**Comment by nghili96** [comment]
let try
`apt remove php-cgi`
it worked to me

**Comment by nghili96** [comment]
let try
 `apt-get remove php-cgi`
it worked to me
