### ISSUE TITLE
cant open the app

### ISSUE THREAD

**Issue by dunkydoggie** [FluxionNetwork/fluxion#45]
### Do you want to request a *feature* or report a *bug*?
-> *Bug*
i cant open the script i try cd fluxion the sudo ./fluxion it say command error not found

----

### What is the current behavior?
-> *Quit accidentally*

---

#### If the current behavior is a bug, please provide the steps to reproduce.
-> *A great way to do this is to provide screenshots and commands.*

--- 

#### What is the expected behavior?
-> *Be creative*

---

### If this is a feature request, what is motivation or use case for changing the behavior?

---

#### Wireless adapter:
*Exact model, chipset, and driver versions.*

#### Does it support injection?
*Paste the output of `aireplay-ng -9`*

#### Fluxion version:
*Paste the output of* `cat fluxion.sh | grep revision`

#### Linux version:
*Paste the output of* `cat /proc/version` or `uname -r`

**Comment by deltaxflux** [comment]
Closed:

Reason: You don't fill out the issue template.
