### ISSUE TITLE
Error, path points to non-existing or empty hash file.

### ISSUE THREAD

**Issue by ylot0** [FluxionNetwork/fluxion#451]
ubuntu 16.04 LTS
fluxion4.4

Problem: inputting the absolute path times wrong。

False hints:_**Error, path points to non-existing or empty hash file.**_

Loop has been required to input and grasp the absolute path of handshake package.

**Comment by nghtho94** [comment]
have you captured handshake successfully?

**Comment by ylot0** [comment]
No, this is a problem before the configuration.
