### ISSUE TITLE
Add domains other than google

### ISSUE THREAD

**Issue by whitepiratebaku** [FluxionNetwork/fluxion#454]
Hi,When  I use fluxion the page to enter password on fake AP  does not appear automatically ,Only appears when I go google.com .Now is it possible to add other urls which will pop up fake AP enter password page?like facebook,youtube and so.

**Comment by rad4day** [comment]
Every Domain will go to your fake page as the dns is rerouting all requests.

**Comment by whitepiratebaku** [comment]
What about dns cache on my phone, can dns cache prevent to go fake AP page?

**Comment by rad4day** [comment]
Well obviously your phone won't ask the dns service where to go if it has the domain in a local cache. Therefore it won't be redirected to the fake ap. I guess the same is true for all DNS devices which use a custom dns server. But I'd have to double check this, and if this is the case I'll probably write a patch for this behaviour during the next days.

**Comment by deltaxflux** [comment]
No this doesn't prevent you. Read here about the [DNS spoofing attack](https://en.wikipedia.org/wiki/DNS_spoofing)
