### ISSUE TITLE
after get install fluxion terminal says this following statement                                                                                        Can't open RFKILL control device: No such file or directory There are no wireless cards, quit...

### ISSUE THREAD

**Issue by shuttlebalaji** [FluxionNetwork/fluxion#457]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by deltaxflux** [comment]
Mhm hint: "There are no wireless cards". What does it mean?

**Comment by rad4day** [comment]
You are trolling right?

**Comment by DIBA99** [comment]
I have the same problem "No such file or directory
There are no wireless cards, SOME SOLUTIONS PLEAS
