### ISSUE TITLE
airbase-ng cant conect to fakeAP

### ISSUE THREAD

**Issue by hadi-dindar** [FluxionNetwork/fluxion#460]
hi dear friend 
i have a tl-wn727n  mt7601u driver 
and this chip cant support  AP mode . and i want to use airbase-ng

in this method i can create  fakeAP and disconnect . but when i connect to fake ap cant show any fake popup for writing password . ?

**Comment by rad4day** [comment]
>  this chip cant support AP mode
Therefore you shouldn't be able to host an Accesspoint.
Also we're not your personal support forum for seemingly unrelated questions.
Also please fill out the template, as this would give us at least a clue about what's wrong.

**Comment by Maxcom47** [comment]
@rad4day 
Can the TL-WN722N be used in AP mode?

**Comment by rad4day** [comment]
@Maxcom47 probably depends on the hardware version. If it's a V1 it can for sure.
https://wikidevi.com/wiki/TP-LINK_TL-WN722N
V2 is considered useless.

**Comment by rad4day** [comment]
Look at wikidevi for example. I don't own any tplink cards so I don't have anything on hand right now. You're looking for a device which includes "AP" or "master" in "Supported modes" of the `iw list` output. Should be enough to make an educated ~~google~~ duckduckgo search. @hadi-dindar

**Comment by hadi-dindar** [comment]
when i use airebase-ng
