### ISSUE TITLE
is this even possible ?!!

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#461]
if it's possible it will be great to add this to fluxion insted of the fake page scenario 
https://youtu.be/HoihKhQWZ7k

**Comment by rad4day** [comment]
It would probably be possible but 802.1x is like another world. Researching everything needed and packaging it in a way it's easy to run would take much time.

I like the idea though.

**Comment by minanagehsalalma** [comment]
@rad4day OK thanks for your opinion

**Comment by deltaxflux** [comment]
Agree to @rad4day

**Comment by minanagehsalalma** [comment]
@deltaxflux  i will do some researchers and post a new update

**Comment by minanagehsalalma** [comment]
@rad4day @deltaxflux i have found this [script ](https://github.com/Tylous/SniffAir) that

[+] Evil Twin - Creates a Fake Access Point, Clients Connect to Divulging MSCHAP Hashes or Cleartext Passwords
