### ISSUE TITLE
got a German languange login page for evil twin attack!

### ISSUE THREAD

**Issue by saintofinternet** [FluxionNetwork/fluxion#463]
hello
when i tried the evil twin attack today i was successful but the fake login page which the client mobile got was in German language. i had selected english language.

why would this happen?
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*No*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by rad4day** [comment]
Can you tell us exactly which page you selected for the attack? Is it a
persistent problem or was it a one off? Would be great if we knew this
for debugging purposes =)

Best regards,
Rad4day

**Comment by rad4day** [comment]
-- Closed --
As there was no further information provided.
