### ISSUE TITLE
segmentation fault on Backbox 5

### ISSUE THREAD

**Issue by azhari33** [FluxionNetwork/fluxion#467]
im using Backbox 5 and external adapter TP-LINK TL-WN722N

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?

[*] Handshake Snooper attack in progress...

	[1] Select another attack
	[2] Exit

[fluxion@Backbox]-[~] 1

**Segmentation fault (core dumped)**

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----
#### FLUXION Info
FLUXION V4.4

#### BASH Info 
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (fluxwl0) Info 
**Device**: phy1
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(322)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### System Info
**Chipset:** Linux version 4.13.0-38-generic (buildd@lgw01-amd64-027) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018

**Comment by rad4day** [comment]
OK that's a new one. As Fluxion is only a script automating the use of several binaries. It's one of those which dumps core. I could only blindly guess what went wrong with the information the debug script gives on that.

Could you do it again, and then check `sudo journalctl -xe` for the entry which explains more about the process which core dumps?  (should be one of the last) =)

**Comment by deltaxflux** [comment]
Lack of response.
