### ISSUE TITLE
LOOPING at start up (Kali Package management)

### ISSUE THREAD

**Issue by yazzi1018** [FluxionNetwork/fluxion#468]
loops at reading package list. again and again,
Err:1 http://http.kali.org/kali kali-rolling/main amd64 libisccfg-export168 amd64 (I wasn't able to screenshot this part)
404 Not found [IP: 192.99.200.113 80]

I tried disabling my internet. Doesn't work.

**Comment by rad4day** [comment]
Seems like your OS is trying to update packages / download dependencies
Your system has to be connected to the internet for this.

The Error tells us it didn't find the package it was looking for on said IP ( which is part of http.kali.org )

This is no bug with fluxion but a problem with your package management.

**Comment by deltaxflux** [comment]
Bug caused by fluxion confirmed

**Comment by deltaxflux** [comment]
Not in this case but in general there is a bug with wrong parameters.

**Comment by deltaxflux** [comment]
Edit: not wrong parameters but some functions can't get reached.
