### ISSUE TITLE
Fluxion preferences folder device full after handshake capture  

### ISSUE THREAD

**Issue by animus-hack** [FluxionNetwork/fluxion#474]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by animus-hack** [comment]
Fluxion runs as expected, captures handshake then when 'select new process' , then select language the response is : 'fluxion /preferences / device full ' . 
tried editing contents of preference folder and it says 'allocate disk space '. how to proceed?  fluxion is run from a disk drive.

**Comment by MPX4132** [comment]
This is a problem with your host machine. Your machine ran out of disk space, we can’t help you with that type of issue, you need to free space on your machine.

**Comment by deltaxflux** [comment]
Properly running kali linux live on a usb stick?
