### ISSUE TITLE
[Notice] Update function is not working

### ISSUE THREAD

**Issue by deltaxflux** [FluxionNetwork/fluxion#477]
I guess that fluxion should auto update or at least should ask the user for updates. It would be better since it is integrated in blackarch. Git submodules should be cloned on fly. Take a look tommorrow.

**Comment by MPX4132** [comment]
Check if [this commit](https://github.com/FluxionNetwork/fluxion/commit/d40dcb45075fa5e199d8bc569b9bd7d16c160ca0) fixed the issue.

**Comment by makmak05** [comment]
please fix !! handshake snooper are not working since update 4.4 to 4.6 when i select targaet and handshake attack using mdk3..it appears on my top screen  the "fix channel flux0w xx random number. i restart all things but same its happen. thanks i return to old 4.4v btw

**Comment by deltaxflux** [comment]
Confirmed working :)
