### ISSUE TITLE
Version 4.6 not stable for me kali linux 2016.2.

### ISSUE THREAD

**Issue by monday88** [FluxionNetwork/fluxion#478]
Dear deltaxflux,
Can you let me know what version kali linux you use?

I use windows 7 64bit SP1, 

Then VMware Workstation Pro 12.5.9 Build 7535481 setting debian 8.x 64bit.
http://\<redacted>

VMware image kali linux 2016.2
ftp://\<redacted>/\<username>/EH/Kali-Linux-2016.2-vm-amd64.7z

Only 3 version stable for me.
fluxion 2 v9 and fluxion 3.10/3.11
Now this version 4.6 my phone cannot connect.

**Comment by rad4day** [comment]
Whow. You shouldn't post either of those links. The 1st one seemed to be a residential connection with an open ftp running. And the seconds site clearly illegal.
I removed them for you.

Also you should REALLY update your software.

**Comment by monday88** [comment]
Dear rad4day,
Can you let me know what version kali linux support fluxion is stable?

**Comment by MPX4132** [comment]
@monday88 Kali rolling (the latest version), should be stable.

**Comment by monday88** [comment]
Dear MPX4132,
Is this version? Kali Linux Rolling 2016.1
Or can you give me VMware image?

**Comment by MPX4132** [comment]
@monday88 You can download the Kali iso and install it on your own virtual machine. You need to look into how to do that.

**Comment by vlldk** [comment]
Download the ISO [here](https://www.kali.org/) ans set it up yourself. Downloading images can be malicious and are often outdated.

**Comment by monday88** [comment]
Dear vlldk,
VMware image 2018.1 stable or not?

**Comment by MPX4132** [comment]
@monday88 That should be stable man. You should **never** have to download a vm image. That's extremely dangerous, since the vm could be loaded with malware which you're releasing into your network if the vm is connected to your local network.

**Comment by monday88** [comment]
Kali-Linux VMware 64-Bit [7z] 2018.1 ok or not

**Comment by vlldk** [comment]
VMware images can be found [here](https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-hyperv-image-download/). Also official.

**Comment by monday88** [comment]
@MPX4132 VMware is kali website give have this problem?

**Comment by MPX4132** [comment]
@monday88 I don't understand your question, sorry.

**Comment by monday88** [comment]
dear, vlldk.
2018 is stable for fluxion 4.6?

**Comment by vlldk** [comment]
Yes @monday88, 2018 should work perfectly with the latest versions of Fluxion

**Comment by monday88** [comment]
@MPX4132  easy to say, I want find version very very stable for fluxion 4.6, can you give me know version

**Comment by vlldk** [comment]
Again, @monday88 but I need to ask - do you know the logic behind this program and how to use Linux?
I don't understand your latest comment...

@rad4day just close it haha, it's not related to the Fluxion

**Comment by monday88** [comment]
Hope next version handshake will add number 5. never stop handshake
How often should the verifier check for a handshake?
       [1] Every 30 seconds (recommended).
	[2] Every 60 seconds.
	[3] Every 90 seconds.
	[4] Back
Because sometime I only want let people wifi cannot USE

**Comment by rad4day** [comment]
@vlldk you think so? :thinking: I'am reaaaaalllyyyyyy unsure about that. (/s)

@monday88 there are OTHER tools which fit this purpose, fluxion isn't intended to do what you want. Also please consider getting basic education regarding the following:

-  information security
-  public ftp
-  warez (especially why you shouldn't setup a public ftp filled with warez on your residential connection)
-  wifi (especially management frames)  

Then consider asking questions again. This is somewhat horrific.

**Comment by vlldk** [comment]
@rad4day Well, now that you ask... maybe we should re-open it to be sure? ;) 
@monday88 I firstly agree with @rad4day and regarding your latest comment i think you're looking for is a variant of an arp-spoofer that can block connections...

**Comment by monday88** [comment]
@vlldk Add number [5]. never check handshake
Let there never check handshake then non-stop block connections.
Easy don't let me find other software.
I know this very easy only add some linux code let there never chek

**Comment by rad4day** [comment]
Rude.

Then add it yourself. This is not what fluxion is intended to be.
