### ISSUE TITLE
Alfa 036NHA not supported in kali 2017.1?

### ISSUE THREAD

**Issue by colmoschin94** [FluxionNetwork/fluxion#48]
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

----

### What is the current behavior?
-> *After interface selection fluxion outputs that Alfa awus036nha is not supported*

---

#### If the current behavior is a bug, please provide the steps to reproduce.
-> *In Kali 2017.1 just run fluxion, select interface and channel to scan you'll get the error*

--- 

#### What is the expected behavior?
-> *to start the interface in monitor mode and scanning available wifi networks*

---

### If this is a feature request, what is motivation or use case for changing the behavior?

---

#### Wireless adapter:
*Alfa awus036nha*

#### Does it support injection?
*yes it does`*

#### Fluxion version:
*latest, cloned today (4/08/2017)*

#### Linux version:
*Kali Linux 2017.1 live without any update*

**Comment by strasharo** [comment]
Pull the latest version and retry.
