### ISSUE TITLE
Fluxion does not want to run

### ISSUE THREAD

**Issue by Fluxyy** [FluxionNetwork/fluxion#481]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
When i closed fluxion and i run the script, it just respondes with a loth of error messages saying:
./fluxion/fluxion.sh: line 286: installer_utils_check_dependencies: command not found and ./fluxion/fluxion.sh: line 287: installer_utils_run_dependencies: command not found

#### If the current behaviour is a bug, please provide the steps to reproduce it.
i go to ./fluxion/fluxion.sh and it runs

#### What do you think the expected behaviour should be?
I think it should run fine i guess?

#### If this is a feature request, what is the motivation or use case for the added feature?
It is not a feature request.
#### Specs
I cant find this?!

-----

**Comment by MPX4132** [comment]
@Fluxyy Something broke, you need to reclone/redownload the script.

**Comment by Fluxyy** [comment]
I cant redownload it because it is not a empty directory. how do i unistall/remove it through the terminal?

**Comment by djmeero** [comment]
sudo rm -rf fluxion and git clone ... again

**Comment by Fluxyy** [comment]
Yeah i already got it, thanks anyways 👍 :)

**Comment by Fluxyy** [comment]
When i recloned it, i had the same issue.

**Comment by Fluxyy** [comment]
![image](https://user-images.githubusercontent.com/38797100/39396669-bdce9b60-4af2-11e8-8c36-04f78451813a.png)
This just runs
