### ISSUE TITLE
Mdk3 at last not running

### ISSUE THREAD

**Issue by JunaidShafi** [FluxionNetwork/fluxion#484]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
You need to fix the title of this issue, it doesn't make sense at all, and you need to fill out the template, otherwise I'll have to close the issue.

**Comment by JunaidShafi** [comment]
The thing is mdk3 isnt deauthenticating the newer phones neither is aireplay
