### ISSUE TITLE
Fluxion does not want to run 2.0

### ISSUE THREAD

**Issue by Fluxyy** [FluxionNetwork/fluxion#485]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
Fluxion does not want to run

#### If the current behaviour is a bug, please provide the steps to reproduce it.
I cloned it via *git clone https://github.com/FluxionNetwork/fluxion.git* then run fluxion/fluxion.sh and then i get this 
![39396669-bdce9b60-4af2-11e8-8c36-04f78451813a](https://user-images.githubusercontent.com/38797100/39397371-888ac530-4afe-11e8-9564-65eb731fcfc2.png)

#### What do you think the expected behaviour should be?
I think it should run fine i guess?

#### If this is a feature request, what is the motivation or use case for the added feature?
Its not a feature request
#### Specs
![image](https://user-images.githubusercontent.com/38797100/39397388-bc89be68-4afe-11e8-85dc-5aaf700021be.png)

-----

**Comment by rad4day** [comment]
Fluxion still doesn't handle it well if it's called from outside it's directory. It seems.

**Comment by Fluxyy** [comment]
I found the solution, --> *cd fluxion/* enter *./fluxion.sh
