### ISSUE TITLE
fluxion unable to rename my card

### ISSUE THREAD

**Issue by sagerpager** [FluxionNetwork/fluxion#488]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### If the current behaviour is a bug, please provide the steps to reproduce it.
<Allocating reserved interface wlan0.
[*] Unblocking all wireless interfaces.
[*] Renaming interface.
[*] Starting monitor interface...
[*] Interface reservation failed!>

#### Specs
my monitor mode is working fine but fluxion isnt working
[*] Select a wireless attack for the access point

                      ESSID: "[N/A]" / [N/A]                                    
                    Channel:  [N/A]                                             
                      BSSID:  [N/A] ([N/A])                          

	[1] Captive Portal Creates an "evil twin" access point.
	[2] Handshake Snopper Acquires WPA/WPA2 encryption hashes.
	[3] Back 

[fluxion@kali]-[~] 1

[+] Allocating reserved interface wlan0.
[*] Unblocking all wireless interfaces.
[*] Renaming interface.
[*] Starting monitor interface...
[*] Interface reservation failed!

-----

**Comment by strasharo** [comment]
What wireless adapter are you using?

**Comment by sagerpager** [comment]
i ran the script here is my output:
#### FLUXION Info
FLUXION V4.7


#### BASH Info 
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** wl
**Chipset:** Broadcom Limited BCM43142 802.11b/g/n (rev 01)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Operation not supported
ioctl(SIOCSIWMODE) failed: Operation not supported
Failed


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### System Info
**Chipset:** Linux version 4.15.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-11)) #1 SMP Debian 4.15.11-1kali1 (2018-03-21)
-------------------- I think my card doesn't support injection . Thanks for the help buddy.

**Comment by MPX4132** [comment]
@sagerpager yeah, sorry, it appears your device does not support injection.

> Injection Test: ioctl(SIOCSIWMODE) failed: Operation not supported
> ioctl(SIOCSIWMODE) failed: Operation not supported
> Failed
