### ISSUE TITLE
Fluxion 4.6 not show out fake AP let people connect in kali linux 2018.1

### ISSUE THREAD

**Issue by monday88** [FluxionNetwork/fluxion#490]
Dear,
I use kali linux 2018.1
Atheros AR9271 USB wireless.
Why not show fake AP let people connect?
Kali linux 2016.2 use fluxion v3.11 no problem.

**Comment by rad4day** [comment]
Please fill out the template.

**Comment by rad4day** [comment]
Yeah let me take a look at my mystic 8 ball...
It's your toaster.

No seriously, I cannot help you without more sophisticated information about your system and what you do prior to the error.
