### ISSUE TITLE
AP Bssid in Chinese couldnt be done

### ISSUE THREAD

**Issue by huxibei** [FluxionNetwork/fluxion#496]
hi bro，AP 's Bssid in Chinese couldnt be correctly work with all version fluxion.

**Comment by MPX4132** [comment]
@huxibei That's a know issue, however, it's an issue with `airodump-ng`, not fluxion.

You can try it yourself. Run airodump-ng alone and log the output to a file:
```
airmon-ng start wlanX
airodump-ng -w data wlanXmon
# Interrupt it (ctrl+c) when the target BSSID is found
more data-01.csv
```
**You'll see the BSSIDs' field all garbled due to some unicode bug with airodump-ng**

**Comment by usama7628674** [comment]
@huxibei If you're using aircrack 1.2-rc4 then please update to newer version which is 1.2 and try again.If that doesn't work then raise the issue on aircrack repository.

**Comment by MPX4132** [comment]
Yeah, I just took a look at airodump-ng's source code, what a shit fest. It's written in C, but it's a damn mess.

**Comment by deltaxflux** [comment]
**You could report [here](https://github.com/aircrack-ng/aircrack-ng)**

**Comment by MPX4132** [comment]
They've already got the [issue here](https://github.com/aircrack-ng/aircrack-ng/issues/1790) on march 10th about it. It's put down as enhancement, so chances are it'll be a while before they fix it. I looked at their source to try and fix it myself but there's practically no comments on the code, it's a damn mess, and they even dared to use C's `goto` statement. That's just my opinion, though.

**Comment by ChunshengZhao** [comment]
https://github.com/aircrack-ng/aircrack-ng/pull/1840

**Comment by MPX4132** [comment]
@ChunshengZhao Have you tried fluxion with the latest version of aircrack-ng? I haven't checked whether it works or not, since I haven't tried building it and checking. Looks like the issue was resolved, so that should finally fix the non-ascii overrun bug.

**Comment by ChunshengZhao** [comment]
It seems normal.
![20180531100449](https://user-images.githubusercontent.com/9263377/40757395-db722920-64ba-11e8-9e7a-ed2bbf5d9874.jpg)
![20180531100527](https://user-images.githubusercontent.com/9263377/40757394-db195d0e-64ba-11e8-8cd2-48d71a28ebe2.jpg)

**Comment by MPX4132** [comment]
Awesome, now people can stop complaining lol, thank you man.
