### ISSUE TITLE
Fake AP cannot connect sometime cannot show in kali linux 2018.1

### ISSUE THREAD

**Issue by monday88** [FluxionNetwork/fluxion#497]
Dear,
I use in official Kali Linux 64 bit VMware VM, then install fluxion v4.7
https://www.kali.org/downloads/3/
Then sudo apt-get update
After then install fluxion
Will have this problem.

**Comment by rad4day** [comment]
No Issue description provided.

**Comment by MPX4132** [comment]
@monday88 Like @rad4day said, you need to fill out the issue template man.
