### ISSUE TITLE
Not able to deselect interface 

### ISSUE THREAD

**Issue by monomaki2035** [FluxionNetwork/fluxion#501]
Hello I'm having an issue deselect my interface when I start fluxion it automatically selects my external wireless adapter I tried to starting fluxion with the "export FLUXIONWIKillProcesses=1;" flag without quotes of course and it still doesn't deselect the the external wireless adapter  any help would be golden keep up the awesome work

**Comment by deltaxflux** [comment]
**Well you did like following?:**
```
su root
export FLUXIONWIKillProcesses=1
./fluxion.sh
```
**You could also use since fluxion 4 -k or --killer like:**
```
./fluxion -k
```

**Comment by monomaki2035** [comment]
Man I'm a reel dummy that did the trick thanx for the help I owe you guys a beer
