### ISSUE TITLE
Adding cowpatty to dependencies install

### ISSUE THREAD

**Issue by djmeero** [FluxionNetwork/fluxion#502]
Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
*Yes*

#### Do you want to request a *feature* or report a *bug*?
*Feature*

#### What is the current behaviour?
*It's all ok just add cowpatty to dependencies list.*

#### What do you think the expected behaviour should be?
*Automatically install cowpatty for lazy people =)*

-----

**Comment by deltaxflux** [comment]
Thanks I will do.
