### ISSUE TITLE
login page not show on device...

### ISSUE THREAD

**Issue by yoriatet** [FluxionNetwork/fluxion#504]
Hi,,

i have install fluxion V4.10 in usb live boot, it is fist time to use fluxion for me
and was tried to run this program.
i was create foke AP, but why my android can not show login page (captive.gateway,lan)?
i just see white screen on my device (android grand duos with RR rom).
i try to wait around 2 minutes, but the login screen still not showing.
what is it wrong? please advice

**Comment by rad4day** [comment]
My advice would be to run the Diagnostics script and post it's output. Like it was statet in the Issue template. Otherwise we can do nothing but taking wild guesses.

**Comment by MPX4132** [comment]
@yoriatet Can you take a screenshot of what you seen on your phone when it attempts to redirect to `captive.gateway.lan`?

**Comment by yoriatet** [comment]
![login page](https://user-images.githubusercontent.com/39051583/39733913-20e61d6e-529f-11e8-913e-c0bfae17b872.png)
only show like this in my device

**Comment by yoriatet** [comment]
![kali](https://user-images.githubusercontent.com/39051583/39734572-128da0cc-52a2-11e8-8732-0525b46dd79f.jpg)
this is the screen when i am running Fluxion V4.10.

Thanks
Best Regards,
Yori

**Comment by MPX4132** [comment]
@yoriatet Thanks for the very good images.
Can you try the following for us:
* Launch the Captive Portal attack
* Open a private tab on Chrome
* Navigate to `http://captive.gateway.lan`
Make absolutely sure to set **http** as the protocol, **not https.**
* Check if it loads

**Comment by MPX4132** [comment]
@yoriatet Just for your information, if your device has a custom DNS set, it'll have issues with fluxion. You mentioned it's a custom ROM, make sure it doesn't have a custom DNS set. It doesn't seem like it, though, since the DNS log shows queries which likely came from the device.

**Comment by yoriatet** [comment]
@MPX4132. Yes this problem only happen in my device only.
just now i tested with HUAWEI nova 2 lite, it is working normally.
may be this is effect from custom rom .

Thanks you for your support.
