### ISSUE TITLE
Nothing happens after starting captive portal access attack

### ISSUE THREAD

**Issue by luciferlightz7** [FluxionNetwork/fluxion#506]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
*Yes*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
fluxion freezes 

#### If the current behaviour is a bug, please provide the steps to reproduce it.
I'm able to get handshakes, but when I try the captive attack (with every possible configuration) it freezes at 

[*] Starting Captive Portal acess point service...

And nothing happens
#### What do you think the expected behaviour should be?
I followed the same steps on another computer and worked just fine

#### FLUXION Info
FLUXION V4.10

#### BASH Info 
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlp3s0mon) Info 
**Device**: phy0
**Driver:** iwlwifi
**Chipset:** Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(332)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 4.15.0-kali3-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-16)) #1 SMP Debian 4.15.17-1kali1 (2018-04-25)

-----

**Comment by rad4day** [comment]
My guess is that either some library is not working as expected, or that the driver for the Intel Centrino card is reporting false information and doesn't support AP mode.
---
If I understand [wiki devi](https://wikidevi.com/wiki/Intel_Centrino_Advanced-N_6205) right it only supports one virtual Interface at a time. So you can't use it to deauth and host the AP at the same time. I'll probably test this next week (I have one of those here, too)

I'm just busy right now and can't install it to test sorry :/
