### ISSUE TITLE
Cannot start Captive Portal service with internal wifi card 

### ISSUE THREAD

**Issue by stevanuscolonne** [FluxionNetwork/fluxion#509]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
Cannot start Captive Portal with internal wifi card

#### If the current behavior is a bug, please provide the steps to reproduce it.
After choosing captive portal generic language, starting captive portal service and stuck at there without being able to stop it (using Ctrl+c also cannot) but if using external wifi there is no problem at all

#### What do you think the expected behaviour should be?
Able to start captive portal service and launch captive portal with internal wifi card

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V4.10

#### BASH Info 
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k
**Chipset:** Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(332)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 4.15.0-kali3-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-16)) #1 SMP Debian 4.15.17-1kali1 (2018-04-25)
-----

**Comment by MPX4132** [comment]
Considering the fact you're using the `ath9k` driver, you shouldn't be having any issues. Give us a detailed description (literal step-by-step) of the options you're choosing to start the attack.

**Comment by usama7628674** [comment]
@stevanuscolonne It's a bug in kernal 4.15.Could you post the log of `dmesg` after captive portal hangs?

**Comment by stevanuscolonne** [comment]
I also tried earlier fluxion version 4.4. The result is same. I think there is something wrong with kali settings. I use Kali 2018.2 and have done apt-get update, apt-get upgrade & apt-get dist-upgrade previously before this error happened.

**Comment by stevanuscolonne** [comment]
@usama yes that the same thing appeared in my dmesg. But i cannot post the screen shot because my laptop still freeze waiting to reboot which currently running for "a stop job  for raise network interfaces.

Any work around for this kernel problem? And how to kill related process? Because it takes so long to reboot due to unkilled network related process.

**Comment by usama7628674** [comment]
@stevanuscolonne My laptop also freeze and takes a lot of time to reboot and shutdown.Right now you can either downgrade your kernal and see if it works or use kali linux 2018.1 which comes with 4.14 kernal.

**Comment by stevanuscolonne** [comment]
@usama7628674 yes that the same thing appeared in my dmesg. But i cannot post the screen shot because my laptop still freeze waiting to reboot which currently running for "a stop job for raise network interfaces.

Any work around for this kernel problem? And how to kill related process? Because it takes so long to reboot due to unkilled network related process.

(sorry repeated comment to use correct tag)

**Comment by stevanuscolonne** [comment]
@MPX4132 i got through the same steps as usual I did. After succesfully captured handshakes, then i choose captive portal attack, verify the handshakes and disable ssl, choosing generic captive portal (no. 7 english) then starting captive portal service and freeze.

@usama7628674 I managed to capture the screen but still waiting for another reboot again. Will post the screen shot soon.

(repeated comment to used the correct tag)

**Comment by stevanuscolonne** [comment]
@usama7628674 here are the screen-shots:

![screenshot from 2018-05-12 16-18-18](https://user-images.githubusercontent.com/24591481/39956192-f5cfd74a-5605-11e8-860f-f078017e554c.png)

![screenshot from 2018-05-12 16-17-03](https://user-images.githubusercontent.com/24591481/39956211-2c161e68-5606-11e8-84eb-4633bfce11cf.png)

**Comment by MPX4132** [comment]
It seems you've got an answer to the issue, so I'm closing it. If you need more help feel free to reopen the issue.
