### ISSUE TITLE
Fluxion stucks, and own made sites...

### ISSUE THREAD

**Issue by sersajar** [FluxionNetwork/fluxion#510]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
not a bug

#### What is the current behaviour?
It stucks at some point, An image is better....

#### If the current behaviour is a bug, please provide the steps to reproduce it.

![flux](https://user-images.githubusercontent.com/16085139/39959633-bd2eae5c-5614-11e8-9919-fc714c18e4a3.jpg)

#### What do you think the expected behaviour should be?
It is suposed to see some clients connected, and so on...

#### If this is a feature request, what is the motivation or use case for the added feature?

I would like to know where to put my own sites, I tried in /sites, but they dont appear.

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V4.10

#### BASH Info 
GNU bash, versión 4.4.19(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licencia GPLv3+: GPL de GNU versión 3 o posterior <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0mon) Info 
**Device**: phy0
**Driver:** iwlwifi
**Chipset:** Intel Corporation Wireless 7260 (rev 73)
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/bin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'VERSION'
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.16.8-1-ARCH (builduser@heftig-7043) (gcc version 8.1.0 (GCC)) #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018

-----

**Comment by MPX4132** [comment]
To get your custom portals working (in sites), you have to prepare it to work with fluxion first. [Here’s the guide](https://github.com/FluxionNetwork/fluxion/wiki/Preparing-portals-for-fluxion) on how to do it.

**Comment by MPX4132** [comment]
I've answered your question, if you need more info feel free to comment below or reopen the issue if we still haven't solved your problem.
