### ISSUE TITLE
compatty  error

### ISSUE THREAD

**Issue by jack00000** [FluxionNetwork/fluxion#513]
![](http://oyj1fkfcr.bkt.clouddn.com/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_20180513233518.png)

**Comment by strasharo** [comment]
What distribution is that? Just install cowpatty.

**Comment by MPX4132** [comment]
You need to install cow patty somehow, for your distro. It should’ve automatically been installed, but it looks like your sister doesn’t have it available or something.
