### ISSUE TITLE
fake acces point

### ISSUE THREAD

**Issue by zenos** [FluxionNetwork/fluxion#514]
----hi all,
the  problem is now i can't create automatically a fake access point when using captive portal , i have tried and old fluxion version its still the same ,previously i haven't this problem .ima using RTL8187 AWUS036H and kali 2007.1 tried 2018.2 too, wifislax  please realy need help "sorry for my poor english"

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by strasharo** [comment]
RTL8187 is not compatible with hostapd, it only works with airbase-ng.
