### ISSUE TITLE
Interface Reservation failed

### ISSUE THREAD

**Issue by Krishsinghal123** [FluxionNetwork/fluxion#515]
#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
After selecting the interface, it gives error-'Interface Reservation Failed'.

#### If the current behaviour is a bug, please provide the steps to reproduce it.
I'm using the latest fluxion(4.0), after selecting the network interface, it produces an error-'Interface reservation failed'. Attached are the screenshots.

![gnome-shell-screenshot-3nwpiz](https://user-images.githubusercontent.com/29298488/40094302-cd26efa0-58e3-11e8-8c86-8278093096cb.png)
![gnome-shell-screenshot-e7uoiz](https://user-images.githubusercontent.com/29298488/40094303-cd74d1fc-58e3-11e8-85f2-b03a424680df.png)
![gnome-shell-screenshot-lowriz](https://user-images.githubusercontent.com/29298488/40094305-cdd5ae32-58e3-11e8-8044-d6a9c6f6864f.png)
![gnome-shell-screenshot-ozmxiz](https://user-images.githubusercontent.com/29298488/40094306-ce258196-58e3-11e8-9714-ac0d7a24d3ac.png)

#### What do you think the expected behaviour should be?
Since the network card is supported for attack, this should work, it might be an error due to package or library. Network card is Broadcom 4360, it is supported.

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
Usage ./scripts/diagnostics [wireless_interface]

-----

**Comment by MPX4132** [comment]
You need to **run the diagnostics script** like it says on the issue template, we need info about your system.
Also, try running fluxion with the `airmon-ng` flag to see if it makes a difference.
```
./fluxion.sh -n
# Alternatively, use the verbose flag
./fluxion.sh --airmon-ng
```

**Comment by Krishsinghal123** [comment]
The diagnostic script yields this result. 

#### Interface ([wlan0]) Info 
**Device:** Unknown
basename: missing operand
Try 'basename --help' for more information.
**Driver:** Unsupported
**Chipset:** 
**Master Modes** Yes
**Injection Test:** ioctl(SIOCGIFINDEX) failed: No such device
Failed


#### XTerm Infos
**Version:** XTerm(332)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.15.0-kali3-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-16)) #1 SMP Debian 4.15.17-1kali1 (2018-04-25)

**Comment by MPX4132** [comment]
Please run the following and post the output:
```
airmon-ng
```

**Comment by MPX4132** [comment]
Run and paste the output of the following:
```
airmon-ng start wlan0
```
Show us the output.

Afterwards, if the command was successful, reverse the command with:
```
airmon-ng stop wlan0mon
```

**Comment by Krishsinghal123** [comment]
I tried the dictionary attack before fluxion, but that didn't seem to capture a handshake(don't know why), and it did capture one my hotspot once but not again.

**Comment by MPX4132** [comment]
@Krishsinghal123 I think you have driver issues, but I don't really know man. I've never seen airmon-ng output that before.

**Comment by MPX4132** [comment]
@Krishsinghal123 Yeah, it looks like it might still have [problems](https://forum.aircrack-ng.org/index.php?topic=1178.0).

**Comment by Krishsinghal123** [comment]
But my network card is in monitor mode, then what is the problem, downloading a different would solve the problem??

**Comment by Krishsinghal123** [comment]
I killed network manager before starting the attack.

**Comment by MPX4132** [comment]
@Krishsinghal123 The network manager is stopped automatically when the attack is launched. Have you actually tried to manually capture a handshake? You should check whether you can do that.

**Comment by Krishsinghal123** [comment]
Nope manually its not working that's why I moved to fluxion.

**Comment by MPX4132** [comment]
@Krishsinghal123 Fluxion automates the manual attack man, if it doesn't work manually, fluxion will not work. Again, you probably have driver issues which might be why monitor-mode isn't working.

**Comment by MPX4132** [comment]
You can try looking for alternative drivers, but there's a high chance you won't find any. It's a Broadcom card you're using, and they're known to do that.

**Comment by Krishsinghal123** [comment]
Monitor mode is working.
For the command
1. airodump-ng wlan0mon. Output:

![airod](https://user-images.githubusercontent.com/29298488/40222964-f938a5a4-5a9e-11e8-9fbe-f8bd9a61d727.png)
2. airodump-ng -c 1 --bssid [bssid ] -w [path to write data] prism0. Output:
![airod1](https://user-images.githubusercontent.com/29298488/40222965-f9a910f0-5a9e-11e8-9879-f5a8e0a385dc.png)
3. aireplay-ng --deauth 10 -a[router bssid] prism0. Output:
![aire](https://user-images.githubusercontent.com/29298488/40223063-5f575eca-5a9f-11e8-9904-62b0c9ae5d68.png)

If this doesn't work what shall I do?

**Comment by MPX4132** [comment]
@Krishsinghal123 You're giving us conflicting information. You said
> Nope manually its not working that's why I moved to fluxion.
Then showed the opposite on the images, monitor mode working and capturing.

**Comment by MPX4132** [comment]
What's `prism0`? Why did you use that instead of wlan0mon?

**Comment by Krishsinghal123** [comment]
What I was trying to say is that I was unable to capture a handshake
manually, although I did capture once but that didn't happen again. Prism0
is the interface, it is used instead of wlan0.

**Comment by MPX4132** [comment]
@Krishsinghal123 Why are you using `prism0` instead of the standard `wlan0mon`? Fluxion offers no support for special cases, and `prism0` is definitely a special case.

**Comment by Krishsinghal123** [comment]
![interface](https://user-images.githubusercontent.com/29298488/40265760-3d495b0e-5b5c-11e8-9ec7-4b84012cbe85.png)


That may be the case but now that we know the problem is there any way we can resolve it, by making some changes in the script?

**Comment by MPX4132** [comment]
You used the `prisim0` interface for deauthentiacation:
> aireplay-ng --deauth 10 -a[router bssid] prism0.

That is non-standard behavior and is not supported by fluxion.

**Comment by Krishsinghal123** [comment]
![wlan0](https://user-images.githubusercontent.com/29298488/40265805-ee5b37aa-5b5c-11e8-9198-fa1582aefd93.png)

If I use wlan0 this is the output. Manual case.

**Comment by Krishsinghal123** [comment]
Are you telling me that manual attack which I'm trying to do is not correct?

**Comment by MPX4132** [comment]
@Krishsinghal123 I'm telling you you're doing something that isn't typically done, at least not that I know of.

1. Check for which interface you want to use by running the following and picking an interface.
```
airmon-ng
```

2. Change the interface you picked in step 1 to monitor mode, for example `wlan0`.
```
airmon-ng start wlan0
```
That should create a new interface, for example, `wlan0mon`

3. Use that interface with airodump-ng, and use a target channel, for example, channel 1:
```
airodump-ng -c 1 wlan0mon
```

4. Run aireplay-ng on that same interface, not `prism0` or whatever other weird interface.
```
aireplay-ng ... OPTIONS_HERE ... wlan0mon
```

**Comment by MPX4132** [comment]
Yeah, that won’t work with fluxion, it’s using a different format. I’ll take a look at it sometime tomorrow.

**Comment by MPX4132** [comment]
@Krishsinghal123 I added support for prism[0-9]+ interfaces, clone the latest commit and try it using the `airmon-ng` flag (`-n` or `--airmon-ng`). **You must use the airmon-ng flag** since fluxion doesn't support those prism[0-9]+ interfaces.
```
./fluxion.sh -n
# or the verbose flag
./fluxion.sh --airmon-ng
```
If that doesn't work, chances are your card driver definitely has issues, particularly, with virtual interfaces.
If that's the case, you'll have to use [this guide](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!) to check yourself whether or not your card supports virtual interfaces.

**Comment by Krishsinghal123** [comment]
Thanks to you, I've got past that issue but when I choose either attack it shows something for a fraction of second and then return back on the same page.

**Comment by MPX4132** [comment]
Run it in debug mode:
```
./fluxion.sh -nd
# or the verbose flags
./fluxion.sh --airmon-ng --debug
```
However, you'll have to reset the interfaces manually, with airmon-ng, or by restarting your system.

**Comment by Krishsinghal123** [comment]
![fluxnew](https://user-images.githubusercontent.com/29298488/40299274-60fd1c72-5d03-11e8-8250-26907bdad187.png)

It scans for the APs but shows no result, tried both attacks and all channel options.

**Comment by Krishsinghal123** [comment]
![fluxnew](https://user-images.githubusercontent.com/29298488/40299274-60fd1c72-5d03-11e8-8250-26907bdad187.png)

It scans for the APs but shows no result, tried both attacks and all channel options.

**Comment by MPX4132** [comment]
Looks like driver issues to me. I’m closing this.

**Comment by BoxuanZng** [comment]
I met it too.
My fluxion's version is 6.9

**Comment by cjb900** [comment]
@BoxuanZng you can't just post to an issue that been closed for over 3 years and just say "I met it too.
My fluxion's version is 6.9" with out giving any information on your set up. like what OS you are using? Is said OS installed natively or are you running it in a VM? What wifi adapter and chiset do you have? A screenshot of the error you are getting always helps too.
