### ISSUE TITLE
hask shake cupture error

### ISSUE THREAD

**Issue by kharadi** [FluxionNetwork/fluxion#516]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*
#> _IceTransSocketUNIXConnect: Cannot connect to non-local host localhost
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost
Warning: Tried to connect to session manager, Could not open network socket
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost
Warning: Tried to connect to session manager, Could not open network socket

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
I've never seen that before, but by the look of it, it has nothing to do with fluxion, since it's a unix socket, and fluxion does not mess with that.
