### ISSUE TITLE
Fluxion cap Missing after hand shake. New UPDATE 2018 MAY 23

### ISSUE THREAD

**Issue by Impromenot** [FluxionNetwork/fluxion#517]
How To Find The Handshake Cap file. Im New About this or what do i type on Command line to find the cap file of the handshake. Sample " root/Desktop/fluxion"

**Comment by MPX4132** [comment]
You need to run the `Handshake Snooper` attack first, which will retrieve the handshake file. After the attack succeeds you can launch the `Captive Portal` attack.

You need to read the wiki, everything’s explained there.
