### ISSUE TITLE
Do you try in VM kali linux 2018.2?

### ISSUE THREAD

**Issue by monday88** [FluxionNetwork/fluxion#519]
Dear Mr/Miss,
Do you try in VMWare kali linux 2018.2 OFFICIAL?
https://www.kali.org/downloads/
I try in VMWare kali linux 2018.2 handshake so so slow capture.
Now I vmware kali linux only can use v3.10 stable.
Please download Office VMWare kali linux 2018.2 OFFICIAL try your fluxion v4.10.

**Comment by deltaxflux** [comment]
> I try in VMWare kali linux 2018.2 handshake so so slow capture.

This has nothing to do with the VM in general.

**Comment by strasharo** [comment]
![image](https://user-images.githubusercontent.com/3337997/40478322-66d1b7d4-5f51-11e8-99d7-e8c6f87fd6be.png)

**Comment by monday88** [comment]
@deltaxflux 
Thank your reply.
After then I use samsung handphone cannot connect fake AP.
Old version 3.10 stable no problem. Now only can use v3.10.
I use USB Ralink RT3070 wifi.
VMware kali linux 2016.2 fluxion v3.10 no problem, 
now use vmware kali linux 2018.2 fluxion 4.10 fake AP samsung handphone cannot connect.
Please download wmware kali linux 2018.2 then try your fluxion v4.10.

**Comment by monday88** [comment]
@MPX4132 
You go to kali linux official website download VMware kali linux 2018.2, then install fluxion will know.
I not professional check the fluxion problem.
I sure fake AP will not connect, 3v10 no problem every thing good.

**Comment by MPX4132** [comment]
@monday88 Please post screenshots of every option you choose on fluxion?
