### ISSUE TITLE
Target can't connect on my Fake AP

### ISSUE THREAD

**Issue by C0D3K1LL3R** [FluxionNetwork/fluxion#520]
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?

 It's Running

#### What do you think the expected behaviour should be?

The Clients of Targets Won't connect on my FakeAp when Using now  the captive Portal
I'm Ubuntu User
#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by MPX4132** [comment]
@C0D3K1LL3R Are you, by any chance, selecting a target tracking interface? If you did **not select skip**, you have to make sure you have two different wireless devices. If you do NOT have two wireless devices, **you must select skip**.

**Comment by C0D3K1LL3R** [comment]
I mean when I'm performing the captive portal,The client ob target not connect.
Why I know?I perform the attacks in my own wifi

**Comment by C0D3K1LL3R** [comment]
This is in my Laptop
![issue](https://user-images.githubusercontent.com/37650125/40705755-5621d3e8-641e-11e8-8aec-bcf9a976088c.png)

This is in my phone

![issue1](https://user-images.githubusercontent.com/37650125/40705782-6c21fda8-641e-11e8-9bd0-8c648b4737f1.jpg)

As you can See, It's only on Connecting and can't connecg=t anymore

**Comment by C0D3K1LL3R** [comment]
This is in my Laptop
![issue](https://user-images.githubusercontent.com/37650125/40705755-5621d3e8-641e-11e8-8aec-bcf9a976088c.png)

This is in my phone

![issue1](https://user-images.githubusercontent.com/37650125/40705782-6c21fda8-641e-11e8-9bd0-8c648b4737f1.jpg)

As you can See, It's only on Connecting and can't connect anymore

**Comment by MPX4132** [comment]
@C0D3K1LL3R What happened to the top left xterm window? Did you close it? That should be the DHCP server, and it should be running.

**Comment by C0D3K1LL3R** [comment]
This is in my Laptop
![issue](https://user-images.githubusercontent.com/37650125/40705935-d5b7fc54-641e-11e8-8d22-e95b8ef40505.png)


And this on my phone
![issue1](https://user-images.githubusercontent.com/37650125/40705982-fab593ae-641e-11e8-9865-bd73eb94f53c.jpg)

As you can see, It's only connecting and its not bein connected

**Comment by C0D3K1LL3R** [comment]
Nope....
theres no xterm on that position

**Comment by C0D3K1LL3R** [comment]
By the Way I'm in Ubuntu OS

**Comment by strasharo** [comment]
While fluxion is running do a:
`netstat -npl | egrep '67|68'`

**Comment by MPX4132** [comment]
You’re missing the DHCP window.

**Comment by MPX4132** [comment]
@C0D3K1LL3R Run fluxion in debug mode:
```
./fluxion.sh -d
```
I think the DHCP server is crashing and the xterm window is closing before you get a chance to read it.

**Comment by C0D3K1LL3R** [comment]
How can I fix it?

**Comment by MPX4132** [comment]
@C0D3K1LL3R Did the DHCP server crash? If it did, what did it crash with? What does it say when it crashes.

**Comment by C0D3K1LL3R** [comment]
Look at this 

![kazam_screenshot_00008](https://user-images.githubusercontent.com/37650125/40707179-7fb3629a-6422-11e8-92c8-8966932bc2e7.png)

**Comment by MPX4132** [comment]
@C0D3K1LL3R If you haven't already, restart your computer and run fluxion regularly (no debug flag):
```
./fluxion.sh
```
Once it's running and the DHCP service window is missing, run the following and paste the output in a reply:
```
more /tmp/fluxspace/dhcpd.conf
```

**Comment by C0D3K1LL3R** [comment]
I type it in?

**Comment by C0D3K1LL3R** [comment]
This is it Still The DHCP Service is missing...

![shot-2018-06-23_01-40-29](https://user-images.githubusercontent.com/37650125/41791035-129ea2a6-7687-11e8-9b60-d1043be0c2ba.jpg)
