### ISSUE TITLE
Select an interface for the captive portal Issue.

### ISSUE THREAD

**Issue by kumyoung** [FluxionNetwork/fluxion#522]
I am running the latest version of Kali Linux and have used Fluxion 3.11
On the Select an interface for the captive portal.
I use the option [1] eth0 [+] Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/G 
I use external access point to imitating the original access point.
and Run like a charm...there is no issue... 

On Fluxion version 4 
the option [1] eth0 is not running..

**Comment by MPX4132** [comment]
@kumyoung What happens if it fails? You left out a bunch of details.
