### ISSUE TITLE
Initial setup looping (cant install 'cowpatty')

### ISSUE THREAD

**Issue by RKouchoo** [FluxionNetwork/fluxion#523]
#### Summary
Fluxion fails to install a dependency and loops.

##### What is the current behaviour?
Endless dependency installation looping; can be seen in this video:
https://drive.google.com/open?id=17zypmKYz_q8reBptjsrzOpU2iAJmgkwU

#### How to reproduce
run fluxion.sh

##### If the current behaviour is a bug, please provide the steps to reproduce it.
run fluxion.sh without the dependencies installed. particularly "cowpatty"

##### What do you think the expected behaviour should be?
It should install the dependency, or give up and throw an error.

### PLEASE VIEW 
https://drive.google.com/open?id=17zypmKYz_q8reBptjsrzOpU2iAJmgkwU

👍

**Comment by RKouchoo** [comment]
You can manually install it by doing this:

```
sudo apt-get install libpcap-dev libssl-dev
cd ~
wget http://pkgs.fedoraproject.org/repo/pkgs/cowpatty/cowpatty-4.6.tgz/b90fd36ad987c99e7cc1d2a05a565cbd/cowpatty-4.6.tgz
tar zxfv cowpatty-4.6.tgz
cd cowpatty-4.6/
make
sudo cp cowpatty /usr/bin
cd ~
```

**Comment by deltaxflux** [comment]
Yeah definitely

**Comment by MPX4132** [comment]
Yeah, it had more bugs than what was being shown here. Some were being hidden by a bug with bash itself.
