### ISSUE TITLE
captive portal

### ISSUE THREAD

**Issue by celik869013** [FluxionNetwork/fluxion#525]
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### Expected behavior

[image hidden, edit to view]

![screenshot_2018-05-31-01-28-39](https://user-images.githubusercontent.com/35223115/40751266-1f602f62-6473-11e8-8ca4-e38035f690c6.png)

the connection does not work please help

**Comment by MPX4132** [comment]
@celik869013 What options did you launch the attack with? Can you show me screenshots of that? Specifically, I want to know what you selected for target tracking.

**Comment by celik869013** [comment]
![ekran alintisi](https://user-images.githubusercontent.com/35223115/40751769-4eec912e-6475-11e8-8a2c-4bf96cb278b3.PNG)

**Comment by MPX4132** [comment]
@celik869013 You showed me the image you had already posted. I said:
> **I want to know what you selected for target tracking.**

So please tell me what you selected there.

**Comment by celik869013** [comment]
çok özür dilerim tam anlayamadım. hedef android - pc ?

**Comment by MPX4132** [comment]
@celik869013 I'm sorry, I didn't realize you were having trouble with the language. Please tell me what network interface you're selecting when the script asks you to select a network interface for "target tracking." If you don't have two wireless devices, you have to select "skip" when prompted for it.

Translated by Google:
Üzgünüm, dil konusunda sorun yaşadığının farkında değildim. Lütfen komut dosyası "hedef izleme" için bir ağ arayüzü seçmenizi istediğinde bana hangi ağ arayüzünü seçtiğini söyle. İki kablosuz aygıtınız yoksa, istendiğinde "atla" seçeneğini seçmeniz gerekir.

**Comment by celik869013** [comment]
![1](https://user-images.githubusercontent.com/35223115/40802010-18d64672-651d-11e8-9833-83fe32d39781.PNG)
![2](https://user-images.githubusercontent.com/35223115/40802019-1f1f913c-651d-11e8-9554-9ac5dd4161fb.PNG)
![3](https://user-images.githubusercontent.com/35223115/40802023-21dbcd82-651d-11e8-838b-d96e80b8c210.PNG)
![4](https://user-images.githubusercontent.com/35223115/40802031-254fba14-651d-11e8-9f31-25521b399732.PNG)
![5](https://user-images.githubusercontent.com/35223115/40802035-27d61e36-651d-11e8-971a-cdc3b9ad4ad5.PNG)
![6](https://user-images.githubusercontent.com/35223115/40802036-29f14fe2-651d-11e8-8f5c-7e191e6cfbf8.PNG)
![7](https://user-images.githubusercontent.com/35223115/40802037-2bed7f8c-651d-11e8-9a87-d8a3cba524b3.PNG)
![8](https://user-images.githubusercontent.com/35223115/40802039-2df26ed2-651d-11e8-85c9-2647c5df4a34.PNG)
![9](https://user-images.githubusercontent.com/35223115/40802042-3064b4d6-651d-11e8-8e08-1cc1697124ec.PNG)
![10](https://user-images.githubusercontent.com/35223115/40802044-329b6ed4-651d-11e8-9e0a-382b5a8e4d93.PNG)
![11](https://user-images.githubusercontent.com/35223115/40802051-3535b6ea-651d-11e8-90d6-87deaa3a244b.PNG)
![12](https://user-images.githubusercontent.com/35223115/40802060-384ae1b6-651d-11e8-8abe-f1919762d3e7.PNG)
![13](https://user-images.githubusercontent.com/35223115/40802069-3e634020-651d-11e8-8dce-ed181db83502.PNG)
![14](https://user-images.githubusercontent.com/35223115/40802074-43671b32-651d-11e8-8a8b-4fa0675d76d6.PNG)
![screenshot_2018-05-31-01-28-39](https://user-images.githubusercontent.com/35223115/40802078-4760dc82-651d-11e8-8231-e67f313db56c.png)

**Comment by celik869013** [comment]
These are the actions I have done.

**Comment by MPX4132** [comment]
@celik869013 Sorry for the delay, I’ve been extremely busy.

Your problem is that you are using the same interface for the rogue AP and for target tracking. That’s impossible, and will fail.

When you get to this step, select “Skip”:

https://user-images.githubusercontent.com/35223115/40802035-27d61e36-651d-11e8-971a-cdc3b9ad4ad5.PNG
