### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by toxxn** [FluxionNetwork/fluxion#526]
Attempted ./install.sh, it seems it's not installing the packages I am missing.

First time I ran install I received error about revolver already existing.

rm -rf revolver

./install.sh

Dhcpd...........Installing ...
Hostapd.........Installing ...
Lighttpd........Installing ...
Php-cgi.........Installing ...

Cloning into 'revolver'...
remote: Counting objects: 99, done.
remote: Total 99 (delta 0), reused 0 (delta 0), pack-reused 99
Unpacking objects: 100% (99/99), done.

./fluxion.sh

dhcpd...........Not installed (isc-dhcp-server)
hostapd.........Not installed
lighttpd........Not installed
php-cgi.........Not installed

I am using Kali 2018.2. Any help would be appreciated! 
Thanks! 

**## ::EDIT::**

I may have been trying to install a different version than whats listed here. So I removed fluxion completely, and followed the directions here. I was met with this error:

           
            [*] dhcpd....................................... Missing!                
            [*] hostapd..................................... Missing!           
            [*] lighttpd.................................... Missing!              
            [*] php-cgi..................................... Missing!           
     
Nothing to check.
Adding missing sources to package manager, please wait.
Adding keys.gnupg.net key, please wait.
Adding pgp.mit.edu key, please wait.
ERROR: Failed to fetch or add the source key!

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bc

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

**Comment by deltaxflux** [comment]
Please use the latest version of fluxion.

**Comment by MPX4132** [comment]
@toxxn Do you not have an internet connection? Seems like the installer failed to fetch the packages.

**Comment by deltaxflux** [comment]
@MPX4132 it is the installer for fluxion 3 so outdated.

**Comment by MPX4132** [comment]
@deltaxflux Ohhh! I didn’t notice, good catch.

**Comment by abd1997-sudo** [comment]
fuck this fuckong fluxion

**Comment by abd1997-sudo** [comment]
won't install

**Comment by ekovegeance** [comment]
phg-cgi not installed
