### ISSUE TITLE
Fluxion freeze when trying to create rougue ap since update

### ISSUE THREAD

**Issue by BRRY876** [FluxionNetwork/fluxion#527]
After the Handshake Snooper I then moved on to creating the captive portal, I created a ssl certifictate and selected the appropriate vendor and language after that froze the entire termianal and this sign kept blinking " _ ". I closed the terminal and type a random command like apt-get update, apt-get upgrade, apt-get install tor and i got this blinking sign "_" . I have tried on different distros and same problem. all of this happen is update of the fluxion tool.

**Comment by deltaxflux** [comment]
Well, please fill the issue template. It is very hard to tell what the exact problem is without knowing which specs you have.  I closing now please open a new issue.

**Comment by MPX4132** [comment]
Yeah, I don’t think this is a problem with fluxion. Sounds like a network issue.
