### ISSUE TITLE
airbase-ng error setting mtu on fluxw10v

### ISSUE THREAD

**Issue by eitanhindi** [FluxionNetwork/fluxion#528]
based on my adapter i can not using hostapd so im using airbase-ng for fake AP.
everything is working fine. but no fake AP is created.
i get this error in fake AP window:
"error setting mtu on fluxw10v"

![1](https://user-images.githubusercontent.com/30051406/40885112-b79c52a8-6728-11e8-8dd1-db4e1f7f39a7.png)

##### What is the current behaviour?
hanging...

##### Specs
this is the diagnostics report of my adapter by fluxion:

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** 8812au
**Chipset:** Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
**Master Modes** Yes
**Injection Test:** Injection is working!

**Comment by deltaxflux** [comment]
which version of fluxion are you using ?

**Comment by eitanhindi** [comment]
the latest

**Comment by eitanhindi** [comment]
i had the same problem at pervious versions

**Comment by MPX4132** [comment]
He’s using airbase-ng, so he’s going to have problems. It’s hit or miss with it.

**Comment by Gh0stInTh3M4ch1n3** [comment]
No, I didn't use airbase-ng, I used cowpatty since it's was the most recommended
