### ISSUE TITLE
Using kali subsystem in windows 1803

### ISSUE THREAD

**Issue by nesperida911** [FluxionNetwork/fluxion#531]
#### Summary

When i try to run fluxion in kali subsystem in windows it always shows "Aborted, X (graphical) session unavailable."

![image](https://user-images.githubusercontent.com/6942408/40973265-32d328ba-68f6-11e8-88c3-75e991293c3a.png)

**Comment by deltaxflux** [comment]
read carefully the readme

**Comment by Gh0stInTh3M4ch1n3** [comment]
Deltaflux, since you're on, could you help with issue #530. It was closed without being solved..
