### ISSUE TITLE
Is fluxion compatible with macOS?

### ISSUE THREAD

**Issue by kavience** [FluxionNetwork/fluxion#532]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

Can I use fluxion on my mac os?

**Comment by p9pine** [comment]
thats why macOS is far behind Windows which supports linux subsystem and hardware managed for linux softwares..thats why people like PCs and Windows instead of macOS

**Comment by p9pine** [comment]
i want updated in kernel linux Drivers for Alfa AWUS1900 realtek RTL8814AU

**Comment by cjb900** [comment]
> i want updated in kernel linux Drivers for Alfa AWUS1900 realtek RTL8814AU

the likely hood of this happening is very low. RTL chipsets have been notoriously problematic for wifi hacking for the last several years.
