### ISSUE TITLE
FluxionNetwork/fluxion

### ISSUE THREAD

**Issue by pitoballz** [FluxionNetwork/fluxion#534]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by pitoballz** [comment]
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

thats after i try to install fluxion

**Comment by deltaxflux** [comment]
Try manually to install dependencies and share results.
