### ISSUE TITLE
Target tracker failed to unprep attack

### ISSUE THREAD

**Issue by wasp478** [FluxionNetwork/fluxion#535]
Hello there.
I think script need to update for real.
When I try with airgeddon, it is working cool.
But with fluxion... Handshake never succesfull. Even I put handshake capture file for evil portal I got this issue everytime : Target tracker failed to unprep attack.

I am on Kali Linux 2018

**Comment by MPX4132** [comment]
Don’t use target tracking if you don’t have two individual devices.
