### ISSUE TITLE
sslstrip2

### ISSUE THREAD

**Issue by liklev** [FluxionNetwork/fluxion#536]
#### Summary

captive portal present ssl/dns brings up warning in target's browser (chrome) that the page i'm visiting is not safe/secure. (caption when redirected from https sites)
LeonardoNve made up some sslstrip+ (or v.2) together with dns2server to force some downgrade which bypassing somehow browser warning. 
i know it may not consider as bug rather new feature. it somewhere in grey zone.
please consider replacing these components.
LeonardoNve is not keeping anymore the git, but some people succeeded to mirror his makes.

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by deltaxflux** [comment]
Would be great.

**Comment by Genetick** [comment]
https://github.com/droe/sslsplit
