### ISSUE TITLE
Fluxion 4 rev.12- doesn't run

### ISSUE THREAD

**Issue by kaliramta** [FluxionNetwork/fluxion#538]
I am try to run latest fluxion 4 rev.12 and it seems unable to load. While all the dependencies displayed OK status.
![fluxion4 12-error](https://user-images.githubusercontent.com/40236471/41351845-278b829c-6f07-11e8-8615-28bef877ca2e.png)

Errors are below:
(1).
./fluxion.sh: line 533: declare: -A: invalid option                            
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./fluxion.sh: line 741: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

(2).
Online Version/root/Documents/fluxion/lib/installer/InstallerUtils.sh: line 79: mapfile: command not found
 [.]
/root/Documents/fluxion/lib/installer/InstallerUtils.sh: line 94: [: : integer expression expected

(3).
./fluxion.sh: line 624: local: -A: invalid option
local: usage: local name[=value] ...
./fluxion.sh: line 628: "set_language": syntax error: operand expected (error token is ""set_language"")

Thanks for your good work and God bless you.

**Comment by MPX4132** [comment]
Run the diagnostics script.

**Comment by MPX4132** [comment]
Closed due to lack of response. We may reopen the issue once we've got more information.
