### ISSUE TITLE
AP crash when client connect

### ISSUE THREAD

**Issue by he2lec** [FluxionNetwork/fluxion#539]
Hi,

I tried to setup a simple AP with fluxion 4. Aside the fact that 90% of the connections failed, when one happened, fluxion stopped the AP, and exit. The only error that i could noticed was in the information terminal:

 `cat: /tmp/fluxspace/clients.txt: No such file or directory`

Since fluxion 4, i didn't succeed to connect any client to my ap.

Sincerely.

**Comment by voltaire1694** [comment]
I am having the same issue.  At random intervals the Captive Portal attack will cease unexpectedly. All xterm windows will close, except for the FLUXION AP Autheticator window. The twin AP will cease broadcasting. In the FLUXION AP window there will appear the line "cat:/tmp/fluxspace/clients.txt: No such file or directory". As I said this is appears to be a bit random, but occurs on about 50% of the tests I've run so far. I should also say that I am typically working with 2.4GHz networks which regularly hop channels.

**Comment by deltaxflux** [comment]
@voltaire1694 @he2lec 
Hey,
Thank you for creating this issue(s). I need some more information to look in detail. 

@he2lec 
Can you ekaborate that it was working in other fluxion versions? Can you please submit the output of the diagnostic script? Do you update your drivers?

@voltaire1694 
Looks like it is the same issue. Please post the output of diagnostic script. I will look in detail.

Regards,

deltax

**Comment by he2lec** [comment]
In other fluxion versions, the clients could connect to the AP without troubles.
Here is the output of the diagnostic script:

```
#### FLUXION Info
FLUXION V4.12


#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.15.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-11)) #1 SMP Debian 4.15.11-1kali1 (2018-03-21)
```

**Comment by he2lec** [comment]
I went back to v4.10 and it doesn't seems to crash.

However i couldn't get a fake page to show, and 90% of the time the client cannot connect ("Unable to join", mac and iphone tested), the hostapd service telling:

`IEEE 801.11: did not acknowledge authentication response`

**Comment by voltaire1694** [comment]
Man, I hate to be such a noob: It's clear that I move to the scripts folder and run ./diagnostics.sh [wlan interface]. I'm using _two_ radios for the attack, both Ralink 2870/3070.  _When_ do I run the diagnostic script?  During the attack? After the attack? Before the attack?  Sorry for the dumb questions.

**Comment by MPX4132** [comment]
@voltaire1694 Run it independently, don’t run the attack while running diagnostics.
Run it once for each device.

**Comment by MPX4132** [comment]
@he2lec when running fluxion 4, are you selecting a target tracking interface? If you are, you better not be selecting the same interface as the one for the `Captive Portal` attack. It’s getting real irritating people don’t read or neglect the fact they don’t understand. I’m not saying that’s the case with you, I’m saying there’s a possibility.

**Comment by deltaxflux** [comment]
Closing lack of response. Opening if required.

**Comment by voltaire1694** [comment]
Very sorry folks -- had out of town guests, mother-in-law, etc.  No time.  
I've run the diagnostic on all three wlan interfaces attached to my machine. See below.

`===============Run on wlan0 interface:

root@DESKTOP-N3NT70Q:~/Desktop/fluxion/scripts# ./diagnostics.sh wlan0 
#### FLUXION Info
FLUXION V4.10


#### BASH Info 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** iwlwifi
**Chipset:** Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-18)) #1 SMP Debian 4.14.12-2kali1 (2018-01-08)


===============re-run on wlan1 interface:

root@DESKTOP-N3NT70Q:~/Desktop/fluxion/scripts# ./diagnostics.sh wlan1

#### FLUXION Info
FLUXION V4.10


#### BASH Info 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan1) Info 
**Device**: phy1
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!
read failed: Network is down
wi_read(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-18)) #1 SMP Debian 4.14.12-2kali1 (2018-01-08)

===============re-run on wlan2 interface:

ot@DESKTOP-N3NT70Q:~/Desktop/fluxion/scripts# ./diagnostics.sh wlan2

#### FLUXION Info
FLUXION V4.10


#### BASH Info 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan2) Info 
**Device**: phy2
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-18)) #1 SMP Debian 4.14.12-2kali1 (2018-01-08)`
******************************

I shut down the unit, and switched USB sockets for the two external radios.  When I ran it again I didn't get the error "write failed: Network is down".  Not sure if this is relevant.

Also here is the AP attack running; everything seems in order
![screenshot from 2018-06-12 22-22-23](https://user-images.githubusercontent.com/39715843/41576217-f35543ae-733a-11e8-9141-eb202c6b0860.png)

Then something goes south on it after a few minutes and all the xterm windows shut down, save one:
![screenshot from 2018-06-13 00-48-17](https://user-images.githubusercontent.com/39715843/41576232-008eb762-733b-11e8-9be3-9bf265e0d22e.png)

_Sometimes_ when the AP attach fails there is the error message in the AP Autheticator xterm window "/tmp/fluxspace/clients.txt: No such file or directory".  Not sure if this is relevant.

![screenshot from 2018-06-13 07-30-37](https://user-images.githubusercontent.com/39715843/41576415-23aa75a0-733c-11e8-9143-6aecd806c7fe.png)

Any insights gratefully received!

**Comment by rattzy** [comment]
@deltaxflux , I know its been a long time since this thread, I`ve encountered the same problem when using Fluxion. 
Sometimes after 2 mins of running I come across the error, that clients.txt - no such file or directory. Ran a diagnostics on both interfaces I`m using with fluxion and I got an error that the Scapy version is 2.4 and pyrit might not work, but I`m not selecting pyrit when configuring Fluxion.
Can you please advise.

Thanks

**Comment by AlexPalencia** [comment]
@rattzy @voltaire1694 Hola, sé que ha pasado mucho desde la apertura del hilo; tuve el mismo error usando la última versión de Fluxion y en mi caso la solución fue elegir 'skip' cuando se debe seleccionar la interfaz.
