### ISSUE TITLE
Cant see any wlan... (bug?)

### ISSUE THREAD

**Issue by 9acca9** [FluxionNetwork/fluxion#540]
Hi to all.
Can somebody give me a hand whit this? i can see any wireless network.
Fluxion start and put the wifi in monitor mode (supposedly).

02:00.0 Network controller: Intel Corporation Wireless 7265 (rev 59)
	Subsystem: Intel Corporation Dual Band Wireless-AC 7265
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi

Thanks to all.

And, by the way, the monitor modo it's ok with other version. I mean, in other version of fluxion i can see the wifi networks. so............

**Comment by deltaxflux** [comment]
Hey,
Thank you for creating this issue but first I need some information. Can you elaborate that the old version is working **now**? Please post the output of the diagnostic script.

**Comment by MPX4132** [comment]
@9acca9 restart your computer, the driver crashed. Happens to me all the time.
