### ISSUE TITLE
AP changes channel

### ISSUE THREAD

**Issue by tdw546** [FluxionNetwork/fluxion#542]
|    Q        |   A
|------------ | -----
| Version     | 4.12 (most recent version pulled from github)

#### Support Question
When using captive portal on a specific network, the evil twin AP set up by fluxion changes the channel repeatedly. If I understand the process correctly, this does not make sense. Is there a misunderstanding on my part or is this a bug?

**Comment by deltaxflux** [comment]
> When using captive portal on a specific network, the evil twin AP set up by fluxion changes the channel repeatedly [...] this does not make sense

Well, fluxion follow the channel to make sure that deauth work. This is not a bug or something else this is the intended to do that,

**Comment by tdw546** [comment]
It seems to me that this is also the case when the target does not change the channel.

I have repeatetly seen the warning that channel A is being deauthed but the target is on channel B

Just letting you know

**Comment by deltaxflux** [comment]
Do you use two wireless cards?

**Comment by tdw546** [comment]
Not always. Is there a connection?

**Comment by MPX4132** [comment]
@tdw546 Did you select an interface for target tracking, and did you select that same interface for AP creation? If you did, that’s a problem since it’s not supported.

You need to select `skip` on target tracking interface selection, otherwise the scanner will keep switching the channels on the rogue AP.

**Comment by tdw546** [comment]
@MPX4132 Thanks for the hint.

That might be it.

However I consider this behavios and the fact that using the same interface is not intendet as a (usability) bug itself. Please consider changing this, e.g. by using a warning message if the same interface is used.

**Comment by MPX4132** [comment]
@tdw546 Nope, can't do that. The fact it doesn't work for us doesn't mean there's no driver that might support multiple channels from virtual interfaces.
