### ISSUE TITLE
apt-get install libasound2 

### ISSUE THREAD

**Issue by pitoballz** [FluxionNetwork/fluxion#543]
![screenshot from 2018-06-16 03-42-48](https://user-images.githubusercontent.com/35594987/41498075-aaf212b0-7153-11e8-8af5-07afc5adb5dc.png)    i have no sound trying to get sound please help new to this

**Comment by deltaxflux** [comment]
This is not a support forum for random things. Ask somewhere else sry.

**Comment by pitoballz** [comment]
spensas buey

**Comment by pitoballz** [comment]
[REDACTED]

**Comment by pitoballz** [comment]
spensas buey
