### ISSUE TITLE
at0 ERROR while getting interface flags: No such device 

### ISSUE THREAD

**Issue by pankaj97k** [FluxionNetwork/fluxion#544]
**fluxion version: FLUX 0.23 (rev.  44) by  deltax**

wireless card: **alfa AWUS036H**

ISSUE:
fluxion is not creating fake ap 
after selecting web interface this error shows up

**at0: unknown interface: No such device
SIOCSIFADDR: No such device
at0: unknown interface: No such **device**
SIOCSIFNETMASK: No such device
SIOCADDRT: Network is unreachable**

![1](https://user-images.githubusercontent.com/40317707/41498592-1d5680cc-7161-11e8-8021-1e3c895e3785.jpg)
![2](https://user-images.githubusercontent.com/40317707/41498593-1da8eb8c-7161-11e8-9848-902be02b6a0e.jpg)
![3](https://user-images.githubusercontent.com/40317707/41498594-1dfa1840-7161-11e8-85ac-2648df785442.jpg)
![4](https://user-images.githubusercontent.com/40317707/41498595-1e4e6eae-7161-11e8-86b3-7ed89bccb920.jpg)
![5](https://user-images.githubusercontent.com/40317707/41498596-1ea3f252-7161-11e8-8d1a-7b7377d36c94.jpg)
![20180616_173747](https://user-images.githubusercontent.com/40317707/41498597-1f0221b0-7161-11e8-9cf3-50e002829de6.jpg)
![20180616_173757](https://user-images.githubusercontent.com/40317707/41498598-1f7380ee-7161-11e8-9611-aed8cf924965.jpg)
![20180616_173804](https://user-images.githubusercontent.com/40317707/41498599-200f2170-7161-11e8-8c77-dcb922c77ae0.jpg)
![20180616_173814](https://user-images.githubusercontent.com/40317707/41498600-2063fe5c-7161-11e8-830b-ec163c4f3cb3.jpg)

**Comment by deltaxflux** [comment]
We have fluxion 4 try to test the latest release.

**Comment by pankaj97k** [comment]
mdk3|mdk4................................... Missing!
please tell me how can i install this, i am using wifislax

**Comment by deltaxflux** [comment]
Well, fixed this bug. Do `git pull` and try again.

**Comment by deltaxflux** [comment]
And I noticed that you use the alfa AWUS036H. I think the wireless card is not compatible with hostapd but not I'm not sure.

**Comment by pankaj97k** [comment]
@usama7628674 is there any way to use fluxion ? or any other method ?

**Comment by pankaj97k** [comment]
can i use airbase??

**Comment by usama7628674** [comment]
Yes you can but I don't recommend it.It's too slow and sometimes takes ages to connect.

**Comment by pankaj97k** [comment]
@usama7628674  will intel dual band wireless-AC 3160 work with hostapd ???

**Comment by usama7628674** [comment]
@pankaj97k I don't know

**Comment by usama7628674** [comment]
@pankaj97k I use `alfa awus036nha`

**Comment by pankaj97k** [comment]
Pls suggest some cheap one

**Comment by pankaj97k** [comment]
Thank you

**Comment by rad4day** [comment]
Make sure to actually get the V1. The newer hardware revisions **DO NOT WORK**

Also I think this issue is resolved. If not please re-open it.

**Comment by pankaj97k** [comment]
Ok thank you
