### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Proxyl3ss** [FluxionNetwork/fluxion#545]
The first step with git clone didn't work for me.. I fixed it by typing git clone (link) and it worked fine.

**Comment by usama7628674** [comment]
@Proxyl3ss Did you follow the additional steps before cloning it?

**Comment by Proxyl3ss** [comment]
@usama7628674 I did bur it didn't work. Anyways I only wanted to say it. It works like a charm.

**Comment by Pride100** [comment]
my issue https://www.youtube.com/watch?v=1u3zBZQs_04

**Comment by usama7628674** [comment]
@Pride100 This tool is outdated use [airgeddon](https://github.com/v1s1t0r1sh3r3/airgeddon)

**Comment by Pride100** [comment]
Why? Is fluxion not usable anymore? Is there any update coming up? And when? 
Can i get the downgraded fluxion v.4.15 i think its more compatible than the latest. I have used fluxion v4 before and i experienced no problem. P.s I need Fluxion v4 not fluxion v2. Thanks!
