### ISSUE TITLE
clone error not complete

### ISSUE THREAD

**Issue by Denzel-Washington** [FluxionNetwork/fluxion#549]
#### Summary
Cloning into 'fluxion'...
Enter passphrase for key '/root/.ssh/id_rsa': 
remote: Counting objects: 6256, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 6256 (delta 59), reused 76 (delta 32), pack-reused 6144
Receiving objects: 100% (6256/6256), 30.02 MiB | 515.00 KiB/s, done.
Resolving deltas: 100% (3272/3272), done.
Submodule 'attacks/Captive Portal/sites' (https://github.com/FluxionNetwork/sites) registered for path 'attacks/Captive Portal/sites'
Cloning into '/root/fluxion/attacks/Captive Portal/sites'...
fatal: clone of 'https://github.com/FluxionNetwork/sites' into submodule path '/root/fluxion/attacks/Captive Portal/sites' failed
Failed to clone 'attacks/Captive Portal/sites'. Retry scheduled
Cloning into '/root/fluxion/attacks/Captive Portal/sites'...
fatal: clone of 'https://github.com/FluxionNetwork/sites' into submodule path '/root/fluxion/attacks/Captive Portal/sites' failed
Failed to clone 'attacks/Captive Portal/sites' a second time, aborting

##### What is the current behaviour?
fluxion clone error

##### If the current behaviour is a bug, please provide the steps to reproduce it.
git clone --recursive git@github.com:FluxionNetwork/fluxion.git

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by MPX4132** [comment]
You can try checking it out over SSL/TLS, just replace the git@github.com:FluxionNetwork/fluxion.git with https://github.com/FluxionNetwork/fluxion.git
