### ISSUE TITLE
Infinte Loop in "Path to capture file"

### ISSUE THREAD

**Issue by bopnrgi** [FluxionNetwork/fluxion#55]
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

----

### What is the current behavior?
-> Prompt ask for path for handshake file (or directory) and loop 2 step backward

---

#### If the current behavior is a bug, please provide the steps to reproduce.
->

 This is  selected options

[1] Captive Portal > [1] Rogue AP - hostapd (recommended) > [1] Path to capture file
At this step, i entered any path (i'm on kali linux) and press "enter" 
Script return to "Select an access point service" and this is an infinite loop

Same for this options
[1] Captive Portal > [1] Rogue AP - hostapd (recommended) > [1] Path to capture file

Note that [1] Path to capture / [2] Handshake directory (rescan) produce same result

--- 

#### What is the expected behavior?
-> *Be creative*

It could be launch the captive portal next or prompt for SSL certificate (i suppose)
---

### If this is a feature request, what is motivation or use case for changing the behavior?

---

#### Wireless adapter:
*Exact model, chipset, and driver versions.*

#### Does it support injection?
Yes, i'm on another computer but it prompt this
aireplay-ng wlan0mon -9
Trying broadcast probe requests...
Injection is working
Found 9 APs

and then injecting...

#### Fluxion version:
*Paste the output of* `cat fluxion.sh | grep revision`
Latest (git clone 2 hours ago)

#### Linux version:
*Paste the output of* `cat /proc/version` or `uname -r` 
4.6.0-kalil-686-pae

**Comment by strasharo** [comment]
Pull again and confirm.

**Comment by bopnrgi** [comment]
After pull, exactly the same infinte loop.
Then, also (even not necessary) rm -rf on fluxion folder, and git clone again... The same infinte loop.

I can see your commit in the log
Maybe a "default folder" could be implemented ?! (like version2)

IS a problem with parsing path ?

**Comment by MPX4132** [comment]
I was wondering if you're getting to the screen with this: "Select a method of verification for the hash"
It occurs right after entering the [absolute] path to the capture file. From what you stated earlier, you're not making it that far, correct?

**Comment by bopnrgi** [comment]
In fact, there are two problems.

At first, by searching the Fluxion code, I saw that a temporary directory /tmp/ fluxspace is created. Inside this directory there is a capture directory that contains the dump-01.cap file. If I copy this file to the desktop and I enter that absolute path then I can have the check verified.

2 - It is impossible for me to launch hostapd, only the aircrack version works for the access point. The new network is created without security (which is normal) but it is broadcast with the same MAC address. How can we deauthenticate the original access point in this case? Changing the mac address would be more useful?

When I succeed, in very rare cases, to have the fake screen for login, fluxion looks in a directory that does not exist and the program fails.

Ideas ?

**Comment by MPX4132** [comment]
I forgot to mention, the default folder location has been changed to: attacks/Captive Portal/handshakes

**Comment by MPX4132** [comment]
Please try the bug fixes I wrote. They haven't been accepted, but you can try them if you'd like.

**Comment by bopnrgi** [comment]
@MPX4132 Your commit fix the bug of capture file path ! Thanks :)
I always have a problem with hotspot which works randomly... Maybe a new ticket for this problem ?

**Comment by deltaxflux** [comment]
Create a new issue for this but before please check out the other pull request.
