### ISSUE TITLE
error: /dev/fd/

### ISSUE THREAD

**Issue by Denzel-Washington** [FluxionNetwork/fluxion#554]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question
hi, when i run fluxion.sh  i get this error:
./fluxion.sh: line 1695: /dev/fd/62: no such file or directory
./fluxion.sh: line 1698: /dev/fd/62: no such file or directory

**Comment by deltaxflux** [comment]
Looks like that the udev package is missing try to install it:
```
aptitude install udev




```

**Comment by strasharo** [comment]
What OS are you trying to run it on?

**Comment by MPX4132** [comment]
No response in two weeks, abandoned.

**Comment by Denzel-Washington** [comment]
hi @MPX4132

sorry for the super late reply ... yeah this "ln -s /proc/self/fd /dev/fd" worked!! .thanks.
