### ISSUE TITLE
Handshake Corrupted!

### ISSUE THREAD

**Issue by cembey068** [FluxionNetwork/fluxion#556]
How can i solve this problem? I'm using Kali Linux 2018.2

**Comment by strasharo** [comment]
What type of verification for the handshake did you choose?

**Comment by MPX4132** [comment]
@cembey068 How do you know it's corrupted?

**Comment by MPX4132** [comment]
@cembey068 If you are in fact getting a corrupted handshake, make sure to capture the handshake with synchronicity of "Synchronous", don't use "Asynchronous".
