### ISSUE TITLE
Unknown mac address appearing in Handshake Captor

### ISSUE THREAD

**Issue by keethesh** [FluxionNetwork/fluxion#559]
There is a Mac address in the handshake captor. It looks awkward as it is composed only of F's.
I'm using a wifi dongle for target tracking, and another one for jamming. I selected mdk3 deauthentication and asynchronous. Is there anything I'm doing wrong? I'm now using version 4.13, but in version 4.12 it was working.

**Comment by MPX4132** [comment]
@keethesh Just pushed version 4.14, fixing lots of bugs introduced on version 4.13, please upgrade.

**Comment by keethesh** [comment]
Thanks, it's now working!
