### ISSUE TITLE
Unable to parse airodump csv output

### ISSUE THREAD

**Issue by strasharo** [FluxionNetwork/fluxion#56]
Is it just me or currently the script is unable to parse the csv output from airodump on the network selection dialog using the stock airodump shipped with Kali?
https://github.com/FluxionNetwork/fluxion/blob/master/fluxion.sh#L675

**Comment by MPX4132** [comment]
I found a bug last night related to different versions of awk, (mawk vs gawk). I used them in the script to parse the output from airodump-ng, which is why it might be relevant. If your system has a link from awk to mawk, you're affected. If that's the issue, it's just been fixed in the latest commit I made.

**Comment by strasharo** [comment]
Yup, I'm on kally and it's linked to mawk:

`root@ktest:~# ls -l `which awk`
lrwxrwxrwx 1 root root 21 Dec 10  2016 /usr/bin/awk -> /etc/alternatives/awk
root@ktest:~# ls -l /etc/alternatives/awk
lrwxrwxrwx 1 root root 13 Dec 10  2016 /etc/alternatives/awk -> /usr/bin/mawk
root@ktest:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
root@ktest:~# 
`

**Comment by strasharo** [comment]
Yup, I'm on Kali and it's linked to mawk:

```
root@ktest:~# ls -l `which awk`
lrwxrwxrwx 1 root root 21 Dec 10  2016 /usr/bin/awk -> /etc/alternatives/awk
root@ktest:~# ls -l /etc/alternatives/awk
lrwxrwxrwx 1 root root 13 Dec 10  2016 /etc/alternatives/awk -> /usr/bin/mawk
root@ktest:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
root@ktest:~# 

```

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/pull/57 fixed it
