### ISSUE TITLE
Can't launch Fluxion

### ISSUE THREAD

**Issue by Mant00** [FluxionNetwork/fluxion#560]
A few days ago I was able to run Fluxion and everything worked perfect, but today I had got a problem. I installed Fluxion on Kali and when I launched it, the problem started. 
Link for video:
https://nofile.io/f/fvE2thNHr5X/problem.webm

Thank you in advance for your reply!

**Comment by MPX4132** [comment]
@Mant00 I already fixed that issue, I'm not sure why it's breaking. Reboot yous system and check if it keeps doing that.

**Comment by Mant00** [comment]
Ok, Thanks a lot!

**Comment by Mant00** [comment]
Now everything works perfect, thank you once again!

**Comment by MPX4132** [comment]
Thanks for letting us know. Looks like you encountered a strange bug with bash itself, rather than fluxion.
