### ISSUE TITLE
After update, cannot capture handshake

### ISSUE THREAD

**Issue by jmeeter** [FluxionNetwork/fluxion#561]
#### Summary
Since recent update, whenever I select which channel I would like to scan for access points, there is a brief error code and I am returned to channel selection screen.

##### What is the current behaviour?
There is a brief error code and I am returned to channel selection screen. Cannot progress

##### If the current behaviour is a bug, please provide the steps to reproduce it.

Select "all channels" using Xubuntu 16.04.

##### What do you think the expected behaviour should be?
I should see available access points.

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
[3;J
#### FLUXION Info
FLUXION V4.14

#### BASH Info 
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wls3) Info 
**Device**: phy0
**Driver:** iwl4965
**Chipset:** Intel Corporation PRO/Wireless 4965 AG or AGN [Kedron] (rev 61)
**Master Modes** Yes
**Injection Test:** socket(PF_PACKET) failed: Operation not permitted
This program requires root privileges.
Failed

#### XTerm Infos
**Version:** XTerm(322)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 beta3 - (C) 2006-2013 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'VERSION'
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.13.0-45-generic (buildd@lgw01-amd64-011) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018

#### Expected behavior

Continue to next screen

**Comment by MPX4132** [comment]
Please clone the latest version from the repo and check again, the issue might've been fixed.

**Comment by MPX4132** [comment]
@arismelachroinos I think you have a very different issue than that of @jmeeter since he can't even launch the attack.

Does your router/access point have both, 2.4Ghz and 5Ghz bands?
