### ISSUE TITLE
Target tracker failed to unprep attack.

### ISSUE THREAD

**Issue by suzzanadh** [FluxionNetwork/fluxion#562]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by suzzanadh** [comment]
Target tracker failed to unprep attack. finally when it tries to deauthenticate and provide fake ap this error occurs in latest version 4.14
help me

**Comment by MPX4132** [comment]
Fill the issue template.

**Comment by suzzanadh** [comment]
Then how can I get rid of this problem. Please give me the solution

**Comment by suzzanadh** [comment]
I am new here .. so I don't know where to fill the issue template
