### ISSUE TITLE
Optiontal SSL certificate?

### ISSUE THREAD

**Issue by kkar** [FluxionNetwork/fluxion#564]
### Feature Request
Hello, is it possible **to NOT** issue a certificate for the web portals? The untrusted certificate is the only reason that fluxion "doesn't work". Most users are not able to "force" their browser to trust our certificate because they don't know how. Plus, they are reading the browser's description for what's happening and they stop responding completely.

Thank you!

**Comment by deltaxflux** [comment]
Yeah that is a problem:
but since using lets encrypt is against terms and building a own one is expensive there is no other choice, use http instead.

**Comment by kkar** [comment]
@deltaxflux how am I going to use http, when the wizard has only two options, one for "new certificate" and one for "search for certificate"..? 🤓

**Comment by rad4day** [comment]
You choose to not use ssl in the previous step
