### ISSUE TITLE
"ifconfig" can't be found and fluxion won't work, but it was SOLVED by installing net-tools package

### ISSUE THREAD

**Issue by budi-darmawan** [FluxionNetwork/fluxion#567]
### Feature Request
| New Feature | yes
| RFC         | no
| BC Break    | yes (maybe)

#### Summary
Many linux distributions don't use ifconfig anymore. It was replaced by "ip" command. So if fluxion planned to use ifconfig for future release, checking/installing "net-tools" package might be good for user.

**Comment by deltaxflux** [comment]
Thank you !

**Comment by deltaxflux** [comment]
We general want to switch to ip because ifconfig is deprecated.
