### ISSUE TITLE
Fluxion Error???

### ISSUE THREAD

**Issue by bradcool22** [FluxionNetwork/fluxion#571]
"Tried to connect to session manager, None of the authentication protocols specified are supported"
I'm getting that error when Im trying to do a captive portal attack.

My wifi adapter is: Alfa AWUS036ACH
Linux Distro: Parrot OS

**Comment by mradsgh** [comment]
same issue here - any update?

**Comment by tomasaquiles** [comment]
solution to fix? here it is like this

**Comment by cjb900** [comment]
There is no fix for this. The issue is due to the chipset in this adapter that does not support VIF which is needed to be able to deauth and create a fake AP at the same time. There is also no driver that I know of that will get this adapter to work either.
