### ISSUE TITLE
Fake AP very slow ??? Why ?

### ISSUE THREAD

**Issue by paladino2** [FluxionNetwork/fluxion#573]
Hi there, i am tryng to use Fluxion, i have  got the handshake.. But i have some problem with the evil twin feature. After i started the fake AP, i tried to connect my phone but sometimes work and load the fake page in  a very slow way, sometimes is stuck on Obtaing IP address, sometimes not connect. I tried different smartphones, different wireless adapter (TP LINK WN-722N V1.10 / Alfa AWUS036NH ) , different computers for kali but always the same problem. What i should do ?

**Comment by strasharo** [comment]
Are you using airbase or hostapd?

**Comment by rad4day** [comment]
I can confirm that it is very very slow with hostapd and a Alfa AWUS036NHA, too.
Didn't test airbase yet.

**Comment by deltaxflux** [comment]
Yeah airbase is slow.

**Comment by paladino2** [comment]
I am using hostapd and airbase as well, same problem. What can i do?
