### ISSUE TITLE
Alfa AWUS036ACH does not work

### ISSUE THREAD

**Issue by ss6916** [FluxionNetwork/fluxion#576]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

Alfa AWUS036ACH does not work in Captive Portal, in the starting Captive Portal access poiint service...

Make error when trying to install Patch driver (rtl8812au)
Root@kali:~/rtl8812au# sudo make
Make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.14.0-kali3-amd64/build M=/root/rtl8812au modules
Make[1]: Entering directory '/usr/src/linux-headers-4.14.0-kali3-amd64'
  CC [M] /root/rtl8812au/core/rtw_cmd.o
  CC [M] /root/rtl8812au/core/rtw_security.o
  CC [M] /root/rtl8812au/core/rtw_debug.o
/root/rtl8812au/core/rtw_debug.c: In function ‘dump_drv_version’:
/root/rtl8812au/core/rtw_debug.c:50:62: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
                                                              ^
/root/rtl8812au/core/rtw_debug.c:50:62: warning: macro "__TIME__" might prevent reproducible builds [-Wdate-time]
  CC [M] /root/rtl8812au/core/rtw_io.o
  CC [M] /root/rtl8812au/core/rtw_ioctl_query.o
  CC [M] /root/rtl8812au/core/rtw_ioctl_set.o
  CC [M] /root/rtl8812au/core/rtw_ieee80211.o
  CC [M] /root/rtl8812au/core/rtw_mlme.o
  CC [M] /root/rtl8812au/core/rtw_mlme_ext.o
  CC [M] /root/rtl8812au/core/rtw_mi.o
  CC [M] /root/rtl8812au/core/rtw_wlan_util.o
  CC [M] /root/rtl8812au/core/rtw_vht.o
  CC [M] /root/rtl8812au/core/rtw_pwrctrl.o
  CC [M] /root/rtl8812au/core/rtw_rf.o
  CC [M] /root/rtl8812au/core/rtw_recv.o
  CC [M] /root/rtl8812au/core/rtw_sta_mgt.o
  CC [M] /root/rtl8812au/core/rtw_ap.o
  CC [M] /root/rtl8812au/core/rtw_xmit.o
  CC [M] /root/rtl8812au/core/rtw_p2p.o
  CC [M] /root/rtl8812au/core/rtw_tdls.o
  CC [M] /root/rtl8812au/core/rtw_br_ext.o
  CC [M] /root/rtl8812au/core/rtw_iol.o
  CC [M] /root/rtl8812au/core/rtw_sreset.o
  CC [M] /root/rtl8812au/core/rtw_btcoex.o
  CC [M] /root/rtl8812au/core/rtw_beamforming.o
  CC [M] /root/rtl8812au/core/rtw_odm.o
  CC [M] /root/rtl8812au/core/efuse/rtw_efuse.o
  CC [M] /root/rtl8812au/os_dep/osdep_service.o
  CC [M] /root/rtl8812au/os_dep/linux/os_intfs.o
  CC [M] /root/rtl8812au/os_dep/linux/usb_intf.o
  CC [M] /root/rtl8812au/os_dep/linux/usb_ops_linux.o
  CC [M] /root/rtl8812au/os_dep/linux/ioctl_linux.o
  CC [M] /root/rtl8812au/os_dep/linux/xmit_linux.o
  CC [M] /root/rtl8812au/os_dep/linux/mlme_linux.o
  CC [M] /root/rtl8812au/os_dep/linux/recv_linux.o
  CC [M] /root/rtl8812au/os_dep/linux/ioctl_cfg80211.o
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_indicate_connect’:
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:758:6: error: passing argument 2 of ‘cfg80211_roamed’ from incompatible pointer type [-Werror=incompatible-pointer-types]
    , notify_channel
      ^~~~~~~~~~~~~~
In file included from /root/rtl8812au/include/osdep_service_linux.h:91:0,
                 From /root/rtl8812au/include/osdep_service.h:41,
                 From /root/rtl8812au/include/drv_types.h:32,
                 From /root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:22:
/usr/src/linux-headers-4.14.0-kali3-common/include/net/cfg80211.h:5477:6: note: expected ‘struct cfg80211_roam_info *’ but argument is of type ‘struct ieee80211_channel *’
 Void cfg80211_roamed(struct net_device *dev, struct cfg80211_roam_info *info,
      ^~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:760:6: warning: passing argument 3 of ‘cfg80211_roamed’ makes integer from pointer without a cast [-Wint-conversion]
    , cur_network->network.MacAddress
      ^~~~~~~~~~~
In file included from /root/rtl8812au/include/osdep_service_linux.h:91:0,
                 From /root/rtl8812au/include/osdep_service.h:41,
                 From /root/rtl8812au/include/drv_types.h:32,
                 From /root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:22:
/usr/src/linux-headers-4.14.0-kali3-common/include/net/cfg80211.h:5477:6: note: expected ‘gfp_t {aka unsigned int}’ but argument is of type ‘unsigned char *’
 Void cfg80211_roamed(struct net_device *dev, struct cfg80211_roam_info *info,
      ^~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:756:3: error: too many arguments to function ‘cfg80211_roamed’
   Cfg80211_roamed(padapter->pnetdev
   ^~~~~~~~~~~~~~~
In file included from /root/rtl8812au/include/osdep_service_linux.h:91:0,
                 From /root/rtl8812au/include/osdep_service.h:41,
                 From /root/rtl8812au/include/drv_types.h:32,
                 From /root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:22:
/usr/src/linux-headers-4.14.0-kali3-common/include/net/cfg80211.h:5477:6: note: declared here
 Void cfg80211_roamed(struct net_device *dev, struct cfg80211_roam_info *info,
      ^~~~~~~~~~~~~~~
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_add_monitor_if’:
/root/rtl8812au/os_dep/linux/ioctl_cfg80211.c:3639:12: error: ‘struct net_device’ has no member named ‘destructor’; did you mean ‘priv_destructor’?
  Mon_ndev->destructor = rtw_ndev_destructor;
            ^~~~~~~~~~
            Priv_destructor
/root/rtl8812au/os_dep/linux

**Comment by strasharo** [comment]
We're not writing drivers for any wireless adapter, contact its developer.
