### ISSUE TITLE
Portal page not show in Device

### ISSUE THREAD

**Issue by huntergon426** [FluxionNetwork/fluxion#577]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

Hi, 
I start the Fluxion, all the step for config the attack are normal, but after the final step to start those associated damons, the monitoring window for Web Service is empty, nothing show in there. And the DNS window just show only 1 line as show below.  The Fake AP could be detected by my Iphone and laptop, and both can connect to the AP , however, cannot show the portal pages.
![image](https://user-images.githubusercontent.com/23494454/43391842-5a12866a-9424-11e8-8d1d-173af77f59c0.png)

Could you please help me on this? I cannot figure how to solve this issue though I search the wiki and google 
#### FLUXION Info
FLUXION V4.14

#### BASH Info 
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan0) Info 
**Device**: phy1
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.15.0-kali3-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-16)) #1 SMP Debian 4.15.17-1kali1 (2018-04-25)

**Comment by deltaxflux** [comment]
### Hey, 
thanks for your issue request. First please update fluxion to 4.15. If the problem still appear use following.

It looks like the lighttpd don't start propertly. Run the attack. Close the lighttpd window. And **execute**:

```
cd /tmp/fluxspace/
lighttpd -f /lighttpd.conf
```

Regards,
deltax

**Comment by huntergon426** [comment]
@deltaxflux thanks for your message. 
I tried what you told. Seems closing the lighttpd window will not terminate the lighttpd process, I need to kill it manually before I run the cmd you said. Otherwise, it promts that the port 80 is in use. After executing the cmd, I still can't got the portal page. Do I need to purge the lighttpd and use the fluxion.sh to auto install it again?

BTW, I noticed that the new diagnostic script has issue with calling the ChipsetUtils.sh.  It seems missing the 'source' cmd and the path is not right either. pls take a look. And the path issue also happen in ChipsetUtil

 
<img width="364" alt="1" src="https://user-images.githubusercontent.com/23494454/43532052-c6daf5f0-95e3-11e8-958c-7f6ff6951008.PNG">
<img width="512" alt="2" src="https://user-images.githubusercontent.com/23494454/43532062-ce05e498-95e3-11e8-8ced-8719e11a280a.PNG">

**Comment by deltaxflux** [comment]
Thanks for the quick response. My bad the command get executed in the background. We have to **kill** the **lighttpd** first. 

**Kill lighttpd:**
`kill -9 [pid]` #in your case `kill -9 4563`

After we run the **lighttpd** command like above.

> BTW, I noticed that the new diagnostic script has issue with calling the ChipsetUtils.sh. It seems missing the 'source' cmd and the path is not right either. pls take a look. And the path issue also happen in ChipsetUtills

Well, the **ChipsetUtils** has nothing to do with that. It is only for **diagnostic** and only get called if someone exectute the diagnostic.sh file. What do you mean by wrong path? If you want to exectute this script you have to call this like (inside the root fluxion directory).
`sudo ./diagnostic [interface]`

**Comment by huntergon426** [comment]
@deltaxflux 
I figure out where the problem is. it's related to my iptables setting. My default policy for INPUT chain of filter table is **DROP**. When I change to ACCEPT, it works well. But if I want to make my environment more secure, I don't want to change it to accept all packet in INPUT chain by default. Could you please tell how should I change the iptables setting?

I tried the below， seems not work. not sure if it needs to change NAT as well, please help.
```
 iptables -A INPUT -i lo -j ACCEPT
  iptables -A INPUT -i fluxwl0v -p tcp --sport 443 -j ACCEPT
  iptables -A INPUT -i fluxwl0v -p tcp --sport 80 -j ACCEPT
  iptables -A INPUT -i fluxwl0v -m state --state ESTABLISHED,RELATED -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
  iptables -t nat -A POSTROUTING -j MASQUERADE
```

**Comment by huntergon426** [comment]
just supplement, the above is changing within the attack.sh file

**Comment by deltaxflux** [comment]
Well, kind of weird because it works for me and I test this on different machines. Anyway I will take closer look at the iptables rules because @rad4day has changed these recently.

Maybe @rad4day can take a closer look at this. If not I will do it. 

Regards,

deltax

**Comment by rad4day** [comment]
@huntergon426 
I think I've found the issue. It seems like sport and dport are confused at lines 1187 and 1188 in attacks/Captive\ Portal/attack.sh

The whole iptables management is somewhat messy in the source at the moment. I'll take a look at this. But as my notebook is not functional atm and I'm pretty busy with exams it'll probably take me some time.

Also I'm pretty sure that in your example 
```
 iptables -A INPUT -i fluxwl0v -p tcp --sport 443 -j ACCEPT
  iptables -A INPUT -i fluxwl0v -p tcp --sport 80 -j ACCEPT
```
should have been
```
 iptables -A INPUT -i fluxwl0v -p tcp --dport 443 -j ACCEPT
  iptables -A INPUT -i fluxwl0v -p tcp --dport 80 -j ACCEPT
```
as we want to accept packages coming to port 80/443 and not originating from port 80/443

**Comment by rad4day** [comment]
The PR in which I introduced changes to the iptables: #444 

Those changes have been reverted as it seems to have broken the DNS script at that time.

**Comment by huntergon426** [comment]
@deltaxflux @rad4day , thank you guys, it works perfectly now.
