### ISSUE TITLE
DNS spoofer not starting on systems with systemd-resolved enabled (e.g. Ubuntu 18.04)

### ISSUE THREAD

**Issue by rad4day** [FluxionNetwork/fluxion#580]
#### Summary
systemd-resolved binds to 127.0.0.1:53 which colides with 0.0.0.0:53 of the dns script.

##### What is the current behaviour?
DNS daemon does not start. The XTerm window never appears.

#### How to reproduce
Try to run captive portal with systemd-resolved running and bound to port 53

##### What do you think the expected behaviour should be?
shutdown systemd-resolved and take note of it. Better yet fix the DNS script to not bind on every interface but only the attacking one.

We also should implement some testing into the captive portal, to see if anything failed to start.

#### Workaround for those affected:
Run `sudo systemctl stop systemd-resolved` before starting the attack. Your own dns resolution will fail until you restart it with `sudo systemctl start systemd-resolved` or reboot.

**Comment by deltaxflux** [comment]
Thank you for your investigation.
