### ISSUE TITLE
Cannot find any wifi AP?

### ISSUE THREAD

**Issue by huangzonghao** [FluxionNetwork/fluxion#581]
I am running the latest fluxion on master(0acbfeb) on a ubuntu 16.04 machine. However, when I tried to scan the nearby wifi, there was nothing being found by the script. What am I missing here?

![screenshot from 2018-08-03 23-51-16](https://user-images.githubusercontent.com/8278802/43672292-fe3f2c78-9778-11e8-8adc-74a01491e565.png)

**Comment by deltaxflux** [comment]
Run the handshake snooper attack first
