### ISSUE TITLE
split install scripts to a separate install.sh

### ISSUE THREAD

**Issue by blshkv** [FluxionNetwork/fluxion#582]
Hi, I'm thinking to port this tool to Pentoo (Gentoo) and found some bits of "emerge" commands.
This is NOT how we install things under Gentoo. Tools are not allowed to modify system settings and should not install or download anything on their own. This is a malicious behaviour typically.
It is possible to run "emerge" because there are ebuilds written for all dependencies.
I would like to write an ebuild for this tool as well. So please split fluxion.sh script into two parts: the installation and the main script. It will help me to port installation commands into an ebuild and install the main script only.

**Comment by deltaxflux** [comment]
Well the installer is already split in multiple parts / files.  
The core: `lib/installer/InstallerUtils.sh`
Gentoo specific: `lib/installer/managers/emerge.sh`

Please submit a pull request with your changes or request a improvement. I didn't use gentoo.

**Comment by blshkv** [comment]
ok, do not call any of these scripts from the main fluxion.sh It is that simple.

**Comment by rad4day** [comment]
We could probably include another function which checks if it should ask to install those automatically, and then just override the Gentoo handler with "do nothing and tell the user that something is missing".

Yes, it is "malicious" behaviour to install dependencies automatically. Still, for ease of use we included this feature and will most likely keep it, as fluxion is not really supposed to be included in a normal everyday distro.

Dunno how @deltaxflux, @strasharo and @MPX4132 think about this proposition.

P.S. @blshkv: you come along as pretty rude.

**Comment by blshkv** [comment]
@rad4day I wasn't until the issue was closed and I have been told to "go far away" and do it myself. 

I understand that the tool is new and not ready to be installed as a system tool yet. But you need to redesign it to a more "traditional" structure if you intend it to be distributed by linux distro by default.
