### ISSUE TITLE
Scenario asks user to push the WPS button if it is available 

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#584]
I Have already feedbacked this  to wifiphisher and they added it in great way ..... but i also love to see it in your  tool.... as i get more satisfaction with ........... and it's more stable and  has more success ratio than it
[https://github.com/wifiphisher/wifiphisher/issues/494](url)
can we see it in your tool ?

tbw

**Comment by deltaxflux** [comment]
This could be an enchantment.
