### ISSUE TITLE
Starting Captive Portal access point service LATEST FLUXION

### ISSUE THREAD

**Issue by kocheko** [FluxionNetwork/fluxion#585]
well i made a video so it is easier to show what happen with the computer when i try to start a captive portal...
[https://www.youtube.com/watch?v=6xbK1aeo1kg](url)

i must say i tried many other options like no ssl or whatever , but i dont know where is the problem because,  as crazy as it sound, i try reinstalling kali linux from scratch , it take a lot of time when you dual boot and also not linux expert here so, but finally reinstall everything and still the same issue...but im sure it is not the card ..but why?
because i had already did this thousand of times before, with kali linux and fluxion 3 and kali 2017 x64, with no problem at all.... so u think why update?? well i ran distro update and fluxion with some command i cant remember now but i guess that was not the problem because after fresh OS reinstall still wont work

can i get my laptop working with fluxion 5 or, if not..how can i have the old fluxion back? or some software i can do the same with... all start when i update fluxion because of those custom sites u can paste your landing into the sites folder and then the captive portal looks like the one u choose instead of generic...and i needed that specific landing for the captive portal

sound impossible? im really lost i could use some help, as u can see im learning a lot with this

and also i readed some other similar post where the fix seems to be install other driver for my card  but i dont know how to do that neither , and to the very last the only way its working again is force shutdown because when i hit shutdown , this come and takes like forever

![img_20180807_184608](https://user-images.githubusercontent.com/42158920/43806286-b0e8c4da-9a79-11e8-9a00-27c3ad420189.jpg)

**Comment by rad4day** [comment]
It's the same problem which was mentioned in #579 which I couldn't reproduce yet.

Can you tell me which kali version this is and exactly how you obtained it? Installation? 2017 dist-upgrade?

To get an old version you can use `git checkout commithash` the commithash you can obtain from the releases tab on github, or you go on code and then on history.

**Comment by usama7628674** [comment]
@kocheko If the chipset uses `ath9k` driver then you can't fix it as there is bug introduced in kernal 4.15 to onwards.

**Comment by usama7628674** [comment]
After fluxion gets stuck execute `dmesg` on terminal and look for red lines.Again if you're using adapter that uses 'ath9k' driver.

**Comment by kocheko** [comment]
So the problem is not fluxion and i have to install an old version of kali but offline so it wont update kernel, right?? Or what do i need to make this work again like before?

**Comment by kocheko** [comment]
execute dmesg:

![img_20180808_062419](https://user-images.githubusercontent.com/42158920/43829206-c686ea32-9ad4-11e8-8083-7054f76c5faf.jpg)
![img_20180808_062644](https://user-images.githubusercontent.com/42158920/43829207-c6ad532a-9ad4-11e8-899a-49c387538933.jpg)

**Comment by usama7628674** [comment]
@kocheko You can still update packages but don't upgrade kernal.Just download kali 2018.1 and install.It comes with kernal 4.14 which is the last working kernal version with fluxion.

**Comment by kocheko** [comment]
ok i will do this right now and ill come back and eventually close

**Comment by rad4day** [comment]
This is actually pretty interesting. Is this a problem only in the kali/ubuntu kernel or also in the mainline linux kernel on [kernel.org](https://kernel.org)?

**Comment by kocheko** [comment]
Im downloading kali 2018.1 but ive found some pci wireless card from old laptops...maybe someone can say me if it will work with kali and if it does, how to install the driver after i replace it

One says:  atheros wll6160-d99
The other one: broadcom bcm94312mcg

**Comment by usama7628674** [comment]
@rad4day I think the bug is in mainline linux kernal.You can track it here https://bugzilla.kernel.org/show_bug.cgi?id=199985

@kocheko Just plug it in slot and it'll auto detect it.

**Comment by deltaxflux** [comment]
Seems like this issue is resolved.
