### ISSUE TITLE
Mdk3 doesnt work when fluxion is up

### ISSUE THREAD

**Issue by PonasKovas** [FluxionNetwork/fluxion#586]
Hi I am using kali linux (the newest) and when I start Fluxion 5, everything works fine, except for the AP Jamming. It shows " Periodically re-reading blacklist/white list every 3 seconds", but I dont get kicked out of the AP. However, if I try mdk3 alone it works perfectly. I also tried to close the AP jamming window on fluxion and then do the jamming mannually, but the fluxwl0v interface throws error that injection is not supported, and when trying the fluxwl0 interface, Fluxion AP window starts throwing errors, and I still dont get kicked out of the AP. Does anyone know how can I fix this?

Edit: oops, turns out the Fluxion AP errors were being thrown when I was trying the `fluxwl0v` interface, not `fluxwl0`.

**Comment by rad4day** [comment]
Can you give us the output of the `scripts/diagnostics.sh` please?
Also what kind of errors are being thrown? This is really important to diagnose the problem

**Comment by PonasKovas** [comment]
`scripts/diagnostics.sh` output:

```
#### FLUXION Info
FLUXION V5.0


#### BASH Info 
GNU bash, version 4.4.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** iwlwifi
**Chipset:** Intel Corporation Centrino Wireless-N 1030 [Rainbow Peak] (rev 34)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 4.15.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-11)) #1 SMP Debian 4.15.11-1kali1 (2018-03-21)

#### Chipset
Chipset: iwlwifi
Don't reseve all required information
```
Then if I run this when fluxion is running:
```
# mdk3 fluxwl0v d xx:xx:xx:xx:xx:xx
ioctl(SIOCSIWMODE) failed: Device or resource busy

ARP linktype is set to 1 (Ethernet) - expected ARPHRD_IEEE80211,
ARPHRD_IEEE80211_FULL or ARPHRD_IEEE80211_PRISM instead.  Make
sure RFMON is enabled: run 'airmon-ng start fluxwl0v <#>'
Sysfs injection support was not found either.
```

Then I start getting `handle_probe_req: send failed` in the Fluxion AP Service [hostapd] window.
If I try the `mdk3 fluxwl0 d xx:xx:xx:xx:xx:xx`, then I dont get any errors, but I dont get kicked out of the AP too.

**Comment by PonasKovas** [comment]
Update:
I have updated my mdk3 from https://github.com/aircrack-ng/mdk3.
Now my AP Jammer window shows something like this:
```
Disconnecting xx:xx:xx:xx:xx:xx from xx:xx:xx:xx:xx:xx on channel 11
Disconnecting xx:xx:xx:xx:xx:xx from xx:xx:xx:xx:xx:xx on channel 11
Disconnecting xx:xx:xx:xx:xx:xx from xx:xx:xx:xx:xx:xx on channel 11
Disconnecting xx:xx:xx:xx:xx:xx from xx:xx:xx:xx:xx:xx on channel 11
Packets sent:     45 - Speed:   32 packets/sec
```
And now I actually do get kicked out of the AP, but only once, then I can freely connect again. And it looks like the window freezes. The last line (`Packets sent:     x - Speed:   x packets/sec`), keeps changing the numbers, but I don't get any more `Disconnecting` messages.

**Comment by PonasKovas** [comment]
Now it looks like I dont get disconnected even once. Also, I tried to jam manually using `aireplay-ng`, it says that `fluxwl0` is on channel -1 and doesnt work, but as soon as I close Fluxion, it starts working perfectly.

**Comment by PonasKovas** [comment]
Now I know that I have been using mdk3 command incorrectly, now I use it like this `mdk3 fluxwl0 d -b blacklist.txt`. The results are the same.
Also I know why `fluxwl0v` threw errors. It is the AP interface, with `master` mode.

**Comment by PonasKovas** [comment]
I monitored the fluxwl0 interface with wireshark, and it captured the deauth and diassociation packages, but my phone still doesnt disconnect. It looks like the virtual interface doesnt work. Can anyone please point me to the location where the interfaces are created so I can take a look?

**Comment by spphinslove** [comment]
same errors with 5.0 and 4.1 version 
I run fluxion on parrot
#### FLUXION Info
FLUXION V5.0


#### BASH Info 
GNU bash，版本 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
许可证 GPLv3+: GNU GPL 许可证第三版或者更新版本 <http://gnu.org/licenses/gpl.html>

本软件是自由软件，您可以自由地更改和重新发布。
在法律许可的情况下特此明示，本软件不提供任何担保。
**Path:** /bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** iwlwifi
**Chipset:** Intel Corporation Wireless 3160 (rev 83)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
No Answer...


#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
  File "/usr/bin/pyrit", line 9
    except pyrit_cli.PyritRuntimeError, e:
                                      ^
SyntaxError: invalid syntax
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.16.0-parrot16-amd64 (team@parrotsec.org) (gcc version 7.3.0 (Debian 7.3.0-24)) #1 SMP Parrot 4.16.16-2parrot16 (2018-07-08)

#### Chipset
Chipset: iwlwifi

**Comment by spphinslove** [comment]
when fluxion is running 
mdk3 [device] d -c X 
will show nothing

**Comment by PonasKovas** [comment]
Turns out I get disconnected when the evil twin starts, and the window doesnt say that it disconnected me. Then when I reconnect, window starts saying that it is disconnecting me, wireshark captures many packets, but I dont get disconnected again.

**Comment by spphinslove** [comment]
I download and install new version from  https://github.com/aircrack-ng/mdk3.It also show nothing.

**Comment by deltaxflux** [comment]
Yeah this is a driver problem. Maybe we should include a option for a secound interface.

**Comment by paulosperrakis** [comment]
HAS ANYONE CRACKED EVEN ONE PASSWORD ?NOOOO........

**Comment by deltaxflux** [comment]
As I mentioned:
- This is a driver problem
- However you could use a second interface
