### ISSUE TITLE
Problem with the AP Host Fake

### ISSUE THREAD

**Issue by the-curi0us** [FluxionNetwork/fluxion#587]
Hello, recently I downloaded Fluxion 5.0 in Wifislax 4.12 FINAL x86 and I have a small problem and that is that when you start the Captive Host Ap this does not disconnect the victim correctly. This causes the fake open AP to not appear correctly. This happens after I select the language of the Fake 

### The error is as follows

`/root/Descargas/fluxion-master/attacks/Captive Portal/attack.sh: línea 1425: systemctl: no se encontró la orden
[*] Starting Captive Portal access point service...
`
Since by that line of code the Ap Host does not load in a correct way preventing the connection by the IP address. What would be the solution or what do you recommend to change ?.

**Comment by rad4day** [comment]
Seems like wifislax is not using systemd.
Seems like around 1425 we check for a running network manager and stop it with systemctl.
If you make sure that no network-manager is running at that time, the script should still work, I guess.

**Comment by deltaxflux** [comment]
Yeah, thanks for catching.
