### ISSUE TITLE
Freeze Captive Portal of adapter AWUSO36AC

### ISSUE THREAD

**Issue by rickjr** [FluxionNetwork/fluxion#588]
Hello, it's very simple, I realize that only happens with the RTL8812AU drive, I'm trying to make an attack and hangs on the captive portal .... it seems to me that it is not possible to do the Access Point
Distro: 4.17.0-kali1-amd64 # 1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU / Linux
Installation: Git
Adapter: Alfa AWUSO36AC

**Comment by deltaxflux** [comment]
Please fill out the issue template.
