### ISSUE TITLE
router.sh missing ?!

### ISSUE THREAD

**Issue by H4xl0r** [FluxionNetwork/fluxion#589]
#### Summary
The router.sh script is missing under /scripts ...

#### How to reproduce
.....
##### What do you think the expected behaviour should be?

Router.sh cloning my router login

**Comment by deltaxflux** [comment]
Thanks for catching, I will upload and rewrite the script today.

**Comment by rad4day** [comment]
has been fixed in 2b8815b

**Comment by deltaxflux** [comment]
It is not fixed.

**Comment by muchomuchachos** [comment]
router.sh is incomplete and not functioning

**Comment by frosteen** [comment]
router.sh is not working. Incomplete code.

**Comment by shizzlepizzle** [comment]
anything on this?

**Comment by Hephaestus-cloud** [comment]
router.sh still missing

**Comment by deltaxflux** [comment]
The router.sh is not required anymore. At main function was to check if the given chipset support AP mode and monitor mode. However, a lot of chipset are not in this list.

**Comment by deltaxflux** [comment]
Additionally this list is hard to maintain.
