### ISSUE TITLE
Where is the .cap file stored?

### ISSUE THREAD

**Issue by syedsami8** [FluxionNetwork/fluxion#59]
Unable pass through absolute path? where is .cap file stored? 

Unable to pass through path to capture file..?

**Comment by MPX4132** [comment]
It’s stored in “attacks/Handshake Snooper/handshakes.” I think I may have fixed it in my fork. If you’d like, you can check.

**Comment by bopnrgi** [comment]
@syedsami8 Yes it's true, the fork of @MPX4132 fix the bug

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/pull/58 merged.
