### ISSUE TITLE
Raspberry Pi & Fluxion problems

### ISSUE THREAD

**Issue by KaliMalibu** [FluxionNetwork/fluxion#591]
#### Summary

Hi,

I use Raspbbery Pi 3B+ with Alfa AWUS36NHA adapter for OS is used Kali and SW Fluxion 5.0
I control it from VNC.
When I do handshake snooper all works like a charm, jamming and also can get handshake.
But when I try to set up captive portal, I lost VNC connection because wireless card build in to Raspberry lost connection.
For interface for target tracking i select "skip"
For jamming interface Atheros Communications, Inc. AR9271 802.11n 
Interface for access point is also Atheros Communications, Inc. AR9271 802.11n

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### FLUXION Info
FLUXION V5.0

#### BASH Info 
GNU bash, version 4.4.23(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan1) Info 
**Device**: phy0
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.9.80-Re4son-v7+ (root@builder) (gcc version 4.9.4 (Linaro GCC 4.9-2017.01) ) #1 SMP Thu Apr 26 17:45:16 CDT 2018

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information
root@kali:~/fluxion/scripts#

**Comment by deltaxflux** [comment]
Yeah, this is definitly a problem. Instead of killing all wireless interface cards, we should just kill the used card.

**Comment by apocalipsys** [comment]
#!/bin/bash
iw fluxwl0 del
iw fluxwl1 del
airmon-ng
#---END---
With this simple script you can continue the attack. When the script do airmon-ng you type y the number of wireless adapters that you used, and in the script if you used a wireless device, you have to delete the line that says fluxwl1, if you used 2, you have to leave it as it is, if you use 3 you have to add fluxwl2 and so on. .

**Comment by strasharo** [comment]
Works fine here, I'm controlling the RPI Zero via it's wireless interface while using external interfaces for fluxion and the connection is not lost. You might be running out of memory, so if that's the case you might want to add some extra swap on a file.
