### ISSUE TITLE
Error al iniciar el AP Fake Host

### ISSUE THREAD

**Issue by the-curi0us** [FluxionNetwork/fluxion#595]
### Bug en el AP Fake Host
I changed a Linux Kali (kali2-amd64 # 1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU / Linux)
Since with wifislax 4.12 this was another error and it was previously reflected, so I can see that little bug was repaired.
Now when the AP Host Fake starts it does not throw any error in the main terminal (where "/fluxion.sh" is executed) but in which it opens the Script (mdk3, authenticator, DNS Fake, etc.)

Everything is fine until it arrives in the part where the AP Fake will go and the following comes out
`xterm: Can´t execvp hostapd: No existe el fichero o el directorio`

Now it is unconnected and disconnects the victim but does not create the Fake AP, in 5.0 it opened the Fake AP and generated more but could not connect and in case of connecting to the Fake network it could not authenticate the key

**Comment by deltaxflux** [comment]
Ok first check which version you running on. Secound post the output of the diagnostic script and share results.

**Comment by the-curi0us** [comment]
### System and Error data
They are the only windows that will open and the system information.
Important: It is NOT a virtual machine, but it is installed on a 50 GB partition of the main hard disk
**Here are some images**
![snap1](https://user-images.githubusercontent.com/42224150/44123465-18b5adb6-9fee-11e8-863a-d2511cf15e5f.png)
![snap4](https://user-images.githubusercontent.com/42224150/44123466-18d76f78-9fee-11e8-92da-84e35873ada3.jpg)
![snap5](https://user-images.githubusercontent.com/42224150/44123467-18f44a9e-9fee-11e8-8786-b37969c5bce9.jpg)
![snap6](https://user-images.githubusercontent.com/42224150/44123468-194849a0-9fee-11e8-8225-8018a5e3d863.png)
![snap7](https://user-images.githubusercontent.com/42224150/44123469-196b380c-9fee-11e8-9a90-90ac18e31cf8.png)
![snap8](https://user-images.githubusercontent.com/42224150/44123470-19c8339a-9fee-11e8-9c62-670d998bfe81.png)
It's always Kali Linux

**Comment by deltaxflux** [comment]
Please follow the instructions I gave you:
* print the version of fluxion version
* run the diagnostic script

**Comment by the-curi0us** [comment]
### Script Diagnostic
#### FLUXION Info
```
FLUXION V5.2


#### BASH Info 
GNU bash, version 4.4.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan1) Info 
**Device**: phy4
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
./scripts/diagnostics.sh: line 79: hostapd: command not found
Path: attacks
bin
CODE_OF_CONDUCT.md
_config.yml
CONTRIBUTING.md
docs
fluxion.sh
iptables-rules
language
lib
LICENSE
logos
misc
preferences
README.md
scripts


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 4.15.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-11)) #1 SMP Debian 4.15.11-1kali1 (2018-03-21)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information
```

**Comment by deltaxflux** [comment]
apt-get install hostapd

**Comment by the-curi0us** [comment]
### Problem solved

**Thank you very much, now the Ap Fake is running correctly, but there is another problem that I will publish as a new one;)**

**Comment by lualkalibra** [comment]
ola estou com um problema no DNSFAKE que é no ap fake nao esta gerando fica barado e nao sai daquilo 
sao o mesmo problema que uma outra pessoa teve  num comentario ai em cima
