### ISSUE TITLE
High CPU usage running the script, and captive portal issue.

### ISSUE THREAD

**Issue by RubenPOR** [FluxionNetwork/fluxion#597]
#### Support Question

I recently uploaded to this new version of fluxion, the previous 0.23 rev 44 and 2 rev 9 are working fine.
I am experiencing two issues:

1 - After the "evil twin" starts, one of my CPU cores is running at 100%. I have no clue why.

2 - If I only use my alfa network card, after I connect to the "evil twin" it doesn't load the captive portal. (If I use my internal wifi card for tracking and jamming, and the alfa just for the AP, this problem doesn't occur).

I would like to use this new version, if you can help me address this issues. Thanks.

#### FLUXION Info
FLUXION V5.2

#### BASH Info 
GNU bash, versão 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licença GPLv3+: GNU GPL versão 3 ou posterior <http://gnu.org/licenses/gpl.html>.
**Path:** /bin/bash

#### Interface (wlan1) Info 
**Device**: phy1
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!

#### Interface (wlan0) Info - This is my internal wifi card
**Device**: phy0
**Driver:** iwlwifi
**Chipset:** Intel Corporation Dual Band Wireless-AC 3168NGW [Stone Peak] (rev 10)
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

I have corrected this pyrit issue with scapy, however it's not relevant for my issue.

#### System Info
**Chipset:** Linux version 4.17.0-kali1-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-25)) #1 SMP Debian 4.17.8-1kali1 (2018-07-24)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by deltaxflux** [comment]
Hey, I can't confirm this issue. In general the script is completly rewritten but there should be no performance issues. Please run fluxion with debug output:
`./fluxion -d`

Lets see if there are some interesting errors.

**Comment by RubenPOR** [comment]
Thanks for helping deltaxflux.

Debug mode produces no on screen errors. Is there a log I can post?

The problem (100% CPU usage in one CPU core) also occurs when using handshake snooper, even in passive mode. The Handshake captor window (airodump), despite saying fixed channel fluxwl0: the channel is not fixed, it is jumping channels and both beacons and Data increment slowly.

No matter what card I choose (internal or usb), the issue I've just described it's exacly the same.

I've tryed starting the script, select the Handshake snooper, the interface, etc... and just before starting the attack tryed in a separate terminal running airodump with the options used in the attack.sh line 145 (airodump-ng --ignore-negative-one -d MAC -w test.cap -c 12 -a fluxwl0), and it runs smooth.

**Comment by deltaxflux** [comment]
Sounds like something is messed up. As I mentioned I can't reproduce this issue. I monitor fluxion using htop/top but I don't have the same results. The only idea I have is that it could be something with drivers. Why?
* you said running airodump-ng manually is ok
* which is why I think you driver only partly support virtual interface

> No matter what card I choose (internal or usb), the issue I've just described it's exacly the same.

And this is strange too

No solution sorry :(
Regards,

**Comment by RubenPOR** [comment]
When I first tried the new script, I was also thinking it should be an issue with the virtual interface, since it's a new thing when compared to the fluxion versions I've mentioned.

But the problems are also present with the handshake snooper, before a virtual interface is needed or initialized. Could it be something related to way the interface is set into monitor mode? (I don't think so because with the monitor mode initialized with the script and then running airodump manually in a different terminal everything runs smooth)

And like you said, it's strange I am having the exact same issue with a different card that uses a different driver. Don't you agree?

Since you can't reproduce the issue, if you remember anything I can change in the script to test...

**Comment by deltaxflux** [comment]
No the handshake snooper use also virtual interface. Which might be the problem here. I don't want to rewrite fluxion because some chipsets doesn't support this. I hope you could understand that. However, I think it is worth to take a look at.

Are you running kali in a virtual box?

**Comment by demecoandrea** [comment]
I'm having the same issue: one core is working at 100% (25% load on a quad-core).
Task manager says that airmon-ng is the CPU sucker (constant 25% cpu load).

I'm using Fluxion 5.6; previously I used Fluxion 2.9 and it worked well, without CPU overloading. 
I'm on Ubuntu 16.04 persistent usb  (yeah, i know, I should use the new kali... i'm lazy; but i don't think this is the direct problem..)

Network controller: Broadcom Corporation BCM4313 802.11bgn Wireless Network Adapter (rev 01)

**Comment by rad4day** [comment]
Linux handles the Load indicator a little different than windows. 0.25 represents 1 core utilized to 25%
All cores at 100% would be 4.0 in your case.

**Comment by demecoandrea** [comment]
@rad4day yeah sorry, I wasn't clear, but I'm sure we're saying the same thing.. 1 core working at 100%; anyway that's not the point xD

the attack can last hours, so I don't want my laptop to run that load for so long, so for the moment, I added a "sleep 20" into the while-true that calls the airodump-ng (line ~1362) 
this way the CPU load should be reduced by 2/3 .. (the monitorTimeout is set to 10 seconds, so in 30 seconds I should have 1/3 working and 2/3 "idle")
obviously this way any change of the AP tracked info could be detected with up to 20 seconds of delay, but I think this is acceptable, rather than melting my laptop LoL

**Comment by deltaxflux** [comment]
Yeah sounds for a solution for you. I may add a variable for that.
