### ISSUE TITLE
Installing dependencies after v5

### ISSUE THREAD

**Issue by M1z23R** [FluxionNetwork/fluxion#598]
It seems something broke the dependency installer after getting fresh fluxiom on a fresh OS.
I am on a Raspberry Pi 3 using raspbian, for some reason dependency check doesn’t pop up and it won’t install dependencies, I’ve tried running installer script from lib folder but also without luck.

**Comment by deltaxflux** [comment]
Yeah, I disabled this in the last commit. Run fluxion -i to install all dependencies.

**Comment by M1z23R** [comment]
Thanks a lot, wasn't really paying attention to changes.

**Comment by Tortuga619** [comment]
I tried downloading dependencies with ./fluxion.sh -i and still wont let me im running linux 18.2

**Comment by rad4day** [comment]
@Tortuga619 which year do we have? I thought 4.x was the newest

**Comment by deltaxflux** [comment]
@rad4day He lives properly in the future.

**Comment by usama7628674** [comment]
I think he forgot mint after linux.

**Comment by Tortuga619** [comment]
Sorry i have kali linux version 2018.2 and i downloaded fluxion and updated it it says its version 5 when i run it am i missjng something??? Im quite a newby

**Comment by Tortuga619** [comment]
I downloaded of kalilinux.org for a virtual machine to check it out what would you recommend where i can build all my own apps and dependencies rather than theirs it seems like all the apps are half built???

**Comment by Tortuga619** [comment]
And whenever i yry fownloading any missing deppendencies they cant be found?

**Comment by deltaxflux** [comment]
Well, you can try to launch fluxion -i to install missing dependencies.

**Comment by Tortuga619** [comment]
@deltaxflux i tried that and it says E: unable to locate

**Comment by deltaxflux** [comment]
Can you please provide screenshots and post on **one** issue.
