### ISSUE TITLE
DHCP does not start

### ISSUE THREAD

**Issue by the-curi0us** [FluxionNetwork/fluxion#599]
### IP is not granted to the victim

Previously, the DHCP server started together with the other tools and now does not start, therefore, when a device connects to the fake AP, it does not provide an IP address, therefore, the connection is not established with the device. As a result, the victim can not enter the password and only loses his connection foolishly

**Comment by deltaxflux** [comment]
Can you please post the output of the diagnostic script?

**Comment by the-curi0us** [comment]
Yes, missing packages, thanks to the new version of Fluxion (5.4) I got the list of missing packages. At the moment there is no Bug ;)
