### ISSUE TITLE
Issues / Ideas

### ISSUE THREAD

**Issue by deltaxflux** [FluxionNetwork/fluxion#60]
Since @MPX4132 publish his great code, I noticed some bugs related to the usability.  There are some bugs related to os.

1. Bug [Signal / Power] measurement is incorrectly 
I noticed that right at the beginning. Signal strength goes over 100%. And the power value is negative.

I think the easiest way to fix that, is to increase the power value by 100. 

```
power = $(echo $((power + 100)) )
```

2. Bug Incompatible with many different OS
The next bug is a small bug. It is caused by this line
```
readarray -t WIAvailableData < <(airmon-ng | grep -P 'wlan\d+' | sed -r 's/[ ]{2,}|\t+/:_:/g')
```

The main idea is that all interfaces have the name wlanX. This is not true. Many OS like the arch or unstable Debian branches follows the idea of a "random" interface name. To be honest, random is not exactly true because the name is giving by the USB port plugged it. In fact, this produces names like:

```
sudo airmon-ng         
[sudo] Passwort für deltax: 

PHY     Interface       Driver          Chipset

phy0    wlp0s29u1u4     rt2800usb       Ralink Technology, Corp. RT2870/RT3070
```
This is why no wireless interfaces output was given. My idea was better but it could easier brick in newer versions of airmon-ng. 

Another point is that in the arch the xterm terminal package is broken. There is already an issue open but it could take much longer to fix this since the gnome developer decides to replace their c code with rust. In fact, I will look for an alternative. This is only caused by the desktop environment gnome.

3.  Installer is not by default executable 
4. Brackets are too much in web interface function
5. Languages should get fixed 

In fact, the version 3 was great. MPX4132 do his best to make fluxion a way better. These are only small issues and I will fix it at the weekend. 

# Improvements

1.  Auto handshake check and continue?
2. Auto resize ap_select output function if essid is oversized

**Comment by MPX4132** [comment]
Thanks, this is good constructive feed back. I'll try helping getting those issues fixed as well. I feel a bit responsible for breaking that functionality, which is why I've been trying to kill all the bugs I introduced. I'm currently trying to improve the language issue.

**Comment by deltaxflux** [comment]
Thank you, I will also work on it.

**Comment by MPX4132** [comment]
Sure thing. I read Arch's wireless interfaces begin with wl, so I changed the regular expression to 'wl(an\d+|\w+)' which might help fix the OS issue. I apologize for not realizing why you guys had done it the original way, I thought Kali and other debian derivatives were the target platform, which is why I didn't bother testing it in other systems before submitting the pull request for V3.

**Comment by MPX4132** [comment]
The 3rd one seems pretty easy to fix, although I haven't looked in the installer. Do you mind explaining what you mean with "Brackets are too much in web interface function?" I don't think understand what you mean.

**Comment by strasharo** [comment]
3) corrected.

**Comment by strasharo** [comment]
By the way, does anyone else have issues with mdk3 running on the latest Kali? Doesn't appear to be picking up anything for deauth and I have to resort back to deauth either using aireplay or an external tool such as wifijammer.

**Comment by deltaxflux** [comment]
Well, I use arch so I can't confirm this problem. Do you use a stock kali or is it completely upgraded?

**Comment by MPX4132** [comment]
Yeah, the mdk3 jammer is super aggressive. It corrupts handshakes, from what I’ve seen. I tested it and only got handshakes if I kept trying to reconnect. I added the “not recommend” tag to it because of that. I hadn’t used mdk3 much before, so I don’t know if it changed recently, but it’s been super agressive since I started working on fluxion. Oh the other hand, it’s great for jamming target APs.

**Comment by strasharo** [comment]
Thing is it doesn't even try to deauth here on a fully upgraded Kali. @deltaxflux does it deauth on Arch?

**Comment by deltaxflux** [comment]
For me, airplay-ng and mdk3 works flawless in  arch :) Better use arch.

**Comment by MPX4132** [comment]
Yeah, they both work fine on my end too (Kali). The only quirk is that mdk3 is just super aggressive.

**Comment by deltaxflux** [comment]
<p align="center"><img src="http://i.imgur.com/KO4wijm.png" /></p>

At the latest point "zurück"(back) are brackets too much. We should check if the language text is empty.

**Comment by MPX4132** [comment]
I removed the brackets completely, they looked a bit weird anyway. I made the portal options auto-center, but I'm thinking of reverting that change since it may look weird on large screens.

**Comment by deltaxflux** [comment]
Well, I kind of like it but this is a personal preference.

**Comment by MPX4132** [comment]
I liked it too, I was just being lazy last night because I was kinda tired.

**Comment by deltaxflux** [comment]
Don't worry about that.

**Comment by deltaxflux** [comment]
All bugs fixed so far
