### ISSUE TITLE
support rtl8812au

### ISSUE THREAD

**Issue by mayankmetha** [FluxionNetwork/fluxion#600]
please add support for rtl8812au

**Comment by usama7628674** [comment]
@mayankmetha The next release of airmon will have support for this driver.You can read here
https://github.com/aircrack-ng/rtl8812au/issues/93#issuecomment-414074458
If you really want this driver to work even without airmon support consider using airgeddon.

**Comment by deltaxflux** [comment]
To improve the understanding. The chipset seems like to be supported by aircrack. However, this patch not included.

> If you really want this driver to work even without airmon support consider using airgeddon.

And this is the point. It is not a problem with fluxion autem with aircrack-ng. So this wrong.

Because this issue is not related to fluxion I will close this issue.
