### ISSUE TITLE
AWUS1900 with  Kali on Raspi - no handshake captured

### ISSUE THREAD

**Issue by H1Andel** [FluxionNetwork/fluxion#601]
#### Support Question
* Sorry, not familiar with Discord or Gitter. Have looked at a number of issues but to no avai. 

 I thought I had the AWUS1900 working but there seems to be no handshake captured.  Ran the diagnostic script. The "Chipset is not in list"seems a bit alarming although I'm not sure what it means. 

Is this a driver issue  of am I doing something wrong? 

Running Kali on RasPi

#### FLUXION Info
FLUXION V5.2

#### BASH Info 
GNU bash, version 4.4.18(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan1) Info 
**Device**: phy1
**Driver:** 8814au
**Chipset:** Realtek Semiconductor Corp. 
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
./diagnostics.sh: line 79: hostapd: command not found
Path: debug.sh
diagnostics.sh
preferences.sh

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
./diagnostics.sh: line 89: pyrit: command not found
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.14.50-Re4son-v7+ (root@kali-pi-dev) (gcc version 6.3.0 20170516 (Debian 6.3.0-18)) #4 SMP Thu Jul 19 11:07:19 AEST 2018

#### Chipset
Chipset: 8814au
Chipset is not in list

**Comment by deltaxflux** [comment]
Please run fluxion -i first.

**Comment by H1Andel** [comment]
Will do & get back to you.

**Comment by H1Andel** [comment]
Works now ! Thanks a millions.
