### ISSUE TITLE
Change of Domain and SSL of Let's Encrypt

### ISSUE THREAD

**Issue by the-curi0us** [FluxionNetwork/fluxion#603]
|    Q        |   A
|------------ | -----
| Fluxion      | 5.4

#### How can I change the Domain (captive.gateway.lan) to (mydomain.com) and in turn is Fluxion compatible with the Let's Encrypt SSL certificates of 4000 bits?
I would like to know how to change the domain that is by default (captive.gateway.lan) in mine (mydomain.com) since I recently tried to find the code of Fluxion and I have not found the correct code line.
This is to be able to correctly carry out the SSL certificate of Let's Encrypt since it only works with a certain domain.

On the other hand, I would like to know if it is compatible with Let's Encrypt SSL to replace the "server.pem" with a valid certificate and, if the answer is yes, what is the order in which the .pem file should go?

#### FLUXION Info
```
FLUXION V5.4


#### BASH Info 
GNU bash, version 4.4.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (wlan1) Info 
**Device**: phy2
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 4.15.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-11)) #1 SMP Debian 4.15.11-1kali1 (2018-03-21)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information
```

**Comment by the-curi0us** [comment]
I have a certificate and I can not make Fluxion detect it, what route, format or name should I put / place?

**Comment by deltaxflux** [comment]
This is against terms so I closing this for now.
