### ISSUE TITLE
Domain change for a custom one

### ISSUE THREAD

**Issue by the-curi0us** [FluxionNetwork/fluxion#604]
|    Q        |   A
|------------ | -----
| Version     | Fluxion 5.5

**I would like to know how I can change the domain of the captive page, only that, since I have tried to modify it by a custom one and I have not achieved it since in the part where AP Fake starts, it is executed incorrectly and remains blocked. Would you be so kind as to tell me what line of code should make the change?**

**Comment by deltaxflux** [comment]
In attack/Captive Portal/attack.sh ~line 293
