### ISSUE TITLE
deauth-ng.py missing

### ISSUE THREAD

**Issue by scarfy000** [FluxionNetwork/fluxion#605]
After selecting the captive portal UI, the AP jammer service throw up the error

> bash: .//tmp/captive_portal/deauth-ng.py: no such file or directory.

Checked /tmp/fluxspace and in fact deauth-ng wasn't there.

I've selected the same interface for both jamming and hosting the AP with hostapd (same using airbase-ng)
The version I was previously using, the 3.11, works flawlessly.
Any idea?

#### FLUXION Info
FLUXION V5.5

#### BASH Info 
GNU bash, versione 4.4.12(1)-release (i686-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licenza GPLv3+: GNU GPL versione 3 o successiva <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (fluxwl0) Info 
**Device**: phy1
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(333)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.14.0-kali3-686-pae (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-18)) #1 SMP Debian 4.14.12-2kali1 (2018-01-08)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by TheWebs** [comment]
I also have this problem

**Comment by scarfy000** [comment]
Release 5.6 fixed the issue for me.
