### ISSUE TITLE
Increase of manufacturer pages for Mexico

### ISSUE THREAD

**Issue by the-curi0us** [FluxionNetwork/fluxion#606]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### New Pages
Hello, deltaxflux. I would like to ask you if you can add some indexes in the Fluxion repositories for the Captive Portal of Mexico, if so, do I leave the download link? or where I send it

**Comment by cgomezmendez** [comment]
You can clone the repo and add then yourself

**Comment by rad4day** [comment]
If you're not capable of doing so, leave a link here. Somebody will probably add those ^^

**Comment by the-curi0us** [comment]
The indexes that I have already done are already proven, but I want them to be renamed and loaded in the official repository

**Comment by deltaxflux** [comment]
Post a download link and I will take a closer look.

**Comment by the-curi0us** [comment]
You're welcome

**Comment by Gabo1203** [comment]
> The indexes that I have already done are already proven, but I want them to be renamed and loaded in the official repository

Good morning, could you help me add a new site that you shared, in my country we have the same manufacturer pages and I do not know how to add it to fluxion.
Thanks for the help you can provide.

Buenos días, podría ayudarme a agregar un nuevo sitio de los que compartiste, en mi país tenemos páginas de fabricantes iguales y no se como agregarla a fluxion.
Gracias por la ayuda que puedas brindar.

**Comment by the-curi0us** [comment]
Claro, para poder ayudarlo primero descargue las paginas desde el link en el cual tengo proporcionado anteriormente, una vez hecho.
Descomprima el archivo zip con `unzip "Pages FLuxion"`
Situese en el directorio en el cual lo haiga descargado
Luego copie los archivos `/tu/diectorio/fluxion/attacks/Captive Portal/sites` y en sites pegue las carpetas descomprimidas
Vuelva a ejecutar fluxion con `./fluxion.sh` y listo, cualquier duda o problema puede escribirlo y con gusto lo ayudare.
Bonita tarde

**Comment by strasharo** [comment]
If anyone's interested in contributing pages for this just create a pull request.
