### ISSUE TITLE
Cannot install missing file.

### ISSUE THREAD

**Issue by monday88** [FluxionNetwork/fluxion#607]
Dear,
Your fluxion app install missing file say " No internet connection found! ".
If I No internet connection found,  why I can detect online version 5.5 ???
![untitled](https://user-images.githubusercontent.com/35053957/44625448-5260af00-a93c-11e8-926a-e1ccef5b70ed.jpg)

**Comment by brutebeer911** [comment]
Hi All,

I am also encountering this.

Systeminfo:
HW:Asus Nexus 7 2012
OS: Kali Sana 2.0
Kernel: 3.1.10
External ralink 3070

**Comment by H4yseed** [comment]
Hi guys, same problem here and I'm on this system:

Gnome version 3.28.0
Memory 7.7 GO
Proc Intelcore i5 @ 2.40 Ghz
Grafic card: Geforce GT540M
OS: Kali GNU/Linux Rolling
64 bits

**Comment by brutebeer911** [comment]
i already figure out my prob.. i used sudo.. sudo ./fluxion.sh -i ..

already install proper pre req.. but it jump to choose SSID with mixedup characters in text step rather than choosing "captive portal" or "handshake snooper".

Thanks for replying dev master.

**Comment by deltaxflux** [comment]
Can you please provide screenshots

**Comment by deltaxflux** [comment]
and open a new issue.
