### ISSUE TITLE
Please let me know what version linux OS your use?

### ISSUE THREAD

**Issue by monday88** [FluxionNetwork/fluxion#608]
Dear Mr/Miss,
Can you let me know what version linux OS your use?
I use this linux OS have problem.
https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-hyperv-image-download/
Office Kali Linux Vm 64 Bit [Zip]
What version your use?
Now only can use fluxion old version 3.10 with kali linux 2016.2 very stable.
fluxion 5.5 with kali linux 2018.2 cannot use.

**Comment by scarfy000** [comment]
Do not use VM.
Try with a regular version.

**Comment by monday88** [comment]
@scarfy000 
I use very stable version is fluxion v3.10 with kali linux 2016.2.
This version very very stable.
VMware is office version I sure no problem.
