### ISSUE TITLE
fluxion crash when I try create AP

### ISSUE THREAD

**Issue by dedetuga** [FluxionNetwork/fluxion#609]
#### Support Question
hi,
I'm having troubles getting fluxion to work
I successful get the handshake but now I can't get the AP working,
it always crash here when i use with hostapd

[*] Starting Captive Portal access point service...

or

[*] Starting Captive Portal access point service...
[*] Starting Captive Portal access point routes...

![captura de ecra de 2018-08-27 10-51-30](https://user-images.githubusercontent.com/6078660/44651616-26036c00-a9ea-11e8-8091-40b202bee40f.png)

and if I try aireplay-ng it start but i never get an ip

![captura de ecra de 2018-08-27 10-40-12](https://user-images.githubusercontent.com/6078660/44651645-39aed280-a9ea-11e8-85d2-afd7221da8ad.png)

to run fluxion i run first:

service isc-dhcp-server start

airmon-ng check kill

./fluxion/fluxion.sh

what I'm missing? i already run a bunch of tutorial from web and nothing work

#### FLUXION Info
FLUXION V5.5

#### BASH Info 
GNU bash, versão 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licença GPLv3+: GNU GPL versão 3 ou posterior <http://gnu.org/licenses/gpl.html>.

Este é um software livre; você é livre para alterar e redistribuí-lo.
Há NENHUMA GARANTIA, na extensão permitida pela lei.
**Path:** /bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k
**Chipset:** Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter (rev 01)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(335)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.17.0-kali3-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-28)) #1 SMP Debian 4.17.17-1kali1 (2018-08-21)

#### Chipset
Chipset: ath9k
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by usama7628674** [comment]
@dedetuga It's a bug in kernal you can verify it by checking `dmesg` log after fluxion crashes.You can use airgeddon tool if you want to use `ath9k` driver or downgrade your kernal to 4.14.x.

**Comment by dedetuga** [comment]
thanks for reply, I'm exploring you sugestion
