### ISSUE TITLE
Stuck on removing extraneous interfaces

### ISSUE THREAD

**Issue by Geczy** [FluxionNetwork/fluxion#61]
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

----

### What is the current behavior?
-> *Hangs*

---

#### If the current behavior is a bug, please provide the steps to reproduce.

![image](https://user-images.githubusercontent.com/1036968/29196770-a73683a6-7e04-11e7-97c4-8eb82c73b334.png)

--- 

#### What is the expected behavior?
-> *No hang*

---

#### Wireless adapter:
USB3: ALFA AWUS036ACH
Chipset: RTL8812AU

#### Fluxion version 
Latest of https://github.com/FluxionNetwork/fluxion/commit/aaa0efc2259691c260b368590347b060b9992018

#### Linux version:

Kali 4.9.0 kali3 amd64

**Comment by MPX4132** [comment]
I've had a similar experience, but my issue seemed to be related to the wireless driver hanging. I pulled the device out and plugged it back in. I chose to repeat the operation (rescan for wireless devices), it came up and started working fine after that. This happened on the current version of Kali (up to date, rolling).

**Comment by Unbotux** [comment]
I

**Comment by strasharo** [comment]
We can do nothing about driver hangs, try removing and adding the adapter as suggested by @MPX4132 .
