### ISSUE TITLE
Any one can help me..

### ISSUE THREAD

**Issue by kumyoung** [FluxionNetwork/fluxion#610]
|    Q        |   A
|------------ | -----
| Version     | 5.5

#### Support Question
Fluxion 3.11 on my kali Version 3.25.92 is no problem... 
Fluxion 5.5 cannot run on my kali Version 3.25.92

#### Specs
Kali Version 3.25.92
Memory 1gb
Processor: Intel® Celeron(R) M CPU 440 @ 1.86GHz
Graphics: Intel® 945GM x86/MMX/SSE2
Base system: Kali GNU/Linux Rolling 32-bit
Disk: 154.9 GB
![screenshot from 2018-08-27 17-08-28](https://user-images.githubusercontent.com/26023750/44651942-3d0f8180-aa1d-11e8-81e5-95baf4a01479.png)
![screenshot from 2018-08-27 17-16-52](https://user-images.githubusercontent.com/26023750/44651957-47ca1680-aa1d-11e8-8c42-42178a6a3aa1.png)
![screenshot from 2018-08-27 17-17-11](https://user-images.githubusercontent.com/26023750/44651975-557f9c00-aa1d-11e8-89b1-fdc13028f374.png)
![screenshot from 2018-08-27 17-17-04](https://user-images.githubusercontent.com/26023750/44651966-4dbff780-aa1d-11e8-925c-989e673fb35d.png)

**Comment by deltaxflux** [comment]
I think your kali is broken, please check if it is running on the latest kali version.
