### ISSUE TITLE
Change redirects to "HTTPS -> HTTP and HTTPS -> HTTP"

### ISSUE THREAD

**Issue by the-curi0us** [FluxionNetwork/fluxion#616]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

####Modify the way you redirect
Below are two images in which they contain a schema with the problem or suggestion. It's already explained. ;)
![fluxion redirecciones](https://user-images.githubusercontent.com/42224150/45004333-57170a00-afb1-11e8-839f-a5155bcf43d0.png)
![fluxion](https://user-images.githubusercontent.com/42224150/45004348-701fbb00-afb1-11e8-9065-599b79f68ed0.png)

**Comment by the-curi0us** [comment]
What is needed is to modify the code so that the redirects do this "HTTPS -> HTTP and HTTPS -> HTTPS" because the pages that the user always looks for or the majority is HTTPS and if an HTTP page is needed, the redirection could not complete and the attack will not succeed, all this if the victim only has computers, in Android and IOS there is no such problem since both in a pop-up window and in a notification appears the "Login" that the computers do not have configured and depend on the redirect or else the victim will never see the fake page

**Comment by rad4day** [comment]
You can't just redirect HTTPS traffic without a valid certificate for the domain used. Would be way to easy if it was possible :(

So we are not able to redirect HTTPS pages to the captive portal without the "invalid certificate" warning in the browser.

**Comment by the-curi0us** [comment]
The certificate I have is valid, but what I want to suggest is that it is necessary that HTTPS URLs are redirected to HTTP, because if the pages are redirected from HTTP to another HTTP and the victim places the following "https://youtube.com" you can not redirect and you need to place, for example, "http://eshost.com.ar" to be redirected, tell me who collects http pages to verify if you have a connection?

**Comment by the-curi0us** [comment]
I do not request that traffic be sent to HTTPS, but that HTTPS traffic be redirected to HTTP

**Comment by rad4day** [comment]
that would also require a 30X redirect directive, which needs a TLS session to be established beforehand and therefore is not possible

**Comment by the-curi0us** [comment]
This redirect code is compatible or only for hosting .htaccess?
It is supposed to redirect from HTTPS to HTTP
```
RewriteEngine On
RewriteCond %{HTTPS} on
RewriteRule (.*) http://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

**Comment by the-curi0us** [comment]
How could they be translated?
```
$ HTTP ["scheme"] == "http" {
    # capture vhost name con regex conditiona ->% 0 en patrón de redireccionamiento
    # debe ser el bloque más interno a la regla de redirección
    $ HTTP ["host"] = ~ ". *" {
        url.redirect = (". *" => "https: //% 0 $ 0")
    }
}
```
Ejemplo 2 - url específico
```
$ HTTP ["scheme"] == "http" {
    $ HTTP ["host"] = ~ ". *" {
        url.redirect = ("^ / phpmyadmin /.*" => "https: //% 0 $ 0")
    }
}
```
It also works the other way around (https -> http) with if $ HTTP ["scheme"] == "https"
I'll see if I can evade the error and redirect HTTPS to HTTP

**Comment by the-curi0us** [comment]
Bye
