### ISSUE TITLE
Page check.php is broken?

### ISSUE THREAD

**Issue by waidoshoruda** [FluxionNetwork/fluxion#618]
Fuxion 5.6

Hi,

in Captive Site attack page check.php is broken? The page doesn't validate any WIFI password, even the correct WIFI password.

I used the generic Captive Site released with fluxion.

Thanks.

**Comment by deltaxflux** [comment]
Ok sounds weird. I never changed any since fluxion 4.10.

**Comment by waidoshoruda** [comment]
How i can help you to help me?

Thanks.

**Comment by the-curi0us** [comment]
Normally it happens when verifying several WPA key authentications and it is necessary to download them again in version 5.6 or more stable 4.10

**Comment by minanagehsalalma** [comment]
@deltaxflux @the-curious ... i am facing this problem too... it only happens in the latest version

**Comment by strasharo** [comment]
It appears that the output of aricrack-ng changed from "Passphrase not in" to "KEY NOT FOUND" recently. Will add a fix shortly.

**Comment by minanagehsalalma** [comment]
@strasharo  OK thanks gonna test it 😁😁😁

**Comment by xlinse** [comment]
Same problem "key not found" in fluxion  can any one help me?
