### ISSUE TITLE
[Request] Put a model of a custom attack somewhere

### ISSUE THREAD

**Issue by Blaxou** [FluxionNetwork/fluxion#62]
#### Do you want to request a *feature* or report a *bug*?
-> *Feature*

----

#### What is the expected behavior?
-> *It would be cool to have a model of a custom attack. To ease the creation of custom attacks from others. For example a Wifi Page with all the Variables avalaible etc.
It might be in the code, but I think reading all the code for the variables needed and the provided variables is a bit too much  :D*

---

#### If this is a feature request, what is motivation or use case for changing the behavior?
-> *Allow people to make custom attacks easily*

---

**Comment by deltaxflux** [comment]
Sorry, I don't understand what you try to express.

**Comment by Blaxou** [comment]
I mean as @MPX3142 said :
*Installation of new attacks or portals is done by adding a directory with contents, what is referred to here as "bundle."*

So is there any specific scheme needed to create a "bundle" ?

**Comment by MPX4132** [comment]
Yeah, I'll try to make an example somewhere, my bad. I was pretty tired that day so I didn't elaborate much.

**Comment by MPX4132** [comment]
Actually, I think the project should have Wikis enabled, they're currently disabled (Settings > Features > Wikis). I could add some documentation there about how to create custom attacks, and other content, like portals.

**Comment by Sismondi** [comment]
Exactly what I meant, thanks for you awesome work by the way !

**Comment by Blaxou** [comment]
Exactly what I meant !Thank you for your awesome work by the way !

**Comment by deltaxflux** [comment]
Well I will create a tutorial in our wiki

**Comment by Blaxou** [comment]
Thank you 😁

**Comment by deltaxflux** [comment]
Check the wiki

**Comment by Blaxou** [comment]
Nice ! Hope you'll make a page for the attacks too :)

**Comment by MPX4132** [comment]
I made a [wiki page](https://github.com/FluxionNetwork/fluxion/wiki/Custom-attack-scripts) about them, hopefully it clears things up a bit.
