### ISSUE TITLE
starting captive portal access point service...

### ISSUE THREAD

**Issue by Black-RTX** [FluxionNetwork/fluxion#620]
after Extracting the handshake and make Fake AP and Choose language 
This sentence appears 
starting captive portal access point service...
and the computer starts to freeze.... I can not control anything other than re
![new](https://user-images.githubusercontent.com/42094275/45332649-21a28b80-b572-11e8-9e10-4a2ef97c968d.png)
starting it
how to fix it ?

**Comment by thxqua** [comment]
Got this problem also

**Comment by Black-RTX** [comment]
need fix

**Comment by usama7628674** [comment]
@Black-RTX @thxqua Please post the output of diagnostic script.

**Comment by the-curi0us** [comment]
This happens when a file is modified within the code line, but if you have not modified it, you must download the version of fluxion 4.10 or 5.6

4.10 https://github.com/FluxionNetwork/fluxion/archive/v4.10.zip
5.6 git clone https://github.com/FluxionNetwork/fluxion.git

**Comment by Black-RTX** [comment]
Thanks

**Comment by Mikewins1** [comment]
Same problem here.  After 10 times sometimes it will work.  I have to restart whole computer and always have 3 stop jobs for 10 minutes

**Comment by Mikewins1** [comment]
i also just reinstalled it with the link you provided above.  Didnt solve anything  same problem

**Comment by usama7628674** [comment]
@Mikewins1 Could you please post the output of diagnostic script ?

**Comment by Mikewins1** [comment]
What code do you want me to run?

**Comment by usama7628674** [comment]
@Mikewins1 Nanigate to scripts and run `bash diagnostics.sh`

**Comment by the-curi0us** [comment]
It is necessary to execute this script because if a package is missing we can tell you which one to install, normally in these cases it is the HTTPD

**Comment by Mikewins1** [comment]
I got
Usage. /scripts/diagnostics [wireless_interface]

**Comment by the-curi0us** [comment]
To be able to run the Diagnostic script it is necessary to be in the same directory

**Comment by the-curi0us** [comment]
Once executed, copy everything that appears in the terminal and paste it here so we can help you

**Comment by Mikewins1** [comment]
I was in CD fluxion/scripts.
That was the output

**Comment by Mikewins1** [comment]
root@KALI:~/fluxion/scripts# bash diagnostics.sh -i wlan1

#### FLUXION Info
FLUXION V5.6


#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (-i) Info 
**Device:** Unknown
basename: missing operand
Try 'basename --help' for more information.
**Driver:** Unsupported
**Chipset:** 
**Master Modes** Yes
**Injection Test:** aireplay-ng: option requires an argument -- 'i'
Failed


#### XTerm Infos
**Version:** XTerm(335)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'VERSION'
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.18.0-kali1-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-29)) #1 SMP Debian 4.18.6-1kali1 (2018-09-10)

#### Chipset
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Chipset: 
Invalid input, chipset appears invalid
root@KALI:~/fluxion/scripts# 
----I am using alfa AWUS036NH
AND HER IS THE OUTPUT FOR TL-WN722N V!
#### FLUXION Info
FLUXION V5.6


#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (-i) Info 
**Device:** Unknown
basename: missing operand
Try 'basename --help' for more information.
**Driver:** Unsupported
**Chipset:** 
**Master Modes** Yes
**Injection Test:** aireplay-ng: option requires an argument -- 'i'
Failed


#### XTerm Infos
**Version:** XTerm(335)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'VERSION'
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.18.0-kali1-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-29)) #1 SMP Debian 4.18.6-1kali1 (2018-09-10)

#### Chipset
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Chipset: 
Invalid input, chipset appears invalid
root@KALI:~/fluxion/scripts#

**Comment by usama7628674** [comment]
@Mikewins1 After fluxion crashes check `dmesg` log and look for red lines and if there's any of it then post the pic of those red lines.

**Comment by the-curi0us** [comment]
Depending on the diagnosis, the network interface is not compatible and therefore can not start the services

**Comment by usama7628674** [comment]
@the-curi0us I'm talking about `ath9k` driver that was working fine until those injection patches for spectre and meltdown introduced in 4.15 kernal and that's after that fluxion is crashing constantly at same phase.

**Comment by the-curi0us** [comment]
well I have the kali 2018.2

**Comment by usama7628674** [comment]
So you're also afftected if your wireless adapter has atheros chipset.

**Comment by Mikewins1** [comment]
So I can only use my Alfa card?

**Comment by MinePro120** [comment]
I have this problem too. What's the solution?

**Comment by Mikewins1** [comment]
Isn't it better to use 2 network cards? One for the AP and one for the death? I hate having one card do both. Or does it make a difference?

**Comment by the-curi0us** [comment]
I use a W722N and I can place the Jamming service and the fake AP on the same wireless interface
![img_20180925_231123](https://user-images.githubusercontent.com/42224150/46056917-a49e1700-c118-11e8-8fa7-cc807dc66dd7.jpg)
![img_20180925_230958](https://user-images.githubusercontent.com/42224150/46056925-b2539c80-c118-11e8-90ac-6bb726207310.jpg)

**Comment by jaspervanbrian** [comment]
You can also run the fluxion script by `$ ./fluxion.sh -d`. This happened to me and it is on issue #642

**Comment by igi456** [comment]
same problem !! Need Fixed by devolper this script

**Comment by deltaxflux** [comment]
Check if the chipset support AP mode if not fluxion does not work

**Comment by usama7628674** [comment]
Well the same problem in kernal.It's still not fixed yet.

**Comment by ahmadswift99** [comment]
I thought they have fixed it. How about my scripts output? Is there any incompatible interface or driver?

**Comment by usama7628674** [comment]
@ahmadswift99 You can `dmesg` on terminal after stuck there you'll see bug in red line.

**Comment by popopoio** [comment]
Hey guys, i think i know what’s wrong with it. I’m just using the Realtek 3070L to try finally its working!! Before i was used 8187L for thousand times but it alwasys failure. I dont know but you guys can try with 3070L~

**Comment by strasharo** [comment]
8187L is not compatible with hostapd, that's a known issue. Should work with airbase-ng though.

**Comment by abouelkhoukh** [comment]
#### FLUXION Info
FLUXION V5.9


#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k
**Chipset:** Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


#### XTerm Infos
**Version:** XTerm(337)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'VERSION'
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.18.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-29)) #1 SMP Debian 4.18.10-2kali1 (2018-10-09)

#### Chipset
Chipset: ath9k
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information
HELP PLSSSSSSSSSSSS

**Comment by icnahom** [comment]
Here's a fix:
Make sure you run "airmon-ng check kill" before you run fluxion.

**Comment by frog972** [comment]
I have this problem too how can i fix

**Comment by cjb900** [comment]
@frog972 You do realize that you are posting to a thread that is 2 years old and you haven't given any information on the exact issues you are experiencing or what your set up is. So how is any one going to be able to help you. The original issue is usually due to the chipset in the wifi adapter you are using not supporting AP mode. So to better help please reply with the answer to the below questions
What OS are you using?
Are you running said OS from a VM or on hardware?
What wifi adapter and chipset do you have?

**Comment by frog972** [comment]
> after Extracting the handshake and make Fake AP and Choose language 
> This sentence appears 
> starting captive portal access point service...
> and the computer starts to freeze.... I can not control anything other than re
> ![new](https://user-images.githubusercontent.com/42094275/45332649-21a28b80-b572-11e8-9e10-4a2ef97c968d.png)
> starting it
> how to fix it ? 

V

**Comment by cjb900** [comment]
you haven't answered any of the questions I asked. Am I just supposed to pull out my crystal ball and guess your setup?? Please answer the below questions to better help you. If you can't answer the questions then this tool is not for you and you should go back to learn how to use Linux first. 

What OS are you using?
Are you running said OS from a VM or on hardware?
What wifi adapter and chipset do you have?

**Comment by frog972** [comment]
> @frog972 You do realize that you are posting to a thread that is 2 years old and you haven't given any information on the exact issues you are experiencing or what your set up is. So how is any one going to be able to help you. The original issue is usually due to the chipset in the wifi adapter you are using not supporting AP mode. So to better help please reply with the answer to the below questions
> What OS are you using?
> Are you running said OS from a VM or on hardware?
> What wifi adapter and chipset do you have?
> 

Kali linux 2020.3, dual boot, WB link 802.11N

**Comment by frog972** [comment]
@cjb900 Kali linux 2020.3, dual boot, WB link 802.11N

**Comment by cjb900** [comment]
do you know what chipset is in that adapter? if not run airmon-ng and post the output here

**Comment by frog972** [comment]
@cjb900 ralink technology crop.mt7601u

**Comment by cjb900** [comment]
that adapter bay be part of your issue. Can you run ```iw list | grep "Supported interface modes" -A 8``` and post the full output here. screen shot would be preferred

**Comment by frog972** [comment]
@cjb900 ![IMG_20200825_113014.jpg](https://user-images.githubusercontent.com/61191660/91127655-8d953600-e65b-11ea-8d70-db3f4cdbdc7a.jpg)

**Comment by frog972** [comment]
![IMG_20200825_113014.jpg](https://user-images.githubusercontent.com/61191660/91127901-085e5100-e65c-11ea-8975-8d2128070956.jpg)
  @cjb900

**Comment by cjb900** [comment]
you don't need to post the same thing twice. That adapter/chipset does not support AP mode or VIF so it will not work with fluxion. their may be a driver that can make it work but I don't have an adapter with that chipset so i can't say for sure. If you recently bought that adapter I would return it and try to get one that is actually supported. It need to support monitor mode, Packet injection, AP mode and VIF. below are some adapters/chipsets that are known to work with fluxion

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by frog972** [comment]
@cjb900  thanks for help😊

**Comment by Delayless** [comment]
choose the "airbase-ng" instead of "hotspad"

**Comment by cjb900** [comment]
@Delayless Using airbase-ng over hostapd will not make any difference here if the wifi adapter they are using doesn't even support AP or VIF mode.

**Comment by Delayless** [comment]
> @Delayless Using airbase-ng over hostapd will not make any difference here if the wifi adapter they are using doesn't even support AP or VIF mode.

sure, but for me, it solves my issue. just a way to try.

**Comment by cjb900** [comment]
ok but unless you have a wifi adapter with the exact same chipset and somehow magically got it to support AP and VIF the one this person has is not going to work weather they use airbase-ng or hostapd. it just does not support the modes needed.
