### ISSUE TITLE
cannot access 'language': No such file or directory

### ISSUE THREAD

**Issue by usuarionuevor** [FluxionNetwork/fluxion#621]
- Kali Light 2018.2
- Fluxion 5.6

problem:
![img_20180912_103549210](https://user-images.githubusercontent.com/35457371/45413337-33228b00-b679-11e8-958c-39029c3c51ba.jpg)
can't select any language so its stuck there.

I checked and language folder is there with its 16 .sh language files inside, I downloaded fluxion again just to be sure but same result.

**Comment by the-curi0us** [comment]
Download the git again and do not change the name of the folder when executing the script, just go directly to the directory and from the same execution ./fluxion and avoid doing it (./root/Documents/tu/folder/fluxion.sh) because no will start correctly;)
