### ISSUE TITLE
target? jamming? access point?

### ISSUE THREAD

**Issue by robinex** [FluxionNetwork/fluxion#625]
I have 2 wifi adapter. I want ask what is best performance?

target wlan0
jamming wlan0
ap wlan1

or 

target wlan0
jamming wlan1
ap wlan1

and this is not working on me 
target wlan0
jamming wlan1
ap wlan0

**Comment by the-curi0us** [comment]
This depends, I can generally recommend that you run as Access Point the one with the most DBI, since it will give the victim the best network and the second one for Jamming.

**Comment by zeeshan7860** [comment]
Is it necessary to have two wifi cards for jamming and creating a fake AP???
Can we use one for jamming and AP?

**Comment by zeeshan7860** [comment]
what the fuck strasharo
