### ISSUE TITLE
Flag "-x" broken/nonexistent. 

### ISSUE THREAD

**Issue by Jezza-x3** [FluxionNetwork/fluxion#626]
#### Summary

typing "fluxion -x" returns an error

fluxion -h AND man fluxion has " -x     Try to run fluxion with xterm terminals instead of tmux."

##### What is the current behaviour?

typing "fluxion -x" returns an error

for version 4.10 it is
`FLUXION V4.10: invalid option -- 'x'                                                                                                                                                                                           
Aborted, parameter error detected...
`

for version 5.6 it is 
`FLUXION V5.6: invalid option -- 'x'                                                                                                                                                                                            
Aborted, parameter error detected...
`
#### How to reproduce

just run the command 'fluxion' with the -x flag.

##### What do you think the expected behaviour should be?

Try to run fluxion with xterm terminals instead of tmux.

#### FLUXION Info
FLUXION V4.10

#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlp2s0) Info 
**Device**: phy0
**Driver:** rtl8192ce
**Chipset:** Realtek Semiconductor Co., Ltd. RTL8188CE 802.11b/g/n WiFi Adapter (rev 01)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!
read failed: Network is down
wi_read(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
read failed: Network is down
wi_read(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
read failed: Network is down
wi_read(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down

#### XTerm Infos
**Version:** XTerm(335)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/bin/hostapd

#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.19.0-1-MANJARO (builduser@development) (gcc version 8.2.1 20180831 (GCC)) #1 SMP PREEMPT Thu Sep 20 19:27:32 UTC 2018

Not sure how to find 5.6's diagnostic script. It auto updates from 4.10 to 5.6 when I run it, it doesn't update the diag script though.
#### Expected behavior

 -x     Try to run fluxion with xterm terminals instead of tmux.

**Comment by Jezza-x3** [comment]
PS, my network worked the entire time. I even updated the script from 4.10 to 5.6 and it still showed that.

**Comment by deltaxflux** [comment]
Yeah could be an enhancement
