### ISSUE TITLE
Fake AP create but users not deAuth / only users deAuth but no Fake AP create 

### ISSUE THREAD

**Issue by suhailmurad** [FluxionNetwork/fluxion#627]
hello guys
i am using Fluxsion in Kali Linux with 1 TPLINK adapter Model no is 722N.
i captured handshake and contt going towards but **sometime my adapter create Fake AP and not DeAuth the users**  OR **sometimes its only DeAuth the users and not creating Fake AP**. 😞 
🤔 
**i can not understand which adapter creating Fake AP builtin one or external adapter**
i tried many time please need help. 😞 
if anyone have lecture about Network adapters settings please share.
Thanks

**Comment by deltaxflux** [comment]
Which revision are you using TPLINK 722n vX?

**Comment by suhailmurad** [comment]
> 
> 
> Which revision are you using TPLINK 722n vX?

it was V3.
but yesterday i bought V1 its working perfect.
