### ISSUE TITLE
Add sites to fluxion

### ISSUE THREAD

**Issue by Gabo1203** [FluxionNetwork/fluxion#628]
Good night, I appreciate the help that may give me. I followed this project as interesting for several months. I would like to know how I can add a new site or captive portal. thanks to whom I can help.

**Comment by Gabo1203** [comment]
Muchas gracias por responder curi0us,  soy de Colombia,  Totalplay es el  sitio que deseo agregar a Fluxion.  En el archivo comprimido que compartiste está ese sitio. He entendido que debo copiarlo en la carpeta a sites. 
La duda que aún tengo es que si este mismo sitio funciona en la versión 2 de fluxion, la cual me funciona mejor al momento de capturar el handshake que la versión 5.6. 
Gracias por tu ayuda!

**Comment by the-curi0us** [comment]
No, lamentablemente no funciona ya que el codigo no estaba listo para poder utilizarlo en esa versión.
Mas sin embargo es posible intentarlo copiando en la carpeta temporal de Fluxion

**Comment by Gabo1203** [comment]
Bueno intentaré con la versión 5.6. Gracias por la información.  Y haré la prueba con la carpeta temporal de la versión 2.
Tienes idea de por qué con la versión 5.6 es más demorado capturar el handshake ? 
Y si el handshake obtenido con la suite de aircrack es compatible a la hora de usarlo en fluxion.

**Comment by the-curi0us** [comment]
Si el handshake te tarda no es por la versión de Fluxion sino porque no hay clientes conectado en la red a la que deseas enviar el ataque procura siempre que estén conectados los clientes y fíjate si estas atacando en el canal de transmisión correcto no valla a ser que ataques al canal 6 y el modem este en el 11.

**Comment by the-curi0us** [comment]
Normalmente el cambio de canales es un poco problemático ya que si no te fijas, tu ataque puede que este desconectando a todos de la red víctima por ejemplo en el canal 10 y si el modem automáticamente cambia al canal 6 el ataque estará activo innecesariamente ya que no podrá desconectar a los clientes y recuperaran su red.
Esto pasa debido a que los Módem's de las compañías vienen configuradas que los canales de transmisión sean automáticos por ende si este cambia tu ataque fracasa

**Comment by the-curi0us** [comment]
Recuerda siempre hacer pruebas en tu propia red así podrás ver lo que estas haciendo.

**Comment by Gabo1203** [comment]
curi0us disculpa tanto molestias. Ya el nuevo site me aparece ante la lista de fabricantes. Hasta hay todo bien. Pude capturar el handshake si mucha demora. Ahora el problema es que al momento de crear el portal gemelo, se crea por unos minutos sin permitir la conexión a este, y cerrándose el sistema y dando un mensaje de error. Quiero saber si lo puedo contactar por otro medio y enviarle los errores ya sea telegram o correo. Gracias

**Comment by Gabo1203** [comment]
A la versión 4.10 le puedo agregar el site que le comenté y que compartió usted anteriormente? 
Si tiene el enlace de esta versión me la puede compartir.

**Comment by the-curi0us** [comment]
Si, el enlace es el siguiente https://github.com/FluxionNetwork/fluxion/archive/v4.10.zip

**Comment by Gabo1203** [comment]
./fluxion.sh: línea 82: /root/Descargas
.
5.6/lib/HashUtils.sh: No existe el fichero o el directorio
./fluxion.sh: línea 83: /root/Descargas
.
5.6/lib/HelpUtils.sh: No existe el fichero o el directorio
./fluxion.sh: línea 148: /root/Descargas
.
5.6/preferences/preferences.conf: No existe el fichero o el directorio
chmod: no se puede acceder a '/root/Descargas'$'\n''.'$'\n''5.6/preferences/preferences.conf': No existe el fichero o el directorio
./fluxion.sh: línea 212: /root/Descargas
.
5.6/language/en.sh: No existe el fichero o el directorio
./fluxion.sh: línea 221: /root/Descargas
.
5.6/iptables-rules: No existe el fichero o el directorio
./fluxion.sh: línea 225: format_center_literals: no se encontró la orden
./fluxion.sh: línea 228: format_center_literals: no se encontró la orden
./fluxion.sh: línea 231: format_center_literals: no se encontró la orden
./fluxion.sh: línea 234: format_center_literals: no se encontró la orden
./fluxion.sh: línea 237: format_center_literals: no se encontró la orden
./fluxion.sh: línea 240: format_center_literals: no se encontró la orden









./fluxion.sh: línea 255: format_center_literals: no se encontró la orden

./fluxion.sh: línea 262: format_center_literals: no se encontró la orden

./fluxion.sh: línea 270: installer_utils_check_update: no se encontró la orden

./fluxion.sh: línea 288: installer_utils_check_dependencies: no se encontró la orden
./fluxion.sh: línea 289: installer_utils_run_dependencies: no se encontró la orden

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

the-curi0us, he decidido instalar kalilinux directamente en mi equipo, al ejecutarlo me han hecho falta algunos paquetes, he instalado varios y he ejecutado nuevamente y ahora me aparece asi.

**Comment by the-curi0us** [comment]
Tienes que volver a descargar fluxion 4.10 y borra el anterior cuando lo ejecutes no cambies el nombre y colocalo en la ruta en la cual vayas a ejecutarlo por que si ejecutas el script ponte en el directorio /root/Documentos y luego lo cambias a /root/Descargas este mismo error te dara

**Comment by the-curi0us** [comment]
También fíjate que te situes dentro de la carpeta Fluxion y des ./fluxion.sh y no
./tu/directorio/fluxion.sh
