### ISSUE TITLE
Please support realtek rtl8812au v5.2.20.2 new driver.

### ISSUE THREAD

**Issue by Casper-88** [FluxionNetwork/fluxion#629]
Dear Fluxion,
Can you support this rtl8812au v5.2.20.2 Driver?
https://github.com/gordboy/rtl8812au
apt-get update
apt install realtek-rtl88xxau-dkms
I use v5.6 fluxion in kali linux 2018.3, 
chip ralink RT3070 fake AP can start,
but relatek rtl8812au fake AP cannot start.
I want use rtl8812au because support 5ghz.

**Comment by deltaxflux** [comment]
Yeah, we are not driver or chipset developer.
