### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by akemesakata6** [FluxionNetwork/fluxion#630]
#### Summary

When I create access point,I can't connect access point or load enter password box page.
##### What do you think the expected behaviour should be?

can connect access point and faster connection
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### FLUXION Info
FLUXION V5.6

#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface ([interface]) Info 
**Device:** Unknown
basename: missing operand
Try 'basename --help' for more information.
**Driver:** Unsupported
**Chipset:** 
**Master Modes** Yes
**Injection Test:** ioctl(SIOCGIFINDEX) failed: No such device
Failed

#### XTerm Infos
**Version:** XTerm(335)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.18.0-kali1-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-29)) #1 SMP Debian 4.18.6-1kali1 (2018-09-10)

#### Chipset
Chipset: Driver
brcmsmac
No information if chipset support ap mode
No information if chipset support monitor mode
Don't reseve all required information

**Comment by strasharo** [comment]
Your chipset is not compatible.
