### ISSUE TITLE
Dhcp issue with Realtek rtl8811au

### ISSUE THREAD

**Issue by axware** [FluxionNetwork/fluxion#632]
I'm using rtl8811au as a AP, everything working even DHCP and showing connected devices with ip but no device able to connect for exp:  in mobile " Obtaining ip" in pc "limited connection"

I used another one (g) as a AP and it was working great.

**Comment by deltaxflux** [comment]
I'm not familiar with every chipset.  Some basics: install sure driver is properly installed and the driver is loaded in the kernel

**Comment by axware** [comment]
I fixed it by changing kernel, now I've another issue fake AP won't stop after turning off victim's AP , 
I suppose (target tracking) are responsible for this function so i use a separated wlan for it,
it just changing channels if the AP restarted.
