### ISSUE TITLE
dependencies not installing

### ISSUE THREAD

**Issue by jitu3232** [FluxionNetwork/fluxion#634]
few dependency are missing and fluxion.sh -i could not install them. and apt-get also didnt find the bc.
how to install them. i have just installed kali and clonned fluxion

**Comment by jitu3232** [comment]
problem was with kali source file list.
solved

**Comment by Geralt-of-Livia** [comment]
>           problem was with kali source file list.
> solved
Could you tell me how did you solve the problem?
