### ISSUE TITLE
Rogue AP unstable, DHCP issue, Router Password Page loading delay.

### ISSUE THREAD

**Issue by gudangboys** [FluxionNetwork/fluxion#637]
Hi,
First of all thanks again for your wonderful effort!

1. A simulated attack on my own router brought up the following issues;

a. The Rogue AP keeps disappearing and reappearing on the available networks list.

b. When the victim tries to connect to the Rogue AP when it appears, stuck in "Obtaining IP" step (In Fluxion it shows that DHCP offer has been made with IP address.

c. After repeated attempts when victim is finally able to connect to the Rogue AP, the Router Login page takes a while to load.

d. Tried and tested on multiple devices with same results as above.

2. Kindly help address above issues.

Thanks lots!

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by deltaxflux** [comment]
Can you please check if #642. I want to know if you have the same problem.

**Comment by gudangboys** [comment]
Thanks for your mail, no my issue is not the same as #642
Thanks

**Comment by deltaxflux** [comment]
Can you provide a small screen recording or the debug output log using `fluxion -d `

**Comment by deltaxflux** [comment]
No response. Closing.
