### ISSUE TITLE
Usb Adapter Recommendation

### ISSUE THREAD

**Issue by ttoa** [FluxionNetwork/fluxion#638]
Hi, my adapter: Alfa Awus036h
Antenna: Alfa AGA-2424T 24 dBi Grid
Awus036h+Aga-2424t Long distance performance is fine.
Awus036h this adapter is old for fluxion.
I'm looking for an adapter that will do a long distance performance with this antenna.
I stayed between 3 adapters for fluxion
AWUS036NH
AWUS036NHA
AWUS036ACH
I thought about taking Nha.But Ach and Nh made me think.

NH:33 Dbi.Normal chiptset.Good packet and penetration testing.
NHA:20 Dbi.Great chipset.Very good packet injection and penetration testing.
ACH:New adapter.12 Dbi (Maybe 18 ?) I don't know the chipset status exactly.But I heard it was problematic.I don't know about Fluxion performance.But the future is bright (?)

I know these.
Long distance,Fluxion.,So what should I choose?
I'd like to hear your ideas if you're using an external antenna like me.

Please help :)

**Comment by strasharo** [comment]
036h is not compatible with hostapd.  AWUS036NHA has the most suitable chipset for fluxion.

**Comment by ttoa** [comment]
Thank you :)

**Comment by neovergen** [comment]
Hi! Due to the fact that airmon-ng has some issues with awus036ach adapter,

After manually doing monitor mode of awus036ach, how do you continue using fluxion? Can anyone help me? Thanks
