### ISSUE TITLE
Hostapd Compatible USB Adapters (2018)

### ISSUE THREAD

**Issue by hasanalizxc** [FluxionNetwork/fluxion#639]
Dear FluxionNetwork and Github Members,

I read this issue (https://github.com/FluxionNetwork/fluxion/issues/212) and they are saying alfa awus036h is NOT compatible with hostapd. I have awus036H and when i try to create an evil twin, it stucks.

Is there any solution fix this? If there is not a solution for this, could you please tell me what is the compatible USB WI-FI adapters with hostapd? I searched on the internet but i couldn't find any new information. They have old models.

Please share your opinions.

**Comment by strasharo** [comment]
awus036nha
