### ISSUE TITLE
E: Unable to locate package bc

### ISSUE THREAD

**Issue by sue35205** [FluxionNetwork/fluxion#640]
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by sue35205** [comment]
Upon running "./fluxion.sh -i" it fails to instal missing elements and report the following:
Nothing to check.
Adding missing sources to package manager, please wait.
Adding keys.gnupg.net key, please wait.
Adding pgp.mit.edu key, please wait.
ERROR: Failed to fetch or add the source key!

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bc

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

**Comment by deltaxflux** [comment]
You mess up your dependencies. Please check the source.lst.
