### ISSUE TITLE
Can't open /tmp/fluxspace/dhcpd.conf: Permission denied

### ISSUE THREAD

**Issue by jaspervanbrian** [FluxionNetwork/fluxion#642]
#### Summary
Hi! Thanks for making this project.
Unfortunately, when I launch an "evil twin" attack, I get an error on FLUXION AP DHCP Service xterm, saying "Can't open /tmp/fluxspace/dhcpd.conf: Permission denied". Tried to chmoding the file while its running, no luck. Thus, it launches a rogue ap that don't give an IP address, and stuck on "Obtaining IP address" on a device.

OS: Ubuntu 18.04

##### What is the current behaviour?
"Can't open /tmp/fluxspace/dhcpd.conf: Permission denied" on DHCP Service

#### How to reproduce
I launched my fluxion on debug mode to see this error because if not on debug, XTerm will suddenly close in a split second after the captive attack is launched, thus you will not know the error.

`$ sudo ./fluxion.sh -d`

I'm on Ubuntu 18.04

##### If the current behaviour is a bug, please provide the steps to reproduce it.
![image](https://user-images.githubusercontent.com/24638813/47199437-3ad5fd80-d3a4-11e8-80e5-952d9a172533.png)

##### What do you think the expected behaviour should be?
Smoothly execute the attack

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by deltaxflux** [comment]
Thanks for reporting. It look like that  /tmp/fluxspace/dhcpd.conf doesn't exist. If I could reproduce this this is a critical bug.

I assign this.

Regards,
deltax

**Comment by jaspervanbrian** [comment]
Actually, it does exist. I checked it all the time I executed "evil twin" attack. Been chmodding it in the source file `attack.sh` but no luck.

**Comment by deltaxflux** [comment]
Could someone confirm that the dhcpd file exists while executing. Using ls /tmp/fluxspace after launching the AP

**Comment by jaspervanbrian** [comment]
Okay, forgot to tell you that I tested the "evil twin" attack on Kali Linux 2018.2. Knowing that our default user in Kali is `root`, I guess the problem happening in Ubuntu is permission levels.

Also btw, when I tested this on Kali, the DHCP works but the fake AP created doesn't let you input a password, so you can distinguish the original from the fake.

**Comment by deltaxflux** [comment]
I'm not into ubuntu. I don't use it and I don't want to use it. If it works on kali use kali.
