### ISSUE TITLE
Can't capture handshakes/deauth works but no handshake after latest upgrade

### ISSUE THREAD

**Issue by shahidakhter786** [FluxionNetwork/fluxion#645]
Everything was working fine since latest upgrade in kali.deauth is working ,handshake is not captured by fluxion.i tried every way.Fern wifi cracker is capturing handshakes but fluxion is taking time and time and long time,clients are deauthenticating and connecting again but nothing.

**Comment by deltaxflux** [comment]
I will try to increase the mdk3 / mdk4 jamming interval.

**Comment by shahidakhter786** [comment]
thank you so much.your efforts are so thankful.
