### ISSUE TITLE
Scapy version conflcts with pyrit:unable to force clients deauthentication on router

### ISSUE THREAD

**Issue by shahidakhter786** [FluxionNetwork/fluxion#647]
here's dignostics.sh results: issue with AP
Injection is working!

#### XTerm Infos
**Version:** XTerm(337)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'VERSION'
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.18.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-29)) #1 SMP Debian 4.18.10-2kali1 (2018-10-09)

#### Chipset
Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by deltaxflux** [comment]
Yeah install an older scapy version using **pip**:
`pip install scapy=2.3.2`
