### ISSUE TITLE
AWUS036ACH compatible

### ISSUE THREAD

**Issue by neovergen** [FluxionNetwork/fluxion#648]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | yes

#### Summary

Suggesting if we can modify script of fluxion tool to use AWUS036ACH adapter. Thanks

**Comment by deltaxflux** [comment]
No, this is the task for driver developers. Fluxion has nothing todo with this.
