### ISSUE TITLE
dhcpd changed to udhcpd

### ISSUE THREAD

**Issue by KatieKate1088** [FluxionNetwork/fluxion#65]
Simple thing, in the most recent upgrade for Kali, apt-get forces install of udhcpd and will not allow install of dhcpd, Any suggestion for bypass  or...

**Comment by MPX4132** [comment]
I'll check it out, I'm upgrading now.

**Comment by KatieKate1088** [comment]
okay let me know what you find out

**Comment by MPX4132** [comment]
Sorry for the delay, I forgot I hadn't upgraded from stock Kali after I reinstalled it a couple of days ago, so it took a while. I'm on kali rolling, fully upgraded and dhcpd is still there. Are you, by any chance, using busybox?

**Comment by KatieKate1088** [comment]
Totally fine and no, just Kali on Rolling, are your sources.list 
InRelease
Main amd64 Packages
nnon-free amd64 packages
contrib amd64 packages

**Comment by MPX4132** [comment]
Well, you've got an extra repo, "InRelease," that's not shipped by default with Kali.

I've got: kali-rolling main non-free contrib

**Comment by strasharo** [comment]
Install isc-dhcp-server instead of using dhcpd.
