### ISSUE TITLE
Fluxion 5.6 Error 

### ISSUE THREAD

**Issue by popadrop** [FluxionNetwork/fluxion#651]
Error message stuck at pick your language ??

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by popadrop** [comment]
ls: cannot access 'language': No such file or directory
head: cannot open 'language/*.sh' for reading: No such file or directory

**Comment by popadrop** [comment]
/root/fluxion-master/scripts/diagnostics.sh: line 12: ../lib/InterfaceUtils.sh: No such file or directory
/root/fluxion-master/scripts/diagnostics.sh: line 13: ../lib/ChipsetUtils.sh: No such file or directory
Usage ./scripts/diagnostics [wireless_interface]

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/issues/621
