### ISSUE TITLE
Cannot Start Captive Portal Attack

### ISSUE THREAD

**Issue by stevanuscolonne** [FluxionNetwork/fluxion#654]
#### Summary
Cannot Start Captive Portal Attack with internal wifi card (atheros)

##### What is the current behaviour?
fluxion stuck

##### If the current behaviour is a bug, please provide the steps to reproduce it.
![screenshot from 2018-11-03 01-39-06](https://user-images.githubusercontent.com/24591481/47947151-c8d7e980-df49-11e8-8b5a-b0c142f722da.png)

![screenshot from 2018-11-03 01-39-38](https://user-images.githubusercontent.com/24591481/47947160-f329a700-df49-11e8-8403-b2de9e3bbd89.png)

Was it kernel related problem?

##### What do you think the expected behaviour should be?
fluxion able to start captive portal attack with internal wifi card (atheros)

##### Specs
Forgot to do, i used kali 2018.3a and already reinstalled with kali 2018.1 which working with internal wifi card

**Comment by strasharo** [comment]
There's a kernel bug with your wireless driver.

**Comment by chunkingz** [comment]
@stevanuscolonne Please I have this same issue where fluxion gets stuck at "starting captive portal access point service" have you been able to solve this problem?? #

also what command did you use on the second tab in your terminal to reproduce that debugging effect, I need it to know what I am actually facing.

**Comment by rad4day** [comment]
@chunkingz looks like `dmesg` to me

**Comment by zabuza99** [comment]
I also had the same problem, although I installed the latest version of Fluxion @deltaxflux
