### ISSUE TITLE
missing dependencies 

### ISSUE THREAD

**Issue by anto1889** [FluxionNetwork/fluxion#655]
ciao ragazzi,
after cloned and opened fluxion.sh, it doesn't load this:
            [*] aircrack-ng...................................... OK.           
            [*] bc.......................................... **Missing!**           
            [*] awk.............................................. OK.           
            [*] curl............................................. OK.           
            [*] cowpatty......................................... OK.           
            [*] dhcpd....................................... **Missing!**           
            [*] 7zr.............................................. OK.           
            [*] hostapd..................................... **Missing!**           
            [*] lighttpd.................................... **Missing!**           
            [*] iwconfig......................................... OK.           
            [*] macchanger....................................... OK.           
            [*] mdk3............................................. OK.           
            [*] nmap............................................. OK.           
            [*] openssl.......................................... OK.           
            [*] php-cgi..................................... **Missing!**           
            [*] pyrit............................................ OK.           
            [*] xterm............................................ OK.           
            [*] rfkill........................................... OK.           
            [*] unzip............................................ OK.           
            [*] route............................................ OK.           
            [*] fuser............................................ OK.           
            [*] killall.......................................... OK.    

and then said that "**no internet connection found**".  I'm connected with tablet's hotspot
use last Kali linux and last fluxion
grazie

**Comment by vlldk** [comment]
You need to run fluxion.sh -i to install dependencies first

**Comment by deltaxflux** [comment]
Can you ping the google dns : `ping 8.8.8.8`?
Please use the latest version of fluxion.
