### ISSUE TITLE
Fake site does not appear in victim's device

### ISSUE THREAD

**Issue by sersajar** [FluxionNetwork/fluxion#662]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

My problem is that the fake site does not appear in the victim device.
The fake AP appears, and I can connect to it, BUT no fake site appears at all. I cannot use the internet in the device, so it is good.
What is the problem here??

#### Specs

![captura de pantalla de 2018-11-10 10-23-22](https://user-images.githubusercontent.com/16085139/48300063-fcc98680-e4d6-11e8-91e2-d333233518ed.png)

**Comment by vampireactual** [comment]
Are you running it as the sudo or root user?

**Comment by chemonicek** [comment]
same problem for me... i start fluxion with sudo :(

**Comment by deltaxflux** [comment]
Edit: I remove the picture because it contain sensitive data.
