### ISSUE TITLE
Not enough information: "dev" argument is required. 

### ISSUE THREAD

**Issue by emaragkos** [FluxionNetwork/fluxion#663]
#### Summary
I tried to make a custom theme for the fake AP page but when I select it to use it I get an error.

##### What is the current behaviour?
I get the error "Not enough information: "dev" argument is required."

#### How to reproduce
Use theme OTE.portal while creating a fake AP page (fluxion/attacks/Captive Portal/sites/OTE.portal)
Here is my fork
https://github.com/emaragkos/fluxion

Nothing special was added to the theme. I just cloned my Modems login page with httrack and added a few modifications based on a working theme (TP-LINK_en.portal) that was tested and was working fine.
Also added the .portal extension to the folder.

**Comment by azamet90** [comment]
if i exit and enter the program again it is fixed on me

**Comment by emaragkos** [comment]
Still no luck :/
https://www.youtube.com/watch?v=uZs_2C7Px_o

**Comment by deltaxflux** [comment]
Thanks for reporting!

**Comment by deltaxflux** [comment]
Could you please execute the script using the debug flag `./fluxion -d`

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/wiki/Preparing-portals-for-fluxion
