### ISSUE TITLE
Please try install in kali linux 2018.4

### ISSUE THREAD

**Issue by Casper-88** [FluxionNetwork/fluxion#667]
Dear fluxion,
Can you let me know fluxion support what wifi chipset  5Ghz?
I try Realtek RTL8812AU still have problem,
You can try install kali linux 2018.4, after then install below driver.
apt-get update
apt install realtek-rtl88xxau-dkms
rtl8812 driver v5.20.2
AP will not start.
Who people can let me know how to solve this problem?

**Comment by NiXoN999** [comment]
Hi, Casper! I have exactly the same problem and can't solve it for several days...If you create AP by hostapd,  I think the problem comes because macchanger can't change mac on virtual interface. I assume this driver problem(((

**Comment by deafgaminghd** [comment]
same!

**Comment by NiXoN999** [comment]
Guys!!!

[https://github.com/FluxionNetwork/fluxion/issues/212#issuecomment-338018996](url)
