### ISSUE TITLE
Captive Portal : Phishing Page

### ISSUE THREAD

**Issue by BinJeremy** [FluxionNetwork/fluxion#668]
I use fluxion ver 5.6 , after Captive Portal attack , I use device1 Android use wifi phishing , it show " Tap here to sign in network " , but it error 
++ The webpage at http://connectivitycheck.gstatic.com/generate_204 could not be loaded because:

net::ERR_NAME_NOT_RESOLVED

---- I use device2 Samsung use WIFI Fake , it not show " Sign in Network " , but using 192.168.254.1 it working ! How ? 

How to fix it ? I use two card TL-WN722N V1 to fluxion .

**Comment by deltaxflux** [comment]
Newer android versions check the internet connection before. Looks like this is not working in newer android and ios version. 

 We could implement a bypass but this could be an enhancement.
