### ISSUE TITLE
Aborted, X (graphical) session unavailable.

### ISSUE THREAD

**Issue by littleheary** [FluxionNetwork/fluxion#669]
i run it in parrot。but the error is Aborted, X (graphical) session unavailable.
how can i do。

**Comment by strasharo** [comment]
As the exception says, run it inside a graphical session.

**Comment by 911didbush420** [comment]
how do you run it inside a grafical session. and i have this in the lazy script and it wont work on there

**Comment by ainur-rahman74** [comment]
Aborted, X (graphical) session unavailable.

**Comment by DarkGlistorm** [comment]
Aborted, X (graphical) session unavailable.

**Comment by Summit-Teoh** [comment]
Does that mean you can't call fluxion from within an SSH session？
