### ISSUE TITLE
Network Connection Failing

### ISSUE THREAD

**Issue by dancrow565** [FluxionNetwork/fluxion#672]
When i do a Handshake Snopper, (or whatever it's called), and I choose my network card (wlan0) it automatically disconnects me from my network and kali gives me an error message saying "Activation of network connection failed", and then I am unable to scan. I dont know if it is a bug or not, and I dont know how to reproduce it

**Comment by deltaxflux** [comment]
Looks like your wireless card is not supported or you have driver problems.

**Comment by Philipp0205** [comment]
Bump, got the same error. Any help?
