### ISSUE TITLE
Unable to connect to fake network

### ISSUE THREAD

**Issue by Dontmindmes** [FluxionNetwork/fluxion#673]
/scripts/diagnostics.sh wlan0
#### FLUXION Info
FLUXION V5.6
 
 
#### BASH Info
GNU bash, version 4.4.23(1)-release (i686-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash
 
 
#### Interface (wlan0) Info
**Device**: phy0
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!
 
 
#### XTerm Infos
**Version:** XTerm(337)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!
 
 
#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd
 
 
#### Aircrack-ng Info
EXIT
  (null) - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org
 
 
#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.
 
#### System Info
**Chipset:** Linux version 4.18.0-kali2-686-pae (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-29)) #1 SMP Debian 4.18.10-2kali1 (2018-10-09)
 
#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

Pictures:  https://cdn.discordapp.com/attachments/424638379800657922/516329277810016294/Screenshot_20181125-110807_Settings.jpg

**Comment by deltaxflux** [comment]
Closing due inactivity

**Comment by vanserna** [comment]
How can we check the dhcp?
