### ISSUE TITLE
Network is down

### ISSUE THREAD

**Issue by wardinh0** [FluxionNetwork/fluxion#676]
The attack stops at the Captive Portal step, I setup everything right, have the handshake, there ARE clients online and the network is UP and running, but in the jamming window it says that the network is down, and in the airodump-ng window shows 0 clients, when I actually have about 5 people connected. Not using the tracker option, just the jamming & fake AP with the same wireless card, it does support monitor mode

Do someone know what could be causing this? It used to work in older versions

**Comment by Leixiaodong** [comment]
Has it been resolved？i met it

**Comment by cjb900** [comment]
@Leixiaodong this was closed 6 years ago. If you are having a similar issue open a new issue and provide all the information required in the issue template.
