### ISSUE TITLE
Can we have fluxion available on Openwrt ?

### ISSUE THREAD

**Issue by itsStar** [FluxionNetwork/fluxion#677]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Can we have fluxion available on [OpenWrt](https://openwrt.org/) ?
It would be handy on a portable router like [MR3040](https://wiki.openwrt.org/toh/tp-link/tl-mr3040) with battery support to deploy an attack on remote location where we don't want to be noticed with a laptop.
As it have the ability to install the dependencies and can be configured via nice LUCI frontend.
The frontend can be created on Web page and admin page can be accessed via special link on mobile phone.
Please share your thoughts on this idea.
Thanks

**Comment by rad4day** [comment]
No.

**Comment by strasharo** [comment]
Just use a Raspberry instead.

**Comment by deltaxflux** [comment]
I think there is to much overhead and its not worth it.

**Comment by deltaxflux** [comment]
Fluxion is in general very huge. Most routers don't have more than 10mb space left.

**Comment by itsStar** [comment]
Actually there is an overlay option which enable openwrt to use USB drive to root from.
And i have attached 2GB Flash drive and have lots of spare room on MR3040 :)
