### ISSUE TITLE
Tuto or short guide to  add new Custom Portal Interfaces manualy ?

### ISSUE THREAD

**Issue by overlife6** [FluxionNetwork/fluxion#680]
Hey,

Question in the title :)
Can't access Custom Portal Interfaces page on wiki and i'm intersted in.
I half inderstand what need portals to work (communicate) with Fluxion, but not files it really need and how to add them to fluxion "web interface" menu before attack.

Best regards

**Comment by strasharo** [comment]
Pick any of these as a sample and adapt it to your needs:
https://github.com/FluxionNetwork/fluxion/tree/master/attacks/Captive%20Portal/sites
