### ISSUE TITLE
Captive portal

### ISSUE THREAD

**Issue by nicolas4d** [FluxionNetwork/fluxion#683]
Starting Captive Portal access point service...  
And nothing 
Help me 
Why ?

**Comment by LePrinz** [comment]
which wifi adapter you're using? Atheros or Realtek ?
ive heard that realtek cannot be used for these attacks, and up to 2018.2 atheros won't neither.. 
Im using 2018.4 with realtek adapter (TPW722N v2) and can't get thought captive portal either.. same problem

**Comment by LePrinz** [comment]
Try to not use Hostapd if you got Realtek wifi adapter. I used the second one here
[1] Rogue AP - hostapd (recommended)
[2] Rogue AP - airbase-ng (slow)
and it seems worked but then this happen..
[https://imgur.com/a/wZoyTRU](url)
is this a bug?

**Comment by HALofBorg** [comment]
@LePrinz https://www.tp-link.com/us/products/details/cat-5519_TL-WDN4800.html with x(3) https://hawkingtech.com/product/hai15sc/ with Kali2019.1 Mate (full installation) on a SanDiskExtreme3.1USB drive seems ok, if it's any help. The card has the power of the mainboard PCIe slot, and works in monitor mode. This , of course, is a tower, not laptop.

**Comment by LePrinz** [comment]
@HALofBorg thanks for the fast reply. my idea was to buy one of these alpha adapters
https://www.amazon.de/gp/product/B01D064VMS
https://www.amazon.fr/ALFA-Network-AWUS036NHA-Adaptateur-connecteur/dp/B004Y6MIXS
they should work fine, is there a difference between? (which one better)

**Comment by strasharo** [comment]
AWUS036NHA should be fine, it has an Atheros chipset, which is compatible.

**Comment by Barty89** [comment]
This is the issuie I’m having
