### ISSUE TITLE
Fluxion exits if password entered is correct or not.

### ISSUE THREAD

**Issue by PoSHMagiC0de** [FluxionNetwork/fluxion#684]
#### Summary
Fluxion Portal Capture exits if correct password is inserted or not.

##### What is the current behaviour?
Fluxion quits Capture Portal attack if current password is correct or not.  Used to only stop attack if correct password matches hash or you manually tell it to.

#### How to reproduce
Run Fluxion against a test AP with handshake and put in wrong password on capture portal.

##### If the current behaviour is a bug, please provide the steps to reproduce it.
Simply running the app as intended.  I did not use an SSL and skipped target tracking.

##### What do you think the expected behaviour should be?
Before in the past the attack will continue if the correct password is not inserted on the Capture Portal.

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V5.6

#### BASH Info 
GNU bash, version 4.4.23(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan1) Info 
**Device**: phy1
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(341)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.18.0-kali3-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-30)) #1 SMP Debian 4.18.20-2kali2 (2018-11-30)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by omgwtfwow** [comment]
Been troubleshooting this same issue. Tried installing previous versions of Fluxion but didn't work. Passwords entered are logged, but Fluxion closes whether they are correct or not.

**Comment by strasharo** [comment]
Fixed in https://github.com/FluxionNetwork/fluxion/commit/f116e5481cf6b28805abc0688d451498e58bd7c3

**Comment by PoSHMagiC0de** [comment]
Awesome.  I will give it a try.  I been toiling over the script.  You might
want to look at aircrack-ng -l option.  It allows you to save a cracked
password to a file.  Another side affect is if the password is not cracked,
no file is created.  You could use this to do a file check for a cracked
password or not and the file will contain just that password.  Just a
thought.
