### ISSUE TITLE
missing dependencies can't be installed

### ISSUE THREAD

**Issue by Geralt-of-Livia** [FluxionNetwork/fluxion#686]
#### Summary

I clone github to my computer in kali linux 2018.2
and ./fluxion -I doesn't work:
Dependency installation failed!
Press enter to retry, ctrl+c to exit...
few dependency are missing and fluxion.sh -i could not install them. and apt-get also didnt find the bc.
how to install them. i have just installed kali and clonned fluxion

**Comment by strasharo** [comment]
Install the missing dependencies manually.
