### ISSUE TITLE
Errore, file hash non valido! 

### ISSUE THREAD

**Issue by nun97** [FluxionNetwork/fluxion#687]
Ciao! 
Qualcuno può dirmi cosa devo fare quando lo script chiede il percorso del file handshake?

Grazie.

**Comment by xxsv3n** [comment]
Devi prima recuperare l'handshake usando "Handshake Snooper". Una volta che hai l'handshake per la rete specifica, il tuo errore dovrebbe scomparire.

**Comment by deltaxflux** [comment]
Please write a **full** issue request on English.

**Comment by xxsv3n** [comment]
I was just replying to his question. He asked what do you do when it asks for path to handshake file. So I'm assuming he never sniffed for the handshake to begin with &  told him as much.
