### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by usama7628674** [FluxionNetwork/fluxion#69]
Can anyone please add router login page that asks for a username and password when you open default gateway like neutral one in the following Image so one can grab router credentials.

![router page](https://user-images.githubusercontent.com/29252277/29241824-0f15934e-7f9b-11e7-8361-8ed6d4b2f922.PNG)

**Comment by deltaxflux** [comment]
Doesn't fit well here. Since was introduced to steal wireless passwords not webpage credentials
