### ISSUE TITLE
what is 7zr package ?

### ISSUE THREAD

**Issue by ZeroizeHD** [FluxionNetwork/fluxion#691]
I Want excute fluxion 

it's problem

Fluxion dpendency 7zr problem

i try search google 7zr

resolution is dnf install p7zip

i try install p7zip but not solved

what should I do?

plz help me ㅠㅠ

i use fedora os

**Comment by ZeroizeHD** [comment]
I Solved this issues
i create new link
ln -s /usr/bin/7z /usr/bin/7zr
thanks

**Comment by ZeroizeHD** [comment]
I Solved this issues
i create new link
ln -s /usr/bin/7z /usr/bin/7zr
thanks

**Comment by BedoM** [comment]
do you find mdk4 ?

**Comment by hossam20520** [comment]
@BedoM 
$ git clone https://github.com/aircrack-ng/mdk4.git
$ cd mdk4
$ make
$ sudo make install
done

**Comment by hossam20520** [comment]
@ZeroizeHD 
$ ln -s /usr/bin/7z /usr/bin/7zr    #not working in fedora 31 
but i this worked for me 
$ sudo ln -s /usr/bin/7za  /usr/bin/7zr    #fedora 31
