### ISSUE TITLE
Would a EAP GTC ... Downgrade useful ?

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#694]
Look
https://github.com/sensepost/mana/issues/104
I think
It would be use to get rid of the captive portal and hsts  / DNS headache !!

**Comment by strasharo** [comment]
Irrelevant.

**Comment by strasharo** [comment]
You have the source, feel free to set whatever you want.

**Comment by minanagehsalalma** [comment]
if i could i would .. but i opened this issue cause i can't..

**Comment by minanagehsalalma** [comment]
@strasharo i have found this [script ](https://github.com/Tylous/SniffAir) that

[+] Evil Twin - Creates a Fake Access Point, Clients Connect to Divulging MSCHAP Hashes or Cleartext Passwords

i hope you add the feautre
