### ISSUE TITLE
"AP Authenticator" window not closing when switching channel (POSSIBLE CRASH)

### ISSUE THREAD

**Issue by usuarionuevor** [FluxionNetwork/fluxion#695]
When AP switches channel Fluxion does accordingly except the "AP Authenticator" window doesn't close and keep it opened with the old channel, so if it switch channel 5 times, there will be 5 "AP Authenticator" windows opened at the same time.

I'm not 100% sure this is the cause, but I usually get CRASH after a while (after several channel switches) with "no client found" error (client IS there).
When the crash happens the options "select another attack" or "exit" doesn't work, need force close and re-start the whole thing.

**Comment by strasharo** [comment]
The authenticator window is made to persist in case you get a valid password, which is displayed in there.

**Comment by usuarionuevor** [comment]
Does it really need so many authenticator window opened at the same time? I'm talking about DOZENS depending on how many times AP changes the channel.
Is there any debug option to track the reason of the crashes?
