### ISSUE TITLE
have two wifi

### ISSUE THREAD

**Issue by lgf01010** [FluxionNetwork/fluxion#696]
hi，When I successfully configure it sequentially, there are two wireless APS with the same name, one needs a password and the other does not need a password.
![image](https://user-images.githubusercontent.com/41816999/53471719-91fd8480-3aa0-11e9-860e-7c24112812fe.png)

**Comment by strasharo** [comment]
![image](https://user-images.githubusercontent.com/3337997/53527160-dfa0de00-3aee-11e9-8b27-f3505a2d1807.png)
