### ISSUE TITLE
Suggestion to Bypass HSTS!!

### ISSUE THREAD

**Issue by jeegarjani** [FluxionNetwork/fluxion#697]
Can u automate ssl2strip, dns2proxy or evilginx in the update so it can bypass HSTS warning while trying connection request in fake dns. I am not a coder but understand where the problem lies...See if u can work out...

**Comment by rad4day** [comment]
You can't bypass HSTS this way. The browser already knows that the site should be served via HTTPS only at the point it shows this warning. This would only help with sites not using hsts and sites the user visits for the first time.

If you want more information about how HSTS works I'd suggest reading the [RFC 6797](https://tools.ietf.org/html/rfc6797)

**Comment by jeegarjani** [comment]
Then for request sending in Fake dns instead of connection request to
Google.com or WhatsApp or other such which use HSTS we can manipulate the
script to request connection for tempmail.com and other such sites which
doesn't use HSTS so the question of warning message doesn't arrive.

**Comment by jeegarjani** [comment]
Sophorn the developer of wifiphisher had mentioned in one of his comments
there are various tricks like using evilginx along with wifiphisher to
bypass HSTS similarly if we integrate same automation within the tool it
can work..is what I think..

There is wifi pumpkin tool also which bypasses HSTS sites.

**Comment by jeegarjani** [comment]
Sslstrip 2 and dns2proxy usage

https://youtu.be/9RPCSVcCv1w
