### ISSUE TITLE
Add PMKID Attacks

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [FluxionNetwork/fluxion#702]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary
I think PMKID attacks would be much faster and easier than handshake capturing.
https://hashcat.net/forum/thread-7717.html

No need for Clients for the first step. Verification is easy as well.

Greetings

**Comment by deltaxflux** [comment]
Good idea. Maybe an enhancement for the handshake snooper method.

**Comment by waidoshoruda** [comment]
Great enhancement.
Today I just checked this project to request this feature.

**Comment by RadhaKrishn4** [comment]
> ### Feature Request
> Q 	A
> New Feature 	yes
> #### Summary
> 
> I think PMKID attacks would be much faster and easier than handshake capturing.
> https://hashcat.net/forum/thread-7717.html
> 
> No need for Clients for the first step. Verification is easy as well.
> 
> Greetings

i also wanted to request this feature! thanx!

**Comment by adrastee** [comment]
PMKID is not available on all routers. handshake yes.

**Comment by deltaxflux** [comment]
@adrastee yeah, because this only works with networks, with roaming functions, enabled. Since aircrack-ng enable this function, this should work.
