### ISSUE TITLE
packets contained no eapol data unable to process this ap 

### ISSUE THREAD

**Issue by Jikhael** [FluxionNetwork/fluxion#706]
So i update to lastest version on fluxion but when the target put his password (or random words) the Fake AP always accept it whenever thats the right password or not and in my computer suddenly there s a word “packets contained no eapol data unable to process this ap” and my fluxion suddenly force exit, there s no word like its a success or a fail, anyone know the solution? And i use tp link 722 v1 its support injection and monitor mode, thx

**Comment by strasharo** [comment]
Looks like there's some issue with the handshake:
https://github.com/aircrack-ng/aircrack-ng/issues/1983#issuecomment-437729085

What distribution are you using?

**Comment by strasharo** [comment]
No response within a week.

**Comment by abdulsami822** [comment]
Same problem with me please help me
