### ISSUE TITLE
Bug on the Fake AP

### ISSUE THREAD

**Issue by theone143** [FluxionNetwork/fluxion#707]
### Bug Report
The Fake Ap is deauthenticating the clients instead of connecting on it.
#### Summary
When I was testing the newer version of fluxion I notice some changes, that on the new version it has a bug on it.
##### For more information
I provide a video on it
https://www.youtube.com/watch?v=9Eh09_yOxu0
Skip it on 5:51

**Comment by leosun620** [comment]
in older version fluxion , can you success? only using one network interface card, the fake AP can be work properly and the original AP can't be connected because of deauthenticating.
