### ISSUE TITLE
A windows based attack !

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#708]
https://null-byte.wonderhowto.com/how-to/android-for-hackers-exfiltrate-wpa2-wi-fi-passwords-using-android-powershell-0192242/

Just like what is in the tutorial ... But we will our local server in rouge ap to receive the passwords ...

**Comment by deltaxflux** [comment]
This is not relevant for fluxion.

**Comment by minanagehsalalma** [comment]
@deltaxflux 

> This is not relevant for fluxion.

this all about  fluxion

just remove the Ngrok part ... and all what's left is a rogue ap with php server and fake page that asks for the password by downloading/auto downloading the powershell or  the good designed exe file  only when a windows device is detected ... 

how else you can send the wifi passwords to the local  php server without using Ngrok/making it public....
the answer is using a rogue ap.

like 

1- we start the rouge AP+ the local  php server
2- the a device connects to  the  rouge AP after he's being disconnected from his ap
3- we detect that is a windows device using user agent .etc
4- the  captive portal page that shows up asks the user to download the wifi password
5- after he opens the file and the passwords are sent . we show him the password in text file (optional )
6-  done

**Comment by minanagehsalalma** [comment]
@strasharo ... But this isn't an payload ... This an harmless powre shell that won't be detected from the antivirus ..
And the #713 dude's idea isn't bad.. But you need root to access the WiFi password on android.... Keylogging would solve the problem .

**Comment by strasharo** [comment]
What part of not relevant you didn't understand?

**Comment by minanagehsalalma** [comment]
@strasharo ..
The part where fluxion have the very same Requirements to do the attack 
In an excellent way .
1- DNS redirecting 
2- captive portal 
3- the ability to detect the user agent 
4- the death attack till they download the file and open it .
