### ISSUE TITLE
when Captive Portal attack，the fake AP work well ,but the real AP still can be connected. 

### ISSUE THREAD

**Issue by leosun620** [FluxionNetwork/fluxion#709]
### Bug Report
yes
#### Summary
after Handshake Snooper Acquires WPA/WPA2 encryption hashes，i begin to Captive Portal。The fake AP work well , my phone can connect it and need input password。but i find that the real AP can still be used and it doesnt be attacked(DDos). the window "FLUXION AP Jammer Service" keep still,showing "Periodically re-reading Blacklist/whitelist every 3 seconds".
i am very sad, i cost all my day on it. Hope you can help me. Thank you very much.

#### How to reproduce
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select a wireless attack for the access point

                      ESSID: "sun2402" / WPA2                                   
                    Channel:  2                                                 
                      BSSID:  34:CE:00:45:21:64 ([N/A])                   

	[1] Captive Portal Creates an "evil twin" access point.
	[2] Handshake Snooper Acquires WPA/WPA2 encryption hashes.
	[3] Back 

[fluxion@kali]-[~] 1
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

                      ESSID: "sun2402" / WPA2                                   
                    Channel:  2                                                 
                      BSSID:  34:CE:00:45:21:64 ([N/A])                   

[*] Fluxion is targetting the access point above.
[*] Continue with this target? [Y/n] y

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select a wireless interface for target tracking.
[*] Choosing a dedicated interface may be required.
[*] If you're unsure, choose "Skip"!

[1] wlan0mon [*] Intel Corporation Wireless 8260 (rev 3a)                       
[2] Skip                                                                    
[3] Repeat                                                                    
[4] Back                                                                    

[fluxion@kali]-[~] 2

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select an interface for the access point.

[1] eth0     [+] Intel Corporation Ethernet Connection I219-V (rev 21)          
[2] wlan0mon [*] Intel Corporation Wireless 8260 (rev 3a)                       
[3] Repeat                                                                    
[4] Back                                                                    

[fluxion@kali]-[~] 2

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select an access point service

                      ESSID: "sun2402" / WPA2                                   
                    Channel:  2                                                 
                      BSSID:  34:CE:00:45:21:64 ([N/A])                   

	[1] Rogue AP - hostapd (recommended)
	[2] Rogue AP - airbase-ng (slow)
	[3] Back

[fluxion@kali]-[~] 1

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] A hash for the target AP was found.
[*] Do you want to use this file?

	[1] Use hash found
	[2] Specify path to hash
	[3] Rescan handshake directory
	[4] Back

[fluxion@kali]-[~] 1

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select a method of verification for the hash

                      ESSID: "sun2402" / WPA2                                   
                    Channel:  2                                                 
                      BSSID:  34:CE:00:45:21:64 ([N/A])                   

	[1] pyrit verification
	[2] aircrack-ng verification (unreliable)
	[3] cowpatty verification (recommended)
	[4] Back

[fluxion@kali]-[~] 3

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select SSL certificate source for captive portal.

	[1] Create an SSL certificate
	[2] Detect SSL certificate (search again)
	[3] None (disable SSL)
	[4] Back

[fluxion@kali]-[~] 1

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select an internet connectivity type for the rogue network.

	[1] disconnected (recommended)
	[2] emulated
	[3] Back

[fluxion@kali]-[~] 1

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 5.7    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select a captive portal interface for the rogue network.

                      ESSID: "sun2402" / WPA2                                   
                    Channel:  2                                                 
                      BSSID:  34:CE:00:45:21:64 ([N/A])                   

          [01] Generic Portal                                   Arabic          
          [02] Generic Portal                                Bulgarian          
          [03] Generic Portal                                  Chinese          
          [04] Generic Portal                                    Czech          
          [05] Generic Portal                                   Danish 
.
.
.
.

[fluxion@kali]-[~] 3

root@kali:~/fluxion/scripts# iwconfig 
fluxwl0   IEEE 802.11  Mode:Monitor  Tx-Power=0 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
lo        no wireless extensions.

fluxwl0v  IEEE 802.11  Mode:Master  Tx-Power=22 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
eth0      no wireless extensions.
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V5.7

#### BASH Info 
GNU bash, version 5.0.2(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0mon) Info 
**Device**: phy0
**Driver:** iwlwifi
**Chipset:** Intel Corporation Wireless 8260 (rev 3a)
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(343)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.8-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.19.0-kali3-amd64 (devel@kali.org) (gcc version 8.2.0 (Debian 8.2.0-16)) #1 SMP Debian 4.19.20-1kali1 (2019-02-14)

#### Chipset
Chipset: iwlwifi
Don't reseve all required information

**Comment by xxsv3n** [comment]
I have the same issue when using a single wireless interface (1 wifi interface for jamming & ap hosting). However, when I used 2 wireless interfaces & set 1 for jamming & the other for deauthing it worked as expected.

**Comment by leosun620** [comment]
2 NIC can fix work well, one for attacking and  other play the fake  role .but  in fact  this  tool  only  need  one  NIC.because  of using virtual Tech.

**Comment by strasharo** [comment]
Install mdk4 manually and fluxion will use it instead of mdk3 if it recognizes that it's in the path. mdk3 has been problematic for quite a long time.

**Comment by leosun620** [comment]
I'm new ,you talk this solution before.but when i apt install mdk4 and apt remove mdk3, i type ./fluxion and it will force you to install mdk3.or can you teach me how to configure the mdk4 in  detail .think  you  every  much 🌹🌹🌹

**Comment by leosun620** [comment]
@strasharo .you  can  also  let  me  know  which  version of  fluxion  can  run well in  mdk3?

**Comment by leosun620** [comment]
@strasharo you  mean that  just  apt  install  mdk4 and  then  run  fluxion  without remove  mdk3. the  fluxion  will  recognize the mdk4 and  use mdk4 instead of  mdk3 automatically. is it right ?

**Comment by strasharo** [comment]
Yes, if you have both mdk4 and mdk3 available in the $PATH, mdk4 takes preference.

**Comment by leosun620** [comment]
@strasharo，after i installed mdk4, it still not work. the real AP  can be connect and fake AP work  well.

**Comment by leosun620** [comment]
ps -aux |grep mdk ,i saw  ........-title FLUXION AP Jammer  Service [AP_name] -e mdk4 fluxwl0 d -c 11 -b "/tmp/fluxspace/mdk3_blacklist .lst "
can  you  help  me ?thanks bro.@strasharo

**Comment by hacker12345677** [comment]
> fluxwl0

Same problem bro
