### ISSUE TITLE
Add metaspolit file hack

### ISSUE THREAD

**Issue by Athis97** [FluxionNetwork/fluxion#713]
if fluxion may extend to metaspolite hack (android and windows)
it may effective,
__For android
when i start fluxion metaspolite apk should automatically generate and when victim enters into fluxion hotspot, apk file should download automatically and show html page for phishing
if victim enter the password in phishing side, we got password
if he install that apk then automatically we get password file from "data/misc/wifi/wpa_supplicant.conf" defenetly it contain saved wifi passwords, after that we gonna manual check for verification of that password with hash by using cowpatty,aircrack-ng or etc,...

In windows
"netsh wlan show profile name=profilename key=clear"

### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

**Comment by Athis97** [comment]
In india,
many android users don't know about login page of wifi,
so they try to use data instead of login,
if fluxion may extend to metaspolite hack (android and windows)
it may effective,
__For android
when i start fluxion metaspolite apk should automatically generate and when victim enters into fluxion hotspot, apk file should download automatically and show html page for phishing
if victim enter the password in phishing side, we got password
if he install that apk then automatically we get password file from "data/misc/wifi/wpa_supplicant.conf" defenetly it contain saved wifi passwords, after that we gonna manual check for verification of that password with hash by using cowpatty,aircrack-ng or etc,...

In windows
"netsh wlan show profile name=profilename key=clear"

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/issues/708

**Comment by minanagehsalalma** [comment]
@athis87 this isn't possible due to root permissions !
