### ISSUE TITLE
why fluxion sometimes crash ?!! 

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#714]
the crash
![snapshot1](https://user-images.githubusercontent.com/20546638/54451039-8f668480-475a-11e9-9c6e-d2eba11513d8.png)

some weird bugs .that appears when i select choose another attack... but still it continues and ignores the bugs  
![snapshot3](https://user-images.githubusercontent.com/20546638/54451068-a1482780-475a-11e9-91eb-fbf1d779e7d0.png)

..
the fluxspace folder while the attack is  in  select another attack mode
![while the attack is select anthoer attack mode](https://user-images.githubusercontent.com/20546638/54451171-e2d8d280-475a-11e9-942d-5ae02b2ebd43.png)
...
the fluxspace folder while the attack is working 
![while the attack is working ](https://user-images.githubusercontent.com/20546638/54451244-0ef45380-475b-11e9-9d0a-c5e08c62e376.png)

.....
i couldn't copy the php.socket-3 file 
![snapshot2](https://user-images.githubusercontent.com/20546638/54451327-4d8a0e00-475b-11e9-898c-3aa821485d60.png)

the fluxion space folder and fluxion-master folder
[flux bug.zip](https://github.com/FluxionNetwork/fluxion/files/2972296/flux.bug.zip)

**Comment by minanagehsalalma** [comment]
@deltaxflux  os; wifislax64-1.1-final

**Comment by strasharo** [comment]
![image](https://user-images.githubusercontent.com/3337997/54473144-959d4500-47dc-11e9-96e8-1cec48ce92c3.png)
There's corruption on the file system of your OS.

**Comment by minanagehsalalma** [comment]
@strasharo  
but the crash happens before this .. it just hangs on starting captive portal.......
