### ISSUE TITLE
Wps karma attack !

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#717]
https://youtu.be/y24_QQjbHFA?t=4860

https://github.com/wifiphisher/wifiphisher/issues/264

**Comment by strasharo** [comment]
I'm going to quote @v1s1t0r1sh3r3:
`You are the suggester, so spend your time to do a very well and clear explanation of what you are suggesting... not a "read this and good luck". No buddy, we are not going to do nothing in this way.`

**Comment by minanagehsalalma** [comment]
@strasharo ... 
@v1s1t0r1sh3r3 isn't  a good cooperator ... he didn't let me reply to his comments ..

"spend your time to do a very well and clear explanation of what you are suggesting"

i provided a video that shows a demo of it and add the start time :4860: to the link...
and even provided an same topic issue ... that people discussed the problems and the solutions...

and i am not that advanced into hostapd settings to detail the steps ..etc 

i just saw an idea that i liked ... and thought it would be great if you can implement/add it .

here is an pdf that discuss the steps 

[[Tuto] Rogue AP discreet in full WPA with hostapd (Page 1) _ The tutorials crack-wifi.com _ Crack-wifi.pdf](https://github.com/FluxionNetwork/fluxion/files/2988090/Tuto.Rogue.AP.discreet.in.full.WPA.with.hostapd.Page.1._.The.tutorials.crack-wifi.com._.Crack-wifi.pdf)


btw the suggest isn't that brilliant idea ... but it still good
