### ISSUE TITLE
fluxion crashes with  a negative channel number in the hostapd.conf  !!

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#718]
the crash it shows the captive portal window and crashes after channel hopping or when it refreshes the channel
![snapshot4](https://user-images.githubusercontent.com/20546638/54765623-8403d500-4c02-11e9-82fa-211153ff3720.png)

the AP-hostapd.conf file
![snapshot1](https://user-images.githubusercontent.com/20546638/54766460-f7f2ad00-4c03-11e9-814b-81a238abcf59.png)

the target info file 
![snapshot2](https://user-images.githubusercontent.com/20546638/54766558-21133d80-4c04-11e9-8769-535bbd8cc376.png)

**Comment by strasharo** [comment]
If the driver reports a negative channel there's nothing we can do about it.

**Comment by minanagehsalalma** [comment]
@strasharo  .. but sometimes it works just fine !?

**Comment by minanagehsalalma** [comment]
@strasharo  "If the driver reports a negative channel there's nothing we can do about it."
i  think there something .... what about removing the "-" from the channel number ?! if it happened.

**Comment by strasharo** [comment]
-1 means invalid channel, there's no point in assuming it's channel 1.

**Comment by minanagehsalalma** [comment]
https://forum.aircrack-ng.org/index.php?topic=748.0

> Dude, the only reason people are getting this is because they forget to kill network managers and THAT'S IT. Killing them is enough to solve the issue.

....
https://askubuntu.com/questions/318583/how-can-i-solve-fixed-channel-1-mon0-is-on-channel-1-issue-when-using-airo

> Download and install the latest Aircrack-ng development (beta). There's an --ignore-negative-one switch that you can use to fix that fixed channel -1 annoying error


@strasharo  i will try newer version of aircrack and tell you 
wouldn't  --ignore-negative-one  switch fix this problem ?!
