### ISSUE TITLE
Issuie not deauthusing Real WiFi when hosting AP

### ISSUE THREAD

**Issue by Barty89** [FluxionNetwork/fluxion#720]
Using AWUS036NHA with kali Linux latest

Updated everything installed mdk4 

I can do everything fine up until making the AP I can host the AP I just can’t seem to jam the real AP to force them to see my fake AP 

I’ve tried removing mdk3 but then I’ve forced to install it again at the start as it says missing I’ve been through the old issues and people have been told to get mdk4 I’ve done that and issuie still there 

Can’t deauth everyone of Real WiFi 

Placed mdk4 in root too no luck

Any suggestions are much appreciated! 

Thanks for reading sorry about my English

**Comment by cjb900** [comment]
you have to have 2 wifi adapters. Since one wifi adapter can only do one think at a time it can not deauthenticate and create a rouge access point at the same time. You need 2 one to deauthenticate and one to create the rouge access point. at least thats what i've found out in my testing. unless i'm doing something wrong my self

**Comment by Barty89** [comment]
Thanks for the reply does it matter what network card hosts and use the AWUS036NHA to deauth ?

**Comment by Barty89** [comment]
Also anyone know the part of code to take out so when we run fluxion it doesn’t check for mdk3 so it just  uses mdk4 maybe ?

**Comment by strasharo** [comment]
If you have both mdk4 and mdk3 in your path it will pick mdk4, no need to remove any code.

**Comment by Barty89** [comment]
What’s the “path” is it a file or the root ?

**Comment by strasharo** [comment]
the $PATH environment variable. Just  type in:
`command -v mdk4`
in the shell prior starting fluxion and if there's any option the command is available in your path and fluxion should pick it.

**Comment by strasharo** [comment]
Also while deauth is running you can do a:
`ps -ef | grep mdk | grep -v grep`
And confirm which one is running - mdk3 or mdk4.

**Comment by Barty89** [comment]
Thank you very much I will try this once I get home

**Comment by Barty89** [comment]
Both commands worked its using mdk4

i got this 
`root@kali:~/fluxion# ps -ef | grep mdk | grep -v grep
root       8022   2213  0 20:14 pts/0    00:00:00 xterm -geometry 50-0-0 -bg black -fg #FF0009 -title FLUXION AP Jammer Service [NOWTV18A94] -e mdk4 fluxwl0 d -c 12 -b "/tmp/fluxspace/mdk3_blacklist.lst"
root       8081   8022  0 20:14 pts/5    00:00:00 mdk4 fluxwl0 d -c 12 -b /tmp/fluxspace/mdk3_blacklist.lst`

how ever it doesn't deauth any devices off the AP any idea how i could fix this please any input much appreciated!

**Comment by leosun620** [comment]
i came across the  same  problem that  you  have  to use 2 NIC (one for deauth, onefor fake AP). install mdk4, it is still  not working .

**Comment by Barty89** [comment]
Thanks leosun I’ve ordered another hopefully coming today the only reason I’m skeptical is when I deauth it doesn’t deauth anything off ap so I was wondering if it changing channel soon as I deauth but if I scan while doing the deauth it says the ap is still on the same channel :/

**Comment by strasharo** [comment]
If mdk4 is not working for you, you can raise the issue at:
https://github.com/aircrack-ng/mdk4/issues

At least for me it works fine with AWUS036NHA and other adapters containing the same chipset.

**Comment by Barty89** [comment]
Damn got my second Alfa adapter and still no joy if anyone’s prepared to help me via team viewer I’m happy to pay them because I haven’t got a clue why it isn’t working now. I can get a hand shake but can’t kick off ap even with a second network adapter tracking and one jamming.

**Comment by Barty89** [comment]
Hey  strasharo quick question how would I know if my AP has 802.11w (encrypted management frames) as I opened up airodump and focused on my AP and when I try mdk4 attack it it is switching ch rapidly in the top left corner so the only think I could think of was that ?

**Comment by strasharo** [comment]
What's the model of your AP?

**Comment by Barty89** [comment]
Manufacturer Sky
Model NR801
Firmware Version 1.00.2182.R

**Comment by Barty89** [comment]
If anyone can help me fix this issuie prepared to pay

**Comment by Barty89** [comment]
Hey update from me not sure if anyone may find this helpful with finding out if their AP is 802.11w protected. 
MDK4 member told me to take these steps to find out 

“You can open the capture with wireshark, locate a beacon, then open the 802.11 wireless wlan section, then the tagged parameters. In the RSN information tag, select RSN capabilities, 802.11w is "Management frame protection". There are 2 bits. It can be disabled ("capable"), optional or mandatory.

If the client has negotiated 802.11w, then you won't be able to kick him out”

Also read this article 
“Management Frame Protection Capable must have the value True. There is also a RSN IE element in the capture of beacons from an SSID send by an access point. If the Management Frame Protection Required is true in the capture of the beacon, only 802.11w-capable devices can connect to this network. If both values for Management Frame Protection Required and Management Frame Protection Capable are False, 802.11w is not enabled on the network. I use an IPad Air to test the connect behaviour when using a device not supporting 802.11w.

To test the 802.11w protection, I use the Aircrack-ng suite. More specific I use Airodump-ng to check if the 4-way handshake is captured and I use aireplay-ng to inject deauthentication packets (replay) to deauthenticate a client and enforce the client to execute the 4-way handshake with the access point (because we need those packets to crack the code). If 802.11w is working, the client will not deauthenticate and the 4-way handshake is not captured.”

Now what baffles me is my AP isn’t protected by 802.11w so not sure why it isn’t deauth any of my devices from my AP
Back to square one. 

I’ll post updates if allowed or needed for fellow newbies like myself.

**Comment by medudder** [comment]
@Barty89,
I Have EXACTLY the same issue!  I have 2 wifi radios.  Both of them worked GREAT on version 4.9 which used mdk3 however since the integration of mdk4 (in the newer versions of Fluxion) it will no longer deauth.   I Agree that the issue is is the mdk4 module but there is nothing i can do about it.  Is there any "simple" way in which we can use Fluxion 5.9 with mdk3 instead of mdk4?  That should solve the problem.

Thanks guys!!

**Comment by Barty89** [comment]
I did weeks of trying to figure it out and googling ect and never personally found a fix I even offered to pay someone who can help me fix this issuie and I’ve had no response ect so still none working for myself like you

**Comment by medudder** [comment]
@Barty89 
I really think there is a serious bug in either Fluxion or mdk4.  I've tried it on various operating systems:  Kali, rasbian, Ubuntu, same results.
If you need version 4.9, let me know, it seems to work perfectly fine, however i would like to keep up to date with this amazing Fluxion community.
The perfect sulution, for me, would be to replace mdk4 with mdk3.  Unfortunately, the newer version of Fluxion require mdk4. 

BTW, i reinstalled mdk4 directly from the Github page, but it's still not deauthing.
