### ISSUE TITLE
Can`t connect to FAKE AP

### ISSUE THREAD

**Issue by Critic777** [FluxionNetwork/fluxion#721]
Do you want to request a feature or report a bug?
-Bug
What is the current behaviour?
-The interception of a handshake is completely intact, but when creating a fake access point through hostapd, the point is not even created, everything stops with the inscription creating a point.
When creating an access point through an air base, everything seems to be "working", but when connected from the phone to a fake point, it automatically turns off.
What are the problems and how to solve them?

Specs
### FLUXION Info
FLUXION V5.7

#### BASH Info
GNU bash version 5.0.2 (1) -release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
GPLv3 + license: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software. You can change and distribute it.
NO WARRANTY is granted to the extent permitted by law.
** Path: ** / usr / bin / bash

#### Interface (wlan0) Info
** Device **: phy0
** Driver: ** ath9k
** Chipset: ** Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
** Master Modes ** Yes
** Injection Test: ** ioctl (SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
** Version: ** XTerm (344)
** Path: ** / usr / bin / xterm
Test: XServer / XTerm success!

#### HostAPD Info
hostapd v2.8-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X / WPA / WPA2 / EAP / RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: / usr / sbin / hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2 - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3 +
** Scapy Version: ** 2.3.3

#### System Info
** Chipset: ** Linux version 4.19.0-kali4-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-2)) # 1 SMP Debian 4.19.28-2kali1 (2019-03 -18)

#### Chipset
Chipset: ath9k
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by strasharo** [comment]
` ** Injection Test: ** ioctl (SIOCSIWMODE) failed: Device or resource busy`
Device is locked by some other process, this would prevent fluxion from working properly.
