### ISSUE TITLE
Channel changes in AP but not in fluxion

### ISSUE THREAD

**Issue by xmagickx** [FluxionNetwork/fluxion#722]
I've an AP which I'm targeting. Everything works fine in fluxion. It's just an enhancement or upgrade that is needed. The AP once attacked changes its channel after few minutes. Then again I've to manually reset the attack to change the channel of the fake AP. Can this be automated with a script so that as fluxion detects a change in AP channel it also changes the channel?

**Comment by strasharo** [comment]
It's already in there, it's called target tracking interface and you need a separate adapter for it.

**Comment by xmagickx** [comment]
I've 2 separate wifi adapters... 1 usb and 1 inbuilt.. both are capable of packet injection... But once the fakeAP is setup then if the real AP changes the channel the fakeAP doesn't...

**Comment by strasharo** [comment]
You have to use one of them for ap and the other for a tracking interface.

**Comment by xmagickx** [comment]
But when one of them is used for target tracking and one for AP then which one is used for disconnecting clients from the real AP?

**Comment by xmagickx** [comment]
@strasharo as per your instructions I've setup fluxion to track track target with one adapter while rogue AP as another adapter. But after 5 second of running fluxion properly with all 6 windows it is stopping with only AP window running and no other windows opening.
