### ISSUE TITLE
Question about changing the form of the login page?

### ISSUE THREAD

**Issue by Asux30** [FluxionNetwork/fluxion#723]
What is the way to change the form of the login page, I have many pages but do not know how to integrate it with fluxion.

**Comment by mehdimers** [comment]
> What is the way to change the form of the login page, I have many pages but do not know how to integrate it with fluxion.
I think you have to go in this directory:  /fluxion/attacks/Captive Portal/sites/
and then you find all router index, you can add your own.

**Comment by Asux30** [comment]
Can you explain the way to me? Because I tried it and did not work

**Comment by strasharo** [comment]
Just edit any existing template found in https://github.com/FluxionNetwork/fluxion/tree/master/attacks/Captive%20Portal/sites and adapt it to your needs.
