### ISSUE TITLE
Support for TL WN 722N v3

### ISSUE THREAD

**Issue by pukarsharma112** [FluxionNetwork/fluxion#725]
The v2 and v3 of **tl wn 722N** doesn't support monitor mode by default but using the drivers found on https://github.com/kimocoder/rtl8188eus make the adapter to go to monitor mode and it works for both monitor mode and packet injection( I have tested on kali linux 2019 ). The only problem is it can't start monitor mode by old method, "**airmon-ng start wlanX**" but using "**iwconfig wlanX mode monitor**", it goes to monitor mode and airodump-ng wlanX work correctly. But fluxion doesn't support this and shows wifi adapter not supported. 
_If there is any way to support fluxion th wn 722N v3 , then guys please help me_

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/issues/83#issuecomment-464261854
