### ISSUE TITLE
can we get Fake web-based network manager for android phones

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#726]
[this awesome attack](https://wifiphisher.org/ps/wifi_connect/)

![image](https://user-images.githubusercontent.com/20546638/55579258-1da9a700-5718-11e9-8d6f-14856710d3f5.png)

**Comment by minanagehsalalma** [comment]
@deltaxflux  the win version code from wifiphisher 
https://github.com/wifiphisher/wifiphisher/tree/master/wifiphisher/data/phishing-pages/wifi_connect

**Comment by strasharo** [comment]
No.
