### ISSUE TITLE
what about a Sextortion based phishing page ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#727]
i am not talking about Threatening the user to send money or post the *** videos part ..

but i am talking about the part where they makes these threats more plausible ..
that they use old/still in use passwords from data breaches .
so the idea is to tell the user to confirm the old password change ( here we type the old password ) please re-enter your new password . this only in case of knowing an old password of the target wifi .

or if we don't know the old password but we know that the password had been changed recently
the page tells the user to confirm the password change please re-enter your new password .

![image](https://user-images.githubusercontent.com/20546638/55673671-4f06ac00-58ab-11e9-97b6-2b78e69d2d71.png)

tell me what do you think

reference
https://www.cisecurity.org/blog/sextortion-hoax-scams-updated-tactics/

**Comment by strasharo** [comment]
![image](https://user-images.githubusercontent.com/3337997/55744500-c1a79100-5a3d-11e9-85fb-5abbbef10bfb.png)
Man, seriously, stop spamming us with this bullshit, you've been warned, next irrelevant request will result in a ban here.

**Comment by minanagehsalalma** [comment]
@strasharo 
Dude spam and ban !!! What are you talking about !!!?

I deserve to  get a top fan budget !

**Comment by minanagehsalalma** [comment]
@strasharo  and there is still a idea   on my mind .
Have you heard about DNS rebinding .
