### ISSUE TITLE
Cannot find device "fluxwl0v"

### ISSUE THREAD

**Issue by edenhikri** [FluxionNetwork/fluxion#728]
![Screen Shot 2019-04-11 at 9 54 02 am](https://user-images.githubusercontent.com/48461270/55921402-ebc8a100-5c3f-11e9-907e-a35731633546.jpg)

Hi. Could you please help me resolve this issue? I am using a Panda Wireless PAU06 300mbps USB adapter. I have tried deleting and then redownloading fluxion. I have also tried deleting the attacks/Captive Portal/attack.conf file but nothing is working.

Thankyou

**Comment by deltaxflux** [comment]
Never used the Panda Wireless PAU06 300mbps USB adpater. Likly this wireless card does not support access point mode. Could you run the diagnostic script ?
