### ISSUE TITLE
Fails to add repo key on Ubuntu 16.04

### ISSUE THREAD

**Issue by Meowcat285** [FluxionNetwork/fluxion#730]
#### Summary

Fails to install due to missing apt keys, when it tries to add the keys it fails
##### What is the current behaviour?

Unable to install dependancys
#### How to reproduce
N/A (may be system specific)
##### What do you think the expected behaviour should be?

It should add the repo and install dependancys
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
N/A
#### Expected behavior

It should add the repo and install dependencys

**Comment by deltaxflux** [comment]
Could you please share any logs ?
