### ISSUE TITLE
mdk4missing

### ISSUE THREAD

**Issue by hanbing88** [FluxionNetwork/fluxion#731]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by hanbing88** [comment]
MDK4 missing in wifislax4.10

**Comment by deltaxflux** [comment]
Install mdk4 using the source.
```
git clone https://github.com/aircrack-ng/mdk4
 cd mdk4 	
make 	
sudo make install
```

**Comment by hanbing88** [comment]
wifislax mdk4 # sudo make install
make -C src clean
make[1]: 正在进入目录 `/root/mdk4/src'
rm -f mdk4
rm -f debug.o helpers.o mac_addr.o linkedlist.o greylist.o dumpfile.o packet.o brute.o osdep.o channelhopper.o ghosting.o fragmenting.o
rm -f ../test *.o
make -C osdep clean
make[2]: 正在进入目录 `/root/mdk4/src/osdep'
make -C radiotap clean
make[3]: 正在进入目录 `/root/mdk4/src/osdep/radiotap'
rm -f *.o
make[3]:正在离开目录 `/root/mdk4/src/osdep/radiotap'
rm -f libosdep.a  *.o .os.*
make[2]:正在离开目录 `/root/mdk4/src/osdep'
make -C attacks clean
make[2]: 正在进入目录 `/root/mdk4/src/attacks'
rm -f attacks.o auth_dos.o beacon_flood.o countermeasures.o deauth.o dummy.o eapol.o fuzzer.o ieee80211s.o probing.o wids.o *.o
make[2]:正在离开目录 `/root/mdk4/src/attacks'
make[1]:正在离开目录 `/root/mdk4/src'
make -C src
make[1]: 正在进入目录 `/root/mdk4/src'
make -C osdep
make[2]: 正在进入目录 `/root/mdk4/src/osdep'
Building for Linux
make[3]: 正在进入目录 `/root/mdk4/src/osdep'
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o osdep.o osdep.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o network.o network.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o file.o file.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o linux.o linux.c
linux.c:1048:12: 警告：‘linux_set_channel’定义后未使用 [-Wunused-function]
 static int linux_set_channel(struct wif *wi, int channel)
            ^
linux.c:2057:13: 警告：‘linux_close’定义后未使用 [-Wunused-function]
 static void linux_close(struct wif *wi)
             ^
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o linux_tap.o linux_tap.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o radiotap/radiotap.o radiotap/radiotap.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o common.o common.c
ar cru libosdep.a  osdep.o network.o file.o linux.o linux_tap.o radiotap/radiotap.o common.o
ranlib libosdep.a 
touch .os.Linux
make[3]:正在离开目录 `/root/mdk4/src/osdep'
make[2]:正在离开目录 `/root/mdk4/src/osdep'
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o debug.o debug.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o helpers.o helpers.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o mac_addr.o mac_addr.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o linkedlist.o linkedlist.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o greylist.o greylist.c
greylist.c: 在函数‘load_greylist’中:
greylist.c:67:13: 警告：从不兼容的指针类型赋值 [enabled by default]
       glist = blist;
             ^
greylist.c:72:13: 警告：从不兼容的指针类型赋值 [enabled by default]
       glist = wlist;
             ^
greylist.c: 在函数‘is_blacklisted’中:
greylist.c:105:6: 警告：传递‘search_in_greylist’的第 2 个参数时在不兼容的指针类型间转换 [enabled by default]
      entry = search_in_greylist(mac, blist);
      ^
greylist.c:44:18: 附注：需要类型‘struct greylist *’，但实参的类型为‘struct blacklist *’
 struct greylist *search_in_greylist(struct ether_addr mac, struct greylist *glist) {
                  ^
greylist.c: 在函数‘is_whitelisted’中:
greylist.c:119:5: 警告：传递‘search_in_greylist’的第 2 个参数时在不兼容的指针类型间转换 [enabled by default]
     entry = search_in_greylist(mac, wlist);
     ^
greylist.c:44:18: 附注：需要类型‘struct greylist *’，但实参的类型为‘struct whitelist *’
 struct greylist *search_in_greylist(struct ether_addr mac, struct greylist *glist) {
                  ^
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o dumpfile.o dumpfile.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o packet.o packet.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o brute.o brute.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o osdep.o osdep.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o channelhopper.o channelhopper.c
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:142:8: 错误：‘struct ifmap’重定义
 struct ifmap {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:111:8: 附注：原先在这里定义
 struct ifmap
        ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:176:8: 错误：‘struct ifreq’重定义
 struct ifreq {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:126:8: 附注：原先在这里定义
 struct ifreq
        ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:225:8: 错误：‘struct ifconf’重定义
 struct ifconf  {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:176:8: 附注：原先在这里定义
 struct ifconf
        ^
channelhopper.c: 在函数‘error_handler’中:
channelhopper.c:155:46: 警告：未使用的参数‘nla’ [-Wunused-parameter]
 static int error_handler(struct sockaddr_nl *nla, struct nlmsgerr *err,
                                              ^
channelhopper.c: 在函数‘finish_handler’中:
channelhopper.c:163:42: 警告：未使用的参数‘msg’ [-Wunused-parameter]
 static int finish_handler(struct nl_msg *msg, void *arg)
                                          ^
channelhopper.c: 在函数‘ack_handler’中:
channelhopper.c:170:39: 警告：未使用的参数‘msg’ [-Wunused-parameter]
 static int ack_handler(struct nl_msg *msg, void *arg)
                                       ^
channelhopper.c: 在函数‘valid_handler’中:
channelhopper.c:186:45: 警告：未使用的参数‘arg’ [-Wunused-parameter]
 int valid_handler(struct nl_msg *msg, void *arg)
                                             ^
channelhopper.c: 在函数‘handle_channels’中:
channelhopper.c:328:50: 警告：未使用的参数‘state’ [-Wunused-parameter]
 static int handle_channels(struct nl80211_state *state, struct nl_msg *msg)
                                                  ^
channelhopper.c: 在函数‘channel_sniff’中:
channelhopper.c:387:6: 警告：未使用的变量‘ie_type’ [-Wunused-variable]
  int ie_type;
      ^
channelhopper.c: 在函数‘init_channel_hopper’中:
channelhopper.c:592:19: 警告：未使用的变量‘i’ [-Wunused-variable]
     int lpos = 0, i;
                   ^
channelhopper.c: 在文件作用域：
channelhopper.c:240:14: 警告：‘dfs_state_name’定义后未使用 [-Wunused-function]
 static char *dfs_state_name(enum nl80211_dfs_state state)
              ^
make[1]: *** [channelhopper.o] 错误 1
make[1]:正在离开目录 `/root/mdk4/src'
make: *** [all] 错误 2
wifislax mdk4 #

**Comment by strasharo** [comment]
Contact wifislax/mdk4 dev.

**Comment by hanbing88** [comment]
thanks for your help.OK,now
