### ISSUE TITLE
server starting service

### ISSUE THREAD

**Issue by testermd12** [FluxionNetwork/fluxion#732]
Server starting service
version: fluxion 5.9

Creating the Evil Twin AP is fine but connecting to it seems to be impossible. ive search every corner to try and resolve this issue but it just seems that when i create the AP it takes ages to connect to and the DNS spoofer doesn't populate at all. not sure how i can resolve this issue ive tried everything so far.

Still trying, update: when connecting to the AP it says no internet.... something is up with the DNS, any ideas?

Kind Regards,

**Comment by strasharo** [comment]
Next time fill in the bug report template.

**Comment by testermd12** [comment]
thats nice of you. very professional
