### ISSUE TITLE
握手包路径存放怎么写，一直都是错误的

### ISSUE THREAD

**Issue by a26188071** [FluxionNetwork/fluxion#739]
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by deltaxflux** [comment]
Fill out the issue template.

**Comment by a26188071** [comment]
Bug Report
Summary
At present, we choose the AP to attack and store the handbag location.
Must present
Write handshake package storage path, no matter what is written is wrong, the corresponding path can not be found.
Expected results: I should enter the path, the interface prompt is successful, and can successfully store the handshake bag.
Five
Specs
Paste the output of ./script/diagnostics.sh [interface]
Log cannot be crawled at present
Expected behavior
