### ISSUE TITLE
Human made dictionaries

### ISSUE THREAD

**Issue by creited** [FluxionNetwork/fluxion#740]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | idk
| BC Break    | idk

#### Summary

I have been playing with your tool and it works really well. I was thinking about a captal portal that would ask the USER to test its WIFI password to check how strong it is. Using simple or more elaborated rules it would test the password (i.e length) and return the user with: weak, medium, strong. It would then add the password to a dictionary file which would be updated with every user that tries to log in the OPEN WIFI. After helping with this "survey", the user would be allowed to use the internet for about 15 minutes (configurable time) and then his mac address would be blocked to avoid the same password being entered twice (this should also be  configurable).

When writing the password to the dictionary file, it would be good to test it (write only if length > 8) check if the password isn't already inside the file.

This was something I was thinking about. If it works good, we can have dictionaries with really usefull passwords.

Any suggestions? Hard points for making this work.

Thanks

**Comment by strasharo** [comment]
Irrelevant to the purpose of the tool.
