### ISSUE TITLE
WiFi Jammer Service

### ISSUE THREAD

**Issue by kohacker59** [FluxionNetwork/fluxion#741]
### Bug Report
Wifi Jammer Service
#### Summary
Wifi Jammer Service not working properly

##### What is the current behaviour?
Wifi Jammer Service close itself after running the fake ap when no one is trying to connect (for about 2- 5minutes) and I will run fake ap again

##### What do you think the expected behaviour should be?
Running

#### Expected behavior
Running

**Comment by strasharo** [comment]
Fill in the template, we don't have a crystal ball to guess your environment.
