### ISSUE TITLE
older version available?

### ISSUE THREAD

**Issue by medudder** [FluxionNetwork/fluxion#743]
Hi,
Is there a way to get an older version of fluxion,   like ver. 4.6?
I've had nothing but problems with the newer versions.

Thanks!!

**Comment by strasharo** [comment]
2.9
https://github.com/wi-fi-analyzer/fluxion

**Comment by azad342** [comment]
I have version 4.4. Follow the link: https://yadi.sk/d/-fUi2SjwrGSMMg
