### ISSUE TITLE
how to make a personal certificate?

### ISSUE THREAD

**Issue by Daniel4u23** [FluxionNetwork/fluxion#748]
Hello, is it possible to NOT issue a certificate for the web portals? The untrusted certificate is the only reason that fluxion "doesn't work". Most users are not able to "force" their browser to trust our certificate because they don't know how. Plus, they are reading the browser's description for what's happening and they stop responding completely.

**in page : https://github.com/FluxionNetwork/fluxion/wiki/Captive-Portal-Attack**
**_Part 6 - 2  :_** 
If you've got a personal certificate, you must save it at fluxion/attacks/Captive Portal/certificate/server.pem and the attack will automatically detect it and auto-select it.
so , **how to make a personal certificate?**

Thank you!

**Comment by strasharo** [comment]
Just choose to have a portal without SSL.

**Comment by Daniel4u23** [comment]
how to make file server.pem ?
