### ISSUE TITLE
Deauthenticator randomly crashes on Kali 2019.2

### ISSUE THREAD

**Issue by MPX4132** [FluxionNetwork/fluxion#749]
### Bug Report
The deauthenticator crashes randomly when using mdk4 **(default)**.

#### How to reproduce
Run a captive portal attack using the default deauthenticator.

##### What do you think the expected behaviour should be?

No crashes.

##### Specs
Card using the ath9k_htc driver.

**Comment by MPX4132** [comment]
This is probably a problem with mdk4, which is probably why we should NOT be using experimental tools.

**Comment by aquilabianca8** [comment]
Same issue..

Il giorno 27 mag 2019, alle ore 04:49, Matias Barcenas <notifications@github.com<mailto:notifications@github.com>> ha scritto:


This is probably a problem with mdk4, which is probably why we should NOT be using experimental tools.

**Comment by medudder** [comment]
I replaced the mdk4 for mdk3 and it works fine.
MDk4 is a problem, I totally agree!!

**Comment by Gabo1203** [comment]
medudder, how did you replace it?
Gracias!
Thank you!

**Comment by medudder** [comment]
@Gabo1203 
de nada :)


**modification in "_fluxion.sh_"
replaced mdk4 for mdk3 in this line:**

 "aircrack-ng" "bc" "awk:awk|gawk|mawk"
    "curl" "cowpatty" "dhcpd:isc-dhcp-server|dhcp" "7zr:p7zip" "hostapd" "lighttpd"
    "iwconfig:wireless-tools" "macchanger" "mdk3" "nmap" "openssl"
    "php-cgi" "pyrit" "xterm" "rfkill" "unzip" "route:net-tools"
    "fuser:psmisc" "killall:psmisc"
  )

**modification in "_attach.sh_"
replaced mdk4 for mdk3 in this line**

	xterm $FLUXIONHoldXterm $BOTTOMRIGHT -bg black -fg "#FF0009" \
        -title "FLUXION AP Jammer Service [$FluxionTargetSSID]" -e \
        "mdk3 $CaptivePortalJammerInterface d -c $FluxionTargetChannel -b \"$FLUXIONWorkspacePath/mdk4_blacklist.lst\"" &
        # Save parent's pid, to get to child later.
    	CaptivePortalJammerServiceXtermPID=$!

**Comment by Futureman83** [comment]
mdk4 is removed in Kali repos.

**Comment by Rainy57** [comment]
How replace it,guys?

**Comment by deltaxflux** [comment]
Compile the source @Futureman83

**Comment by yehias** [comment]
just use nano:

$ nano fluxion.sh

then press :

$ ctrl+\

write:

$ mdk4

replace:

$mdk3

click:

$ shift +a

**Comment by usuarionuevor** [comment]
how come this is still not fixed?

**Comment by adrianbelmans** [comment]
Please fix this, I tried installing mdk4 by compiling and installing the make file from github. the jammer still fails to work and crashes... 

after that i tried replacing mdk4 with mdk3 with the method described above, still crashes...

My networkcard is an alfa AWUS036NH

if I try fluxion 2.0 from the official repo then the deauthenticator works but i get some other bugs like the password checked correct or getting corrupted handshakes.

**Comment by deltaxflux** [comment]
I revert to mdk3 later.
