### ISSUE TITLE
Templates pack

### ISSUE THREAD

**Issue by ushasha** [FluxionNetwork/fluxion#75]
Hello, this is a pack of 17 templates created by DidyMond (credit him if they are used)
[Templates.zip](https://github.com/FluxionNetwork/fluxion/files/1225170/Templates.zip) for a Linset italian fork. They are complete for the use with linset, but not compatible (at least at a first attempt) with Fluxion. I tried to change the name folder for each router and indeed they are recognized by Fluxion, and pages even start and are displayed, but the gathered password isn't sent to the script. Is it possible to add them to Fluxion?

**Comment by deltaxflux** [comment]
You miss our wiki page?
https://github.com/FluxionNetwork/fluxion/wiki/Prepping-protals-for-fluxion

**Comment by ushasha** [comment]
i tried to modify one template and adapt it to fluxion, but honestly i don't have the necessary skills, sorry. i uploaded the files for anybody better than me at this. i asked the author but unfortunately he has no time/possibility to modify them, and loose all that work, with so many routers, looks like a real waste. again, sorry if i can't be more helpful, didn't want to beg or demand nothing, just be somewhat useful

**Comment by MPX4132** [comment]
I just updated fluxion with compatibility for linset portals, thanks for the tip.

**Comment by MPX4132** [comment]
@deltaxflux should we add the portals to the repository, or just close this thread? The issue has already been addressed by the addition of support for linset portals. I tested them, and they worked fine after the update.

**Comment by deltaxflux** [comment]
Give me some minutes so I can check the login pages.
