### ISSUE TITLE
FLUXION AP Jammer - Se Cierra luego de unos minutos.

### ISSUE THREAD

**Issue by Gabo1203** [FluxionNetwork/fluxion#750]
Hola! Estoy usando fluxion 5 rev9 - Pero la ventana llamada FLUXION AP Jammer - luego de unos minutos de haber iniciado el portal cautivo se cierra de forma inesperada. Creo que no es normal.
Uso kalilinux 2019.1 en VMware® Workstation 14 Pro. Y tarjeta inalambrica tplink tl-wn722n v1.
Gracias por la informacion que puedan brindar.

**Comment by jamezrin** [comment]
Duplicate of #749
