### ISSUE TITLE
error of segmentation

### ISSUE THREAD

**Issue by frankota** [FluxionNetwork/fluxion#751]
hello
I am testing fluxion  5.9 and after handshake snooper, when it captured the handshake, I press ctrl+c, I chose select another attack but I have the error of segmentation and it show the prompt of linux.
What could be the problem?

Thanks
FRank

**Comment by strasharo** [comment]
How exactly does the error look like?

**Comment by frankota** [comment]
it brings me out of fluxion and it shows " error of segmentation" nothing more :(

**Comment by strasharo** [comment]
We don't have psychic abilities over here.

**Comment by lydi202019** [comment]
hi
I'm testing fluxion 6.5 and after handshake snooper, when it captured the handshake, I press ctrl+c, I chose select another attack but I have the error of segmentation and it show the prompt of linux.
What could be the problem?

Thanks
lydia
