### ISSUE TITLE
Add fake ap stop if the victim wifi is off

### ISSUE THREAD

**Issue by thieulam** [FluxionNetwork/fluxion#753]
### Feature Request
<Add stop fake ap if the victim ap is not present for 30 seconds.
The first action of victim is turn off the power for resetting the modem. If the modem is off, but the fake ap is present , is a situation very strange-->

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/issues/612
