### ISSUE TITLE
 mdk4........................................ Missing! 

### ISSUE THREAD

**Issue by dhirajy** [FluxionNetwork/fluxion#757]
Site: https://github.com/FluxionNetwork/fluxion                                                   
                                                         FLUXION 5 (rev. 9) by FluxionNetwork                                                         
                                                                Online Version [5.9]

                                               [*] aircrack-ng...................................... OK.                                              
                                               [*] bc............................................... OK.                                              
                                               [*] awk.............................................. OK.                                              
                                               [*] curl............................................. OK.                                              
                                               [*] cowpatty......................................... OK.                                              
                                               [*] dhcpd............................................ OK.                                              
                                               [*] 7zr.............................................. OK.                                              
                                               [*] hostapd.......................................... OK.                                              
                                               [*] lighttpd......................................... OK.                                              
                                               [*] iwconfig......................................... OK.                                              
                                               [*] macchanger....................................... OK.                                              
                                               [*] mdk4........................................ Missing!                                              
                                               [*] nmap............................................. OK.                                              
                                               [*] openssl.......................................... OK.                                              
                                               [*] php-cgi.......................................... OK.                                              
                                               [*] pyrit............................................ OK.                                              
                                               [*] xterm............................................ OK.                                              
                                               [*] rfkill........................................... OK.                                              
                                               [*] unzip............................................ OK.                                              
                                               [*] route............................................ OK.                                              
                                               [*] fuser............................................ OK.                                              
                                               [*] killall.......................................... OK.

**Comment by dhirajy** [comment]
https://github.com/aircrack-ng/mdk4

use above problem solved

**Comment by bayati221111** [comment]
sudo apt-get install mdk4
if it didn't fix your issue, try sudo ./fluxion.sh -i
