### ISSUE TITLE
/tmp/fluxspace/Captive_portal_authenticator.sh permission denied   

### ISSUE THREAD

**Issue by udontknowit** [FluxionNetwork/fluxion#758]
im using the  last build I updated all the necessary things Downloaded and installed mkd4 I also got the handshake for wpa2 network

when the “captive portal authenticator”  window i get this error  /tmp/fluxspace/Captive_portal_authenticator.sh permission denied   

I tried chmoding main fluxion and /Captive_portal_authenticator.sh 

still the same

**Comment by strasharo** [comment]
There's some issue with your environment or it doesn't permit executing scripts from /tmp. You can alter the temp path here and point it to some user directory instead of /tmp :
https://github.com/FluxionNetwork/fluxion/blob/master/fluxion.sh#L13

**Comment by udontknowit** [comment]
Thanks I tried this and it works fine , I was wondering is it better to choose eth0 built in wifi for access point or to choose wlan0 ( alfa ) for both ?

**Comment by udontknowit** [comment]
I want to know for target tracking and access point , do I choose the same wifi card , I got Alfa awe36nh

**Comment by udontknowit** [comment]
when it says fix channel , 

is that normal
