### ISSUE TITLE
can't install missing files

### ISSUE THREAD

**Issue by Farazrao786** [FluxionNetwork/fluxion#76]
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

----

### What is the current behavior?
-> *Quit accidentally*

---

#### If the current behavior is a bug, please provide the steps to reproduce.
-> *A great way to do this is to provide screenshots and commands.*

--- 

#### What is the expected behavior?
-> *Be creative*

---

### If this is a feature request, what is motivation or use case for changing the behavior?

---

#### Wireless adapter:
*Exact model, chipset, and driver versions.*

#### Does it support injection?
*Paste the output of `aireplay-ng -9`*

#### Fluxion version:
*Paste the output of* `cat fluxion.sh | grep revision`

#### Linux version:
*Paste the output of* `cat /proc/version` or `uname -r`

**Comment by MPX4132** [comment]
By "missing files" do you mean dependencies?

**Comment by azad112** [comment]
I have missing dependencies. They are dhcpd, hostapd and php-cgi. How can i install them? I am using kali 2.0. Please help me.
