### ISSUE TITLE
Monitor interface doesn't lock at specified channel

### ISSUE THREAD

**Issue by taner1** [FluxionNetwork/fluxion#760]
#### Summary
Monitor mode cant stay at specified channel.
Also deauth attacks should specify a client, mdk4 and aireplay tools aren't disconnecting clients for my setup, i have to do it manually.
My setup is intel 6205 pci wifi card and Manjaro 18.0.4 with 5.1.10-ck kernel.
##### What is the current behaviour?
While doing deauth the channel keeps switching. That cause unsuccessful attack.
*also bunch of adjustments needed like downgrade python2-scapy to 2.3.2 and add cowpatty -2 parameter -its guiding for arch based distro users-*
##### If the current behaviour is a bug, please provide the steps to reproduce it.
`
  while true; do
    echo "[T-Tracker] Captor listening for $monitorTimeout seconds..."
    timeout --preserve-status $monitorTimeout airodump-ng -aw "$capturePath" \
      -d "$FluxionTargetMAC" $FluxionTargetTrackerInterface &> /dev/null
    local error=$? # Catch the returned status error code.`
This code block seems to broken in fluxion.sh and adding hardcoded -c *channel* is temporary fix.

##### What do you think the expected behaviour should be?
Wifi monitor interface must be at specified channel all time.

**Comment by strasharo** [comment]
It's locked on the channel:
https://github.com/FluxionNetwork/fluxion/blob/master/attacks/Captive%20Portal/attack.sh#L1526

If you specify the tracking interface to be the same as the default one it would start hopping.
