### ISSUE TITLE
Fluxion [2] Error: your wireless card  isn't supported

### ISSUE THREAD

**Issue by RaphaelLima123** [FluxionNetwork/fluxion#762]
How can I fix it?

|    Q        |   A
|------------ | -----
| new feature     | Yes

![Screenshot from 2019-06-25 10-56-27](https://user-images.githubusercontent.com/47906061/60105492-65e1cf80-9731-11e9-81d2-78239ea769bf.png)

**Comment by deltaxflux** [comment]
No information provided.
