### ISSUE TITLE
deauth on channel 13

### ISSUE THREAD

**Issue by bigicxxl** [FluxionNetwork/fluxion#763]
hello , i have stange problem..... when i try to attack and deauth client from wifi on channelm12 or 13 is not possible... only possible is when wifi is on channel 1-11. why is that? so if my wifi network is on channel 12 or 13 i'm imune to attacks? i have try with all my 3 wifi adapters like Alfa, .... with support monitor mode and injections...etc but not working attack on channel 12 or 13. but i have no problem to connect on channel 12 or 13 , so i dont understand

**Comment by strasharo** [comment]
The region set in your wireless adapter firmware doesn't have those channels. You can confirm that with "iw list" and "iw reg get"

**Comment by bigicxxl** [comment]
![Screenshot_20190707-205337](https://user-images.githubusercontent.com/52566280/60773383-1920d000-a105-11e9-8c04-3a8870fc26cd.png)
