### ISSUE TITLE
Landing Page is not appearing - until disconnecting from AP , also sideeffects with 2nd hostapd session 

### ISSUE THREAD

**Issue by Grauen** [FluxionNetwork/fluxion#764]
I'm running Fluxion on a Raspberry Pi (Kali).
Usually I'm running a hostapd access point to have "direct" ssh and vnc-access to the rapi.
(to see how I setup the AP please check out this link, maybe you'll see what could have caused side effects on Fluxion: https://frillip.com/using-your-raspberry-pi-3-as-a-wifi-access-point-with-hostapd/)

There are two WIFI interfaces - wlan0 and wlan1. **wlan0** is the default interface coming with raspberry (this is used for providing the AP). **wlan1** is an usb wifi dongle. I'm using wlan1 for fluxion.

First I started fluxion, while being connected to the **wlan0** AP. 
So there are **2 sessions of hostapd** running.

When hostapd is already running, the Fluxion-Fake-AP (wlan1) is not always showing up during wifi scans, until you restart the attack. Sometimes the wlan1 AP is available though.

- Maybe this is some config I'm missing in dhcpcd or in my local hostapd.conf - but right now I don't even know where to look next to resolve this. Do you have any idea?

When I'm trying to connect to the internet **via wlan0, I'll see the fake-AP login page**. Even though I'm not even connected to the Fake AP. I think the web service should only listen to connections coming from the interface you chose while setting up the attack.
**If you are connecting to the fake ap, there will be no internet connection and no auth page available.**

**Issue part 2**
So I turned off my wlan0 AP and the whole hostapd service. 

When I was running Fluxion I was able to connect to the wlan1 Fluxion AP and the AP never disappeared. Also the "auth-page" was available. 

But when I try to open the auth page, the browser keeps on loading the page and all I see is a white screen. There is some logging in the Fluxion Web Service about resources from the portal being requested. And when I disconnect from the AP, the loaded part of the page will be displayed in the browser.

Funny thing is - when I'm opening the browser while being connected to wlan0 AP, the portal page will always appear without any loading issues.

**Comment by strasharo** [comment]
Sort out your hostapd setup, fluxion is not designed to support multiple hostapd daemons running.
