### ISSUE TITLE
I don't find dependency mdk4 & 7zr on fedora 30 x64

### ISSUE THREAD

**Issue by BedoM** [FluxionNetwork/fluxion#765]
|    Q        |   A
|------------ | -----
| Version     | Online Version [5.9]

#### Support Question

Hello I try to use fluxion on my fedora 30 and after install automaticaly and manualy the dependenci i don't find 7zr but i have only 7z and i don't find mdk4..

**Comment by BedoM** [comment]
delete pls

**Comment by ramiroaisen** [comment]
> delete pls

Hey did you solve this? Im having same issue here
