### ISSUE TITLE
at0 no such device when ESSID has spaces

### ISSUE THREAD

**Issue by officiallor** [FluxionNetwork/fluxion#766]
#### Summary

I'm running the preinstalled fluxion on wifislax (rev 0.24 fluxion it says) and it works normally with my awus036h but when the network has a space it can't start DHCP and it says at0 not found. This happens only on awus036h and not with internal rt3070 card.

#### How to reproduce
Try a network with awus036h that has spaces, like "HELLO WORLD" and launch an attack.
##### What do you think the expected behaviour should be?

It should start the AP normally.
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by strasharo** [comment]
Not even sure how old is that version, pull the current one and retry.
