### ISSUE TITLE
isnt recognizing handshakes(.cap) captured earlier by the script itself or any other program

### ISSUE THREAD

**Issue by RadhaKrishn4** [FluxionNetwork/fluxion#767]
#### Summary
it fails to recognize handshakes captured in cap files earlier by the script itself

##### What is the current behaviour?
when we provide file path to the stored .cap file(earlier captured by the script itself & backed up) in the absolute file path step in captive portal setup it says "path points to non-existing or empty path file.this message also appears for the handshakes captured by other programs such as airgeddon etc.

##### If the current behaviour is a bug, please provide the steps to reproduce it.
when setting up captive portal when it asks for path of handshake .cap file point it to the path of any handshake file (even the default handshake capturing directory would also suffice)just it has to be manual input of path
![Screenshot from 2019-07-29 12-10-04](https://user-images.githubusercontent.com/40521810/62027048-53f4c000-b1fa-11e9-8aa3-667ff82c32ec.png)

##### What do you think the expected behaviour should be?
it should recognize the handshake provided in the .cap files then proceed to captive portal setup

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V5.9

#### BASH Info 
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k
**Chipset:** Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(347)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.8
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.2
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.19.0-kali5-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.37-6kali1 (2019-07-22)

#### Chipset
Chipset: ath9k
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

#### Expected behavior

it should recognize the handshake provided in the .cap files then proceed to captive portal setup

**Comment by andtankian** [comment]
Try to copy the handshake from the **Handshaker Snoop** fold and paste it on **/root.**

After that, rename the file to another simpler name, like _sarma.cap_.

Type the following to the absolute path: **/root/sarma.cap**

**Comment by RadhaKrishn4** [comment]
after latest commit its saying dependency installation falied and gets stuck at it  @andtankian 
![Screenshot from 2019-08-08 15-09-19](https://user-images.githubusercontent.com/40521810/62692619-9c785e80-b9ee-11e9-8709-0874b9d2b3c0.png)

**Comment by RadhaKrishn4** [comment]
i closed the thread because there's now a new issue!now i cant even open nor run the script/program hence until that issue is resolved im keeping this closed

**Comment by RadhaKrishn4** [comment]
@andtankian tried renaming and pasting in root folder the same problem repeats

**Comment by andtankian** [comment]
Strange.

Try to not put simple quotes ( ' ) around the path.

Just: /root/sarma.cap

**Comment by RadhaKrishn4** [comment]
yes thanx. removing quotes from path works.but quotes are necessary if the path contains spaces right?? what to do then??
