### ISSUE TITLE
Script stuck @ starting captive portal access point service,Fakeap ,fake dns ,other miscelleneous windows not opening,

### ISSUE THREAD

**Issue by RadhaKrishn4** [FluxionNetwork/fluxion#768]
#### Summary
Script stuck at starting captive portal access point service,Fakeap ,fake dns ,other miscelleneous windows not opening,tried with 3 different adapters @afonso @dandrews @Geczy @anhskohbo @spmedia 

##### What is the current behaviour?
gets stuck at starting captive portal service & no fake ap is created

##### If the current behaviour is a bug, please provide the steps to reproduce it.
in fluxion ver 5.9 just complete all steps to create a captive portal setup after selecting any login page & try to attack it will get stuck at starting captive portal service & no windows will be opened 
![Screenshot from 2019-07-29 13-05-45](https://user-images.githubusercontent.com/40521810/62031912-0a11d700-b206-11e9-8a8c-00ce4790c18f.png)

##### What do you think the expected behaviour should be?
it should open various windows & start the attack & create fakeap with captive portal

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V5.9

#### BASH Info 
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (fluxwl0) Info 
**Device**: phy0
**Driver:** ath9k
**Chipset:** Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(347)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.8
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.2
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.19.0-kali5-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.37-6kali1 (2019-07-22)

#### Chipset
Chipset: ath9k
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

#### Expected behavior
it should create fakeap with captive portal and deauth target access point from connecting with clients & force them to connect to our fake AP & then verify the password entered in the captive portal login page by user with the handshake captured earlier &save the password in a file(if its correct)& then close fakeap & other relevant windows and processes to avoid suspicion.

**Comment by deltaxflux** [comment]
Please checkout last commit.

**Comment by RadhaKrishn4** [comment]
after latest commit the script gets stuck at Dependency installation failed @deltaxflux @afonso @dandrews @Geczy

**Comment by RadhaKrishn4** [comment]
@deltaxflux @afonso @dandrews @Geczy respected brothers the same issue exits in latest commit

**Comment by KeoJam** [comment]
just display 
Usage ./scripts/diagnostics [wireless_interface]

**Comment by KeoJam** [comment]
#### FLUXION Info
FLUXION V5.9


#### BASH Info 
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** mt7601u
**Chipset:**  
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!


#### XTerm Infos
**Version:** XTerm(344)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.8
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.19.0-kali4-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-2)) #1 SMP Debian 4.19.28-2kali1 (2019-03-18)

#### Chipset
Chipset: mt7601u
