### ISSUE TITLE
Something went wrong with MDK4

### ISSUE THREAD

**Issue by kimphat** [FluxionNetwork/fluxion#769]
I installed a new Kali linux v2019.2( i tried 2018.4 but still have the same problem). Fisrt of all, after run ./fluxion -i everything went well, but after run it again ./fluxion it didnt scan anything. So i tried to run airmon-ng start wlan0 and run fluxion again, everything  run well but the real problem is fluxion doesnt run deauth attack. Fluxion created a new AP with the same name but, the real Wifi still using OK, and no device auto connect to the Fishing AP. Although, if i connect to the fake AP manually and type the password, everything run well again. I thought something went wrong with the MDK4 because that's its job but not sure. I tried another card wifi( USB wifi) but still the same problem.  I havent used fluxion been along time so any help is appreciated. Thank for reading. Love u guys

**Comment by deltaxflux** [comment]
Yeah you are right. I revert to mdk3. Try it now!
