### ISSUE TITLE
There is not lib folder and fail

### ISSUE THREAD

**Issue by aeri** [FluxionNetwork/fluxion#770]
It seems like lib folder, that is neccesary to run fluxion is not available in the latest commit.

**Comment by RadhaKrishn4** [comment]
![Screenshot from 2019-08-08 15-09-19](https://user-images.githubusercontent.com/40521810/62693031-52dc4380-b9ef-11e9-9a99-b14c7a883cba.png)
the script gets stuck at dependency installation failed and doesn't move forward from there @aeri @afonso @dandrews @Geczy @anhskohbo

**Comment by deltaxflux** [comment]
Thank you!

Due the .gitgnore the lib folder was untracked and I removed cached files which should not be tracked by git.
