### ISSUE TITLE
mt7601u cannot create fake ap

### ISSUE THREAD

**Issue by KeoJam** [FluxionNetwork/fluxion#772]
i use mt7601u  to create fak ap   but  it just show creating fake ap,  show some windows and close soon,  and nothing happened

**Comment by RadhaKrishn4** [comment]
@KeoJam i cant even see opening windows.no windows are opening and the script gets stuck at starting captive portal service

**Comment by KeoJam** [comment]
@RadhaKrishn4  i mean when begin to create fake ap, just two console windows appeared and close soon, i saw some course that has six console windows appeared when create fake up.

**Comment by RadhaKrishn4** [comment]
yes its not working.the script is not creating fakeap and to me theres not
even a single window opening it just gets stuck @ starting captive portal
service

**Comment by KeoJam** [comment]
@RadhaKrishn4 
FLUXION Info
FLUXION V5.9

BASH Info
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /usr/bin/bash

Interface (wlan0) Info
Device: phy0
Driver: mt7601u
Chipset:
Master Modes Yes
Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

XTerm Infos
Version: XTerm(344)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

HostAPD Info
hostapd v2.8
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen j@w1.fi and contributors
Path: /usr/sbin/hostapd

Aircrack-ng Info
EXIT
Aircrack-ng 1.5.2 - (C) 2006-2018 Thomas d'Otreppe
https://www.aircrack-ng.org

Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
Scapy Version: 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

System Info
Chipset: Linux version 4.19.0-kali4-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-2)) #1 SMP Debian 4.19.28-2kali1 (2019-03-18)

Chipset
Chipset: mt7601u

**Comment by md-rubel** [comment]
same problems are here..  no ap is creating  :(
