### ISSUE TITLE
Enhancement/Upgrade feature for problems of AP channel changing 

### ISSUE THREAD

**Issue by xmagickx** [FluxionNetwork/fluxion#780]
### Feature Request

In certain Routers/APs after deauthing clients from the AP by mdk3 the AP/Router changes it's channel automatically & renders the attacks ineffective by mdk3. 

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Instead of using mdk3 if we use mdk4 which has far more options with the "deauthentication/disassociation mode". The mdk4 has several implementation of the "d" option where you don't have to provide a blacklist.txt file option for the attack. Instead there are other flags under the "disassociation" option namely- "-S" flag which takes the AP MAC as input which attacks any client connected to the AP, hence even if the AP changes channel no client will be able to connect it as mdk4 attacks the AP MAC address.

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/issues/769
