### ISSUE TITLE
I have an idea for routers to automatically change channels

### ISSUE THREAD

**Issue by zcvxcv** [FluxionNetwork/fluxion#781]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

I have an idea for routers to automatically change channels, and I've written Bash, but I'm a novice and don't know how to integrate into Fluxion.
I found that the aireplay-ng-0 0-A MAC command is always valid regardless of the channel change of the target router, but there is a problem that it sometimes shuts down automatically.
So I wrote this Bash  
Hope to help everyone
It currently supports only 2.4 GHz, and I don't have a 5G network card that supports KALI.  
[Continuous-attacks](https://github.com/zcvxcv/Continuous-attacks.git)

**Comment by strasharo** [comment]
There's already a tracking interface functionality in fluxion.
