### ISSUE TITLE
Fluxion can't detect the right password inserted.

### ISSUE THREAD

**Issue by Sirvod** [FluxionNetwork/fluxion#783]
#### Summary
I had a hash with handshake snooper i used aireplay-ng deauth method
Run a captive portal with the particular hash used aircrack-ng and i connected my device with the evil-twin AP and inserted the corrected password to the captive portal but rejects the password with incorrected password and "attempt" increments.
I used aircrack cause its the only way i could get a valid hash in fluxion.

Then i closed fluxion run aircrack-ng on the hash captured by fluxion with a wordlist that has that particular password and aircrack-ng got the key.

OS - Blackarch 2019.09.01

**Comment by strasharo** [comment]
Verification in the captive portal is being done using cowpatty:
https://github.com/FluxionNetwork/fluxion/blob/master/attacks/Captive%20Portal/attack.sh#L920

If the handshake doesn't pass cowpatty verification it wouldn't work.
