### ISSUE TITLE
Staring captive portal access point service (duplicate of #777)

### ISSUE THREAD

**Issue by MinePro120** [FluxionNetwork/fluxion#788]
#### Summary
Fluxion halts while creating "captive portal access point service".

##### What is the current behaviour?
Fluxion halts.

#### How to reproduce
Launch the evil twin attack with the same network adapter (in all questions) and the recommended settings. I used fluxion to successfully capture a handshake before. Language

##### What do you think the expected behaviour should be?
I suppose it should bring up 2 or 3 terminal windows, the http/dns server and the deauther. Actually, it tries to bring up a window, but it instantly closes.

#### FLUXION Info
FLUXION V5.9

#### BASH Info 
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k
**Chipset:** Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter (rev 01)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(348)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.2
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 5.2.0-kali2-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-19)) #1 SMP Debian 5.2.9-2kali1 (2019-08-22)

#### Chipset
Chipset: ath9k
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

Note : it might seem that my wireless card cannot switch to monitor mode or inject packets, but it's quite capable of doing so. I remember some programs reporting that my card was not suitable. Please don't close this issue, it has been mentioned before as well (#777).

**Comment by strasharo** [comment]
Try with another adapter.
