### ISSUE TITLE
For all people that have problems running fluxion on ubuntu - this is a guide to help you

### ISSUE THREAD

**Issue by BlinkingRiki182** [FluxionNetwork/fluxion#792]
Hallo dear community,

I'm by no means an experienced coder but I've spent some hours making fluxion ver. 5.9 run smoothly on ubuntu. Here are my findings which I hope will be helpful to you.

Right off the bat, installing fluxion on ubuntu requires a few additional steps documented here:
https://miloserdov.org/?p=227

After installing fluxion with all dependencies, there are some additional problems that require tackling:

1) Captive Protal AP can't be launched - this is definitely a problem with your WLAN driver or WLAN hardware. This is working off the bat in ubuntu, so if you face this problem don't bother trying to fix it in the code, as described here: https://github.com/FluxionNetwork/fluxion/issues/579

2) DNS doesn't start (DNS Window doesn't show up in Captive Portal mode). This has been already found by the community described here:  https://github.com/FluxionNetwork/fluxion/issues/580

What you need to do here is stop the service that listens on port 53 (DNS) by default on ubuntu by using:
sudo systemctl stop systemd-resolved

After the attack, the service can be started again using "sudo systemctl start systemd-resolved" or by reboot. You can edit that in the script "fluxion/attacks/Captive_Portal/attack.sh" so that the service is stopped before the attack and started after it.

3) DHCPD doesn't run or doesn't have access to /tmp/fluxspace/dhcpd.*. This problem has two aspects - first the DHCPD doesn't run because it needs root privileges. This can be fixed by adding a "sudo" command in front of calling the dhcpd service:

In "fluxion/attacks/Captive_Portal/attack.sh", Line 1483:
....
-title "FLUXION AP DHCP Service" -e \
"_sudo_ dhcpd ..."
....

After you have done this, if you try to restart the attack, the DHCPD service will start but won't have access to dhcpd.leases and dhcpd.conf in /tmp/fluxspace/. This problem is described here:

https://help.ubuntu.com/community/isc-dhcp-server

What you need to do is stop the apparmor deamon: "sudo /etc/init.d/apparmor stop" and then edit in the following lines in /etc/apparmor.d/usr.sbin.dhcpd with root permissions:

/tmp/fluxspace/dhcpd.leases* rwl,
/tmp/fluxspace/dhcpd.conf r,
/tmp/fluxspace/clients.txt rwl,
/tmp/fluxspace/candidate_result.txt rwl,

You can now start apparmor: "sudo /etc/init.d/apparmor start"

The DHCPD and DNS should now be running in Captive Portal mode.

4) After a successful attack, the victim lands on your website and tries to enter a password. Currently as of 5.9, the default method for hash verification is cowpatty. Unfortunately this doesn't seem to work very well on ubuntu. When the victim enters the correct password, it isn't recognized as being correct. The way to go around this problem is to use aircrack-ng (follow the optional step described in step 1 (look in the link) to install the latest aircrack-ng version in ubuntu). I'm sure there's a much more elegant way to do this in the code but I just removed the whole cowpatty section:

In "fluxion/attacks/Captive_Portal/attack.sh", after Line 922: remove the whole "if cowpatty" section. Also you need to add "sudo" here and there and remove some aircrack-ng parameters. Code should look like this for the whole "if":

======================================================

if [ $CaptivePortalAuthenticatorMode = "hash" ]; then
    # 05/26/19: Default to cowpatty for verification since aircrack-ng appears to have a bug.
      echo "
      if [ -f \"$FLUXIONWorkspacePath/candidate_result.txt\" ]; then
          # Check if we've got the correct password by looking for anything other than \"Passphrase not in\" or \"KEY NOT FOUND\".
          if ! sudo aircrack-ng -w \"$FLUXIONWorkspacePath/candidate.txt\" \"$CaptivePortalHashPath\" | egrep -qi \"Passphrase not in|KEY NOT FOUND\"; then
              sudo echo \"2\" > \"$FLUXIONWorkspacePath/candidate_result.txt\"
              sleep 1
              break
          else
              sudo echo \"1\" > \"$FLUXIONWorkspacePath/candidate_result.txt\"
          fi
      fi" >> "$FLUXIONWorkspacePath/captive_portal_authenticator.sh"
  fi

======================================================

Now you're ready to launch an attack. I had success using pyrit verification.

Hope this guide helps. I wasn't sure where to put this, so I guess I'll just put it here.

**Comment by PranavBhattarai** [comment]
This means that fluxion devs are not going to solve this mess for Ubuntu.
In other words, make it ubuntu compatible.

_When the maximum Linux users are Ubuntu, this is saddening for a lot of users. 
Not everyone can find this solution and try other software like wifite._

**Comment by bocman2003** [comment]
its because u cant dissconnect people and make an AP with the same adapter

**Comment by BlinkingRiki182** [comment]
> its because u cant dissconnect people and make an AP with the same adapter

Oh rly?

**Comment by lesol144** [comment]
I can’t connect to the fake network, what should I do?
