### ISSUE TITLE
Not working on Kali NetHunter

### ISSUE THREAD

**Issue by joelstitch** [FluxionNetwork/fluxion#794]
I am running Kali NerHunter on my Oneplus 7 Pro running an image made by re4son. Everything works great but for some reason can't get Fluxion to run right. I install it with git clone and when I try to run the script it just doesnt show anything on the terminal. I am using a VNC Viewer to access the GUI on my Kali installation.

I installed it also on a raspberry pi and on it it runs smoothly.

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/issues/268

**Comment by jepunband** [comment]
anyone got it working on nethunter? .. i'm not seeing anything after launching it .. ./fluxion.sh
just blank screen.
