### ISSUE TITLE
Fluxion Not Authenticating PW Hash

### ISSUE THREAD

**Issue by dakrisht** [FluxionNetwork/fluxion#795]
|    Q        |   A
|------------ | -----
| Version     | 5.9

#### Support Question
When entering the correct credentials (pw) in the rogue AP captive portal, multiple Fluxion portals DO NOT acknowledge the password and throw a “wrong password” error.

Further, the button to go back says “volver” on multiple EN portals and text bottom right says “¿please help .....?” Which makes zero sense.

Handshake acquired via Snooper, verified via Cowpatty, AP not using SSL (iOS13 does *not* launch a captive portal with SSL but does without SSL), AP, jammer, all working just fine.

![84264E68-6623-448D-BC2A-B592DF346F84](https://user-images.githubusercontent.com/1464758/68084503-52cfc200-fdeb-11e9-8696-987f013404ac.jpeg)

![8D5598D8-244A-4933-8D6A-87FF7C36B5A4](https://user-images.githubusercontent.com/1464758/68084723-6e889780-fdee-11e9-8874-c7a94e33879e.jpeg)

Adding: ARRIS captive portal never even gets passed the “authenticating” screen once PW is entered and button is pressed. Screen attached.

![6A46F6D1-A1CA-4A69-A305-7EBA56676C66](https://user-images.githubusercontent.com/1464758/68093942-11bdc900-fe50-11e9-8a02-cf24d6eea687.png)

#### Specs

> #### Interface (wlan0) Info 
> **Device**: phy3
> **Driver:** rt2800usb
> **Chipset:** Ralink Technology, Corp. RT2870/RT3070
> **Master Modes** Yes
> **Injection Test:** Injection is working!
> 
> 
> #### XTerm Infos
> **Version:** XTerm(348)
> **Path:** /usr/bin/xterm
> Test: XServer/XTerm success!
> 
> 
> #### HostAPD Info
> hostapd v2.9
> User space daemon for IEEE 802.11 AP management,
> IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
> Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
> Path: /usr/sbin/hostapd
> 
> 
> #### Aircrack-ng Info
> EXIT
>   Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
>   https://www.aircrack-ng.org
> 
> 
> #### Pyrit Info
> Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
> https://github.com/JPaulMora/Pyrit
> This code is distributed under the GNU General Public License v3+
> **Scapy Version:** 2.4.2
> Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.
> 
> #### System Info
> **Chipset:** Linux version 5.2.0-2parrot1-amd64 (team@parrotsec.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 5.2.9-2parrot1 (2019-08-25)
> 
> #### Chipset
> Chipset: rt2800usb
> Chipset support ap mode
> Chipset support monitor mode
> Don't reseve all required information
>

**Comment by strasharo** [comment]
Specify the exact templates you're having issues with.
