### ISSUE TITLE
Fluxion AP Jammer Not Working (MDk4)

### ISSUE THREAD

**Issue by dakrisht** [FluxionNetwork/fluxion#796]
### Bug Report
Fluxion 5 rev.9 (v.5.9)

#### Summary
Fluxion AP Jammer is not deauthing clients even with the latest version of Fluxion and MDk4 installed.

##### What is the current behaviour?
Rogue AP created, without SSL, appears on iOS devices however, does not appear on a Windows nor a Macbook laptop (strange). Hostapd shows working fine and able to connect to rogue AP on iOS device and captive portal opens.

However, clients connected to secured network are NOT being deauthed.

So three issues here:

1) No deauth on the AP Jammer
2) No AP on certain devices visible
3) Captive Portal does not close and locks after "authenticate" is clicked (in this case, ARRIS EN)

#### How to reproduce
0. airmon-ng check kill as a primer
0. Start Fluxion
1. Captive Portal
2. All Channels 2.4Ghz
3. SSID selected after scan
4. (2) skip
5. Interface for access point (Ralink RT2870/3070) selected (wlan0)
6. Rogue AP - hostapd
7. Use hash found
8. Cowpatty - success
9. None - disable SSL
10. Disconnected
11. ARRIS EN (29

Attack starts

![Screen Shot 2019-11-03 at 4 42 14 PM](https://user-images.githubusercontent.com/1464758/68094837-35d1d800-fe59-11e9-8c7d-c99f1d293939.png)

##### What do you think the expected behaviour should be?
Fluxion should 1) jam and deauth the existing AP and 2) broadcast the new open AP to all clients, not just one iPhone.

Current AP Jammer screens only shows;

> "Periodically re-reading blacklist/whitelist every 30 seconds."

##### Specs

> Interface (wlan0) Info
> Device: phy3
> Driver: rt2800usb
> Chipset: Ralink Technology, Corp. RT2870/RT3070
> Master Modes Yes
> Injection Test: Injection is working!
> 
> XTerm Infos
> Version: XTerm(348)
> Path: /usr/bin/xterm
> Test: XServer/XTerm success!
> 
> HostAPD Info
> hostapd v2.9
> User space daemon for IEEE 802.11 AP management,
> IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
> Copyright (c) 2002-2019, Jouni Malinen j@w1.fi and contributors
> Path: /usr/sbin/hostapd
> 
> Aircrack-ng Info
> EXIT
> Aircrack-ng 1.5.2 - (C) 2006-2018 Thomas d'Otreppe
> https://www.aircrack-ng.org
> 
> Pyrit Info
> Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
> https://github.com/JPaulMora/Pyrit
> This code is distributed under the GNU General Public License v3+
> Scapy Version: 2.4.2
> Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.
> 
> System Info
> Chipset: Linux version 5.2.0-2parrot1-amd64 (team@parrotsec.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 5.2.9-2parrot1 (2019-08-25)
> 
> Chipset
> Chipset: rt2800usb
> Chipset support ap mode
> Chipset support monitor mode
> Don't reseve all required information

**Comment by RasyiidWho** [comment]
What I know, Fluxion uses mdk3 instead of mdk4 because some bugs that now already fixed (but Fluxion not updated yet).. And normally, mdk3 only shows "Periodically re-reading blacklist/whitelist every 30 seconds." without jammer log (jammer log available in mdk4).

If you want try Fluxion with mdk4 version, you can try usama version
https://github.com/usama7628674/Fluxion

**Comment by dakrisht** [comment]
> What I know, Fluxion uses mdk3 instead of mdk4 because some bugs that now already fixed (but Fluxion not updated yet).. And normally, mdk3 only shows "Periodically re-reading blacklist/whitelist every 30 seconds." without jammer log (jammer log available in mdk4).
> 
> If you want try Fluxion with mdk4 version, you can try usama version
> https://github.com/usama7628674/Fluxion

Thanks. Will try this. Was under the impression that Fluxion switched to mdk4 if it was installed but doesn’t look that way.

I’ve tried to aireplay-ng deauth the AP and also the client SSID as well and cannot get neither client nor AP offline to present only the rogue AP.

More concerning is the Rogue AP (hostapd) freezing after the user clicks the “authenticate” button... this doesn’t make sense. Should loop back to password error, or as by design, kill the attack if PW success.

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/issues/769
