### ISSUE TITLE
http://captive.gateway.lan Server Not Found

### ISSUE THREAD

**Issue by vladinko0** [FluxionNetwork/fluxion#799]
### Bug Report
Captive portal on Kali machine at http://captive.gateway.lan is displaying Server Not Found and of course on client machine I see just "No internet" window. 

#### How to reproduce
Step | Parameter
-- | --
Select a wireless interface for Target searching. | [1] wlan0
Select a wireless interface for Target tracking. | [1] wlan0
Select an interface for jamming. | [1] wlan0
Select an interface for the Access point. | [4] wlan1
Select an access point service | hostapd
Select SSL certificate source For captive portal. | 1
Select an internet connectivity Type for the rogue network. | 1
Select a captive portal interface For the rogue network. | 7

![Screenshot from 2019-11-11 05-42-56](https://user-images.githubusercontent.com/16008547/68581466-737cc500-0446-11ea-8e55-2e55342e9190.png)

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V5.9

#### BASH Info 
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** rtl88xxau
**Chipset:** ASUSTek Computer, Inc. USB-AC56 802.11a/b/g/n/ac [Realtek RTL8812AU]
**Master Modes** Yes
**Injection Test:** No Answer...
Injection is working!

#### XTerm Infos
**Version:** XTerm(348)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.2
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 5.2.0-kali2-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-19)) #1 SMP Debian 5.2.9-2kali1 (2019-08-22)

#### Chipset
Chipset: 88XXau
Chipset is not in list

#### Expected behavior

Captive portal should be displayed.

Note: I am using the newest and clean Kali 2019.3.

**Comment by vladinko0** [comment]
I disabled firewall and checked lighttpd, it is running...
Still Server Not Found in captive.gateway.lan

![Screenshot from 2019-11-12 07-02-33](https://user-images.githubusercontent.com/16008547/68670380-d0e24600-051a-11ea-965b-6d955f8457f7.png)

**Comment by strasharo** [comment]
Your fluxion host doesn't have the fake DNS server defined, so you won't be able to resolve it from there, use a separate client connected to the fake wireles network.

**Comment by vladinko0** [comment]
Excuse me, maybe I was not detailed enough.
I am using two rtl8812au wifi adapters and I can successfuly create fake AP. On client machine I can connect on it. The problem is, that then I don' t get Captive portal, there is No Internet message.
I thought that this issue is caused the Server Not Found message in captive.gareway.lan message on hosting Kali machine. So I focused on this, if you have some suggestions regarding maybe webserver.

One more quetion. Do you know if even someone successed in Captive Portal Attack with this chipset?

**Comment by strasharo** [comment]
Driver is currently unstable:
https://github.com/ZerBea/hcxdumptool/issues/74#issuecomment-553430492
