### ISSUE TITLE
"can't" connect Huawei phones to the fake AP

### ISSUE THREAD

**Issue by jinglei207** [FluxionNetwork/fluxion#801]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

Sorry for my poor English.
I'm using the fluxion 5.9 and it works greatly. Every function worked until I met Huawei phones...
My Xiaomi phones and iPhones can connect to the fake AP and few seconds later, the captive.gateway will pop up.
But I'm having problems with Huawei phones.
This is what happens when a Huawei phone is trying to connect to the fake AP(picture).
I don't know what's the problem because I don't have a Huawei phone.
Anyone can help me?

#### Specs

![IMG_20191116_175920](https://user-images.githubusercontent.com/31416095/68996483-02e90480-089b-11ea-984d-3f37b7499edc.jpg)

**Comment by jinglei207** [comment]
Wireless adapter ralink 3070.
Linux 5.3

**Comment by jinglei207** [comment]
There are at least 5 Huawei phones trying to connect this WiFi. I kind of feel sorry for my neighbor 😂😂😂

**Comment by strasharo** [comment]
What do you exactly expect us to do, buy Huawei phones and test it for you?

**Comment by jinglei207** [comment]
> What do you exactly expect us to do, buy Huawei phones and test it for you?

No, I'm just saying that it doesn't work with Huawei phones. I also added a picture trying to figure out if it's a software's problem.

I don't think that a Huawei phone is necessary since the only thing it can test is connect to the fake AP.
