### ISSUE TITLE
Wlan0 is not found anymore.. (NEED HELP)

### ISSUE THREAD

**Issue by 3dlir** [FluxionNetwork/fluxion#803]
So i installed this script, from the lazy script.
Before i installed this script, i had no problems with wlan0.
Now all the tools/scripts cant detect my wlan0 device.
Also i see fluxwl0 is enabled instead of wlan0
Anybody got an fix? am new to this ^^

**Comment by cjb900** [comment]
It would help to know what OS you are using and if you have checked for any updates/upgrades. I can say that the way Fluxion works is that when using it it does switch your interface from wlanX to fluxwl0 but once you stop using fluxion it supposed to set it back to the regular wlanX. if it doesn't restarting the computer usually fixes that. if it still not working that would indicate something being corrupt or broken in what ever OS you are using.
