### ISSUE TITLE
how to run multiple fluxions?

### ISSUE THREAD

**Issue by jinglei207** [FluxionNetwork/fluxion#805]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Is there anyone know how to run more than one fluxion?
Right now I'm using VMware to run multiple attacks simultaneously, but it's really inconvenient.

**Comment by strasharo** [comment]
Run it inside docker containers.
