### ISSUE TITLE
Kali 5.2.0 and Awus 036ACH

### ISSUE THREAD

**Issue by indagator667** [FluxionNetwork/fluxion#807]
Hi folks!

I have Alfa AWUS036ACH adapter. In latest kali linux kernel 5.2.0, fluxion cannot work. Captive portal freeze and handshake not working. I tried another version drivers, but same things. Any idea?

**Comment by strasharo** [comment]
5.x kernels are a mess currently, a lot of different chipsets affected and there's no fix in any upstream distribution:
https://bugzilla.kernel.org/show_bug.cgi?id=202541#c102
Even simple injection fails.
