### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ggrswiss** [FluxionNetwork/fluxion#808]
Hello,

I'm using the last Kali Linux and i can't solve the problem with the missings
            [*] aircrack-ng...................................... OK.           
            [*] bc.......................................... Missing!           
            [*] awk.............................................. OK.           
            [*] curl............................................. OK.           
            [*] cowpatty.................................... Missing!           
            [*] dhcpd....................................... Missing!           
            [*] 7zr.............................................. OK.           
            [*] hostapd..................................... Missing!           
            [*] lighttpd.................................... Missing!           
            [*] iwconfig......................................... OK.           
            [*] macchanger....................................... OK.           
            [*] mdk3........................................ Missing!           
            [*] nmap............................................. OK.           
            [*] openssl.......................................... OK.           
            [*] php-cgi..................................... Missing!           
            [*] pyrit....................................... Missing!           
            [*] xterm............................................ OK.           
            [*] rfkill........................................... OK.           
            [*] unzip............................................ OK.           
            [*] route............................................ OK.           
            [*] fuser............................................ OK.           
            [*] killall.......................................... OK. 

I followed many tutorials related to this problem but it didn't work.
Could you help me ?

Thank you,

**Comment by crashorburn** [comment]
Type bash fluxion.sh -i or sudo bash fluxion.sh -i or type ./fluxion.sh -i

**Comment by ggrswiss** [comment]
Actually, i had a trouble with Kali Linux which was installed, i don't know what's happened...i had to reinstall it and now it works !

**Comment by airyeti** [comment]
Hello, the same issue here, but i need step by step answer, i am not familiar with commands and stuff, so i need all the commands to write and hit ENTER.

I already have fluxion, latest version, just downloaded through terminal, but it has 10 dependencies missing, writing ./fluxion.sh -i didn't help, it gives a failure, in the left corner, i think you guys are already familiar with it.
What to do now??? please HELP.

**Comment by BouregagYoucef** [comment]
write   
sudo ./fluxion.sh -i

**Comment by roshnirajak** [comment]
sudo ./fluxion.sh -i is not working for php-cgi
after trying is so many times php-cgi is still 'Missing'.

**Comment by cjb900** [comment]
@roshnirajak if you can't get fluxion to install php-cgi just install it manually.

**Comment by riadh402** [comment]
how  manually.
