### ISSUE TITLE
cannot find device "fluxwl0v"

### ISSUE THREAD

**Issue by MrFred17** [FluxionNetwork/fluxion#811]
I have an issue with fluxion.
Hash goes successfully, though after selecting the language interface for the captive portal, it says: cannot find device "fluxwl0v".
Thing is it worked perfectly the first time, though now it shows that message all the time and fails to work properly.
I've tried installing&uninstalling and also deleting the attacks.conf file but nothing seems to work.

Thank you!

![image](https://user-images.githubusercontent.com/57257280/71424082-03916980-2697-11ea-981b-64e50d961916.png)

**Comment by strasharo** [comment]
And we're supposed to guess what your setup is based on a crystall ball?
