### ISSUE TITLE
cannot find device "fluxwl0v"

### ISSUE THREAD

**Issue by MrFred17** [FluxionNetwork/fluxion#812]
I'm using a TP-LINK TL-WN821N w/300Mbps.
Hash goes successfully, though after selecting the language interface for the captive portal, it says: cannot find device "fluxwl0v".
Thing is it worked perfectly the first time, though now it shows that message all the time and fails to work properly.
I've tried uninstalling&installing and also deleting the attacks.conf file but nothing seems to work.
Thank you for the help!
![image](https://user-images.githubusercontent.com/57257280/71424590-9d5b1580-269b-11ea-94f4-39e7f80dec70.png)

**Comment by strasharo** [comment]
TL-WN821N has like 6 revisions with 3 different chipsets.

**Comment by MrFred17** [comment]
> TL-WN821N has like 6 revisions with 3 different chipsets.

hey, listen... I am not an expert in these kinds of stuff... I'm just trying to get some help here... instead of closing it all the time just tell me the exact info you need...
