### ISSUE TITLE
Captive portal Warning:  locale not supported by Xlib, locals set to C

### ISSUE THREAD

**Issue by jackz33** [FluxionNetwork/fluxion#815]
I’m getting error message on ver 6.1 When captive portal tries to start. Here it is below

Warning: locale not supported by Xlib, locale set to C
[*] Starting Captive Portal access point service...
Warning: locale not supported by Xlib, locals set to C

##### What is the current behaviour?

No

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
Alfa Atheros AR9271

**Comment by strasharo** [comment]
https://lmgtfy.com/?q=%22locale+not+supported+by+Xlib%2C+locale+set+to+C%22
