### ISSUE TITLE
loose intetnet when launching fluxion on the latest kali 2019.4

### ISSUE THREAD

**Issue by cjb900** [FluxionNetwork/fluxion#816]
#### Summary

I'm running the latest version of Kali (2019.4) from a live USB. when starting fluxion it instantly kills internet access and will not be able to install any of the missing dependencies. 
##### What is the current behaviour?

Internet connection crashes 
#### How to reproduce
run the latest version of kali 2019.4 and then start fluxion. you will loose internet connection

##### What do you think the expected behaviour should be?

You should not loose internet connection when lunching fluxion whether you have missing dependencies or not

**Comment by strasharo** [comment]
https://github.com/FluxionNetwork/fluxion/commit/a39b6c05a60fff9355bbc139d27a495a2a53300d

First you complain all of the time you want @usama7628674 fixes, then you complain you don't like the behaviour after they're merged. Can you finally decide what you want?
