### ISSUE TITLE
When I start Fluxion doesnt doesn't see my external wifi card

### ISSUE THREAD

**Issue by flu1234** [FluxionNetwork/fluxion#818]
|    Q        |  
|------------ | -----
| Version     | 6.4

#### Support Question
Hello Everyone,
Yesterday when I use Fluxion everything work fine. I was able to pick my wifi card. I try use Fluxion today Im not able to pick my wifi card from the list. Today when I first started the program it ask me if I wanted wanted to install a update. Now after I did the update, I can't seem to pick my wifi card like I did before. Did the update do something to it or is a fix for this problem?

Thanks you your time.

**Comment by strasharo** [comment]
Let me pick my crystal ball and guess what cad you have there.
