### ISSUE TITLE
Dependencies need to be updated.

### ISSUE THREAD

**Issue by MPX4132** [FluxionNetwork/fluxion#82]
https://github.com/FluxionNetwork/fluxion/blob/846380552a8135eb08ed75d0278317c7286ba9fd/fluxion.sh#L316

I don't think the following are being used in fluxion.sh anymore:
* strings
* unzip

**Comment by deltaxflux** [comment]
Let me check to confirm it

**Comment by MPX4132** [comment]
It looks like the updater is broken. I imagine this is where unzip was being used, what do you think?

**Comment by MPX4132** [comment]
To check what's using it, I ran
```
grep -rnw -E 'strings'
```
At fluxion's root directory.

**Comment by deltaxflux** [comment]
Yep confirmed both are not longer required
