### ISSUE TITLE
not create captive portal

### ISSUE THREAD

**Issue by zackfair1412** [FluxionNetwork/fluxion#823]
hello, i having this kind of issues with latest version of fluxion, it doesn't create captive portal. 

![image](https://user-images.githubusercontent.com/27601824/71777196-75db4580-2fd7-11ea-97f5-23a44a25918f.png)

here is my setup, i'm using alfa awus036nha

#### FLUXION Info
FLUXION V6.4

#### BASH Info 
GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k_htc
**Chipset:** Qualcomm Atheros Communications AR9271 802.11n
**Master Modes** Yes
**Injection Test:** No Answer...

#### XTerm Infos
**Version:** XTerm(351)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 4.19.0-kali4-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-2)) #1 SMP Debian 4.19.28-2kali1 (2019-03-18)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

is it cause by the pyrit? thanks

**Comment by strasharo** [comment]
Which version of Kali is that?

**Comment by zackfair1412** [comment]
> Which version of Kali is that?

Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

**Comment by jinglei207** [comment]
We

> Which version of Kali is that?

I also have the same problem, but I think it happens only on the 13 channel.

**Comment by zackfair1412** [comment]
> We
> 
> > Which version of Kali is that?
> 
> I also have the same problem, but I think it happens only on the 13 channel.
> All the wifi on the 13 channel don't start.

nope, it happen on all channel for me

**Comment by hanbing88** [comment]
i have the same problem.

**Comment by hanbing88** [comment]
i have the same problem.

**Comment by jinglei207** [comment]
have you tied to update kali?
apt-get update
apt-get upgrade

**Comment by strasharo** [comment]
I asked what's the version of Kali, not what's the kernel.
