### ISSUE TITLE
Unable to start captive portal, returning

### ISSUE THREAD

**Issue by snow022** [FluxionNetwork/fluxion#824]
|    Q        |   A
|------------ | -----
| Version     | 6.4.x

#### Support Question

How can I fix the error below:

![image](https://user-images.githubusercontent.com/59530394/71780315-0166cd80-2ffc-11ea-8940-358f79e50c89.png)

#### Specs
Usage ./scripts/diagnostics [wireless_interface]Usage ./scripts/diagnostics [wireless_interface]

**Comment by jinglei207** [comment]
go back and reselect your adapter. works for me.

**Comment by snow022** [comment]
I tried it already but it didn't work. I also notice that wlan0 was changed to fluxwl0, when capturing handshake is it normal?

**Comment by jinglei207** [comment]
have you tied to update kali?
apt-get update
apt-get upgrade

**Comment by jinglei207** [comment]
i have an adapter that works only for one thing, either as jammer or fake AP, can't use it for both. Maybe that's the problem. is this your first time using this adapter?

**Comment by snow022** [comment]
Yes it is my first time using it. I will try different adapter. Thanks. :)
