### ISSUE TITLE
Fluxion jammer service won't start if "Restore Attack" is selected.

### ISSUE THREAD

**Issue by jinglei207** [FluxionNetwork/fluxion#826]
#### Summary

i ran the fluxion for the first time and it remembered all the attack mode so the next time i can directly select "restore attack."
But the problem is that if i close the fluxion and rerun ``./fluxion.s,` and select "Restore Attack", "Fluxion jammer service" won't start. I have to select "reset attack" and reset all the settings.

##### What is the current behaviour?

Fluxion jammer service won't start 
#### How to reproduce
select `[1] Captive Portal Creates an "evil twin" access point.` and then attack an wifi.
close fluxion
restart  `./fluxion.sh`
select `[1] Captive Portal Creates an "evil twin" access point.` and then attack an wifi.
after selected a wifi, the next step select "restore attack"
and everything starts except the jammer.

##### If the current behaviour is a bug, please provide the steps to reproduce it.

select `[1] Captive Portal Creates an "evil twin" access point.` and then attack a wifi.
close fluxion
restart  `./fluxion.sh`
select `[1] Captive Portal Creates an "evil twin" access point.` and can a wifi.
after selected a wifi, the next step select "restore attack"
and everything starts except deauth.

##### What do you think the expected behaviour should be?

fluxion jammer service starts with fake AP
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V6.4

#### BASH Info 
GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy2
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(350)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                       

#### System Info
**Chipset:** Linux version 5.3.0-kali2-amd64 (devel@kali.org) (gcc version 9.2.1 20191109 (Debian 9.2.1-19)) #1 SMP Debian 5.3.9-3kali1 (2019-11-20)

#### Chipset
Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode

**Comment by xpz3** [comment]
https://github.com/xpz3/fluxion/commit/7494bbb73fbdd42d52493d964bfd248c49db4feb
The above commit on forked version fixes this problem

**Comment by strasharo** [comment]
Create a PR.
