### ISSUE TITLE
everything works cool but...

### ISSUE THREAD

**Issue by azamet90** [FluxionNetwork/fluxion#827]
is it not posible to make the networks dissappear like some tools? i mean if the access point the real one dissappears will be nice or not?

**Comment by jinglei207** [comment]
What tools can make the real one disappear?

**Comment by azamet90** [comment]
> What tools can make the real one disappear?

can i mention the tool name here? is it okay?

**Comment by strasharo** [comment]
Next bullshit issue will bring you a ban.
