### ISSUE TITLE
fluxion freezes after few hops (hostapd problem)

### ISSUE THREAD

**Issue by jinglei207** [FluxionNetwork/fluxion#828]
#### Summary

https://github.com/FluxionNetwork/fluxion/issues/825 this wass the problem which i had before(same problem), resolved it by updating kali. But the problem now I'm having is that after few hops, the same problem reappears.
i ran in debug mode and looked like that hostapd didn't support 12 and 13 channel(same problem).
![Screenshot_2020-01-06_20-37-16](https://user-images.githubusercontent.com/31416095/71843964-620e0d00-30c5-11ea-9619-c7788bce92d0.png)

##### What is the current behaviour?

unable to to create fake APs on 12 and 13 channels

#### How to reproduce
1 router is set to `auto`
run an attack to an AP, after it hops on channel 12 or 13, hostapd stops functioning. 
##### What do you think the expected behaviour should be?

attack APs without problems
##### If this is a feature request, what is the motivation or use case for the added feature?
**1. I want to know if anyone knows what's the problem and how to solve it.**

**2 How can i use a `indepented` adapter as  AP on a fixed channel? this way i can easily solve the problem. But right now the AP runs on the same channel as the real AP even with a dedicated adapter.**

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
FLUXION Info

FLUXION V6.4
BASH Info

GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /usr/bin/bash
Interface (wlan0) Info

Device: phy2
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
Master Modes Yes
Injection Test: Injection is working!
XTerm Infos

Version: XTerm(350)
Path: /usr/bin/xterm
Test: XServer/XTerm success!
HostAPD Info

hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen j@w1.fi and contributors
Path: /usr/sbin/hostapd
Aircrack-ng Info

EXIT
Aircrack-ng 1.5.2 - (C) 2006-2018 Thomas d'Otreppe
https://www.aircrack-ng.org
Pyrit Info

Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
Scapy Version: 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.
System Info

Chipset: Linux version 5.3.0-kali2-amd64 (devel@kali.org) (gcc version 9.2.1 20191109 (Debian 9.2.1-19)) #1 SMP Debian 5.3.9-3kali1 (2019-11-20)
Chipset

Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode

**Comment by jinglei207** [comment]
i have also tried with other adapters, so, i don't think this is a driver problem.
maybe is that hostapd is created in the US (not sure), but nobody in the US uses channel 12 and 13?

**Comment by jinglei207** [comment]
More problem found. Mdk4 And aireplay-ng can't deauth 12 and 13 channel even though they output ”deauthenticating”.

 The same problem as hostapd, can make them work for few minutes if I reboot PC.

**Comment by strasharo** [comment]
Your adapter region restricts you from using these channels:
iw reg get
iw list | grep MHz

**Comment by jinglei207** [comment]
> Your adapter region restricts you from using these channels:
> iw reg get
> iw list | grep MHz

I live in Italy so it's normal, totally legal to use 12 and 13 channels. Maybe because I have some settings that are in "US region"? 

Works for some minutes tough.

**Comment by jinglei207** [comment]
> Your adapter region restricts you from using these channels:
> iw reg get
> iw list | grep MHz

I run the fommand `iw reg get` and noticed that the country is not set! I run the command `iw reg set IT` and now it seems working without problem!

Hope you can add this suggestion in README, this problem seems quite common for those from EU.

Thank you!!!

**Comment by jinglei207** [comment]
> Your adapter region restricts you from using these channels:
> iw reg get
> iw list | grep MHz

I run the fommand `iw reg get` and noticed that the country is not set! I run the command `iw reg set IT` and now it seems working without problem!

Hope you can add this suggestion in README, this problem seems quite common for those from EU.
How to set it permanently: https://askubuntu.com/questions/503416/wifi-country-changed-to-us-how-do-i-change-it-back
Thank you!!!

**Comment by strasharo** [comment]
You can use this to patch your regdom restrictions:
https://github.com/strasharo/wifi_channel_unlocking

Settings are found in this file, I've patched the 00 country (not set) by default:
https://github.com/strasharo/wifi_channel_unlocking/blob/master/wireless-regdb/db.txt

**Comment by jinglei207** [comment]
> You can use this to patch your regdom restrictions:
> https://github.com/strasharo/wifi_channel_unlocking
> 
> Settings are found in this file, I've patched the 00 country (not set) by default:
> https://github.com/strasharo/wifi_channel_unlocking/blob/master/wireless-regdb/db.txt

I have to mention that if run or hostapd mdk4 manually, they work. They stops working after I run fluxion. There might be some codes from fluxion that change some wifi related settings?
