### ISSUE TITLE
BLANK SCREEN

### ISSUE THREAD

**Issue by anshmishra** [FluxionNetwork/fluxion#829]
#### Summary
nothing happens on running the script (Kali 2019.4 on Raspberry Pi 3 Model B)

##### What is the current behaviour?
upon running script command, nothing happens. Closing the script shows cleanup screen

![192 168 29 88_1 (root's X desktop (kali_1)) - VNC Viewer 08-Jan-20 9_31_53 AM](https://user-images.githubusercontent.com/35838695/71949624-38a2cd80-31fa-11ea-9ae6-dc62e2e5e270.png)

##### If the current behaviour is a bug, please provide the steps to reproduce it.
cd fluxion
./fluxion.sh
(after this, nothing happens)

upon closing, this screen appears
![192 168 29 88_1 (root's X desktop (kali_1)) - VNC Viewer 08-Jan-20 9_33_17 AM](https://user-images.githubusercontent.com/35838695/71949655-5b34e680-31fa-11ea-950d-33679b5cda0c.png)

##### What do you think the expected behaviour should be?
It should show language selecting option and script should start

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by anshmishra** [comment]
apolgy for bad english

**Comment by strasharo** [comment]
No diagnostics information provided.
