### ISSUE TITLE
Fluxion not starting with Iptables installed

### ISSUE THREAD

**Issue by ramondunker** [FluxionNetwork/fluxion#831]
|    Q        |   A
|------------ | -----
| Version     | 6.4

#### Support Question
When I have iptables installed I can't run fluxion. It just won't start. When I invoke Ctrl-C it shuts down and shows clearing etc etc.

When I uninstall iptables the handshake snooper works, but the captive portal doesn't!

#### FLUXION Info
FLUXION V6.4

#### BASH Info 
GNU bash, versie 5.0.11(1)-release (aarch64-unknown-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
De licentie is GPLv3+: GNU GPL versie 3 of later.
Zie http://gnu.org/licenses/gpl.html voor de volledige tekst.

Dit is vrije software; u mag het vrijelijk wijzigen en verder verspreiden.
Er is GEEN GARANTIE, voor zover de wet dit toestaat.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy3
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(351)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                               

#### System Info
**Chipset:** Linux version 4.19.81-Re4son-v8+ (root@kali-pi-dev-v8) (gcc version 8.2.0 (Debian 8.2.0-12)) #1 SMP PREEMPT Wed Nov 6 03:33:03 UTC 2019

#### Chipset
Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

What am I doing wrong?

**Comment by strasharo** [comment]
Iptables is needed for NAT. On startup it's running "iptables-save" in order to save the current rules and restore them later. If for some reason iptables-save hangs, this would hang the whole script.
