### ISSUE TITLE
No access points or clients?

### ISSUE THREAD

**Issue by maxiedaniels** [FluxionNetwork/fluxion#832]
I'm using the latest Kali Linux, fresh install, with a Awus036neh wifi usb card. I run a handshake capture with Fluxion, and the airmon-looking window pops up, but no access points.

Other apps work normally - wifite for example shows tons of access points.

**Comment by jinglei207** [comment]
Read the wiki page.

**Comment by strasharo** [comment]
Works fine here. Check your environment and update Kali to the latest packages.
