### ISSUE TITLE
Fluxion 6 (Update 4) can't Install Dependencies

### ISSUE THREAD

**Issue by airyeti** [FluxionNetwork/fluxion#833]
Hello, i need help solving a problem.

The problem is exactly like in this link below

https://github.com/FluxionNetwork/fluxion/issues/808

but the thing is that reading from the comments it didn't help me a bit.

No point installing Kali again just to believe that it will be working now.

Please Help solving this problem.

**Comment by strasharo** [comment]
Just install them manually, the fact that there's something wrong with your install is not a fluxion issue.

**Comment by airyeti** [comment]
what can be wrong with my installer, i cloned through Kali/Terminal just like anybody else, but when i try to make the install for dependencies, it gives some errors saying that the missing dependencies aren't anywhere to be found, they were moved, obsolete and stuff... i never said anything about Fluxion having problems, i'm only saying that the dependencies are missing from where Fluxion needs to download them, that's all. why did you close this topic, my problem isn't solved, is this how you people help solving the problems around? how to install them manually? you didn't help at all. if i could find a place to show how to do that i wouldn't have come here to bother you in the first place. it was a mistake coming here and make an account for nothing, some community this is.
