### ISSUE TITLE
Help  how to make fluxion only use wlan1 and not wlan0?

### ISSUE THREAD

**Issue by xm00ds** [FluxionNetwork/fluxion#835]
install kali on a raspberry pi version version 2 rev 9, I have 2 wifi cards, the internal and an external tp-link 722, the problem you have is that by the internal card I am connecting ssh to the raspberry to be able to use fluxion , the problem is that I don't know how to fix the code so that it doesn't disable all the network cards when it asks to select the interface I want the fluxion not to touch the other card because by it I keep my access to ssh or vnc

**Comment by strasharo** [comment]
Just don't select that interface and it won't touch it.

**Comment by xm00ds** [comment]
Dear friend, the erratite problem in that before selecting the interfaces, the code has all the interfaces buried even if I am connected to the internet by wlan0 disconnects it, I need help to modify the code so that it only takes the wlan1 and does not knock the wlan0 that is the the interena card

**Comment by xm00ds** [comment]
that is, when I start the fluxion, he reads and makes a list of the interfaces after the language is selected, at that moment if you look at the network administrator, you will want to make the modification so that it only does so with wlan1 and Do not even turn to see wlan0 so I can stay connected to the Internet and be able to control the raspberry pi by ssh or VNC do you understand me?
