### ISSUE TITLE
Fluxion can't find the /tmp/fluxspace/clients.txt

### ISSUE THREAD

**Issue by 0plan** [FluxionNetwork/fluxion#849]
#### Summary

Fluxion in the current master version can't find the /tmp/fluxspace/clients.txt file, but the file exists and has content. the problems occurs if i start the final attack with hostapd.

the errormsg is: 

cat: /tmp/fluxspace/clients.txt: File or Directory not found!

#### How to reproduce

install fluxion with kali 2020.1.
capture a handshake and start the attack.
a few seconds later the errormessage occurs 

![Bildschirmfoto vom 2020-02-23 17-39-57](https://user-images.githubusercontent.com/51053959/75115950-e7dd1c00-5663-11ea-818b-cb9349ce610e.png)

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### FLUXION Info
FLUXION V6.4

#### BASH Info 
GNU bash, Version 5.0.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
Lizenz GPLv3+: GNU GPL Version 3 oder jünger <http://gnu.org/licenses/gpl.html>

Dies ist freie Software.  Sie darf verändert und verteilt werden.
Es wird keine Garantie gewährt, soweit das Gesetz es zulässt.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** rtl8723be
**Chipset:** Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(353)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.10-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 5.4.0-kali3-amd64 (devel@kali.org) (gcc version 9.2.1 20200104 (Debian 9.2.1-22)) #1 SMP Debian 5.4.13-1kali1 (2020-01-20)

#### Chipset
Chipset: rtl8723be
Chipset is not in list

#### Expected behavior

start fluxion attack and offer my own AP with the victim SSID.

**Comment by strasharo** [comment]
Adapter not supported.

**Comment by ubilight0066** [comment]
sorry I just had the same problem and my adapter is supported 3070, is it some kind of file system permission problem?
