### ISSUE TITLE
Unable to Install Fluxion in Kali Linux

### ISSUE THREAD

**Issue by Anushanth** [FluxionNetwork/fluxion#85]
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

----

### What is the current behavior?
-> Unable to Install Fluxion in Kali Linux

---

#### If the current behavior is a bug, please provide the steps to reproduce.
-> Check the Screenshot - http://imgur.com/a/833Ja

Unable to Install Fluxion in Kali Linux

Error Code: ./install.sh: line 234: [: too many arguments

---

#### Linux version:
Linux version 4.9.0-kali3-amd64 (devel@kali.org) (gcc version 6.3.0 20170321 (Debian 6.3.0-11) ) #1 SMP Debian 4.9.18-1kali1 (2017-04-04)

**Comment by MPX4132** [comment]
Please use the latest version https://github.com/FluxionNetwork/fluxion/archive/master.zip
If you continue to have problems, come back here.
