### ISSUE TITLE
Error of losing Wifi

### ISSUE THREAD

**Issue by JunPham** [FluxionNetwork/fluxion#851]
I use Kali Linux 2020.1
When I open Fluxion specifically in the channel selection step. I lost wwifi and when I turned off the terminal, the wifi returned to normal

**Comment by strasharo** [comment]
And we must use a crystal ball to guess your setup, right?

**Comment by JunPham** [comment]
I did not set anything. All I do is install potassium and load fluxion. Even when I use usb live Kali, it still does.
So I have to tell you what settings.
