### ISSUE TITLE
请问我的fluxion ap dns service的IP是192.169.254.1需要怎样修改呢？谢谢

### ISSUE THREAD

**Issue by gakkiAgakki** [FluxionNetwork/fluxion#854]

**Comment by strasharo** [comment]
![image](https://user-images.githubusercontent.com/3337997/76689602-30bf3980-6640-11ea-9cc0-ef806a9bb133.png)

**Comment by gakkiAgakki** [comment]
How to solve this situation?  Thank you

**Comment by gakkiAgakki** [comment]
![QQ截图20200315160521](https://user-images.githubusercontent.com/45597516/76697849-3a47b080-66d7-11ea-8594-76bca3c95fec.png)
How to solve this situation?  Thank you

**Comment by gakkiAgakki** [comment]
![QQ截图20200315160521](https://user-images.githubusercontent.com/45597516/76697875-59464280-66d7-11ea-85bf-6e4e8354f3d5.png)
How to solve this situation?  Thank you

**Comment by xpz3** [comment]
Whats wrong with this situation? Can't see any problem here
