### ISSUE TITLE
大神，新版本的fluxion，总是卡在“开始建立钓鱼热点AP”的界面？

### ISSUE THREAD

**Issue by tylzqiqi** [FluxionNetwork/fluxion#855]
我百度 了一下，发现有很多相同的问题，是什么原因呢？望大神尽快解决，或答复，谢谢！

**Comment by cjb900** [comment]
What do you expect us to do. Magically guess your setup. It would help to know what OS you are using and what wife adapter you are using and the chipset it has. 
This issue is usually caused by the wife adapter you are using not supporting AP mode

**Comment by tylzqiqi** [comment]
意思是我的其中一个网卡不支持是吗？

> What do you expect us to do. Magically guess your setup. It would help to know what OS you are using and what wife adapter you are using and the chipset it has.
> This issue is usually caused by the wife adapter you are using not supporting AP mode

意思是我的其中一个网卡不支持？

**Comment by cjb900** [comment]
Well you still haven't answered any of my questions. So I have no idea if your network card is properly supported or not for WiFi hacking. You also still haven't told us what OS you are using. like if you are using Kali Linux or some other OS. So as I said before are we supposed to just magically guess what your setup is

**Comment by tylzqiqi** [comment]
> Well you still haven't answered any of my questions. So I have no idea if your network card is properly supported or not for WiFi hacking. You also still haven't told us what OS you are using. like if you are using Kali Linux or some other OS. So as I said before are we supposed to just magically guess what your setup is

我是在wifislax-X64-1.1中下载新的版本后运行的，之前在ubuntu中也遇到过相同的问题。

**Comment by cjb900** [comment]
Well Fluxion is not designed for Ubuntu out of the box. It takes a lot of additional setup and tweaking to get it to properly work and wouldn't be recommended. Wifislax would be a better option, but you still haven't mentioned what WiFi adapter you are using. So I still can't say what is causing your issue. 

Just a guess but are you using the built in wifi adapter in your computer?

**Comment by tylzqiqi** [comment]
> Well Fluxion is not designed for Ubuntu out of the box. It takes a lot of additional setup and tweaking to get it to properly work and wouldn't be recommended. Wifislax would be a better option, but you still haven't mentioned what WiFi adapter you are using. So I still can't say what is causing your issue.
> 
> Just a guess but are you using the built in wifi adapter in your computer?

其中一个是内置的intel 6205网卡，一个是外置的拓实N815网卡，N815应该是8189芯片，

**Comment by tylzqiqi** [comment]
不好意思，回复错了，N815是3072芯片

**Comment by tylzqiqi** [comment]
> > Just a guess but are you using the built in wifi adapter in your computer?
> 
> 其中一个是内置的intel 6205网卡，一个是外置的拓实N815网卡，N815应该是8189芯片，不了

> Well Fluxion is not designed for Ubuntu out of the box. It takes a lot of additional setup and tweaking to get it to properly work and wouldn't be recommended. Wifislax would be a better option, but you still haven't mentioned what WiFi adapter you are using. So I still can't say what is causing your issue.
> 
> Just a guess but are you using the built in wifi adapter in your computer?

其中一个是内置的intel 6205网卡，一个是外置的拓实N815网卡，N815应该是3072芯片

**Comment by xpz3** [comment]
The Intel 6205 chipset should work. Before running fluxion run the following command in a terminal
airmon-ng check kill
Then open fluxion and select 6205 chipset. Then select skip on target tracking menu and try running the captive portal. It should work. Don't forget to run the command before running fluxion

**Comment by tylzqiqi** [comment]
> The Intel 6205 chipset should work. Before running fluxion run the following command in a terminal
> airmon-ng check kill
> Then open fluxion and select 6205 chipset. Then select skip on target tracking menu and try running the captive portal. It should work. Don't forget to run the command before running fluxion

谢谢，有空我再试试
