### ISSUE TITLE
I used Manjaro 19.0, and at first it worked, but after a while, something went wrong, and I don't know what went wrong.

### ISSUE THREAD

**Issue by tylzqiqi** [FluxionNetwork/fluxion#856]
- 
![微信图片_20200318162140](https://user-images.githubusercontent.com/58105231/76940829-ea1a5980-6935-11ea-8f99-b554b9ed6a46.png)

|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by xpz3** [comment]
Did you run the command airmon-ng check kill before running fluxion?

**Comment by tylzqiqi** [comment]
> Did you run the command airmon-ng check kill before running fluxion?

I tried again, but it didn't work, and after a few minutes of running, the same thing happened

**Comment by xpz3** [comment]
People facing this issue solved it by running the command i told you. It could also be a problem with your wireless adapter or its driver.

**Comment by tylzqiqi** [comment]
> People facing this issue solved it by running the command i told you. It could also be a problem with your wireless adapter or its driver.
> Also if you are using a virtual machine try without one
I ran it like you said, and it didn't work, Is there no other way?

**Comment by tylzqiqi** [comment]
> People facing this issue solved it by running the command i told you. It could also be a problem with your wireless adapter or its driver.
> Also if you are using a virtual machine try without one

I didn't use a virtual machine. I installed it on a physical machine

**Comment by xpz3** [comment]
Try another adapter

**Comment by tylzqiqi** [comment]
> Try another adapter

 Okay. Thank you

**Comment by xpz3** [comment]
When this happens open a terminal and run iwconfig and paste the output if you can
