### ISSUE TITLE
Weird problem

### ISSUE THREAD

**Issue by masikszabi** [FluxionNetwork/fluxion#857]
Hi,

I was trying to test Fluxion on my wireless modem (provieded by Telekom) the router type is SAGEMCOM fast 5655v2 with both 2.4ghz and 5ghz is on, but the fluxion doesn't detect any of them. In fact, my neighbor also have Telekom, I can see 3 of them on the network list (even with airodump-ng) but when using fluxion it detects every wifi around me except the Telekom SAGEMCOM fast 5655v2. What could be the issue? (I can connect to the network, working perfectly, but it doesn't show up during the scan) 

Thank you

**Comment by strasharo** [comment]
And I should pull out a crystal ball and guess your setup?

**Comment by masikszabi** [comment]
cheers m8
