### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by masikszabi** [FluxionNetwork/fluxion#858]
|    Q        |   A
|------------ | -----
| Version     | 6.5

#### Support Question

Hi,

I was trying to test Fluxion on my wireless modem (provieded by Telekom) the router type is SAGEMCOM fast 5655v2 with both 2.4ghz and 5ghz is on, but the fluxion doesn't detect any of them. In fact, my neighbor also have Telekom, I can see 3 of them on the network list (even with airodump-ng) but when using fluxion it detects every wifi around me except the Telekom SAGEMCOM fast 5655v2. What could be the issue? (I can connect to the network, working perfectly, but it doesn't show up during the scan)

Sorry for the previously missing specs
Thank you

#### FLUXION Info
FLUXION V6.5
 
 
#### BASH Info
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash
 
 
#### Interface (wlan1) Info
**Device**: phy1
**Driver:** ath9k_htc
**Chipset:** Qualcomm Atheros Communications AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!
 
 
#### XTerm Infos
**Version:** XTerm(353)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!
 
 
#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/bin/hostapd
 
 
#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org
 
 
#### Pyrit Info
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.3.3
 
#### System Info
**Chipset:** Linux version 5.5.8-1-MANJARO (builder@216fb1516504) (gcc version 9.2.1 20200130 (Arch Linux 9.2.1+20200130-2)) #1 SMP PREEMPT Thu Mar 5 20:29:51 UTC 2020
 
#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by xpz3** [comment]
Try running airodump outside of airgeddon and see if it fetches your ap or not

**Comment by masikszabi** [comment]
Yes, it detects all of them (3) with attached hotspots as well as I mentioned before. But when I'm using Handshake Snooper, those are the only what's missing from the list. The rest, like TP-LINK's, Tenda's, etc.. remains, that's why I don't get it.

**Comment by masikszabi** [comment]
> 
> 
> Try running airodump outside of airgeddon and see if it fetches your ap or not

Yes, it detects three of them, but when I'm using Handshake Snooper, all of them are missing. The rest is still there. That's why I don't understand

**Comment by xpz3** [comment]
Do you mean while exploring for targets, your AP is missing? If yes then open fluxion.sh and goto line number 1101 and edit airodump parameters and try again.

**Comment by masikszabi** [comment]
> 
> 
> Do you mean while exploring for targets, your AP is missing? If yes then open fluxion.sh and goto line number 1101 and edit airodump parameters and try again.

Exactly. 
https://imgur.com/a7QGgpF

I'm looking at the line in the script but I'm not exactly sure what should I change, I got parameters like --channel, --band, etc..

**Comment by masikszabi** [comment]
and these are the settings on my router 
https://imgur.com/HvR3rn2

**Comment by xpz3** [comment]
airodump-ng -w \"$FLUXIONWorkspacePath/dump\" $1" 2> $FLUXIONOutputDevice; then
Change like this

**Comment by masikszabi** [comment]
> 
> 
> airodump-ng -w "$FLUXIONWorkspacePath/dump" $1" 2> $FLUXIONOutputDevice; then
> Change like this
I've changed the line. Now I got a new problem 

[*] Starting scanner, please wait...
[*] Five seconds after the target AP appears, close the FLUXION Scanner (ctrl+c).
xterm: bad command line option "-e"

**Comment by masikszabi** [comment]
> 
> 
> airodump-ng -w "$FLUXIONWorkspacePath/dump" $1" 2> $FLUXIONOutputDevice; then
> Change like this
I've changed the line. Now I got a new problem 

[*] Starting scanner, please wait...
[*] Five seconds after the target AP appears, close the FLUXION Scanner (ctrl+c).
xterm: bad command line option "-e"

**Comment by xpz3** [comment]
You might have missed quotes. Dunno

**Comment by masikszabi** [comment]
> 
> 
> You might have missed quotes. Dunno

You're right, first I've just commented out the original line, after it got removed everythings perfect.
Thank you xpz3, you're a star! 🥇
