### ISSUE TITLE
Found Hashes but AP does not start. Nothing pops up on any of my devices. Please help!

### ISSUE THREAD

**Issue by warrior14mmo** [FluxionNetwork/fluxion#859]
Hello I am new in this, but I have a deep interest in this subject. I was able to find hashes but when I proceed to Captive Portal nothing starts up on any of my devices. And I can not get connected to the fake Wifi on my iPhone nor mac.
please help

**Comment by strasharo** [comment]
Sure, let me pull out the crystal ball and guess your setup.

**Comment by warrior14mmo** [comment]
Hardware: Macbook Pro 13inch Retina
Linux: Kali Linux Vmware 64-bit 2020.1
Wifi Adapter: Panda PAU05 & Panda PAU06
Software: Fluxion 6.5

**Comment by warrior14mmo** [comment]
What screenshots do you need I will send
