### ISSUE TITLE
Cannot get past interface/AP menu

### ISSUE THREAD

**Issue by kirby193** [FluxionNetwork/fluxion#86]
###Feature or Bug:
Bug

###What is the current behavior?
Error occurs when attempting to select wireless interface
When wireless is enabled (airmon-ng stop wlan0mon), it detects the card, though selecting it tells me its in use and to run export FLUXIONDropnet=1. Doing so does nothing upon the rerunning of fluxion.

When wireless is disabled (airmon-ng start [interface]), it does not give me an option to choose a card, instead putting me in the scan for AP menu, upon doing so returns none and says card may not be supported.
Note that killing network-manager (service network-manager stop) returns the same result as above.

###If the current behavior is a bug, please provide the steps to reproduce.
Wireless enabled (Currently connected to a network): http://imgur.com/5qjbgn3l.png
In the above image, my card is given as an option to choose. Attempting so gives me
http://imgur.com/ry7FgUml.png
In which running it and rerunning fluxion gives me the same error.
Wireless disabled (airmon-ng start interface): http://imgur.com/jUX2wZ8l.png
In which I am not given a card selection and am given this menu instead.

###What is the expected behavior?
I would assume the expected behavior is not being stuck in this menu.

###Specs

###Wireless adapter:
Ralink RT2800 / Firmware rt2870.bin / Version 2.3.0    Installed with apt install firmware-ralink
Followed from here: https://wiki.debian.org/rt2800usb

###Does it support injection?

ioctl(SIOCSIWMODE) failed: Device or resource busy
00:56:57  Trying broadcast probe requests...
00:56:57  Injection is working!
00:56:59  Found 3 APs

00:56:59  Trying directed probe requests...
00:56:59  myapmacaddress- channel: 1 - 'myapname'
00:56:59  Ping (min/avg/max): 2.939ms/14.570ms/28.745ms Power: -67.27
00:56:59  30/30: 100%
And two other APs

###Fluxion version:

		FLUXIONOnlineInfo=("version=?\n" "revision=?\n")
		FLUXIONOnlineRevision=$(echo "${FLUXIONOnlineInfo[@]}" | awk -F= 'tolower($1)~/revision/{print $2}')
				echo -ne $CRed"            New revision found! "$CYel

I know that it says "New revision found", however this is a fresh git clone of about 5 minutes before writing this (I redownloaded to make sure it wasn't an issue with my original download). Running fluxion tells me that it is Fluxion 3 version 1.

###Linux version:
Linux version 4.11.0-1-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.11.6-1 (2017-06-19)

**Comment by deltaxflux** [comment]
I can't reproduce this issue.
