### ISSUE TITLE
Found Hashes but AP does not start. Nothing pops up on any of my devices. Please help!

### ISSUE THREAD

**Issue by warrior14mmo** [FluxionNetwork/fluxion#860]
Found Hashes with pyrit and cowpatty both but Evilt twin does not start neither on my mac or iPhone.
On my mac I do not get disconnected at all. On iPhone I do get disconnected but I can't connect to the fake one.

Hardware: Macbook Pro 13inch Retina
Linux: Kali Linux Vmware 64-bit 2020.1
Wifi Adapter: Panda PAU05 & Panda PAU06
Software: Fluxion 6.5

What screenshots do you need?

Run the diagnostic script
----------------------------
#### FLUXION Info
FLUXION V6.5

#### BASH Info 
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy1
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT5372
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(353)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                                         

#### System Info
**Chipset:** Linux version 5.4.0-kali4-amd64 (devel@kali.org) (gcc version 9.2.1 20200203 (Debian 9.2.1-28)) #1 SMP Debian 5.4.19-1kali1 (2020-02-17)

#### Chipset
Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode

**Comment by xpz3** [comment]
Have you tried airmon-ng check kill before starting fluxion?
Show screenshot of all xterm windows while running the attack. Also join discord server for easier communication.
https://discord.gg/G43gptk

**Comment by warrior14mmo** [comment]
did airmon-ng check kill. Kiled 2 processes but still no luck
My iPhone does not connect to fake wifi automatically, when I try to do it manually it says: Unable to connect to "XYZ"

Attaching the screenshots 
---------------------------------------------
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/62561077/77544088-fff1c680-6ec1-11ea-936b-1bda7f08f799.png">
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/62561077/77544103-04b67a80-6ec2-11ea-8bbc-ee55cb7bbd1a.png">

**Comment by xpz3** [comment]
This issue was solved through discord yesterday
