### ISSUE TITLE
The fluxwl0v device not found issue in the latest FLUXION.

### ISSUE THREAD

**Issue by adityacharate** [FluxionNetwork/fluxion#864]
#### FLUXION Info
FLUXION V6.5

#### BASH Info 
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlx60e327171fb8) Info 
**Device**: phy1
**Driver:** ath9k_htc
**Chipset:** Atheros Communications, Inc. AR9271 802.11n
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(330)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 5.3.0-46-generic (buildd@lcy01-amd64-013) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

The above diagnostic contain my system information. As we know Fluxion has two modes (primiraly). Each time when I start any attack it create a wifi interface named 'fluxwl0v'. 
![Screenshot from 2020-04-03 09-15-02](https://user-images.githubusercontent.com/63085087/78322422-4dd69080-758c-11ea-835a-f6cb73958db2.png)
![Screenshot from 2020-04-03 09-17-27](https://user-images.githubusercontent.com/63085087/78322433-54650800-758c-11ea-9f97-18b60bc691fe.png)
![Screenshot from 2020-04-03 09-18-05](https://user-images.githubusercontent.com/63085087/78322446-59c25280-758c-11ea-9412-3f684d4d2dc8.png)

**Comment by cjb900** [comment]
well first off you are running fluxion from a none Linux hacking distro. so we can't guarantee it will work. Others that have used other distors that are not dedicated for hacking like Kali or Parrot OS usually have to make some modification to the OS to get fluxion to work properly. This might help https://github.com/FluxionNetwork/fluxion/issues/792 but if not you may just be better off using a dedicated hacking OS that has the proper settings for wifi hacking like Kali or Parrot OS

**Comment by xpz3** [comment]
Restart your pc
Run airmon-ng check kill
Start fluxion

While running fluxion it creates two virtual interfaces. One should be in master mode and the other one in monitor mode. Then it should work.

**Comment by strasharo** [comment]
One more issue like this and I'm going to return the automatic kill functionality.

**Comment by xpz3** [comment]
Im not 100% sure, but i think that killing of processes is needed for older versions of NetworkManagers only. But it's hard to ask every user regarding their version. So it's better to kill processes and restart them later after the attack. I don't think every user is going through wiki and use FLUXIONWIKillProcesses. They just open an issue and tell it's not working.
