### ISSUE TITLE
Pyrit do not instal

### ISSUE THREAD

**Issue by pierredias** [FluxionNetwork/fluxion#866]
#### Summary

When install  flexion, do not install pyrit, and without pyrit the fluxion do not launch. 
 What is the current behaviour?
Even if install from git the pyrit its not recognised 

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by cjb900** [comment]
I believe you issue is that pyrit is no longer available from the default kali repository. you will need to install it from here https://github.com/JPaulMora/Pyrit

**Comment by xpz3** [comment]
http://kali.download/kali/pool/main/p/pyrit/
Download pyrit deb file from link above. Choose the right arch while downloading. Then run apt install ./filename.deb
