### ISSUE TITLE
Problem with hostapd

### ISSUE THREAD

**Issue by heils** [FluxionNetwork/fluxion#867]
#### Summary
I'm creating the fake ap but I cant connect to it, the hostapd window says this every time I try to connect to the fake ap:
"Authenticated"
"Station sent an invalid asociation request"

##### What is the current behaviour?
Not working

#### How to reproduce
Not really sure

##### If the current behaviour is a bug, please provide the steps to reproduce it.
Not sure if its a bug

##### What do you think the expected behaviour should be?
Connect to the ap

##### Specs
Usage ./script/diagnostics [wireless-interface]

#### Expected behavior
Connect to the fake ap

**Comment by xpz3** [comment]
Where's the diagnostics report bro? Which os? Your chipset. Etc...?
