### ISSUE TITLE
cannot run fluxion no pyrit on kali 2020

### ISSUE THREAD

**Issue by bricco1981** [FluxionNetwork/fluxion#873]
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by cjb900** [comment]
pyrit was removed from the default repository in the latest version of kali. you will need to download and install it from here http://kali.download/kali/pool/main/p/pyrit

**Comment by strasharo** [comment]
Install it manually.

**Comment by riadh402** [comment]
i install pyrit and  it not showing up on screen of fluxion what to do
