### ISSUE TITLE
mdk4 deauthentication window disappears after few min when captive portal attack is started & deauthentication stops

### ISSUE THREAD

**Issue by RadhaKrishn4** [FluxionNetwork/fluxion#876]
#### Summary
mdk4 deauthentication window(every time) & dns server window(sometimes) disappears after 3-4 min when we start captive portal attack 
##### What is the current behaviour?

mdk4 deauthentiction stops working after few min
#### How to reproduce
just start the captive portal attack with recommended settings in fluxion then after  few min the deauthentiction window disappears & sometimes the dns server window too
##### If the current behaviour is a bug, please provide the steps to reproduce it.

start the captive portal attack normally ull b able 2 reproduce it
##### What do you think the expected behaviour should be?

the mdk4 deauthentication along with dns server window should stay open
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
 #### FLUXION Info
FLUXION V6.5

#### BASH Info 
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan2) Info 
**Device**: phy7
**Driver:** rtl88XXau
**Chipset:** Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(353)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                             

#### System Info
**Chipset:** Linux version 5.4.0-kali4-amd64 (devel@kali.org) (gcc version 9.2.1 20200203 (Debian 9.2.1-28)) #1 SMP Debian 5.4.19-1kali1 (2020-02-17)

#### Chipset
Chipset: rtl88XXau
Chipset is not in list

#### Expected behavior

mdk4 deathentication should work continuously till a user enters correct password

**Comment by RadhaKrishn4** [comment]
@strasharo @afonso @dandrews @Geczy @xpz3 Brother y was the thread closed even if i change the adapter the deauth window is closing every time.i have used ralink mt7601u external card for deauth & also the laptops intel internal card.but every time the deauth window gets closed.also the dns server window also gets closed sometimes but not everytime like deauth window!!

**Comment by RadhaKrishn4** [comment]
@strasharo @afonso @dandrews @Geczy @xpz3 also if a use the same card with airgeddon & launch the mdk4 attack it doesn't get closed!

**Comment by xpz3** [comment]
I'm one of airgeddon collaborators and afaik, both the cards mt7601 and rtlxx cards are incompatible with airgeddon for evil twin attac bcoz both cards have virtual interfaces issues which is required for airgeddon evil twin attack. That's why you require two separate cards, one for AP and other for Deauth.
You can use both cards for mdk4 deauth attack from DoS menu on airgeddon because for that virtual interfaces are not needed.

Now if the deauth window is getting closed after some time, you can try two things.

1. when it gets stopped try airmon-ng check command and see if it shows any process name
If it does, then that process might be interfering while you run deauth thereby stopping it.
2. Just run airmon-ng check kill before running fluxion and see if that helps. If it fails again do step 1 to check for interfering process.

**Comment by RadhaKrishn4** [comment]
@xpz3 @strasharo @afonso @dandrews brother when i run airmon-ng check as u said there were networkmanager &  wpa_supplicant processes found

**Comment by RadhaKrishn4** [comment]
@xpz3 @strasharo @afonso @dandrews thanx so much brother your advise running airmon-ng check kill before starting fluxion does work the windows are not closing by themselves.
@xpz3 bro could you also help on the issue of slow loading of captive portal login page on clients phone
