### ISSUE TITLE
captive portal is taking min 40 sec 2 appear on the clients phone.older ver of fluxion it would be done in 10 seconds

### ISSUE THREAD

**Issue by RadhaKrishn4** [FluxionNetwork/fluxion#877]
#### Summary

2 much time taking 4 d captive portal page 2 appear on d clients phone.it takes min 40 sec to appear.bcoz of this d connected clients r disconnecting the fake AP.under older version of fluxion it would take very less time 
##### What is the current behaviour?

2 slow captive login page
#### How to reproduce
just use the captive portal attack normally & ull see that it tkes long time 4 the captive portal 2 appear on clients phone.
##### If the current behaviour is a bug, please provide the steps to reproduce it.

it takes round 40 sec which is making the client to disconnect from the fake AP
##### What do you think the expected behaviour should be?

like in older ver of fluxion the login page should appear very quickly
##### If this is a feature request, what is the motivation or use case for the added feature?
if the login page takes 2 long 2 appear then d clients r disconnecting from the AP
##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V6.5

#### BASH Info 
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan2) Info 
**Device**: phy7
**Driver:** rtl88XXau
**Chipset:** Realtek Semiconductor Corp. RTL8814AU 802.11a/b/g/n/ac
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(353)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                             

#### System Info
**Chipset:** Linux version 5.4.0-kali4-amd64 (devel@kali.org) (gcc version 9.2.1 20200203 (Debian 9.2.1-28)) #1 SMP Debian 5.4.19-1kali1 (2020-02-17)

#### Chipset
Chipset: rtl88XXau
Chipset is not in list

#### Expected behavior

fast loading of login page on clients mobile just like in older version of fluxion

**Comment by xpz3** [comment]
I can see that you are using rtl88xx Card. Did you select an additional Card for the attack?
If yes, which Card for AP and which Card for deauth? 
If the fake AP has enough range/power, the fake portal will load immediately provided that you use a fully compatible wifi chipset for creating the fake AP.

**Comment by RadhaKrishn4** [comment]
@xpz3 @strasharo @afonso @dandrews im using the rtl8814au card for ap & another ralink mt7601u external card for deauth.

**Comment by RadhaKrishn4** [comment]
@xpz3 @strasharo @afonso @dandrews brother pls tell me how to solve the slow loading of captive portal login page in clients phone.it used to load very fast in earlier (like 5.xx) versions of fluxion!

**Comment by xpz3** [comment]
Join discord channel of fluxion and message me. Ill send you a fix. If that works for you ill talk to the devs about that.
