### ISSUE TITLE
pyrit cannot install

### ISSUE THREAD

**Issue by lingQiup** [FluxionNetwork/fluxion#879]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package pyrit is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'pyrit' has no installation candidate

**Comment by strasharo** [comment]
Install it manually.

**Comment by lingQiup** [comment]
> Install it manually.

But install manually also the same error come out
