### ISSUE TITLE
Not Deauthing while getting the hash file

### ISSUE THREAD

**Issue by AlienWolfX** [FluxionNetwork/fluxion#880]
|    Q        |   A
|------------ | -----
| Version     | 6.5

#### Support Question
While capturing the Handshake of a network Fluxion does not Deauth the user from the network causing it to continue searching is there a fix for this issue?.

#### FLUXION Info
FLUXION V6.5

#### BASH Info 
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan1) Info 
**Device**: phy16
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!
read failed: Network is down
wi_read(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
read failed: Network is down
wi_read(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
read failed: Network is down
wi_read(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down
write failed: Network is down
wi_write(): Network is down

#### XTerm Infos
**Version:** XTerm(353)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                                                               

#### System Info
**Chipset:** Linux version 5.4.0-kali4-amd64 (devel@kali.org) (gcc version 9.2.1 20200203 (Debian 9.2.1-28)) #1 SMP Debian 5.4.19-1kali1 (2020-02-17)

#### Chipset
Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

**Comment by strasharo** [comment]
Looking at your injections test there's something interfering with your adapter. Try running airmon-ng check kill prior running it.

**Comment by AlienWolfX** [comment]
When running the airmon-ng check kill before starting problem still persist.

**Comment by xpz3** [comment]
Join discord channel of fluxion. Will see if i can help. I need to see some screenshots

**Comment by AlienWolfX** [comment]
> Join discord channel of fluxion. Will see if i can help. I need to see some screenshots

Can you send me the invitation link.

**Comment by cjb900** [comment]
look at the bottom of the main github page. its under links
