### ISSUE TITLE
add internet connectivity to fake ap for authenticityity

### ISSUE THREAD

**Issue by RadhaKrishn4** [FluxionNetwork/fluxion#882]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

since android phones are disabling automatic reconnection of fake ap when they discover that they have no internet.we could just before launching the captive portal attack we make transfer internet from another lan or wlan or mobile usb adapter to this fake ap & let the Android phone of client save it as an ap with internet & after few seconds just disable the internet to the ap and start the captive portal login page or we could just relaunch the ap with only captive portal attack & no internet thus making the client reconnect 
or we could also add dns queries of different phones in emulation attack.

**Comment by strasharo** [comment]
already there
