### ISSUE TITLE
Fluxion crashes after start with errors (read below)

### ISSUE THREAD

**Issue by sudo-HackerMan** [FluxionNetwork/fluxion#885]
#### Summary
When I try to start Fluxion, it crashes.

##### What is the current behaviour?
Fluxion crashes

##### If the current behaviour is a bug, please provide the steps to reproduce it.
./fluxion.sh: line 255: format_center_literals: command not found

./fluxion.sh: line 262: format_center_literals: command not found

./fluxion.sh: line 270: installer_utils_check_update: command not found
./fluxion.sh: line 288: installer_utils_run_dependencies: command not found

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

**Something is not installed, I guess. But what?**

##### What do you think the expected behaviour should be?
Fluxion should show dependencies and if they are all installed, start.

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### FLUXION Info
FLUXION V6.5

#### BASH Info 
GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan1) Info 
**Device**: phy1
**Driver:** rtl8192cu
**Chipset:** ASUSTek Computer, Inc. USB-N13 802.11n Network Adapter (rev. B1) [Realtek RTL8192CU]
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(353)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                           

#### System Info
**Chipset:** Linux version 5.4.0-kali2-amd64 (devel@kali.org) (gcc version 9.2.1 20200104 (Debian 9.2.1-22)) #1 SMP Debian 5.4.8-1kali1 (2020-01-06)

#### Chipset
Chipset: rtl8192cu
Chipset doesn't support ap mode
Chipset support monitor mode
Don't reseve all required information

#### Expected behavior
Fluxion should show dependencies and if they are all installed, start.

**Comment by cjb900** [comment]
well first we don't know what OS you are using and second the adapter you are using says is doesn't support AP mode so it will not work with fluxion by its self. you would have to have 2 adapter

**Comment by sudo-HackerMan** [comment]
1) I use Kali Linux 2020.1
2) I'd like to create an AP with 1st adapter and crash the network with 2nd adapter

**Comment by cjb900** [comment]
ok so you would need 2 adapters to do that. what you posted only referenced 1 adapter and the chipset of that adapter

**Comment by sudo-HackerMan** [comment]
It says that chipset of 1st is not in list, would it create an AP?

**Comment by cjb900** [comment]
Chipset

Chipset: rtl8192cu
**Chipset doesn't support ap mode**
Chipset support monitor mode
Don't reseve all required information

No. you will need a separate adapter to create the AP and one to deauth the network

**Comment by sudo-HackerMan** [comment]
I've got 2 adapters. First is wlan0, diagnostics says it's not in list. Second is wlan1 and I sent diagnostics of second. So, could wlan0 create an AP if it's not in list?

**Comment by cjb900** [comment]
you can only use wlan0 if it supports the proper modes for wifi hacking. if its not showing in the diagnostics.sh then it probably wont work. you may need to install a driver to get that other adapter to work

**Comment by sudo-HackerMan** [comment]
I heard that Fluxion use 2 adapters. 1st for deauth and 2nd for creating an AP. I wanted to use wlan0 for AP and wlan1 for deauth.

**Comment by cjb900** [comment]
well with out knowing the chipset of wlan0 i can't say if that will work and if it didn't show in the diagnostics.sh then it most likely wont work

**Comment by sudo-HackerMan** [comment]
#### FLUXION Info
FLUXION V6.5


#### BASH Info 
GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath10k_pci
**Chipset:** Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter (rev 31)
**Master Modes** Yes
**Injection Test:** No Answer...


#### XTerm Infos
**Version:** XTerm(353)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

**Scapy Version:** 2.4.3
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                                                                                                           

#### System Info
**Chipset:** Linux version 5.4.0-kali2-amd64 (devel@kali.org) (gcc version 9.2.1 20200104 (Debian 9.2.1-22)) #1 SMP Debian 5.4.8-1kali1 (2020-01-06)

#### Chipset
Chipset: ath10k_pci
Chipset is not in list


**It's wlan0**

**Comment by cjb900** [comment]
run this and post the output
iw list | grep "Supported interface modes" -A 8

**Comment by sudo-HackerMan** [comment]
Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
                 * P2P-device

**Comment by sudo-HackerMan** [comment]
It's wlan0 because I've just unplugged wlan1

**Comment by cjb900** [comment]
so you should be able to use wlan0 as the AP and then use wlan1 to deauth the network

**Comment by sudo-HackerMan** [comment]
Ok, but I'd like to know why Fluxion crashes)

**Comment by sudo-HackerMan** [comment]
with this

./fluxion.sh: line 255: format_center_literals: command not found

./fluxion.sh: line 262: format_center_literals: command not found

./fluxion.sh: line 270: installer_utils_check_update: command not found
./fluxion.sh: line 288: installer_utils_run_dependencies: command not found

Dependency installation failed!
Press enter to retry, ctrl+c to exit...

**Comment by cjb900** [comment]
are all the dependencies installed for it. I've not seen this error with fluxion before

**Comment by sudo-HackerMan** [comment]
I tried to start it and it should give me list of dependencies but instead of it there are errors. I guess, packages which should show dependencies are not installed. Because this beautiful text at start made by other packages

**Comment by cjb900** [comment]
can you post a screen shot of the command you are running and then the errors you are getting

**Comment by sudo-HackerMan** [comment]
I type: sudo ./fluxion.sh
Screen cleans and I get these errors

**Comment by cjb900** [comment]
run:
sudo ./fluxion.sh -i

**Comment by sudo-HackerMan** [comment]
Tried, the same

**Comment by cjb900** [comment]
then something is wrong with your install of kali. i've never had it crash on a fresh install of kali and i've never seen those errors before

**Comment by sudo-HackerMan** [comment]
It standard install of kali, it should be ok. The most strange thing is this is not new bug. I saw it on 2019.4, 2019.3... The same. I'll try to upgrade

**Comment by cjb900** [comment]
yes but there have been updates to both kali and fluxion since those version of kali were released and there hasn't been any new posts that i've seen where anyone is having this issue in recent months with kali 2020.1

**Comment by sudo-HackerMan** [comment]
Now updating, I'll say if it won't work,

**Comment by sudo-HackerMan** [comment]
It was updating all night.... But.. Nothing. The same

**Comment by cjb900** [comment]
well i know this might not be that much helpful but i just reinstalled kali 2020.1 on another computer i have and was able to install and run fluxion with no errors. so my guess would be that there is something wrong with with either your install of kali, something with your computer or one of the dependencies is broken

**Comment by kandarpgautam** [comment]
> It was updating all night.... But.. Nothing. The same

I would want you to check your sources.list, it won't be an issue if you never tampered with it. 
You can check it with command: 
`sudo cat /etc/apt/sources.list`

**Comment by cjb900** [comment]
why would i need to give you my source list if i never tampered with it it can easily be found on the website for kali.org. i'm also well aware of how to get the sources.list and updating my kali wont do anything i haven't already done before. also no one is going to help you when the information you are asking is easily gotten on either the kali.org site or google

**Comment by MPX4132** [comment]
This sounds like a problem with the interpreter, bash outdated?
