### ISSUE TITLE
Captive Portal Interface Freeze with message "Alright, got hit!"

### ISSUE THREAD

**Issue by iindestructible** [FluxionNetwork/fluxion#886]
#### Summary
Unable to perform Evil Twin at Captive Portal execution

##### What is the current behaviour?
Fluxion freeze with message "Alright, got hit!"

##### If the current behaviour is a bug, please provide the steps to reproduce it.
Start Evil Twin session with cowpatty hash found from Handshake session previously.
Select Wifi for Jamming then Wifi for AP then select Captive Portal 67

##### What do you think the expected behaviour should be?
After selecting the portal, it should begin the deauthenticating the target wifi and creating portal for the victim user

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by cjb900** [comment]
can you share a screen shot of the error you are getting. there have been some recent updates to fluxion

**Comment by MPX4132** [comment]
lol my bad

**Comment by MPX4132** [comment]
It's corrected on the repository now lol. 
https://github.com/FluxionNetwork/fluxion/commit/ebb7cc936fad9efdb285e90d0732feecd20cd45c#r38760231
