### ISSUE TITLE
Captive Portal has no field to enter password

### ISSUE THREAD

**Issue by iindestructible** [FluxionNetwork/fluxion#887]
![IMG_20200427_103758](https://user-images.githubusercontent.com/31999379/80331982-c4a53780-8873-11ea-8201-694af9e9b50b.jpg)

#### Summary
Captive Portal appears with no password field to input

##### What is the current behaviour?
Evil Twin portal cannot retrieve victim's password

##### If the current behaviour is a bug, please provide the steps to reproduce it.
Select Captive Portal Form 7 or 67 in the Captive Portal Selection screen (using Cowpatty Hash)

##### What do you think the expected behaviour should be?
The Evil Twin Portal should have input field for passphrase

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by cjb900** [comment]
Well in testing this on my end I get the captive portal with the spot to put in the password with both the 7![Screenshot_20200427-002006_CaptivePortalLogin](https://user-images.githubusercontent.com/47070308/80334252-ab25d080-881e-11ea-8a11-7ddf3a489e03.jpg) and 67![Screenshot_20200427-002624_CaptivePortalLogin](https://user-images.githubusercontent.com/47070308/80334253-ac56fd80-881e-11ea-92c8-0abaa88a87e3.jpg) options on my Samsung note 9 running android 10. I know there were recent updates in fluxion so may be something there but i don't think the recent changes modified how the captive portals are displayed. So the issue may be with the version of android you have or the model phone you have. One thing I did find out is that I no longer get the captive portal prompt on my iPhone 11 running IOS 13.4.1

**Comment by strasharo** [comment]
Which templates are you using?

**Comment by cjb900** [comment]
I used the same ones  iindestructible mentioned to see if i had the same issue. they were number 7 which is the English one and 67 which is the tp-link english one

**Comment by iindestructible** [comment]
I tried it again on another phone and laptop and it turns out okay now, I guess Android 8.1.0 has some problems with this, not the fluxion
