### ISSUE TITLE
Fluxion hostapd missing

### ISSUE THREAD

**Issue by zubair41** [FluxionNetwork/fluxion#890]
i install fluxion and all its dependencies...
all of dependencies install successfully instead of hostapd
i tried 
apt-get install hostapd
but it does not help me.
![32354546-10f327e0-c022-11e7-9b01-62225bcb9811](https://user-images.githubusercontent.com/64449617/80446752-1e1f6c00-8931-11ea-99be-9ba3c74d27b4.png)

**Comment by xpz3** [comment]
It seems you are not connected to internet. Make sure you can open webpages and then try again

**Comment by zubair41** [comment]
@xpz3 i can access the webpages..but cant install hostapd
plz help me

**Comment by xpz3** [comment]
run `apt update && apt install hostapd`
