### ISSUE TITLE
se detiene el ataque 

### ISSUE THREAD

**Issue by luisjulior** [FluxionNetwork/fluxion#892]
cada 5 minutos se detiene el ataque, bueno la ventana de jamming se cierra y se detiene tengo tarjeta externa alfa Alfa-AWUS036NHA

**Comment by gladston** [comment]
Much more information is needed to know what happens.
  Before everything ran command
#**sudo apt-get update && apt-get upgrade**
Are you using two wireless cards for the attack? one for dedicated attack and one for monitoring and jamming?

Did you run # **airmon-ng check kill** before running the script?
