### ISSUE TITLE
Cannot connect to fake ap 

### ISSUE THREAD

**Issue by ajaychhadwa** [FluxionNetwork/fluxion#893]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Specs

Cannot connect fake access point created by fluxion.. It is showing acquiring ip address but it is not connecting 

I am on ubuntu bodhi linux latest 

And have also installed the latest script 

I am using the internal wifi of my acer laptop

**Comment by ajaychhadwa** [comment]
Why is it closed?

**Comment by azamet90** [comment]
because developpers doesnt know it too i think :D it was edited by another guy unofficial version with but the developpers takes the fixed tool and makes it garbage again :D
