### ISSUE TITLE
How to get the latest version?

### ISSUE THREAD

**Issue by piiiiq** [FluxionNetwork/fluxion#895]
What same git clone command gets fluxion 5.9 on Ubuntu 19.10, and fluxion 6.7 on Kali 2019.4(in one day)?
Now I am using fluxion 6.7 (GIT clone). Is this the latest version? If not, how can I get the latest version of fluxion? I am using Kali 2019.04

**Comment by cjb900** [comment]
yes this is the official github for fluxion and yes the latest version is 6.7

**Comment by piiiiq** [comment]
> yes this is the official github for fluxion and yes the latest version is 6.7

ok thinks
