### ISSUE TITLE
Secondary pages not loading after update

### ISSUE THREAD

**Issue by rpifuntime** [FluxionNetwork/fluxion#896]
#### Summary

After updating a couple of days ago I’m experiencing some issues. 
Captive portal launches just fine but when correct password is entered nothing happens onscreen, rather than going to the progress page it just sits there on the password entry page until the server closes and ultimately the captive portal shuts. 
Also the same thing seems to be happening if a wrong password is entered and it needs to load a new page, the page won’t load and some of the captive portals then go non responsive. 
Sometimes I can get it to load the wrong password page by continually pushing the onscreen button

There seems to be an issue where if you are entering the wrong password and only enter a small password for example two characters nothing happens, but if you enter an eight character password then it tells you the password was wrong, it seems it doesn’t like people putting in short passwords

##### If the current behaviour is a bug, please provide the steps to reproduce it.

Setup captive portal using tp-link or any portal that loads more than one page, for example loads a progress page after inputting correct password, join portal from a device and input password and see if page loads

Set up any captive portal and enter a two digit password in both fields

**Comment by M1z23R** [comment]
I am not sure how you managed to put 2 digit password into it, you need to set minimum characters needed for the form to submit, generic pages have that already set.

**Comment by rpifuntime** [comment]
I see, thanks, that makes sense why nothing happens with passwords that are too short, maybe in future releases it could say “wrong password” rather than do nothing. 

The other issue still stands where pages aren’t loading after inputting correct password though

**Comment by strasharo** [comment]
Which template exactly?

**Comment by rpifuntime** [comment]
The problem was with all the templates that had to load a second page after user inputted password. 
Thing is I can’t recreate the problem now, problem persisted over a couple of days with multiple reboots, now I’ve gone back to get screen shots and a more detailed description everything is working as normal. 
I’ll close this for now and if it happens again I’ll report back. 
Cheers
