### ISSUE TITLE
Do I need an external wireless card for deauthentication?

### ISSUE THREAD

**Issue by v0ZXE7** [FluxionNetwork/fluxion#897]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x
Version 6.7

I do not have gitter or discord
#### Support Question

The issue/question. When I have the handshake, I start captive portal; but jammer does not work. Do I need to buy an external card from tp-link or other provider?
#### Specs

Thank

**Comment by rpifuntime** [comment]
You will need a wireless card capable of packet injection, if you are trying to use the inbuilt wireless card it probably won’t work, Alfa cards seem to be the most popular

**Comment by v0ZXE7** [comment]
Ok, I though something like that. I will buy alfa network card, although my wireless device support injections because I got the handshake to deauthenticate users, but I think I will need one inside my pc to run the AP, and other to run the injection package.

I also want to contribute to the project with more code of website of routers I have, I will read guidelines to do that.

Thank for your response!!
