### ISSUE TITLE
Fluxion scanner not showing available connections

### ISSUE THREAD

**Issue by Gimhan-minion** [FluxionNetwork/fluxion#898]
#### Summary
Fluxion scanner keeps changing channels but available wifi networks not found.

##### What is the current behaviour?
I executed fluxion as usual but fluxion scanner doesn't show any available connections

1. I tried "sudo airmon-ng check kill"
2. Even "sudo ./fluxion.sh -r"
3. I selected both 2.5Ghz and 5Ghz

But nothing worked! :(

**Comment by strasharo** [comment]
Let me pull out the crystal ball and guess your setup.
