### ISSUE TITLE
although it hops channels it not deauthenticate clients after channel change !!!!!!

### ISSUE THREAD

**Issue by hanbing88** [FluxionNetwork/fluxion#9]
<???>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
<???>

**Comment by hanbing88** [comment]
although it hops channels it not deauthenticate clients after channel change !!!!!!

**Comment by Genetick** [comment]
Same problem please add features. And please fix mdk3 . Periodically re- reading blacklist/white list every 3 seconds.  I'm used fluxion mdk3 kali.2016'1 work mdk3 other kali 2017'1 not work

**Comment by strasharo** [comment]
mdk3 is an external product and we're  not developing it, contact the author. Pull requests are welcome.

**Comment by deltaxflux** [comment]
Well if you want to add this feature, develop it. 
Here is the source code: 
* https://github.com/wi-fi-analyzer/mdk3-master

@strasharo How to handle [this](https://github.com/wi-fi-analyzer/fluxion)

**Comment by strasharo** [comment]
@deltaxflux , handled, lol, check it out.
