### ISSUE TITLE
ARP linktype is set to 1 (Ethernet) - expected arphrd_ieee80211

### ISSUE THREAD

**Issue by agustinscaz** [FluxionNetwork/fluxion#900]
|    Q        |   A
|------------ | -----
| Version     | 6.7

#### Support Question

I'm trying to run Fluxion with the option "Handshake Snooper", selecting any option, Fluxion app opens a new console and closes inmediatly.

Notes:
Running on Raspberry Pi 3 with Kali
Aircrack-ng is working good

#### Specs

![c47d91a0-e592-4700-93c6-2b403cb6bbb2](https://user-images.githubusercontent.com/17032561/81488877-58610580-926f-11ea-8772-2a2ad04f832b.jpg)

**Comment by xpz3** [comment]
Select a wifi interface, not Ethernet.

**Comment by deltaxflux** [comment]
Do you use the default raspberry pi wireless card?

**Comment by Tarun1921** [comment]
> 
> 
> Select a wifi interface, not Ethernet. If the interface is wifi, then it might not be supported. Get a supported card

he bro please help me too regarding fluxion.. check my issue please

**Comment by deltaxflux** [comment]
Run the diagnostic script

**Comment by agustinscaz** [comment]
> Do you use the default raspberry pi wireless card?

Yes, I use the default raspberry pi wireless card.

I've just reinstalled Kali, installed Fluxion, installed missing packages, and throws me the same error.


> Run the diagnostic script

how can i run the diagnostic script?

**Comment by agustinscaz** [comment]
Diagnostic script
`#### FLUXION Info
FLUXION V6.8


#### BASH Info 
GNU bash, version 5.0.16(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash


#### Interface (fluxwl0) Info 
**Device**: phy0
**Driver:** brcmfmac
**Chipset:** Unknown chipset for SDIO device.
**Master Modes** Yes
**Injection Test:** 
ARP linktype is set to 1 (Ethernet) - expected ARPHRD_IEEE80211,
ARPHRD_IEEE80211_FULL or ARPHRD_IEEE80211_PRISM instead.  Make
sure RFMON is enabled: run 'airmon-ng start fluxwl0 <#>'
Sysfs injection support was not found either.

Failed
`

**Comment by strasharo** [comment]
It's a Broadcom, it won't work.

**Comment by agustinscaz** [comment]
Thankyou for the fast response, I will buy another one.
> It's a Broadcom, it won't work.
And why the aircrack-ng is working?

Thanks!

**Comment by xpz3** [comment]
If you search online with the exact error message you'll know more about your issue. If aircrack works for you, then you can use `n` flag for fluxion so that airmon-nh manages monitor mode. Still you may face issue going forward. If you plan to buy a card please do some research on supported cards. Join fluxion discord to know more on supported cards..
