### ISSUE TITLE
Problem in fluxion

### ISSUE THREAD

**Issue by Tarun1921** [FluxionNetwork/fluxion#901]
I am using the latest version of fluxion. There are a couple issues. Firstly After successfully capturing handshake by mdk4 deauth i then go to captive portal attack. there too i choose mdk4 but this time in Fluxion AP jammer service there is nothing but " Periodically re-reading blacklist/whitelist". Please do note that i am using mdk4. Then in a new terminal i open airodump-ng and aireplay-ng to manually deauth the clients but this time in the DHCP window it says that network is down which i think means that my rogue AP is down but the jammer service starts working.... I really need a solution to this..
Secondly, I tried using older versions of fluxion but they require Pyrit which i try to install by downloading from github and then when i try to install it using python it shows the following error:
root@kali:# ls
fluxion mdk3 Pyrit
root@kali:# cd Pyrit
root@kali:/Pyrit# ls
build COPYING MANIFEST.in pyrit pyrit_cli.pyc Pyrit-logo.png setup.py
CHANGELOG cpyrit modules pyrit_cli.py Pyrit-logo.ai README.md test
root@kali:/Pyrit# python setup.py clean
running clean
removing 'build/temp.linux-x86_64-2.7' (and everything under it)
root@kali:~/Pyrit# python setup.py build
running build
running build_py
running build_ext
building 'cpyrit._cpyrit_cpu' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/cpyrit
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cpyrit/_cpyrit_cpu.c -o build/temp.linux-x86_64-2.7/cpyrit/_cpyrit_cpu.o -Wall -fno-strict-aliasing -DVERSION="0.5.1" -maes -mpclmul
cpyrit/_cpyrit_cpu.c:35:10: fatal error: openssl/hmac.h: No such file or directory
35 | #include <openssl/hmac.h>
| ^~~~~~~~~~~~~~~~
compilation terminated.
Failed to build; Compiling without AES-NI
building 'cpyrit._cpyrit_cpu' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-uC7NI8/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c cpyrit/_cpyrit_cpu.c -o build/temp.linux-x86_64-2.7/cpyrit/_cpyrit_cpu.o -Wall -fno-strict-aliasing -DVERSION="0.5.1"
cpyrit/_cpyrit_cpu.c:35:10: fatal error: openssl/hmac.h: No such file or directory
35 | #include <openssl/hmac.h>
| ^~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Please help i'm so stuck. please help me with any one of the problems .......

**Comment by strasharo** [comment]
This is related to pyrit.

**Comment by xpz3** [comment]
The first problem is something related to your wifi adapter chipset or any interfering process. But without providing any information about your setup we can't help you. You were clearly given instructions what to provide while opening an issue. Where's the diagnostics information? So you are in your own
