### ISSUE TITLE
Problem DNS I Can’t resolve please help

### ISSUE THREAD

**Issue by MadMax6z** [FluxionNetwork/fluxion#903]
Hello I have a problem with fluxion I manage to recover the Handshake without problem but when I launch a malicious Twin attack I have the following problem

Bonjour j’ai un problème avec fluxion j’arrive à récupérer le Handshake sans problème mais quand je lance une attaque Jumeaux malveillant j’ai le problème suivant 

![521187AD-F36A-4686-91DB-FFD040020CEB](https://user-images.githubusercontent.com/64981719/81502308-7ebd8a00-92dd-11ea-8d5c-494dd88fd32c.jpeg)

I try make:  a sudo systemctl stop système-resolved         

but don’t work
 I’m on ubuntu

**Comment by cjb900** [comment]
Well Fluxion is not designed for Ubuntu and many have had issues getting it up and running properly. You can try and follow this and see if it helps [https://github.com/FluxionNetwork/fluxion/issues/792](https://github.com/FluxionNetwork/fluxion/issues/792). If not you would be better off using a dedicated hacking distro like [Kali ](https://kali.org) or [Parrot OS](https://parrotsec.org/)

**Comment by xpz3** [comment]
Please tell us what your problem is. The screenshot from dns window seems ok. It won't show anything unless a client connects to the fake AP

**Comment by MadMax6z** [comment]
I want use fluxion for attack evil twins and don’t work
![2B297423-F5AB-422D-B852-0EBD4CC781EB](https://user-images.githubusercontent.com/64981719/81507536-6c077d00-92fe-11ea-8486-5ce75fcbdcff.jpeg)
![A97686D1-8AD9-4BF3-8084-3B469B22F29F](https://user-images.githubusercontent.com/64981719/81507537-6f026d80-92fe-11ea-8f8e-a3ee95f8bea1.jpeg)

**Comment by MadMax6z** [comment]
I’ m on fluxion 6.8 do you want my iw list ?

**Comment by xpz3** [comment]
Your wireless card doesn't seem to support virtual interfaces. You can use an additional wifi card or buy a fully compatible card that supports vif. In the above screenshot you can clearly see that hostapd and dhcp windows are missing. Without those, the attack is useless.
