### ISSUE TITLE
/root/fluxion/lib/IOUtils.sh : line 72 /dev/stdout : permission denied 

### ISSUE THREAD

**Issue by emongroove** [FluxionNetwork/fluxion#905]
please help me solve this problem
when i opened ./fluxion.sh I found This

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                                              ]
[                   FLUXION 6.8    < Fluxion Is The Future >                   ]
[                                                                              ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[*] Select your language

/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied
/root/fluxion/lib/IOUtils.sh: line 73: /dev/stdout: Permission denied

[fluxion@localhost]-[~] 

in the language window there is this display

i am noob, please helpme master

**Comment by cjb900** [comment]
well are we just supposed to use our crystalball to see your setup?? If you don't give us this information we can't help you with what you sent. 



### Bug Report

#### Summary


##### What is the current behaviour?


#### How to reproduce

##### If the current behaviour is a bug, please provide the steps to reproduce it.


##### What do you think the expected behaviour should be?


##### If this is a feature request, what is the motivation or use case for the added feature?

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### Expected behavior

**Comment by Czechball** [comment]
Obligatory question, but are you running Fluxion as root? (sudo ./fluxion.sh)

**Comment by emongroove** [comment]
> Pertanyaan wajib, tetapi apakah Anda menjalankan Fluxion sebagai root? (sudo ./fluxion.sh)
when i run with this sudo command the output is issued

sudo: unable to send audit message: Operation not permitted

**Comment by emongroove** [comment]
> well are we just supposed to use our crystalball to see your setup?? If you don't give us this information we can't help you with what you sent.
> 
> ### Bug Report
> #### Summary
> ##### What is the current behaviour?
> #### How to reproduce
> ##### If the current behaviour is a bug, please provide the steps to reproduce it.
> ##### What do you think the expected behaviour should be?
> ##### If this is a feature request, what is the motivation or use case for the added feature?
> ##### Specs
> _Paste the output of `./script/diagnostics.sh [interface]`_
> 
> #### Expected behavior

after I do your advice, this output is issued

Usage ./scripts/diagnostics [wireless_interface]

**Comment by xpz3** [comment]
Are you running from docker?

**Comment by emongroove** [comment]
> Are you running from docker?

What is docker ?
I am new in linux
But i am running ubuntu linux on android

**Comment by cjb900** [comment]
Well that's going to be part of your issue right there. Fluxion is not designed for Ubuntu by default. there are some stuff you need to change to get it to work. You can find more information here https://github.com/FluxionNetwork/fluxion/issues/792 if you can't get it to work in Ubuntu you may be better off using a dedicated hacking distro like https://www.kali.org/

**Comment by xpz3** [comment]
He is running Ubuntu chroot on Android. Its not going to work.
