### ISSUE TITLE
What is the wifi adapter (chipset) with excellent compatibility with fluxion?

### ISSUE THREAD

**Issue by carl0s12** [FluxionNetwork/fluxion#908]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by carl0s12** [comment]
What is the wifi adapter (chipset) with excellent compatibility with fluxion?

**Comment by cjb900** [comment]
any of these will work in fluxion with little to no set up. i personally have the panda pau09 that works out of the box with kali and fluxion

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by carl0s12** [comment]
https://forums.kali.org/showthread.php?45021-rtl8822be-wifi-not-working-after-updated-to-kernel-5-2-0

**Comment by cjb900** [comment]
ok so if thats a card that you have you may have to downgrade the kernel back to 4.19. this is just a list of cards that have been known to work in the past. i don't know if al of them have been tested in the latest kali
