### ISSUE TITLE
unable to start captive portal interface

### ISSUE THREAD

**Issue by gnomanton** [FluxionNetwork/fluxion#910]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

Hi, all! 
im using kali64 on VBox. My adapter is alfa awus036ach. 
im supa noob, but i've updated to the latest karnel and installed drivers for my card.
the issue is after capturing the handshakes and proceeding to EvTw setup i get "unable to start captive portal interface" error. (same as issue#824 had). 
i stopping networkmanager.service and kill airmon-ng check.
i also tried the airgeddon, but there as soon as i run handshake capture it gives me "it seems we failed" error.
anyone who may help me with that? ive searched all over the internet but couldnt find the solution, even though ppl ve got same issue
tnx in advance

**Comment by cjb900** [comment]
Hi, 
The issue is that the card you have uses a chipset of Realtek RTL8812AU which does not support VIF. This means that the card can not deauth and create a captive portal at the same time. You will need to replace this card with one that supports VIF or get a second card to use along side this one so one is deauthing and another one is creating the captive portal

**Comment by gnomanton** [comment]
oh! tnx for the quick response. 
got u! may u recommend me a card that supports VIF? 
i also get similar error at ma airgeddon, is that related?
and sorry for all that questions, but could u tell me if i may somehow use my internal card rtl8822be for dat? so i may continue to search how to connect it to ma VM w/ wifi option(it only recognize it as ethernet adp) or may be i should use host vertion of linux?
thank u very much

**Comment by cjb900** [comment]
Yes airgeddon also requires a card that supports VIF. You can look here for a list of cards that will work with airgeddon and fluxion https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets. As for using your internal card in a VM that is not possible as VM are not able to use internal wifi cards.You will either have to dual boot to be able to use both cards or look into getting a second one or replace the one you have with one that supports VIF

**Comment by gnomanton** [comment]
thank you very much, ma friend
have a good one
case is closed
