### ISSUE TITLE
No wifi adapter detected. Fluxion auto closing

### ISSUE THREAD

**Issue by Yogesh111264** [FluxionNetwork/fluxion#912]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

I am running Nethuter on Oneplus6 with custom kernal. I have issues with fluxion that it is not detecting my wifi chipset which is already in monitor mode. It show no wireless adaptor detected and autoclose. Same time adaptor detected by wifite as well as Airmon-ng. I using one plus 6 internal Qualcomm chipset and running that into monitor mode through Nethuter app.
![Screenshot_20200522-225437](https://user-images.githubusercontent.com/65632559/82693979-1af17480-9c80-11ea-8089-35d2fb232183.jpg)

**Comment by cjb900** [comment]
You are using this from an android phone. i have not seen any one be successful in getting this to properly work on an Android phone. but one thing to note is that you can't use the built in wifi adapter in the phone and would have to use a USB wifi adapter with an OGT cable and your phone has to support OTG as not all do. But in the end you are going to be better off using a support platform like kali or parrot OS from a computer either running from a virtual machine, a live USB or dual booting along side your main OS

**Comment by strasharo** [comment]
Not supported.
