### ISSUE TITLE
Fluxion is not starting

### ISSUE THREAD

**Issue by ScryE778** [FluxionNetwork/fluxion#916]
When i start the program with the command sudo ./fluxion.sh or sudo bash fluxion.sh i got this errors:
./fluxion.sh: line 255: format_center_literals: command not found
./fluxion.sh: line 262: format_center_literals: command not found
./fluxion.sh: line 270: installer_utils_check_update: command not found
./fluxion.sh: line 289: installer_utils_check_dependencies: command not found
./fluxion.sh: line 290: installer_utils_run_dependencies: command not found
Dependency installation failed!
Predd enter to retry, ctrl+c to exit..
-- Then i press ctrl+c and i got error for two seconds (then automatically the program exit):
[-]
[-]
[-]
[-]
./fluxion.sh: line 376: sandbox_remove_workfile: command not found
[+]
[+]

**Comment by cjb900** [comment]
well you didn't give any information to help with this issue. 

this issue will be closed if you don't provide this information 




|    Q        |   A
|------------ | -----
| Version     | 4.10.x



#### Support Question


#### Specs
