### ISSUE TITLE
Unable to start captive portal interface.

### ISSUE THREAD

**Issue by bk-killer** [FluxionNetwork/fluxion#918]
I have been trying to use Fluxion i managed to capture the handshake but when i try the captive portal it is not working .
PS : in tracking interface i press skip and  after it i seleced my wifi adapter 

I am using usb wifi  TP-Link TL-WN722N  i was able to change it to monitor mode and used it as managed but i am still not 100% if the driver is correct or if it can cause any issue 

##### What is the current behaviour?
captive portal not working 

Unable to start captive portal interface, returning!

##### If the current behaviour is a bug, please provide the steps to reproduce it.
i tried to lunch the captive portal after i got the handshake and also before it both same issue 

##### What do you think the expected behaviour should be?
captive portal to lunch 

#### FLUXION Info
FLUXION V6.8

#### BASH Info 
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** 8188eu
**Chipset:** TP-Link TL-WN722N v2
**Master Modes** Yes
**Injection Test:** No Answer...
Injection is working!

#### XTerm Infos
**Version:** XTerm(356)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
./diagnostics.sh: line 89: pyrit: command not found
**Scapy Version:** 2.3.3

#### System Info
**Chipset:** Linux version 5.6.0-kali1-amd64 (devel@kali.org) (gcc version 9.3.0 (Debian 9.3.0-11)) #1 SMP Debian 5.6.7-1kali1 (2020-05-12)

#### Chipset
Chipset: 8188eu
Chipset is not in list

**Comment by strasharo** [comment]
Chipset isn't supported.

**Comment by Eisblume77** [comment]
I also use the TL-WN722N and it doesn't work.

Which USB-Wifi is recommended for using fluxion in a virtual machine with kali ??

**Comment by gfbangie** [comment]
Could you tell us which chipset works so we can buy that one please and thank you

**Comment by cjb900** [comment]
these adapters/chipset are known to work with fluxion. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by gfbangie** [comment]
So tp link wn722n version 2 won’t work ? 💔

**Comment by cjb900** [comment]
no it will not. TP-link changed the chipset in the V2/3 of that adapter and it no longer properly works

**Comment by rohanagrawal8053** [comment]
Is alfa AWUS036ACS SUPPORT CAPATIVE PORTAL INTERFACE

**Comment by cjb900** [comment]
Looks like that adapter has an RTL8811AU chipset so that would not work by itself. You may be able to get it to work with another wifi adapter.

**Comment by rohanagrawal8053** [comment]
No it has RTL 8812AU/8821AU CHIPSET
![Uploading 16193665374457838172658564483637.jpg…]()

**Comment by cjb900** [comment]
Well either way that chipset will not work wither. RTL chipsets in general are notoriously problematic for wifi hacking

**Comment by rohanagrawal8053** [comment]
Then what can I do

**Comment by cjb900** [comment]
buy one of the adapters/chipsets I posted above. those ones are known to work with fluxion. If its not one of those I can't say if it will work
