### ISSUE TITLE
ALFA AWUS036ACH IS NOT WORKING IN FLUXION KINDLY HELP PLEASE!!!!!!!!!!!!

### ISSUE THREAD

**Issue by chirag636** [FluxionNetwork/fluxion#919]
#### Summary

ALFA AWUS036ACH IS NOT WORKING IN FLUXION. WHEN MONITOR MODE STRATS OF FLUXION IT DOES NOT MONITOR WIFI AND I GIVE 5 MINUTES ALSO BUT THIS IS NOT WORKING.

KINDLY GIVE SUPPORT TO ALFA AWUS036ACH FOR PENERTRATION TESTING AND PLEASE DON"T 

WASTE MY MONEY SIR!!!!

##### What is the current behaviour?
 NO MONITOR SUPPORT

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by chirag636** [comment]
1. I WAS TAKING ABOUT PREVIOUS VERSION OF FLUXION https://github.com/wi-fi-analyzer/fluxion

2. in new fluxion it is still not working and unable to capture handshake file

**Comment by chirag636** [comment]
NO CAPATIVE PORTAL ATTACK AND NO DEAUTHENTICATE ATTACK KINDLY SEE THIS PLEASE SAVE MY 

MONEY TO FIX THIS OTHERWISE IT IS DUMPED MONEY ( BUT HARDWORKING MONEY TO ME ).

**Comment by cjb900** [comment]
This card does not support virtual interfaces. There is no one that can fix this card to work with Fluxion by its self. You will need to either get a new one or get a card that supports virtual interfaces.

**Comment by strasharo** [comment]
Calm down, Pajeet.
![image](https://user-images.githubusercontent.com/3337997/83324089-67821480-a26b-11ea-88ff-0f202a1c8424.png)

**Comment by chirag636** [comment]
Chipset is Realtek Rtl8812AU . WHAT I DO

SIR PLEASE GIVE SUPPORT TO THIS

DRIVER IN YOUR FLUXION TOOL.

I AM VERY MUCH DEPRESSED BECAUSE

I GIVE ALL MY SAVING TO THIS ADAPTER

PLEASE SUPPORT ME AND HELP ME!!!!!!!

**Comment by xpz3** [comment]
There is no driver in fluxion tool. Your chipset is incompatible with fluxion or similar tools for captive portal attack. If you can return your card just do it and get a refund. Buy another compatible card. You should have done some research before investing your hard earned money on something useless.

**Comment by chirag636** [comment]
Okkk thks all of u for helping me.
