### ISSUE TITLE
Deauthentication Not Working On Fluxion

### ISSUE THREAD

**Issue by oxemanuelexo** [FluxionNetwork/fluxion#921]
Here is what I did:
For capturing Handshake:
1. export FLUXIONAirmonNG=1
2. ./fluxion.sh
3.Then Selected Handshake Snooper 
4. Then Selected wlan0, my Intel WiFi 6 AX200 chip, for target searching
5. Then I selected to monitor all the channels and chose the WiFi which I want to use
6. Then skipped the wireless interface for target tracking
7. Then selected aireplay-ng deauthenthication as handshake retriever
8. Then selected cowpatty verification for the hash
9. Selected 30 seconds for verifier
10. Selected Synchronously as a verification
11. Success fully captured hash

Captive Portal Option:
1. Selected targeting the access point above
2. Selected wlan0 for target tracking
3. Selected interface wlan0 for access point
4. Then Selected Aireplay as a method of Deauthentication
5. Used hostapd as access point service
6. Used cowpatty as password verification method
7. Selected use hash found
8. Then selected to used cowpatty as verification for the hash
9. Selected to create an ssl certificate
10. Then selected disconnect as a connectivity type
11. Then used generic captive portal
12. Let it run

On the fluxion jammer service tab it said waiting for beacon frame. Not sure if that's the problem

**Comment by cjb900** [comment]
And what do you expect us to magically guess your OS and setup. No one is going to be able to help you if you do not provide this information.


Note: All issues will instant closed if the issue template is not complete. Please understand that it is easier for us if you fill out the template to help you faster.




### Bug Report

#### Summary


##### What is the current behaviour?


#### How to reproduce

##### If the current behaviour is a bug, please provide the steps to reproduce it.


##### What do you think the expected behaviour should be?


##### If this is a feature request, what is the motivation or use case for the added feature?

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### Expected behavior

**Comment by oxemanuelexo** [comment]
Sorry Didn't realize that there was a bug report

**Comment by oxemanuelexo** [comment]
the output of ./script/diagnostics.sh wlan0 is:
#### FLUXION Info
FLUXION V6.8


#### BASH Info 
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** iwlwifi
**Chipset:** Intel Corporation Wi-Fi 6 AX200 (rev 1a)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
No Answer...


#### XTerm Infos
**Version:** XTerm(356)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                 

#### System Info
**Chipset:** Linux version 5.6.0-kali2-amd64 (devel@kali.org) (gcc version 9.3.0 (Debian 9.3.0-13)) #1 SMP Debian 5.6.14-1kali1 (2020-05-25)

#### Chipset
Chipset: iwlwifi
Don't reseve all required information

**Comment by cjb900** [comment]
you are most likely going to need a different wifi card. most internal wifi adapters do not support all the proper modes for wifi hacking such as monitor mode, packet injection and AP mode. this is most likely why you are having issues deauthing

**Comment by oxemanuelexo** [comment]
Is there any way to install the drivers for the network card which is going to make it work for what I am doing? Also I saw now that  Pyrit is incompatible with scapy version 2.4.0. Might one of those be problem?

**Comment by cjb900** [comment]
you can try and find drivers that might make this card work. But there are other factors with using internal wifi cards that make is not ideal for wifi hacking such as not having an antenna and having limited range for deauthing and creating an AP. the issue with pyrit is not anything that would cause the issues you are having as its all with the card you currently are using

**Comment by strasharo** [comment]
Try switching between mdk3 and mdk4 for deauth.
