### ISSUE TITLE
Fluxion not working on usb persistence, kali linux

### ISSUE THREAD

**Issue by pseudoyeyo** [FluxionNetwork/fluxion#925]
Fluxion was working on my laptop when I had kali in dual boot mode.
I thought of trying usb persistence as I loved the concept. So covid-19 quarantine was the best time to try it. So I created bootable usb with kali. Most of the programs were working.
When I tried to use fluxion scanner it wouldn't show anything.
Is the problem with the usb persistence or with fluxion?

**Comment by deltaxflux** [comment]
You should fill out the issue template.
