### ISSUE TITLE
Network not showing up

### ISSUE THREAD

**Issue by shizzlepizzle** [FluxionNetwork/fluxion#926]
Hi guys,
Something really weird is happening.. I would like to try and hack a really close access point with fluxion, but It just doesn't show up in the Fluxion scanner.. It's right there when I use airodump or wash, and I was able to get a perfect handshake with airodump + aireplay, but for some reason it doesn't show up in the Fluxion Scanner..
Any ideas?

Thx in advance!
Chris

**Comment by adrastee** [comment]
HI,
Same issue here.
Using Kali and Fluxion lastest versions.

`iwlist wlan0 s`
 shows around 30 ESSIDs
Then I launch FLuxion and fluxion scanner, nothing appear : 0 network.
How to fix this?
Thanks.

**Comment by shizzlepizzle** [comment]
similar, but fluxion does show all other AP's in my case... just not the one that I need.. :)

**Comment by ch4m30** [comment]
This is probably a redundant question, but are you scanning the right frequency? Anytime I cannot find the AP I need it has been because Iǘe selected an incorrect option.

**Comment by strasharo** [comment]
Let me pull up the crystal ball and guess your setup.

**Comment by shizzlepizzle** [comment]
f

**Comment by deltaxflux** [comment]
If you  don't fill out the issue template. It is hard to help you :)
