### ISSUE TITLE
Does not work through RDP ?

### ISSUE THREAD

**Issue by adrastee** [FluxionNetwork/fluxion#927]
|    Q        |   A
|------------ | -----
| Version     | 6 rev 8

#### Support Question
I am connecting to Kali (uptodate) through RDP, but Fluxion exits with xterm issue : "xterm test session failed"
Is there a way to enable xterm through RDP ?
Thanks.

#### FLUXION Info
FLUXION V6.8

#### BASH Info 
GNU bash, version 5.0.16(1)-release (aarch64-unknown-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan1) Info 
**Device**: phy0
**Driver:** mt7601u
**Chipset:** Edimax Technology Co., Ltd 
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

**Comment by deltaxflux** [comment]
Fluxion require a (graphical) X session.
