### ISSUE TITLE
target tracker failed to unprep attack

### ISSUE THREAD

**Issue by danny69420** [FluxionNetwork/fluxion#929]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question
After I have captured the handshake and on the ssl certificate to finally get the password, I am greeted with a message "target tracker failed to unprep attack". I am not sure what I did wrong

#### Specs
Fluxion 6.9

**Comment by cjb900** [comment]
You do not need target tracking. It is only used if when deauthing an AP you get notice the channel its on is different than the one you are deauthing on. then you would need target tracking and you would need a separate wifi adapter to use it

**Comment by danny69420** [comment]
How do I disable it?
