### ISSUE TITLE
AP function is currently broken

### ISSUE THREAD

**Issue by deltaxflux** [FluxionNetwork/fluxion#93]
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

### What is the current behaviour?
-> *Acess point interface doesn't get generated

#### If the current behaviour is a bug, please provide the steps to reproduce.
Sample output while running fluxion
```
sudo airmon-ng                           (08-19 11:38)

PHY	Interface	Driver		Chipset

phy0	wlp0s26u1u5	rt2800usb	Ralink Technology, Corp. RT2870/RT3070

```
#### What is the expected behaviour?
-> Interface wlp0s26u1u5FLXap should get generated

#### Wireless adapter:
*Exact model, chipset, and driver versions.*
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT2870/RT3070
#### Does it support injection?
*Paste the output of `aireplay-ng -9`*
It does.

#### Fluxion version:
*Paste the output of* `cat fluxion.sh | grep revision`
3
#### Linux version:
*Paste the output of* `cat /proc/version` or `uname -r` 
4.12.5-1-ARCH

**It will take a look what causes the bug.**

**Comment by MPX4132** [comment]
Hmm, try running it with the airmon-ng flag to see if that fixes it:
```
export FLUXIONAirmonNG=1; ./fluxion.sh
```

**Comment by SiNaPsEr0x** [comment]
I resolve to buy atheros 9271 chip becouse rt28** dont have a AP mode and with airmon have a problem.. but with alfa awsus036nha runnly correctly!

**Comment by MPX4132** [comment]
Seriously, every time we've got an issue you can almost guarantee there's a "Ralink Technology" chipset involved. I've been testing things with a small WNA1100, which uses the same driver and chipset as the AWUS036NHA (ath9k_htc, Atheros AR9271). Sometimes I use the built in one, which uses the ath9k driver and has an Atheros AR9485 chipset. They always work flawlessly... Ralink should learn a thing or two.

**Comment by MPX4132** [comment]
Actually, I should get one of those notorious chipsets to test with. I wouldn't have to keep asking people to give me diagnostic info.

**Comment by deltaxflux** [comment]
Broke after the last merge of the other branch. 

> same problem on 
Duplicate of #92 

Well, this is more or less a memory for me.

**Comment by MPX4132** [comment]
Oh, I think I got it. Not 100% sure, but it seems like the interface identifier is too long... wlp0s26u1u5FLXap isn't a valid parameter (error -22)...

**Comment by MPX4132** [comment]
Pull the latest commit and check it it's been resolved. I'm using a temporary interface naming scheme.

**Comment by deltaxflux** [comment]
Does work as expected thanks for fixing.
