### ISSUE TITLE
Fake Ap is mega Slow / unreachable 

### ISSUE THREAD

**Issue by nedom123** [FluxionNetwork/fluxion#930]
Hey all ,
After the successed handshake, putting the fake ap on it seems really slow i cant even really connect.. After a few trys the fake login page opens but dont realy loads.. i noticed that the targeting host is sometimes available again and my fake ap disappears and comes up again..
Tried also as hostapd 
Did the same procedure 2 years ago on the same notebook all worked fine...

Got kali linux 2020 + fluxion 6.8
Network adapter : atheros ar9285 wireless 

Sorry for my bad english btw

**Comment by nedom123** [comment]
What is this for a bad Support ? Even not 1 reply and it got closed ? Nice one ..

**Comment by nedom123** [comment]
I thought this section is there for support help beginners etc..

**Comment by bruvv** [comment]
Perhapse because you didnt read the issue template?

**Comment by nedom123** [comment]
Which issue tenplate i‘m new in here sorry if i broke the rules but i just wanted to get my problem solved.. but okay i gotta clear it up myself

**Comment by bruvv** [comment]
it's the text you deleted before making this 'issue'...

**Comment by nedom123** [comment]
Cant i just get some support :D
