### ISSUE TITLE
Add Non Graphical Mode & WSL support.

### ISSUE THREAD

**Issue by HerendraTJ** [FluxionNetwork/fluxion#94]
Plz add Non graphical mode.Add support for WSL (Windows Subsystem for Linux)

**Comment by MPX4132** [comment]
I don't think this is possible due to a ridiculous amount of reasons. You're better off using a software hypervisor with a virtual machine hosted on Windows.

**Comment by deltaxflux** [comment]
I agree with that, there is no point doing this.
