### ISSUE TITLE
Can you recommend us a "best" wireless card?

### ISSUE THREAD

**Issue by fredzhang2018** [FluxionNetwork/fluxion#949]
**Can you recommend us a "best" wireless card?
strong signal and excellent compatibility with fluxion. tks!**
some wireless card's signal is very weak, some wireless card is not compatible with fluxion in the market.

**Comment by gr01d** [comment]
It is hard to recommend "best" wireless cards, as some may look identical but may contain different chipsets. Until you buy and test it with fluxion, you may never know if it will/will not work. I had some luck with using an Atheros miniPCIe internal wifi and Ralink 3070 chipset (but they s*ck at deauth).

**Comment by cjb900** [comment]
Here is a list of known cards and chipsets that work with fluxion. I can't say which ones in this list are the best but i personally have the panda pau09 and an off brand card with a RT3070 and both work great with no issues. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)
