### ISSUE TITLE
Add Sites to default git pull

### ISSUE THREAD

**Issue by SiNaPsEr0x** [FluxionNetwork/fluxion#95]
please @deltaxflux add auto download for fix error on hostapd

**Comment by MPX4132** [comment]
Oh, if you're using git, just do
```
git clone --recursive git@github.com:FluxionNetwork/fluxion.git
```

**Comment by SiNaPsEr0x** [comment]
thanks soo much

**Comment by SiNaPsEr0x** [comment]
for git pull the command is git pull --recurse-submodules @MPX4132 ??

**Comment by MPX4132** [comment]
Sorry for the delay, I had to feed my pets. Yeah, that should do it.

**Comment by deltaxflux** [comment]
I also change the readme. Sites should get their own repository so it is easier to handle.
