### ISSUE TITLE
fluxion cannot detect installed software

### ISSUE THREAD

**Issue by marcosrmjr** [FluxionNetwork/fluxion#950]
fluxion cannot detect installed software
![Anotação 2020-07-21 233152](https://user-images.githubusercontent.com/22861429/88127667-a452f380-cbaa-11ea-96ee-d158f6ababd5.png)

**Comment by cjb900** [comment]
looks like you are using kali linux which by default does not have these dependencies installed so they need to be installed. you can run ```sudo ./fluxion.sh -i``` to install them

**Comment by marcosrmjr** [comment]
I already did it, and it didn't work, it still doesn't install, I'll try another distribution to see if it works

**Comment by cjb900** [comment]
ya that would indicate that either something is wrong with your installation if Kali or that you need to fix your sources.list to fix being able to install packages in Kali

**Comment by marcosrmjr** [comment]
doesnt work :/ 
![image](https://user-images.githubusercontent.com/22861429/88129763-41b02680-cbaf-11ea-8a0a-b019864ecfac.png)
![image](https://user-images.githubusercontent.com/22861429/88129797-5d1b3180-cbaf-11ea-9c6e-f3394cb4d9fa.png)

**Comment by cjb900** [comment]
you may want to check your sources,list here [https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/](https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/) and then make sure that you have all the updates/upgrades in Kali then try and see if you can install the missing dependencies

**Comment by marcosrmjr** [comment]
71/5000
you will laugh at me, but the problem was the lack of use of "sudo"
