### ISSUE TITLE
No target shown for Handshake Snooper

### ISSUE THREAD

**Issue by jcxhunter123** [FluxionNetwork/fluxion#956]
After I choose option 2 there is no targets for me to choose. FYI I am using VBox for running the kali
<img width="317" alt="Screenshot 2020-08-03 at 1 22 11 PM" src="https://user-images.githubusercontent.com/24419860/89148475-8d3dd980-d58c-11ea-9fe1-ff1f35753e27.png">
)

|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by strasharo** [comment]
Let me pick up the crystal ball and guess your setup.
