### ISSUE TITLE
8187 dont   support  create ap？

### ISSUE THREAD

**Issue by a937287837** [FluxionNetwork/fluxion#958]
version 6.9，everything is ok but creat ap，it seems not good，please tell how to solve
3070 is ok ？

**Comment by xpz3** [comment]
8187 need driver patches
 Rt3070 would work

**Comment by a937287837** [comment]
Thank you for your reply，can you tell me where i can get 8187  patches driver

**Comment by cjb900** [comment]
you can get the driver from here [https://github.com/matrix/backports-rtl8187](https://github.com/matrix/backports-rtl8187). i can't say if it will work properly in what ever OS you are using because others have had issues with it in the latest version of Kali

**Comment by a937287837** [comment]
This my OS
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.2
Codename:       kali-rolling
i will try the driver from here https://github.com/matrix/backports-rtl8187.

**Comment by a937287837** [comment]
> you can get the driver from here https://github.com/matrix/backports-rtl8187. i can't say if it will work properly in what ever OS you are using because others have had issues with it in the latest version of Kali

his my OS
Distributor ID: Kali
Description: Kali GNU/Linux Rolling
Release: 2020.2
Codename: kali-rolling
i will try the driver from here https://github.com/matrix/backports-rtl8187.
