### ISSUE TITLE
Unable to launch Captive Portal or Handshake Snooper

### ISSUE THREAD

**Issue by derek540** [FluxionNetwork/fluxion#959]
#### Summary
As soon as I launch the Captive Portal or Handshake Snooper, a new terminal pops up for 1 second and instantly closes.

##### What is the current behaviour?
Captive Portal and Handshake Snooper window launches for ~1 second and automatically closes out. Unable to monitor any networks.

##### If the current behaviour is a bug, please provide the steps to reproduce it.
Pressing 1 or 2 launches a new terminal and the new terminal closes within a second.

##### What do you think the expected behaviour should be?
Fluxion should sniff traffic

##### Specs
I am unsure which specs or how to pull them (very new to Linux)

#### Expected behavior
Fluxion would sniff for APs near me and capture a handshake.

**Comment by fckyouandme** [comment]
same exact problem here.

**Comment by cjb900** [comment]
so how is anyone able to help you with out knowing any information on your setup. 

What OS are you using?
Are you using said OS in a VM?
What wifi adapter/chipset are you using?
