### ISSUE TITLE
Captive portal accept any random password

### ISSUE THREAD

**Issue by lucius100** [FluxionNetwork/fluxion#960]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x

#### Support Question

The last time I tried fluxion it worked flawlessly, I forget which version I used that time.
But now, I got some problem when trying to use captive portal.
After I got handshake and setup a portal, if the victim entered any random password, the portal will accept it, said success and closed itself. On the terminal side, it shows key not found. 

#### Specs

I tried v 4.1 and 6.9, same results. Using kali linux 2020 2a

**Comment by pdqk** [comment]
Same issue!
If ( input == correct password ) => wrong password
If ( input == something else is random ) => right and saved

Another one, my deauth did not work when fakeap was running.
Sorry about my English.

**Comment by pdqk** [comment]
> Q	A
> Version	4.10.x
> #### Support Question
> The last time I tried fluxion it worked flawlessly, I forget which version I used that time.
> But now, I got some problem when trying to use captive portal.
> After I got handshake and setup a portal, if the victim entered any random password, the portal will accept it, said success and closed itself. On the terminal side, it shows key not found.
> 
> #### Specs
> I tried v 4.1 and 6.9, same results. Using kali linux 2020 2a



> Q	A
> Version	4.10.x
> #### Support Question
> The last time I tried fluxion it worked flawlessly, I forget which version I used that time.
> But now, I got some problem when trying to use captive portal.
> After I got handshake and setup a portal, if the victim entered any random password, the portal will accept it, said success and closed itself. On the terminal side, it shows key not found.
> 
> #### Specs
> I tried v 4.1 and 6.9, same results. Using kali linux 2020 2a

Same issue!
If ( input == correct password ) => wrong password
If ( input == something else is random ) => right and saved

Another one, my deauth did not work when fakeap was running.
Sorry about my English.

**Comment by xpz3** [comment]
git clone https://github.com/FluxionNetwork/fluxion -b 5b0ef2bc914d24e104b248412cee056f739285ee
Clone this tree or remove the last commit

**Comment by deltaxflux** [comment]
Does this appear after the latest commit (pull request)?

**Comment by xpz3** [comment]
Yes

**Comment by deltaxflux** [comment]
I remove the pull request. Problem should be fixed.

**Comment by abdullah0168** [comment]
Hello.
The same problem is happening for me.
im using ubuntu 20.04

If ( input == correct password ) => wrong password
If ( input == something else is random ) => correct and saved

sorry for my bad english & please help me.
