### ISSUE TITLE
raspberry pi4 4GB monitor/manage mode issue

### ISSUE THREAD

**Issue by vaniaamad** [FluxionNetwork/fluxion#966]
i have raspberry pi 4 4GB , having built in wifi chip ,downloaded kali linux 2020.3a nexmon 64 bit image from www.kali.org . downloaded tool fluxion from github.com for evil twin attack & when i try to put the wifi in monitor/manage mode, it doesnt work , although i have checked that the on board chip supports monitor & managed mode with packed injection. as tools like fern wifi cracker , aircrack they are good to go in both modes.

any help will be highly appreciated as i couldn't find the solution after 3 days of googling & pasting my issue on the official kali community support & got no luck.

i even posted the issue on unix&linux but they say to contact the tool authors.

please help to resolve this issue as why isn't monitor/managed mode working in fluxion for the onboard wifi chip on raspberry pi4 4GB. I have used this tool for many years & never had issue with it on laptop.

**Comment by strasharo** [comment]
Broadcom is not supported, get a proper adapter.
