### ISSUE TITLE
Jammer not working while Evil Twin Attack

### ISSUE THREAD

**Issue by ErcouldnT** [FluxionNetwork/fluxion#969]
#### Summary
Jammer not working while Evil Twin Attack

##### What is the current behaviour?
Deauth process stopped and closing immediately.

#### How to reproduce
Every single time.

##### If the current behaviour is a bug, please provide the steps to reproduce it.
I dont know.

##### What do you think the expected behaviour should be?
Deauth process should work for hacking.

##### If this is a feature request, what is the motivation or use case for the added feature?
No.

##### Specs
No such file.

#### Expected behavior
WORKING.

**Comment by cjb900** [comment]
well what are we supposed to do just guess your setup. What OS are you using? What Wifi adapter/chipset are you using? Are you running said OS in a VM or on hardware? Have you tried deauthign out side of fluxion and if so does it work or not?

**Comment by ErcouldnT** [comment]
Sorry mate, you are abso-right. Kali Linux latest Live version, so im using USB-OS. Intel AC 3165 adapter/chipset. OS on hardware but USB-Live version. Fluxion handshake process is succesfull, no problem while deauth process. BUT in ET-attack section, deauth process not working. I tried manually activating aircrack-ng but im not sure it's working or not. Thanks for helping me.

**Comment by cjb900** [comment]
If you are using the built in wifi adapter in your computer that is most likely the issue. Built in wifi adapters are notorious for not working properly for wifi hacking. You would be better off getting a dedicated USB wifi adapter that is known to work for wifi hacking. like one of these. 
Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
QCA9565/AR9565
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by ErcouldnT** [comment]
My laptop is Lenovo v330-15ikb. I don't know is it built-in or not? Is it, sir ?

**Comment by ErcouldnT** [comment]
I just don't understand that its working while capturing handshakes...

**Comment by cjb900** [comment]
if you don't have a external USB wifi adapter then you are using the wifi card built into the laptop. which are notorious for not working properly for wifi hacking. Just because it works for getting the handshake doesn't mean it will work for other portions of wifi hacking. the only thing anyone can suggest is to get an external US wifi adapter/chipset that is known to properly work for wifi hacking like one of the ones i mentioned before

**Comment by ErcouldnT** [comment]
Sir, Can I use my Android mobile to send deauth packages ? Fluxion AP is working properly, All I need is just deauth process?

**Comment by cjb900** [comment]
not very easily. You would need an android phone that is rooted, supports OTG and you would still need a USB wifi adapter. You can't deauth with the built in wifi adapter in an android phone. So the bottom line is you will still need to get a USB wifi adapter if you were to use your phone
