### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by attilius743** [FluxionNetwork/fluxion#974]
Dear developer,
thanks for your work.
I installed Kali linux 2019.4 as you suggest, but I launch it from usb live persistence. Could it be a problem?
Because when I install fluxion with ./fluxion.sh -i 
it doesn't install dhcp. It returns "Unable to locate package dhcp".
Then if I try to install with apt-get install isc-dhcp-server or similar commands, it returns that there is a dependecy problem with kernel headers.
I tryed to add other repositories in source.list and do apt-get update, but nothing...
Someone can help me?

**Comment by strasharo** [comment]
If there's a dependency problem it can't be resolved by fluxion.
