### ISSUE TITLE
error when starting Captive Portal Interface

### ISSUE THREAD

**Issue by tomasaquiles** [FluxionNetwork/fluxion#978]
I've already captured the handshake but when I try to run the captive portal I can't complete the process. After choosing a captive portal interface from those available in the list I see the following error:

[*] Starting Captive Portal access point service ...
Warning: Tried to connect to session manager, Authentication Rejected, reason: None of the authentication protocols specified are supported and host-based authentication failed

I tried to look for something about it but I couldn't find a solution. Any solution?

My kali is 2020.3 and fluxion 6.9.

**Comment by cjb900** [comment]
This is usually caused by a wifi adapter that does not support VIF or AP mode. do you know what wifi adapter/chipset you have?

**Comment by tomasaquiles** [comment]
i have two adapters:
tplink tl-wn722N with chipset Atheros AR9271
Kasens G9000 with chipset Realtek RTL8187

same problem for both

**Comment by strasharo** [comment]
![image](https://user-images.githubusercontent.com/3337997/97215294-ed7b9a80-17cc-11eb-899a-ac17634de4db.png)
