### ISSUE TITLE
cat: /tmp/fluxspace/clients.txt no such file or directory

### ISSUE THREAD

**Issue by Herossandro** [FluxionNetwork/fluxion#979]
I was testing on my laptop (Not VM) and after capturing the handshake, I had to create the AP.
When a client connects to wifi fluxion say the error up here

I tried to chmod -R 777 fluxspace/ in tmp folder 
I tried to modify the permision on the creation of files (so the future files created can be written)
I tried to update
I tried to upgrade
I tried to reboot
I tried to reinstall Parrot OS (Last thing I did)
I tried to reinstall fluxion

Parrot OS

**Comment by strasharo** [comment]
![image](https://user-images.githubusercontent.com/3337997/97215233-da68ca80-17cc-11eb-8015-8745c8b8d35d.png)
