### ISSUE TITLE
Helppp? im having a problem with fluxion!!! Everything starts beautiful, even the Fake AP... but when you connect devices to fake AP, Captive portal doesn’t show on the device (phishing page)!

### ISSUE THREAD

**Issue by CyberFreak420** [FluxionNetwork/fluxion#982]
Please help! i can provide screenshots! let me know!Im a newbie btw

Im using fluxion 6.9 btw....

|    Q        |   A
|------------ | -----
| Version     | 4.10.x

**Comment by cjb900** [comment]
So what are we just supposed to use a crystal ball to guess your setup??

**Comment by CyberFreak420** [comment]
> So what are we just supposed to use a crystal ball to guess your setup??

as i said! im a newbie! lol What do you want to know about the setup? 

Kali linux 2020.3
Fluxion version: 6.9

Wifi adapter: ALFA AWUS036NEH 
Chipset: Ralink (Mediatek) RT2870/RT3070


Let me know what else you need? really need some help bro! 

![image](https://user-images.githubusercontent.com/70420266/98456937-d717fc00-2147-11eb-8ad0-03ef4863858d.jpeg)

**Comment by cjb900** [comment]
I have an adapter with that same chipset and have not had issues using fluxion. You could try running "airmon-ng check kill" brfore running fluxion and see if that helps. Also as a side note wifi hacking in a VM is known to be problematic. So it could be that which is causing your issues. If you can't get it to work I would try either dual booting or run kali from a USB and see if it works there

**Comment by CyberFreak420** [comment]
> I have an adapter with that same chipset and have not had issues using fluxion. You could try running "airmon-ng check kill" brfore running fluxion and see if that helps. Also as a side note wifi hacking in a VM is known to be problematic. So it could be that which is causing your issues. If you can't get it to work I would try either dual booting or run kali from a USB and see if it works there 

Thanks you bro! appreciate the help! Didn't really know what was the issue, but that fixed it! Now when i log in to fake AP from my Iphone the portal shows up! issue SOLVED!
