### ISSUE TITLE
[FEATURE REQUEST]Nexmon NetHunter 

### ISSUE THREAD

**Issue by TRKARTAL** [FluxionNetwork/fluxion#983]
### Feature Request

Hello dear Fluxion community.
You know, there is a Nexmon project for patching Broadcom wlan0 drivers to monitor mode and injectons..
I patched for my device and installed NetHunter kernel and chroot so i can start wlan0 monitor mode and  running injections successfully.
![sketch-1604961487377](https://user-images.githubusercontent.com/52033039/98604828-77f7ea00-22f5-11eb-88d4-dc8950328aa0.png)
![sketch-1604961493148](https://user-images.githubusercontent.com/52033039/98604850-80502500-22f5-11eb-9111-a5b06efb8715.png)
![sketch-1604961498280](https://user-images.githubusercontent.com/52033039/98604862-85ad6f80-22f5-11eb-8377-de1fa1ffd491.png)
![sketch-1604961504138](https://user-images.githubusercontent.com/52033039/98604874-8c3be700-22f5-11eb-9ca2-7604f6e15aa9.png)

Also there is a GUI for NetHunter...
![Screenshot_20201110-014407](https://user-images.githubusercontent.com/52033039/98605422-74189780-22f6-11eb-9f8f-21cdeb700705.png)
![Screenshot_20201110-014424](https://user-images.githubusercontent.com/52033039/98605432-7975e200-22f6-11eb-92ba-e5877b2839fe.png)

so, what you say about edit script for nexmon ?

**Comment by strasharo** [comment]
No.
