### ISSUE TITLE
Captive portal attack "handle_prob_req : send failed " after few minutes

### ISSUE THREAD

**Issue by Nazerr** [FluxionNetwork/fluxion#984]
#### Summary

When i launch an captive portal attack, after getting a handshake, the whole fluxion system is down after 5-10 minutes.
Everything work fine before that. AP is up, i can connect, have an IP and see the captive portal on my phone

##### What is the current behaviour?

It seems that the problem come from hostapd window.
The problem appear when hostapd disable interface and try to re-enable it.
After that, i can't connect to the AP but it is still visible

![Capture d’écran_2020-11-22_16-22-59](https://user-images.githubusercontent.com/63106546/100148757-77d31f00-2e9d-11eb-8c50-ea6f3d268353.png)

##### If the current behaviour is a bug, please provide the steps to reproduce it.

Just launch a captive portal attack, the problem happen every time so i can reproduce it easily

##### What do you think the expected behaviour should be?

I think the AP should stay up a little bit longer ;)

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

#### FLUXION Info
FLUXION V6.9

#### BASH Info 
GNU bash, version 5.1.0(1)-rc2 (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>

Ceci est un logiciel libre ; vous être libre de le modifier et de le redistribuer.
AUCUNE GARANTIE n'est fournie, dans les limites permises par la loi.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k_htc
**Chipset:** Qualcomm Atheros Communications AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(361)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.

#### System Info
**Chipset:** Linux version 5.9.0-kali2-amd64 (devel@kali.org) (gcc-10 (Debian 10.2.0-16) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35.1) #1 SMP Debian 5.9.6-1kali1 (2020-11-11)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

Sorry if i'm opening something that already being solved, can't find anything on that exact issue :(

Have a good day

**Comment by strasharo** [comment]
All looks good on the fluxion side, it appears the driver is crashing at some point. Could you, please, try running on a different distro like Parrot or switching the adapter instead?

**Comment by Zayonx-0** [comment]
Exact same issue running freshly installed latest version of Kali Linux, i'm using an awus036nh, Chipset : RT3070
Any idea of what could be wrong, what I can do / change to make it work properly ?

**Comment by cjb900** [comment]
I have an adapter with an RT3070 that works with no issues. You could try running ```airmon-ng check kill``` before starting fluxion and see if that helps with your issue.

**Comment by Zayonx-0** [comment]
I ran `airmon-ng check kill` which killed a process (i don't remember which) before starting fluxion, and it seems to have solved my issue. Thanks @cjb900 !
