### ISSUE TITLE
fluxwl0 and wlan0mon

### ISSUE THREAD

**Issue by slagsleutel** [FluxionNetwork/fluxion#986]
i had installed everything
started it with ./fluxion.sh and choose handshake . No AP appears in the screen
open another trminal and started airodump-ng wlan0mon, no such device
ctrl-C  fluxion and airmon-ng start wlan0
then started ./fluxion.sh and it search AP 2.4 and 5 Ghz.

why must the card be in wlan0mon mode to start fluxion.

Intel wireless 7265

**Comment by cjb900** [comment]
You should not need to put a wifi adapter into monitor mode before starting fluxion. You may be better off getting a USB wifi adapter as internal wifi adapters are known to be problematic for wifi hacking

**Comment by slagsleutel** [comment]
at the moment i havenot one. I noticed that after i close Fluxion there is wlan0monmon
But after ...
airmon-ng start wlan0  cd fluxion  ./fluxion.sh
5./ English  2./ Handshake Snooper  1./ Alle channels 2.4
stop the search ctrl-C
choosing an AP 
select a wireless interface and there are 4 options
1 wlan0mon [*] intel corp wireless 7265 rev 59
2 Skip
3 Repeat
4 Back
I choose 1./
2./ Reset Attack
3./ mdk4
2./ cowpatty
1./ every 30
1./ Asynchro
3 terminals open and after a while 2 away and one says a vald hash detected
menu says ....hadshake snooper in progress.......
and you can choose 1- selct another attack or 2 exit.
if you choose 1- it goes back to the begin again
is this all ?

**Comment by cjb900** [comment]
Well as I mentioned before you should not need to put your adapter in to monitor mode before starting fluxion. I have not needed to do that with any of my adapters. So if you have to do that to do that and are still having issues with fluxion it is probably an issue with your adapter.

**Comment by slagsleutel** [comment]
if i uses aircrack-ng i didnot needed an extrernal adapter.

: airmon-ng start wlan0
: airodump-ng wlan0mon
choose the target AP
choose client
: airodump-ng -c 11 --bssid 11:22:33:44:55:66 -w dump wlan0mon
alt-ctrl-T
: aireplay-ng -0 0 -a 11:22:33:44:55:66 wlan0mon
wait handshake in terminal with handshake
ctrl C
: aircrack-ng -w rockyou.txt  dump-01.cap

Used on my own AP with a small -w file.txt with dump-01.cap I found teh password.

Well i will not stop trying Fluxion
thanks

**Comment by cjb900** [comment]
Well all I can say is that many have had issues using internal wifi adapters for wifi hacking. So just because everything works out side of fluxion does not guarantee that it will work in fluxion. Fluxion uses a lot of different dependencies verses doing it manually. If you can't get fluxion to work you can always try airgeddon and see if that works for you

**Comment by slagsleutel** [comment]
external wifi adaptor i will order untill then i try airgeddon
btw 5 ghz scanning by fluxion is ok. Do you know wich command they use
