### ISSUE TITLE
Unable to launch Captive portal attack

### ISSUE THREAD

**Issue by TAOcroatia** [FluxionNetwork/fluxion#987]
#### Summary

Launching "Captive portal" attack halts(shows a blinking cursor) the script right after picking the captive portal interface or outputs text below and halts. CTRL + C to exit the script doesn't work, only CTRL + Z

`Cannot find device "fluxwl0v"`
`Cannot find device "fluxwl0v"`
`[*] Starting Captive Portal access point service...`

##### What is the current behaviour?

Script shows blinking cursor right before starting Captive Portal attack.

#### How to reproduce

1. Type sudo ./fluxion.sh in the terminal and press enter
2. Pick Captive Portal
3. Pick All Channels (2.4Ghz)
4. CTRL + C and pick my network
5. Pick Skip
6. Pick Reset attack
7. Pick my adapter `[3] wlx00c0caa55ded [*] Ralink Technology, Corp. RT2870/RT3070 `
8. Pick mdk4
9. Pick Rouge AP - hostapd
10. Pick hash - Cowpatty
11. Pick Use hash found
12. Pick Cowpatty verification
13. Pick None (disable ssl)
14. Pick disconnected
15. Pick Generic Portal        English

![Screen Capture_deepin-terminal_20201129223108](https://user-images.githubusercontent.com/34100820/100554230-95382c80-3293-11eb-94aa-1ec14b1c277c.png)

##### What do you think the expected behaviour should be?

Captive Portal attack should be launched. Multiple windows should appear.

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V6.9

#### BASH Info 
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlx00c0caa55ded) Info 
**Device**: phy21
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(344)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.8-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info
EXIT
  Aircrack-ng 1.5.2  - (C) 2006-2018 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
**Scapy Version:** 2.4.0
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                       

#### System Info
**Chipset:** Linux version 5.3.0-3-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP deepin 5.3.15-6apricot (2020-04-13)

#### Chipset
Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information
tao_croatia@ryzenator:~/fluxion$ 

#### Expected behavior

Captive Portal attack should be launched. Multiple windows should appear.

**Comment by Markw27348** [comment]
I also have this same issue

**Comment by desegura** [comment]
Same here with 88XXau + rtl88x2bu

All up to date and tried all possible combinations exchanging:
- Interface for target tracking
- Interface for jamming
- Interface for AP
- Captive portal

**Comment by cjb900** [comment]
@TAOcroatia Your issue may be due to not having a consistent wireless interface name like wlan0/wlan1. I would get your wireless interface to be wlan0/wlan1 and see if that helps. you can try running this and see if this helps reset your interface ``` ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules``` If not you can try running ```airmon-ng check kill``` before running fluxion. 

@Markw27348 with out knowing what OS and wifi adapter/chipset you are running there is no to know where your issue is. 

@desegura Those chipsets are known to not support VIF. So you might be able to use both of them in fluxion and get it to work but there is no guarantee since RTL chipsets are notoriously problematic for wifi hacking. You can try and run ```airmon-ng check kill``` before running fluxion and see if that helps. Other wise you may have to get another wifi adapter that is known to work with fluxion

here is a list if adapters/chipsets that are known to work with fluxion 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
QCA9565/AR9565
Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by Markw27348** [comment]
> @TAOcroatia Your issue may be due to not having a consistent wireless interface name like wlan0/wlan1. I would get your wireless interface to be wlan0/wlan1 and see if that helps. you can try running this and see if this helps reset your interface ` ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules` If not you can try running `airmon-ng check kill` before running fluxion.
> 
> @Markw27348 with out knowing what OS and wifi adapter/chipset you are running there is no to know where your issue is.
> 
> @desegura Those chipsets are known to not support VIF. So you might be able to use both of them in fluxion and get it to work but there is no guarantee since RTL chipsets are notoriously problematic for wifi hacking. You can try and run `airmon-ng check kill` before running fluxion and see if that helps. Other wise you may have to get another wifi adapter that is known to work with fluxion
> 
> here is a list if adapters/chipsets that are known to work with fluxion
> 
> Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
> Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
> Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
> Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
> Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
> QCA9565/AR9565
> Ralink RT5572 <- present in Panda PAU09 (2.4Ghz/5Ghz - USB)
> Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

Kali 2020.4 with the awus036nh

**Comment by cjb900** [comment]
@Markw27348 that adapter and OS should work. If you are running kali in a VM that is known to be problematic for wifi hacking and would be recommended to run on hardware. Whether you are running in a VM or not you can try running ```sudo airmon-ng check kill``` and see if that helps or not.

**Comment by Markw27348** [comment]
> @Markw27348 that adapter and OS should work. If you are running kali in a VM that is known to be problematic for wifi hacking and would be recommended to run on hardware. Whether you are running in a VM or not you can try running `sudo airmon-ng check kill` and see if that helps or not.

Have ran with a check kill. Not in a VM. Thanks for suggestions though

**Comment by desegura** [comment]
This issue is related with some kali update, I was able to run it with my 8814au one month ago but now no way.

@cjb900 is there any flag we can run with ./fluxion.sh to debug the error when trying to up the captive portal?

**Comment by cjb900** [comment]
@desegura if it worked before and now won't than that would indicate that something somewhere changed. I don't have any adapters with those chipset so I can't say what would have changed. You can look here for debugging options in fluxion [https://github.com/FluxionNetwork/fluxion/wiki/Flags-&-Preferences](https://github.com/FluxionNetwork/fluxion/wiki/Flags-&-Preferences)

**Comment by deltaxflux** [comment]
I took a quick _lookup_ and it seems that this chipset has problems in **AP-Mode.**
You can also read [here](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!).
