### ISSUE TITLE
Captive portal error

### ISSUE THREAD

**Issue by Dylan433447** [FluxionNetwork/fluxion#991]
i get this error   already done   apt-update & apt-get upgrade    ,    latest Kali version 2020.4  
all required tools installed                                            the  portal run fine for  5 mins then it gives this error after 5 minutes and no longer works why ??????

**Comment by deltaxflux** [comment]
Seems like a driver issue. Can you please provide more information?

**Comment by deltaxflux** [comment]
I remove your screenshots since they contain sensitive information. Please do not share any screenshots which contain information like

- BSSID

- ESSSID

Thank you.

Regards,
deltax

**Comment by Dylan433447** [comment]
Okay i fixed the problem using sudo airmon-ng check kill
