### ISSUE TITLE
AUTO RE-DIRECT

### ISSUE THREAD

**Issue by Dylan433447** [FluxionNetwork/fluxion#992]
I run fluxion normally , i run sudo airmon-ng check kill then ... then i grab handshake of "X" NETWORK   THEN I RUN CAPTIVE PORTAL ATTACK ,, I CHOOSE RECOMMENED CHOICES AND NO SSL CERTIFICATE , THE PROBLEM IS  .....   WHY IT KEEPS DISCONNECTING WIHOUT REDIRECTING KICKED DEVICES IT ONLY DISCONNECT NO REDIRECTION TO THE FAKE AP WHY ????
KEEP IN MIND : IM RUNNINH KALI 2020.4 DUAL BOOT WITH UPDATED TOOLS AND ALL REQUIREMENTS INSTALLED FOR THE APP I JUST WANNA KNOW WHY IT DOESNT REDIRECT ?? TO THE FAKE AP

**Comment by cjb900** [comment]
automatically redirecting to the fake AP Is not possible. The real network has password and the fake network is an open network. Its not possible to force the victim to connect to the fake network. The configuration is different between the networks. There will always be a social engineering factor in evil twin attacks.
