### ISSUE TITLE
Portal hostname not resolved intermittently but frequently

### ISSUE THREAD

**Issue by Markw27348** [FluxionNetwork/fluxion#993]
#### Summary

When launching a captive portal, the portal works about half of the time. An error is presented, dns cannot be resolved. Going directly to 192.169.251.1 does resolve the portal sometimes, but rarely. Usually the only fix is to disconnect from the AP and reconnect, but upon first connection, the portal only works about half the time.
![Screenshot 2020-12-13 05:19:48](https://user-images.githubusercontent.com/23714476/102019170-8ba0d100-3d37-11eb-8fec-ef7afbd14bdd.png)

##### What is the current behaviour?

dns cannot be resolved intermittently. Approximately half of the time.

#### How to reproduce

creating a captive portal. with any options selected, each one was individually tested.

##### If the current behaviour is a bug, please provide the steps to reproduce it.

select interface for targetting - wlan0 (AR9271)
select all channels 2.4
ctrl+c
select SSID
Skip target tracking
reset attack
select wlan0 (AR9271) for jamming
select wlan0 (AR9271) for access point
mdk4
hostapd
cowpatty
enter in absolute path of handshake
cowpatty verification
create ssl cert
select disconnected for internet connectivity
generic portal english

Then connect to captive portal and sign in from device.
Error, dns cannot be resolved.

##### What do you think the expected behaviour should be?

Resolve the captive portal to 192.169.254.1

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V6.9

#### BASH Info 
GNU bash, version 5.1.0(1)-rc3 (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash

#### Interface (wlan0) Info 
**Device**: phy3
**Driver:** ath9k_htc
**Chipset:** Qualcomm Atheros Communications AR9271 802.11n
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(362)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.6  - (C) 2006-2020 Thomas d'Otreppe
  https://www.aircrack-ng.org

#### Pyrit Info
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key
**Scapy Version:** unknown.version
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.             

#### System Info
**Chipset:** Linux version 5.9.0-kali1-amd64 (devel@kali.org) (gcc-10 (Debian 10.2.0-15) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35.1) #1 SMP Debian 5.9.1-1kali2 (2020-10-29)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

#### Expected behavior

resolve captive portal to 192.169.254.1
![Screenshot_20201213-172204_CaptivePortalLogin](https://user-images.githubusercontent.com/23714476/102027125-c9b5e900-3d67-11eb-863e-1f2c642c0fcd.jpg)

**Comment by strasharo** [comment]
All seems good. If your mobile device is using an external DNS provider for some reason it won't work for obvious reasons.

**Comment by Markw27348** [comment]
> All seems good. If your mobile device is using an external DNS provider for some reason it won't work for obvious reasons.

It is not. It's on all clients, not just mobile.

**Comment by 1732337191** [comment]
解决了吗
