### ISSUE TITLE
Captive Portal attack not starting

### ISSUE THREAD

**Issue by harsh15044** [FluxionNetwork/fluxion#997]
on some step for captive portal attack

select a wireless interface for target tracking 

i press (2) or skip

select an interface for accesss point 

i select my wifi card (wn722n v2 or v3, put in monitor mode by custom drivers)

*Unable to start captive portal interface, returning.

is there any solution to this

**Comment by cjb900** [comment]
the chipset in that adapter is known to not work as it does not support VIF which is needed to create the fake AP and deauth at the same time. Just because you found a driver that makes that adapter support monitor mode does not mean it will work for fluxion. you are going to either have to use 2 adapters or get one that supports monitor mode, AP mode and VIF.

**Comment by harsh15044** [comment]
ok

so in the target tracking menu i should select my monitor mode enabled one and select any other cheap wifi card which even doesnot support monitor mode in the access point menu 

am i correct

**Comment by cjb900** [comment]
no that is not correct. you only need target tracking if you know for a fact that the AP you are attacking changes the channel the AP is on when you deauth it. Not all AP's do this. I normally skip that option all together my self. You would still need a second adapter if you are using the wn722n v2 or v3 or an adapter that supports monitor mode, AP mode and VIF.

**Comment by harsh15044** [comment]
ok

I googled and found out that WN722N is going to be used for jamming the clients on the original ap so they come to the fake ap created by other adapter.


so, is there any way that i can ask fluxion to not to jam the ssid and simply start the access point on my WN722N card 

i will deauth the targets myself using esp8266 deauther (https://github.com/SpacehuhnTech/esp8266_deauther)

**Comment by cjb900** [comment]
the way fluxion is designed is that it deauths and creates the fake AP at the same time there is no way i know of to just have it create the fake AP.
