### ISSUE TITLE
Fluxion Does only one part on your request!

### ISSUE THREAD

**Issue by harsh15044** [FluxionNetwork/fluxion#998]
is there any way that i can ask fluxion to not to jam the ssid and simply start the access point on my wifi card which does not support VIF.

i will deauth the targets myself using esp8266 deauther (https://github.com/SpacehuhnTech/esp8266_deauther)

**Comment by cjb900** [comment]
you just asked this question in your previous issue [997](https://github.com/FluxionNetwork/fluxion/issues/997). there is no way to have fluxion just create the fake AP with out having it deauth at the same time. to so that would require re-coding the way fluxion is designed.
