### ISSUE TITLE
Wifi Name with the special character (ñ)

### ISSUE THREAD

**Issue by rudy880719** [FluxionNetwork/fluxion#999]
Hello community, I have a problem with the Name of a WiFi, the Name content the special character ñ, the SSID is Ana Peña, when the App fake is create, is wrong because is create with the next SSID Ana Pe&?a, and as you can see, is not the same Name. Please somebody help me,

**Comment by MPX4132** [comment]
The problem at the time was that airodump-ng did not support special characters. If it still doesn’t work, that means the current version installed on the machine Fluxion is running on still does not support special characters.
